### ISSUE TITLE
No dashboard anymore

### ISSUE THREAD

**Issue by BellZaph** [siduck76/NvChad#100]
After install.sh && Packer Install
![image](https://user-images.githubusercontent.com/33688736/123530481-9d1e5900-d71c-11eb-869f-298314428ff3.png)

**Comment by siduck76** [comment]
@BellZaph yes its not loaded by default , press space + db and tell me if it shows , then I'll show how to enable it

**Comment by BellZaph** [comment]
> @BellZaph yes its not loaded by default , press space + db and tell me if it shows , then I'll show how to enable it

its ok, just read the commits
It would be nice if dashboard opens if you open no file 
![image](https://user-images.githubusercontent.com/33688736/123531186-2b4a0d80-d724-11eb-8ee4-febc7467c174.png)
and nvim . opens NerdTree

**Comment by siduck76** [comment]
@BellZaph 
![image](https://user-images.githubusercontent.com/59060246/123531224-7eba5c80-d720-11eb-9fb3-55f4ed1f4af6.png)

remove cmd table 

![image](https://user-images.githubusercontent.com/59060246/123531233-8a0d8800-d720-11eb-8041-0fb084037ef8.png)

and :PackerSync

**Comment by siduck76** [comment]
> @BellZaph
> ![image](https://user-images.githubusercontent.com/59060246/123531224-7eba5c80-d720-11eb-9fb3-55f4ed1f4af6.png) change to 1
> 
> remove cmd table
> 
> ![image](https://user-images.githubusercontent.com/59060246/123531233-8a0d8800-d720-11eb-8041-0fb084037ef8.png)
> 
> and :PackerSync

**Comment by gaetgu** [comment]
So I tried the same steps that you have listed.
1. change `0` to `1` on line 6 of `plugins/dashboard.lua`
2. comment out lines 196-202, which is the `cmd` table for `glepnir/dashboard-nvim`.
3. Run `:PackerSync`, which says that `Everything already up to date!`

Despite this, when I open a new nvim instance without specifying a file, the dashboard does not show up. Any ideas?

**Comment by G-Rowell** [comment]
@gaetgu 

Hi there,
I've just tried your steps on a clean git branch and I do get the dashboard (IE. it works fine for me).

Can you complete the following for me please?

1. Output of NVim version: run in CLI `nvim --version | head -n1`
2. Is `:checkhealth` good? `Yes/No` run in nvim `:checkhealth`, is there anything of note here?
3. Is your copy of NvChad completely up to date? `Yes/No`

Ensure you run in nvim: `:PackerSync`, then restart nvim.

Let's figure this out :)

**Comment by gaetgu** [comment]
1. `nvim --version | head -n1` -> NVIM v0.5.0-dev+1419-gf76f72a27
2. `:checkhealth` -> everything is OK
3. As of yesterday night, everything was up to date, yes.

I did all the steps as well, still no change.

One thing that I want to note, though, is that `g.dashboard_disable_at_vimenter ` is defaulting to `1` after a new installation, but it retains its `-- dashboard is disabled by default comment`. I tried changing this over to 0, but it did not do anything.

**Comment by siduck76** [comment]
> 1. `nvim --version | head -n1` -> NVIM v0.5.0-dev+1419-gf76f72a27
> 2. `:checkhealth` -> everything is OK
> 3. As of yesterday night, everything was up to date, yes.
> 
> I did all the steps as well, still no change.
> 
> One thing that I want to note, though, is that `g.dashboard_disable_at_vimenter ` is defaulting to `1` after a new installation, but it retains its `-- dashboard is disabled by default comment`. I tried changing this over to 0, but it did not do anything.

put it to 0 and remove this cmd table 

![image](https://user-images.githubusercontent.com/59060246/127241400-ec50416f-319e-4b29-bff8-b909ea9a0d9e.png)

**Comment by gaetgu** [comment]
> put it to 0 and remove this cmd table

I did that, and the dashboard shows up, but now whenever I try to execute any of the space commands on the dashboard (like `SPC f f`) I get an error like `E492: Not an editor command: Telescope find_files`

Every command shown on the dashboard throws a similar error.

**Comment by G-Rowell** [comment]
Can you run in NVim: `:PackerSync` then `:PackerCompile`

Then exit and restart NVim, try any Telescope command, such as `<SPACE> + f + f` (mapping for `:Telescope find_files`

**Comment by G-Rowell** [comment]
Often 'Not an editor command` means that the Packer plugin manager has not compiled all the plugins (probably due to a new install or smth of the like)

**Comment by gaetgu** [comment]
Thanks so much, that works! I was always running `:PackerSync`, but I never ran `:PackerCompile`, which was the issue.

**Comment by G-Rowell** [comment]
No problem :+1: 

`:PackerSync` pretty much only updates plugins,
`:PackerCompile` re-compiles new plugin settings

Glad I could help :smile:

**Comment by arbkm22** [comment]
> @BellZaph
> ![image](https://user-images.githubusercontent.com/59060246/123531224-7eba5c80-d720-11eb-9fb3-55f4ed1f4af6.png) change to 1 ( lua/dashboard.lua file)
> 
> remove cmd table
> 
> ![image](https://user-images.githubusercontent.com/59060246/123531233-8a0d8800-d720-11eb-8041-0fb084037ef8.png) (lua/pluginList.lua file)
> 
> and :PackerSync
> 
> should enable dashboard.

there's no pluginList.lua file

**Comment by siduck76** [comment]
> > @BellZaph
> > ![image](https://user-images.githubusercontent.com/59060246/123531224-7eba5c80-d720-11eb-9fb3-55f4ed1f4af6.png) change to 1 ( lua/dashboard.lua file)
> > remove cmd table
> > ![image](https://user-images.githubusercontent.com/59060246/123531233-8a0d8800-d720-11eb-8041-0fb084037ef8.png) (lua/pluginList.lua file)
> > and :PackerSync
> > should enable dashboard.
> 
> there's no pluginList.lua file

oh its lua/plugins/init.lua now

**Comment by lampardnk** [comment]
The new file for dashboard is named alpha.lua, how do i config chadrc for dashboard to show up? M.plugins.status.alpha = true doesnt work

**Comment by trystin** [comment]
@lampardnk 
> The new file for dashboard is named alpha.lua, how do i config chadrc for dashboard to show up? M.plugins.status.alpha = true doesnt work

I had the same issue. Go to plugins/init.lua and find this section of the file `
  ["goolord/alpha-nvim"] = {
    after = "base46",
    disable = false,
    config = function()
      require "plugins.configs.alpha"
    end,
  },
`
change disabled to false like it's shown here. run :PackerSync. Then reload.

**Comment by kelvynsantos** [comment]
now it is on  lua > core > default_config.lua >  nvdash = {
    load_on_startup = false,

    header = {
