### ISSUE TITLE
Default <C-i> to jump is overrided with <S-Tab> shortcut.

### ISSUE THREAD

**Issue by lkhphuc** [siduck76/NvChad#102]
In most terminal, `<C-i>` is indistinguishable from `<S-tab>` key press.
Given that in vim the most important keypresses for jumping around are `<C-i>`, `<C-o>`, I think it would be wise to not override these default keybindings.

**Comment by siduck76** [comment]
I have removed the <s-tab> keybinds related to bufferline and it wasnt getting overrided but I tried changing it <S-Tab> to <C-p> and the issue was still there :/ . I think this is bufferline's issue.

**Comment by siduck76** [comment]
@lkhphuc its <TAB> overriding that , But i dont get it. How can Tab or S-Tab override <C-i>

**Comment by lkhphuc** [comment]
https://www.reddit.com/r/vim/comments/3dauvp/i_cant_inoremap_tab_and_ci_to_different_things/ , https://stackoverflow.com/questions/26106340/map-c-i-and-tab-independently
It's how most terminal currently work, see `:h tab`.
Until this is fixed in nvim (https://github.com/neovim/neovim/issues/5916), I would try to avoid remap Tab though.
