### ISSUE TITLE
Nvim-comment is not activated without custom keybinding.

### ISSUE THREAD

**Issue by lkhphuc** [siduck76/NvChad#103]
In the new update, the nvim-comment is lazy-loaded when the comment is called. This comment is called by the custom mapping.
I'm a heavy use of the default mapping `gc` so if I don't use / delete the custom mapping `<leader>/`, the comment is not loaded and the default keybinding `gc` is not activated unless I manually type in `:CommentToggle`.
I tried to change the lazy-load activation to some other events like `BufRead`, but the default keybinding is still not activated.

**Comment by siduck76** [comment]
@lkhphuc dont change the lazy loading of nvim-comment! 

in mappings config change these lines 

![image](https://user-images.githubusercontent.com/59060246/123630673-6be47c80-d833-11eb-86d4-291a22b4e561.png)

**Comment by lkhphuc** [comment]
Yeah that's one way to fix this. But it just feel a bit redundant to have an explicit mapping again for the default mappings. Thanks.
