### ISSUE TITLE
NvChad consumes a lot of memory while opening a python file

### ISSUE THREAD

**Issue by Jasylum** [siduck76/NvChad#113]
So whenever I start a python file with NvChad it consumes more than 700+MB because of node. I am using qtile so it's necessary for me to use python. But the memory just spikes up as soon as i start a python file. Any fixes?

![2021-07-02-010808_1920x1080_scrot](https://user-images.githubusercontent.com/52153618/124133847-f6caae80-daa1-11eb-81b7-61f2135bfb26.png)

P.S : I just started the system monitor so the memory consumption is relatively low than usual 

 - Arch linux
 - Kitty
 - Neovim 0.5

**Comment by siduck76** [comment]
@Jasylum I think this depends on the lsp server and not nvchad's configurations 

nvim without any file opened

![image](https://user-images.githubusercontent.com/59060246/124135087-1b725680-daa1-11eb-962b-b53877156a69.png)

nvim with TS lsp ( for js etc)

![image](https://user-images.githubusercontent.com/59060246/124135214-3ba21580-daa1-11eb-8bbb-7d94e4d78601.png)

also I think this is due to nvim-lsp .

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/124135805-c97e0080-daa1-11eb-9fb0-aa99ec2353bd.mp4

**Comment by siduck76** [comment]
I have tested this with no plugins I think there are some heavy plugins consuming ram in the bg when we're in the insert mode maybe.

**Comment by Jasylum** [comment]
So what about the node running in the background while running a python file? And as you mentioned that lsp can be a reason, are any other lsp for python that would help?

**Comment by siduck76** [comment]
> So what about the node running in the background while running a python file? And as you mentioned that lsp can be a reason, are any other lsp for python that would help?

I dont think so , nvim without lsp running has like 39mb + . I'll check if there are some plugins causing the memory spike up.

**Comment by Jasylum** [comment]
Does your nvim startup node while opening a random python file? and if it does how much resource does it consume.

**Comment by siduck76** [comment]
> Does your nvim startup node while opening a random python file? and if it does how much resource does it consume.

yes the lsp is pyright , written in typescript . so ye heavy node stuff 

![image](https://user-images.githubusercontent.com/59060246/124144304-78720a80-daa9-11eb-8367-4f50a3e6302e.png)

**Comment by siduck76** [comment]
Also it depends on the lsp . most lsps like for web dev , python have node stuff. there are some that dont like lua lsp ( sumneko_lsp)

**Comment by ashincoder** [comment]
Yeah it is the lsp cause it is connecting with language server so it may consume memory.

**Comment by ashincoder** [comment]
I hope @Jasylum your issue is cleared and the road is yours

**Comment by jtuz** [comment]
Pyright was my first choice when I began to use NvChad settings for my Neovim, but there are a lot of issues, so I turned to use : https://github.com/python-lsp/python-lsp-server and I added this line on my fork from NvChad:  https://github.com/jtuz/NvChad/blob/1b2431f9a6ebd6b38185fb781cacc0ed2cbb4f5e/lua/nvim-lspconfig.lua#L48 , until now works like a charm

**Comment by Jasylum** [comment]
Thank you everyone for your help
