### ISSUE TITLE
Telescope is giving errors in nvchad

### ISSUE THREAD

**Issue by ashishbinu** [siduck76/NvChad#115]
**Describe the bug**
Opening telescope causes it to give errors.

**To Reproduce**
1. Run `:PackerSync` in nvim.
2. Restart nvim.
3. Open `:Telescope find_files`.

**Expected behavior**
It should open directly without showing the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/56691622/124135105-20cfa100-daa1-11eb-9720-fcdfbaf2ed2d.png)

**Desktop (please complete the following information):**
 - Operating System : Manjaro
 - Terminal : kitty 
 - Version of Neovim : v0.5.0-dev+1449-gbdf3df402

**Additional context**
This is happening because telescope has committed some breaking changes in their api.

**Comment by siduck76** [comment]
I'll update its config soon :)

**Comment by ashincoder** [comment]
Hey @siduck76 I have a created PR to solve the errors. @ashishbinu please check the update I made #116 then check if the error is solved.

**Comment by ashincoder** [comment]
Ok thank you for pointing it out @ashishbinu . Close it please :smile:
