### ISSUE TITLE
Removing `williamboman/nvim-lsp-installer` causes error in `:PackerSync`

### ISSUE THREAD

**Issue by azuwis** [siduck76/NvChad#1163]
**Describe the bug**
Removing `williamboman/nvim-lsp-installer` causes error in `:PackerSync`.

**To Reproduce**

1. `~/.config/nvim/lua/custom/chadrc.lua`:
```
local M = {}

M.plugins = {
  remove = {
    "williamboman/nvim-lsp-installer",
  },
}

return M
```
2. Run `:PackerSync` in `nvim`
3. Error:
```
[packer.nvim] [ERROR 14:36:05] async.lua:20: Error in coroutine: ...ite/...lua:592: Dependency nvim-lsp-installer for { "nvim-lspconfig" } not found
```

**Expected behavior**
NvChad should work without nvim-lsp-installer.

**Desktop (please complete the following information):**
 - Operating System: NixOS
 - Terminal: Kitty
 - Version of Neovim: 0.7.0

**Additional context**
nvim-lsp-installer does not work well on NixOS. It tries to install yamlls every time when neovim edits yaml files, even though `yamlls` exe already exists (It also check for `nodejs` in addition to `yamlls`, which is not available due to how NixOS works.).

I use package manager of NixOS to install language servers, nvim-lsp-installer is not needed, so I'd like to remove it.

**Comment by siduck** [comment]
In your M.plugins.install section : 

```lua
 ["neovim/nvim-lspconfig"] = {
      after = "gitsigns.nvim",
      config = function()
          require "plugins.configs.lspconfig"
      end,
   },
   ```
