### ISSUE TITLE
Might want to change git sign colors

### ISSUE THREAD

**Issue by m2kulkarni** [siduck76/NvChad#117]
**Describe the bug**
https://github.com/siduck76/NvChad/blob/76cdd5a29b89ea501f094424a7f5c2c096a542b5/lua/highlights.lua#L64  
assigns colors.one_bg2 to DiffChange. If I use nvim in diff mode (nvim -d) , this causes the changed line to be of the same color as the background, essentially making it invisible

**Expected behaviour**
Just assign a different color.

**Screenshots**
![image](https://user-images.githubusercontent.com/56233197/124182597-b173a480-dad4-11eb-8b86-36fd38d32788.png)

**Comment by siduck76** [comment]
@m2kulkarni NvChad uses a custom version of  onedark. so set your terminal's bg to #1e222a 

https://github.com/siduck76/NvChad/wiki/Themes#onedark

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/124209460-37104800-db07-11eb-8dc9-87c4e4ab6c64.png)

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/124223708-dfcba100-db21-11eb-9c19-43cdbefcb32d.png)

**Comment by siduck76** [comment]
@m2kulkarni your terminal bg color should be changed to #1e222a and the gitsigns would look good :) . i'll be closing this issue , feel free to reopen it if you have any issues.

**Comment by ashincoder** [comment]
Isn't the issue solved.

**Comment by ashincoder** [comment]
Isn't the issue solved.

**Comment by siduck76** [comment]
> Isn't the issue solved.

yes its solved , he's using onedark's original bg color for his terminal . since nvchad makes neovim use terminal bg so his gitsigns look hidden. All he has to do is use #1e222a for bg ;v
