### ISSUE TITLE
How to set the padding in the bufferline?

### ISSUE THREAD

**Issue by evolify** [siduck76/NvChad#119]
How to set the padding in the bufferline as the image in the Readme?

**Comment by ashincoder** [comment]
In the lua directory there is a file called top-bufferline.lua. Change the padding to your liking.

**Comment by siduck76** [comment]
> How to set the padding in the bufferline as the image in the Readme?

padding around buffers?

**Comment by evolify** [comment]
> > How to set the padding in the bufferline as the image in the Readme?
> 
> padding around buffers?

yeah, padding top of the bufferline.
![image](https://user-images.githubusercontent.com/12669069/124264844-9140f580-db67-11eb-959c-332fd7176c8a.png)

and how to get the border ?
![image](https://user-images.githubusercontent.com/12669069/124264765-7a9a9e80-db67-11eb-805f-4d9fc43562ee.png)

**Comment by siduck76** [comment]
@evolify thats not a nvchad feature! its a terminal feature . set 2 to 5 for inner padding . I set it to 0 but idk why my st build adds lil border in bspwm .

**Comment by evolify** [comment]
thank you.
