### ISSUE TITLE
`luasnip` not found

### ISSUE THREAD

**Issue by mizzunet** [siduck76/NvChad#1235]
**Describe the bug**
`luasnip  not found error shown`

**To Reproduce**
1. Intstall nvchad
2.  open nvim
3. enter insert mode
4. go back to normal mode

**Expected behavior**
Enter normal mode normally

**Screenshots**
![image](https://user-images.githubusercontent.com/10193999/174447105-b491e6aa-9b51-4820-8a00-417cf618d31f.png)

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: foot
 - Version of Neovim: neovim-nightly-bin 0.8.0+dev+441+ge651ae586-1

Hopefully it was resolved by installing `neovim-luasnip-git` package

**Comment by siduck** [comment]
can you try a clean install ?

**Comment by siduck** [comment]
very weird, i cant reproduce this at all

**Comment by siduck** [comment]
also please use 0.7v neovim

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/174478403-b6a4c85e-f0c4-495e-a8b2-22a8fce23f3b.mp4

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/174478418-a34e8597-c4eb-4f99-b9d8-127e5fecd282.png)

Do not use paq or you are gonna mess up our packer.nvim config probably and dont make changes outside the lua/custom dir

**Comment by siduck** [comment]
@mizzunet thats fzf integrated with mksh shell. There's fzf history+tab completion for bash + zsh too, search its repo
