### ISSUE TITLE
Not an editor command

### ISSUE THREAD

**Issue by AjayShanker-geek** [siduck76/NvChad#127]
**Describe the bug**
Hi vim beginner here, after installing I had to `dos2unix -f ` some files to run it without errors. When using I will get below error when I run `:Neoformat` or any other plugins.

`Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:68: Vim:E492: Not an editor command: Neoformat
Please check your config for correctness
`

**Desktop (please complete the following information):**
 - Macbook Air (M1) MacOS Big Sur
 - iTerm2
 - NVIM v0.5.0

**Comment by siduck76** [comment]
> dos2un

do :PackerSync

**Comment by Pocco81** [comment]
Open the files with all the plugins and then:
```lua
:luafile %
:PackerInstall
:PackerSync
```

Then close the file, open it again and then run `:PackerStatus`. If there is not a line that says:
```
 • neoformat
```

Then I'd recommend you reinstall [Packer.nvim](https://github.com/wbthomason/packer.nvim).

**Comment by AjayShanker-geek** [comment]
`:PackerSync`

<img width="721" alt="Screenshot 2021-07-05 at 11 40 28 AM" src="https://user-images.githubusercontent.com/26241915/124415303-2a018c00-dd87-11eb-8eac-1dbf1909b195.png">

`:PackerStatus`

<img width="721" alt="Screenshot 2021-07-05 at 11 48 46 AM" src="https://user-images.githubusercontent.com/26241915/124415365-469dc400-dd87-11eb-92a5-9bc5133cd1bf.png">

What am I doing wrong?

**Comment by siduck76** [comment]
@AjayShanker-geek is this nvchad's latest config?

**Comment by ashincoder** [comment]
@AjayShanker-geek I think it is best to delete all packer content in ~/.local/share/nvim ~/.cache/nvim ~/.config/nvim. Then reinstalling Packer.nvim manually and using NvChad or by using the NvChad install script.

**Comment by AjayShanker-geek** [comment]
Yup using the latest git clone and followed steps from [https://github.com/siduck76/NvChad/wiki#clone-my-setup](url)


`:Packerinstall`

<img width="722" alt="Screenshot 2021-07-05 at 11 13 22 AM" src="https://user-images.githubusercontent.com/26241915/124417382-98484d80-dd8b-11eb-8a62-4328158c388b.png">

I will run `dos2unix ` to fix the error

**Comment by siduck76** [comment]
@AjayShanker-geek update your neovim

**Comment by ashincoder** [comment]
Yeah maybe that will fix since [neovim](https://github.com/neovim/neovim/releases/tag/v0.5.0) released new 0.5 stable version

**Comment by AjayShanker-geek** [comment]
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/config -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/include
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

**Comment by AjayShanker-geek** [comment]
Ran `:Checkhealth`

## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /opt/homebrew/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v16.4.1
  - INFO: Nvim node.js host: /opt/homebrew/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13

**Comment by ashincoder** [comment]
Is the issue still continuing after reinstalling packer.

**Comment by AjayShanker-geek** [comment]
How do u properly reinstall packer?

 This is what I did:

`rm -rf .local/share/nvim/site/pack/packer  `

and then

`git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim`

**Comment by ashincoder** [comment]
remove all the ~/.local/nvim and ~/.cache/nvim then reinstall packer with 
`git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim`

**Comment by AjayShanker-geek** [comment]
Still facing the issue after reinstalling :( 

I will spend time on the weekends to troubleshoot.

**Comment by siduck76** [comment]
@AjayShanker-geek try using the 0.5v from the release page then.

**Comment by Pocco81** [comment]
A little bit out of topic, but just wanted to mention that I'm don't use NVChad, however, I was using a very outdated appimage and when I grabbed the now stable 0.5 two plugins stopped working. I reinstalled both and everything worked after that. I'm my case I'm currently using the build from the official Arch Linux repo.

**Comment by ashincoder** [comment]
Is this issue still happening @AjayShanker-geek

**Comment by AjayShanker-geek** [comment]
Manage to fix it by reinstalling the macOS. Manage to run this config with [Neovide](https://github.com/Kethku/neovide)
