### ISSUE TITLE
[Feature]: Create a `dev` branch to make a distinction between what is stable (main) and what is under development (dev)

### ISSUE THREAD

**Issue by Pocco81** [siduck76/NvChad#128]
**Is your feature request related to a problem? Please describe.**
Inconsistency with the way the development of the project has been carried all along.

**Describe the solution you'd like**
I'd like to have a branch named `dev` (or really any other name that you'd like) where stuff that is underdevelopment will reside. Thanks to that simple yet powerful branching strategy in case there are errors they won't be in the stable branch (main).

**Describe alternatives you've considered**
None.

**Additional context**
[This post](http://billpatrianakos.me/blog/2014/05/02/the-importance-of-having-a-git-branching-strategy/#:~:text=Branching%20in%20open%20source%20projects%20is%20important%20because%20of%20the,in%20commits%20from%20multiple%20commiters.) by Bill Patrianakos describes why it is important to have a solid and consistent branching strategy. 

**Screenshot**
Maybe a screenshot of the feature
Not needed.

**Comment by ashincoder** [comment]
@Pocco81 I mean this is a common thing among many repositories creating a dev branch and a stable main branch. But I don't know why @siduck76 has'nt started it. He may

**Comment by siduck76** [comment]
> @Pocco81 I mean this is a common thing among many repositories creating a dev branch and a stable main branch. But I don't know why @siduck76 has'nt started it. He may

nvchad's just a config , I test the config on multiple systems before pushing it on the repo.

**Comment by ashincoder** [comment]
@siduck76 it is best having a dev branch

**Comment by siduck76** [comment]
> @siduck76 it is best having a dev branch

Ik , but nvchad is just a config . I dont think anyone has a dev branch for the dotfiles! Also I test the config multiple times and on many systems before pushing to the repo . Adding a dev branch might add extra effort which might not be needed for just a config.

**Comment by ashincoder** [comment]
If there is more than 2k stars then it more than a config @siduck76

**Comment by Pocco81** [comment]
> I dont think anyone has a dev branch for the dotfiles!

Well I do...

Imo regardless of this being "just a config", you must take into consideration what @ashincoder, it's very popular with 2k starts and a lot of people depend on it/use it daily.

It's a good practice to have a distinction between what's stable and what's not, so if I was you I'd totally do it.

**Comment by siduck76** [comment]
> > I dont think anyone has a dev branch for the dotfiles!
> 
> Well I do... And when I share my dots with someone I tell them to look into main, and thus I'm 100% sure it'll work for them.
> 
> Imo regardless of this being "just a config", you must take into consideration what @ashincoder said, it's very popular with 2k starts and a lot of people depend on it/use it daily.
> 
> It's a good practice to have a distinction between what's stable and what's not, so if I was you I'd totally do it.

the releases are supposed to be stable where as the main branch is rolling release xD

**Comment by siduck76** [comment]
@Pocco81  https://github.com/siduck76/NvChad/commits/dev
