### ISSUE TITLE
"vim.opt" may be nil

### ISSUE THREAD

**Issue by tnhh00037** [siduck76/NvChad#135]
**Describe the bug**
Error when declaring local variable
```
local opt = vim.opt
```

Only can be fix by assigning
```
local opt = {}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35983840/124601576-f74cb600-dea2-11eb-9314-866af8e0636b.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu
 - Terminal: zsh
 - Version of Neovim: NVIM v0.5.0-dev+1133-g0869cbd55

**Comment by ashincoder** [comment]
can you elaborate your issue

**Comment by tnhh00037** [comment]
So currently in file `./lua/misc-utils.lua` first line
`local opt = vim.opt`

I didn't change anything and when open neovim, it shows
![image](https://user-images.githubusercontent.com/35983840/124602876-49daa200-dea4-11eb-8e02-ee695a9d9c61.png)

In other to avoid error, I have to set to `{}` (avoid nil since I think `vim.opt` is currently nil)
`local opt = {}`

**Comment by ashincoder** [comment]
Have you updated neovim to the stable 0.5 version ?
It is available in all the repositories I think.

**Comment by ashincoder** [comment]
https://github.com/neovim/neovim/releases/tag/v0.5.0

**Comment by tnhh00037** [comment]
Thank you! It works! 
Been using `init.vim` for long time, first time switching to `init.lua` and inspired by your repo.

Great work sir!
