### ISSUE TITLE
It broke my init.vim config file and vim-plug

### ISSUE THREAD

**Issue by keven-mate** [siduck76/NvChad#136]
**Describe the bug**
After removing the installed files from my .config/nvim and placing my own config file, nothing there works anymore, I thought that the plugins were removed, when I try installing them using vim-plug, nothing happens, I tried reinstalling the plugin and it still doesn't do anything.

 - Operating System:
 - Arch Linux

 - Terminal
 - Alacritty
 - Version of Neovim
 - 0.5.0

**Comment by siduck76** [comment]
you need to remove .local/share/nvim/site/pack/ to completely remove nvchad

**Comment by keven-mate** [comment]
> you need to remove .local/share/nvim/site/pack/ to completely remove nvchad

Thanks, removing it helped me.
