### ISSUE TITLE
Status Bar Disappears When Highlighting Matching Bracket

### ISSUE THREAD

**Issue by larkwiot** [siduck76/NvChad#138]
When the cursor is on an open curly brace (for example), the corresponding close curly brace is highlighted. If the close curly brace is on the line that exists under the status bar, then the status bar disappears in order to show it. This causes the status bar to appear to blink/flicker in many cases, which makes for an uncomfortable visual experience.

**To Reproduce**
1. Make or open a source file with curly braces on separate lines.
2. Scroll up/down in such a way as to position the close curly brace line underneath the status bar at the bottom of the screen. (Or such that the line immediately preceding the curly brace is the last visible line of source above the status bar.)
3. Move cursor over the open curly brace.
4. The status bar should disappear, and the source line previously underneath it should be shown so as to show the position of the corresponding close brace.

**Expected behavior**
While the automatic brace highlighting is a good and important feature, the status bar should not disappear in an effort to show the close brace. Keep the status bar visible and "on top", even if the corresponding brace is underneath the status bar.

**Desktop (please complete the following information):**
 - Void Linux
 - Kitty
 - 0.6 DEV (from master)

**Comment by larkwiot** [comment]
PS: If this is not a bug and is a "feature," then perhaps an option in the config should be exposed to toggle this behavior. I doubt I am the only one who would rather have the status bar remain always visible.

**Comment by ashincoder** [comment]
![2021-07-07-113700_216x186_scrot](https://user-images.githubusercontent.com/83629316/124708272-ae831480-df17-11eb-8bed-f6d37415666f.png)
Is this what you mean

**Comment by ashincoder** [comment]
I think it is a feature

**Comment by siduck76** [comment]
@larkwiot its a vim-matchup feature 
![image](https://user-images.githubusercontent.com/59060246/124716165-623cd200-df21-11eb-8570-f71deac3c9f7.png)


if the declaration or matchup isnt visible in your current buffer then vim-matchup shows it on the statusline 

like this 

![image](https://user-images.githubusercontent.com/59060246/124716257-800a3700-df21-11eb-853a-2e07e3da5aa8.png)

**Comment by larkwiot** [comment]
Ah okay. How may I disable that plugin?

**Comment by siduck76** [comment]
> Ah okay. How may I disable that plugin?

just remove vim-matchup from your pluginlist and :PackerClean
