### ISSUE TITLE
Lsp Servers do not install correctly 

### ISSUE THREAD

**Issue by shaunsingh** [siduck76/NvChad#141]
Hello, I'm loving the config so far. I customized it a fair bit (https://github.com/shaunsingh/vimrc-dotfiles/tree/main/.config/nvim) but I haven't changed any of the LSP stuff so I think its fine 

Installing any server though `:LspInstall language` e.g. `:LspInstall python` results in this 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/124782196-09b20880-df12-11eb-8c53-788e1f2bd326.png">

**Comment by siduck76** [comment]
you sure you're using nvim 0.5 ? and did you try :PackerSync

**Comment by shaunsingh** [comment]
I am using neovim 0.5, and I ran `:PackerSync`

I think the issue is lspconfig and lspinstall are lazy loaded, so one of the two aren't available yet.

**Comment by shaunsingh** [comment]
I can confirm removing the `event bufread` line from lspconfig's packer config resolved the issue. Testing with hyperfine, I don't notice any increase in startup time either

**Comment by siduck76** [comment]
> I can confirm removing the `event bufread` line from lspconfig's packer config resolved the issue. Testing with hyperfine, I don't notice any increase in startup time either

check :St , to display the startuptime. Im on my old pentium machine and NvChad takes like this much time to launch up

![image](https://user-images.githubusercontent.com/59060246/124795669-e74dd880-df6d-11eb-989d-46678086ce60.png)

**Comment by ashincoder** [comment]
@shaunsingh are you sure your using NvChad, cause that looks like doom-nvim

**Comment by shaunsingh** [comment]
> check :St , to display the startuptime. Im on my old pentium machine and NvChad takes like this much time to launch up

<img width="846" alt="image" src="https://user-images.githubusercontent.com/71196912/124798500-6832b300-df21-11eb-902f-5eb00601bad5.png">

> are you sure your using NvChad, cause that looks like doom-nvim

I'm using a customized version of NvChad. I replaced the dashboard and statusline with personal ones that (as you said) look kind-of like doom-nvim. The lspconfig file is still the same (https://github.com/shaunsingh/vimrc-dotfiles/blob/main/.config/nvim/lua/nvim-lspconfig.lua)

**Comment by siduck76** [comment]
are you using the latest config of nvchad?

**Comment by shaunsingh** [comment]
Yes, my config is based on https://github.com/siduck76/NvChad/commit/b16c5a2f70e632a439820869dd8abd1b48a16a4e

**Comment by siduck76** [comment]
> Yes, my config is based on [b16c5a2](https://github.com/siduck76/NvChad/commit/b16c5a2f70e632a439820869dd8abd1b48a16a4e)

weird , this doesnt happen with the configs from dev/main branch , btw can you backup your config for a file and use NvChad only config? and test whether lspconfig's working.

**Comment by shaunsingh** [comment]
it doesn't occur with the dev/main branch oddly enough. Might be something I accidentally removed from the config. thanks for the help, sorry for all the trouble!
