### ISSUE TITLE
Lsp large file

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#143]
**Describe the bug**
Lsp shows error saying 'large file size. limit is 100KB'

**To Reproduce**
1. Open lua file
2. Scroll through the file
3. It will pop up in the statusline

**Expected behavior**
Don't show the error.

**Screenshots**
![2021-07-08-192908_1341x127_scrot](https://user-images.githubusercontent.com/83629316/124935330-2e49d580-e023-11eb-9721-817c4b490d3c.png)

**Desktop (please complete the following information):**
 - Void linux
 - St
 - Stable neovim 0.5

**Comment by siduck76** [comment]
dont put lua file in home folder , put it in some dir and cd into that dir , then open that lua file and let me know,

**Comment by ashincoder** [comment]
Now it doesn't happen. It happened yesterday Now it doesn't
