### ISSUE TITLE
Wal colorscheme not working

### ISSUE THREAD

**Issue by ThatOneCalculator** [siduck76/NvChad#146]
Sorry if these seem pretty basic, I'm new to NeoVim and Vim in general. 

1. How can I set it to use my terminal/pywal colors?

2. How can I open a folder and show the file picker like in this screenshot? ![Screenshot_20210709-160509.jpg](https://user-images.githubusercontent.com/44733677/125143408-76263680-e0cf-11eb-9ec3-99ad92403f91.jpg)

**Comment by tanshunyuan** [comment]
>     2\. How can I open a folder and show the file picker like in this screenshot?

The key mapping for toggling the tree is `Ctrl-N`. You can look at the key mappings under `lua/plugins/mappings.lua`

**Comment by ThatOneCalculator** [comment]
Thank you! I found a pywal theme, but it has to be installed thru Plug, and I can't figure out how to install Plug.

**Comment by siduck76** [comment]
> Thank you! I found a pywal theme, but it has to be installed thru Plug, and I can't figure out how to install Plug.

go to the lua/pluginlist.lua file and 

add this  use {"dylanaraps/wal.vim"}

**Comment by ThatOneCalculator** [comment]
I did that, but after doing `:colorscheme wal`, it looks like this (not what it should look like):
![image](https://user-images.githubusercontent.com/44733677/125153181-d1bfe680-e106-11eb-9a59-ce040226734e.png)

**Comment by ThatOneCalculator** [comment]
There's this note on the repo:
> Neovim users, make sure to remove set termguicolors as it messes up the colorscheme.
How do I remove set termguicolors, if it's even there?

**Comment by ThatOneCalculator** [comment]
Also...I think I might've fucked something up, `:PlugInstall` isn't showing as a command anymore

**Comment by siduck76** [comment]
> Also...I think I might've fucked something up, `:PlugInstall` isn't showing as a command anymore

we dont use vim-plug , but packer.nvim!

**Comment by siduck76** [comment]
> There's this note on the repo:
> 
> > Neovim users, make sure to remove set termguicolors as it messes up the colorscheme.
> 
> How do I remove set termguicolors, if it's even there?

remove nvim-base16 plugin and remove its config from init.lua

**Comment by ThatOneCalculator** [comment]
@siduck76 I've followed everything but I still can't get it to work. Should I purge ~/.config/nvim and reinstall?

**Comment by siduck76** [comment]
> @siduck76 I've followed everything but I still can't get it to work. Should I purge ~/.config/nvim and reinstall?

I dont think so , btw how does wal colorscheme normally look for you?

**Comment by ThatOneCalculator** [comment]
As it is in most programs, it SHOULD by using whatever colorscheme pywal made.
![image](https://user-images.githubusercontent.com/44733677/125154458-0041bf80-e10f-11eb-8c76-c59d0d076a0a.png)

**Comment by siduck76** [comment]
> As it is in most programs, it SHOULD by using whatever colorscheme pywal made.
> ![image](https://user-images.githubusercontent.com/44733677/125154458-0041bf80-e10f-11eb-8c76-c59d0d076a0a.png)

did wal.vim work on your old setup?

**Comment by ThatOneCalculator** [comment]
> did wal.vim work on your old setup?

This is my first time using neovim, or customizing vim lol

**Comment by siduck76** [comment]
> > did wal.vim work on your old setup?
> 
> This is my first time using neovim, or customizing vim lol

oh lol then idk! pywal colors are meh thats why NvChad has ts own themes.

**Comment by ThatOneCalculator** [comment]
> > > did wal.vim work on your old setup?
> > 
> > This is my first time using neovim, or customizing vim lol
> 
> oh lol then idk! pywal colors are meh thats why NvChad has ts own themes.

I use pywal for my whole system tho lol

**Comment by siduck76** [comment]
@tanshunyuan I got it working! do https://github.com/siduck76/NvChad/issues/146#issuecomment-877571147 

go to lua/options.lua and set this false :D

![image](https://user-images.githubusercontent.com/59060246/125202291-97825080-e290-11eb-842d-7e251ef93360.png)

**Comment by siduck76** [comment]
go to lua/options.lua and set termguicolors as false and check again

**Comment by ThatOneCalculator** [comment]
Oooo I'll try this

**Comment by ThatOneCalculator** [comment]
I get this error when launching neovim now after setting it:

```
Error detected while processing BufReadPost Autocommands for "*":
&termguicolors must be set
Press ENTER or type command to continue
```

**Comment by ThatOneCalculator** [comment]
And it seems to work, but when I open the filemanager, it breaks

**Comment by ThatOneCalculator** [comment]
Working:
![image](https://user-images.githubusercontent.com/44733677/125204656-295b7080-e233-11eb-9920-63a1ab55b754.png)

Broken:
![image](https://user-images.githubusercontent.com/44733677/125204661-2d878e00-e233-11eb-98e5-9f08261b9f7a.png)

**Comment by siduck76** [comment]
> And it seems to work, but when I open the filemanager, it breaks

because you gotta change its highlights :p , so pywal themes wont work well imo . you still have to change so many highlights.

**Comment by siduck76** [comment]
> I get this error when launching neovim now after setting it:
> 
> ```
> Error detected while processing BufReadPost Autocommands for "*":
> &termguicolors must be set
> Press ENTER or type command to continue
> ```

yeah cuz most plugins need that!

**Comment by ThatOneCalculator** [comment]
Sorry for the late reply. I changed that, but it still doesn't work

**Comment by ThatOneCalculator** [comment]
My init.lua:

```lua
-- load all plugins
require "pluginList"
require "options"
require "plugins.bufferline"

local g = vim.g

g.mapleader = " "
g.auto_save = true
-- colorscheme related stuff

-- g.nvchad_theme = "onedark"
-- local base16 = require "base16"
-- base16(base16.themes["onedark"], true)

-- require "highlights"
require "mappings"

require("utils").hideStuff()
```

My lua/options.lua:
```lua
local opt = vim.opt

opt.ruler = false
opt.hidden = true
opt.ignorecase = true
opt.splitbelow = true
opt.splitright = true
opt.termguicolors = false
opt.cul = true
opt.mouse = "a"
opt.signcolumn = "yes"
opt.cmdheight = 1
opt.updatetime = 250 -- update interval for gitsigns
opt.timeoutlen = 200
opt.clipboard = "unnamedplus"
-- opt.termguicolors = false
-- Numbers
opt.number = true
opt.numberwidth = 2
-- opt.relativenumber = true

-- for indenline
opt.expandtab = true
opt.shiftwidth = 2
opt.smartindent = true

-- disable builtin vim plugins
vim.g.loaded_gzip = 0
vim.g.loaded_tar = 0
vim.g.loaded_tarPlugin = 0
vim.g.loaded_zipPlugin = 0
vim.g.loaded_2html_plugin = 0
vim.g.loaded_netrw = 0
vim.g.loaded_netrwPlugin = 0
vim.g.loaded_matchit = 0
vim.g.loaded_matchparen = 0
vim.g.loaded_spec = 0

local M = {}

function M.is_buffer_empty()
    -- Check whether the current buffer is empty
    return vim.fn.empty(vim.fn.expand("%:t")) == 1
end

function M.has_width_gt(cols)
    -- Check if the windows width is greater than a given number of columns
    return vim.fn.winwidth(0) / 2 > cols
end

-- file extension specific tabbing
-- vim.cmd([[autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4]])

return M
```

**Comment by siduck76** [comment]
disabling guicolors is a big meh for neovim , I have tried wal.vim and it works with the syntax but the rest of the thing gets messed up like plugin's highlights .

**Comment by ThatOneCalculator** [comment]
I'm gonna try with this, cuz I also use wpgtk: https://github.com/deviantfero/wpgtk.vim

**Comment by ThatOneCalculator** [comment]
Nope, the same problem

**Comment by ThatOneCalculator** [comment]
It seems this won't support wal, so I've given up and moved to vim.reaper.
