### ISSUE TITLE
My vim is too stuck, I am going to change to nvim, I encountered an installation error

### ISSUE THREAD

**Issue by jicvi** [siduck76/NvChad#151]
![666666666_20210712081959](https://user-images.githubusercontent.com/14210650/125286931-5454cb80-e2ea-11eb-8341-e0197d13a70d.png)

$ lua -v
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio

$ nvim --version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by jicvi** [comment]
How to mount NvChad in docker:
ln -s /work-path/config/vim-config/usr/ubuntu/bin/vim /usr/bin/vim

ln -s /work-path/config/vim-config/vimrc.vim $HOME/.vimrc
ln -s /work-path/config/vim-config/tmux.conf $HOME/.tmux.conf

**Comment by siduck76** [comment]
> How to mount NvChad in docker:
> ln -s /work-path/config/vim-config/usr/ubuntu/bin/vim /usr/bin/vim
> 
> ln -s /work-path/config/vim-config/vimrc.vim $HOME/.vimrc
> ln -s /work-path/config/vim-config/tmux.conf $HOME/.tmux.conf

why vim tho? nvchad works only on neovim 0.5. Also just to be clear , after running the install.sh , some errors will popup so keep pressing enter to skip em and all plugins will be installed.

**Comment by mculp** [comment]
I'm trying to install on mac

1. how to get .xresources -> .itermcolors? :D 
2. I saw it go through installing packages but nothing seems to work, this is ctrl-n:

<img width="392" alt="Screen Shot 2021-07-12 at 9 04 35 AM" src="https://user-images.githubusercontent.com/129983/125301094-4144fa00-e2f0-11eb-9d06-7e5b18145887.png">

**Comment by siduck76** [comment]
> I'm trying to install on mac
> 
> 1. how to get .xresources -> .itermcolors? :D
> 2. I saw it go through installing packages but nothing seems to work, this is ctrl-n:
> 
> <img alt="Screen Shot 2021-07-12 at 9 04 35 AM" width="392" src="https://user-images.githubusercontent.com/129983/125301094-4144fa00-e2f0-11eb-9d06-7e5b18145887.png">

reopen neovim and do cltrl + n

**Comment by mculp** [comment]
> reopen neovim and do cltrl + n

yeah, I've tried that several times, didn't work. When I open nvim, I see only this:

<img width="431" alt="Screen Shot 2021-07-12 at 9 27 07 AM" src="https://user-images.githubusercontent.com/129983/125304685-671fce00-e2f3-11eb-8579-7f5e62232555.png">

I tried to run :PackerInstall and :PackerSync again

<img width="856" alt="Screen Shot 2021-07-12 at 9 29 15 AM" src="https://user-images.githubusercontent.com/129983/125305133-bebe3980-e2f3-11eb-818e-51ac1b1bb393.png">


```
❯ nvim -v                                                                                                                                                                                                            4m  Mon Jul 12 14:30:13 2021
NVIM v0.5.0-dev+1374-g7d4f890aa
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210604-16164-n2exzb/build/config -I/tmp/neovim-20210604-16164-n2exzb/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210604-16164-n2exzb/build/src/nvim/auto -I/tmp/neovim-20210604-16164-n2exzb/build/include
~
Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by siduck76** [comment]
@mculp can you update neovim ? 0.5 has already released so probably in macos repos or such.

**Comment by jicvi** [comment]
> @mculp can you update neovim ? 0.5 has already released so probably in macos repos or such.

Thank you
