### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by FernandoJRR** [siduck76/NvChad#152]
I just installed NvChad yesterday and when I first wanted to open a file this error message appeared

![Screenshot_2021-07-12-25_1897x175](https://user-images.githubusercontent.com/37566757/125339427-8415ca80-e30e-11eb-8693-3ddeb2c7d5fb.png)

When I press Enter I can continue normally but both  nvim-lspconfig and nvim-lspinstall doesn't work, in the sense that they doesn't recognize any installed language server using the command LspInfo (in for example a Lua file) even after I used LspInstall lua and tried to install a server, I used the other commands (LspStart, LspRestart) but it doesn't seem to work either.
Every time I open a file I get the same error message

I'm using the Arch-based distro Archcraft with the Alacritty terminal in Bspwm, I use Neovim v0.5.0 Release with LuaJIT 2.0.5

**Comment by siduck76** [comment]
Update your nvchad config  and do :PackerSync , this error has already been fixed.

**Comment by FernandoJRR** [comment]
Done, but didn't work I'm still getting the same error and lsp is still not working :(

**Comment by siduck76** [comment]
> Done, but didn't work I'm still getting the same error and lsp is still not working :(

Weird,  i hope you're using the latest release of neovim

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/commit/5ff50c63e96954b9cd829be03c978ae4b361f2a4#diff-dc436b329f4da6c88b0b6ce79d829ac4fc33746b454604e2bcbad25a8e2985fe

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/pull/149

**Comment by FernandoJRR** [comment]
Okay i was checking pluginList.lua and it was not the same of the repo even if I cloned yesterday, I cloned again the repo, re-installed nvchad and it solved the problem
