### ISSUE TITLE
No dashboard at start

### ISSUE THREAD

**Issue by slfg** [siduck76/NvChad#153]
I'm trying to use dashboard at the start of neovim (everytime that I open neovim without a file) using the [issue that was referenced in the wiki](https://github.com/siduck76/NvChad/issues/100) and after changing dashboard_diable_at_vimenter to 1, removing the cmd table from pluginList.lua and using :PackerSync the dashboard continues to operate the same way as the default configuration entails.
When I open a blank neovim a message on the bottom appears:
![image](https://user-images.githubusercontent.com/72230679/125401749-1798db00-e3a3-11eb-9ae9-33f82b0952e4.png)

**Comment by siduck76** [comment]
Use the updated version of nvchad  or just remove branch option from blankline plugin , go in pluginlist.lua file . Do :PackerSync at last.

**Comment by slfg** [comment]
It worked but unless I misunderstood the guide one part is wrong "change to 1 ( lua/dashboard.lua file)" you actually need to change to 0.
But the indent-blankline problem is totally solved after the update :)
