### ISSUE TITLE
[CODE STYLE] Properly format all the lua files in one style

### ISSUE THREAD

**Issue by Akianonymus** [siduck76/NvChad#154]
Currently they have very random formatting for each files, i suggest to use stylua to format it and having a stylua.toml at root folder.

If this is fine then i can create pull request.

**Comment by siduck76** [comment]
> Currently they have very random formatting for each files, i suggest to use stylua to format it and having a stylua.toml at root folder.
> 
> If this is fine then i can create pull request.

I use luafmt for formatting.

**Comment by siduck76** [comment]
> > > Currently they have very random formatting for each files, i suggest to use stylua to format it and having a stylua.toml at root folder.
> > > If this is fine then i can create pull request.
> > 
> > 
> > I use luafmt for formatting.
> 
> This one ?
> https://github.com/trixnz/lua-fmt

yes

**Comment by Akianonymus** [comment]
> > 
> > 
> > This one ?
> > https://github.com/trixnz/lua-fmt
> 
> yes

Hmm, i see why the inconsistencies happen, it doesn't handle all the cases, although i have found only one.

```
require("something")

require "something"
```
It doesn't handle these, ideally it should format one to other.

Any plans for stylua ? We can have a configuration file too

Let me know, if not stylua, i will fix those cases manually and pr.

**Comment by siduck76** [comment]
also require "anything" looks more cleaner than require("anything) . I use the parenthesis while calling any function/var etc

**Comment by siduck76** [comment]
stylua breaks indenting too :/ 

![image](https://user-images.githubusercontent.com/59060246/125470526-b5b01b2f-bd31-4ec0-83a5-06d484b62b84.png)
 
 original : 
 
![image](https://user-images.githubusercontent.com/59060246/125470567-9b91848d-5efd-4d94-b92f-77a7c09839f0.png)

**Comment by Akianonymus** [comment]
Hmm, stylua seems to be using tabs out of the box, well, lua-fmt is good i think, no need of config.
