### ISSUE TITLE
Configured LSP (Deno) is not active in Buffer

### ISSUE THREAD

**Issue by typkrft** [siduck76/NvChad#157]
**Describe the bug**
More than likely I am missing something, but I have installed Deno with `:LspInstall deno`. When I open up a new file like `:e test.js` or from the command line like `nvim test.js` and then check `LspInfo` it states the following:
``` 
Configured servers: deno
Neovim logs at: /Users/brandon/.cache/nvim/lsp.log

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype javascript:
  
  Config: deno
  	cmd:               /Users/USERNAME/.local/share/nvim/lspinstall/deno/./bin/deno lsp
  	cmd is executable: True
  	identified root:   /Users/USERNAME/.config/nvim/lua
  	custom handlers:   textDocument/definition, textDocument/references
```
I am not familiar with lua, but it looks like the config is supposed to grab all the installed servers and load them into applicable buffers. I have looked around LSPInstall and LSPConfig repos, but am still unsure of what might need to change. 

**To Reproduce**
1. Install LSP Server `:LspInstall deno`
2. Open new .js file `:e test.js`
3. Check configured servers with `:LspInfo`
4. Server Configured, but not active in buffer. 
5. `:set filetype?` shows `filetype=javascript`
6. `set filetype=javascript` resolves the issue oddly enough

**Expected behavior**
Automatically attach configured LSP to buffer.

**Screenshots**
I can supply them if needed. 

**Desktop (please complete the following information):**
 - macOS 11.3 (20E232)
 - iTerm2 Build 3.4.8
 - NVIM v0.6.0-dev+43-g02bf251bb occurs with --head also on nvim installed through (home/linux)brew.

**Additional context**
I greatly appreciate your work on this. Feel free to point me in the right direction, I am not afraid of learning or rereading if it's something obvious.

**Comment by typkrft** [comment]
Well, I am not sure what resolved this issue, but I went along and installed  a couple plugins and it started working. Doubtful anything I added had an impact, but maybe just updating and installing did something. I'll close this because it appears to be working now.

**Comment by IBugraGezer** [comment]
same issue for java and jdtls
