### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by m3hdi404** [siduck76/NvChad#158]
Hi
I just installed NvChad on Fedora34 but when i'm trying to open dashboard using (space+d+b) i get an error.
![image](https://user-images.githubusercontent.com/74054557/125959120-2272cb0c-d8ed-4a90-b451-7366ae40ff23.png)
Is there any way to fix it?

**Comment by siduck76** [comment]
update neovim to 0.5 latest ( should be available as release on all distros ig)

**Comment by m3hdi404** [comment]
It's already 0.5
Should i compile it manually?

**Comment by Akianonymus** [comment]
> It's already 0.5
> Should i compile it manually?

Try binaries from their github actions, should work.

https://github.com/neovim/neovim/actions/runs/1036356026#artifacts

**Comment by m3hdi404** [comment]
Still getting the same error

**Comment by siduck76** [comment]
when did you install nvchad? did you run :PackerSync ?

**Comment by m3hdi404** [comment]
I installed it yesterday
All packages are up to date when running PackerSync

**Comment by siduck76** [comment]
> I installed it yesterday
> All packages are up to date when running PackerSync

can you try it now again? clear ~/.config/nvim and run ./install.sh -i

**Comment by m3hdi404** [comment]
Still doesn't work

**Comment by siduck76** [comment]
can you enable dashboard and check?

**Comment by m3hdi404** [comment]
How can i enable dashboard?

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/wiki#dashboard

**Comment by m3hdi404** [comment]
Finally it works 
Thanks bro.
