### ISSUE TITLE
 Error when not in clone directory.

### ISSUE THREAD

**Issue by SupremeDeity** [siduck76/NvChad#159]
**Describe the bug**
When not in the repository clone directory, using install.sh --install gives No such file or directory errors on lua folder and init.lua file.

**To Reproduce**
1. Go to ~
2. Run ~/<Path to repo>/install.sh --install
3. See error

**Expected behavior**
Should continue installing without errors.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - Arch Linux
 - Kitty
 - neovim-nightly-bin 0.6.0+dev+43+g02bf251bb-1

**Additional context**
Not sure if its a important error or not, but thought i should report it just in case, so that atleast a Note on the wiki can be added.

Maybe just getting the parent dir from the calling command should do the trick, line 93(install.sh)
![2021-07-16_19-01](https://user-images.githubusercontent.com/29257166/125961230-572ca79e-6edf-4e43-ad65-55e4268641a8.png)

**Comment by siduck76** [comment]
> **Describe the bug**
> When not in the repository clone directory, using install.sh --install gives No such file or directory errors on lua folder and init.lua file.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to ~
> 2. Run ~//install.sh --install
> 3. See error
> 
> **Expected behavior**
> Should continue installing without errors.
> 
> **Screenshots**
> Attached
> 
> **Desktop (please complete the following information):**
> 
> * Arch Linux
> * Kitty
> * neovim-nightly-bin 0.6.0+dev+43+g02bf251bb-1
> 
> **Additional context**
> Not sure if its a important error or not, but thought i should report it just in case, so that atleast a Note on the wiki can be added.
> 
> Maybe just getting the parent dir from the calling command should do the trick, line 93(install.sh)
> ![2021-07-16_19-01](https://user-images.githubusercontent.com/29257166/125961230-572ca79e-6edf-4e43-ad65-55e4268641a8.png)

yea , cd into clone dir and run install.sh

**Comment by siduck76** [comment]
the install.sh should work as long as you have nvchad repo (as cwd)
