### ISSUE TITLE
Bufferline & splits issue

### ISSUE THREAD

**Issue by G-Rowell** [siduck76/NvChad#163]
**Describe the bug**
I think there is an upstream issue with bufferline.lua,
just wanting to check that this is repeatable & correct.
May be a non-trivial fix within bufferline.lua

See [bufferline.lua #87](https://github.com/akinsho/nvim-bufferline.lua/issues/87)

**To Reproduce**
1. new NvChad instance
2. open neovim
3. enter insert mode and enter some text in the buffer (any text, this just helps keep track of buffers)
4. Split with a terminal using `<CNTL> + l`  (this happens with other splits too)
5. Use `<Tab>` to swap between buffers, this should not do anything

**Expected behavior**
`<Tab>` should not swap between splits I think maybe?
At the very least you shouldn't be able to swap to a buffer that is already being shown.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System:   Debian Buster 
 - Terminal:                  Konsole
 - Version of Neovim:   0.5 stable

**Additional context**
N/A

**Comment by Akianonymus** [comment]
definitely a bug, a serious issue

**Comment by siduck76** [comment]
I think this is a feature

**Comment by G-Rowell** [comment]
I think buffer line manages buffers instead of windows?

https://github.com/mhinz/vim-galore#buffers-windows-tabs

**Comment by G-Rowell** [comment]
https://github.com/rockerBOO/awesome-neovim#tabline

This may be an issue with bufferline specifically (**buffer**line)
Could be solved using a tabline?

Looking into it atm

**Comment by G-Rowell** [comment]
[Solved in my pull request](https://github.com/siduck76/NvChad/pull/167)

Closing

@siduck76
