### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by kilpkonn** [siduck76/NvChad#164]
**Is your feature request related to a problem? Please describe.**
I wish to have some git integration in neovim.  
Required features:
- 3 way merge
- Git blame

**Describe the solution you'd like**
I've been using [vim-fugitive](https://github.com/tpope/vim-fugitive) and it works really nice

**Describe alternatives you've considered**
Pretty much any solution that provides 3 way merge and git blame will do.
You you know any lua based plugins, I'd prefer them.

**Screenshot**
You can click through this video to get the idea: https://www.youtube.com/watch?v=PO6DxfGPQvw

**Comment by siduck76** [comment]
there's already gitsigns for the git diff signs on the signcolumn

**Comment by siduck76** [comment]
telescope for git commits and git diff changes 

![image](https://user-images.githubusercontent.com/59060246/126079149-0c75557a-2cd8-4388-ac8b-624c1c93fa0a.png)

![image](https://user-images.githubusercontent.com/59060246/126079175-99d1a0a1-04d3-41d9-af53-a8e28402a19e.png)

**Comment by kilpkonn** [comment]
That is true, and I really like it. :)
It's just that I'd also like to have git blame and 3 way merge tool as well inside vim.

Any ideas about these functionalities?

**Comment by siduck76** [comment]
> That is true, and I really like it. :)
> It's just that I'd also like to have git blame and 3 way merge tool as well inside vim.
> 
> Any ideas about these functionalities?

whats git blame and 3way merge tool?

**Comment by kilpkonn** [comment]
Git blame: 
![image](https://user-images.githubusercontent.com/19900308/126111446-3b6c5195-576f-4146-abcb-3951b2c1554c.png)
^ Useful to find how when and who added particular change to file.

**Comment by ashishbinu** [comment]
@kilpkonn `:Gitsigns toggle_current_line_blame` gives the current line blame if the cursor is on that line.

**Comment by kilpkonn** [comment]
3-way-merge:
![a](https://user-images.githubusercontent.com/19900308/126206190-414b9519-9d03-4e72-addc-e47a6b8a2da2.png)
You can pretty much see merge conflict in a following way and then pick changes on whichever side you want with shortcuts or edit the result file manually.
| - Ours - | - Result - | - Theirs - |

**Comment by siduck76** [comment]
> 3-way-merge:
> ![a](https://user-images.githubusercontent.com/19900308/126206190-414b9519-9d03-4e72-addc-e47a6b8a2da2.png)
> You can pretty much see merge conflict in a following way and then pick changes on whichever side you want with shortcuts or edit the result file manually.
> | - Ours - | - Result - | - Theirs - |

which plugin is this?

**Comment by kilpkonn** [comment]
Vim-fugitive
https://github.com/tpope/vim-fugitive

If you'd be interested I can create a PR and then you can test it etc.

**Comment by ashishbinu** [comment]
A merge tool is pretty useful for an editor. `vim-fugitive` would be a nice addition. There are other plugins like [vim-mergetool](https://github.com/samoshkin/vim-mergetool) which only does merging part if you only need merging tool feature.

**Comment by siduck76** [comment]
how about this? https://github.com/ruifm/gitlinker.nvim

**Comment by ashishbinu** [comment]
>  how about this? https://github.com/ruifm/gitlinker.nvim

This plugin doesn't include a merge tool.

**Comment by siduck76** [comment]
> > how about this? https://github.com/ruifm/gitlinker.nvim
> 
> This plugin doesn't include a merge tool.

Any merge tool written in lua?

**Comment by ashishbinu** [comment]
@siduck76 I haven't found any lua based git merge tools. As of now `vim-fugitive` is the only plugin with most of the git functionality. There is plugin called  [neogit](https://github.com/TimUntersberger/neogit) which have most of git functionality but they haven't yet implemented merge tool.
