### ISSUE TITLE
How to load mason-registry

### ISSUE THREAD

**Issue by axdank** [siduck76/NvChad#1680]
hello i am trying to use the mason registration module, but i can't get it to work at all, because it always returns that the module does not exist, even though it is installed.

`plugins/init.lua`
![imagen](https://user-images.githubusercontent.com/55039048/201711245-41a709e6-d331-4509-9872-45e9c9170f48.png)

1. `rust-tools.lua`
![imagen](https://user-images.githubusercontent.com/55039048/201711469-426e6b7b-ce1f-4c34-b47b-0481eca72155.png)

2. `rust-tools.lua`
![imagen](https://user-images.githubusercontent.com/55039048/201711644-f67c4878-799f-4cd4-a23e-1ffa01c18961.png)

`error`
![imagen](https://user-images.githubusercontent.com/55039048/201712103-4c04553a-e4d9-4ff7-a1c4-dee3749a9f0b.png)

I have tried in multiple instances running `:PackerSync`, `:PackerClean`, `:PackerCompile`, and deleting the `plugin/packer_compiled.lua` folder.

**Comment by siduck** [comment]
```lua
["williamboman/mason.nvim"] = {
      event = "VimEnter"
  },
  ```
  
  put this in your custom plugins and reopen nvim, do packercompile and then reopen nvim

**Comment by siduck** [comment]
> It worked like a charm! Thank you

yep that basically reversed the lazyloading effect of mason plugin, we just load at some commands but there are cases like yours when mason needs to be loaded at the start
