### ISSUE TITLE
Escape mapping lag

### ISSUE THREAD

**Issue by G-Rowell** [siduck76/NvChad#172]
**Describe the bug**
When typing the `j` key, the mapping for, escape to normal, `j + k` causes lag.
Causes NeoVim to feel unresponsive & laggy.
[Related to this closed PR (though this may not be the best solution)](https://github.com/siduck76/NvChad/pull/160)

[These are the mappings](https://github.com/siduck76/NvChad/blob/08dfe17678f8d4759effdb934cdc30bad760dc88/lua/mappings.lua#L22)

**To Reproduce**
1. Open buffer, write some 5+ lines of text
2. Use visual mode `V` to highlight by line, from 1st line
3. Use `j` key to select some lines below **notice `lag` here**

**Expected behavior**
Should not wait for the mapping to confirm before using the j character?

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Debian Buster
 - Terminal: Konsole
 - Version of Neovim: 0.5 release
 - Version of NvChad: current

**Additional context**
[Related to this PR](https://github.com/siduck76/NvChad/pull/160)

**Comment by G-Rowell** [comment]
I'm happy to do some work on this soon, just doing some important uni work rn

**Comment by G-Rowell** [comment]
[This is the mapping](https://github.com/siduck76/NvChad/blob/08dfe17678f8d4759effdb934cdc30bad760dc88/lua/mappings.lua#L22)

**Comment by Akianonymus** [comment]
It's happening because in visual mode `j` handles 2 events, 

1. It is used for moving

2. Because of out mapping for `jk` to escape in visual mode, after pressing `j`, it waits for the `j` key

Now, that's out there, i don't understand why `jk` for visual mode was added, because in visual mode, `v` itself acts as a escape key.

**Comment by G-Rowell** [comment]
Yeah, totally agree that's why it's happening.

It's an issue with the mapping in `insert`, `visual` & `terminal` modes (too).

I think it's worth having the visual mode mapping so that there is a uniform `<ESC>` keybind for all NeoVim modes (don't have to swap to different escape keys depending on mode, can just always hit `j + k`.

Will look as soon as I can :)

**Comment by Akianonymus** [comment]
@siduck76 This can be closed now ? 🤔
