### ISSUE TITLE
Builtin plugins are still loaded 

### ISSUE THREAD

**Issue by shaunsingh** [siduck76/NvChad#173]
**Describe the bug**
upon running `:St` it appears that builtin plugins are still loaded

**To Reproduce**
1. install nvchad
2. run neovim
3. run :St
4. open any of the logs 

**Expected behavior**
Builtin plugins shouldn't be loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/71196912/126545473-3cd52b41-eace-491e-8ca1-af8c8b4572ab.png)

**Desktop (please complete the following information):**
 - MacOS 12
 - Alacritty (+neovide gui)
 - Latest dev (0.6)

**Additional context**
Note that I'm using my own "fork" of the configuration, but the logic for disabling plugins (https://github.com/siduck76/NvChad/blob/020daec5fc827bfd03bd92e1f42b6ed569af6ec9/lua/options.lua#L48) is the same.

**Comment by siduck76** [comment]
@Pocco81

**Comment by ashincoder** [comment]
@siduck76 and @shaunsingh no matter if you disable or undisable they will be still sourced. No idea why. \__/. But yeah

**Comment by siduck76** [comment]
> @siduck76 and @shaunsingh no matter if you disable or undisable they will be still sourced. No idea why. __/. But yeah

maybe some other plugins are using it idk

**Comment by ashincoder** [comment]
I don't think so

**Comment by ashincoder** [comment]
They are hardcoded to source these plugins.

**Comment by siduck76** [comment]
> They are hardcoded to source these plugins.

maybe

**Comment by Akianonymus** [comment]
The reason why it is sourced because it is checked in that file itself if the plugin is enabled or not.

If the plugin is enabled, then it adds a bunch of autocmds and stuff to our nvim runtime, if not then it exits from the file right away, doing nothing.

So, whether you have it enabled or disabled, it will source the file.

Here is first few lines from gzip.vim
```
" Vim plugin for editing compressed files.
" Maintainer: Bram Moolenaar <Bram@vim.org>
" Last Change: 2016 Oct 30

" Exit quickly when:
" - this plugin was already loaded
" - when 'compatible' is set
" - some autocommands are already taking care of compressed files
if exists("loaded_gzip") || &cp || exists("#BufReadPre#*.gz")
  finish
endif
let loaded_gzip = 1

augroup gzip
  " Remove all gzip autocommands
  au!

  " Enable editing of gzipped files.
  " The functions are defined in autoload/gzip.vim.
  "
  " Set binary mode before reading the file.
  " Use "gzip -d", gunzip isn't always available.
  autocmd BufReadPre,FileReadPre	*.gz,*.bz2,*.Z,*.lzma,*.xz,*.lz,*.zst,*.br,*.lzo setlocal bin

..... goes on
```

**Comment by ashincoder** [comment]
Yeah that is what I said xD

**Comment by siduck76** [comment]
Oh then this shouldn't be the issue lol.

**Comment by shaunsingh** [comment]
Oh understandable. So from what I understand its still sourced, but nothing is actually loaded (and therefore there shouldn't be an impact to startuptime)
