### ISSUE TITLE
Keep custom setting during update

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#177]
**Is your feature request related to a problem? Please describe.**
Is it possible to define custom settings in a separate file that is kept while the update process like custom keybindings?

**Describe the solution you'd like**
A custom.settings file that does not get overwritten by an --update

**Comment by siduck76** [comment]
We are thinking about a global config which doesn't get overwritten by updates  , check that issue.

**Comment by siduck76** [comment]
I'll be closing this issue since the global config issue is already active!
