### ISSUE TITLE
add lspsaga.nvim

### ISSUE THREAD

**Issue by siduck76** [siduck76/NvChad#182]

**Comment by G-Rowell** [comment]
For some reason I keep seeing this title and reading it as

[`add lasagna.nvim`](https://www.jessicagavin.com/wp-content/uploads/2014/02/slice-of-meat-lasagna.jpg)

**Comment by Vanderscycle** [comment]
You will definitely want this https://github.com/glepnir/lspsaga.nvim/issues/145

**Comment by siduck76** [comment]
Ig this should go to the chad user configs section in the wiki! Will think about having this if many want this feature.

**Comment by Vanderscycle** [comment]
@G-Rowell if you want an example https://github.com/siduck76/NvChad/pull/207 you may or may not need .6 but works on mine at .5
