### ISSUE TITLE
Telescope acting strange

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#183]
**Describe the bug**
:Telescope media_files, find_files or the shortcuts do either nothing with the error not a editor command or give this error.

![image](https://user-images.githubusercontent.com/69777713/126855126-d429c3ea-8554-43aa-9768-19a562369eba.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck76** [comment]
@se7en-x230 update your config!

**Comment by se7en-x230** [comment]
Okey now it works.
BUT I can't find dotfiles anymore ... and media_files is not an option anymore. Neither via space fp nor :Telescope media_files
