### ISSUE TITLE
Telescope and hidden files

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#185]
I can't find out how to search for hidden files in telescope.
I have export FZF_DEFAULT_COMMAND="find -L" set in my profile and hidden files work in fzf alone....

**Comment by siduck76** [comment]
make a mapping for this 

:Telescope find_files find_command=rg,--ignore,--hidden,--files

**Comment by siduck76** [comment]
or replace it with leader + ff mapping

**Comment by siduck76** [comment]
check telescope docs for more info!

https://github.com/nvim-telescope/telescope.nvim#vim-commands

**Comment by se7en-x230** [comment]
Thanks found a solution already 
map("n", "<Leader>ff", [[<Cmd> Telescope find_files hidden=true<CR>]], opt)

**Comment by siduck76** [comment]
> Thanks found a solution already
> map("n", "ff", [[ Telescope find_files hidden=true]], opt)

if everything works then close the issue :)
