### ISSUE TITLE
nvim-treesitter failed to install during a fresh installation

### ISSUE THREAD

**Issue by raymond-u** [siduck76/NvChad#1853]
**Describe the bug**
I removed old neovim-related files and tried a fresh re-installation, but nvim-treesitter always failed to install.

**To Reproduce**
```bash
rm -rf "${HOME}/.cache/nvim" "${HOME}/.config/nvim" "${HOME}/.local/share/nvim"
git clone --depth=1 --quiet https://github.com/NvChad/NvChad "${HOME}/.config/nvim"
nvim
```

**Screenshots**
<img width="1512" alt="Screenshot 2023-03-24 at 19 42 01" src="https://user-images.githubusercontent.com/36328498/227512387-fcef5ef4-37ce-43b2-a53b-6057bf47513b.png">
<img width="1512" alt="Screenshot 2023-03-24 at 19 42 07" src="https://user-images.githubusercontent.com/36328498/227512426-a05621c2-f5cd-4ee6-9d4a-db29124e57ed.png">

**Desktop (please complete the following information):**
 - Operating System: MacOS 13.2.1
 - Terminal: WezTerm
 - Version of Neovim: v0.8.3

**Additional context**
If I'm missing something or if there is anything else I should provide, please let me know.

**Comment by siduck** [comment]
hi @raymond-u its a clear issue. thats not a nvchad issue! its your ISP most likely

**Comment by raymond-u** [comment]
@siduck I suppose so, but everything else works fine. I came accross this [thread](https://github.com/nvim-treesitter/nvim-treesitter/issues/3232) that reported the same issue, and I wonder if there is a way I can configure NvChad to prefer install via git?

**Comment by siduck** [comment]
@raymond-u go to .config/nvim/lua/plugins/configs/treesitter.lua and add this 
![image](https://user-images.githubusercontent.com/59060246/227515725-1060971c-ac2c-42af-bcff-a08f285d8db6.png)

close terminal , and do `rm -rf ~/.local/share/nvim` 

run nvim command

**Comment by siduck** [comment]
if that works then i will make this change globally i.e in this repo itself

**Comment by raymond-u** [comment]
@siduck Still the same error, guess it won't help much. I'll try to run update through a proxy.

**Comment by raymond-u** [comment]
Ok, seems like OpenSSL is broken on my server so it broke every https request. Thanks for your speedy response and sorry about wasting your time.

**Comment by siduck** [comment]
> Ok, seems like OpenSSL is broken on my server so it broke every https request. Thanks for your speedy response and sorry about wasting your time.

no worries all good!
