### ISSUE TITLE
Syntax Highlighter 'fails' to correctly color sometimes

### ISSUE THREAD

**Issue by datner** [siduck76/NvChad#1854]
**Describe the bug**
TreeSitter(? maybe nvchad? not sure who is responsible) fails to color some typescript syntax, but is successful in doing so in other configs (like lunarvim)

Also colors false-positives when 'primitive' names are used, like `map` or `log`
Also also mistakes all-caps namespaces like `JSON` with SCREAM_CASE consts

This might be a me-issue for all I know, but it's making me sad :(

**To Reproduce**
1. make a `.ts` file
2. write code, any code
4. Be disappointed

**Expected behavior**
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/22598347/227570524-f3fe7bfa-f307-4830-8ee8-3b2591a52958.png">

**Screenshots**
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/22598347/227570701-637b5438-9170-4ce7-ba03-0dfa90299177.png">

**Desktop (please complete the following information):**
 - Operating System Mac
 - Terminal Kitty
 - Version of Neovim v0.8.1

**Additional context**
Clean install of new NvChad on pristine nvim. No extra config.

**Comment by siduck** [comment]
`TSInstall tsx typescript javascript`

**Comment by datner** [comment]
@siduck Thanks, I only had `tsx` and `typescript`, apparently my missing features were in `javascript`. Peculiar :)
