### ISSUE TITLE
NvimTree has odd icons

### ISSUE THREAD

**Issue by datner** [siduck76/NvChad#1855]
**Describe the bug**
Why does everything has a red `X` next to it when dirty? There are no errors in those files

**To Reproduce**
1. Go to your project
2. Change code
3. Save
4. Look at NvimTree get angry with you

**Expected behavior**
<img width="338" alt="image" src="https://user-images.githubusercontent.com/22598347/227577178-e53d8fa2-a49e-4926-b1c1-995db5bd1912.png">

**Screenshots**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/22598347/227577258-a2bac672-dda4-435d-9b1a-efd45d4f16d8.png">

**Desktop (please complete the following information):**
 - MacOs
 - KiTTY
 - v.0.8.1

**Additional context**
The comparison is from lunarvim. NvChad is unmodified on a pristine nvim

**Comment by siduck** [comment]
those "X" implies that the file hasnt been committed
