### ISSUE TITLE
NvDash doesn't work

### ISSUE THREAD

**Issue by stepanzak** [siduck76/NvChad#1858]
**Describe the bug**
NvDash doesn't show up on startup and doesn't show up even when I run :Nvdash.

**To Reproduce**
1. Start Neovim
2. In chadrc.lua, set
   `M.ui = {
  nvdash = {
    load_on_startup = true
  }
}`
3. quit neovim
4. start neovim
5. NvDash isn't here
6. run :Nvdash command
7. nothing happens

**Expected behavior** 
I expect the dashboard to show up

**Screenshots**
chadrc.lua:
![Screenshot_20230325_211008](https://user-images.githubusercontent.com/99094176/227739273-498cad2e-ed65-4054-8fbf-e20c6ea32097.png)
My screen on neovim startup:
![Screenshot_20230325_211032](https://user-images.githubusercontent.com/99094176/227739285-be4f7f31-72e8-4e01-82a8-023edbfda64d.png)
My screen after running :Nvdash :
![Screenshot_20230325_211118](https://user-images.githubusercontent.com/99094176/227739322-fabc4145-35e9-4180-8f7c-e2f246dcd859.png)

**Desktop (please complete the following information):**
 - Operating System: EndeavourOS (Arch) Linux
 - Terminal: KDE Konsole
 - Version of Neovim: v0.8.3

**Additional context**
I also tried it in docker using this command:
`docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git nodejs neovim ripgrep build-base --update
  git clone https://github.com/NvChad/NvChad ~/.config/nvim
  nvim
  '`
Which is from NvCad's website.
NvChad in docker threw few errors, but somehow worked.
Issue was the same.

**Comment by siduck** [comment]
your font size seems too large, decrease it or nvdash wont have enough space
