### ISSUE TITLE
Error loading base64 cache

### ISSUE THREAD

**Issue by webel** [siduck76/NvChad#1859]
**Describe the bug**
When updating nvchad this morning I got this error; 

<img width="909" alt="Screenshot 2023-03-26 at 09 20 36" src="https://user-images.githubusercontent.com/4248688/227761406-2e686e25-0461-4728-a7b9-b22b17afbd3a.png">

**Additional notes** I ran git reset one commit back at a time and was able to open nvim without errors at this commit `HEAD is now at effec96 luasnip: add globals for various types of snippets`.

Thank you for nvchad ❤️

**Comment by siduck** [comment]
do Lazy sync

**Comment by webel** [comment]
I ran lazy sync in the same editor after running the update command (as Lazy isn't available if running git pull and then opening nvim in a new window after the above error). 
But, I'm getting the same error 🤔 I haven't changed anything in that init file either.

**Comment by siduck** [comment]
> I ran lazy sync in the same editor after running the update command (as Lazy isn't available if running git pull and then opening nvim in a new window after the above error). But, I'm getting the same error thinking I haven't changed anything in that init file either.

rm -rf .local/share/nvim
