### ISSUE TITLE
Disabling keymapping with prefix isn't working

### ISSUE THREAD

**Issue by ranamashood** [siduck76/NvChad#1860]
**Describe the bug**
By disabling the keymap of a mapping that consists of prefix, isn't disabling.

**To Reproduce**
1. Go to custom/mappings.lua
2. Scroll to M.disabled
3. Disable a keymap that consists of prefix

**Expected behavior**
Keymap should be disabled and not be showing in whichkey too.

**Screenshots**
Same outcome in both cases:
- With comments
![image](https://user-images.githubusercontent.com/112761667/227767731-dd24ce7b-1dd7-468e-86d9-b9de5a1cfdae.png)
- Without comments
![image](https://user-images.githubusercontent.com/112761667/227767764-4f930556-457c-443e-afcf-4c0d362356e7.png)
- whichkey
![image](https://user-images.githubusercontent.com/112761667/227767833-621f9ef9-2e19-4542-bc2d-8d30ab743e11.png)

**Desktop (please complete the following information):**
 - ArcoLinux Hyprland
 - Kitty v0.27.1
 - NVIM v0.8.3

**Comment by lucario387** [comment]
![image](https://user-images.githubusercontent.com/29790821/227772786-84e1355e-cb6c-46b5-9483-d278f4ab40f1.png)
Eh, from a quick search, there's no `<leader>c`,
to trigger it/override which-key here, press enter
