### ISSUE TITLE
Error while opening

### ISSUE THREAD

**Issue by karambaq** [siduck76/NvChad#1861]
**Describe the bug**
Just installed today and get this error

```
E5113: Error while calling lua chunk: cannot open ~/.local/share/nvim/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        ~/.config/nvim/init.lua:20: in main chunk
```

**Desktop (please complete the following information):**
 - MacOS
 - iTerm2
 - 0.9.0

**Comment by karambaq** [comment]
Sorry, didn't delete my previous `~/.local/share/nvim/`

**Comment by siduck** [comment]
hi @karambaq even a Lazy sync could fix the error btw

**Comment by iujakchu** [comment]
Hello  @siduck.
What do you mean by "Lazy sync" here?

**Comment by siduck** [comment]
> Hello @siduck. What do you mean by "Lazy sync" here?

its a command but if it doesnt work then rm -rf .local/share/nvim

**Comment by iujakchu** [comment]
Thx for your help.
