### ISSUE TITLE
Failed to source - /usr/share/nvim/runtime/plugin/nvchad.vim, line 3: Vim(luafile):E5113: Error while calling lua chunk: /usr/share/nvchad/i nit.lua:21: loop or previous error loading module 'plugins'

### ISSUE THREAD

**Issue by jose1711** [siduck76/NvChad#1863]
**Describe the bug**
Fresh install of NvChad from git (`nvchad-git` from AUR), upon invocation I get:
``` 
Failed to source `/usr/share/nvim/runtime/plugin/nvchad.vim`
vim/_editor.lua:0: /usr/share/nvim/runtime/plugin/nvchad.vim[3]..nvim_exec2() called at /usr/share/nvim/runtime/plugin/nvchad.v
im:3../usr/share/nvim/runtime/plugin/nvchad.vim, line 3: Vim(luafile):E5113: Error while calling lua chunk: /usr/share/nvchad/i
nit.lua:21: loop or previous error loading module 'plugins'
stack traceback:
^I[C]: in function 'require'
^I/usr/share/nvchad/init.lua:21: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:438: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/cor
e/loader.lua:437>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:437: in function 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:396: in function 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:364: in function 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:124: in function 'startup'
^I.../jose/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:85: in function 'setup'
^I/usr/share/nvchad/lua/plugins/init.lua:262: in main chunk
^I[C]: in function 'require'
^I/usr/share/nvchad/init.lua:21: in main chunk
# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - /usr/share/nvchad/lua/plugins/init.lua:262
  - /usr/share/nvchad/init.lua:21
``` 

**To Reproduce**
1. Execute `nvim`
2. See error

**Desktop (please complete the following information):**
 - Arch Linux x86-64 rolling

**Additional context**
Tried `LazySync` but it did not fix the problem.

**Comment by siduck** [comment]
@jose1711 never use aur package for nvchad.,  all you have to do is clone the repo at .config/nvim i.e nvim config path

**Comment by jose1711** [comment]
Thank you, that worked.

**Comment by FullStackAlex** [comment]
@siduck Why should one never use aur package for nvchad? I've installed a huge bunch of aur packages and 99% of them work without any issues. Perhaps in this particular case something is indeed wrong with the aur package. But why so categorically?

**Comment by siduck** [comment]
> @siduck Why should one never use aur package for nvchad? I've installed a huge bunch of aur packages and 99% of them work without any issues. Perhaps in this particular case something is indeed wrong with the aur package. But why so categorically?

I wont be maintaining it and dont have the time to handle issues for those who use nvchad packages :neutral_face: 

they're on their own.

**Comment by FullStackAlex** [comment]
> > @siduck Why should one never use aur package for nvchad? I've installed a huge bunch of aur packages and 99% of them work without any issues. Perhaps in this particular case something is indeed wrong with the aur package. But why so categorically?
> 
> I wont be maintaining it and dont have the time to handle issues for those who use nvchad packages neutral_face
> 
> they're on their own.

fair enough. 
uninstalling aur pacakge, deleting `.cache/nvim` and running the default install (git-clone) command fixed the issue indeed.

**Comment by Sohail-XD** [comment]
> deleting `.cache/nvim` and running the default install (git-clone) command fixed the issue indeed.

This dosen't fix it. I'm bout to cry. I was just very worried then & forgot to remove the aur package first but that caused the issue.

**Comment by siduck** [comment]
> > deleting `.cache/nvim` and running the default install (git-clone) command fixed the issue indeed.
> 
> This dosen't fix it. I'm bout to cry. I was just very worried then & forgot to remove the aur package first but that caused the issue.

rm -rf .local/share/nvim

**Comment by hockeymikey** [comment]
Should be fixed now. Got mucked up with the lazy loading changes a few months back here.
