### ISSUE TITLE
Enabling netrw old way does not work in v2.0 release

### ISSUE THREAD

**Issue by Sidicer** [siduck76/NvChad#1865]
Hello.

I've been reading through already closed issues from May 2022 and December 2022 on how to "re-enable" `netrw` plugin, to be able to `scp` within `neovim`, but sadly none of the solutions provided work anymore.

The `chadrc.lua` has changed, where now `nvim/lue/custom/plugins.lua` is used instead of  `M.plugins = { builtins = {} }`

---

So the solutions tried that did not work:
```lua
-- # chadrc.lua:
local M = {}
M.plugins = {
  builtins = {
      "2html_plugin",
      "getscript",
      "getscriptPlugin",
      "gzip",
      "logipat",
      -- "netrw",
      "netrwPlugin",
      "netrwSettings",
      "netrwFileHandlers",
      "matchit",
      "tar",
      "tarPlugin",
      "rrhelper",
      "spellfile_plugin",
      "vimball",
      "vimballPlugin",
      "zip",
      "zipPlugin",
   }
}
return M

-- # custom/init.lua
local enable_providers = {
  "netrw",
  "netrwPlugin",
  "netrwSettings",
  "netrwFileHandlers",
}
for _, plugin in pairs(enable_providers) do
  vim.g["loaded_" .. plugin] = nil
  vim.cmd("runtime " .. plugin)
end

-- # # I've even tried loading the netrw plugin with this in plugins.lua:
  {
    url = "https://github.com/prichrd/netrw.nvim.git",
    lazy = false
  },
-- # # which sadly still did not work
```

![image](https://user-images.githubusercontent.com/9251667/228227825-4415a6b7-5f8b-49c3-b44e-89e8371bb810.png)

---

What would be the correct/preferred way of re-enabling `netrw` in `v2.0` of NvChad? (by using example_config on first install).

Thank you!

**Comment by siduck** [comment]
```lua
M.lazy_nvim = {
  performance = {
    rtp = {
      disabled_plugins = {
        "2html_plugin",
        "tohtml",
        "getscript",
        "getscriptPlugin",
        "gzip",
        "logipat",
        -- "netrw",
        -- "netrwPlugin",
        -- "netrwSettings",
        -- "netrwFileHandlers",
        "matchit",
        "tar",
        "tarPlugin",
        "rrhelper",
        "spellfile_plugin",
        "vimball",
        "vimballPlugin",
        "zip",
        "zipPlugin",
        "tutor",
        "rplugin",
        "syntax",
        "synmenu",
        "optwin",
        "compiler",
        "bugreport",
        "ftplugin",
      },
    },
  },
}
```

in chadrc

**Comment by Sidicer** [comment]
Appreciate such a quick response and can confirm this actually solved my issue.

**Comment by siduck** [comment]
@Sidicer shorter code for you!

```lua

M.lazy_nvim = {
  performance = {
    rtp = {
      disabled_plugins = vim.tbl_filter(function(name)
        return string.sub(name, 1, 5) ~= "netrw"
      end, require("plugins.configs.lazy_nvim").performance.rtp.disabled_plugins),
    },
  },
}
```

- This uses vim's filter function and takes the values from default lazy_nvim config which is a table and returns each value if it doesnt start with netrw word*

**Comment by Sidicer** [comment]
Dope! Can confirm shorter version that uses vim's `filter` function also works!

Would love to see this somewhere in documentation either on NvChads official website or somewhere here on github
