### ISSUE TITLE
Pre-requisites missing npm

### ISSUE THREAD

**Issue by Circle-Developer** [siduck76/NvChad#1867]
Nvchad's website is missing npm in the pre-requisites.
You need npm for some language servers to work.

**Comment by siduck** [comment]
@Circle-Developer thats upto the user. By default nvchad only downloads lua lsp which doesnt need npm. 

there are people who just code in c/rust stuff and need clangd & rust_anaylyzer. they wouldnt even need npm! 

So i think this is upto the user, based on which lsp server he downloads. hashell's one needs something called ghc :thinking: we cant list pre-requisites for each LSP!

**Comment by Circle-Developer** [comment]
oh sorry about that
