### ISSUE TITLE
Feature: Provide more overrides for configuring cmp

### ISSUE THREAD

**Issue by airtonix** [siduck76/NvChad#1868]
**Is your feature request related to a problem? Please describe.**

1. currently the cmp plugin can only be affected from the `chadrc` with regards to theming: 
    -  https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/init.lua#L186-L188C9
    - https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/cmp.lua#L5
2. vbut there's a bunch of things users would like to customise here that aren't affected by the chardrc: 
    - https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/cmp.lua#L70-L113 

**Describe the solution you'd like**

some way to provide more overrides to the the rest of cmp via `chadrc`

**Describe alternatives you've considered**

- copy paste the cmp plugin entry along with all related files into `custom`

**Additional context**

i want to change the order of the completions so that lsp is first.

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
@airtonix those things can be overriden by the "opts" field!

![image](https://user-images.githubusercontent.com/59060246/228384564-7529948e-54e2-481b-9479-acd8ead0118b.png)

**Comment by airtonix** [comment]
@siduck But wont doing it exactly like that blow away all the cmp plugin setup that already outside of the custom directory?

**Comment by airtonix** [comment]
nvm ok looks like it might be merging it.

**Comment by airtonix** [comment]
Ok so the reason why i think i opened this ticket was this comment in the docs: 

https://github.com/NvChad/nvchad.github.io/blob/src/src/routes/(index)/docs/config/plugins.mdx?plain=1#L43


![image](https://user-images.githubusercontent.com/61225/228677127-f601397a-d2a0-44ce-9067-f9aa155e8c2e.png)


But it looks like you've just suggested to me somethign that contradicts that ?

**Comment by siduck** [comment]
> @siduck But wont doing it exactly like that blow away all the cmp plugin setup that already outside of the custom directory?

it wont, lazy.nvim overrides it.

**Comment by siduck** [comment]
> Ok so the reason why i think i opened this ticket was this comment in the docs:
> 
> https://github.com/NvChad/nvchad.github.io/blob/src/src/routes/(index)/docs/config/plugins.mdx?plain=1#L43
> 
> ![image](https://user-images.githubusercontent.com/61225/228677127-f601397a-d2a0-44ce-9067-f9aa155e8c2e.png)
> 
> But it looks like you've just suggested to me somethign that contradicts that ?

oops yea, will fix the docs!

**Comment by siduck** [comment]
thats incorrect

**Comment by Lucifer-02** [comment]
when I override the mapping of "cmp" plugins in "custom/configs/overrides.lua" like this 
```lua
local M = {}
local cmp = require "cmp"
M.cmp = {
  mapping = {
    ["<Down>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif require("luasnip").expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
    ["<Up>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif require("luasnip").jumpable(-1) then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
  },
}

return M

```
it just adds the key to the final config. I want to replace "cmp" "Tab" key to "up" and "down". How to do that?

**Comment by siduck** [comment]
@Lucifer-02 
```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      mapping = {
        ["<Down>"] = require("cmp").mapping(function(fallback)
          local cmp = require "cmp"
          if cmp.visible() then
            cmp.select_next_item()
          elseif require("luasnip").expand_or_jumpable() then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
          else
            fallback()
          end
        end, {
          "i",
          "s",
        }),
        ["<Up>"] = require("cmp").mapping(function(fallback)
          local cmp = require "cmp"
          if cmp.visible() then
            cmp.select_prev_item()
          elseif require("luasnip").jumpable(-1) then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
          else
            fallback()
          end
        end, {
          "i",
          "s",
        }),
      },
    },
  },
  ```
  
  Now organize it in your cmp overrides

**Comment by Lucifer-02** [comment]
@siduck Tab key still working on cmp, I have to comment the code in plugins/configs/cmp.lua to disable it

**Comment by siduck** [comment]
> @siduck Tab key still working on cmp, I have to comment the code in plugins/configs/cmp.lua to disable it

just override it then?

```lua
mapping = {
 ["<Tab>"] = false 
 }

**Comment by Lucifer-02** [comment]
@siduck 
This time it working but whenever I switch to insert mode, neovim display this:
```
E5108: Error executing lua ...lucifer/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:143: bad argument #1 to 'pairs' (table expected, got string) stack traceback: 
[C]: in function 'pairs' 
...lucifer/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:143: in function ‘prepare’ 
...lucifer/.local/share/nvin/lazy/nvim-cmp/lua/cmp/init. ua: 303: in function <...lucifer/.local/share/nvim/lazy/nvin-cmp/lua/cmp/init.lva:299> 
...ocal/share/nvin/lazy/nvin-cmp/lua/cmp/utils/feedkeys.ua:47: in function <...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:45> Press ENTER or type command to continue] 
```

**Comment by siduck** [comment]
let me test here,w ait

**Comment by siduck** [comment]
@Lucifer-02 o k this works
```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      mapping = {
        -- disable  tab
        ["<Tab>"] = function(callback)
          callback()
        end,

        ["<S-Tab>"] = function(callback)
          callback()
        end,

        -- use Up and down for cycling completion
        ["<Down>"] = require("cmp").mapping(function(fallback)
          local cmp = require "cmp"
          if cmp.visible() then
            cmp.select_next_item()
          elseif require("luasnip").expand_or_jumpable() then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
          else
            fallback()
          end
        end, {
          "i",
          "s",
        }),
        ["<Up>"] = require("cmp").mapping(function(fallback)
          local cmp = require "cmp"
          if cmp.visible() then
            cmp.select_prev_item()
          elseif require("luasnip").jumpable(-1) then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
          else
            fallback()
          end
        end, {
          "i",
          "s",
        }),
      },
    },
  }
  ```

**Comment by Lucifer-02** [comment]
> @Lucifer-02 o k this works
> 
> ```lua
> {
>     "hrsh7th/nvim-cmp",
>     opts = {
>       mapping = {
>         -- disable  tab
>         ["<Tab>"] = function(callback)
>           callback()
>         end,
> 
>         ["<S-Tab>"] = function(callback)
>           callback()
>         end,
> 
>         -- use Up and down for cycling completion
>         ["<Down>"] = require("cmp").mapping(function(fallback)
>           local cmp = require "cmp"
>           if cmp.visible() then
>             cmp.select_next_item()
>           elseif require("luasnip").expand_or_jumpable() then
>             vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
>           else
>             fallback()
>           end
>         end, {
>           "i",
>           "s",
>         }),
>         ["<Up>"] = require("cmp").mapping(function(fallback)
>           local cmp = require "cmp"
>           if cmp.visible() then
>             cmp.select_prev_item()
>           elseif require("luasnip").jumpable(-1) then
>             vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
>           else
>             fallback()
>           end
>         end, {
>           "i",
>           "s",
>         }),
>       },
>     },
>   }
> ```

Oh man, thanks a lot
