### ISSUE TITLE
How to change Nvdash colours?

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [siduck76/NvChad#1869]
I tried adding this to `nvdash = { },` :
```
NvDashAscii = {
    fg = "blue",
    bg = "one_bg",
  },

NvDashButtons = {
    fg = "blue",
    bg = "one_bg",
  },
```

But this didn't work

**Comment by siduck** [comment]
you're close, but read https://nvchad.com/docs/config/theming

**Comment by 1-minute-to-midnight** [comment]
Yeah I did read it, I have written it based on what I understood from it 😅. What am I doing wrong?

**Comment by siduck** [comment]
@1-minute-to-midnight read the docs again!!  its totally useless to put them in nvdash table bruh

**Comment by 1-minute-to-midnight** [comment]
Ok I finally got it 😮‍💨. 

- **custom/chadrc.lua**

```
hl_override = {
    NvDashAscii = {
    fg = "blue",
    bg = "one_bg",
    },

  NvDashButtons = {
    fg = "blue",
    bg = "one_bg",
  }
```
