### ISSUE TITLE
python support is messing with plugin , works well other config of neovim

### ISSUE THREAD

**Issue by Aneeqasif** [siduck76/NvChad#1875]
i followed https://github.com/NvChad/NvChad/issues/1417 and :echo has('python3') return 1 
but as soon as i install luk400/vim-jukit 
python just retun 0 no matter what i do untill i remove relevant lines from core/init.lua 
```lua
for _, provider in ipairs { "node", "perl", "python3", "ruby" } do
  vim.g["loaded_" .. provider .. "_provider"] = 0
end
```

but when i use another config , the :echo has('python3') always return 1 even after installation of the plugin.
if nvim comes by default with these providers enabled then why they are disabled in core/init

**Comment by siduck** [comment]
add this in your custom/init.lua

```lua
local enable_providers = {
      "python3_provider",
      "node_provider",
      -- and so on
    }
    
    for _, plugin in pairs(enable_providers) do
      vim.g["loaded_" .. plugin] = nil
      vim.cmd("runtime " .. plugin)
    end
```
  
 > if nvim comes by default with these providers enabled then why they are disabled in core/init
 
good question, not all users code in ruby, python etc langs, in nvchad you just enable what you want.

**Comment by siduck** [comment]
also `:echo has('python3')` returns 0 even on `nvim -u NONE` here.

**Comment by Aneeqasif** [comment]
> also `:echo has('python3')` returns 0 even on `nvim -u NONE` here.

idk but removing the suckless lines in init.lua get it working for me :)

**Comment by siduck** [comment]
> > also `:echo has('python3')` returns 0 even on `nvim -u NONE` here.
> 
> idk but removing the suckless lines in init.lua get it working for me :)

dude just add the above code in your custom/init.lua

**Comment by siduck** [comment]
you wont get nvchad updates if you edit files outside of custom dir

**Comment by siduck** [comment]
Proof that it works here https://0x0.st/HHZp.mp4
