### ISSUE TITLE
todo-comments.nvim pugin is broken in NvChad

### ISSUE THREAD

**Issue by chikko80** [siduck76/NvChad#1877]
**Describe the bug**
The Plugin just doesn't work in NvChad, with any other config it works fine.
Issue was raised on the plugin repo, but the owner said its related to NvChad

**To Reproduce**
1. Install the plugin in NvChad
2. try to comment something with a marker like TODO, HACK

**Expected behavior**
Proper line highlighting

**Desktop (please complete the following information):**
 - MacOS 13.2.1
 - Kitty
 - 0.9

This is a minmal.lua file where you can test its working with Neovim 0.9 so it must be related to NVChad

**To Reproduce**
1. Use the minimal.lua to reproduce in minimal environment
2. ```nvim --clean -u minimal.lua test.lua```
3. try to comment something with a marker like TODO, HACK

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "olimorris/onedarkpro.nvim",
    opts = {
      -- Your OneDarkPro config goes here
    },
    config = true
  },

  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "folke/todo-comments.nvim" },

  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

vim.cmd("colorscheme onedark")
```

**Comment by siduck** [comment]
lazy=false , pls read our plugin docs :(

**Comment by chikko80** [comment]
@siduck 
Dude, i've read the docs and have lazy = false in my own config, this is not the problem - the example i've provided is unrelated to nvchad. I think you didn't read the issue at all.
I am not the only one having this issue:

[https://github.com/folke/todo-comments.nvim/issues/192](https://github.com/folke/todo-comments.nvim/issues/192)

**Comment by siduck** [comment]
you mean this plugin? https://github.com/Djancyp/better-comments.nvim

**Comment by chikko80** [comment]
my bad, mixed the names - its todo-comments.nvim

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/229067365-60ccae57-4d84-4438-9563-def9fa510d9c.png)

works fine here

**Comment by siduck** [comment]
```lua
 {
    "folke/todo-comments.nvim",
    lazy = false,
    config = function()
      require("todo-comments").setup()
    end,
  },
```

working perfect.

**Comment by chikko80** [comment]
okay strange, its not working on my side - i've all my plugins on lazy = false, as long as i am experimenting to sort out any potential issues - still doesn't work on my side, facing the same problem as the dude in the todo-comments issue.
Probably related to anything else, i'll investigate.

What OS / Terminal do you use?

**Comment by siduck** [comment]
Artix linux & St terminal ( my fork )

**Comment by siduck** [comment]
https://0x0.st/HHPk.mp4

tested on example_config too, works perfect. So the problem is 100% at your end

**Comment by siduck** [comment]
copy paste this to test 
```
-- PERF: test perf?  
-- HACK: bruh
-- TODO: wew
-- NOTE:  sdkfj dkfjskdfj 
-- FIX: fixed 
-- WARNING: test done
```
