### ISSUE TITLE
Theme readability 

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#188]
![image](https://user-images.githubusercontent.com/69777713/127097917-59915684-373d-463b-8172-e094057627d2.png)

The highlighted portion in tomorrow-night is almost unreadable.

**Comment by Akianonymus** [comment]
> ![image](https://user-images.githubusercontent.com/69777713/127097917-59915684-373d-463b-8172-e094057627d2.png)
> 
> The highlighted portion in tomorrow-night is almost unreadable.

![Screenshot_20210728-095442_Termux_1](https://user-images.githubusercontent.com/32216346/127263589-c49f7f2d-e05d-4910-aec4-841d86f8c2b2.png)

Looks fine though.

**Comment by siduck76** [comment]
> ![image](https://user-images.githubusercontent.com/69777713/127097917-59915684-373d-463b-8172-e094057627d2.png)
> 
> The highlighted portion in tomorrow-night is almost unreadable.

maybe you're using an older version of nvchad , i had updated some colors for tomorrow night.

**Comment by se7en-x230** [comment]
Yes thanks @siduck76  that was the problem.

On that note:
What is the best way to update?

Once cloned the repo you run 
1. ./install.sh --update
2. Inside nvchad :PackerUpdate, PackerSync and PackerCompile?

**Comment by Akianonymus** [comment]
@se7en-x230 If you have personal changes, there is really no best way to update.

If not, then `bash install.sh --update --no-backup`
