### ISSUE TITLE
E5113: Error while calling lua chunk

### ISSUE THREAD

**Issue by ImanolGo** [siduck76/NvChad#1880]
**Describe the bug**

```
Error detected while processing ~/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ~/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        ~/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        ~/.config/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

**To Reproduce**
1. Freshly install neovim using `apt install neovim`
2. Open new terminal
3. Insert `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
4. See previously described error. 

**Expected behavior**
It should prompt: `Do you want to install example custom config? (y/n)`

**Desktop:**
 - Operating System: Ubuntu 22.10
 - Terminal: Kitty
 - Version of Neovim: v0.7.2

**Comment by JayJaySea** [comment]
I have a similar problem on arch linux, setup is the same apart from fresh neovim install:

```
Error detected while processing /home/xkali/.config/nvim/init.lua:
E5113: Error while calling lua chunk: cannot open ~/.local/share/nvim/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        ~/.config/nvim/init.lua:19: in main chunk
```

**Comment by snowkluster** [comment]
Have the same issue on windows, I got the error after I ran the update for nvchad 
```
Error detected while processing C:\Users\rohan\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: cannot open C:\Users\rohan\AppData\Local\nvim-data/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        C:\Users\rohan\AppData\Local\nvim\init.lua:19: in main chunk
```

Details:
- Operating system: windows 10
- terminal: alacritty
- nvim version: 0.8.3

**Comment by siduck** [comment]
@snow-kluster please rm -rf your nvim dir

**Comment by siduck** [comment]
```sh
# Linux / Macos (unix)
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim

# Windows
rd -r ~\AppData\Local\nvim
rd -r ~\AppData\Local\nvim-data
```

**Comment by ImanolGo** [comment]
@siduck. Unfortunately, that didn't work. Do you have any idea what the error message could mean. I'm new to NeoVim and Lua, but with some guidance I can try to solve it myself.

I'd appreciate your help.

**Comment by siduck** [comment]
@ImanolGo make sure you are using neovim v0.8.3 only

**Comment by ImanolGo** [comment]
@siduck Thanks, that did the trick

**Comment by engg-rehman** [comment]
so NvChad is not compatible with higher neovim version ?

**Comment by siduck** [comment]
> so NvChad is not compatible with higher neovim version ?

use the lts version, nvchad might have weird issues with nightly
