### ISSUE TITLE
Changing the theme in the config does not work

### ISSUE THREAD

**Issue by MathisP75** [siduck76/NvChad#1885]
**Describe the bug**
Editing the theme in `.config/nvim/lua/custom/chadrc.lua` does not change the theme in nvim

**To Reproduce**
1. Open `.config/nvim/lua/custom/chadrc.lua` with a text editor
2. Change the line `theme = "theme-name",` to the desired theme
3. Open nvim
4. The theme does not change

**Expected behavior**
The theme should change accordingly

**Desktop (please complete the following information):**
 - Arch Linux
 - Kitty
 - neovim 0.8.3-1

**Additional context**
I tried making the theme plugin not lazy load and a coupe other things, without success. I would like to be able to change the theme by editing the config for a system wide theme switcher I am working on.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/229569293-b5fcbda2-d172-48d9-bb3d-a4b9f5f32036.mp4

unable to reproduce, hence closing. 

if you share a video of this issue, i'll reopen it

**Comment by MathisP75** [comment]
Thank you, the problem was the theme toggle part

**Comment by MathisP75** [comment]
It seems to not update when editing the file using another text editor or with a shell script. Is that related to the lazy loading?

**Comment by MathisP75** [comment]
It seems like I have fixed it by disabling lazy loading, setting priority to 1000 and replacing `build =` by `config =` in `init.lua`

**Comment by siduck** [comment]
> It seems like I have fixed it by disabling lazy loading, setting priority to 1000 and replacing `build =` by `config =` in `init.lua`

nooo you dont change files outside of custom dir

**Comment by siduck** [comment]
also theme_toggle works here, can you  provide a video?

**Comment by MathisP75** [comment]
I might be wrong on the theme toggle thing, but what's the issue of changing something outside of custom and where would I apply the same changes?

**Comment by siduck** [comment]
> I might be wrong on the theme toggle thing, but what's the issue of changing something outside of custom and where would I apply the same changes?

you will no longer get nvchad updates.

**Comment by MathisP75** [comment]
Is it not that nvchad will overwite my changes? I didn't change anything besides the color scheme plugin.

**Comment by siduck** [comment]
> Is it not that nvchad will overwite my changes? I didn't change anything besides the color scheme plugin.

nvchad gitignores the custom dir so all of your changes must be done there.
