### ISSUE TITLE
 Copilot not working

### ISSUE THREAD

**Issue by Sarthak950** [siduck76/NvChad#1886]
i am using windows 11 and in installed the nvchad according to the video

[https://www.youtube.com/watch?v=Mtgo-nP_r8Y&t=517s](url)

but now i am having some issue with it 

whenever i type :lazy  
it shows me this error
![image](https://user-images.githubusercontent.com/93645760/229775848-938cc3f5-ccca-4725-9754-b8182736b724.png)

also i installed the github copilot using the methord then the comand :Copilot setup
shows this
![image](https://user-images.githubusercontent.com/93645760/229776111-193b52f5-0d1b-49af-bd79-bf49eef45d2a.png)

this is my setup for it
![image](https://user-images.githubusercontent.com/93645760/229776247-08eb025d-b3f4-4cac-a52b-9b618e11ea4d.png)

please help me 

Also 
![image](https://user-images.githubusercontent.com/93645760/229776344-0ea419ab-2e92-46d9-b1aa-f3d93691022f.png)
there is un necessary borders around it how do i remove it

**Comment by siduck** [comment]
lazy=false

**Comment by Sarthak950** [comment]
sir thats not the the case with lazy = false none of the plugin is activating

**Comment by siduck** [comment]
> sir thats not the the case with lazy = false none of the plugin is activating

![image](https://user-images.githubusercontent.com/59060246/229988569-74fb08e2-2e2e-4eb6-8a1b-4f08135f838b.png)

not all plugins need to be started on startup, u couldve read our docs properly

**Comment by Sarthak950** [comment]
but the copilot need to be signed to the github and to do that we need to use the   :Copilot setup comand but that shows error




![image](https://user-images.githubusercontent.com/93645760/230048384-7307d663-9a99-43ce-9245-d6d4184ea8ac.png)
this is from the copilot docs




[https://github.com/github/copilot.vim](url)





here is the error messege
![image](https://user-images.githubusercontent.com/93645760/230048529-20923b5b-93e9-46c3-901a-a4a47bfaa2b5.png)
here see


also , this is same with the telescope
![image](https://user-images.githubusercontent.com/93645760/230049173-82dbcf27-6bb2-4286-869d-716fa31be33d.png)

**Comment by siduck** [comment]
@Sarthak950  telescope.nvim is not a command but Telescope is. Just use lazy=false for copilot. its a plugin we need to have on startup

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230056027-0e1d8b70-16c1-4413-833d-2751a093468e.png)
help me with this issue sir 


here is the exact file of the nvim
https://github.com/Sarthak950/nvim

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230057146-a20f495a-178d-463c-a895-5ebf49fb620b.png)

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230057312-4d809062-7847-4e73-b2bd-5f2578fcc30a.png)
thanks its now done  ..
very greatful of you

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230057445-09d6af87-87c0-40cd-b458-421545558859.png)



also can u help me removing the extra spacing in the terminal around the border

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/93645760/230057445-09d6af87-87c0-40cd-b458-421545558859.png)
> 
> also can u help me removing the extra spacing in the terminal around the border

your terminal handles the padding. just remove it from some setting.

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230065791-1ae5338a-9d29-4383-adf7-1ec54d9dd096.png)


what to do with this

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/93645760/230065791-1ae5338a-9d29-4383-adf7-1ec54d9dd096.png)
> 
> what to do with this

install clangd via mason, simple.

**Comment by Sarthak950** [comment]
how do u have any links i can refer

**Comment by siduck** [comment]
> how do u have any links i can refer

run Mason command and look for clangd, install it. by pressing i make sure you have clang installed on your system.

**Comment by Sarthak950** [comment]
still not able to figure it out

**Comment by siduck** [comment]
> still not able to figure it out

run Mason command, press `g?`

**Comment by Sarthak950** [comment]
still showing the same error

**Comment by siduck** [comment]
> still showing the same error

do you have clang installed on system? and show me output of Mason command

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230095881-add91a8c-1b58-4c3e-a895-c3de9cbf50e9.png)
see

![image](https://user-images.githubusercontent.com/93645760/230096052-cfe8783a-6130-43c6-b59e-d9acbfe35744.png)
even after this

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230103881-50160b4a-b6cb-4394-9740-02f1d6150baa.png)

**Comment by siduck** [comment]
reopen nvim bruh and show your custom lspconfig? and null-ls config

**Comment by Sarthak950** [comment]
i did reopend it 

https://github.com/Sarthak950/nvim

here is the link to all the config

**Comment by siduck** [comment]
1) https://github.com/Sarthak950/nvim/blob/main/lua/custom/plugins.lua#L54 dont redefine it again

2) https://github.com/Sarthak950/nvim/blob/main/lua/custom/configs/overrides.lua#L24 Include `clangd and clang-format` here 

Reopen neovim and run `MasonInstallAll` command , open a c/c++ file and show the output of LspInfo

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230173385-601213a2-4aa5-4244-863b-06dc40e1d61c.png)
i have this error after i did this


//commented this
![image](https://user-images.githubusercontent.com/93645760/230174178-1291f1dd-e951-486a-b6a0-bb9eac947e0f.png)

and added this
![image](https://user-images.githubusercontent.com/93645760/230174286-a4af2b66-884d-415a-b4a0-3733e1092a4b.png)


here are the LspINfo
![image](https://user-images.githubusercontent.com/93645760/230174502-67ba500a-5054-43df-9af8-5d3d1e37347e.png)



also i am so greatful of you as u are helping me a newbie to this a lot thanking u from heart

**Comment by siduck** [comment]
@Sarthak950 bro put the clang stuff in mason overrides table :/

**Comment by Sarthak950** [comment]
![image](https://user-images.githubusercontent.com/93645760/230272440-9fa984e8-576a-42f1-a4e5-0d876f514a4b.png)
done ..!


everytime i run MasonInstallAll it shows this
![image](https://user-images.githubusercontent.com/93645760/230272749-3bc91fd8-e7d0-4462-a5fd-8c3faab8a249.png)

even after this
![image](https://user-images.githubusercontent.com/93645760/230272802-10c61d5c-c1dc-4131-877e-e454a4b9dd9e.png)


this is the output
![image](https://user-images.githubusercontent.com/93645760/230272941-0c585ba8-13df-4af1-96f0-bb361fce711c.png)

![image](https://user-images.githubusercontent.com/93645760/230272967-d4ded8a0-e60e-4a37-90ea-3394c7bed742.png)

**Comment by Sarthak950** [comment]
its still not working

**Comment by siduck** [comment]
> its still not working

idk then man, it works fine here.. cant help with windows :( . ask on discord server

**Comment by Sarthak950** [comment]
give me the link for that

**Comment by siduck** [comment]
> give me the link for that

https://nvchad.com/#community

**Comment by Sarthak950** [comment]
buddy can u asign me to a friend of your's who can help me  in this

**Comment by siduck** [comment]
> buddy can u asign me to a friend of your's who can help me in this

just ask in my discord server, hopefully some user can help u!

**Comment by BrunoKrugel** [comment]
> 
> whenever i type :lazy it shows me this error ![image](https://user-images.githubusercontent.com/93645760/229775848-938cc3f5-ccca-4725-9754-b8182736b724.png)
> 

Its `:Lazy` not `:lazy`

why do you have `plugin.lua` and `lspconfig.lua` empty in your directory?  this will cause confusion to you.

what do you mean with still giving error? `:LspInfo` shows the clangd up and running.

and it seems that your clangd is not installed in your `path`, this has nothing to do with nvchad.

**Comment by Sarthak950** [comment]
If the clangd is installed then why isn't it working

**Comment by BrunoKrugel** [comment]
>and it seems that **_your_** clangd is **_not_** installed in **_your_** `path`, this has **_nothing_** to do with nvchad.

**Comment by siduck** [comment]
> > and it seems that **_your_** clangd is **_not_** installed in **_your_** `path`, this has **_nothing_** to do with nvchad.

if he installed it via mason then it should be on path definitely, we do it 

![image](https://user-images.githubusercontent.com/59060246/230518182-2e38dbad-8386-46b0-9523-2682c896c9db.png)

**Comment by lucario387** [comment]
> if he installed it via mason then it should be on path definitely, we do it

Not exactly, ig

**Comment by siduck** [comment]
> > if he installed it via mason then it should be on path definitely, we do it
> 
> Not exactly, ig

ughh windows issues again? :angry:
