### ISSUE TITLE
add code runner plugin

### ISSUE THREAD

**Issue by Cabbasca** [siduck76/NvChad#1896]
**Is your feature request related to a problem? Please describe.**
I want to run code without leaving neovim

**Describe the solution you'd like**
I want the code runner plugin (https://github.com/CRAG666/code_runner.nvim) to be added

**Describe alternatives you've considered**
Leaving neovim and running commands in the shell like a normal person

**Comment by siduck** [comment]
@Cabbasca add it in your custom plugins table. Also you can achieve a similar functionality with our nvterm plugin

https://github.com/NvChad/nvterm#additional-functionality
