### ISSUE TITLE
How do I change the terminal for nvchad?

### ISSUE THREAD

**Issue by ItsLiyua** [siduck76/NvChad#1899]
I know it's explained in the NvTerm repository. However in the NvChad default config instead of a map or an object or whatever it#s called in lua there is just the `opts` field and I don't know how to append the command which sets the terminal to that. I never used lua so please don't mind me not calling the object / map thing by it's actual name.

Thanks for reading

**Comment by ItsLiyua** [comment]
I'm trying to change the default shell to zsh btw if that's relevant.

**Comment by ItsLiyua** [comment]
Nvm. Figured it out.
I replaced `require("nvterm").setup(opts)` with
```lua
require("nvterm").setup(vim.tbl_deep_extend("force", opts, {
  terminals = {
    shell = "/bin/zsh"
  }
}))
```
in `~/.config/nvim/plugins/init.lua`

**Comment by muhssamy** [comment]
@ItsLiyua thanks it helped me
