### ISSUE TITLE
Built in auto completetion for popular languages.

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#190]
It would be be better to have lsp auto-completion/intellisense  support for mostly used languages like python,javascript/typescript(reactjs and other frameworks) html css bash and c++.

Lua can be very chalenging for new users hence this feature being builtin might be more inviting to new users instead of intalling them manually.

Feel free to share your thoughts on this. :)

**Comment by JustSage** [comment]
You have LspInstall within NvChad's config, so just invoke `:LspInstall` <language-name> and you're guuchi.
Check out the LSP's supported [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall).

Aside from LspInstall extension you also have [lspconfig](https://github.com/neovim/nvim-lspconfig) documentation to provide specifications for each language or examples for hooking an Lsp that may not be supported by LspInstall.

You don't have to understand Lua in order to accomplish this IMO :).

**Comment by siduck76** [comment]
> You have LspInstall within NvChad's config, so just invoke `:LspInstall` and you're guuchi.
> Check out the LSP's supported [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall).
> 
> Aside from LspInstall extension you also have [lspconfig](https://github.com/neovim/nvim-lspconfig) documentation to provide specifications for each language or examples for hooking an Lsp that may not be supported by LspInstall.
> 
> You don't have to understand Lua in order to accomplish this IMO :).

Agreed , :lspInstall python and so on! Shouldn't be hard in my opinion

**Comment by JustSage** [comment]
On top of that if an extension (not necessarily an lsp) requires completion, check out [nvim-compe](https://github.com/hrsh7th/nvim-compe) documentation to see if it's supported. Like vim-dadbod/nvim-orgmode etc...

Psst @siduck76 come on gitter if possible.

**Comment by CTZxVULKAN** [comment]
Thanks i see. I am very new to lua and was lost reading [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md).
This is indded similar to CoC.

**Comment by JustSage** [comment]
> Thanks i see. I am very new to lua and was lost reading [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md).
> This is indded similar to CoC.

If it doesn’t make sense just open an issue and the maintainers will response. But it’s generally a list of specific configurations for each LSP supported by Nvim. The languages you mentioned in the initial post are all supported by LspInstall so don’t worry about it.
