### ISSUE TITLE
Gopls not working with NVChad 

### ISSUE THREAD

**Issue by morenohernan** [siduck76/NvChad#1901]
I just downloaded NVChad and installed gopls. 
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/700619/230599983-668ffd92-bea3-42dc-9de7-6b4e931792fb.png">

In custom/plugins.lua
<img width="925" alt="image" src="https://user-images.githubusercontent.com/700619/230600228-170005ad-888e-4eec-a9e2-a6d5ebbfe29a.png">

In custom/lspconfig.lua
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/700619/230600419-f631469d-cebe-4740-a16a-58ac37c403b5.png">

In the go code when I try to select any option from to complete or change I able to see the list but not to select any of them
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/700619/230601397-b0d938e2-2331-4115-91d4-fd763792950e.png">

Any help ? should I change something in configuration?

**Comment by siduck** [comment]
@morenohernan  press enter

**Comment by morenohernan** [comment]
Yes, I know but I'm not able to select (with up or down key) from the list ..  for instance in here if I want to select Printf instead of Println, I could hit up or down key until I select it and then hit enter. Currently only if I type until it is the only choice   I can select it and then hit enter, is this the expected behavior?
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/700619/230654588-620ec008-4b0e-4d27-be1f-fb368f6ae77a.png">

**Comment by danielrs** [comment]
@morenohernan I get the same behavior, to change between options in the list you can use `<Tab>` or `<Shift-Tab>`

**Comment by morenohernan** [comment]
@danielrs yes, You are right, it works with those keys .. Thanks a lot !!!!
