### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by vonschutter** [siduck76/NvChad#1904]
**Describe the bug**
Documentation bug. It appears that this should just work given that one has neovim installed... not so. Latest Ubuntu + neovim != success! Please list the requirements for this lua scripting to work. What does it expect on my system? 

Also tried with LTS Ubuntu. This also failed. 

**To Reproduce**
1. Install Ubuntu/Debian (can do vm)
2. sudo apt install neovim
3. git clone https://github.com/NvChad/NvChad ~/.config/nvim && nvim
4. See error: boom--- E5113: Error while calling lua chunk: /home/user1/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)

**Expected behavior**
I expect the behavior of the video: https://www.youtube.com/watch?v=Mtgo-nP_r8Y

**Screenshots**
terminal... see above.

**Desktop (please complete the following information):**
Static hostname: thinkpad-x1
Pretty hostname: ThinkPad-X1
Operating System: Ubuntu 22.10                    
Kernel: Linux 5.19.0-38-generic
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad X1 Carbon 4th
Firmware Version: N1FET82W (1.56 )

neovim/kinetic,now 0.7.2-3 amd64 [installed]

**Additional context**
An install script must work. It should satisfy dependencies and arrive at the target unless explicitly stated that a requirement violates this...

**Comment by siduck** [comment]
use neovim 0.8.3
