### ISSUE TITLE
Error detected while processing /Users/hrq/.config/nvim/init.lua: E5113: Error while calling lua chunk: cannot open /Users/hrq/.local/share/nvim/n vchad/base46/defaults: No such file or directory stack traceback:         [C]: in function 'dofile'         /Users/hrq/.config/nvim/init.lua:19: in main chunk Press ENTER or type command to continue

### ISSUE THREAD

**Issue by hrqmonteiro** [siduck76/NvChad#1906]
**Describe the bug**
Just ran the instructions to instal:

```
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```

And have this error:

```
Error detected while processing /Users/hrq/.config/nvim/init.lua:
E5113: Error while calling lua chunk: cannot open /Users/hrq/.local/share/nvim/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        /Users/hrq/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue
```

**To Reproduce**
Read above.

**Expected behavior**
Not to happen?

**Screenshots**
![Screenshot 2023-04-08 at 9 58 23 PM](https://user-images.githubusercontent.com/17055027/230748851-3ad67a87-be9d-4c05-9f07-0d835d0efa78.png)

**Desktop (please complete the following information):**
 - macOS Ventura.
 - Anyone i tried, it is not a terminal problem.
 - Nvim 0.8.3

**Additional context**
-

**Comment by unknownK19** [comment]
Same problem on POP!_OS
It stuck in empty nvim
 
![Screenshot from 2023-04-09 18-26-12](https://user-images.githubusercontent.com/107351441/230774207-6f644468-330d-41e0-9376-7118abcee2e4.png)
![Screenshot from 2023-04-09 18-26-24](https://user-images.githubusercontent.com/107351441/230774212-e684f7f4-2d2d-483f-80f1-b9da6eb1c922.png)
![Screenshot from 2023-04-09 18-26-33](https://user-images.githubusercontent.com/107351441/230774216-898e4d4e-fa4b-489e-9682-413212646be5.png)
![Screenshot from 2023-04-09 18-32-56](https://user-images.githubusercontent.com/107351441/230774220-988974b0-fb30-486d-b8ae-6d3e93926e31.png)

**Comment by siduck** [comment]
Unable to reproduce this.  Please delete ~/.local/share/nvim before installing 

video as a proof that it works ( clean install ) https://0x0.st/HXOc.mp4
