### ISSUE TITLE
LSP overrides treesitter color settings

### ISSUE THREAD

**Issue by Synntix** [siduck76/NvChad#1907]
**Describe the bug**
When using an LSP server, it seems to override the treesitter color settings.

In my custom/plugins.lua i have the following settings for tresitter: 
```lua
{
    "neovim/nvim-lspconfig",

    dependencies = {
     "jose-elias-alvarez/null-ls.nvim",
     config = function()
       require "custom.configs.null-ls"
     end,
   },

    config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end,
},

{
    "nvim-treesitter/nvim-treesitter",

    opts = {
      ensure_installed = {
        ...
        "rust",
        ...
      },

      highlight = {
        vim.api.nvim_set_hl(0, "@comment.documentation.rust", { fg = "#89dceb" })
      },
    },
},

... (more plugins)
```

When I load a rust file containing a documentation comment it appears blue for 2-3 seconds and then goes grey after the load of rust_analyzer. Moreover, if I type in the comment line, the letters spawn blue but quickly turns grey.
Without lspconfig, the comment stays blue.

**To Reproduce**
1. Setup LSP with a custom treesitter highlight setting
2. Load a file with LSP
3. Wait for the LSP to full load
4. See the custom color changed

**Expected behavior**
Keep the treesitter color setting

**Video**
![2023-04-10 00-18-34](https://user-images.githubusercontent.com/36386823/230799191-0fcd2bb9-9a9d-440e-9548-de44538d0a5e.gif)

**Desktop (please complete the following information):**
 - Arch Linux
 - Alacritty
 - NVIM v0.9.0

**Additional context**

**Comment by siduck** [comment]
@Synntix its normal. this is the lsp semantic highlighting 

https://github.com/NvChad/base46/blob/v2.0/lua/base46/integrations/syntax.lua#L120

**Comment by siduck** [comment]
i think i should keep this optional

**Comment by Synntix** [comment]
Oh right, sorry.
Can I disable it ?

**Comment by siduck** [comment]
> Oh right, sorry. Can I disable it ?

alright, i'll add an option for this

**Comment by lucario387** [comment]
This doesn't resolve the issue, as lsp semantic tokens highlighting will still have higher priority, and still be used.
See:
- `:h vim.highlight.priorities`
- https://github.com/neovim/neovim/pull/22981

**Comment by lucario387** [comment]
The temporary solution is to entirely disable lsp semantic tokens from on_attach, and not this

**Comment by siduck** [comment]
> The temporary solution is to entirely disable lsp semantic tokens from on_attach, and not this

on_attach? how :thinking:

**Comment by lucario387** [comment]
Another solution is to do:
```lua
vim.highlight.priorities.semantic_tokens = 95 -- Or any number lower than 100, treesitter's priority level
```

**Comment by siduck** [comment]
> Another solution is to do:
> 
> ```lua
> vim.highlight.priorities.semantic_tokens = 95 -- Or any number lower than 100, treesitter's priority level
> ```

also semantic tokens hl groups seem to link the default syntax hl groups then why do  some colors still look different?

**Comment by lucario387** [comment]
> > The temporary solution is to entirely disable lsp semantic tokens from on_attach, and not this
> 
> on_attach? how thinking

Add this to on_attach(client, bufnr)

```lua
if vim.version().minor >= 9 and lsp_semantic_tokens then
client.server_capabilities.semanticTokensProvider = vim.NIL
end
```

**Comment by lucario387** [comment]
> > Another solution is to do:
> > ```lua
> > vim.highlight.priorities.semantic_tokens = 95 -- Or any number lower than 100, treesitter's priority level
> > ```
> 
> also semantic tokens hl groups seem to link the default syntax hl groups then why do some colors still look different?

Because your syntax hl groups and treesitter hl groups are different, duh

**Comment by siduck** [comment]
oh bruh

**Comment by lucario387** [comment]
and it links to different sections

**Comment by siduck** [comment]
vim.NIL? never heard of that, cant it be just false?

**Comment by lucario387** [comment]
re-open this for now
as the fix suggested was not working
no need to kill from base46

**Comment by lucario387** [comment]
> vim.NIL? never heard of that, cant it be just false?

just `:h vim.NIL`. it can also be `nil` but from my experience vim.NIL makes it produce less errmsg

**Comment by lucario387** [comment]
> ```lua
> vim.highlight.priorities.semantic_tokens = 95 -- Or any number lower than 100, treesitter's priority level
> ```

This can also be applied, and used ui.lsp_semantic_tokens to set. This will work, but need to tell user to reenable

**Comment by jdrouhard** [comment]
The actual solution is to just have the theme link the LSP groups to the treesitter groups so semantic tokens don't change the treesitter highlights when they kick in. The linked PR is trying to get those links into core, but themes can make the links now for a better experience. 

Just disabling the feature because the colors don't line up isn't helping anyone.

**Comment by PraxTube** [comment]
I just updated NvChad and now I seem to get this exact issue. Last time I updated was roughly two months ago (on v2.0). Any idea why? It also seems like all the fixes are already in place, so I have no idea how I could fix this.

**Comment by siduck** [comment]
@PraxTube check nvchad's lsp docs and use the on_init function toyour lsp server's setup call. That function has semantic tokens disabled

**Comment by PraxTube** [comment]
That did the trick, thank you for the quick reply.
