### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by rayone121** [siduck76/NvChad#1910]
This error occurs when attempting to edit files in languages supported by lspconfig.
`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:98: attempt to index field 'semanticTokensProvider' (a nil value)`

1. Go to a file with a language listed in lspconfig
2. Try to edit it

**Screenshots**
![image](https://user-images.githubusercontent.com/44477929/230949938-7b6467b2-2096-4751-8b63-a84503e21f5f.png)

**Desktop :**
 - Arch Linux WSL2 with kernel version 5.15.90.1-microsoft-standard-WSL2
 - Windows Terminal
 - Neovim 0.9.0

**Additional context**
After downgrading Neovim to version 0.8.3, the error no longer appears.

**Comment by siduck** [comment]
is your nvchad uptodate?

**Comment by rayone121** [comment]
Yes, I installed it today.

**Comment by siduck** [comment]
im on 0.9 , cant reproduce the issue.

**Comment by KarmaiSAYIn** [comment]
Make sure you delete ~/.local/share/nvim and ~/.local/state/nvim, then try again.
