### ISSUE TITLE
Issue in NvChadUpdate after recent update

### ISSUE THREAD

**Issue by pathakraul** [siduck76/NvChad#1912]
Today i updated the nvchad and after that its giving me this error on subsequent update commands
 
```
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/extensions/lua/nvchad/update
.lua:135: attempt to concatenate upvalue 'config_branch' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/extensions/lua/nvchad/update.lua:135: in function <.../.local/s
hare/nvim/lazy/extensions/lua/nvchad/update.lua:129>
```

nvim version -  NVIM v0.9.0-dev-1301+g5bf2f4b3c
Ubuntu 22.04

This has started just after today's update

**Comment by pathakraul** [comment]
Update: I just checked with nvim 0.9.0 stable and same issue

**Comment by siduck** [comment]
@pathakraul did you do lazysync?

**Comment by njrardin** [comment]
I'm getting a similar error:

```
Error detected while processing /home/my-name/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/my-name/.config/nvim/lua/core/i
nit.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/my-name/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/my-name/.config/nvim/init.lua:1: in main chunk
```

**Comment by siduck** [comment]
> I'm getting a similar error:
> 
> ```
> Error detected while processing /home/my-name/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: /home/my-name/.config/nvim/lua/core/i
> nit.lua:77: attempt to index field 'fs' (a nil value)
> stack traceback:
>         /home/my-name/.config/nvim/lua/core/init.lua:77: in main chunk
>         [C]: in function 'require'
>         /home/my-name/.config/nvim/init.lua:1: in main chunk
> ```

for this you need v0.8.3 neovim at least!! :smile:

**Comment by pathakraul** [comment]
> lazysync

This command does not exist 

![image](https://user-images.githubusercontent.com/23165276/231072965-9e7fdaa3-43d1-458c-a8b5-1d14feef79f1.png)

**Comment by pathakraul** [comment]
I had to reinstall everything again. not sure what happened earlier. 
I will close this issue

**Comment by siduck** [comment]
> > lazysync
> 
> This command does not exist
> 
> ![image](https://user-images.githubusercontent.com/23165276/231072965-9e7fdaa3-43d1-458c-a8b5-1d14feef79f1.png)

Lazy and then space, type sync or just open lazy window and press S

**Comment by pathakraul** [comment]
ok, thanks.
let me ask another question here - Instead of doing `	lazy = false,` for each plugin. Is there a common place which disables lazy loading for all plugins?

**Comment by siduck** [comment]
> ok, thanks. let me ask another question here - Instead of doing ` lazy = false,` for each plugin. Is there a common place which disables lazy loading for all plugins?

yes, just override the lazy_nvim config through chadrc, check default_config.lua. 

But i wont advice it. you're going to slow down neovim by a lot, if you install a new plugin, try to find ways to lazyload it like by keys/cmd/events etc, if you cant then just set lazy=false for it event="VeryLazy"
