### ISSUE TITLE
Leader+e to focus nvim tree not working

### ISSUE THREAD

**Issue by marcandru** [siduck76/NvChad#1915]
**Describe the bug**
Whenever I press the leader key to see the options, e is blank, and pressing it doesn't focus the nvim tree, even though the configuration has been set to 

**To Reproduce**
1. start nvim
2. Do leader + e
3. Nothing happens

**Expected behavior**
Focus nvim tree

**Screenshots**
![image](https://user-images.githubusercontent.com/82116351/231329661-409d00fa-9b7c-4bd1-929e-5b23da7a3643.png)

The configuration hasn't been changed, like right there the binding hasn't changed, but the options have it blank, and it does nothing when I select it.

**Desktop (please complete the following information):**
 - macOS Ventura 13.3.1
 - ITerm2
 - Neovim 0.8.1

**Additional context**
I was installing plugins for python when it stopped, I installed pyright, black, and isort. I also had the rust-analyzer and the lua-language-server too.

**Comment by siduck** [comment]
weird, works here

![image](https://user-images.githubusercontent.com/59060246/231335913-7c63b9ff-d959-4a4d-b217-0a61edf02c9b.png)

**Comment by marcandru** [comment]
It seems to work only when I initially open nvim and then use the command, but stops working afterwards, and the focus nvimtree does come up, but still does nothing, so I have no idea what's happening

**Comment by marcandru** [comment]
Also when I try :NvimTreeFocus, it does work

**Comment by siduck** [comment]
> It seems to work only when I initially open nvim and then use the command, but stops working afterwards, and the focus nvimtree does come up, but still does nothing, so I have no idea what's happening

weird, show your custom plugins file

**Comment by marcandru** [comment]
[custom.zip](https://github.com/NvChad/NvChad/files/11207306/custom.zip)

I was following this video for setting up stuff: https://www.youtube.com/watch?v=Mtgo-nP_r8Y

**Comment by siduck** [comment]
@marcandru 

![image](https://user-images.githubusercontent.com/59060246/231364024-648ca64f-ad50-4ece-a2c9-46f1093ba65c.png)

in custom/lspconfig.lua
