### ISSUE TITLE
“vim.g.xxxx” in plugin config not working after upgrading to NvChad 2.0

### ISSUE THREAD

**Issue by Liampor** [siduck76/NvChad#1916]
**To Reproduce**
1. Install a plugin via Lazy, e.g. [chaoren/vim-wordmotion](https://github.com/chaoren/vim-wordmotion)
2. setup in plugins.lua like
```
  {
    "chaoren/vim-wordmotion",
    event = {"BufEnter", "BufRead"},
    config = function()
      require "custom.configs.userWordMotion"
    end,
  },
```
in config file `userWordMotion.lua` put
`vim.g.wordmotion_prefix = 'e'`

3. The setup doesn't work, but If move the `vim.g.wordmotion_prefix = 'e'` to file `init.lua`, it could work.

**Expected behavior**
vim.g.xx in config file should works like in the nvchad 1.0

I am using the latest NvChad and stable NeoVim 0.9

It may not be a nvchad issue, but I would ask here for some help. Thank you all in advance

**Comment by siduck** [comment]
show your userWOrdMotion config?

**Comment by Liampor** [comment]
> show your userWOrdMotion config?

hi
only this line 
vim.g.wordmotion_prefix = 'e'
in the config file as a minimal example

**Comment by siduck** [comment]
oh thats normal then!

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/231530726-6417d20f-1029-4c5e-b08e-dd6264d93f47.png)

**Comment by siduck** [comment]
config function runs after the plugin loads so use init function

```lua
init = function()
   vim.g.wordmotion_prefix = 'e'
end
```

or u can just put the global in `custom/init.lua`

**Comment by Liampor** [comment]
> config function runs after the plugin loads so use init function
> 
> ```lua
> init = function()
>    vim.g.wordmotion_prefix = 'e'
> end
> ```
> 
> or u can just put the global in `custom/init.lua`

Thanks a lot, works fine now
