### ISSUE TITLE
make nvim-cmp not autoselect the 1st option

### ISSUE THREAD

**Issue by mrw954** [siduck76/NvChad#1917]
I hope to change the default behavior to disable the automatic selection of the first option.The reason is that when the last word of a group has suggestions, press Enter key to apply the first suggestion, not just inserting a change symbol.

For example；Typeing in the CPP file
 
```c++
ma<CR>
``` 
Is replaced by something like:
```c++
int main (int argc, char *argv[])
{
 ----
     return 0;
}
``` 

But I just want to insert a newline character。

This problem only appears in V2.0.

**Comment by siduck** [comment]
```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      completion = {
        completeopt = "menuone,noselect",
      },
    },
  },
  ```
  
  put it in your custom plugins table
