### ISSUE TITLE
attempt to index field 'fs' (a nil value)

### ISSUE THREAD

**Issue by haidar47x** [siduck76/NvChad#1918]
I get this error when I clone and install NvChad. I've removed the `nvim` directories from `.cache` and `.local`. I don't know what the problem might be.

I've also installed the `lua5.4` package from the repository. That didn't work.

I'm using Ubuntu 23.04 and Alacritty.

```
Error detected while processing /home/hey/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/hey/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/hey/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/hey/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

**Comment by siduck** [comment]
use neovim 0.8.3 at least and delete old nvim dirs , .local/share/nvim before installing nvchad

**Comment by mdotme** [comment]
Hi there! I'm facing the same issue. I did EXACTLY what docs say:
<img width="300" alt="image" src="https://github.com/NvChad/NvChad/assets/82057826/06f672c5-24aa-43a4-a91e-7387b2123ea3">
<img width="252" alt="image" src="https://github.com/NvChad/NvChad/assets/82057826/491cc2f3-9517-4c63-a016-a4faa336eaea">
<img width="1588" alt="image" src="https://github.com/NvChad/NvChad/assets/82057826/44444f1b-b82e-4b12-a120-f8f1b0466309">

**Comment by siduck** [comment]
@manuchekhr32 try again , pushed a fix
