### ISSUE TITLE
Parent Directory Visibility

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#192]
**The bug**
The parent directory showed in N foreground ( text color ) is not visible in Nvim Tree

**To Reproduce**

1. Set theme to onedark / javacafe .
2. Open Nvim Tree 
3. See top part where the parent directory is to be shown.
4. Nothing is visible there.

**Expected behavior**
The parent directory should be visible and shown in white text for readibility.

**Desktop (please complete the following information):**
 - Artix Linux 
 - Kitty
 - 0.5

**Additional context**
I am looking for how to set the text color of the parent directory to white

**Comment by Akianonymus** [comment]
It is actually intended ( according to @siduck76 ) because it doesn't looks good at the place it is.

I know it sounds dumb to remove such an important information because of aesthetics, but that's what he said.

**Comment by CTZxVULKAN** [comment]
@siduck76 @Akianonymus  Could you please tell me how to set it back to visible ?

**Comment by Akianonymus** [comment]
> @siduck76 @Akianonymus Could you please tell me how to set it back to visible ?

Change this line colour: https://github.com/siduck76/NvChad/blob/7f34fee4a407f0465101b5b3b068fe7d096473e8/lua/highlights.lua#L78

**Comment by se7en-x230** [comment]
change 
fg("NvimTreeRootFolder", darker_black)
in the highlight.lua file

**Comment by CTZxVULKAN** [comment]
Thanks mate :)

**Comment by siduck76** [comment]
> It is actually intended ( according to @siduck76 ) because it doesn't looks good at the place it is.
> 
> I know it sounds dumb to remove such an important information because of aesthetics, but that's what he said.

Not just because of aesthetics , statusline already shows the cwd so I removed it from nvimtree

**Comment by Akianonymus** [comment]
@siduck76 Remember https://github.com/siduck76/NvChad/pull/161#issuecomment-881995328 ? lol

And i will try to bring this:  https://github.com/siduck76/NvChad/pull/161#issuecomment-881996024

**Comment by se7en-x230** [comment]
Strange if it is off when you navigate through different folder ...
But easy to enable if you know how

**Comment by siduck76** [comment]
> @siduck76 Remember https://github.com/siduck76/NvChad/pull/161#issuecomment-881995328 ? lol
> 
> And i will try to bring this:  https://github.com/siduck76/NvChad/pull/161#issuecomment-881996024

I'll think about it

**Comment by siduck76** [comment]
> 
> Strange if it is off when you navigate through different folder ...
> But easy to enable if you know how

I'll add it again then!! But I need to highlight its whole block , try adding the guibg to it and it will add bg to the text only but not it's block.

**Comment by se7en-x230** [comment]
> > Strange if it is off when you navigate through different folder ...
> > But easy to enable if you know how
> 
> I'll add it again then!! But I need to highlight its whole block , try adding the guibg to it and it will add bg to the text only but not it's block.

That is what I did. Works fine for me.
