### ISSUE TITLE
Issue with lazy.nvim on clean install

### ISSUE THREAD

**Issue by fxpr** [siduck76/NvChad#1920]
**Describe the bug**
When installing NVChad it throws an error while installing lazy.nvim.
```
  Installing lazy.nvim & plugins ...
Error detected while processing /Users/felixu/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/felixu/.config/nvim/lua/plugins/init.lua:276: module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/felixu/.config/nvim/lua/plugins/init.lua:276: in main chunk
        [C]: in function 'require'
        /Users/felixu/.config/nvim/lua/core/bootstrap.lua:27: in function 'lazy'
        /Users/felixu/.config/nvim/init.lua:16: in main chunk
```
If there is no clear solution to this, can I somehow install it manually?

**To Reproduce**
1. `rm -rf .config/nvim .local/share/nvim/`
2. Install via `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`

**Expected behavior**
I expect it to install without failure, because it is a clean install, as far as I am aware.

**Screenshots**
<img width="1680" alt="Screenshot 2023-04-13 at 09 26 32" src="https://user-images.githubusercontent.com/83762290/231685398-f9e61f8f-0c65-4b9f-a7f8-678efa3560a5.png">

**Desktop (please complete the following information):**
 - Operating System: macOS Montery
 - Terminal: Alacritty
 - Version of Neovim: v0.9.0

**Comment by siduck** [comment]
very weird @fxpr could you make a video of a clean installation?

**Comment by fxpr** [comment]
@siduck sure:

https://user-images.githubusercontent.com/83762290/231731133-0fef7b5f-2838-4727-91ac-044ffa9e9c2f.mov

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/232018430-c60fe800-5bfc-47b3-8357-638547bd4fc4.mp4



Weird, I cant reproduce this issue at all!

**Comment by fxpr** [comment]
@siduck ty for trying. It seems like nvim.lazy is just not getting cloned or installed correctly. I tried using lazy.nvim independently outside of NVChad and it does not work either, so the problem is not with NvChad. Therefore the issue can be closed of course. On Linux it throws no problems for me either.

Would you know if it is possible to install the following manually in the terminal? I am fairly new to this.
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
```

**Comment by siduck** [comment]
hi @fxpr  try this 

`git clone https://github.com/folke/lazy.nvim ~/.local/share/nvim/lazy/lazy.nvim`

**Comment by fxpr** [comment]
I figured it out now. The problem was simply that my version of git was outdated.
Anyways, thanks for this amazing config!

**Comment by RogueRussell** [comment]
I had the exact same issue as fxpr and can confirm it was because my version of git was outdated. The version of git clone I had did not have the --filter option which is where the issues arose. Just wanted to add this in case anyone else has these issues as well.
