### ISSUE TITLE
Error while calling lua chunk: Cannot open base64/defaults

### ISSUE THREAD

**Issue by spjz** [siduck76/NvChad#1925]
MacOS 13.3.1 (22E261)
NVIM v0.9.0

Pulled latest `v2.0` from last working commit `effec96b538319c6091194f59407d6d6b265dda0` today, encountering issue:

```
Error detected while processing /Users/spjz/.config/nvim/init.lua:
E5113: Error while calling lua chunk: cannot open /Users/spjz/.local/share/nvim/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        /Users/spjz/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue
```

Indeed `/Users/spjz/.local/share/nvim/nvchad/base46/` does not exist in my environment. Fresh install fails with same error.

**Comment by bryaneaton** [comment]
Same issue here with ArchLinux
```
OS: Arch Linux x86_64
Host: ROG Zephyrus G14 GA402RJ_GA402RJ 1.0
Kernel: 6.2.9-arch1-1
Uptime: 2 days, 17 hours
Packages: 1914 (pacman)
Shell: zsh 5.9
Resolution: 5120x1440
DE: GNOME 43.4
WM: Mutter
WM Theme: Adwaita
Theme: Adwaita [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: alacritty
```

**Comment by siduck** [comment]
hi guys just `rm -rf ~/.local/share/nvim`

And this is a one-time thing only, Our base46 theme cache used to be in the general ~/.cache dir . but some windows users complained that they used to clean their tmp dir which resulted in also deletion of our base46 cache which through which nvim wont open! 

So i moved the cache location to some other path
