### ISSUE TITLE
More benign installer?

### ISSUE THREAD

**Issue by thisismygitrepo** [siduck76/NvChad#1926]
Can we have an installer that doesn't interfere with `nvim` and any of its files, and instead creates its own files and work separately?
This is the case in `lunarvim` where after installation, the bare naked nvim is untouched and the new editor launches with `lvim` command and it runs its files away from nvim.

Such behavior would allow installation of multiple editors with zero conflict.

**Comment by siduck** [comment]
https://www.youtube.com/watch?v=LkHjJlSgKZY&ab_channel=ElijahManor
