### ISSUE TITLE
Error when starting nvim after install

### ISSUE THREAD

**Issue by SweeterBoi** [siduck76/NvChad#1929]
So I installed NvChad as is recommended, by running
`rm -rf ~/.config/nvim`
and 
`rm -rf ~/.local/share/nvim`
and then running
`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`

The repo was cloned without errors and nvim launched into this error message:
```
Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/user/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/user/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```
after pressing ENTER I enter into nvim but without the fancy default screen.

**Comment by AllanChain** [comment]
What's your NeoVim version? Looks like you should upgrade it to at least 0.8

**Comment by MahadMuhammad** [comment]
### I am facing the similiar issue:
```bash
Error detected while processing /home/usr/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/usr/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/usr/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/usr/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

> After pressing ENTER I enter into nvim but without the fancy default screen and unable to install plugins.

**Comment by SweeterBoi** [comment]
> What's your NeoVim version? Looks like you should upgrade it to at least 0.8

I am using the latest version of nvim.

**Comment by SweeterBoi** [comment]
I reinstalled nvim and that fixed it.

**Comment by MahadMuhammad** [comment]
I did reinstall the nvim multiple times but this doesn't solved my issue.

**Comment by siduck** [comment]
> I did reinstall the nvim multiple times but this doesn't solved my issue.

brother use neovim 0.8.3

**Comment by MahadMuhammad** [comment]
The default Ubuntu package manager gave me an older version of nvim, but using Homebrew I was able to install a newer version and the issue was resolved. Thanks @siduck :)

**Comment by siduck** [comment]
@MahadMuhammad  as-salamu alaikum brother,  I think there's a neovim ppa https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable/+packages, try it :)

**Comment by MahadMuhammad** [comment]
Wasalam, That's great. However, I noticed on the Neovim installation page for [ubuntu](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu)
> Note: The Neovim team does not maintain the PPA packages.

This led me to use Homebrew instead. Nevertheless, this is a great option, and thanks @siduck  for letting me know :)
