### ISSUE TITLE
Changing the highlights in NvDash

### ISSUE THREAD

**Issue by OSfrog** [siduck76/NvChad#1930]
Hi, is there a way to change the Dashboard to look like the first image in the NvDash showcasing image? Mine looks like the second picture and I want to change it to the first one

![image](https://user-images.githubusercontent.com/19598619/232339149-13eea793-059e-4ca7-ae31-2de3b344b67e.png)

**Comment by siduck** [comment]
https://nvchad.com/docs/config/theming

```lua

  hl_override = {
    NvDashAscii = {
      bg = "none",
      fg  = "blue"
    },

    NvDashButtons = {
      bg = "none",
      fg  = "light_grey"
    },
  }
  ```
