### ISSUE TITLE
LSP format not working

### ISSUE THREAD

**Issue by programatik29** [siduck76/NvChad#1933]
`<Space>fm` and `:lua vim.lsp.buf.format()` is not working with my rust-analyzer setup. It is working with my old non-nvchad configuration.

rust-analyzer is installed with mason.nvim and it is working perfectly except formatting.

My `custom/plugins.lua`:
```lua
local plugins = {
  {
    "neovim/nvim-lspconfig",
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "lua-language-server",
        "rust-analyzer",
      },
    },
  },
}
return plugins
```

My `custom/configs/lspconfig.lua`:
```lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = { "rust_analyzer" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

**Comment by siduck** [comment]
@programatik29  either enable formatting  your on_attach function. check our default lspconfig's on_attach function or just define rustfmt in your null-ls config.

**Comment by programatik29** [comment]
> @programatik29 either enable formatting your on_attach function. check our default lspconfig's on_attach function or just define rustfmt in your null-ls config.

Thank you. Following modification solved my problem.

```lua
local on_attach = function(client, bufnr)
  require("plugins.configs.lspconfig").on_attach(client, bufnr)
  client.server_capabilities.documentFormattingProvider = true
end
```

**Comment by rokonio** [comment]
Sorry if this is a stupid question, but why is it disabled by default in the on_attach from plugins/config/lspconfig.lua ? This seems like a good option to have

**Comment by siduck** [comment]
> Sorry if this is a stupid question, but why is it disabled by default in the on_attach from plugins/config/lspconfig.lua ? This seems like a good option to have

before we used to have an error that whenever you tried to format, there would be a message giving you option to format from the lsp server or the null-ls formatter.  but now i dont see it, ig they fixed the issue
