### ISSUE TITLE
Nvdash doesn't load on startup

### ISSUE THREAD

**Issue by Thanatermesis** [siduck76/NvChad#1936]
I have tried to set nvdash (on its own conf) to be enabled on startup and doesn't seems to work:

>   -- nvdash (dashboard)
>  nvdash = {
>    load_on_startup = true,

I also tried to disable lazy to see if is related but didn't do any effect:

> lazyload = false,

**Comment by siduck** [comment]
please do it in your chadrc

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/232639297-1e5a6134-8b97-43ca-a7a2-b84bef7ab6e2.mp4

**Comment by gogones** [comment]
I have already set it up on chadrc but it still doesn't work.

**Comment by siduck** [comment]
> I have already set it up on chadrc but it still doesn't work.

make a video and show me

**Comment by gogones** [comment]
> > I have already set it up on chadrc but it still doesn't work.
> 
> make a video and show me

https://github.com/NvChad/NvChad/assets/19695153/1d63504e-e49e-4994-9d0d-11bf9c5f0ab5

**Comment by noamsto** [comment]
It's not working for me as well...
I can lunch NvDash but it's not loading on startup.
Nvim version: 
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
NvChad Ref: a9bc954

**Comment by siduck** [comment]
@noamsto please add the required config in chadrc

**Comment by siduck** [comment]
> > > I have already set it up on chadrc but it still doesn't work.
> > 
> > 
> > make a video and show me
> 
>  Screen.Recording.2023-06-26.at.14.36.14.mov

thats normal, nvdash will only load when you run nvim without any args, whats the use of nvim . anyways? just type nvim

**Comment by noamsto** [comment]
> chadrc

![image](https://github.com/NvChad/NvChad/assets/17932324/0d46e485-7128-4a7d-aa2e-23d8a3d41ee6)

This is my `chadrc.lua`

I launch nvim without any arguments

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/c7db8e7a-048c-4725-b106-bccdfa63eb2c

@noamsto did a clean install and checked, itworks here :/

![image](https://github.com/NvChad/NvChad/assets/59060246/2e90073f-93c0-4fb2-b9a9-46d6dac2522f)


also please put this in custom init.lua, chadrc must only contain a table structure of core/default_config.lua

**Comment by noamsto** [comment]
Works for me as well on a clean install :sweat: 
Sorry!
I'll check what went wrong with my configuration...
Thanks a lot for your super quick response and awesome work :D

**Comment by Thanatermesis** [comment]
> I'll check what went wrong with my configuration...

For me it looks like the problem was also on my config, but I was unable to find where exactly, it worked without issues later, could be good to know what caused it

**Comment by siduck** [comment]
> > I'll check what went wrong with my configuration...
> 
> For me it looks like the problem was also on my config, but I was unable to find where exactly, it worked without issues later, could be good to know what caused it

just comment code ( line ) one by one and you'll be able to debug easily :)

**Comment by noamsto** [comment]
I've found the culprit, if anyone stumble here, this change fixed it
`custom/plugins.lua`
```diff
	{
		"f3fora/cmp-spell",
		config = function()
			local cmp = require("cmp")
			local config = cmp.get_config()
			table.insert(config.sources, {
				name = "spell",
				option = {
					keep_all_entries = false,
					enable_in_context = function()
						return require("cmp.config.context").in_treesitter_capture("spell")
					end,
				},
				cmp.setup(config),
			})
		end,
-		lazy = false,
+		event = "InsertEnter",
		
	},

```

**Comment by siduck** [comment]
@noamsto  imo your way of adding a cmp dependency is bad! 

do this instead  (   this way you dont need to call cmp's get_config function )

````lua
{
    "hrsh7th/nvim-cmp",

    opts = function()
      local conf = require "plugins.configs.cmp"

      local spell_source = {
        name = "spell",
        option = {
          keep_all_entries = false,
          enable_in_context = function()
            return true
          end,
        },
      }

      table.insert(conf.sources, spell_source)

      return conf
    end,

    dependencies = { "f3fora/cmp-spell" },
  }

**Comment by noamsto** [comment]
Ah!
Thanks for showing the correct way, I'm quite new with NeoVIM and lua so i'm hacking my way around...
Also I'm running it on NixOS which adds another layer of difficulty :sweat:

**Comment by siduck** [comment]
> Ah! Thanks for showing the correct way, I'm quite new with NeoVIM and lua so i'm hacking my way around... Also I'm running it on NixOS which adds another layer of difficulty 😓
ugh man,

 nixos is a huge pain!
