### ISSUE TITLE
No way to disable a default included plugin

### ISSUE THREAD

**Issue by endoze** [siduck76/NvChad#1938]
**Describe the bug**
After upgrading to v2.0, I'm no longer able to remove unwanted plugins that are provided by default such as indent-blankline.nvim.

Previously with packer at the helm for plugin management, I could just add to my plugins table something along the lines of the following and Packer would remove the plugin:

```lua
-- snip from chadrc.lua main branch
M.plugins = {
  ["lukas-reineke/indent-blankline.nvim"] = false,
}
```

Looking at the lazy.nvim documentation, they have an option called enabled which you should be able to set on a plugin spec. They even mention when migrating from packer.nvim to swap from `disable=true` ➡️ `enabled = false`.

Using the following in my chadrc.lua this still does not work and lazy.nvim ensures that this plugin is installed (even if I've manually removed it).

```lua
-- snip from chadrc.lua v2.0 branch
M.plugins = "custom.plugins"
```

```lua
-- plugins.lua v2.0 branch
return {
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
}
```

**To Reproduce**
1. Start with NvChad on the main branch setup with the first code snippet in your chadrc.lua. 
2. Upgrade to v2.0 branch for NvChad3. 
3. Use second code snippets for chadrc.lua and plugins.lua

**Expected behavior**
I should be able to disable plugins using v2.0 branch the same as I can with the main branch. I do not want or need indent-blank line.nvim and find it highly distracting when just trying to get some coding done. 

**Desktop (please complete the following information):**
 - MacOS Monterey 12.5.1
 - Alacritty 0.12.0 (5a72819)
 - NVIM v0.9.0 Build type: Release

**Additional context**
Thank you very much for this great Neovim setup. I appreciate the time and effort that goes into making such a huge project and maintaining it.

**Comment by endoze** [comment]
It seems with the change from the main branch to v2.0 branch, the plugins table is no longer keyed with strings and instead keyed with indexes. I was merging tables from multiple sources to generate a customized plugin list with `vim.tbl_deep_extend`. I'll have to consider how to support this configuration for myself. 

Thanks again for all your hard work and I apologize for the false report. Disabling plugins does indeed work by setting `enabled = false` in the plugin spec.

All of that said, you used to show how to disable plugins as part of the website documentation and I could no longer find this documented. On top of my own issue with merging plugin tables, not being able to find documentation lead me to believe it no longer was supported 😄 .

**Comment by siduck** [comment]
hi @endoze  nvchad uses 100% lazy.nvim now so all lazy options will work. I've updated the docs for u
