### ISSUE TITLE
Terraform language server fails

### ISSUE THREAD

**Issue by Jay-boo** [siduck76/NvChad#1942]
**Describe the bug**
I'am adding terraform-ls to my custom/configs/lspconfig.lua

**To Reproduce**
1. Go to 'custom/configs/lspconfig.lua'
2. Put 
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

-- if you just want default config for the servers then put them in a table
local servers = { "html", "cssls", "tsserver", "clangd","pyright","rust_analyzer" ,"jdtls","terraform-ls"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
-- lspconfig.terraform-lsp.setup{
--   filetypes = { 'terraform', 'tf', 'hcl' }
-- }
--
-- lspconfig.pyright.setup { blabla}

```
4.Use :MasonInstall terraform-ls
5. open a `main.tf`

**Expected behavior**
Use of the terraform LS.

**The error**
I'm getting the following message when opening a `main.tf` 

[lspconfig] Cannot access conifguration for terraform-ls.ENsure this server is listed in `server_configurationq.md` or addes as a custom server

An when looking at `:LspLog`, I get
```
[ERROR][2023-04-18 16:41:41] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2023/04/18 16:41:41 opts.go:205: Received request batch of size 1 (qlen=0)\n2023/04/18 16:41:41 opts.go:205: Dequeued request batch of length 1 (qlen=0)\n2023/04/18 16:41:41 rpc_logger.go:29: Incoming request for "shutdown" (ID 2): \n2023/04/18 16:41:41 service.go:544: stopping closedDirWalker for session ...\n2023/04/18 16:41:41 service.go:546: closedDirWalker stopped\n2023/04/18 16:41:41 service.go:549: stopping openDirWalker for session ...\n2023/04/18 16:41:41 service.go:551: openDirWalker stopped\n2023/04/18 16:41:41 scheduler.go:54: stopped scheduler\n2023/04/18 16:41:41 scheduler.go:54: stopped scheduler\n2023/04/18 16:41:41 rpc_logger.go:50: Response to "shutdown" (ID 2): null\n2023/04/18 16:41:41 opts.go:205: Completed 1 requests [221.087µs elapsed]\n'

```

**Additional context**

**Comment by siduck** [comment]
[lspconfig] Cannot access conifguration for terraform-ls.ENsure this server is listed in server_configurationq.md or addes as a custom server


not a nvchad issue

pls always check lspconfig docs before defining servers in your custom lspconfig

![image](https://user-images.githubusercontent.com/59060246/233056246-090126a0-d587-454b-bc20-57d42afd0051.png)
