### ISSUE TITLE
SSL error on nvchad.com

### ISSUE THREAD

**Issue by oec** [siduck76/NvChad#1943]
Access to nvchad.com  in chrome returns an ERR_SSL_PROTOCOL_ERROR.  Also, `curl https://nvchad.com` returns

```
curl: (35) error:0A000438:SSL routines::tlsv1 alert internal error
```

**Comment by siduck** [comment]
duplicate of https://github.com/NvChad/nvchad.github.io/issues/147 

does nvchad.netlify.app work?

**Comment by siduck** [comment]
@oec does it work now?

**Comment by oec** [comment]
yep, I can access https://nvchad.com again.
