### ISSUE TITLE
Cannot add snippets 

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [siduck76/NvChad#1945]
1. added vscode_snippets in custom/init.lua as shown in the docs 
![image](https://user-images.githubusercontent.com/76522725/233549895-902c51ff-6cef-47d6-9a5e-c8d68666f602.png)
![image](https://user-images.githubusercontent.com/76522725/233549949-7829bbc4-790f-4b1b-b7b5-8287f95851ed.png)

2. added example snippet of c++ 
![image](https://user-images.githubusercontent.com/76522725/233550091-07e6307e-f702-46d7-a0fa-6d5e588d2c7b.png)

3. restarted nvim and no snippets found 
![image](https://user-images.githubusercontent.com/76522725/233550195-77681387-e894-4040-9c2f-d72b5914fb71.png)

**Comment by siduck** [comment]
does absolute path work? like `/home/sid/.config/nvim/lua/custom/snippets`

**Comment by piush-terminalwitchcraft** [comment]
nope :(

**Comment by siduck** [comment]
> nope :(

does it work when you define the path in the luasnip config itself (our default luasnip config is in plugins/others.lua)

**Comment by piush-terminalwitchcraft** [comment]
![image](https://user-images.githubusercontent.com/76522725/233557023-8d1c43ae-2e04-42e8-a831-1091bd8b1d76.png)
nope, still same issue

**Comment by siduck** [comment]
hmm idk then :/

**Comment by siduck** [comment]
does it work without nvchad?

**Comment by piush-terminalwitchcraft** [comment]
let me try with snipmate format, 
snippets are working from default rafamadriz/friendly-snippets

**Comment by piush-terminalwitchcraft** [comment]
when i edit ~/.local/share/nvim/lazy/friendly-snippets/snippets/cpp.json , it works

**Comment by xiopt** [comment]
Can confirm custom vscode style snippets don't work but custom lua snippets are working fine.

NvChad version: 2.3.0
Lua version: 5.4.4
Nvim version: 0.8.3
OS: Mac

```
vim.g.vscode_snippets_path = vim.fn.stdpath "config" .. "/lua/custom/vscode_snippets"
vim.g.lua_snippets_path = vim.fn.stdpath "config" .. "/lua/custom/lua_snippets"
```

![image](https://user-images.githubusercontent.com/10100850/233614539-e986e9b1-c30c-4c08-8629-972b582ac6eb.png)

Contents of php.lua file:
```
local status, ls = pcall(require, "luasnip")
if not status then
  return
end

local snip = ls.snippet
local text = ls.text_node
local insert = ls.insert_node

ls.add_snippets("php", {
  snip({
    trig = "vd",
    namr = "var_dump",
    dscr = "var_dump with formating",
  }, {
    text { "echo '#'.__LINE__.'<BR>'.__FILE__.'<br><pre>';" },
    text { "", "var_dump(" },
    insert(1),
    text { ");" },
    text { "", "echo '</pre><br>';" },
    text { "", "die();" },
  }),
})
```

Contents of php.json file:
```
{
  "var_dump_format": {
    "prefix": "vd",
    "body": [
      "echo '#' . __LINE__ . '<br>' . __FILE__ . '<br><pre>';",
      "var_dump($0);",
      "echo '</pre><br>';",
      "die();"
    ],
    "description": "var_dump with format"
  }
}
```

**Comment by siduck** [comment]
@xiopt i dont use snippets so cant test much, can you check if it works if you directly define paths etc in  luasnip config?

**Comment by piush-terminalwitchcraft** [comment]
> 

same issue, no  problems with other snippets style like ultisnips or luasnips

**Comment by siduck** [comment]
do the snippets work with non nvchad config?

**Comment by siduck** [comment]
try this minimal config https://github.com/NvChad/basic-config

**Comment by siduck** [comment]
ok guys found the issue, you need a package.json in your snippet directory . REad luasnip docs please https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vs-code
