### ISSUE TITLE
"<leader>fm" not registered when only null-ls attached

### ISSUE THREAD

**Issue by isvicy** [siduck76/NvChad#1946]
**Describe the bug**
I am new to NvChad, and consider port my configs to NvChad. I used V2.0_feature branch of your example config for testing before porting, and found the "leader fm" key not registerd as expected.  here is the detail:

I add ` b.formatting.yamlfmt,` in the null-ls sources, and install the tool with mason, after restart neovim, i create an test.yaml with wrong format, when i press leader f ， i don't see a "m" key reminder from which key. so leader fm don't work.
![image](https://user-images.githubusercontent.com/9302617/233575273-df66b622-8a47-4b2c-a2ad-b9a0774a0895.png)

but if i do `lua vim.lsp.buf.format()` manualy, the format works as expected. (proved the mason + null-ls is worked) 

**To Reproduce**
1. use v2.0_feature branch from https://github.com/NvChad/example_config as custom config;
2. add `  b.formatting.yamlfmt` to sources table in null-ls.lua
3. use mason install yamlfmt
4. restart neovim
5. create an test.yaml file, and mess the indent, press <leader>f, and wait which-key menu popup

**Expected behavior**
leader fm is registered.

**Screenshots**
![image](https://user-images.githubusercontent.com/9302617/233577370-d6a1e999-c7ae-4887-978a-f0d0f0475be1.png)

**Desktop (please complete the following information):**
 - Operating System: ubuntu 18.04 server
 - Terminal: ssh from windows terminal
 - neovim: 
 ```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```
**Additional context**

**Comment by siduck** [comment]
hi @ak2kay  thats a part of our lsp mappings and lsp mappings are only available when the lsp server is active. just enable yamlls https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#yamlls
