### ISSUE TITLE
Enable netrw properly

### ISSUE THREAD

**Issue by bgaillard** [siduck76/NvChad#1949]
**Is your feature request related to a problem? Please describe.**

I struggle to configure NvChad to make the 'gx' shortcut work (i.e. open link using Netrw).

There are 2 "problems" / stuffs to configure to make it working.
- By default the [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua) plugin disables Netrw which is not obvious and silent (see https://github.com/nvim-tree/nvim-tree.lua/commit/ce2420b9dab282703fb08e72009f0787b1a7b097 to see what's disabling it)
- NvChad disables Netrw here https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/lazy_nvim.lua#L23

This feature request is also related to https://github.com/NvChad/NvChad/issues/1865#issuecomment-1486776504

**Describe the solution you'd like**

Add a section in the NvChad documentation to explain that both [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua) and NvChad are disabling Netrw and in consequence the 'gx' shortcut is not working by default.

Perhaps also explain why NvChad chose to disable Netrw by default (seems to be related to performances).

Finally explain how to re-enable the 'gx' shortcut, here is how I did it.

Add the following options in the `nvim-tree` plugin definition in your custom plugins file.

```lua
{
  "nvim-tree/nvim-tree.lua",
   opts = {
     -- Enable Netrw to make the 'gx' shortcut work
     disable_netrw = false,
     hijack_netrw = false,
  }
}
```

Add the following to your `chardrc.lua` file.

```lua
-- Re-enable Netrw to make the 'gx' shortcut work
--
-- see https://github.com/NvChad/NvChad/issues/1865
M.lazy_nvim = {
  performance = {
    rtp = {
      disabled_plugins = vim.tbl_filter(function(name)
        return string.sub(name, 1, 5) ~= "netrw"
      end, require("plugins.configs.lazy_nvim").performance.rtp.disabled_plugins),
    },
  },
}
```

If you do not want to open Netrw at startup add the following to your `init.lua` file.

```lua
-- Do not open Netrw at startup, we only need Netrw for the 'gx' shortcut to still work
--
-- see https://github.com/nvim-tree/nvim-tree.lua/commit/ce2420b9dab282703fb08e72009f0787b1a7b097
-- see https://www.reddit.com/r/vim/comments/3d4cpf/prevent_netrw_or_nerdtree_from_opening_when/
vim.cmd([[autocmd VimEnter * silent! au! FileExplorer *]])
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
hi @bgaillard , nvimtree doesnt completely disable netrw, if I dont disable it via lazy.nvim then we will still have this 
![image](https://user-images.githubusercontent.com/59060246/233777078-c5f665d6-e3a5-45b8-90f0-fb27df5d5cc7.png)

**Comment by bgaillard** [comment]
Hi @siduck, thanks for your reactivity on this.

I'm not sure to perfectly understand why you bring me that response as it does not completely respond to my problem which is to fix the `gx` shortcut problem :grimacing:.

You perhaps though that having the 2 `NetrwClean` and `NetrwSettings` commands available makes 'gx' work ? Sadly this is not the case.

If we let the `nvim-tree` default configuration (i.e. disable Netrw with `disable_netrw` to `true` and `hijack_netrw` to `false`) then we encounter the following error while we enter the `gx` shortcut.

![image](https://user-images.githubusercontent.com/1327782/233778287-cf0ff94f-8412-48f6-990a-031e7aef8e90.png)

`Netrw` has to be enabled even if you disable it you see what you show in your previous command. 

The problem is that if only `NetrwClean` and `NetrwSettings` are available then the `NetrwBrowseX()` function is not available if Netrw is disabled.

We can check it by entering this command having the cursor on a link.

![image](https://user-images.githubusercontent.com/1327782/233779667-bce35622-394a-4145-98b0-06eff4682782.png)
![image](https://user-images.githubusercontent.com/1327782/233779678-63920dac-3824-4393-86d0-8506e58afb50.png)

If we re-enable Netrw the function is found and the link opens.

We can see the implementation of the function in the Netrw source code so i'm 99.999 % sure we have to enabled Netrw :smile:  

See the code here https://github.com/vim/vim/blob/master/runtime/autoload/netrw.vim#L5296

We can also see that the function is called in `netrwPlugin.vim` (but this one is not required for 'gx' which only needs Netrw).

![image](https://user-images.githubusercontent.com/1327782/233779826-ba6b2b86-927a-4525-a5ff-57c5fa4a8c77.png)

I see that you changed the title of my request, i'm not sure the new title is appropriate if somebody searches in issues.

You closed it really fast, does it means you do not want to document it in the NvChad documentation (in this case users will be able to find this issue anyway) ?

Thanks for your help and time.

Baptiste

**Comment by siduck** [comment]
@bgaillard Hi, I thought you resolved the issue so I closed this one and pinned it so other users could find it more accessible. 

and for the netreclean/pass, I meant I wanted to disable netrw completed so I disabled it via lazy.nvim too!

**Comment by bgaillard** [comment]
Ok perfect thanks a lot and thanks for your work on this great NvChad tool :+1:
