### ISSUE TITLE
Nvchad installer showing up with an error

### ISSUE THREAD

**Issue by tomcat-at-cintill** [siduck76/NvChad#1950]
On Kali Linux, i run:

sudo apt install neovim
*nvchad installer thing*

and i get

Error detected while processing /home/tomcat/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/tomcat/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/tomcat/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/tomcat/.config/nvim/init.lua:1: in main chunk
E484: Can't open file /usr/share/nvim/runtime/syntax/syntax.vim
Press ENTER or type command to continue

**Comment by herberthudson** [comment]
You need to clean old nvim dirs, more details here https://github.com/NvChad/NvChad/issues/1918 
Work for me
