### ISSUE TITLE
Backspace not working properly in insert mode

### ISSUE THREAD

**Issue by heavyjoost** [siduck76/NvChad#1952]
Looks like the same issue in #1294 has reappeared as it's not working properly in the latest version.

I noticed commit https://github.com/NvChad/NvChad/commit/9bd303feeeb58dff030ec66d9183e45a5b79b696 fixed the issue, but then the next commit in `mapping.lua` (https://github.com/NvChad/NvChad/commit/1b8eff75164a8e8c96701fb9739e44ed22f69c6b) reverted the change, by accident I think?

I reapplied the commit removing those lines locally and that does the trick :slightly_smiling_face:

**Comment by siduck** [comment]
hi @heavyjoost can you describe the issue? So backspace in insert mode doesnt work? did you map it?

**Comment by heavyjoost** [comment]
I have the exact same issue as described in #1294. When I hit backspace in insert mode, it just moves the cursor to the left by one character without removing anything. After applying the change from commit https://github.com/NvChad/NvChad/commit/9bd303feeeb58dff030ec66d9183e45a5b79b696 it works properly, i.e. it removes one character and move one to the left.

I noticed that you had applied that change back in December but after migrating to Lazy in January that change got undone. Just wanted to make you aware of this in case in got undone by accident :slightly_smiling_face: 

I hope that helps!

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/233881443-47209708-5592-4043-b8dd-9cc92597e6fd.mp4

Weird, I cant reproduce it

**Comment by heavyjoost** [comment]
I think it depends on the terminal emulator and/or OS: https://github.com/NvChad/NvChad/issues/1294#issuecomment-1361008090

In my case I'm using st (suckless simple term) on FreeBSD. When I comment out those 4 lines `lua/core/mappings.lua` it works fine for me. I'd be fine with adding something to my `chadrc.lua` that'd do the same but I'm a total noob so I have no idea how to do that :laughing:

**Comment by siduck** [comment]
> I think it depends on the terminal emulator and/or OS: [#1294 (comment)](https://github.com/NvChad/NvChad/issues/1294#issuecomment-1361008090)
> 
> In my case I'm using st (suckless simple term) on FreeBSD. When I comment out those 4 lines `lua/core/mappings.lua` it works fine for me. I'd be fine with adding something to my `chadrc.lua` that'd do the same but I'm a total noob so I have no idea how to do that laughing

I'm using st as well ( Linux ) :D

**Comment by siduck** [comment]
read the mapping docs https://nvchad.com/docs/config/mappings

**Comment by heavyjoost** [comment]
Lol neat, finally somebody who uses the same. I'm not sure if it matters but it I switch to a terminal outside of X (or Wayland), e.g. by using ctrl-alt-f1, the code for backspace is `^H`. Looks like Linux and FreeBSD are different in this way.

I'll go ahead and RTFM :wink: 

Edit: just checked what backspace gives me in Linux and indeed it showed something else, namely `^?`

**Comment by heavyjoost** [comment]
Just adding this here for FreeBSD users with the same issue. This fixes the problem for me without having to mess around with the core files :+1: 
1. Add this line to `lua/custom/chadrc.lua`: `M.mappings = require "custom.mappings"`
2. Create `lua/custom/mappings.lua` with contents:
```lua
local M = {}

M.disabled = {
  i = {
      ["<C-h>"] = ""
  }
}

return M
```
