### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by YuFei29** [siduck76/NvChad#1954]
**most of time, we are not edit a single file. We edit files inside a project.**
Maybe there's a way we can do something inside project( find files inside project, grep inside project etc), and we can switch between different project. 

**what we need are some keybinds like <leader>ff and <leader>fw**
we can add some keymap for project level. such as <leader>pf to find file inside project, <leader>pg to grep inside project and <leader>pp to switch between projects.

of course, we need a way to determine which project we inside and maybe auto changedir to project root dir.

**there's a nvim lua plugin for this**
[nvim lua plugin](https://github.com/ahmedkhalf/project.nvim)

**and emacs builtin support for this**
[emacs builtin support](https://www.gnu.org/software/emacs/manual/html_node/emacs/Projects.html)

thanks for your work. NvChad is great, I love it.

**Comment by siduck** [comment]
hi @YuFei29 , you could use an external plugin for this. Maybe in the future I'll add this functionality in nvchad but not at the moment!
