### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by adesai1000** [siduck76/NvChad#1957]
**Describe the bug**
I'm used the git clone command and after that when I do nvim I get error

**To Reproduce**
1. paste the command git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
2. Then paste nvim

**Expected behavior**
Error popus up saying 
rror detected while processing /home/jack/.config/nvim/init.lua:
E5113: Error while calling lua chunk: cannot open /home/jack/.local/share/nvim/nvcha
d/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        /home/jack/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue

**Screenshots**
![image](https://user-images.githubusercontent.com/68861149/233977768-cf22834e-49cb-4b2b-a5bc-71db66827d48.png)

**Desktop (please complete the following information):**
 - Operating System Pop!_OS latest
 - Terminal Stock
 - Version of Neovim Version 10

**Additional context**
I did make sure that nvim config was clear
I also tried a fresh install of nvim

**Comment by siduck** [comment]
rm -rf .local/share/nvim && rm -rf .config/nvim 

then clone the repo

**Comment by adesai1000** [comment]
That did it, Thanks a lot
