### ISSUE TITLE
NvChad Installation Error - Lua Chunk Error

### ISSUE THREAD

**Issue by kbakdev** [siduck76/NvChad#1959]
**Describe the bug**
Following this quickstart https://nvchad.com/docs/quickstart/install I encountered bug during installation

**To Reproduce**
1. rm -rf ~/.config/nvim
2. rm -rf ~/.local/share/nvim
3. git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim

**Expected behavior**
Successful installation

**Screenshots**
```bash
Error detected while processing /home/kacper/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/kacper/.config/nvim/lua/core/init.lu
a:67: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/kacper/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/kacper/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

**Desktop (please complete the following information):**
 - Operating System Linux Mint 21.1 x86_64 
 - Terminal zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
 - Version of Neovim NVIM v0.6.1

**Additional context**

**Comment by siduck** [comment]
@53jk1 install neovim v0.8.3 at least
