### ISSUE TITLE
How to change the edit icon in status line ?

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#196]
How am i supposed to change the edit icon (pencil icon) in the status line ? 
I have searched for it on the web and also went through the entire config but was unable to get any solution.
Any help would be appreciated :)
![2021-07-29-093935_321x33_scrot](https://user-images.githubusercontent.com/65299153/127430491-dc431838-35c0-47da-a030-c8ba11dd722f.png)

**Comment by Akianonymus** [comment]
@CTZxVULKAN lua/plugins/nvimtree.lua

**Comment by CTZxVULKAN** [comment]
I checked `lua/plugins/nvimtree.lua` but was unable to find that pencil icon in that file. 
Do I have to add a new line on my own ? Could you please tell me what i have to add ?

**Comment by siduck76** [comment]
> I checked `lua/plugins/nvimtree.lua` but was unable to find that pencil icon in that file.
> Do I have to add a new line on my own ? Could you please tell me what i have to add ?

Ig that's a galaxyline thing , I didn't see any option to set it. Check it's docs
