### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by sabiviji** [siduck76/NvChad#1961]
Error executing vim.schedule lua callback: /home/sabi/.config/nvim/lua/core/utils.lua:80: attempt to index a nil value                                         
stack traceback:                                                                                                                                               
        /home/sabi/.config/nvim/lua/core/utils.lua:80: in function </home/sabi/.config/nvim/lua/core/utils.lua:55>

I had installed NvChad and removed if by  `rm ~/.config/nvim`

Now when I tried to reinstall again, it gives me this error. Whenever I open with NvChad config this error comes

![image](https://user-images.githubusercontent.com/58526582/234297600-23138b32-9f66-4901-913f-71ccbb20657c.png)

**Comment by sabiviji** [comment]
Also my leader key is not working

**Comment by siduck** [comment]
rm -rf .local/share/nvim then install nvchad
