### ISSUE TITLE
Can't get a "complex keymap" to work

### ISSUE THREAD

**Issue by R3l4x3** [siduck76/NvChad#1963]
**Describe the bug**
I am trying to include a - according to the documentation - "more complex keymap". However, the keymapping does not lead to the desired result, but throws an error at startup.

> Error executing vim.schedule lua callback: /Users/sew/.config/NvChad/lua/core/utils.lua:67: attempt to index local 'mapping_info' (a function value)
> stack traceback:
>         /Users/sew/.config/NvChad/lua/core/utils.lua:67: in function 'set_section_map'
>         /Users/sew/.config/NvChad/lua/core/utils.lua:85: in function </Users/sew/.config/NvChad/lua/core/utils.lua:55>

**To Reproduce**
1. add mapping to `custom/mappings.lua`
  ```
M.custom = {
  ["<leader>pi"] = {
    function()
      require("lazy").install()
    end,
    "Plugins Install",
  },
}
```
2. Save & Close
3. Open NvChad

**Expected behavior**
I would expect the installation window of Lazy to open when using `<leader>pi`

**Desktop (please complete the following information):**
 - MacOS
 - iTerm2
 - nvim 0.9.0

**Comment by siduck** [comment]
```lua

M.custom = {
  n = {
    ["<leader>pi"] = {
      function()
        require("lazy").install()
      end,
      "Plugins Install",
    },
  },
}
```

you should wrap it under a mode name, read our mapping docs!
