### ISSUE TITLE
nvim-tree doesn't change dir when other file (path) is opened!

### ISSUE THREAD

**Issue by AYehia0** [siduck76/NvChad#1966]
NvChad doesn't update the nvim-tree buffer when a new location is opened in the same terminal path.

**The Expected behavior**
When I cd into another location, the nvim-tree buffer should start from that point.
I have read about `audochdir` but I don't know how to apply!, also a quick fix is to `:cd %:h` from the nvim-tree buffer.

**Screenshots**
![nvim-tree_weird](https://user-images.githubusercontent.com/33802020/234929976-50a9931d-eeaa-4d05-aea1-d515d389990c.gif)

**Desktop:**
 - OS : `Arch Linux BTW`
 - Terminal : `kitty`
 - Nvim : `v0.8.3`

**Comment by AYehia0** [comment]
I fixed it by setting `autochdir` to true in the `init.lua`.
Please check it out.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/pull/1967#issuecomment-1526827605
