### ISSUE TITLE
Vim history

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#197]
**Describe the solution you'd like**
IMHO a sane way to edit files would be to open the document where you left the file last and to keep an undo history in case the last edit had not the results you where hoping for.

I don't know if the team feels that this is a feature they would like to implement. 
If not would someone point me in the right direction how to edit the lua files to get that result please?

**Comment by EasyS7** [comment]
Opening a file where you last left off is as simple as adding this line to the options file:

`vim.cmd([[au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif]])`

And if you want a permanent undo you have to add the following line:

`opt.undofile = true`

**Comment by se7en-x230** [comment]
> Opening a file where you last left off is as simple as adding this line to the options file:
> 
> `vim.cmd([[au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif]])`
> 
> And if you want a permanent undo you have to add the following line:
> 
> `opt.undofile = true`

Many thanks :)

**Comment by siduck76** [comment]
> Opening a file where you last left off is as simple as adding this line to the options file:
> 
> `vim.cmd([[au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif]])`
> 
> And if you want a permanent undo you have to add the following line:
> 
> `opt.undofile = true`

I'll test this , lemme see if it's worth adding

**Comment by siduck76** [comment]
> Opening a file where you last left off is as simple as adding this line to the options file:
> 
> `vim.cmd([[au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif]])`
> 
> And if you want a permanent undo you have to add the following line:
> 
> `opt.undofile = true`

Does this thing depend on git?

**Comment by EasyS7** [comment]
It does not.

This line `if expand('%:p') !~# '\m/\.git/'` means if the file path contains .git don't remember file position. The rest of the conditional is sufficient if you want to remember the last cursor position in all files.

:h line() for more information

**Comment by siduck76** [comment]
> It does not.
> 
> This line `if expand('%:p') !~# '\m/\.git/'` means if the file path contains .git don't remember file position. The rest of the conditional is sufficient if you want to remember the last cursor position in all files.
> 
> :h line() for more information

nice! btw the opening file part makes has some impact on nvim's startuptime by 50 ms ~ . So i'll include that in the config but keep it disabled by default , (commented).
