### ISSUE TITLE
error coming after cloning the config

### ISSUE THREAD

**Issue by v-d-k** [siduck76/NvChad#1970]
Error detected while processing /home/dinesh/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/dinesh/.config/nvim/lua/core/init.lu
a:67: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/dinesh/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/dinesh/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue

**Comment by siduck** [comment]
please install neovim v0.8.3  +

**Comment by CBroz1** [comment]
I'm experiencing a similar issue after using linuxbrew to install neovim with an Ubuntu variant (OS: Pop!_OS 22.04 LTS x86_64)
```console
> nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by siduck** [comment]
> I'm experiencing a similar issue after using linuxbrew to install neovim with an Ubuntu variant (OS: Pop!_OS 22.04 LTS x86_64)
> 
> ```
> > nvim --version
> NVIM v0.9.0
> Build type: Release
> LuaJIT 2.1.0-beta3
> ```

could you make a video of this? first remove all nvim related dirs then install nvchad

**Comment by CBroz1** [comment]
> could you make a video of this? first remove all nvim related dirs then install nvchad

Is that just my `~/.config/nvim`? Or are there others?

**Comment by siduck** [comment]
> > could you make a video of this? first remove all nvim related dirs then install nvchad
> 
> Is that just my `~/.config/nvim`? Or are there others?

rm -rf .local/share/nvim

**Comment by CBroz1** [comment]
After clearing these directories, I wasn't able to replicate my previous errors. Thanks for your attention to this

**Comment by siduck** [comment]
> After clearing these directories, I wasn't able to replicate my previous errors. Thanks for your attention to this

![image](https://user-images.githubusercontent.com/59060246/236587289-54de7d59-a2c5-491d-80fa-3a07f7366cfd.png)

**Comment by CBroz1** [comment]
Unfortunately, the [tutorial](https://www.youtube.com/watch?v=Mtgo-nP_r8Y) I followed failed to mention this step or direct to official documentation. I apologize for not pursuing the docs further. They've been helpful since
