### ISSUE TITLE
Tmux navigation is not working 

### ISSUE THREAD

**Issue by yuvarajmadineni** [siduck76/NvChad#1971]
**Describe the bug**
I have installed the vim-tmux-navigator plugin in both nvchad and tmux and configured the navigation keys , but the navigation is not working when I am in nvim , but working without nvim in tmux

**To Reproduce**
1. Install vim-tmux-navigator plugin in both tmux and nvim 
2. Set keymappings for navigation same as nvim 
3. Try navigating by opening neovim
4. The navigation is not working

**Expected behavior**
The navigation should work as expected
**Screenshots**

**Desktop (please complete the following information):**
 - Macos
 - Iterm2 
 - Version of Neovim: 0.9.0

**Additional context**
Here in the attached recording , I am able  to switch between panes in tmux normally , but when I entered into nvim the navigation is not working (<C-l> right navigation)

https://user-images.githubusercontent.com/43857118/235319125-200066c1-6127-410f-8749-f9d564b26432.mp4

**Comment by siduck** [comment]
hi @yuvarajmadineni  just disable ctrl+h/j/k/l in nvchad, these are the default mappings in nvchad which let us move through windows .

read https://nvchad.com/docs/config/mappings
