### ISSUE TITLE
Odd lazy-load Comment.nvim, mappings.lua, and which-key.nvim interaction

### ISSUE THREAD

**Issue by sudorook** [siduck76/NvChad#1972]
**Describe the bug**

I tried out this project, and I ran into some perplexing default behavior with the Comment.nvim integration.

First, Comment.nvim is lazy-loaded by default, so newly opened files do not have its default keybindings enabled.

Instead, mappings.lua creates new comment key-mappings that directly call the package:
```lua
M.comment = {
  plugin = true,

  -- toggle comment in both modes
  n = {
    ["<leader>/"] = {
      function()
        require("Comment.api").toggle.linewise.current()
      end,
      "toggle comment",
    },
  },

  v = {
    ["<leader>/"] = {
      "<ESC><cmd>lua require('Comment.api').toggle.linewise(vim.fn.visualmode())<CR>",
      "toggle comment",
    },
  },
}
```

Only after entering these mappings does Comment.nvim get loaded, after which `<leader>/` mappings for commenting things out line-wise exist **in addition to** the default Comment.nvim mappings (e.g. `gcc`, `gbc`, etc.).

If I try Comment.nvim mappings before it is actually loaded, they do nothing except in the case where pressing `gc` as part of `gcc` clashes, I think, with which-key.nvim. It causes a command completion glossary to open. When the `mappings.lua` shortcuts are entered, though, Comment.nvim is loaded, and its default mappings are enforced. Pressing `gc` no longer has any alternate effect.

**Desktop (please complete the following information):**
 - Arch Linux
 - kitty
 - NVIM v0.9.0

**Additional context**

Is this really the intended behavior? Would it not make more sense to either:

1) Override all the default Comment.nvim bindings when it is loaded in order to avoid adding superfluous key combinations (and the `gc` which-key clash), or
2) Have the mappings.lua configuration match the Comment.nvim bindings (and remap `gc` for which-key)?

**Comment by siduck** [comment]
@sudorook alright I added lazyloading of comment.nvim with gcc and gbc keys now

**Comment by cusxio** [comment]
I don't think this is fixed.

As reported by the issue, on initial load (open `nvim`), `gcc`, and `gbc` does not work.

The keys (`gcc/gcb`)  are only activated after  `<leader>/`. For some reason.
