### ISSUE TITLE
Novim-mode plugin does not work

### ISSUE THREAD

**Issue by agoodfellow123** [siduck76/NvChad#1973]
**Describe the bug**
I installed the plugin 'tombh/novim-mode'. Unfortunately, it did not take effect. I can see it in the installed plugins list however my keybinds are still Vim keybinds.

**To Reproduce**
Install the 'tombh/novim-mode' by:
Adding:  `M.plugins = 'custom.plugins'` to chadrc.lua inside lua/custom/
Writing these to plugins.lua:
```
local plugins = {
	{
		"tombh/novim-mode"
	}
}
return plugins
```
And restarting Nvim

**Expected behavior**
Use Nvchad with CUA keybindings.

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - Terminal: Alacritty
 - Version of Neovim: v0.9.0

**Additional Information**
I did try the plugin with vanilla Nvim and it did work so it's not a problem with the plugin itself.

**Comment by siduck** [comment]
```lua
{ 
  "tombh/novim-mod", 
   event = "VeryLazy"
 }
 ```
