### ISSUE TITLE
C-v in nvim-tree will not open a file in vertical split, although C-x can open a file in horizontal split. 

### ISSUE THREAD

**Issue by hopezh** [siduck76/NvChad#1976]
**Describe the bug**
1) Using C-v in nvim-tree will not open a file in a vertical split. 
2) Got the following error: 
```
paste: Error executing lua: vim/_editor.lua:0: Vim:E21: Cannot make changes, 'modifiable' is off^@stack traceback:^@^I[C]: in function 'nvim_put'^@^Ivim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**To Reproduce**
1. use Space-e to focus on nvim-tree
2. select a file
3. C-v to open the selected file in vertical split
4. See the error as shown above
5. Strangely, C-x can open a file in a horizontal split. 

**Expected behavior**
C-v should open a selected file in a vertical split. 

**Screenshots**
![2023-04-30 23 59 42](https://user-images.githubusercontent.com/23435810/235363291-6e3707b9-a47b-4c43-bddf-977768a100b3.png)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 22.04 installed in vmware in Windows 11 
 - Terminal: Alacritty
 - Version of Neovim: v0.10.0-dev-198+gd321deb4a-Homebrew

**Additional context**
Nil.

**Comment by siduck** [comment]
unable to reproduce, please make a video and use 0.9 or 0.8.3


https://user-images.githubusercontent.com/59060246/235388412-92e7f02b-3197-45d5-a362-4087a1b911a7.mp4

**Comment by dreznicek** [comment]
This is happening for me as well.

- Ubuntu 20.04 in WSL2 on windows 10
- Completely fresh NvChad install (`rm -fr` on ~/.config/nvim and ~/.local/share/nvim and then `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim` and `y` on default config )
- brew install neovim, so its on `stable 0.9.0 (bottled), HEAD`

It might be worth noting that I can do a `:vsplit` and that works fine.

**Comment by dreznicek** [comment]
I figured it out. Windows Terminal was hijacking the `Ctrl+v` as _paste_. I remapped paste to be `Ctrl+Shift+v` in Windows Terminal, and now it works as intended in nvim-tree.
