### ISSUE TITLE
Telescope open files in insert mode

### ISSUE THREAD

**Issue by yoplat** [siduck76/NvChad#1978]
**Describe the bug**
When using telescope to open files (find files or old files) the file buffer gets opened in insert mode

**To Reproduce**
1.  Launch Neovim
2. Launch telescope find files or old files
3. Select a file and open it

**Expected behavior**
Open buffer/file in normal mode

**Desktop:**
 - Operating System MacOS
 - Terminal Alacritty
 - Version of Neovim 0.9

**Comment by siduck** [comment]
unable to produce :/

**Comment by yoplat** [comment]
> unable to produce :/

The only thing i have added for telescope are this opts:
  defaults = {
    mappings = {
      i = {
        ["<esc>"] = require("telescope.actions").close,
        ["<C-j>"] = require("telescope.actions").move_selection_next,
        ["<C-k>"] = require("telescope.actions").move_selection_previous,
      },
    }
  }

Would you need anything else to help?

**Comment by siduck** [comment]
> > unable to produce :/
> 
> The only thing i have added for telescope are this opts: defaults = { mappings = { i = { [""] = require("telescope.actions").close, [""] = require("telescope.actions").move_selection_next, [""] = require("telescope.actions").move_selection_previous, }, } }
> 
> Would you need anything else to help?

remove them, does the problem persists?

**Comment by yoplat** [comment]
> > > unable to produce :/
> > 
> > 
> > The only thing i have added for telescope are this opts: defaults = { mappings = { i = { [""] = require("telescope.actions").close, [""] = require("telescope.actions").move_selection_next, [""] = require("telescope.actions").move_selection_previous, }, } }
> > Would you need anything else to help?
> 
> remove them, does the problem persists?

Just tried, still happening.
I have made my custom config repo public,
this is the link if you have the time to test it your self: https://github.com/carlobonandriniunimi/CustomNvChad.
I tried it on both my macbook and my linux machine and the problems still occurs.

**Comment by siduck** [comment]
does it happen without custom dir? back it up and check

**Comment by siduck** [comment]
@carlobonandriniunimi i can reproduce this issue when I compiled nvim from source , not 0.9 stable release. I think its an upstream issue so closing this

**Comment by siduck** [comment]
wait this doesnt happen when I disabled the tabufline, also duplicate of https://github.com/NvChad/ui/issues/89

**Comment by yoplat** [comment]
> @carlobonandriniunimi i can reproduce this issue when I compiled nvim from source , not 0.9 stable release. I think its an upstream issue so closing this

Oh yeah i forgot that i was running 0.10 on this machine, downgrading fixed it thanks!

**Comment by kevinrambaud** [comment]
> @carlobonandriniunimi i can reproduce this issue when I compiled nvim from source , not 0.9 stable release. I think its an upstream issue so closing this

Thanks for that @siduck. I was running into the same issue, and it was indeed related to the latest version of neovim built from the source. Using the stable version resolves this issue.
