### ISSUE TITLE
`s` remap to `cl`

### ISSUE THREAD

**Issue by mikaizhu** [siduck76/NvChad#1979]
i am using:
- Apple M2 Ventura 13.0.1
- kitty
- NVIM v0.8.3

**Describe the bug**
`s` remap to `cl`

**To Reproduce**

1. install nvchad `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
2. install default custom config
3. open a file
4. type `s` and it will remap to `cl`

**Expected behavior**
i want to use `leap` plugin，when i use it，`s` do not work，i found `s` remap to `cl`

**Comment by siduck** [comment]
leap.nvim maps "s" to something else , check 

![image](https://user-images.githubusercontent.com/59060246/235419984-c02f7ad4-2438-4160-b145-879221b0ae7d.png)


not a nvchad issue

**Comment by mikaizhu** [comment]
but i am using default nvchad custom config ， it dont hava leap nvim plugin
<img width="949" alt="image" src="https://user-images.githubusercontent.com/59464933/235420885-084e778b-5fcd-447b-8774-2a32f3e54356.png">

it still will remap `s` to `cl`

**Comment by mikaizhu** [comment]
> leap.nvim maps "s" to something else , check
> 
> ![image](https://user-images.githubusercontent.com/59060246/235419984-c02f7ad4-2438-4160-b145-879221b0ae7d.png)
> 
> not a nvchad issue

but i am using default nvchad custom config ， it dont hava leap nvim plugin
<img width="949" alt="image" src="https://user-images.githubusercontent.com/59464933/235420885-084e778b-5fcd-447b-8774-2a32f3e54356.png">

it still will remap `s` to `cl`

**Comment by siduck** [comment]
@mikaizhu  very weird, `map s` command says no mapping found

**Comment by mikaizhu** [comment]
> @mikaizhu very weird, `map s` command says no mapping found

your env also have this problem？in nvchad v1 it works fine

**Comment by siduck** [comment]
> > @mikaizhu very weird, `map s` command says no mapping found
> 
> your env also have this problem？in nvchad v1 it works fine

no

**Comment by mikaizhu** [comment]
> > > @mikaizhu very weird, `map s` command says no mapping found
> > 
> > 
> > your env also have this problem？in nvchad v1 it works fine
> 
> no

![test](https://user-images.githubusercontent.com/59464933/235444463-69dc3a49-8a34-4f56-9e0b-d68d8134b1c8.gif)

**Comment by siduck** [comment]
can you try another terminal? like kitty/alacritty

**Comment by mikaizhu** [comment]
> 

yep, i am using kitty right now

and i tried iterm2, also this problem

**Comment by siduck** [comment]
very weird, "s" works perfectly here. Do you face this issue with nvim --clean?

**Comment by mikaizhu** [comment]
nvim --clean works fine here, won't remap s to cl

**Comment by mikaizhu** [comment]
i am using:
- Apple M2 Ventura 13.0.1
- kitty
- NVIM v0.8.3

**Comment by siduck** [comment]
ugh i cant find any way to reproduce this D:

**Comment by mikaizhu** [comment]
> ugh i cant find any way to reproduce this D:

thanks! 
this is my Nvchad config: https://github.com/mikaizhu/MyVim
In this config, I can't use 'leap.nvim' plugin.
Both in my local env(Mac OS) and remote ssh env(Ubuntu 20.04).
I don't kown why this config not working. Can you help me check if there are any problems in the configuration file?

**Comment by siduck** [comment]
@mikaizhu  dm me on tg discord etc , links are on my profile https://github.com/siduck

EDIT : guys the issue was that leap.nvim overrides vanilla  vim mappings like S and s 

just make your own mappings out of these
```
          vim.fn.feedkeys("S", "n")
          vim.fn.feedkeys("n", "n")
```
