### ISSUE TITLE
Not an editor command: Telescope

### ISSUE THREAD

**Issue by YevhenKap** [siduck76/NvChad#198]
**Describe the bug**
After installing NvChad configuration I am trying to execute `<leader>ff` command and it gives me an error:

```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:77: Vim:E492: Not an editor command: Telescope find_files                                                   
Please check your config for correctness
```

**Expected behavior**
Execute Telescope's _find\_files_ command

**Desktop (please complete the following information):**
 - Operating System: macOS 10.15.7
 - Terminal: Hyper
 - Version of Neovim: 0.5.0

**Comment by siduck76** [comment]
:PackerSync and :PackerCompile

**Comment by YevhenKap** [comment]
Thanks. I have tried those commands several times, but I had compiled  at first and then synced 😅
