### ISSUE TITLE
Issue while cloning the repository

### ISSUE THREAD

**Issue by sundaram123krishnan** [siduck76/NvChad#1980]
I am getting an error after cloning the repository /home/sundaram/.config/nvim/lua/core/init.
![Screenshot from 2023-05-01 11-44-55](https://user-images.githubusercontent.com/104441812/235415641-18452838-4f75-47b9-9bcb-e5bf2884edfc.png)
lua:77: attempt to index field 'fs' (a nil value)

**Desktop (please complete the following information):**
 - Operating System - Linux
 - Terminal - zsh
 - Version of Neovim  - NVIM v0.7.2

**Comment by siduck** [comment]
rm -rf ~/.local/share/nvim

and please use 0.8.3 nviim at least :cry:

**Comment by sundaram123krishnan** [comment]
ok thx for ur kind response

**Comment by Chris-Gillis** [comment]
@siduck that fixed my problem, thank you!
