### ISSUE TITLE
Breaking changes of Nerd Font 3.0 (icon not showing correctly)

### ISSUE THREAD

**Issue by sorae42** [siduck76/NvChad#1982]
**Describe the bug**
Breaking changes in Nerd Font 3.0 makes certain icons not showing correctly.

**Expected behavior**
The icon should display correctly.

**Workaround**
Install 2.X version of Nerd Font (e.g 2.3.3) instead.

**Screenshots**
<img width="276" alt="Screenshot 2023-05-02 at 02 45 13" src="https://user-images.githubusercontent.com/34794115/235518624-c20d9da9-e9e3-4264-9355-5ab1c17fcf92.png">
<img width="1679" alt="Screenshot 2023-05-02 at 02 47 54" src="https://user-images.githubusercontent.com/34794115/235519007-d4713a36-156f-48b7-9dcf-b1030016550d.png">

**Desktop (please complete the following information):**
 - Operating System: macOS 13.3.1
 - Terminal: kitty 0.28.1
 - Version of Neovim: 0.8.1

**Comment by panoplied** [comment]
Nerd-Fonts introduced breaking change with the code points in their 3.0 release (https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0), but many nvim plugins still use old ones.

Similar issue:
https://github.com/ryanoasis/nerd-fonts/issues/1190

There're some pull request to take a look also:
https://github.com/nvim-tree/nvim-web-devicons/pull/264
https://github.com/onsails/lspkind.nvim/pull/64

**Comment by sorae42** [comment]
Alright I have downgraded, should work for the time being.

Left issue open until fixed.

**Comment by mikaizhu** [comment]
> Alright I have downgraded, should work for the time being.
> 
> Left issue open until fixed.

the same problem, by the way, you say "downgraded", what do you mean? 

you downgrad the OS or something else?

**Comment by sorae42** [comment]
@mikaizhu I downgraded the nerd font back to 2.X.

**Comment by mikaizhu** [comment]
> @mikaizhu I downgraded the nerd font back to 2.X.

I just upgrade mac os system, then get the same problem, emm..

**Comment by sorae42** [comment]
You just have to remove the 3.0 Nerd Font and install the 2.X one.

**Comment by mikaizhu** [comment]
> You just have to remove the 3.0 Nerd Font and install the 2.X one.

I think I am not using 3.0 Nerd Font, because I never download it.

I tried to download 2.x Nerd Font, and replace `Hack` ttf files, but still the wrong icon...

**Comment by siduck** [comment]
not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues

**Comment by sorae42** [comment]
Just a reminder to mention that the 3.0 nerd font is not compatible with NvChad or its plugins due to breaking changes so you might want to update it, as mentioned by @panoplied above.

**Comment by siduck** [comment]
> Just a reminder to mention that the 3.0 nerd font is not compatible with NvChad or its plugins due to breaking changes so you might want to update it, as mentioned by @panoplied above.

NO IT IS COMPATIBLE BRUH! 

did you not see our icons in our theme screenshots on nvchad.com?  All of them have proper icons. Please use another terminal :sob:

**Comment by siduck** [comment]
nvm it, i misread the issue. didnt know nerdfonts updated yesterday, will look into this

**Comment by panoplied** [comment]
> Just a reminder to mention that the 3.0 nerd font is not compatible with NvChad or its plugins due to breaking changes so you might want to update it, as mentioned by @panoplied above.

If I understand the issue correctly, it's a bit more complex, and making stuff straightforward compatible with NF 3.x would most probably break it on 2.x. So maybe a flag/option?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/235638234-948cbde5-c72c-410f-8294-c7f5d82448a5.png)

Try copying this into your terminal, this exact icon wouldnt be displayed, it'll show a different icon ( outline dir icon ) weird

**Comment by sorae42** [comment]
I'd suggest having a way to tell people to install the 2.X ver instead (like pin an issue regarding this), so you don't have to worry about upgrading.

**Comment by kqualters-elastic** [comment]
I inadvertently broke this with brew upgrade, had to uninstall my font of choice, then reinstall an older version manually, `curl https://raw.githubusercontent.com/Homebrew/homebrew-cask-fonts/c6f6dbdf5da109fdcc01d86703bd7d64329f143d/Casks/font-mononoki-nerd-font.rb > font-mononoki-nerd-font.rb && brew install --cask font-mononoki-nerd-font.rb`

**Comment by Pludam** [comment]
This could also be solved by creating an second config for the plugin with the version number of nerd font and the right glyphs 
eg. 3.0.0 for the New version and 2.x for the old one. 
then edit the init.lua file  to match the version of the font you have installed

**Comment by Pludam** [comment]
@siduck that's because the website is still on 2.3.3

**Comment by siduck** [comment]
> @siduck that's because the website is still on 2.3.3

ugh!

**Comment by mehalter** [comment]
@siduck I just finished fixing this over on AstroNvim, I used this nerdfix tool and it was perfect: https://github.com/loichyan/nerdfix

It tells you recommendations for replacements of deprecated icons which basically just tells you the new location of the material design icon. You can just run it across all of the files in the project and it should work :)

I would just `cd` into the repo folders and run 

```sh
find -type f -name '*.lua' -exec nerdfix check {} \;
```

**Comment by Pludam** [comment]
Maybe im making an PR with this in the next week or so with an separate file for the changes so its compatible with 2.x and 3.x

**Comment by siduck** [comment]
> Maybe im making an PR with this in the next week or so with an separate file for the changes so its compatible with 2.x and 3.x

no need, I'd want to support only 3.x

**Comment by siduck** [comment]
hi guys is this icon removed?  couldnt find it via fontforge too, can anyone find it please
 

![image](https://user-images.githubusercontent.com/59060246/235812660-943196af-6117-4aa8-96bf-48e8152dda01.png)

**Comment by Pludam** [comment]
@siduck If you type in the hex value into the search Bar you'll find it but im not sure if it still exists in the font

**Comment by Pludam** [comment]
Alternativly we could use the nf-cod variant of the folder types

**Comment by siduck** [comment]
> Alternativly we could use the nf-cod variant of the folder types

this one is the best looking so far imo, i dont want to lose it :(

**Comment by Pludam** [comment]
Nur ist would be good for consitency behause were currently using different icons for some things

**Comment by Pludam** [comment]
It would be great if we used These because
of consistency

**Comment by siduck** [comment]
> It would be great if we used These because of consistency

yes but if you look at our old folder icon, it looks very similar to these 

![image](https://user-images.githubusercontent.com/59060246/236078376-1af4a47f-f8c8-4797-a9bc-ac98a61c0dcf.png)

just looks like a filled version of it

**Comment by siduck** [comment]
anyways Ive updated our icons so closing this

**Comment by mikaizhu** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/235638234-948cbde5-c72c-410f-8294-c7f5d82448a5.png)
> 
> Try copying this into your terminal, this exact icon wouldnt be displayed, it'll show a different icon ( outline dir icon ) weird

how you fix this problem? I copy icon in my kitty terminal, but it show different icon, and I searched kitty issue, no one mention it..

**Comment by tonnylou44853** [comment]
I am not sure if it is just me but some of the icons on the dashboard are still broken (Recent Files and Find Word). Would you mind having a look at them? Thanks!
<img width="436" alt="Screenshot 2023-05-07 at 15 40 59" src="https://user-images.githubusercontent.com/69238318/236684302-5e130d30-08ec-480b-a0f1-c1cbdffa6288.png">

**Comment by siduck** [comment]
> 

![image](https://user-images.githubusercontent.com/59060246/236686710-3d7f664c-520e-409b-9797-bc256f2d82b3.png)

**Comment by tonnylou44853** [comment]
Interesting... seems like it is a problem on my end. 
Thanks for looking into this!

**Comment by panoplied** [comment]
@tonnylou44853 have you updated your nerd fonts to version 3?

**Comment by tonnylou44853** [comment]
Yes, I am using nerd fonts v3.

In the meantime, I also checked the `default_config.lua` using `nerdfix` just now and it seems like the icons are marked as obsolete (`U+F719` and `U+F72C`), so I thought I might not be the only one that has the same problem?

<img width="530" alt="Screenshot 2023-05-08 at 09 49 47" src="https://user-images.githubusercontent.com/69238318/236780198-69636c65-6173-4b66-a4cb-4a0db5606819.png">

**Comment by sorae42** [comment]
idk if it's just me but nerd fonts v2 still working even though i did update nvchad

not an issue but something odd yeah

**Comment by NorthernBlow** [comment]
> not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues

i still use alacritty but have same problems with icons. why you put icons? its unnecessary  thing

**Comment by siduck** [comment]
> > not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues
> 
> i still use alacritty but have same problems with icons. why you put icons? its unnecessary thing

icons make neovim look very pretty imo. I swear i wouldnt ever touched neovim/vim if it didnt support icons stuff

**Comment by sorae42** [comment]
> > not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues
> 
> i still use alacritty but have same problems with icons. why you put icons? its unnecessary thing

so i can see which file i am looking for

seeing the file extension within a sea of files really hurt my eyes

**Comment by NorthernBlow** [comment]
where those config files exists these icons? i want to delete all icons that statusline uses. 

thanks

**Comment by siduck** [comment]
> where those config files exists these icons? i want to delete all icons that statusline uses.
> 
> thanks

you cant

**Comment by RenanZX** [comment]
The close icon and document icon is not showing to me, have a way to change it? I already checked the nvimtree file, but it's not in there. I'm using hacker nerd font too.

<img width="189" alt="image" src="https://github.com/NvChad/NvChad/assets/20937501/aa485ee1-5c65-45d1-8fda-793cf37a23c0">

<img width="131" alt="image" src="https://github.com/NvChad/NvChad/assets/20937501/baa69783-dc53-4f3a-b9d0-6a32aac7e073">

<img width="614" alt="image" src="https://github.com/NvChad/NvChad/assets/20937501/0ffe0f06-d259-4889-8b02-f244e036f3a6">

**Comment by siduck** [comment]
> The close icon and document icon is not showing to me, have a way to change it? I already checked the nvimtree file, but it's not in there. I'm using hacker nerd font too.
> 
> <img alt="image" width="189" src="https://user-images.githubusercontent.com/20937501/250958665-aa485ee1-5c65-45d1-8fda-793cf37a23c0.png"> <img alt="image" width="131" src="https://user-images.githubusercontent.com/20937501/250958731-baa69783-dc53-4f3a-b9d0-6a32aac7e073.png"> <img alt="image" width="614" src="https://user-images.githubusercontent.com/20937501/250959208-0ffe0f06-d259-4889-8b02-f244e036f3a6.png">

did you    update your nerdfont? try another nerd font and see if it works

**Comment by RenanZX** [comment]
> did you update your nerdfont? try another nerd font and see if it works


Yes, i tried to rollback the nerdfont version too, still not working.

**Comment by siduck** [comment]
> > did you update your nerdfont? try another nerd font and see if it works
> 
> Yes, i tried to rollback the nerdfont version too, still not working.

please try jebtrainsmono nerdfont and set      it in your terminal or try another terminal

**Comment by RenanZX** [comment]
> please try jebtrainsmono nerdfont and set it in your terminal or try another terminal

Found out what was happening, i'm using wsl for windows, but for some reason windows wasn't showing nerd fonts icons, when i opened a new linux tab with ```-d Ubuntu``` in Terminal app configuration, the icons appeared properly.

Thanks

**Comment by remiconnesson** [comment]
> Found out what was happening, i'm using wsl for windows, but for some reason windows wasn't showing nerd fonts icons, when i opened a new linux tab with `-d Ubuntu` in Terminal app configuration, the icons appeared properly.
> 
> Thanks

Hey @RenanZX  I have the same problem, can I ask you what I mean by this? I don't quite understand

**Comment by ammarsaf** [comment]
> not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues

I used zsh where the problem still happened.

**Comment by siduck** [comment]
> > not a nvchad issue. your terminal issue! please use other terminals like kitty alacritty wezterm, iterm2 has some issues
> 
> I used zsh where the problem still happened.

please update your terminal font

**Comment by kosmonavtus** [comment]
> please update your terminal font

Actually updating fonts doesn't help, that's why people came to this thread....

**Comment by siduck** [comment]
> > please update your terminal font
> 
> Actually updating fonts doesn't help, that's why people came to this thread....

update all nvim plugins and nvchad too :/

**Comment by alexrosen45** [comment]
> > > please update your terminal font
> > 
> > 
> > Actually updating fonts doesn't help, that's why people came to this thread....
> 
> update all nvim plugins and nvchad too :/

I'm having this issue after a fresh install of everything today

**Comment by siduck** [comment]
> > > > please update your terminal font
> > > 
> > > 
> > > Actually updating fonts doesn't help, that's why people came to this thread....
> > 
> > 
> > update all nvim plugins and nvchad too :/
> 
> I'm having this issue after a fresh install of everything today

i cant do anything about it then, seek help in our discord server

**Comment by dgokcin** [comment]
@sorae42 is the icon at the bottom left corner next to the vim mode is coming from a nerdfont or it is a part of a custom plugin?

**Comment by sorae42** [comment]
> @sorae42 is the icon at the bottom left corner next to the vim mode is coming from a nerdfont or it is a part of a custom plugin?

It's all nerd font

**Comment by dgokcin** [comment]
> > @sorae42 is the icon at the bottom left corner next to the vim mode is coming from a nerdfont or it is a part of a custom plugin?
> 
> It's all nerd font

@sorae42 may I please ask what is the font that you are using?

**Comment by isggwp** [comment]
fresh install after using nvchad and use nerd font but still
<img width="699" alt="Screenshot 2024-07-04 at 18 29 17" src="https://github.com/NvChad/NvChad/assets/15064152/ead5163b-4ded-4073-a4e2-3bec41e42d36">

**Comment by siduck** [comment]
thats clearly terminal issue @isggwp
