### ISSUE TITLE
custom defined plugin not loading with certain keys

### ISSUE THREAD

**Issue by damca** [siduck76/NvChad#1984]
# Setup
* neovim 0.9.0
* fresh install of NvChad
* choose "yes" to example custom config

## custom/plugins.lua
```lua
  -- Install a plugin
  {
    "christoomey/vim-tmux-navigator",
    keys = { "<leader>", "<C-j>", "<C-k>", "<C-h>", "<C-l>"}
  },
```

## Observation

The plugin loads successfully with `<leader>`, but not with any of the control commands `<C-j>`, etc.

Upon loading a fresh nvim session and performing `:nmap` prior to the plugin loading I can see the following:

```
︙
n  <Space>     * <Lua 31: ~/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:67>
︙
n  <C-J>       * <C-W>j
                 window down
︙
```
And after triggering loading, the \<C-j\> mapping becomes:
```
︙
   <C-J>       * :<C-U>TmuxNavigateDown<CR>
︙
```
As intended.

But the question remains: why do the `<C-j>, <C-k>, etc.` commands not trigger plugin loading?

## My guess

It seems that `<Space>` and other keys bound by lazy plugins occurs within the `plugins/init.lua` module. However, the `core/mappings.lua` seems to somehow prevent keys being bound by definitions within `custom/plugins.lua`.

Any thoughts on how to remedy this?

**Comment by siduck** [comment]
hi @damca  C-hjkl are our default mappings, just disable them in your custom mappings section, if you dont know how to do it, read our docs!

**Comment by damca** [comment]
Thanks! That fixed it for me. I added the following to `custom/mappings.lua`:

```lua
M.disabled = {
  n = {
    -- Disable to allow the plugin nvim-tmux-navigator to bind (see custom/plugins.lua)
    ["<C-h>"] = "",
    ["<C-l>"] = "",
    ["<C-j>"] = "",
    ["<C-k>"] = "",
  }
}


```
