### ISSUE TITLE
Which-key should be loaded (or reloaded) after other plugins

### ISSUE THREAD

**Issue by Thanatermesis** [siduck76/NvChad#1985]
Im adding custom plugins on the /custom/ directory, and also extra mapped keys, they show nicely on the which-key feature, but this only happens when I re-select the colorscheme, otherwise they don't show up

Seems like which-key is not really loading after all the gui / plugins as how it says on his configuration comment, or at least not after the ones in the /custom/ user-defined plugins, I have tried to set on the which-key config all the "lazy" configurations from the docs like priority, VeryLazy event, etc... none of them works, the only way was with "lazy = false" on my custom plugins, but as the NvChad documentation says it is strongly suggested to lazy-load all the plugins.

I think "which-key" should be loaded really after all other plugins has been loaded / set up, so that it can show correctly all the key mappings of all the plugins, if this is not possible, maybe it's needed to add a code that re-loads which-key after some time passed since neovim has been launched in order to reload the keymappings to list them correctly 🤔

**Comment by siduck** [comment]
usually plugin mappings load before the plugin loads, which mappings are you missing?

**Comment by mikaizhu** [comment]
I think 'which-key' plugin may have conflict with 'leap.nvim' plugin, the default 'leap' use "s" to leap forward search, and if I use "sv" or "sh" to split windows, I found key "s" will not activate leap plugin..., I don't know if your env is working or not.

I tried in Ubuntu 20.04, `leap` and 'which-key' seem conflict.

**Comment by Thanatermesis** [comment]
@mikaizhu this is a different issue, what is this issue about is that the plugin which-key is not showing the mappings defined by the user from /custom/ plugins & mappings unless you reload the colorscheme a few seconds later. About your issue i don't think the issue is which-key which basically is for showing your mappings, but probably the issue is in your mapping, try to disable your sv/sh mappings to see if leap works and if does, then you need to remap your sv/sh in a way that makes it compatible, maybe using the "nowait" parameter

**Comment by Thanatermesis** [comment]
@siduck They are for the extra plugins I added (so in the /custom/ directory), to make my life easier I added mappings for them like toggles, but they don't appear on the whichkey list unless I add them in the main mappings which is not what the want (modifications should be made only on /custom/ dir), I know that they works because reloading the colorscheme lists them (probably similar to if i reload the whichkey plugin later)

**Comment by siduck** [comment]
{
    "folke/which-key.nvim",
    event = "VeryLazy"
  },
  
  works for me @Thanatermesis  , please check Lazy command to see if its loaded
  
  @Thanatermesis its normal bruh! mappings must be defined before plugins load, see how we do it for default plugins, 
  
  If you dont want to do this, remove lazyloading for your plugin and load at VeryLazy event at least

**Comment by Thanatermesis** [comment]
@siduck I think the issue is elsewhere, I already tried many "lazy" settings without change so maybe this is not the issue 🤔, did this setting changed anything on your side? here is the same

I recorded a video to show what exactly is happening: https://www.youtube.com/watch?v=nPqAXg8F0gk  (jump directly to minute 1:01 to see the issue)

**Comment by mikaizhu** [comment]
> @mikaizhu this is a different issue, what is this issue about is that the plugin which-key is not showing the mappings defined by the user from /custom/ plugins & mappings unless you reload the colorscheme a few seconds later. About your issue i don't think the issue is which-key which basically is for showing your mappings, but probably the issue is in your mapping, try to disable your sv/sh mappings to see if leap works and if does, then you need to remap your sv/sh in a way that makes it compatible, maybe using the "nowait" parameter

I tried disable "which-key", and make "leap.nvim" event=VeryLazy, then check the verbose of map s, `:verbose map s`

<img width="354" alt="image" src="https://user-images.githubusercontent.com/59464933/236364451-24c941ac-641e-4548-801b-7c6e73aaec5c.png">

I don't kown why "s" doesn't work. and this is the verbose of map S, key "S" can leap-backword-to search,

<img width="472" alt="image" src="https://user-images.githubusercontent.com/59464933/236364589-9f47b6e4-60c9-4db6-89af-b9724cae990c.png">

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/236375363-74970018-dcc8-4da0-a16c-cd3c83bd2c27.png)

@Thanatermesis watching the vid right now, you should load the mappings in the init folder or else they will not be available by default. 

Also i dont think it makes sense to load cmp mappings by default because we use cmp only in insert mode so at insertenter event cmp loads, then you should load its mappings

**Comment by siduck** [comment]
It works when you change the colorscheme because, to change nvchad colorscheme you open our telescope theme switcher whose prompt is in insert mode, which then activates cmp plugin and cmp plugin then loads your mappings.

if you want to load mappings at start, put them at the "init" function here 

![image](https://user-images.githubusercontent.com/59060246/236375809-4e425aca-d2c1-4aaf-9ea9-e44e450942c7.png)

you put it in your opts or config function i think which loads only after the plugin loads where as "init" function loads at startup

**Comment by Thanatermesis** [comment]
Ooooh I see! Thank you, it seems to work now by moving them to the "init" function, these settings are very dynamic and not easy to understand :)

**Comment by siduck** [comment]
> Ooooh I see! Thank you, it seems to work now by moving them to the "init" function, these settings are very dynamic and not easy to understand :)

what do you not understand? tell me, i'll explain properly
