### ISSUE TITLE
Change the Neovim install link to 0.8.3 instead of 0.8.0

### ISSUE THREAD

**Issue by ManishAradwad** [siduck76/NvChad#1986]
**Describe the bug**
In the official docs, the suggested neovim version is 0.8.3 but link takes you to 0.8.0

0.8.0 causes issues after installation since, nvim-treesitter expects 0.8.3+ neovim version

**Expected behavior**
Here's the 0.8.3 version link: https://github.com/neovim/neovim/releases/tag/v0.8.3
Just needs to be changed in the docs

**Comment by siduck** [comment]
done
