### ISSUE TITLE
vim.treesitter.query.get_query() is deprecated

### ISSUE THREAD

**Issue by Zaedus** [siduck76/NvChad#1988]
**Describe the bug**
When I press 'o' to go down a new line it gives the following error. This only happens when a lsp is active.
![image](https://user-images.githubusercontent.com/42098470/236234393-6ac74ed6-a4a7-4be8-a5db-0df7ec2fa90b.png)

**To Reproduce**
1. Start a language server by some means
2. Press 'o' in the file the language server is active in
4. See warning

**Expected behavior**
There should be no deprecation warning ideally. This isn't the end of the world, but seeing it every time gets a little annoying.

**Desktop (please complete the following information):**
 - Arch Linux x86_64
 - Alacritty, Blackbox (this is a terminal agnostic problem)
 - NVIM v0.9.0, Build type: Release, LuaJIT 2.1.0-beta3

**Additional context**
I haven't seen this error reported, so I'm guessing that this issue is specific to me. Either way, any help would be lovely.

**Comment by siduck** [comment]
@lucario387 any idea?

**Comment by lucario387** [comment]
Not nvim-treesitter's fault. It has updated to mitigate the warning for nearly 2 months by now

**Comment by siduck** [comment]
@Zaedus update all of your plugins , if still doesnt work then rm -rf .local/share/nvim and run nvim command
