### ISSUE TITLE
Starting neovim error in init.lua

### ISSUE THREAD

**Issue by nathanpena** [siduck76/NvChad#1991]
**Describe the bug**
In Ubuntu 22.04.2 LTS I installed the latest NvChad and then attempted to open neovim.

Getting this error:

![image](https://user-images.githubusercontent.com/9323627/236281348-6447f89b-f3e3-4548-b60a-1210c4f398bf.png)

**Comment by siduck** [comment]
hi @nathanpena , install v0.8.3 of nvim at least

**Comment by nathanpena** [comment]
thank you @siduck.  That worked.
