### ISSUE TITLE
Lua Error loading custom mappings

### ISSUE THREAD

**Issue by kleemeo** [siduck76/NvChad#1995]
**Describe the bug**
I am trying to load a custom mappings into NvChad and I keep getting a `bad argument for 'pair'` error. Looking at the utils, it seems like it's from the utils function where it's looping in the function `remove_disabled_keys`. Maybe I formatted the table wrong in lua? Maybe just need more eyes on my setup. Thank you!

I can't seem to see why it's not iterating the custom mapping that I followed from the docs. It keeps taking it as wrong type?

**Reproduce**
1. Add `M.mappings = require 'custom.mappings'` to `custom/chadrc.lua`
```lua
-- custom/chadrc.lua
local M = {}
M.mappings = require 'custom.mappings'
M.ui = { theme = 'chadtain' }
M.plugins = 'custom.plugins'
return M
```
2. Adding this custom mapping in `custom/mappings.lua`
```lua
-- custom/mappings.lua
local M = {}

M.abc = {
  n = {
     ["<A-k>"] = {":m-2<CR>", "Move line up"},
     ["<A-s>"] = {":m+<CR>", "Move line down"} 
  }
}
return M
```
3. Save in `chadrc.lua` triggers error for loading the mappings file
```shell
Error detected while processing BufWritePost Autocommands for "/Users/root/.config/nvim/lua/custom/chadrc.lua":                                 
Error executing lua callback: /Users/root/.config/nvim/lua/core/utils.lua:26: bad argument #1 to 'pairs' (table expected, got boolean)          
stack traceback:                                                                                                                                
        [C]: in function 'pairs'                                                                                                                
        /Users/root/.config/nvim/lua/core/utils.lua:26: in function 'remove_disabled_keys'                                                      
        /Users/root/.config/nvim/lua/core/utils.lua:11: in function 'load_config'                                                               
        /Users/root/.config/nvim/lua/core/init.lua:91: in function </Users/root/.config/nvim/lua/core/init.lua:82>  
```

Tracing to `core/utils.lua:26` function:
```lua
-- ...
M.remove_disabled_keys = function(chadrc_mappings, default_mappings)
  if not chadrc_mappings then
    return default_mappings
  end

  -- store keys in a array with true value to compare
  local keys_to_disable = {}
  for _, mappings in pairs(chadrc_mappings) do
    for mode, section_keys in pairs(mappings) do
      if not keys_to_disable[mode] then
        keys_to_disable[mode] = {}
      end
      section_keys = (type(section_keys) == "table" and section_keys) or {}
      for k, _ in pairs(section_keys) do
        keys_to_disable[mode][k] = true
      end
    end
  end
-- ...

```

**Screenshots**

**OS**
 - Mac OSX 12.6
 - Kitty

**Comment by siduck** [comment]
are   you using nvchad v2.0?

**Comment by kleemeo** [comment]
I used this when installing: https://nvchad.com/docs/quickstart/install
`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
(last weekend)

would that be v2? so is it just syntax difference for lazy?

**Comment by kleemeo** [comment]
I just tried it again, the error is gone. But the mappings doesn't seem to work.

`<A-j>` and `<A-k>`

**Comment by kleemeo** [comment]
Hi @siduck,

Thanks for such a great starter base for nvim.

I figured it out in the end, for Mac, Alt/Option is not registered the same?

so I had to use the symbol it produces as the key. Not sure if it's the best way to map the keys, but it works for my use cases. Thanks again!

```lua
     ["˚"] = {"<cmd>m-2<CR>", "Move line up"},
     ["∆"] = {"<cmd>m+<CR>", "Move line down"},
```

(love how it also gets loaded into cheatsheet automatically!)

**Comment by alexklann** [comment]
Getting the exact same error when adding the `M.mappings = require 'custom.mappings'` line.
Custom.mappings indeed exists and it has the default content from the docs.

chadrc.lua
```lua
local M = {}

M.ui = { theme = 'onedark' }

M.mappings = require 'custom.mappings'

return M

```

mappings.lua
```lua
local M = {}

-- In order to disable a default keymap, use
M.disabled = {
  n = {
      ["<leader>h"] = "",
      ["<C-a>"] = ""
  }
}

-- Your custom mappings
M.abc = {
  n = {
     ["<C-n>"] = {"<cmd> Telescope <CR>", "Telescope"},
     ["<C-s>"] = {":Telescope Files <CR>", "Telescope Files"} 
  },

  i = {
     ["jk"] = { "<ESC>", "escape insert mode" , opts = { nowait = true }},
    -- ...
  }
}

return M

```

Edit: It randomly worked again

**Comment by fedesilvaponte** [comment]
Having the same issue here. Anyone figured out how to fix it?
