### ISSUE TITLE
How can I change the icons and colors of files in nvim-tree?

### ISSUE THREAD

**Issue by fuqianya** [siduck76/NvChad#1996]
**Describe the bug**
I would like to customize the appearance of nvim-tree by modifying some of its icons and file colors. For example, I want to change the icon used for the LICENSE file and alter the color of the README file shown below.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/45023083/236599279-932e3f4e-3750-4102-9698-27ec830d1af3.png">

Firstly, to change the icon used for the LICENSE file, I tried to override the default icons in the [nvchad_ui](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/icons.lua) and `nvim-web-devicons`. To achieve this, I added the following configuration into `lua/custom/chadrc.lua`:
```
 M.ui = {
  icons = {
    icon = "",
    color = "#51a0cf",
    cterm_color = "74",
    name = "License",
}
```
However, it's not working. Could you please provide me with an example of how to override the icons in the [nvchad_ui](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad_ui/icons.lua).

Secondly, I would like to modify the color of the README file since it looks different from the other files. I want to change the README file's color to white to match that of the other files. After searching through the issues, I found a convenient way to change the icons' color [here](https://github.com/NvChad/NvChad/issues/1752). However, I am unsure how to modify the color of filenames. Could you please advise?

**Comment by DoctorKnowsBetter** [comment]
Dear Developers. The main problem is that the colors specified in **base46/integrations** can't be changed via **hl_override** or **hl_add**. And it makes you very uncomfortable.

**Comment by DoctorKnowsBetter** [comment]
@fuqianya your problem is solved as follows, this applies to colors not defined in base46/integrations:

1. Copy the file ui/lua/nvchad_ui/icons.lua to the custom directory and change/add the devicons you want.
2. Then add the plugin as follows:
```
{
        "nvim-tree/nvim-web-devicons",
        opts = function()
            return { override = require("custom.icons").devicons }
        end,
},
```

**Comment by fuqianya** [comment]
Hello, @DoctorKnowsBetter. Thank you very much for your kind help. This helps me to change the icon in the nvim-tree.

**Comment by fuqianya** [comment]
But how to alter the color of the README file shown below? It looks different from the other files. I want to change the README file's color to white to match that of the other files.

![](https://user-images.githubusercontent.com/45023083/236599279-932e3f4e-3750-4102-9698-27ec830d1af3.png)

**Comment by DoctorKnowsBetter** [comment]
@fuqianya Glad to help, but the problem with overriding icon colors **base46/integrations** remains, waiting for reaction of developers.

```
[ venv ] base46/integrations [ v2.0 ] >_ cat $HOME/.local/share/nvim/lazy/base46/lua/base46/integrations/devicons.lua | grep -i md
DevIconMd = {fg = colors.blue},
```

**Comment by DoctorKnowsBetter** [comment]
@fuqianya, I had the same problem with the colors README.md, solved as follows:
in custom/init.lua added the following (use your own colors):


>vim.api.nvim_create_autocmd("User", {
    pattern = "NvimTreeRequired",
    callback = function()
        vim.api.nvim_command("hi NvimTreeCursorLine guibg=#152131 guifg=" .. color30.nocolor)
        vim.api.nvim_command("hi NvimTreeSpecialFile  guibg=" .. color30.nocolor .. " guifg=" .. color30.white)
    end,
})

**Comment by fuqianya** [comment]
Thanks for your help! 🙌

**Comment by siduck** [comment]
> Dear Developers. The main problem is that the colors specified in **base46/integrations** can't be changed via **hl_override** or **hl_add**. And it makes you very uncomfortable.

impossible

**Comment by DoctorKnowsBetter** [comment]
@siduck
It's sad, of course, but thanks for the response.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/236604207-7f97d709-7381-455d-b727-3dc57d0af21e.mp4


A crystal clear proof that you are wrong, delete your comment as its a clear LIE :angry:

**Comment by siduck** [comment]
@DoctorKnowsBetter look at the video above, hl_override works 100%

**Comment by fuqianya** [comment]
@DoctorKnowsBetter, maybe this [issue](https://github.com/NvChad/NvChad/issues/1752) will help you.

**Comment by siduck** [comment]
> @DoctorKnowsBetter, maybe this [issue](https://github.com/NvChad/NvChad/issues/1752) will help you.

no it wont, just color the hl group

**Comment by DoctorKnowsBetter** [comment]
@siduck Thank you very much

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/236605607-fba6a8ba-2d7e-4e50-9a3d-cd2f131b0200.png)

Sorry for being rude, i just didnt like you both jumped to conclusions without trying hl_override properly, it has been tested since months and its perfect!

**Comment by fuqianya** [comment]
Hello, @siduck. I noticed that the color of the filenames in your nvim-tree differs from mine, which is due to us using different themes (i.e., everforest vs ashes). Although I have read the theme configuration, I could not find the color option that determines the filenames. Could you please assist me with this?

**Comment by exzolink** [comment]
@siduck Hello! How can i change the fg color of the text in case of an error, warn, etc.?

**Comment by siduck** [comment]
> @siduck Hello! How can i change the fg color of the text in case of an error, warn, etc.?

open nvimtree and then run  Telescope highlights  command


![image](https://github.com/user-attachments/assets/f0aa0fe6-0dcf-420d-b4a2-e29494ffeae8)

then add these in hl_add

**Comment by exzolink** [comment]
> > @siduck Hello! How can i change the fg color of the text in case of an error, warn, etc.?
> 
> open nvimtree and then run Telescope highlights command
> 
> then add these in hl_add

Oh, thanks, but what to do with underline? I wanna remove it and set fg color
NvimTreeDiagnosticErrorFileHL for example

**Comment by siduck** [comment]
> > > @siduck Hello! How can i change the fg color of the text in case of an error, warn, etc.?
> > 
> > 
> > open nvimtree and then run Telescope highlights command
> > then add these in hl_add
> 
> Oh, thanks, but what to do with underline? I wanna remove it and set fg color NvimTreeDiagnosticErrorFileHL for example

so those hlgroups with underline, u want to remove underline for them and just set fg color?

if yes then just use `underline=false` for them, check :h nvim_set_hl docs

**Comment by exzolink** [comment]
It works via vim.api.nvim_set_hl, is it possible override it in chadrc?
 And how i can get default theme color previously used for underline?

**Comment by siduck** [comment]
> It works via vim.api.nvim_set_hl, is it possible override it in chadrc? And how i can get default theme color previously used for underline?

 https://nvchad.com/docs/config/theming

**Comment by exzolink** [comment]
https://github.com/NvChad/base46/blob/v2.5/lua/base46/integrations/nvimtree.lua

Looks like diagnostics are not supported?

**Comment by siduck** [comment]
> https://github.com/NvChad/base46/blob/v2.5/lua/base46/integrations/nvimtree.lua
> 
> Looks like diagnostics are not supported?

add them in hl_add then?

**Comment by exzolink** [comment]
```
hl_override = {
    NvimTreeDiagnosticErrorFileHL = {
      fg = "#000000",
      underline = false
    }
  }
```

What am i doing wrong?
hl_add dont works too

**Comment by siduck** [comment]
> ```
> hl_override = {
>     NvimTreeDiagnosticErrorFileHL = {
>       fg = "#000000",
>       underline = false
>     }
>   }
> ```
> 
> What am i doing wrong? hl_add dont works too

```lua
M.base46 = {
    hl_add = {
    NvimTreeDiagnosticErrorFileHL = {
      fg = "#000000",
      underline = false
    }
  }
  ```

**Comment by exzolink** [comment]
Yea, this is full code
```

M.base46 = {
  theme = "catppuccin",

  hl_add = {
    NvimTreeDiagnosticErrorFileHL = {
      fg = "#000000",
      underline = false
    }
  },
}
```

**Comment by exzolink** [comment]
Even DiagnosticUnderlineError doesnt work

**Comment by siduck** [comment]
> Even DiagnosticUnderlineError doesnt work

lets talk on the discord/matrix server or u can dm me there,  so i can debug this faster , github notifs are disabled here
