### ISSUE TITLE
How to change the color of filenames in nvim-tree ?

### ISSUE THREAD

**Issue by fuqianya** [siduck76/NvChad#1997]
**Describe the bug**
Hello, @siduck. I noticed that the color of the filenames in your nvim-tree differs from mine, which is due to us using different themes (i.e., everforest vs ashes). Although I have read the theme configuration at [here](https://github.com/NvChad/base46/tree/master/lua/base46/themes), I could not find the color option that determines the filenames. Could you please assist me with this?

![](https://user-images.githubusercontent.com/59060246/236605607-fba6a8ba-2d7e-4e50-9a3d-cd2f131b0200.png)
![](https://user-images.githubusercontent.com/45023083/236599279-932e3f4e-3750-4102-9698-27ec830d1af3.png)

**Comment by siduck** [comment]
@fuqianya 
![image](https://user-images.githubusercontent.com/59060246/236660263-9a38a3ed-e1b0-4bbb-848e-fd3568d2476a.png)


also avoid making issues for external plugins related questions, ask it on our community groups, servers etc or github discussions
