### ISSUE TITLE
Can't disable some default keys

### ISSUE THREAD

**Issue by mikaizhu** [siduck76/NvChad#1999]
**Describe the bug**

Can't disable some default keys

**To Reproduce**

1. I want disable these key mapping, and put them in  `custom/mapping.lua`

```
M.disable = {
  n = {
    ["<C-Space>"] = "",
    ["<C-n>"] = "",
    ["<leader>tk"] = "",
    ["<C-s>"] = "",
    ["<C-c>"] = "",
  },
}
```

2. It give this error

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/59464933/236754330-0526a443-d237-4510-8d25-a073a41a8b8b.png">

**Desktop (please complete the following information):**
 - Mac OS
 - kitty
 - Neovim 0.83

**Comment by siduck** [comment]
its disabled and not disable

**Comment by mikaizhu** [comment]
OK，I got it, Thanks
