### ISSUE TITLE
Wrong cursor color.

### ISSUE THREAD

**Issue by totoro-ghost** [siduck76/NvChad#200]
**Describe the bug**
Color of cursor dosen't match the color scheme used by nvim. Especially on the left side of indent.

**Screenshots**
![image](https://user-images.githubusercontent.com/87352198/127621163-03de2d23-4f51-4236-b0e2-94e387ce67f3.png)
![image](https://user-images.githubusercontent.com/87352198/127621184-578dd9ef-0edc-4bbe-989d-f166979dffb6.png)

**Desktop (please complete the following information):**
 - Operating System - Ubuntu 20.04 LTS
 - Terminal - tested on both `alacritty`,  `konsole` 
 - Version of Neovim - `NVIM v0.6.0-dev`

**Comment by G-Rowell** [comment]
I've had this too myself

**Comment by ashincoder** [comment]
could you guys test using kitty terminal

**Comment by siduck76** [comment]
> **Describe the bug**
> Color of cursor dosen't match the color scheme used by nvim. Especially on the left side of indent.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/87352198/127621163-03de2d23-4f51-4236-b0e2-94e387ce67f3.png)
> ![image](https://user-images.githubusercontent.com/87352198/127621184-578dd9ef-0edc-4bbe-989d-f166979dffb6.png)
> 
> **Desktop (please complete the following information):**
> 
> * Operating System - Ubuntu 20.04 LTS
> * Terminal - tested on both `alacritty`,  `konsole`
> * Version of Neovim - `NVIM v0.6.0-dev`

why 0.6?

**Comment by totoro-ghost** [comment]
> why 0.6?

Because it is the unstable-ppa, stable ppa one doesn't support the lua config completely, it still have some issues. 
I tried the appimage for the 0.5 one and i get these errors, 

![image](https://user-images.githubusercontent.com/87352198/127654866-99103abe-3699-4ad3-8a6d-f0e18503aba6.png)

**Comment by siduck76** [comment]
> > why 0.6?
> 
> Because it is the unstable-ppa, stable ppa one doesn't support the lua config completely, it still have some issues.
> I tried the appimage for the 0.5 one and i get these errors,
> 
> ![image](https://user-images.githubusercontent.com/87352198/127654866-99103abe-3699-4ad3-8a6d-f0e18503aba6.png)

delete ~/.local/share/nvim folder

install nvchad , run install.sh again

**Comment by gaetgu** [comment]
I would like to add that I also have this issue when running NVIM 0.5

**Comment by siduck76** [comment]
weird , I never had this issue

**Comment by ashincoder** [comment]
Neither did I

**Comment by ashincoder** [comment]
Try removing ~/.cache/nvim and ~/.local/share/nvim then reinstall.

**Comment by ashincoder** [comment]
If this does'nt work try using kitty terminal since kitty terminal doesn't change the cursor colors in neovim like alacritty.

**Comment by ashincoder** [comment]
Hope this issue is solved

**Comment by siduck76** [comment]
@totoro-ghost do you still have this issue?

**Comment by Vanderscycle** [comment]
I have the issue come and go when using alacrity but its not that noticeable. I should test on konsole see if it shows.

**Comment by ashincoder** [comment]
Try testing it on kitty since it doesnot change cursor colors like alacritty

**Comment by Pocco81** [comment]
Looks good to me in both Alacritty and Kitty.

**Comment by Vanderscycle** [comment]
> Looks good to me in both Alacritty and Kitty.

I'm not suggesting any changes. I do have a theme running on alacrity so maybe that's the issue.

**Comment by Iorvethe** [comment]
I think this comes from the `indent-blankline` plugin. I don't really know how to fix it properly but as a temporary solution until someone investigates it further, I replaced/added the following lines to have a `background-indent` instead of a `line-indent`. It's not like before but at least the blue cursor is gone now.

In `~/.config/nvim/lua/plugins/others.lua`, replace the configuration for `blankline` with:
```lua
      vim.g.indent_blankline_char_highlight_list = {"IndentOdd", "IndentEven"}
      vim.g.indent_blankline_space_char_highlight_list = {"IndentOdd", "IndentEven"}

      -- don't show any characters
      vim.g.indent_blankline_char = " "
      vim.g.indent_blankline_space_char = " "

      -- when using background, the trailing indent is not needed / looks wrong
      vim.g.indent_blankline_show_trailing_blankline_indent = false
```

Then in `~/.config/nvim/lua/highlights.lua`, add the following lines after `fg("IndentBlanklineChar", line)` :
```lua
fg_bg("IndentOdd", 'NONE', 'NONE')
fg_bg("IndentEven", 'NONE', black2)

```

**Comment by Pocco81** [comment]
Btw @totoro-ghost, but what did you use to take the screenshot?

**Comment by shivanshu-semwal** [comment]
I installed the alacritty v5 from source, but the issue is still there, @Iorvethe workaround works.

@Pocco81 i used flameshot.

**Comment by totoro-ghost** [comment]
I installed allacritty-v5 form source but the issue is still there, @Iorvethe  workaround works.
@Pocco81  i used flameshot for screenshot.

**Comment by kirusfg** [comment]
The problem still appears, although only in alacritty and xterm out of all terminals I've tested this on (alacritty, st, kitty, xterm). Additionally, the colors are different in xterm (the comments, for example, are of the same blue color). I will investigate into this later.

**Comment by kirusfg** [comment]
An interesting finding: the cursor is not blue when a file is opened through nvim (from telescope, for example). When opened via command line like so:
```
nvim file.rs
```
or through file launcher like `rifle`, which is used by the tui file manager `ranger`, the cursor is blue wherever the code is indented. `rifle` definitely opens files like above, so that could mean something has not enough time to load (perhaps, some plugin) or the settings do not get applied in time.

**Comment by peppapig450** [comment]
Why not build the stable from one from source

**Comment by siduck** [comment]
alacritty's weird ;(

**Comment by peppapig450** [comment]
Why I don't use it lol it doesn't support ligatures and always seems to mess up other stuff

**Comment by Pocco81** [comment]
@peppapig450 on my tests Alacritty ran faster... I use Kitty too btw; life without ligatures is not life!

**Comment by peppapig450** [comment]
@Pocco81  I meant tbf kitty has so many much features and the speed difference is marginal but to each their own I guess

**Comment by siduck** [comment]
> @peppapig450 on my tests Alacritty ran faster... I use Kitty too btw; life without ligatures is not life!

try ST :rocket:

**Comment by Pocco81** [comment]
@peppapig450

> kitty has so many more features

it's true, but in my case, with Tmux, any terminal can feel like home, even TTYs.

**Comment by peppapig450** [comment]
I've never tried tmux seems way too complicated

**Comment by Pocco81** [comment]
It ain't. Configuring it? perhaps. But if you have the docs opened with a nice "intro to tmux" tutorial playing, then it becomes easier to understand and use. Trust me, Tmux gives you wings. Here is my [config](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/main/home_dots/.tmux.conf), and [here](https://github.com/catppuccin/tmux) is a theme I made for tmux yesterday, which looks like this:

<p align="center">
  <img src="https://raw.githubusercontent.com/catppuccin/tmux/main/assets/ss.png"/>
</p>

_trust the process_

**Comment by peppapig450** [comment]
This my MacBook
<img width="1433" alt="Screen Shot 2021-11-12 at 10 09 49 PM" src="https://user-images.githubusercontent.com/55930078/141608125-115dd851-6ac0-4c9f-aaa1-33a2c8e095d0.png">

**Comment by peppapig450** [comment]
I might try tmux on arch linux tho. Don't want to change my MacBook configuration it took forever

**Comment by siduck** [comment]
> This my MacBook <img alt="Screen Shot 2021-11-12 at 10 09 49 PM" width="1433" src="https://user-images.githubusercontent.com/55930078/141608125-115dd851-6ac0-4c9f-aaa1-33a2c8e095d0.png">
![firewatch-purple](https://user-images.githubusercontent.com/59060246/141608175-4a078cb1-3174-4654-964f-a0225b9a9f1a.png)

the wallpaper looks lighter for the transparent terminal , use this wallpaper

**Comment by peppapig450** [comment]
Thanks :D

**Comment by FelixKratz** [comment]
I highlighted how to resolve this bug [here](https://github.com/alacritty/alacritty/issues/5440). I am not sure if this could also be fixed less invasive because it seems to me that this only happens because of a misconfiguration

**Comment by kirusfg** [comment]
The cursor is white all the time instead of being dimmed (of grey-ish color) at positions of indents, but that is not very important, taking into consideration how annoying that blue acid cursor was. Great finding, @FelixKratz! 

Once I have enough time I'll look into this issue and let you know if I manage to fix it. Thank you.
