### ISSUE TITLE
Strange color behaviour in nvim tree

### ISSUE THREAD

**Issue by Ethanol48** [siduck76/NvChad#2000]
**Describe the bug**
Colors in nvimtree starting nvim are not correct, it occurs only in starting nvim, but it goes to normal after 

**To Reproduce**
1. Install NvChad 2.0
2. Go to custom.pluggins.lua and add custom overrides (as shown at the end of the issue)

3. Restart nvim

5. to make it disapear, :w and it would go to normal

**Expected behavior**
Having correct color in the begginning

**Screenshots**

### Starting nvim
<img width="221" alt="Screenshot 2023-05-08 at 10 30 40" src="https://user-images.githubusercontent.com/96821054/236779588-5b267524-32a8-4c5c-8710-19baf1d8e25c.png">

### After saving file, even if there's no changes
<img width="229" alt="Screenshot 2023-05-08 at 10 29 27" src="https://user-images.githubusercontent.com/96821054/236779970-549cdcd1-b263-4d1f-a36c-de83a0dc6446.png">

**Desktop (please complete the following information):**
 - MacOs 12.5.1
 - Alacritty
 - Version of Neovim v0.8.2

**Additional context**
I encountered the problem after doing my custom overrides,

I saw that by doing:  
```lua
-- plugins.lua

  {
    "nvim-tree/nvim-tree.lua",
    opts = overrides.nvimtree,
  },
```

Didn't work, I search the documentation in nvimtree, a .setup() was needed, so I use this code:
```lua
-- plugins.lua

  {
    "nvim-tree/nvim-tree.lua",
     config = function()
       require("nvim-tree").setup(overrides.nvimtree)
     end,
  },
```

The overrides worked this time, but I the error appears.
in my overrides I'm not changing colors, this is in my config.overrides:

```lua
M.nvimtree = {

  filters = {
    dotfiles = false,
    git_clean = false,
  },

  git = {
    enable = true,
    ignore = false,
  },

  view = {
    hide_root_folder = false,
  },

  renderer = {

    indent_markers = {
      enable = true,
    },

    highlight_git = false,

    icons = {

      show = {
        git = true,

      },

      glyphs = {

        -- folder icons
        folder = {  
          empty = "",
          empty_open = "",

        },
      },
    },
 }
}



```

**Comment by siduck** [comment]
are you running nvimtree on startup?

**Comment by siduck** [comment]
Also the root_folder_label option is moved to renderer field

**Comment by siduck** [comment]
```lua
M.nvimtree = {
  filters = {
    dotfiles = true,
    custom = { "node_modules" },
  },
  git = {
    enable = true,
  },
  renderer = {
    root_folder_label = ":~:s?$?/..?",
    highlight_git = true,
    icons = {
      show = {
        git = true,
      },
    },
  },
}
```

And you dont need to write config function for nvimtree, only overrides are enough

**Comment by Ethanol48** [comment]
Thank you, it was fine It worked the opts = override.nvimtree I just had an issue with my icons
