### ISSUE TITLE
Can't select on interface

### ISSUE THREAD

**Issue by IGLOU-EU** [siduck76/NvChad#2014]
**Describe the bug**
Can't select on interface

**To Reproduce**
install; run nvim

**Expected behavior**
Can select on interface

**Screenshots**
![Capture d’écran du 2023-05-11 16-18-25](https://github.com/NvChad/NvChad/assets/15379333/2e834ce0-047d-4416-9f00-801ff8ebe0e4)

**Desktop (please complete the following information):**
 - Operating System: Archlinux
 - Terminal: Kitty
 - NVIM v0.9.0
- Build type: Release
- LuaJIT 2.1.0-beta3

**Additional context**
Tapez un nombre et <Entrée> ou cliquez avec la souris (q ou rien annule) :
E5108: Error executing lua: Keyboard interrupt
stack traceback:
        [C]: in function 'inputlist'
        /usr/share/nvim/runtime/lua/vim/ui.lua:50: in function 'select'
        ...cal/share/nvim/lazy/mason.nvim/lua/mason/ui/instance.lua:527: in function 'effect_handler'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:251: in function 'call_effect_handler'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/ui/display.lua:263: in function 'dispatch_effect'

**Comment by siduck** [comment]
Unable to reproduce this issue, please show a video + error in english so I could read it

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/881535b7-3ae0-4daa-8551-0e3219db4a14)

Not a nvchad issue
