### ISSUE TITLE
Getting an error on init.lua line 77

### ISSUE THREAD

**Issue by rmasci** [siduck76/NvChad#2015]
**Describe the bug**
Had a working instance of nvchad. Went in to neovim and this error started happening:
```
/home/rich/.config/nvim/lua/core/init.lua:77:
```
**To Reproduce**
nvim

**Expected behavior**
nvim editor would open with nvchad config

**Desktop (please complete the following information):**
Linux Kubuntu 23.04
Konsole

**Comment by siduck** [comment]
rm -rf .local/share/nvim and then reinstall nvchad
