### ISSUE TITLE
null-ls and tsserver are formatting incorrectly

### ISSUE THREAD

**Issue by homerosbart2** [siduck76/NvChad#2016]
**Describe the bug**
Starting this week all my TypeScript projects started to format incorrectly, it looks like double formatting, but the first one formats correctly and the second one doesn't. I'm using Prettier with ESLint.

First, I want to mention that I had set the format on save in `lua/custom/init.lua`.
```lua
autocmd("BufWritePre", {
    pattern = "*",
    callback = function()
        vim.lsp.buf.format { async = false }
    end,
})
```

This is important to mention because while debugging I found out that commenting these lines in `lua/custom/configs/lspconfig.lua` make the problem disappear when formatting manually (`<leader>fm`) and it works correctly when saving and auto format.

```lua
for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
        on_attach = on_attach,
        capabilities = capabilities,
    }
end
```

Commenting those lines made `tsserver` not start:

<img width="900" alt="image" src="https://github.com/NvChad/NvChad/assets/25249581/c03ff99e-942b-415c-b8ed-e152b64be993">

So I can only conclude that is something related specifically to `tsserver`. I don't have much experience with lua or vim configuration, so I'm pretty lost with this 😅. 

**To Reproduce**
I started a new project, and it is still happening, so working with Prettier, ESLint, and TypeScript should be enough to reproduce this.

My `null-ls` sources:

```lua
local sources = {

    -- webdev stuff
    -- b.formatting.deno_fmt, -- choosed deno for ts/js files cuz its very fast!
    -- b.formatting.prettier.with { filetypes = { "html", "markdown", "css" } }, -- so prettier works only on these filetypes
    b.formatting.eslint_d,
    b.diagnostics.eslint_d,
    -- b.code_actions.eslint_d,
    b.formatting.stylelint,
    b.diagnostics.stylelint,

    -- Lua
    b.formatting.stylua,

    -- cpp
    b.formatting.clang_format,
}
```

I tried disabling them, which made the double format stop, but it was still formatting incorrectly. So this only confirms that the problem is more on the side of `tsserver`.

**Expected behavior**
To format correctly ✨

**Screenshots**

**Before formatting**|**After formatting**|**After pressing `u`**
---|---|---
<img width="503" alt="image" src="https://github.com/NvChad/NvChad/assets/25249581/cc531f68-baf4-46de-8120-abd361db9220">|<img width="585" alt="image" src="https://github.com/NvChad/NvChad/assets/25249581/d8656871-fed9-4531-8f2e-1b00866acffd">|<img width="474" alt="image" src="https://github.com/NvChad/NvChad/assets/25249581/6a74ae11-dbe9-4f8d-91d1-c388929c8b37">

**Desktop (please complete the following information):**
 - Operating System: macOS 13.1 Beta 
 - Terminal: iTerm2
 - Version of Neovim: this is happening with versions 0.9 and 0.8 (I tried upgrading hoping to solve this issue)

**Additional context**

**Comment by ViiEx** [comment]
Have you tried to move the autocmd into the on_attach for null-ls?

Here is an example:

```lua
---------------------------------
-- Formatting
---------------------------------
local diagnostics = require("null-ls").builtins.diagnostics
local formatting = require("null-ls").builtins.formatting
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

require("null-ls").setup({
	debug = true,
	sources = {
		formatting.black,
		formatting.rustfmt,
		formatting.phpcsfixer,
		formatting.prettier,
		formatting.stylua,
		formatting.phpcbf,
		diagnostics.shellcheck.with({ diagnostics_format = "#{m} [#{c}]" }),
	},
	on_attach = function(client, bufnr)
		if client.supports_method("textDocument/formatting") then
			vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
			vim.api.nvim_create_autocmd("BufWritePre", {
				group = augroup,
				buffer = bufnr,
				callback = function()
					vim.lsp.buf.format({ bufnr = bufnr })
				end,
			})
		end
	end,
})
```
Edit:

[Here](https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Formatting-on-save) is the docs from null-ls for more info.

**Comment by homerosbart2** [comment]
Hey @ViiEx 👋🏼

I didn’t, I will try! But I don’t know how that could fix the problem. Could you explain me the reason? The code formatting works correctly (null-ls) when `tsserver` is not enabled, and the problem happens too when I press `<leader>fm`.

It was working correctly before 🤔 it seems like something has been updated automatically and produced the bug.

**Comment by homerosbart2** [comment]
Another important thing I forgot to mention is that it happens with the rules of Prettier that change the indentation size. I use indentation of 4 spaces, but there are some cases where Prettier decides to use different lengths to indent. Those cases are the ones that fail and are formatted incorrectly.

I have this in `lua/custom/init.lua`
```lua
opt.shiftwidth = 4
opt.tabstop = 4
opt.softtabstop = 4
```

**Comment by ViiEx** [comment]
I'm not 100% sure that this will fix your problem but few things that you will win from moving your `autocmd` to null-ls `on_attach` is that at the start null-ls will check if your current buffer supports formatting so you don't have to try to format file types that are not supported, then with this function on the following part:

```lua
vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
```
from what I understand it clears the other autocmds and that will prevent NeoVim from accidently run the same command twice.

One thing you may want to check tho, and that is not related to NeoVim at all, is if your project, since you ar formatting typescript, has installed and configure es_lint with different configuration. That will cause the double format and since there are different settings you will see 2 different outputs.

**Comment by homerosbart2** [comment]
@ViiEx it didn't work 😢 

```lua
local present, null_ls = pcall(require, "null-ls")
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

if not present then
    return
end

local b = null_ls.builtins

local sources = {
    b.formatting.eslint_d,
    b.diagnostics.eslint_d,
    b.formatting.stylelint,
    b.diagnostics.stylelint,
    b.formatting.stylua,
    b.formatting.clang_format,
}

null_ls.setup {
    debug = true,
    sources = sources,
    on_attach = function(client, bufnr)
        if client.supports_method "textDocument/formatting" then
            vim.api.nvim_clear_autocmds { group = augroup, buffer = bufnr }
            vim.api.nvim_create_autocmd("BufWritePre", {
                group = augroup,
                buffer = bufnr,
                callback = function()
                    vim.lsp.buf.format { bufnr = bufnr }
                end,
            })
        end
    end,
}
```

**Comment by homerosbart2** [comment]
@ViiEx what do you mean by `has installed and configure es_lint with different configuration`? 👀

**Comment by ViiEx** [comment]
> @ViiEx what do you mean by `has installed and configure es_lint with different configuration`? eyes

From what I see in your config you have configure `es_lint` as your null-ls formatter.
EsLint can have a config file with rules for linting and formatting (they can be found [here](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file-formats))

You may also have eslint or prettier in your project that have different rules tho. In that case your project's format will run and then the generic eslint from null ls causing you to have the issue you are facing

**Comment by siduck** [comment]
@ViiEx 

can you add 
```lua
 client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentRangeFormattingProvider = false
 ```
 
 here
 
 
![image](https://github.com/NvChad/NvChad/assets/59060246/0db2de40-5bb6-4354-a6a2-e9da29a44999)

"plugins/configs/lspconfig" file

**Comment by siduck** [comment]
@ViiEx 

can you add 
```lua
 client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentRangeFormattingProvider = false
 ```
 
 here
 
 
![image](https://github.com/NvChad/NvChad/assets/59060246/0db2de40-5bb6-4354-a6a2-e9da29a44999)

"plugins/configs/lspconfig" file

**Comment by homerosbart2** [comment]
> You may also have eslint or prettier in your project that have different rules tho. In that case your project's format will run and then the generic eslint from null ls causing you to have the issue you are facing

I only have one ESLint configuration file and one Prettier configuration file, they are at the project level. And I don't think that could be the problem because when only `null-ls` is working, the formatting works correctly. I think that `tsserver` is using some different configuration.

**Comment by homerosbart2** [comment]
> @ViiEx
> 
> can you add
> 
> ```lua
>  client.server_capabilities.documentFormattingProvider = false
>   client.server_capabilities.documentRangeFormattingProvider = false
> ```
> 
> here
> 
> ![image](https://user-images.githubusercontent.com/59060246/237909705-0db2de40-5bb6-4354-a6a2-e9da29a44999.png)
> 
> "plugins/configs/lspconfig" file

IT WORKED @siduck 🎉 

Why is this needed? 🤔

**Comment by siduck** [comment]
@homerosbart2  seems like null-ls formatter isnt being used because if the current LSP which is tsserver has  formatting capabilities then lsp will use tsserver only to format!! the above code, disables formatting. 

I'll add the code back because we all primarily use null-ls only for formatting :)

**Comment by homerosbart2** [comment]
Thx @ViiEx and @siduck for your help and for sharing your knowledge 🙏🏼
