### ISSUE TITLE
nvim-tree cmd invaild

### ISSUE THREAD

**Issue by cathaysia** [siduck76/NvChad#202]
Sorry, I'm not using your configure, but I refer you a lot, I can't sure this bugs whether happends with you.

Here are your codes:
```
use {
            "kyazdani42/nvim-tree.lua",
            cmd = "NvimTreeToggle",
            config = function()
                require "plugins.nvimtree"
            end
        }
```
and in `nvimtree.lua`
```lua
g.nvim_tree_auto_close = 0 -- closes tree when it's the last window
```

Had you find that `g.nvim_tree_auto_close = 1` is valid? This command can't be run in 

```lua
config = function()
    require "plugins.nvimtree"
end
```
Here is my commit to fix this, may can bring some idea to you :)

https://github.com/cathaysia/nvim_lua/commit/61996de6e87a2f4377471e98f6df28a54c511627

**Comment by siduck76** [comment]
could you be more specific about reproducing the error?

**Comment by cathaysia** [comment]
1. set `g.nvim_tree_auto_close = 1` : this will close nvim when NvimTree is latest window. 
2. open nvim and `:NvimTreeToggle`
3. close other windows other than NvimTree

Then you will find NvimTree not closed when last window be closed

Expected effect should be: 
![Peek 2021-07-31 12-54](https://user-images.githubusercontent.com/42114817/127729060-510a3e78-81e2-4c8f-a34f-d230081fbb65.gif)

**Comment by Akianonymus** [comment]
> 1. set `g.nvim_tree_auto_close = 1` : this will close nvim when NvimTree is latest window.
> 2. open nvim and `:NvimTreeToggle`
> 3. close other windows other than NvimTree
> 
> Then you will find NvimTree not closed when last window be closed
> 
> Expected effect should be:
> ![Peek 2021-07-31 12-54](https://user-images.githubusercontent.com/42114817/127729060-510a3e78-81e2-4c8f-a34f-d230081fbb65.gif)

It does work, i tested

do this
```
:lua vim.g.nvim_tree_auto_close = 1
```
 then try

**Comment by cathaysia** [comment]
OK,. Thanks :)

**Comment by Akianonymus** [comment]
@cathaysia If you want permanent change, then edit lua/plugins/nvimtree.lua.

**Comment by cathaysia** [comment]
Thank you very much :) I encounter this bugs with my configure, whose structure has some difference with you. So this solution not suit with me(I find another way to solve this bug temporarily).

Emm, for I refer to your repo a lot, so I think may your repo has this bugs also, but the fact slap my face. HAHA.

Thank you anyway 😃
