### ISSUE TITLE
How do I integrate Copilot in NVChad?

### ISSUE THREAD

**Issue by alessandrocapra** [siduck76/NvChad#2020]
**Is your feature request related to a problem? Please describe.**
I can successfully install and authenticate in Copilot using the copilot.vim plugin. However, it is not working due to the Tab key being already assigned in insert mode.

**Describe the solution you'd like**
A simple step-by-step guide on the recommended approach on how to integrate it, e.g. change the binding of Copilot or the nvim-cmp ones. Perhaps this issue could become a guide to link other people in the same situation (noobs like me :P)

**Describe alternatives you've considered**
I tried to go through other issues mentioning this, but could not do it properly. Checked the example-config, but could not really understand what the recommended approach is in this case.

My last try was to add this line in `custom/init.lua`:

```lua
vim.api.nvim_set_keymap('i', '<C-Tab>', ':Copilot<CR>', {noremap = true, silent = true})
```

**Additional context**
When I try to run the command :Copilot status. it mentions a conflict regarding the Tab key being used elsewhere (nvim-cmp). I tried to ask help to ChatGPT but no working solution found yet.

**Comment by siduck** [comment]
```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      mapping = {
        -- disable  tab
        ["<Tab>"] = function(callback)
          callback()
        end,

        ["<S-Tab>"] = function(callback)
          callback()
        end,
     }
}
```

**Comment by alessandrocapra** [comment]
Is it correct to modify this in `plugins/init.lua`? That's the only occurrence where I find something similar. I think you are using a different version of NVChad, what I've found similar to this starts at line 82 of `plugins/configs/cmp.lua`

However, this solution prevents me from cycling through the intellisense suggestions, which is very much not desirable. How would you assign the shortcut for Copilot to be CTRL + Tab? 

Thanks for your help

**Comment by siduck** [comment]
> Is it correct to modify this in `plugins/init.lua`? That's the only occurrence where I find something similar. I think you are using a different version of NVChad, what I've found similar to this starts at line 82 of `plugins/configs/cmp.lua`
> 
> However, this solution prevents me from cycling through the intellisense suggestions, which is very much not desirable. How would you assign the shortcut for Copilot to be CTRL + Tab?
> 
> Thanks for your help

tab is used by nvim-cmp and you wanted to disable it! but you're using ctrl + tab which shouldnt be an issue i think

**Comment by siduck** [comment]
also for the conflict part,yes copilot needs disabling our default tab key. You can cycle in the completion menu by C-n/p btw

**Comment by alessandrocapra** [comment]
I am still unable to configure it to this day, unfortunately. Can someone please make a step-by-step tutorial on how to make it work? I think Ctrl+Tab makes more sense, and keeping Tab to cycle through suggestions.

It's fine if you also drop me a message with the bare minimum, I can then write a nice comment that explains it for people who will have the same problem in the future.

Thanks, and great work with NvChad!

**Comment by siduck** [comment]
@alessandrocapra  https://github.com/NvChad/NvChad/issues/1868

**Comment by mauromartinezr** [comment]
After you install github/copilot.vim you need to configure in the your custom lua/custom/plugins.lua like this:


```
 {
    "github/copilot.vim", 
    lazy = false,
    config = function()
      -- Mapping tab is already used by NvChad
      vim.g.copilot_no_tab_map = true;
      vim.g.copilot_assume_mapped = true;
      vim.g.copilot_tab_fallback = "";
      -- The mapping is set to other key, see custom/lua/mappings
      -- or run <leader>ch to see copilot mapping section
    end
  },

```

 That code will make copilot doesn’t complain that the <Tab> is already used. Then, we need to add the mapping in the lua/custom/mappings.lua

```
M.copilot = {
  i = {
    ["<C-l>"] = {
      function()
        vim.fn.feedkeys(vim.fn['copilot#Accept'](), '')
      end,
      "Copilot Accept",
      {replace_keycodes = true, nowait=true, silent=true, expr=true, noremap=true}
    }
  }
}
```

**Comment by alessandrocapra** [comment]
@compilerbyte thank you so much for your answer! I am a total noob in neovim and NVChad, I wish there was more documentation to understand fully how to properly setup any plugin I might need in the future, but I understand it's hard.

Cheers again!

**Comment by siduck** [comment]
@alessandrocapra nvchad just uses lazy.nvim so be familiar with lazy.nvim first. then read all of our docs in order

**Comment by alessandrocapra** [comment]
Thanks for the tip, I went through the docs of lazy and it makes much more sense! One questions still remains though, I have tried to set the shortcut to accept the Copilot suggestion to `Ctrl + Tab` but it does not accept the suggestion. Any clue? Thanks!

```
M.copilot = {
  i = {
    ["<C-Tab>"] = {
      function()
        vim.fn.feedkeys(vim.fn["copilot#Accept"](), "")
      end,
      "Copilot Accept",
      { replace_keycodes = true, nowait = true, silent = true, expr = true, noremap = true },
    },
  },
}
```

**Comment by siduck** [comment]
@alessandrocapra  can you try another key combo?

**Comment by alessandrocapra** [comment]
The one suggested above works well (CRTL + L), I am using that one eventually but if it's possible to figure out the tab one it would be great

**Comment by siduck** [comment]
@alessandrocapra first make it work with vim.keymap.set, if it works then its an nvchad bug!

**Comment by stedwick** [comment]
To quickly test out Copilot you can add this line into your `~/.config/nvim/lua/custom/mappings.lua`
```
M.general = {
  n = {
    ["cp"] = { ":Copilot panel<enter>", "Copilot panel" },
  },
```
Then type cp in normal mode to get suggestions. This shouldn't interfere with any other tab completion you have.

Oh, and this worked for me to enable it fully: https://azamuddin.com/en/blog/050623-setting-up-copilot-on-nvchad

**Comment by vermacodes** [comment]
The [suggestions](https://github.com/NvChad/NvChad/issues/2020#issuecomment-1691652333) posted above make it work. But they break the default behavior of Tab key in insert mode to insert tabs.

I removed `vim.g.copilot_tab_fallback = "";` from plugin.lua to make it work.

@alessandrocapra were you able to make it work with Ctrl + Tab?

**Comment by ckt114** [comment]
With nvchad 2.5 I had to add the folowing mapping for it to work even though I've set `<C-l>` in copilot's mapping which didn't work.

```
map("i", "<C-l>", function()
  require("copilot.suggestion").accept()
end, { desc = "Copilot accept" })
```

**Comment by siduck** [comment]
@ckt114 where did u put it?

**Comment by ckt114** [comment]
@siduck `~/.config/nvim/lua/mappings.lua`.

**Comment by siduck** [comment]
> @siduck `~/.config/nvim/lua/mappings.lua`.

check `:map <C-l>`

**Comment by ckt114** [comment]
This one? https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/mappings.lua#L6

I don't care about shortcut so ...

**Comment by siduck** [comment]
@ckt114 so it means you didnt setup mapping properly...  

show your config in a repo so i could look

**Comment by ckt114** [comment]
My config is in a chezmoi repo which contains my personal stuff. By here's my config for mappings and copilot in pastebin. https://pastebin.com/Jn0iNiWd

**Comment by ckt114** [comment]
Played w/ it a little more and looks like using `event = "InsertEnter"` works w/o the extra mapping.

```
return {
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "InsertEnter",
  opts = {
    panel = {
      auto_refresh = true,
      layout = {
        position = "right",
        ratio = 0.3,
      },
    },
    suggestion = {
      auto_trigger = true,
      keymap = {
        accept = "<C-l>",
      },
    },
  },
}
```

**Comment by siduck** [comment]
@ckt114  your mappings work fine for me 

https://github.com/NvChad/NvChad/assets/59060246/b1469f42-b3ca-461f-bfba-8b659c01abda


So i cant help any further as i cant reproduce it , seek help in our discord server

**Comment by ckt114** [comment]
I figured it out via my previous response. Thanks @siduck.
