### ISSUE TITLE
Some icons look wrong

### ISSUE THREAD

**Issue by hankji** [siduck76/NvChad#2023]
**Describe the bug**
icons can not display in the latest commit

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/4995120/7d97feb1-7d4a-4ff2-a5db-2771d547dc6d)
![image](https://github.com/NvChad/NvChad/assets/4995120/aced0ff2-8626-496e-988b-e17175265bf5)
![image](https://github.com/NvChad/NvChad/assets/4995120/29dc817d-2e30-4cce-81ab-369c6f5a5fec)
![image](https://github.com/NvChad/NvChad/assets/4995120/09981bb5-f18f-4add-8662-c978c30bcdc3)

**Desktop (please complete the following information):**
 - MacOS
 - Iterm2
 - NVIM v0.10.0-dev-46+ge23c6ebed

**Comment by siduck** [comment]
please update your nerdfonts to v3.0 at least

**Comment by hankji** [comment]
OK. thanks :)
