### ISSUE TITLE
Error executing vim.schedule lua callback: linux mint 21.1/nvim.0.9

### ISSUE THREAD

**Issue by syaoransan** [siduck76/NvChad#2025]
I just upgraded neovim to version 0.9 from 0.8.3 and when i reinstalled nvchad i got this error

Error executing vim.schedule lua callback: /home/san/.config/nvim/lua/core/utils.lua:80: attempt to index a nil value
stack traceback:
        /home/san/.config/nvim/lua/core/utils.lua:80: in function </home/san/.config/nvim/lua/core/utils.lua:55>

![Screenshot from 2023-05-15 23-35-01](https://github.com/NvChad/NvChad/assets/78855146/cbea5f30-1498-44cc-855f-634090e9d6ae)

**Comment by siduck** [comment]
rm -rf .local/share/nvim
