### ISSUE TITLE
The format of some languages does not take effect

### ISSUE THREAD

**Issue by mrw954** [siduck76/NvChad#2026]
When I use F formating my code:  
 
  If it's a C++ code, The format tool works.

  If it's json, `<leader>fm`  not working,  but I can format it using the command: `lua vim.lsp.buf.format { async = true }`.

  If it's python,  I can only format the code using external commands, example `:black %`

**This is  null-ls.lua ：**

 _cpp:_  
`
  b.formatting.clang_format.with {
    extra_args = {......},
`

_json_:
`
 b.formatting.prettierd,
`

_python_:
`
b.formatting.black.with { extra_args = { "--fast" } },
`

**Desktop (please complete the following information):**
 - Operating System：debian
 - Terminal ：windows terminal
 - Version of Neovim：0.9.0

**Comment by siduck** [comment]
leader fm is a lsp mapping and lsp mappings are enabled only when lsp server's attached to the server. So either define the mapping or enable c# lsp server

**Comment by mrw954** [comment]
> 领导者 FM 是 LSP 映射，仅当 LSP 服务器连接到服务器时，才会启用 LSP 映射。因此，要么定义映射，要么启用 c# lsp 服务器

c# ？ I don't understand，Please guide me，thanks.
** This is LSP status ** :
![image](https://github.com/NvChad/NvChad/assets/24312113/67171318-be48-4ea4-8575-00838b2c3716)

**Comment by siduck** [comment]
> > 领导者 FM 是 LSP 映射，仅当 LSP 服务器连接到服务器时，才会启用 LSP 映射。因此，要么定义映射，要么启用 c# lsp 服务器
> 
> c# ？ I don't understand，Please guide me，thanks. ** This is LSP status ** : ![image](https://user-images.githubusercontent.com/24312113/238555032-67171318-be48-4ea4-8575-00838b2c3716.png)

oh never mind i misread, please enable lsp for c++ which is clangd!

**Comment by mrw954** [comment]
> 

CPP can be formatted properly，null-ls is not a LSP sever ? Shouldn't all formatting services be provided by null-ls!

**Comment by mrw954** [comment]
> 



> > > 领导者 FM 是 LSP 映射，仅当 LSP 服务器连接到服务器时，才会启用 LSP 映射。因此，要么定义映射，要么启用 c# lsp 服务器
> > 
> > 
> > c# ？ I don't understand，Please guide me，thanks. ** This is LSP status ** : ![image](https://user-images.githubusercontent.com/24312113/238555032-67171318-be48-4ea4-8575-00838b2c3716.png)
> 
> oh never mind i misread, please enable lsp for c++ which is clangd!

CPP can be formatted properly，null-ls is not a LSP sever ? Shouldn't all formatting services be provided by null-ls!

**Comment by siduck** [comment]
> > 
> 
> > > > 领导者 FM 是 LSP 映射，仅当 LSP 服务器连接到服务器时，才会启用 LSP 映射。因此，要么定义映射，要么启用 c# lsp 服务器
> > > 
> > > 
> > > c# ？ I don't understand，Please guide me，thanks. ** This is LSP status ** : ![image](https://user-images.githubusercontent.com/24312113/238555032-67171318-be48-4ea4-8575-00838b2c3716.png)
> > 
> > 
> > oh never mind i misread, please enable lsp for c++ which is clangd!
> 
> CPP can be formatted properly，null-ls is not a LSP sever ? Shouldn't all formatting services be provided by null-ls!

it tries to be a fake lsp server. All i mean is leader fm wont be available unless you have an actual lsp server attached

**Comment by mrw954** [comment]
> > > 
> > 
> > 
> > > > > 领导者 FM 是 LSP 映射，仅当 LSP 服务器连接到服务器时，才会启用 LSP 映射。因此，要么定义映射，要么启用 C# LSP 服务器
> > > > 
> > > > 
> > > > c# ？ 我不明白，请指导我，谢谢。** 这是 LSP 状态 ** ：![图像](https://user-images.githubusercontent.com/24312113/238555032-67171318-be48-4ea4-8575-00838b2c3716.png)
> > > 
> > > 
> > > 哦，没关系我看错了，请为 C++ 启用 LSP，这是 clangd！
> > 
> > 
> > CPP 可以正确格式化，null-ls 不是 LSP 服务器吗？不应该所有的格式化服务都由 null-ls 提供吗！
> 
> 它试图成为伪造的LSP服务器。我的意思是领导者 fm 将不可用，除非您连接了实际的 lsp 服务器

Thank you for your patience, I understand!
