### ISSUE TITLE
JSX comment is not working

### ISSUE THREAD

**Issue by yuvarajmadineni** [siduck76/NvChad#2029]
**Describe the bug**
When I am trying to comment the JSX code , its taking default javascript comment convention (adding "//" instead of {/* */})

**To Reproduce**
1. Go to custom.configs.plugins file
2. Add this   {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        -- defaults
        "vim",
        "lua",

        -- web dev
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "json",

        "rust",
      },
      context_commentstring = {
        enable = true,
      },
    },
    dependencies = {
      "JoosepAlviste/nvim-ts-context-commentstring",
    },
  },

**Expected behavior**
After restarting the JSX commenting should work.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Iterm2
 - Latest

**Additional context**

**Comment by siduck** [comment]
@yuvarajmadineni not related to nvchad. comment.nvim requires another plugin to support jsx commenting

**Comment by siduck** [comment]
```lua
{
    "numToStr/Comment.nvim",
    dependencies = "JoosepAlviste/nvim-ts-context-commentstring",
    config = function()
      require("Comment").setup {
        pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
      }
    end,
  }
  ```

**Comment by yuvarajmadineni** [comment]
I tried using this, but still unable to get it working

**Comment by siduck** [comment]
> I tried using this, but still unable to get it working

please reopen neovim and make sure the plugin is installed

**Comment by caneta** [comment]
What I did to make it work was modify lua/custom/plugins.lua with the following:
```lua
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "JoosepAlviste/nvim-ts-context-commentstring",
    },
    opts = overrides.treesitter,
  },
  {
    "numToStr/Comment.nvim",
    dependencies = "JoosepAlviste/nvim-ts-context-commentstring",
    config = function()
      require("Comment").setup {
        pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
      }
    end,
  },
```
The first part is to install [needed dependency for Comment.vim](https://github.com/JoosepAlviste/nvim-ts-context-commentstring#commentnvim), the second part is the one suggested by @siduck .
After neovim restart, the dependecy will be installed and you will be able to comment jsx/tsx files properly.

**Comment by saikete** [comment]
I also encountered this problem when developing, I searched for the solution here: https://github.com/numToStr/Comment.nvim/pull/133,
I don't understand why I set opts but it still doesn't work
