### ISSUE TITLE
Neoformat config issue

### ISSUE THREAD

**Issue by Bio47** [siduck76/NvChad#203]
Hi there! I trying to config the Neoformat plugin for mostly the languages I use like Python, Rust and Clang. But I'm not sure if I'm doing it well because I have this little code and I have this error and the config doesn't work:

```
local present, neoformat = pcall(require, "neoformat")
local g = vim.g
if not present then
  return
end 

neoformat.setup(
  {
    g:neoformat_enabled_python = ['autopep8'] -- Miss symbol ',' or ':'.

  }
)
```

Also I added this part to pluginList.lua:

```
        use {
            "sbdchd/neoformat",
            cmd = "Neoformat",
            config = function()
                require "plugins.neoformat"
            end
        }
```

Like I said before not sure if this is correct or I should add anything else. 
Thanks you in advance.

**Comment by siduck76** [comment]
Whats the error?

**Comment by siduck76** [comment]
Also I don't think you need to require neformat , it's a vimscript plugin

**Comment by siduck76** [comment]
also thats not the right to define globa variables with lua in nvim , 

example : 

```
let g:autosave= 1  will be made to 

vim.g.autosave = 1
```

Similarly :+1: 

```
    vim.gneoformat_enabled_python ={'autopep8}
```
