### ISSUE TITLE
How can netrw be enabled?

### ISSUE THREAD

**Issue by 3douhao** [siduck76/NvChad#2032]
**Describe the bug**

Netrw can not be enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Terminal: Iterm
 - Version of Neovim: 0.9

**Additional context**
I read closed issues about netrw and paste the following code into the chadrc.lua file in the custom folder. 
> ```lua
> M.options = {
>    disable_default_plugins = {
>       "2html_plugin",
>       "getscript",
>       "getscriptPlugin",
>       "gzip",
>       "logipat",
>       "matchit",
>       "tar",
>       "tarPlugin",
>       "rrhelper",
>       "spellfile_plugin",
>       "vimball",
>       "vimballPlugin",
>       "zip",
>       "zipPlugin",
>    },
> }
> ```

However, it does not work.
Anyone can kindly teach me how to enable netrw? Thanks a lot.

**Comment by 3douhao** [comment]
I pasted the followiing code to chadrc.lua and it worked.
```
M.lazy_nvim = {
  performance = {
    rtp = {
      disabled_plugins = vim.tbl_filter(function(name)
        return string.sub(name, 1, 5) ~= "netrw"
      end, require("plugins.configs.lazy_nvim").performance.rtp.disabled_plugins),
    },
  },
}
```

**Comment by siduck** [comment]
> I pasted the followiing code to chadrc.lua and it worked.
> 
> ```
> M.lazy_nvim = {
>   performance = {
>     rtp = {
>       disabled_plugins = vim.tbl_filter(function(name)
>         return string.sub(name, 1, 5) ~= "netrw"
>       end, require("plugins.configs.lazy_nvim").performance.rtp.disabled_plugins),
>     },
>   },
> }
> ```

congrats! you're one of the rare ones here who managed to fix the issue on own :D
