### ISSUE TITLE
Folder icon in nvim-tree no longer showing unless folder is open

### ISSUE THREAD

**Issue by wobbleRed** [siduck76/NvChad#2034]
**Describe the bug**
Folder icons are no longer showing up unless the file is open it just shows an empty box

**To Reproduce**
pull in latest changes, restart nvim, open up a directory with sub directories and you will see it.

**Expected behavior**

**Screenshots**
<img width="380" alt="image" src="https://github.com/NvChad/NvChad/assets/10539888/8209f37c-450a-4410-9009-6d3992d315e1">

**Desktop (please complete the following information):**
 - MacOS
 - Kitty
 - 0.9.0

**Additional context**

**Comment by siduck** [comment]
hi @wobbleRed 
![image](https://github.com/NvChad/NvChad/assets/59060246/20259add-eb1d-4ac7-8cfd-d47f2d25e8f2)

**Comment by georgejean** [comment]
@wobbleRed.
If you go through similar problems, custom config is also your friend :
```nvim
-- custom/plugins.lua
 {
    "nvim-tree/nvim-tree.lua",
    opts = { renderer = { icons = { glyphs = {
      folder = { default = "󰉋" }
    } } } },
  },
```
with the ad-hoc icon [here](https://www.nerdfonts.com/cheat-sheet).
