### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by gaetgu** [siduck76/NvChad#204]
**Describe the bug**
When indenting on enter, nvim does indents closing bracket, and indents content too far.

**To Reproduce**
1. Open a supported file type (but more obscure, such as `.ino` for arduino files)
2. Create a new function or something with brackets, and hit enter.
3. Notice that the indentation is messed up

**Expected behavior**
Languages such as `.wren` (added syntax support through a plugin) and `.ino` should have the same indentation behavior as languages such as `.js` and `.c`. 

**Screenshots**
C:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/47652746/127708402-1e17551d-3ee5-44e6-8323-c5c645b5ef42.png">
Ino (Ino is just C but with some extensions, should not be handled differently):
<img width="196" alt="image" src="https://user-images.githubusercontent.com/47652746/127708486-e0f746be-f38b-4bb3-917a-a72a9a4daaad.png">

**Desktop:**
 - macOS 12.0
 - iTerm2
 - NVIM v0.5.0-dev+1419-gf76f72a27

**Comment by siduck76** [comment]
weird happens with me too .

![image](https://user-images.githubusercontent.com/59060246/127790686-8df7aedb-bcd8-4370-9fde-da8bff0f7556.png)


Idk if setting indent of C file to ino filetype is possible

**Comment by siduck76** [comment]
check this https://github.com/sudar/vim-arduino-syntax

**Comment by gaetgu** [comment]
It is less of a problem with specifically `.ino` files as it is with just about every filetype from a more obscure language. For example, I am using [wren](https://github.com/wren-lang/wren) for some gamedev, and this indentation problem is ***really*** annoying. I *do* have a language plugin for wren, but it is not doing anything (besides adding syntax highlighting ofc)

**Comment by siduck76** [comment]
does the plugin i mentioned earlier do any good?

**Comment by gaetgu** [comment]
yes, it does. I have installed a language plugin for another language, but it is not fixing the problem. Since the problem is fixable, I will just close this issue and maybe try to write my own plugin.
