### ISSUE TITLE
Registry installation failed for mason

### ISSUE THREAD

**Issue by speckbr** [siduck76/NvChad#2041]
**Describe the bug**
In a fresh install of NvChad, at the first time opening neovim, the mason registry fail to be installed

**To Reproduce**
1. go to nvchad official site
2. Click on 'Docker'
3. Copy the 'docker run" command listed in the 'install' section
4. Paste it on a linux terminal. The machine must have docker installed and the user must have permission to run docker
5. When asked if you want to install the example config, choose 'N'

**Expected behavior**
An error message as displayed in the screenshot

**Screenshots**
![luty](https://github.com/NvChad/NvChad/assets/91562634/40e085bf-6ca0-4b8d-8cf6-15424efe2a72)

**Desktop (please complete the following information):**
 - Debian GNU/Linux 12 (bookworm)
 - Kitty
 - Version of Neovim: 0.9.0

**Comment by siduck** [comment]
hi @speckbr this isnt a nvchad issue, raise it on mason.nvim repo

**Comment by speckbr** [comment]
> hi @speckbr this isnt a nvchad issue, raise it on mason.nvim repo

Hi @siduck. I solved my problem. The alpine image has a busybox version of the wget package that does not work with mason. I just added the 'wget' package in the 'docker run' line that installs the dependencies and it worked for me. I believe the site should be changed in the site. This is the command that worked:

`docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git nodejs neovim ripgrep build-base wget --update
  && git clone https://github.com/NvChad/NvChad ~/.config/nvim
  && nvim
  '`

**Comment by siduck** [comment]
@speckbr is it necessary to add the && ? cant it be multi-lined like before?

![image](https://github.com/NvChad/NvChad/assets/59060246/ee049e2d-fc57-4371-9257-11e86add736c)

**Comment by plucio-beegol** [comment]
> @speckbr is it necessary to add the && ? cant it be multi-lined like before?
> 
> ![image](https://user-images.githubusercontent.com/59060246/240115415-ee049e2d-fc57-4371-9257-11e86add736c.png)

It is not necessary to add the &&. You can use the multine as before. I put it there because in the post i could not put it multine. Just add the wget

**Comment by speckbr** [comment]
> @speckbr is it necessary to add the && ? cant it be multi-lined like before?
> 
> ![image](https://user-images.githubusercontent.com/59060246/240115415-ee049e2d-fc57-4371-9257-11e86add736c.png)

There is no need to add the '&&'. It is exactly as your screenshot.

**Comment by ferdinandhubbard981** [comment]
> Hi @siduck. I solved my problem. The alpine image has a busybox version of the wget package that does not work with mason. I just added the 'wget' package in the 'docker run' line that installs the dependencies and it worked for me. I believe the site should be changed in the site. This is the command that worked:
> 
> `docker run -w /root -it --rm alpine:latest sh -uelic ' apk add git nodejs neovim ripgrep build-base wget --update && git clone https://github.com/NvChad/NvChad ~/.config/nvim && nvim '`

This fixed the issue for me. It should be added to the website's docker install command.

**Comment by siduck** [comment]
> > Hi @siduck. I solved my problem. The alpine image has a busybox version of the wget package that does not work with mason. I just added the 'wget' package in the 'docker run' line that installs the dependencies and it worked for me. I believe the site should be changed in the site. This is the command that worked:
> > `docker run -w /root -it --rm alpine:latest sh -uelic ' apk add git nodejs neovim ripgrep build-base wget --update && git clone https://github.com/NvChad/NvChad ~/.config/nvim && nvim '`
> 
> This fixed the issue for me. It should be added to the website's docker install command.

![image](https://github.com/NvChad/NvChad/assets/59060246/8a603189-688f-41f9-950e-ff347f75adaf)

**Comment by ferdinandhubbard981** [comment]
> > This fixed the issue for me. It should be added to the website's docker install command.
> 
> ![image](https://user-images.githubusercontent.com/59060246/251515557-8a603189-688f-41f9-950e-ff347f75adaf.png)

Can't see wget in the command you screenshotted.

**Comment by siduck** [comment]
> > > This fixed the issue for me. It should be added to the website's docker install command.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/59060246/251515557-8a603189-688f-41f9-950e-ff347f75adaf.png)
> 
> Can't see wget in the command you screenshotted.

oops my bad, i missed. pushed the change
