### ISSUE TITLE
having hard time setting up luasnip in nvchad

### ISSUE THREAD

**Issue by Aneeqasif** [siduck76/NvChad#2043]
i am trying to  to install ultisnip and its cmp support in nvchad https://github.com/quangnguyen30192/cmp-nvim-ultisnips and https://github.com/SirVer/ultisnips. but the issue is the cmp config is so tightly modified for luasnip that i am confused where should i put ultisnip-cmp configs as given in https://www.zoomiti.net/2022/08/21/cmp-ultisnips.html

**Comment by siduck** [comment]
@Aneeqasif 

- Add ultisnip and its cmp plugin as dependencies in cmp 
- Disable luasnip ( i  hope you know how to do it with lazy.nvim )
- Disable cmp mappings that need luasnip
