### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by nafsuuddin** [siduck76/NvChad#2046]
I have installed nvchad and when I run nvim I get the following error: 

Error detected while processing /home/kali/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/kali/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/kali/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/kali/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue

**Comment by siduck** [comment]
please use neovim 0.8.3 at least
