### ISSUE TITLE
Can only see onedark.lua in themes folder.

### ISSUE THREAD

**Issue by SmellsNice** [siduck76/NvChad#205]
**Describe the bug**
As the title states I cannot find the gruvchad theme to modify.

**To Reproduce**
Use install.sh
Basically it.

**Expected behavior**
For there to be 2(?) files.

**Desktop (please complete the following information):**
 - EndeavourOS
 - Alacritty
 - 0.5.0

**Comment by siduck76** [comment]
It should work , update your nvchsd conifg

**Comment by SmellsNice** [comment]
Solved. Needed to clone github instead of using release.

**Comment by siduck76** [comment]
> Solved. Needed to clone github instead of using release.

oh yea the releases are meant to store specific versions of nvchad. I'll mention that in the config!
