### ISSUE TITLE
How to use sniprun in NvChad?

### ISSUE THREAD

**Issue by supursql** [siduck76/NvChad#2050]
![sc_20230523210646](https://github.com/NvChad/NvChad/assets/33394080/cd1f3193-285e-4d4c-b360-745b335337ab)

The ”sniprun“ plugin has a do operation，But NvChad doesn't support it.
![image](https://github.com/NvChad/NvChad/assets/33394080/4e5eef59-47fe-4f3c-b3ae-86420322d85b)

**Comment by siduck** [comment]
run => build , please read lazy.nvim docs
