### ISSUE TITLE
NvChad Mason.nvim stuck at installing lua-language-server

### ISSUE THREAD

**Issue by SwayKh** [siduck76/NvChad#2057]
I Just installed the NvChad config via following the Install Instructions, And Mason.nvim is stuck at installing lua-language-server on the initial startup. Not Sure if this is expected behaviour or If there were any additional instructions that I had to follow, as I was not able to find any related Issue related to this behaviour.

I have tried Manually installing lua-language-server via `MasonInstall` command and Removing the config and and reinstalling it. I was however able to Install `stylua` and `gofumpt` Formatters
 
I Am running Pop Os 22.04 LTS
Kitty Terminal, with Nerd Fonts installed
Neovim version is 0.9.0

**Comment by georgejean** [comment]
Try to run MasonUpdate from command line and retry.

**Comment by siduck** [comment]
@SumitKhatri712  please show  a screenshot

**Comment by georgejean** [comment]
@siduck Shouldn't be a good idea to add `build = ":MasonUpdate"` at Mason's plugin Spec in `plugins/init.lua`?

**Comment by georgejean** [comment]
I've read [this](https://github.com/williamboman/mason.nvim#registries) : 

> Mason's core package registry is located at [mason-org/mason-registry](https://github.com/mason-org/mason-registry). Before any packages can be used, the registry needs to be downloaded. This is done automatically for you when using the different Mason commands (e.g. :MasonInstall), but can also be done manually by using the :MasonUpdate command.

so the registries should be updated anyway.

**Comment by SwayKh** [comment]
![Screenshot from 2023-05-26 21-38-33](https://github.com/NvChad/NvChad/assets/59339401/5a094edd-e83b-4705-a68e-95c512194e64)

Mason is stuck here, This is after running `MasonUpdate`. 
I've reinstalled multiple times now. `MasonLog` also shows no error other than `Installation Was Aborted`

**Comment by georgejean** [comment]
Are there errors or warnings after running checkhealth ?

**Comment by SwayKh** [comment]
![Screenshot from 2023-05-26 22-14-32](https://github.com/NvChad/NvChad/assets/59339401/b0528b5e-5686-4630-8ade-9fe8417d1488)

No, there are no warning or errors

**Comment by siduck** [comment]
@SumitKhatri712  its not related to nvchad, but mason.nvim so closing this. if you're able to work lua-lsp with non nvchad configs then i'll look into this

**Comment by georgejean** [comment]
You can also try a [manual install](https://github.com/luals/lua-language-server/wiki/Getting-Started#command-line) of lua ls.

**Comment by SwayKh** [comment]
![Screenshot from 2023-05-26 23-08-11](https://github.com/NvChad/NvChad/assets/59339401/5120597b-b44a-4e77-b5e7-c6b87d6ec656)
@siduck  I deleted the NvChad config and tried out AstroNvim, Mason.nvim was still showing errors with a few LSP but I was able to install Lua-language-server.

**Comment by siduck** [comment]
@SumitKhatri712  try MasonInstall lua-language-server

**Comment by SwayKh** [comment]
I did try running `MasonInstall lua-language-server` manually, it still gets stuck at the exact same place

**Comment by siduck** [comment]
> I did try running `MasonInstall lua-language-server` manually, it still gets stuck at the exact same place

try this config https://github.com/NvChad/basic-config and lemme if it works, if it does then i'll reopen this issue

**Comment by SwayKh** [comment]
Sorry, I didn't get a chance to use Basic config you mentioned. 
But the issue seems to have solved itself.
After various re-installs and trying out AstroNvim and LunarVim, I downloaded the NvChad config again and It just worked out of the box. 
I didn't have to take any special steps So I am not sure what the solution was.  
Thanks for the help anyway

**Comment by bheemaguli** [comment]
Facing same error here. Tried to install on my Arch system and was failing. I hopped to my Ubuntu system, and it worked right out of the box. 
Using basic-config throws more error.

![Screenshot_20230527_230452](https://github.com/NvChad/NvChad/assets/55400146/c011263e-d354-49b0-8da1-c6f5edb82b72)

**Comment by barungh** [comment]
> Facing same error here. Tried to install on my Arch system and was failing. I hopped to my Ubuntu system, and it worked right out of the box. Using basic-config throws more error.
> 
> ![Screenshot_20230527_230452](https://user-images.githubusercontent.com/55400146/241416674-c011263e-d354-49b0-8da1-c6f5edb82b72.png)

I also use Arch, 

It looks like NodeJs and npm is not installed in your machine

**Comment by bheemaguli** [comment]
@barungh My bad. nvm was not sourced. 

As for issue, I tried @SumitKhatri712 method of installing one config after the other. Installing LunarVim did the job for me. I just had to run the installation script, install needed dependencies, uninstall and get back to NvChad.
