### ISSUE TITLE
LSP is not working.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2058]
I'm using clangd with C++ and installed it using the Mason plugin provided by nvChad. Where are some proofs:

![errors](https://github.com/NvChad/NvChad/assets/101094719/ce13e845-480d-4d60-a189-444e0dedff20)

![lsp](https://github.com/NvChad/NvChad/assets/101094719/4c714e8c-a054-48d3-90b5-f705c935aa7e)

Please give me the solution or fix it soon.

**Comment by siduck** [comment]
@MubinMuhammad as-salamu alaikum brother, enable clangd lsp in  your custom lspconfig. mason plugin just downloads the lsp and doesnt set in your config. You can think it like your package manager which can install clangd, but how would you tell neovim to use clangd? nvim-lspconfig plugin does it!

https://nvchad.com/docs/config/lsp
