### ISSUE TITLE
LSP does not work after following nvChad's LSP tutorial.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2059]
Assalamu Alaikum (if you are muslim), I am using C++ with clangd and it does not work. This is my C++ code:

``` cpp
#include <iostream>
#include <cstdlib>

template<class T>

class automem {
  public:
    T *container = (T)malloc(sizeof(T));
    idnt capacity = 0; // <-- one error here.
    int size = 0;

    void insert(T value);
}

typedef<class T> utomem::insert() { // <-- 2 more here
  if (capacity == size) {
    
  }
} 
```

In this code there are three errors.
And here is the configuration in the  `.config/nvim/lua/custom/configs/lspconfig.lua`:

``` lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

lspconfig.clangd.setup {
  on_attach = on_attach,
  capabilities = capabilities,
}
```

And here is the configuration in the `.config/nvim/lua/custom/plugins.lua`:

``` lua
-- In order to modify the `lspconfig` configuration:
{
  "neovim/nvim-lspconfig",
   config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
   end,
},
```

By the way, I'm new to Neovim I used Helix before so don't mind if the problem was very stupid.

**Comment by barungh** [comment]
your lsp config file does not look okay,

did you choose to **install example configuration** during installation or not ?

if not I suggest you do re install and choose Y to install example config,

clangd ( lsp for c++ ) is configured in example config

also be sure to have prerequisite installed

**Comment by mubin-thinks** [comment]
I have figured it out. The problem was that I have to put `M.plugins = 'custom.plugins'` in the chadrc.lua file and now it works perfectly. (consider islam)

**Comment by siduck** [comment]
> I have figured it out. The problem was that I have to put `M.plugins = 'custom.plugins'` in the chadrc.lua file and now it works perfectly. (consider islam)

yes that loads the custom plugins file so obviously its needed!
