### ISSUE TITLE
Lsp issues when entering buffer

### ISSUE THREAD

**Issue by JustSage** [siduck76/NvChad#206]
The issue is separated to two problems:
1. Once entering a new buffer (without writing the file), Lsp commands are not accessible. Meaning I would have to save the file (:w), exit the buffer and enter the buffer again either from vim or the terminal. 
The completions provided are Luasnip's/buffer but Lsp is not present.
2. After entering a saved file, the expected behavior would be the attachment of an Lsp. Yet the completion, again triggers Luasnip/buffer, Lsp commands do work. LspInfo does provide with the Lsp path. Using LspStart command does trigger activate Lsp yet it doesn't happen automatically as it should.

Will note this was tested in python, c/c++, java and js.

[![Problem 1](https://user-images.githubusercontent.com/50245184/127734099-f6225f7e-495a-49c1-ac1e-2f81c208cdb9.mp4)]
[![Problem 2](https://user-images.githubusercontent.com/50245184/127734109-959a4997-daef-4132-99e6-e6cc683cff96.mp4)]

**Comment by siduck76** [comment]
@JustSage this was present with your custom config right?

**Comment by siduck76** [comment]
@JustSage this was present with your custom config right?

**Comment by JustSage** [comment]
Yes I managed to solve it after reordering pluginList putting fugitive at the bottom and changing `BufRead` to `BufEnter` on lspinstall and lspkind
