### ISSUE TITLE
Incorrect icon on telescope's git files

### ISSUE THREAD

**Issue by luizkowalski** [siduck76/NvChad#2060]
hey 👋🏻 

I'm unsure if this is the right place to report this (if not, please point me in the right direction).

The icon for Git Files on Telescope is missing/wrong:

<img width="773" alt="image" src="https://github.com/NvChad/NvChad/assets/112706/82abd324-94b1-44f2-b5b4-e8ae52cda916">

I also see this on Find Files options too:

<img width="685" alt="image" src="https://github.com/NvChad/NvChad/assets/112706/b9de32ac-471f-47ee-b7e9-c4390b58d2bf">

I tried running `nerdfix` (with `find . -type f -name '*.lua' -exec nerdfix fix -w {} \;`) on `~/.local/share/nvim/lazy/` folder, no icons changed this time (they did when initially Nerd Fonts 3 was released)

I tried updating the plugins with `:Lazy update` but nothing has changed. 

I also tried running `:NvChadUpdate` and it broke the directory icons too:

<img width="320" alt="image" src="https://github.com/NvChad/NvChad/assets/112706/1fc15ec7-41c2-4860-bb24-9f3c0c0dae1f">

but the open folder icon is correct:

<img width="239" alt="image" src="https://github.com/NvChad/NvChad/assets/112706/a4c92aae-15c1-4bb4-a3d6-db6803a38553">

edit: changing the nerd font (was using Symbols Nerd) fixed the directory icons but no the one as initially report on Telescope

**Desktop (please complete the following information):**
 - MacOS 13.4
 - iTerm 2 3.4.19
 ```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by siduck** [comment]
hi @luizkowalski for the search icon in telescope, its an issue with iterm2 , just override the icon. And for the folder icons, update nerdfonts icon to v3.0.1 ( latest )
