### ISSUE TITLE
nvChand installing problem

### ISSUE THREAD

**Issue by sahiltrambadiya707** [siduck76/NvChad#2061]
I got this issue while installing nvChand please help to slove this problem
Neovim version => 0.9.0
vim version => 8.2.4919 

Error detected while processing /home/sahil/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.version' not found:
        no field package.preload['vim.version']
        no file './vim/version.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/version.lua'
        no file '/usr/local/share/lua/5.1/vim/version.lua'
        no file '/usr/local/share/lua/5.1/vim/version/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/vim/version.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/vim/version/init.lua'
        no file './vim/version.so'
        no file '/usr/local/lib/lua/5.1/vim/version.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/vim/version.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...hare/nvim/lazy/base46/lua/base46/integrations/syntax.lua:121: in main chunk
        [C]: in function 'require'
        .../sahil/.local/share/nvim/lazy/base46/lua/base46/init.lua:80: in function 'load_highlight'
        .../sahil/.local/share/nvim/lazy/base46/lua/base46/init.lua:133: in function 'compile'
        /home/sahil/.config/nvim/lua/core/bootstrap.lua:18: in function 'lazy'
        /home/sahil/.config/nvim/init.lua:16: in main chunk
E484: Can't open file /__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim/syntax/syntax.vim

**Comment by siduck** [comment]
rm  -rf ~/.local/share/nvim

make sure you have neovim v0.9 and then install nvchad

**Comment by sahiltrambadiya707** [comment]
Thank you so mush but i have one more problem 
i use nvim.appimage to install nvim 0.9.0
so how to get nvim global command 
when i run this is workin fine ./squashfs-root/usr/bin/nvim
but i try to run nvim is not working

**Comment by siduck** [comment]
@sahiltrambadiya707  compile neovim from source or use bob neovim manager, I dont use appimage so cant tell about it

**Comment by sahiltrambadiya707** [comment]
Ok thank you very mush i will try
