### ISSUE TITLE
'}' expected (to close '{' at line 203) near '{'

### ISSUE THREAD

**Issue by phob** [siduck76/NvChad#2064]
I've got an Installation Error:

`Error detected while processing C:\Users\Pho\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:21: C:\Users\Pho\AppData\Local\nvim/lua/plugins/init.lua:205: '}' expected (to close '{' at line 203) near '{'
stack traceback:
        [C]: in function 'error'
        vim/_init_packages.lua:21: in function <vim/_init_packages.lua:15>
        [C]: in function 'require'
        C:\Users\Pho\AppData\Local\nvim\init.lua:21: in main chunk`

OS: Windows 11
Neovim: 0.9.1 (also the same with 0.9.0)

**Comment by trentzz** [comment]
Having the same issue, exact same message.

OS: PopOS 22.04 LTS
Neovim: 0.9.1 (same issue with 0.9.0 and 0.8.3)

**Comment by martin-braun** [comment]
Run `vim $HOME/.config/nvim/lua/plugins/init.lua` and append a `,` at line 204 and 208.

**Comment by phob** [comment]
After that everything downloads fine in the background and then I get:
`Error executing vim.schedule lua callback: C:\Users\Pho\AppData\Local\nvim/lua/core/utils.lua:80: attempt to index a nil value
stack traceback:
        C:\Users\Pho\AppData\Local\nvim/lua/core/utils.lua:80: in function <C:\Users\Pho\AppData\Local\nvim/lua/core/utils.lua:55>`

**Comment by lukasschachner** [comment]
should this be reopened or should another issue be opened for the followup issue

**Comment by siduck** [comment]
guys do a git pull!

**Comment by lukasschachner** [comment]
already did. the issue @phob is talking about still persists

**Comment by siduck** [comment]
> already did. the issue @phob is talking about still persists

show me the output of git log command

**Comment by lukasschachner** [comment]
[nvchad.log](https://github.com/NvChad/NvChad/files/11592218/nvchad.log)

**Comment by siduck** [comment]
> [nvchad.log](https://github.com/NvChad/NvChad/files/11592218/nvchad.log)

rm -rf .local/share/nvim and reopen nvim

**Comment by lukasschachner** [comment]
> > [nvchad.log](https://github.com/NvChad/NvChad/files/11592218/nvchad.log)
> 
> rm -rf .local/share/nvim and reopen nvim

fixed the issue
