### ISSUE TITLE
Autocompletion / snippet issues

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [siduck76/NvChad#2069]
**Describe the bug**
characters appear after auto-completion is confirmed (if you dont enter any word, for eg -  (class.) then I use tab to see the methods, when I click any one, this problem occurs, but if i type atleast 1 or 2 letters, problem wont appear)
I dont have idea why this problem occurs, probably with LSP ? or snippet engine?

**Screenshots**
![Screenshot_20230530_134824](https://github.com/NvChad/NvChad/assets/76522725/7b6affad-723d-4fc0-8ddf-fde3aed7cc3d)

and i do get warning like this sometimes 
![image](https://github.com/NvChad/NvChad/assets/76522725/3510172c-253b-47bb-9522-84ba719b6e4e)

**Desktop (please complete the following information):**
 - Operating System - Arch linux
 - Terminal - Kitty
 - Version of Neovim - 0.9.1

**Comment by siduck** [comment]
the multiple encodings issue isnt related to nvchad

**Comment by siduck** [comment]
unable to reproduce this issue, can you check if it happens with other lsp servers?

**Comment by piush-terminalwitchcraft** [comment]
It happens with dart as well.

**Comment by siduck** [comment]
i'm unable to reproduce this! does it happen with other terminals?

**Comment by mrw954** [comment]
Add the following code to null-ls.lua

```
 local notify = vim.notify
 vim.notify = function(msg, ...)
   if msg:match "warning: multiple different client offset_encodings" then
     return
   end
   notify(msg, ...)
 end
```
Reference:https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428

**Comment by piush-terminalwitchcraft** [comment]
okayy, and is this thing related to autocompletion issue?

**Comment by piush-terminalwitchcraft** [comment]
> i'm unable to reproduce this! does it happen with other terminals?

need to check  let me try with alacritty

**Comment by siduck** [comment]
> > i'm unable to reproduce this! does it happen with other terminals?
> 
> need to check let me try with alacritty

does it work?

**Comment by cpra** [comment]
I had the same issue when using `clangd`, fixed it via lspconfig as per [lazyvim's instructions](https://www.lazyvim.org/configuration/recipes#fix-clangd-offset-encoding).

**Comment by ronandalton** [comment]
@cpra Would you be able to elaborate on the steps you used to solve this problem? I tried pasting the linked snippet into `custom/plugins.lua` but nothing changed. I am using the example config.
