### ISSUE TITLE
how to remap backtick mark with single-quote mark globally?

### ISSUE THREAD

**Issue by bommbo** [siduck76/NvChad#2070]
I don't know how to config keymap.
```
vim.cmd("nnoremap ' `");
vim.cmd("nnoremap ` '");
vim.cmd("onoremap ' `");
vim.cmd("onoremap ` '");
```
It's not working like that.

**Comment by siduck** [comment]
whichkey maps those keys so you have to either disable whichkey or put the nnoremap code in whichkey config function as well as your custom/init.lua

```lua

  {
    "folke/which-key.nvim",
    config = function(_, opts)
      dofile(vim.g.base46_cache .. "whichkey")
      require("which-key").setup(opts)

      vim.cmd "nnoremap ' `"
      vim.cmd "nnoremap ` '"
      vim.cmd "onoremap ' `"
      vim.cmd "onoremap ` '"
    end,
  },
  ```

**Comment by bommbo** [comment]
But It can't show anything when I press ' or `.

**Comment by siduck** [comment]
> But It can't show anything when I press ' or `.

yes because you're remapping them! so whichkey stuff wont work. What you can do is map those whichkey functions to your keys instead

**Comment by bommbo** [comment]
How to map those whichkey function about " ` "? https://github.com/folke/which-key.nvim/issues/270 is a great example. But I don't know how to map " ' " whichkey function .

**Comment by siduck** [comment]
```lua
local wk = require("which-key")

wk.register({
    ["`"] = {
        name = 'Window management',
        w = { function() require'nvim-window'.pick() end, 'Pick Window' },
        s = "Split window",
        v = "Split window vertically",
        q = "Quit a window",
        T = "Break out into a new tab",
        x = "Swap current with next",
        ["-"] = "Decrease height",
        ["+"] = "Increase height",
        ["<lt>"] = "Decrease width",
        [">"] = "Increase width",
        ["|"] = "Max out the width",
        ["="] = "Equally high and wide",
        h = "Go to the left window",
        l = "Go to the right window",
        k = "Go to the up window",
        j = "Go to the down window",
    },
}, { preset = true })
```

**Comment by siduck** [comment]
put it in your whichkey config function

**Comment by bommbo** [comment]
er... I want neovim defalut "`" function. It's  move to mark not window manager.

**Comment by siduck** [comment]
> er... I want neovim defalut "`" function. It's move to mark not window manager.



> whichkey maps those keys so you have to either disable whichkey or put the nnoremap code in whichkey config function as well as your custom/init.lua
> 
> ```lua
>   {
>     "folke/which-key.nvim",
>     config = function(_, opts)
>       dofile(vim.g.base46_cache .. "whichkey")
>       require("which-key").setup(opts)
> 
>       vim.cmd "nnoremap ' `"
>       vim.cmd "nnoremap ` '"
>       vim.cmd "onoremap ' `"
>       vim.cmd "onoremap ` '"
>     end,
>   },
> ```

this should work :/

**Comment by bommbo** [comment]
Yes, Functionally, the keys are swapped.But It can't show anything through "which-key.nvim" when I press ' or `.

**Comment by siduck** [comment]
> Yes, Functionally, the keys are swapped.But It can't show anything through "which-key.nvim" when I press ' or `.

better ask this in whichkey repo

**Comment by bommbo** [comment]
https://github.com/folke/which-key.nvim/issues/166 ...  It's not be solved now.
