### ISSUE TITLE
New install, getting only vanilla nvim

### ISSUE THREAD

**Issue by madhat2r** [siduck76/NvChad#2071]
**Describe the bug**
I have installed via instructions. (cloned to ~/.config/nvim) but when I launch `nvim` I get plain nvim.
I also installed the example config from the `NvChad/example_config` repo into `custom` folder, still nothing.

I also removed `.config/nvim` and `.local/share/nvim` before installing `NvChad`

**Expected behavior**
NvChad configuration

**Desktop (please complete the following information):**
 - macOS Ventura
 - iTerm2
 - Neovim v0.9.0 (from homebrew)

Thanks for your help.

**Comment by siduck** [comment]
@madhat2r  can you please record a video of this? I find it very hard to believe

**Comment by madhat2r** [comment]
@siduck will this do, or do you need somehting else?

https://github.com/NvChad/NvChad/assets/4122449/194c1956-3aac-43b6-aad4-4e6da221720e

**Comment by madhat2r** [comment]
I also just noticed that there was a newer version of nvim on homebrew, so I installed v0.9.1 and `rm -r` dirs again and reinstalled but have the same result.

**Comment by georgejean** [comment]
It seems you try to remove `.local/share/.nvim` instead of `.local/share/nvim`.
Is there any message displayed with the command
`:echo $XDG_CONFIG_HOME $XDG_DATA_HOME $NVIM_APPNAME` ?

**Comment by madhat2r** [comment]
You're right, in the video I had it miss-typed. But when I first did it, I got it right. `.local/share/nvim` does not exist on my system until after I launch `nvim`.

Output:
`$XDG_CONFIG_HOME = ~/.config/`
`$XDG_DATA_HOME = not set`
`$NVIM_APPNAME = not set`

**Comment by siduck** [comment]
seems like your PATHS are messed up but idk how

**Comment by thyeun** [comment]
@madhat2r Can i know before that, you have install others Neovim repos right? try go into your ```.cache``` and ```.local/share``` deleted any others Neovim. And try install again.

**Comment by georgejean** [comment]
Indeed, $XDG_CONFIG_HOME seems to have been set.
Try:
`:echo stdpath("config")` (to see the effect of the trailing slash)
`:echo stdpath("state")`

next possible steps:
- unset $XDG_CONFIG_HOME (make it empty),
- clean (or backup) your folders defined by `stdpath(...)` where `...` is either "config", "state", "data" or "cache".
- then try to install again.

**Comment by madhat2r** [comment]
> @madhat2r Can i know before that, you have install others Neovim repos right? try go into your `.cache` and `.local/share` deleted any others Neovim. And try install again.

I have a working install of LunarVim, which should not interfere as it uses it's own custom dirs for everything. The only other repo I have tried is SpaceVim and I believe I have it removed.



> Indeed, $XDG_CONFIG_HOME seems to have been set. Try: `:echo stdpath("config")` (to see the effect of the trailing slash) `:echo stdpath("state")`
> 
> next possible steps:
> 
> * unset $XDG_CONFIG_HOME (make it empty),
> * clean (or backup) your folders defined by `stdpath(...)` where `...` is either "config", "state", "data" or "cache".
> * then try to install again.

The trailing slash did not show up in the `stdpath`. All the "config", "state", "data" or "cache", looked properly configured.

I did remove all of them again, removed `XDG_CONFIG_HOME`, and reinstalled. Still get the same thing.

@siduck you said `seems like your PATHS are messed up but idk how`.  What paths appear to be messed up?

**Comment by siduck** [comment]
@madhat2r .local/share/nvim or .config/nvim

**Comment by madhat2r** [comment]
@siduck Those paths look correct don't they? When echoed from inside nvim they come back properly. After I install NvChad, then launch nvim, the `.local/share/nvim` folder gets created, which should mean paths are correct, no? Perhaps I am missing something here.

**Comment by madhat2r** [comment]
Also I have tried using the new `NVIM_APPNAME` env. variable, which corrects all the paths to be appname specific for nvim. And when checked using `stdpath(..)` they all turned out correctly matched to the new `NVIM_APPNAME` but I still don't have the `NvChad` config even though the paths all point to the right place.

**Comment by siduck** [comment]
@marcomayer ask on our discord server / telegram group
