### ISSUE TITLE
Getting error when using git status.

### ISSUE THREAD

**Issue by thyeun** [siduck76/NvChad#2072]
**Describe the bug**
Getting error when using ```git status```

**To Reproduce**
1. Edit git repos ```Readme.md```
2. Press SPC g t
3. See error

**Expected behavior**

**Screenshots**
```Before using git status```
![Screenshot_2023-05-31-01-07-48_1682](https://github.com/NvChad/NvChad/assets/1939446/ee58c7d2-d64e-4f38-aa8b-ecb291ee5009)

```After using git status```
![Screenshot_2023-05-31-01-00-28_29879](https://github.com/NvChad/NvChad/assets/1939446/77054b50-6c76-4dd4-81eb-f6a723d6dbb4)

**Desktop (please complete the following information):**
 - Operating System : Arch Linux
 - Terminal : kitty
 - Version of Neovim :  v0.9.0-dev-1115+g446c353a5

**Additional context**

**Comment by siduck** [comment]
cd into your git dir, the error is clear.  your folder isnt a git repo! Please ask such trivial issues on our server/groups before making an issue here! it gives me un-necessary tension xD

**Comment by thyeun** [comment]
@siduck No, my folder is a git repos, as you can see it from ```emacs``` screenshot, as below, i wont so silly if my folder are not git repos, and if the folder not git repos, the first images ```Before using git status```, you wont see the git repos status icon ```master``` show on the bar.

![Screenshot_2023-05-31-01-22-29_8733](https://github.com/NvChad/NvChad/assets/1939446/9c1bfdcd-0b65-44fb-bb94-bf766f9d4e4f)

**Comment by siduck** [comment]
@thyeun ohh but still, Telescope git_status command needs  you to "cd" into your git folder and then edit your file so not a nvchad issue!

**Comment by thyeun** [comment]
@siduck ohh i see, luckily it was not Nvchad issue. =.=
