### ISSUE TITLE
The README and the "About" section contradict each other.

### ISSUE THREAD

**Issue by ivandimitrov8080** [siduck76/NvChad#2081]
The README says:
![image](https://github.com/NvChad/NvChad/assets/80976541/b85df225-7b84-490f-98c7-31a4c4ea9855)
While the `About` section says:
![image](https://github.com/NvChad/NvChad/assets/80976541/2fe54338-c9f3-4797-87a6-243da344d131)

So which one is it?

**Comment by siduck** [comment]
@ivandimitrov8080  you are right,  probably i accidentally added it. fixed it
