### ISSUE TITLE
Can't install NvChad on PopOs

### ISSUE THREAD

**Issue by Plarpoon** [siduck76/NvChad#2082]
Hello, I have just formatted my system to the most recent version of PopOS, I went to install NvChad as usual and I noticed an error that prevents me to proceed the installation as a whole.

**To Reproduce**
1. execute the one liner installer: "git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim"
2. See error

**Expected behavior**
The correct installation of the program

**Screenshots**
[screenshot.](https://i.imgur.com/UY7HxWb.png)

**Desktop (please complete the following information):**
 - PopOs
 - Gnome-Terminal
 - None

**Additional context**
I never had this issue before with NvChad, it was always a flawless installation, I am up for testing if I can be of use!

**Comment by siduck** [comment]
install neovim v0.9 at least! please use ubuntu unstable neovim ppa or compile neovim from source or try bob neovim manager
