### ISSUE TITLE
post Installation error

### ISSUE THREAD

**Issue by afrid18** [siduck76/NvChad#2085]
**Describe the bug**

**To Reproduce**
1. Remove existing installation of NvChad using `rm -rf ~/.config/nvim`
2. Do a fresh install with `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
3. See error

**Expected behavior**
A neat installation and Mason window for LSP installation.

**Screenshots**
<img width="1272" alt="image" src="https://github.com/NvChad/NvChad/assets/59523682/985b3221-3b78-4571-b7e6-7832a6035475">

**Desktop (please complete the following information):**
 - MacOS with M1 (Ventura 13.5)
 - Alacritty with Zsh
 - Neovim version: 0.9.0

**Comment by siduck** [comment]
rm -rf .local/share/nvim && nvim
