### ISSUE TITLE
Completions too the whole screen

### ISSUE THREAD

**Issue by yassinebenarbia** [siduck76/NvChad#2086]
As I've checked the nvchad default configs and the nvim-cmp docs, I couldn't find any way of adjusting the number of displayed completions for each keystroke, where as he default behavior took the whole screen where as the completion and the doc's covers most of it.
![NvChad_issue](https://github.com/NvChad/NvChad/assets/104306099/a25f5525-9d69-4ba7-849e-a1de93438f55)

I guess it will be really helpful to have an option under the cmp table key
![NvChad_sol](https://github.com/NvChad/NvChad/assets/104306099/d6c3114f-c492-4b4e-a9b9-742fc819e60a)

:help nvim_open_win() 
This command may be helpful as after a bit of research I found that nvim-cmp use it to display the completion suggestions

**Comment by siduck** [comment]
please set pumheight value! 

vim.opt.pumheight = 10 in your custom init.lua
