### ISSUE TITLE
Getting an error with fresh install

### ISSUE THREAD

**Issue by dsancheznet** [siduck76/NvChad#2087]
After cloning the repo into .config/nvim on a fresh Debian Bookworm RC install I obtain the following error:

```
E5113: Error while calling lua chunk: /home/user/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/user/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/user/.config/nvim/init.lua:1: in main chunk
```

NeoVim Version: 
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

Distro is Debian Bookworm on `Linux Laptop 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux` kernel.

Best regards
DSanchez

**Comment by IzioDev** [comment]
You should look at this page : https://nvchad.com/docs/quickstart/install

This includes Pre-requisites, which you don't have currently, please install newer `neovim` version

**Comment by dsancheznet** [comment]
You are absolutely right.v Just found that out. Please accept my apologies...
