### ISSUE TITLE
The warnings beyond window? How to solve that?

### ISSUE THREAD

**Issue by LikeTheWindGone** [siduck76/NvChad#2088]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
@LikeTheWindGone not a nvchad issue, please use a plugin like lsp_lines.nvim/ trouble.nvim or just leader f to check floating diagnostics. Probably there's some way to do it internally within nvim itself, but idk! so ask on r/neovim or it's matrix server
