### ISSUE TITLE
Colorscheme Override

### ISSUE THREAD

**Issue by krugrantz** [siduck76/NvChad#2092]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by krugrantz** [comment]
Add some more colorschemes in base46 or provide a feature to override it

**Comment by siduck** [comment]
@krugrantz  please check https://nvchad.com/docs/config/theming

**Comment by krugrantz** [comment]
> @krugrantz please check https://nvchad.com/docs/config/theming

https://github.com/olivercederborg/poimandres.nvim


Can you tell me how to plug this in NvChad

**Comment by siduck** [comment]
> > @krugrantz please check https://nvchad.com/docs/config/theming
> 
> https://github.com/olivercederborg/poimandres.nvim
> 
> Can you tell me how to plug this in NvChad

it will break many nvchad highlight groups, a better way would be creating a custom theme for it. check our base46 repo's readme or wait until   I add it, probably next month

**Comment by krugrantz** [comment]
Okay....... it their a way to completely remove base46 from nvchad in my own custom and then introduce poimandres

**Comment by krugrantz** [comment]
> > > @krugrantz please check https://nvchad.com/docs/config/theming
> > 
> > 
> > https://github.com/olivercederborg/poimandres.nvim
> > Can you tell me how to plug this in NvChad
> 
> it will break many nvchad highlight groups, a better way would be creating a custom theme for it. check our base46 repo's readme or wait until I add it, probably next month

Thank you! I'll wait for it. I think poimandres is a very great theme. I'd love to see the integration.

**Comment by siduck** [comment]
> Okay....... it their a way to completely remove base46 from nvchad in my own custom and then introduce poimandres

no, our theming depends on that!
