### ISSUE TITLE
`<Tab>` mapping conflicts with `<C-i>`

### ISSUE THREAD

**Issue by KorigamiK** [siduck76/NvChad#2096]
As referenced by this issue neoclide/coc.nvim#1089 the jumplist is unusable while having the `<Tab>` key mapped. 

https://github.com/NvChad/NvChad/blob/f8a489ea1a670569eead0fe5651c0c48add743e8/lua/core/mappings.lua#L73

I think changing the default mapping for switching buffers would be better as the jumplist is an integral part of the vim navigations.

**Comment by siduck** [comment]
you can just disable the tab used there

**Comment by KorigamiK** [comment]
I'm not sure if it works. 

Can you give me an example for disabling it in the custom config?

**Comment by siduck** [comment]
just override tab mappings 

```lua
{
	"hrsh7th/nvim-cmp",
	opts = {
		mapping = {

			["<Tab>"] = require("cmp").mapping(function(fallback)
				local cmp = require("cmp")

				if cmp.visible() then
					cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
				elseif require("luasnip").expand_or_jumpable() then
					vim.fn.feedkeys(
						vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true),
						""
					)
				else
					fallback()
				end
			end, {
				"i",
				"s",
			}),
		},
	},
}
  ```

**Comment by hugolbz** [comment]
I changed the default mappings , so CTRL+I is mapped to  the vim default (newer position in jump list)
```lua
M.disabled = {
  n = {
      ["<tab>"] = "",
      ["<S-tab>"] = ""
  }
}

M.tabufline = {
  n = {
    -- cycle through buffers
    ["<leader>k"] = {
      function()
        require("nvchad_ui.tabufline").tabuflineNext()
      end,
      "Goto next buffer",
    },

    ["<leader>j"] = {
      function()
        require("nvchad_ui.tabufline").tabuflinePrev()
      end,
      "Goto prev buffer",
    },
  },
}
```

**Comment by KorigamiK** [comment]
> I changed the default mappings , so CTRL+I is mapped to the vim default (newer position in jump list)
> 
> ```lua
> M.disabled = {
>   n = {
>       ["<tab>"] = "",
>       ["<S-tab>"] = ""
>   }
> }
> 
> M.tabufline = {
>   n = {
>     -- cycle through buffers
>     ["<leader>k"] = {
>       function()
>         require("nvchad_ui.tabufline").tabuflineNext()
>       end,
>       "Goto next buffer",
>     },
> 
>     ["<leader>j"] = {
>       function()
>         require("nvchad_ui.tabufline").tabuflinePrev()
>       end,
>       "Goto prev buffer",
>     },
>   },
> }
> ```

Hi, are you able to move backwards in your jump list with this?

**Comment by hugolbz** [comment]
Yes I can move backward with CTRL I

**Comment by KorigamiK** [comment]
> Yes I can move backward with CTRL I

I'm sorry but I'm still having this issue. I am not able to use `Ctrl+I` it just acts like tab for me. Can you tell me what terminal you are using?

**Comment by georgejean** [comment]
Strange coincidence, I've run into this today. Here is a solution (in fact, the same as @hugolbz's). I use Windows Terminal.
```lua
-- custom/mappings
local M = {}

M.disabled = {
  n = {
    ["<tab>"] = "",
  },
}
M.abc = {
  n = {
    --useless actually, only to be registered by which-key :
    ["<tab>"] = {"<C-I>", "Go to [count] newer cursor position in jump list"} 
  },
}

M.tabufline = {
  n = {
    -- cycle through buffers
    ["<leader><tab>"] = {
      function()
        require("nvchad_ui.tabufline").tabuflineNext()
      end,
      "Goto next buffer",
    },
  },
}
return M
```

**Comment by KorigamiK** [comment]
Thanks it turned out that I am actually stupid, I was following the wrong table schema.
Replaced this:

```lua
M.disabled = {
 disabled = {
   n = {
     ["<leader>e"] = "",
     ["<tab>"] = "",
     ["<S-tab>"] = "",
  }
}
```

with this:
```lua
M.disabled = {
  n = {
     ["<leader>e"] = "",
     ["<tab>"] = "",
     ["<S-tab>"] = "",
   }
}
```

**Comment by vuxuanhungg** [comment]
If you're using Kitty terminal, you can use something like this to keep both `Tab` and `Ctrl+I` functionalities
```lua
-- "custom.mappings"

M.disabled = {
  n = {
    ["<tab>"] = "",
  }
}

M.abc = {
  n = {
    ["<C-i>"] = { "<C-i>", "Keep Ctrl+I functionality when press Tab" },
    ["<tab>"] = {
      function()
        require("nvchad.tabufline").tabuflineNext()
      end,
      "Goto next buffer",
    },
  }
}
```

IMPORTANT: need to remap `<C-i>` before mapping `<tab>`. That's why you need to disable the default mapping first and remap yourself.
