### ISSUE TITLE
Uninstalling script

### ISSUE THREAD

**Issue by NikolaTesla13** [siduck76/NvChad#210]
**Is your feature request related to a problem? Please describe.**
I installed NvChad but it doesn't work really well with my system (aesthetically) and I would like to uninstall it.

**Describe the solution you'd like**
A script similar to install.sh but for uninstalling.

**Describe alternatives you've considered**
Or a guide on what config files you need to remove.

**Comment by siduck76** [comment]
Wym not working well? Please  be more specific

**Comment by NikolaTesla13** [comment]
Aesthetically, it doesn't look good with my other programs. There is no problem with NvChad, I just tried it and I'd like to remove it.

**Comment by Akianonymus** [comment]
just remove ~/.config/nvim

**Comment by siduck76** [comment]
> Aesthetically, it doesn't look good with my other programs. There is no problem with NvChad, I just tried it and I'd like to remove it.

Other programs like? If you want to remove it , remove .local/share/nvim too
