### ISSUE TITLE
`:Tutor` not available

### ISSUE THREAD

**Issue by notramo** [siduck76/NvChad#2100]
On a vanilla Neovim config, `:Tutor` opens a tutorial, but not when NvChad is installed.

**Comment by siduck** [comment]
hi its disabled by default cuz once you know basic nvim stuff you'd never open Tutor, this saves some startuptime too, just do nvim --clean to read from it or go to chadrc's lazy_nvim field and enable it there, search for lazy_nvim.lua file in our whole config and you'll know where its disabled
