### ISSUE TITLE
Clangd not working in c++ file

### ISSUE THREAD

**Issue by ATSxp** [siduck76/NvChad#2102]
Hello, when I go into a C++ file, it doesn't find the standard library, but when I'm in a C file, it works perfectly:
![image](https://github.com/NvChad/NvChad/assets/92697714/d6e2a175-8e56-4998-ad9c-1b95d47781ce)

My clangd is already installed by Mason, how can I solve this?

**Desktop (please complete the following information):**
 - Linux Mint 21 xfce
 - urxvt
 - 0.9.0

**Comment by siduck** [comment]
please enable clangd in your custom lspconfig :(
