### ISSUE TITLE
How to correctly add `telescope-fzf-native`?

### ISSUE THREAD

**Issue by GreenSleeper** [siduck76/NvChad#2111]
I add `telescope-fzf-native` like this:
```lua
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-telescope/telescope-fzf-native.nvim",
      build = "make",
      config = function()
        require("telescope").load_extension "fzf"
      end,
    },
    opts = {
     extensions = {
        fzf = {
          fuzzy = true, -- false will only do exact matching
          override_generic_sorter = true, -- override the generic sorter
          override_file_sorter = true, -- override the file sorter
          case_mode = "smart_case", -- or "ignore_case" or "respect_case"
          -- the default case_mode is "smart_case"
        },
      },
    },
  },
```
but fuzzy search using `'`, `$`, `^` doesn't seem to work.

**Comment by siduck** [comment]
are ' $ ^ actual mappings? i dont think so

**Comment by GreenSleeper** [comment]
> are ' $ ^ actual mappings? i dont think so

No, they are like search rules you would use in fzf, like `'` means exact match.
I've make it work now. Closing this.

**Comment by siduck** [comment]
> > are ' $ ^ actual mappings? i dont think so
> 
> No, they are like search rules you would use in fzf, like `'` means exact match. I've make it work now. Closing this.

how did you make it work? i'd like to use this feature as well

**Comment by GreenSleeper** [comment]
I changed the configuration to this:
```lua
  {
    "nvim-telescope/telescope-fzf-native.nvim",
    build = "make",
    event = "BufReadPost",
    config = function()
      require("telescope").load_extension "fzf"
    end,
  },

  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-telescope/telescope-fzf-native.nvim",
    },
    opts = {
      extensions = {
        fzf = {
          fuzzy = true, -- false will only do exact matching
          override_generic_sorter = true, -- override the generic sorter
          override_file_sorter = true, -- override the file sorter
          case_mode = "smart_case", -- or "ignore_case" or "respect_case"
          -- the default case_mode is "smart_case"
        },
      },
    },
  },
```
Didn't really know the difference, but it works for me now.

**Comment by siduck** [comment]
probably it removes lazyloading of that plugin,  btw could you record a video of this feature? I'd like to see how it works.Never used fzf for this so idk

**Comment by GreenSleeper** [comment]
Sorry, I'm using this at work and due to company policy, I can't upload pictures to webpage. But I'm sure that there are enough tutorials about fzf, it's fairly popular.



---Original---
From: "Sidhanth ***@***.***&gt;
Date: Thu, Jun 15, 2023 12:45 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [NvChad/NvChad] How to correctly add `telescope-fzf-native`?(Issue #2111)




 
probably it removes lazyloading of that plugin,  btw could you record a video of this feature? I'd like to see how it works.Never used fzf for this so idk

**Comment by mebble** [comment]
I found this thread useful, but it still didn't work for me. It would error with
```
This extension doesn't exist or is not installed: fzf
libfzf.so (no such file)
```

Ultimately I got it working by doing this
```lua
{
    "nvim-telescope/telescope.nvim",
    dependencies = {
        'nvim-telescope/telescope-fzf-native.nvim',
        build = 'make',
        lazy = false,
        config = function ()
            require('telescope').load_extension('fzf')
        end
    }
}
```

I copied this from [lazyvim's example plugins file](https://github.com/LazyVim/starter/blob/main/lua/plugins/example.lua). One difference from that one is that I also included `lazy = false` because without it, the fzf extension didn't seem to start up.

**Comment by fabiodcorreia** [comment]
@mebble Do you notice a lot of difference in terms of performance or usability?

**Comment by mebble** [comment]
@fabiodcorreia Difference from the terminal's fzf? Nope it seems to run pretty fast, even on a moderately large java project. I've only started using it today though.

**Comment by fabiodcorreia** [comment]
> @fabiodcorreia Difference from the terminal's fzf? Nope it seems to run pretty fast, even on a moderately large java project. I've only started using it today though.

@mebble The fzf on the terminal is good but Telescope sometimes feels some lag, I was wondering if using that native extension would improve telescope experience with big workspaces.

**Comment by mebble** [comment]
I've never had a speed problem with the built-in telescope fuzzy finder, but if you have, then it's worth trying out the fzf extension

**Comment by GreenSleeper** [comment]
@fabiodcorreia I've been working with large codebase, and from my experience, I don't think there is a very noticeable performance difference between telescope built-in fuzzy finder and `telescope-fzf-native`.
I've been using [fzf-lua](https://github.com/ibhagwan/fzf-lua) with `NvChad` for a while, and it's much faster than `telescope`.

here's my `opts` section for it btw
```lua
opts = {
      "borderless_full",
      global_file_icons = true,
      global_git_icons = false,
      -- files = {
      --   path_shorten = 1,
      -- },
      -- grep = {
      --   path_shorten = 1,
      -- },
      winopts = {
        height = 0.8,
        width = 0.9,
        row = 0.5,
        preview = {
          horizontal = "right:55%",
          -- winopts = {
          --   number = false,
          -- },
        },
        on_create = function()
          vim.keymap.set("t", "<C-r>", [['<C-\><C-N>"'.nr2char(getchar()).'pi']], { expr = true, buffer = true })
        end,
      },
      hls = {
        normal = "TelescopeNormal",
        border = "TelescopeBorder",
        title = "TelescopePromptTitle",
        help_normal = "TelescopeNormal",
        help_border = "TelescopeBorder",
        preview_normal = "TelescopeNormal",
        preview_border = "TelescopeBorder",
        cursor = "Cursor",
        cursorline = "TelescopePreviewLine",
        cursorlinenr = "TelescopePreviewLine",
        search = "IncSearch",
        preview_title = "TelescopePreviewTitle",
      },
      fzf_colors = {
        ["fg"] = { "fg", "TelescopeNormal" },
        ["bg"] = { "bg", "TelescopeNormal" },
        ["hl"] = { "fg", "TelescopeMatching" },
        ["fg+"] = { "fg", "TelescopeSelection" },
        ["bg+"] = { "bg", "TelescopeSelection" },
        ["hl+"] = { "fg", "TelescopeMatching" },
        ["info"] = { "fg", "TelescopeMultiSelection" },
        ["border"] = { "fg", "TelescopeBorder" },
        ["gutter"] = { "bg", "TelescopeNormal" },
        ["prompt"] = { "fg", "TelescopePromptPrefix" },
        ["pointer"] = { "fg", "TelescopeSelectionCaret" },
        ["marker"] = { "fg", "TelescopeSelectionCaret" },
        ["header"] = { "fg", "TelescopePromptTitle" },
      },
    }
```
