### ISSUE TITLE
Icons doesn't work in the nvim tree. 

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2112]
Assalamu Alaikum (if you are muslim). Why NvChad does not realize the icons for the folder in my project. I am using Nerd Font as well.
I think it is a bug. So please fix it fast.
![No_Icons](https://github.com/NvChad/NvChad/assets/101094719/4900ae9c-93fa-46b0-a7df-b02a5787a868)

**Comment by siduck** [comment]
waleykumusalam wa rehmutAllahi wa barkhatu, please update nerdfonts to latest

**Comment by mubin-thinks** [comment]
Thanks, That worked.
