### ISSUE TITLE
Allow custom config on $XDG_CONFIG_HOME/nvchad/lua/custom

### ISSUE THREAD

**Issue by robsonpeixoto** [siduck76/NvChad#2116]
**Is your feature request related to a problem? Please describe.**
Make the `custom` configs easier to manage in a dotfiles repository.

**Describe the solution you'd like**
I'd like to use another directory, like `~/.config/nvchad/lua/custom`, to keep all custom configs and keep it tracked by my git repository.

References:
- https://astronvim.com/Configuration/manage_user_config#setting-up-a-user-configuration
- https://github.com/AstroNvim/AstroNvim/blob/54545b9db3f8d82e1fc619b87469a51c3e028012/lua/astronvim/bootstrap.lua#L17-L22

**Comment by siduck** [comment]
@robsonpeixoto just symlink  your dotfiles/custom i.e

ln -s ~/dotfiles/custom ~/.config/nvim/lua/custom

works for me

![image](https://github.com/NvChad/NvChad/assets/59060246/1ffce530-1401-46b9-877b-d3f17b256d67)
