### ISSUE TITLE
Plugins for debugging stuff

### ISSUE THREAD

**Issue by siduck76** [siduck76/NvChad#212]
nvim dap , dap ui and dapInstall

**Comment by erikrodrgz** [comment]
@siduck76 Do you plan to add debuggers to NvChad? It would be really cool!

**Comment by siduck76** [comment]
> @siduck76 Do you plan to add debuggers to NvChad? It would be really cool!

yes but I think after v2.0! I'll add it to the 2.0's milestone in the future.

**Comment by ArshiAAkhavan** [comment]
any plans for adding support for DAP now?

**Comment by siduck** [comment]
> any plans for adding support for DAP now?

its more of a user preference. we dont configure any language specific things in nvchad. 

just add the plugin yourself https://nvchad.com/docs/config/plugins
