### ISSUE TITLE
Multiple start screen symbols not showing

### ISSUE THREAD

**Issue by LukasMarsch** [siduck76/NvChad#2120]
**Description**
Hey, when opening nvim, some of the symbols on the dashboard don't show up for me.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/50878285/093772f7-a517-4de8-a59b-650bc9033f75)

![image](https://github.com/NvChad/NvChad/assets/50878285/c039c75c-e49c-401f-998b-36bd3d6d97e3)

**System**
- Win10
- Powershell v7.3.4
- oh-my-posh v16.9.1
- JetBrainsMonoNL NFM v3.0.2
- most recent nvchad
- nvim v0.9.1

**Comment by siduck** [comment]
try another terminal

**Comment by mhadhbimouwahed** [comment]
This doesn't work on Arch using Alacritty as a terminal
![Screenshot from 2023-06-15 21-42-04](https://github.com/NvChad/NvChad/assets/78224809/04ab79f4-0c3b-4deb-a3a6-c609242e675c)

**Comment by mhadhbimouwahed** [comment]
![Screenshot from 2023-06-15 21-45-08](https://github.com/NvChad/NvChad/assets/78224809/5d917577-9a4e-4991-b916-d4a970d961f8)

**Comment by siduck** [comment]
@LukasMarsch 
 
 alacritty with no config
 
 
![image](https://github.com/NvChad/NvChad/assets/59060246/8455bddf-7a82-492d-b62e-79e1016c8610)


please set proper fonts in your config

**Comment by LukasMarsch** [comment]
Yep works in alacritty, guess i'll have to use that

**Comment by siduck** [comment]
> Yep works in alacritty, guess i'll have to use that

or else you can just change that icon!
