### ISSUE TITLE
Error while calling lua chunk: nvim/lua/core/bootstrap.lua:18: module 'base46' not found

### ISSUE THREAD

**Issue by rashil2000** [siduck76/NvChad#2121]
**Describe the bug**
I'm unable to freshly install NvChad. 

**To Reproduce**
1. Delete AppData/Local/nvim and AppData/Local/nvim-data
2. Clone NvChad repo into AppData/Local/nvim
3. Start neovim with command 'nvim'
4. See this error: 
![image](https://github.com/NvChad/NvChad/assets/46838874/5860bd41-33bc-4822-89a4-d3a71cde8ed7)

**Expected behavior**
Installation should succeed. 

**Desktop (please complete the following information):**
 - Operating System: Windows 11 Build 25375
 - Terminal: Windows Terminal v1.18
 - Version of Neovim: 0.9.1

**Additional context**
I have installed GCC v12.2.0 and it's available on my PATH.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/cc7825b8-6ddb-42fd-8958-0bcc35a1b385

Unable to reproduce, please delete it properly

**Comment by rashil2000** [comment]
Hi, thanks for the quick reply - I found that there was an issue with https clones. I updated Git and it works fine now.

**Comment by rashil2000** [comment]
Hey, just a quick unrelated question: how do I toggle between the 2 themes in my chadrc? Can't seem to find a mapping in the code or in the docs...
