### ISSUE TITLE
KeyBinding

### ISSUE THREAD

**Issue by MostafaMohamed2002** [siduck76/NvChad#2125]
**To Reproduce**
this happens when i press space  

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/41519636/4f0f525b-3a56-4f54-a292-82b6145bff31)

**Desktop (please complete the following information):**
 - Operating System ubuntu 23.04
 - Terminal Gnome-Terminal
 - Version of Neovim NVIM v0.9.0

**Comment by sravioli** [comment]
What's wrong?

**Comment by MostafaMohamed2002** [comment]
![image](https://github.com/NvChad/NvChad/assets/41519636/e4cb06e6-203e-423d-9500-08ac71485432)
it should be looking like this

**Comment by sravioli** [comment]
Could you please expand your issue? Why should it look like that?

**Comment by siduck** [comment]
> ![image](https://user-images.githubusercontent.com/41519636/246365099-e4cb06e6-203e-423d-9500-08ac71485432.png) it should be looking like this

we didnt add group names in whichkey config, you are free to do it yourself.   Also 

if we have no keybind for <leader>f then it will show empty on whichkey, so add those stuffs yourself.
