### ISSUE TITLE
Issue running after fresh install

### ISSUE THREAD

**Issue by DarkblooM-IO** [siduck76/NvChad#2126]
**Describe the bug**
Gives a LUA error message, then incorrectly opens nvim

**To Reproduce**
1. Install nvim
2. Clone repo to `~/.config/nvim`
3. Run nvim

**Expected behavior**
Should prompt to install example custom config

**Screenshots**
![screenshot](https://i.imgur.com/Jd7JeaT.png)

**Desktop (please complete the following information):**
 - Pop!_OS 22.04 LTS x86_64
 - GNOME Terminal
 - 0.6.1

**Additional context**
/

**Comment by hardal7** [comment]
see #1496

You need to use the latest version of neovim.

**Comment by siduck** [comment]
> see #1496
> 
> You need to use neovim v0.7.2

v0.9 in general , nvchad needs the latest stable release.

**Comment by geckord** [comment]
I have the same issue.
```
$ nvim -v
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by hardal7** [comment]
> I have the same issue.
> ```
> $ nvim -v
> NVIM v0.7.2
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by team+vim@tracker.debian.org
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

Please read the answer posted by siduck, you need the latest version of neovim. I've changed my answer accordingly aswell.
