### ISSUE TITLE
Squares instead of git icons

### ISSUE THREAD

**Issue by RannyArcher** [siduck76/NvChad#2129]
i **already searched** on issues, even if **all of them are closed**.

**Describe the bug**
**Git icons are not showing correctly**.

**To Reproduce**
1. Steps to reproduce the behavior:
2. open nvchad on dirty git directory.
3. open nvimTree.

**Expected behavior**
i'm expecting to get the **icons instead of those squares**.

**Screenshots**
![2023-06-17-001444_1280x800_scrot](https://github.com/NvChad/NvChad/assets/77194867/285bf97b-c409-4f02-9384-f97c3979a308)

**Desktop (please complete the following information):**
 - Operating System: **Linux (Arch)**
 - Terminal: **urxvt**
 - Version of Neovim: **v0.9.1**

**Additional context**
after some reasearch i see some nerd icons got removed after the last update. and i think that happens because of that.

**Comment by ddiazghub** [comment]
The problem may be one of these:
* Unsupported icons: Some Nerd Fonts do not support all icons. Try testing with different fonts, one of them may fix the icons.
* Outdated fonts: I had your same problem in Windows, uninstalling the fonts and downloading the latest version fixed my problem.
* Breaking changes in fonts: An update to the font may have introduced breaking changes. Try with other fonts.

**Comment by siduck** [comment]
update fonts
