### ISSUE TITLE
How to implement tabbing properly in javascript with react?

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#213]
I was working on a **react js file (.js)**  and noticed that new lines are not tabbed properly as they should be.

Here is a small example : 

* Expected formating
```jsx
import React from 'react';

const test = () => {
  return(
    <>
      <div> //proper tabbing
         Hello
      <div>
    </>
  )
};

export default test;
```

* Actual behaviour

```jsx
import React from 'react';

const test = () => {
  return(
    <>
    <div> //Improper tabbing
Hello
    <div> 
    </>
  )
};

export default test;
```
>Additional notes : 

```js
case X:
  return xy.map((z) => (z._id === action.payload._id ? action.payload : z));
```
This issue does not occur in other cases of `js` or `jsx` where i use use **normal logic** , like in the above example the tabbing is completly fine. Nor does this issue occour with other filetypes ( tested with `cpp`, `html`,`css` , `py`, `lua`). 
This issue so far only happens when i am using components in react with `js` and `jsx` files.

The tabbing is not fixed even after using neoformatter `space + fm`.
I think this might be an issue with the formatter but i am not sure. 

Any help would be greatly appreciated in this matter.

**Comment by mTvare6** [comment]
Works for me with neoformat

**Comment by siduck76** [comment]
> what did you do ?
> any changes in configuration?

install prettier or any of these ( neoformat readme )

![image](https://user-images.githubusercontent.com/59060246/128162635-838970cb-ab4f-472a-87e9-718ec485b8bd.png)

I use deno fmt , works well :)

**Comment by mTvare6** [comment]
> what did you do ?
> any changes in configuration?

I use prettier

**Comment by CTZxVULKAN** [comment]
@mTvare6 i installed `prettier` &  `eslint-config-prettier`.
```
 yarn global add prettier
 yarn global add eslint-config-prettier
```
Tabbing is still not properly working yet what else do i need to do to configure it to work normally ?

**Comment by siduck76** [comment]
weird ,  can you try deno fmt?

**Comment by CTZxVULKAN** [comment]
Now i know what was the issue.
Installing with yarn did not work for some reason however globally installing with npm works fine.
```
sudo npm i -g prettier
```
