### ISSUE TITLE
Feature request - Please add a gruvbox theme

### ISSUE THREAD

**Issue by ignacek1** [siduck76/NvChad#2133]
I think I don't have to say anything else

**Comment by siduck** [comment]
@ignxcy press leader th and select gruvbox

**Comment by ignacek1** [comment]
@siduck Whats the leader an th key by default?

**Comment by siduck** [comment]
> @siduck Whats the leader an th key by default?

space, also read docs at nvchad.com

**Comment by ignacek1** [comment]
> > @siduck Whats the leader an th key by default?
> 
> space, also read docs at nvchad.com

okay, thank you
