### ISSUE TITLE
Default mapping for floating LSP diagnostics is not working

### ISSUE THREAD

**Issue by insomnes** [siduck76/NvChad#2136]
**Describe the bug**
When you are trying to call floating diagnostics from LSP with `"<leader>f"` it would not work, cause `f` acts as prefix.
Re-maping to something like `"<leader>fd"` helps

**To Reproduce**
1. Go to the file with LSP diagnostics messages
2. Go to the line with the message
3.  Try to get floating diagnostics via default mapping `"<leader>f"`
4. See no message

**Expected behavior**
Floating diagnostic shown

**Screenshots**
***Defaults***
![image](https://github.com/NvChad/NvChad/assets/16958893/fc6e8bf0-e910-4030-8236-71f36e192b7f)
![image](https://github.com/NvChad/NvChad/assets/16958893/9bd7e527-fa15-481b-87de-1e923838d7d0)
***Re-map***
![image](https://github.com/NvChad/NvChad/assets/16958893/70c0eb0e-d976-4eec-abd4-ac1f108af637)

![image](https://github.com/NvChad/NvChad/assets/16958893/37ead4cb-ff34-48e3-8a31-f35fb9922690)
![image](https://github.com/NvChad/NvChad/assets/16958893/e0458d8b-d68a-4069-8b17-77f330acb916)

**Desktop (please complete the following information):**
 - Linux
 - kitty
 - 0.9.1

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/6331c2eb-d2ef-441c-8dd7-a8082811b274


unable to reproduce, i dont see any reason for leader f to work unless you're using a plugin that uses it

**Comment by insomnes** [comment]
Strange. Thank you!
Will check on the clear installation

**Comment by siduck** [comment]
> Strange. Thank you! Will check on the clear installation

you should press leader f , fast :D

**Comment by insomnes** [comment]
WOAH! Mind blown! 
It works.! I am sorry I've bothered you about this. 
Thank you for your time!
