### ISSUE TITLE
Adding VSCode snippets using the vim.g.vscode_snippets_path variable not working

### ISSUE THREAD

**Issue by p32929** [siduck76/NvChad#2143]
**Describe the bug**
Adding VSCode snippets using the `vim.g.vscode_snippets_path` variable not working. Snippets not showing in the suggestion while typing.

**To Reproduce**
1. Add VSCode snippet location in the variable in the custom/init.lua file. I have done it like this:
```
local spath = "C:\\Users\\P32929\\AppData\\Roaming\\Code\\User\\snippets"
vim.g.vscode_snippets_path = spath
```
2. Start Neovim
3. Goto input mode and type the snippet
4. The snippet doesn't show in the suggestion

**Expected behavior**
While typing snippet word or a few characters of the snippet word, it should show in the suggestion list & the user should be able to use the VS code snippets

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal: Neovide and Neovim-QT
 - Version of Neovim: 0,9.0

**Additional context**
Hi, First of all, really thanks for maintaining NVChad. Its been great for a beginner like me. 
So, I've been trying to follow this tutorial: https://nvchad.com/docs/config/snippets
I already had some VSCode snippets so I used the VSCode snippet path address in the custom/init.lua like this:
```
local spath = "C:\\Users\\P32929\\AppData\\Roaming\\Code\\User\\snippets"
vim.g.vscode_snippets_path = spath
```
And one of my VSCode snippet named typescriptreact.json which looks like this:
```
{
  "React Tailwind Usm TypeScript": {
    "prefix": "rsctut",
    "body": [
      "import React from 'react'",
      "import { useSelector } from 'react-redux';",
      "",
      "interface Props {",
      "",
      "}",
      "",
      "const $TM_FILENAME_BASE: React.FC<Props> = (props) => {",
      "	const states = useSelector(() => controller.states);",
      "",
      "    return (",
      "		<div>",
      "			$TM_FILENAME_BASE",
      "		</div>",
      "	)",
      "",
      "}",
      "",
      "export default $TM_FILENAME_BASE;"
    ],
    "description": "React Tailwind Usm TypeScript"
  }
}
```

But when I am trying to use the snippet inside a *.tsc file, it doesn't show. Here's a screenshot:
![Screenshot (258)](https://github.com/NvChad/NvChad/assets/6418354/c63092bc-2c05-429d-96ec-8b8758960907)

I'm not sure if it is a bug or I'm the one who's doing something wrong. Any help would be really appreciated. Thanks a lot.

**Comment by siduck** [comment]
only the snippets json file wont work, please add a package.json too :/

read luasnip docs https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vs-code
