### ISSUE TITLE
I can't use other plugins with NvChad.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2149]
Assalamu Alaikum  Recently, I am having some problems with neovim in general. Because I used Helix before as the first modal text editor. So, the problem is that I installed a minimap plugin in Lazy and it does not work. it is set to "Not Loaded". How do load it?

![10-13-16](https://github.com/NvChad/NvChad/assets/101094719/cd9fe1c5-6ff4-4121-9672-8654b96f1f4c)
![10-17-12](https://github.com/NvChad/NvChad/assets/101094719/4d60f5ca-a4a9-4bba-a43b-c68f4ef5e576)

**Comment by siduck** [comment]
waleykumusalam wa remutAllahi wa barkhatu,

  lazy=false , or please lazyload it on its cmds , like
  
  cmd = {"Minimap" , "MinimapToggle" }
