### ISSUE TITLE
[Feature] Add tokyo night theme

### ISSUE THREAD

**Issue by ayushjaipuriyar** [siduck76/NvChad#215]
Can we get tokyo night theme : )

From this one [Tokyo night](https://github.com/folke/tokyonight.nvim)

**Comment by Vanderscycle** [comment]
I love folke's theme. can you submit a pr using the [wiki info](https://github.com/siduck76/NvChad/wiki#submitting-your-own-themes).

**Comment by siduck76** [comment]
> I love folke's theme. can you submit a pr using the [wiki info](https://github.com/siduck76/NvChad/wiki#submitting-your-own-themes).

I've heard the wiki related to creating nvchad themes was confusing af xD , so I'll make this one myself too! Gotta make perfect themes ;)

**Comment by ayushjaipuriyar** [comment]
I tried making it myself , but I got confused as there are 5-6 blues in there and couldn't decide which colours to replace

**Comment by siduck76** [comment]
> I tried making it myself , but I got confused as there are 5-6 blues in there and couldn't decide which colours to replace

I'll try making it today

**Comment by siduck76** [comment]
@ayushjaipuriyar its done.
