### ISSUE TITLE
Themes not working in mac os ventura zsh shell

### ISSUE THREAD

**Issue by spino17** [siduck76/NvChad#2151]
**Describe the bug**
I have installed nvchad config for my neovim in my mac os M2 ventura with zsh shell. The theme looks so weird nothing like what given in the screenshots of official website.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/43537018/cdcda55e-56dd-4a28-a709-4c12f2148e45)
![image](https://github.com/NvChad/NvChad/assets/43537018/34d61cbd-9a8c-4085-be9b-c15fa8fa2e96)

**Desktop (please complete the following information):**
 - Mac os M2 ventura
 - zsh shell
 - 0.9.1

**Additional context**

**Comment by siduck** [comment]
please enable true color support in your terminal or change it, use alacritty/wezterm etc

**Comment by spino17** [comment]
Thanks @siduck for the answer. Which one would you suggest alacritty or wezterm ?

**Comment by siduck** [comment]
> Thanks @siduck for the answer. Which one would you suggest alacritty or wezterm ?

alacritty
