### ISSUE TITLE
[linux-aarch64] clangd: The current platform is unsupported.

### ISSUE THREAD

**Issue by hsun-code** [siduck76/NvChad#2159]
**Describe the bug**
I use the **custom** config from https://github.com/NvChad/example_config, and run `MasonInstallAll`. It seems that `clangd` is not supported on my platform.
Note that I'm working on Linux + AArch64 platform.

**To Reproduce**

```sh
# download nvchad
cd ~
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

# download the custom config example
git clone --depth 1 https://github.com/NvChad/example_config custom

# move it to ~/.config/nvim/lua/ dir
mv custom ~/.config/nvim/lua/

# start nvim
nvim

# try to install clangd lsp server
:MasonInstallAll
```

**Expected behavior**
I expected that `clangd` should be installed successfully.

**Screenshots**
Here shows the screenshot
![Screenshot 2023-06-27 at 13 37 52](https://github.com/NvChad/NvChad/assets/88446025/a832f868-c1ee-4986-80b4-600c14420333)

**Desktop (please complete the following information):**
 - Operating System: 
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```
 - Terminal
 - Version of Neovim:
```
$ nvim --version
NVIM v0.9.2-dev-db33f17
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Additional context**
From https://github.com/clangd/clangd/issues/514, I guess `clangd` is not supported on Linux+AArch64 for now.

It seems that it should not be a BUG for NvChad, but the problem of `clangd`.

If so, does anyone know if there is a substitution of `clangd` I can use on Linux+AArch64?
Or if it is possible for me to install `clangd` manually instead of using `mason`?

Thanks a lot.

**Comment by siduck** [comment]
not a nvchad issue!

yes install clangd manually, also try asking on  mason repo's discussion section, they probably have better solution

**Comment by hsun-code** [comment]
> not a nvchad issue!
> 
> yes install clangd manually, also try asking on mason repo's discussion section, they probably have better solution

Thanks for your reply. I will take a try.

**Comment by juliangaal** [comment]
I can reproduce the issue, *even though clangd is installed*,  @siduck 

Following your docker instructions:

```bash
docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git nodejs neovim ripgrep build-base wget --update
  git clone https://github.com/NvChad/NvChad ~/.config/nvim
  nvim
  '
```

then manually installing clangd

```bash
apk add clang clang-dev
```

and installing with `MasonInstall clangd` results in the same behavior.

Clangd itself works fine, when starting on the command line.

**Comment by siduck** [comment]
@juliangaal that isnt nvchad issue :/ , thats mason.nvim stuff
