### ISSUE TITLE
Not sure how to fix this ....

### ISSUE THREAD

**Issue by udaysinh-git** [siduck76/NvChad#2161]
> Well this is more of a issue im getting would like to get a answer about how to fix this 

**TraceBack**
Error detected while processing /home/udaysinh/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/udaysinh/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        /home/udaysinh/.config/nvim/lua/core/init.lua:77: in main chunk
        [C]: in function 'require'
        /home/udaysinh/.config/nvim/init.lua:1: in main chunk

> Any way to fix this ? Im a new person to neovim...

> My Os : Ubuntu - Kde - X11

**Comment by siduck** [comment]
pls use neovim 0.9
