### ISSUE TITLE
Please Help! Where do I find each individual NvChad theme?

### ISSUE THREAD

**Issue by ghost** [siduck76/NvChad#2165]
I would just like to know if there is  any way I can install the Radium theme on my own Nvim without installing the whole NvChad suit? I've been unsuccessful in finding the repo where the themes are being maintained, only pictures on reddit and the NvChad wiki.

I'm a little lost :sweat_smile:

**Comment by siduck** [comment]
@leier69 you cant! but  u can get the colors, check base46 repo's themes dir
