### ISSUE TITLE
Conflicting formatting functionality for LSP and null_ls

### ISSUE THREAD

**Issue by m-m-moradi** [siduck76/NvChad#2167]
Hey there!

I came across an issue while working with NvChad and editing a JSON file. It seems that the `<leader>fm` mapping isn't working as expected, even after I installed the `fixjson` formatter using Mason. So, I decided to dive into the related GitHub issues, and now I'm confused and in need of some help!

Turns out, there are several complaints from users about `<leader>fm` not working, and the response was that it's actually an LSP mapping that only functions when you have an actual LSP server attached. Like these ones:

- [Issue #2026](https://github.com/NvChad/NvChad/issues/2026)
- [Issue #1946](https://github.com/NvChad/NvChad/issues/1946)

People have also been complaining about LSP servers not formatting their code properly. Recently, there was even a closed pull request ([Pull Request #2158](https://github.com/NvChad/NvChad/pull/2158)) that aimed to address this exact problem. The suggested workaround in the following issues was to enable formatting for LSP in the `on_attach` function, which is disabled by default:

- [Issue #1646](https://github.com/NvChad/NvChad/issues/1646)
- [Issue #1541](https://github.com/NvChad/NvChad/issues/1541)
- [Issue #1933](https://github.com/NvChad/NvChad/issues/1933)

Based on what I understand, here's my take on it:

1. Formatting is available both in certain LSP servers and through formatters managed by `null_ls` (this applies to diagnostics and other features too).
2. It seems the default formatting by LSP servers was disabled because, as mentioned in [Issue #1541](https://github.com/NvChad/NvChad/issues/1541#issuecomment-1240040699), people tend to use `null_ls` formatters more, so they should take priority.
3. The formatting keymaps are linked to LSP mappings, and they only get loaded when an actual LSP server is attached.

So, this is the situation: People who want to use their LSP server for formatting can't do it by default. And those who want to use `null_ls` formatters (like me, since I only need to format a JSON file and don't require a full LSP server) are out of luck because the mappings are missing. So, only those who have both can happily format their files. In some cases, like the one mentioned in [Issue #1946](https://github.com/NvChad/NvChad/issues/1946), people are even installing an LSP server just to load the mapping so they can use `null_ls` formatters (in other words `null_ls` provides the functionality, but the mappings are designed for LSP servers)!

If my understanding is correct and I haven't missed anything, I must say this whole situation is pretty weird. In my opinion, the proper mapping should be loaded whenever someone wants to work with `null_ls` only or LSP servers only. Currently, if people don't want to change any configurations, they have to install both components (and this applies not just to formatters, but also to diagnostics and other cool stuff).

**Comment by siduck** [comment]
@m-m-moradi just edit your on_attach function and enable formatting in it

the mappings only work when you have an actual lsp server attached to the buffer, null-ls isnt an actual lsp server :/

**Comment by m-m-moradi** [comment]
@siduck I understand that it may not be considered an 'actual' LSP server, but in this context, it doesn't really matter whether it is or not. `null_ls` provides formatters that work with `:lua vim.lsp.buf.format()`, and when people install a formatter, they naturally expect the formatting keybinding to work as well. As you mentioned [here](https://github.com/NvChad/NvChad/issues/1541#issuecomment-1240040699), people tend to use `null_ls` formatters more frequently. So, it seems puzzling why people need to install an LSP server just to load the mapping that triggers the `null_ls` formatter.

Am I mistaken here? The `on_attach` function is specifically designed for LSP servers, the 'actual' ones as you mentioned. However, in my particular scenario, I don't have an LSP server dedicated to handling JSON files. So, am I correct in understanding that I would need to install an LSP server for JSON files (which supports formatting), modify the on_attach function accordingly, and disregard any formatters provided by `null_ls`?

**Comment by siduck** [comment]
alright i will exclude only leader fm from lsp mappings

**Comment by antoineco** [comment]
There is one thing that recently put me off, so I'm going to share it here for others to find.

`lua_ls` — the only language server that's [enabled by default](https://github.com/NvChad/NvChad/blob/10b668d98aba6bce9b494d028174207e59e5c59a/lua/plugins/configs/lspconfig.lua#L44-L46) — is also using the default `on_attach` callback function with `documentFormattingProvider` disabled. Yet, formatting works inside Lua files **with the [example configuration](https://github.com/NvChad/example_config)**.

This is because the example configuration [enables null-ls](https://github.com/NvChad/example_config/blob/f0786f5ea1ea4f7160e4c989f18b3d3ee081b13a/plugins.lua#L11-L17), and `null-ls` registers itself outside of NvChad, with its own [default `on_attach` callback](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/aac27a1fa550de3d0b2c651168167cc0d5366a9a/doc/CONFIG.md#on_attach-function-optional), therefore it doesn't use NvChad's `on_attach`.
