### ISSUE TITLE
Telescope warning on fresh install when finding hidden files

### ISSUE THREAD

**Issue by b4rlw** [siduck76/NvChad#2168]
**Describe the bug**
When I install NvChad from scratch, launch `nvim` from a directory,  and use `<leader>+fa` to find the hidden files within said directory, I get the following warning:

```
[telescope] [WARN HH:MM:SS] /Users/user/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:318: The `no_ignore` key is not available for the `find` command in `find_files`.
```

I think this can be fixed by simply overriding the mapping for "Find all" and removing the `no_ignore` key:

```lua
M.telescope = {
  plugin = true,

  n = {
    -- find
    ["<leader>fa"] = { "<cmd> Telescope find_files follow=true hidden=true <CR>", "Find all" },
  },
}
```

**To Reproduce**
1. Install NvChad from scratch.
2. `<leader>+fa`

**Expected behavior**
No warning presented by Telescope.

**Desktop (please complete the following information):**
 - Operating System
macOS
 - Terminal
Kitty
 - Version of Neovim
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by siduck** [comment]
make sure fd is installed

**Comment by b4rlw** [comment]
Thanks, must have missed that!

**Comment by ogios** [comment]
> make sure fd is installed

@siduck what `fd` means? sorry i'm a newbie to this, and i encoutered the same issue

**Comment by siduck** [comment]
@ogios its an alternative to find program, written in rust
