### ISSUE TITLE
Lualine breaks telescope

### ISSUE THREAD

**Issue by ayushjaipuriyar** [siduck76/NvChad#217]
**Describe the bug**
Using telescope instead of galaxyline breaks telescope, also chad themes doesnt work on lualine

**To Reproduce**
1. Follow the steps on wiki [lualine](https://github.com/siduck76/NvChad/wiki/Chad-user-configs#lualine-galaxyline-alternative)
2. Run any telescope functions
3. Theme doesnt apply to lualine no matter what

**Expected behavior**
Telescope find popup should come up but 

**Screenshots**
![2021-08-06_22-41-43_1920x1080](https://user-images.githubusercontent.com/66643292/128547609-b131ee4d-2c6b-4510-8f64-5c1d8d8fd0fa.png)

**Desktop (please complete the following information):**
 - Manjaro
 - Alacrittyl
 - neovim 0.5

**Comment by siduck76** [comment]
we havent added highlights for lualine yet and lualine isnt causing the telescope issue. I have had the telescope issue and its too random , PackerSync or reinstallation fix it but idk whats causing it.

**Comment by ayushjaipuriyar** [comment]
Okay, but its not fixing on mine

**Comment by siduck76** [comment]
> Okay, but its not fixing on mine

delete .config/nvim folder and try again

**Comment by ayushjaipuriyar** [comment]
> > Okay, but its not fixing on mine
> 
> delete .config/nvim folder and try again

Did that still the same , works just fine on galaxyline
i guess i will continue using galaxyline

**Comment by siduck76** [comment]
> > > Okay, but its not fixing on mine
> > 
> > 
> > delete .config/nvim folder and try again
> 
> Did that still the same , works just fine on galaxyline
> i guess i will continue using galaxyline

yes , you can customize it to look like lualine too

**Comment by ayushjaipuriyar** [comment]
> > > > Okay, but its not fixing on mine
> > > 
> > > 
> > > delete .config/nvim folder and try again
> > 
> > 
> > Did that still the same , works just fine on galaxyline
> > i guess i will continue using galaxyline
> 
> yes , you can customize it to look like lualine too

Okaay , i will close this then , thanks though

**Comment by JustSage** [comment]
> we havent added highlights for lualine yet and lualine isnt causing the telescope issue. I have had the telescope issue and its too random , PackerSync or reinstallation fix it but idk whats causing it.

Don't need specific highlights for lualine, you could either use vim.g.nvchad_theme to set the theme property or use the colors from theme.lua and define colors for each component.
You could even set the theme property to 'auto' which automatically detects your theme but that's a bit off in my experience.

Regards to Telescope errors, it's usually a typo in your configurations - above Telescope setup call.
`rm -r -f nvim/plugin` -> `:PackerSync` -> `:PackerCompile` -> get out of buffer -> get to a new buffer and test Telescope.
It's a Telescope thing -.-
