### ISSUE TITLE
<leader> + fm takes 2 seconds

### ISSUE THREAD

**Issue by basava70** [siduck76/NvChad#2171]
First of all thanks for the awesome NvChad.
As the title says, the inbuilt <leader> + fm command takes atleast 2 seconds to format and 
the format on save code for null-ls makes the editor stuck for a second or two. 
Is this natural or am I missing something ?

**Comment by siduck** [comment]
@basava70 depends on the formatter, nothing to do with nvchad

**Comment by basava70** [comment]
Its a .tex file and I have used the same file in lunarvim and a personal configuration of mine. It does almost instantly ( format on save). In NvChad, I am only trying <leader> + fm, it takes 2 seconds. I am not sure if its entirely just the formatter.
Formatter I used is chktex.

**Comment by siduck** [comment]
@basava70 did it happen before?

**Comment by georgejean** [comment]
I think chktex is just a semantic linter. The formatter you use is perhaps latexindent which is known to be slow, but it doesn't explain the difference with your lunarvim config.

**Comment by basava70** [comment]
It was actually something to do with ubuntu, I tried formatting with lunarvim and it is still taking that 2 seconds time. I reverted to a previous version of ubuntu and its same in both nvim configs (NvChad and LunarVim).
I am closing this a solved.
