### ISSUE TITLE
Formatting doesn't work on new empty install of nvchad

### ISSUE THREAD

**Issue by itamarsch** [siduck76/NvChad#2174]
**Describe the bug**
Formatting doesn't work on installed language server

**To Reproduce**
1. Install fresh nvchad
2. `rm -rf ~/.local/share/nvim`
3. Open lua file and press `<leader>fm`
4. Foramtting doesn't work

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/71348842/ebf4737e-8f48-4b53-b099-7e08c62ce8ed)

**Desktop:**
 - Fedora 38
 - gnome-terminal
 - latest neovim version 0.9.1

**Comment by georgejean** [comment]
Formatting capabilities are disabled by default for LSP clients (question to @siduck : is it still necessary?) and `lua_ls` client is already setup (see `lua/plugins/configs/lspconfig.lua`).
If you setup it twice, the second call to `setup {}` will overwrite the first.
For now, you can use a null-ls built-in like stylua instead.

**Comment by siduck** [comment]
@georgejean by default we disable lsp's inbuilt formatting as we use formatters defined by null-ls, so just edit the on_attach function

**Comment by georgejean** [comment]
@siduck
Thanks.
I think it could be interesting to replace the following code chunk in lua/plugins/configs/lspconfig.lua:

```lua
require("lspconfig").lua_ls.setup {
  on_attach = M.on_attach,
  capabilities = M.capabilities,

  settings = {
    Lua = {
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        library = {
          [vim.fn.expand "$VIMRUNTIME/lua"] = true,
          [vim.fn.expand "$VIMRUNTIME/lua/vim/lsp"] = true,
          [vim.fn.stdpath "data" .. "/lazy/extensions/nvchad_types"] = true,
          [vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy"] = true,
        },
        maxPreload = 100000,
        preloadFileSize = 10000,
      },
    },
  },
}
```

by (storing lua_ls server setup in M):

```lua
M.servers = {
  lua_ls = {
    settings = {
      Lua = {
        diagnostics = {
          globals = { "vim" },
        },
        workspace = {
          library = {
            [vim.fn.expand "$VIMRUNTIME/lua"] = true,
            [vim.fn.expand "$VIMRUNTIME/lua/vim/lsp"] = true,
            [vim.fn.stdpath "data" .. "/lazy/extensions/nvchad_types"] = true,
            [vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy"] = true,
          },
          maxPreload = 100000,
          preloadFileSize = 10000,
        },
      },
    },
  },
}

require("lspconfig").lua_ls.setup {
	on_attach = M.on_attach,
	capabilities = M.capabilities,

	settings = M.servers.lua_ls.settings,
}
```

thus we could possibly use the table M in custom lspconfig and modify setup for lua_ls without rewriting everything. For example:
```lua
-- lua/custom/plugins.lua
{
    "neovim/nvim-lspconfig",
    config = function()
      local lsp = require "plugins.configs.lspconfig"
      local on_attach_bis = function(client, bufnr)
        lsp.on_attach(client, bufnr)
        client.server_capabilities.documentFormattingProvider = true
      end
      require("lspconfig").lua_ls.setup {
      on_attach = on_attach_bis,
      capabilities = lsp.capabilities,
      settings = lsp.servers.lua_ls.settings}
    end,
  },
``` 
Moreover, it wouldn't affect the actual way to config custom's lsp clients.
What do you think about that?
