### ISSUE TITLE
Try do sisable only Friendly-snippets

### ISSUE THREAD

**Issue by javierjcf** [siduck76/NvChad#2176]
I read a lot about to disable this unwanted pluggin: friendly-snippets. I see is dependency of nvim-cmp (why?).

I try to disable only this part, in my custom/plugins.lua i add:
```lua
  {
     --"hrsh7th/nvim-cmp",
     "rafamadriz/friendly-snippets",
     enabled = false
  }
```
If i do this, it disable all autocompletion.
```lua
  {
     "hrsh7th/nvim-cmp",
     enabled = false
  }
```

I also try to edit init.lua, and look dor nvim-cmp and try to comment the dependency of friendly-snippets. It seems work but when i pres tab, i got and error and breaks.

Is possible to disable it?, or configure to not show any snippet?

**Comment by siduck** [comment]
{
     --"hrsh7th/nvim-cmp",
     "rafamadriz/friendly-snippets",
     enabled = false
  }
  
  works here

**Comment by siduck** [comment]
ok just dont include the luasnip sources, so override cmp config

```lua
sources = {
    { name = "nvim_lsp" },
    { name = "path" },
  --  { name = "luasnip" },
    { name = "buffer" },
    { name = "nvim_lua" },
  },
  ```

**Comment by javierjcf** [comment]
It works. Thanks @siduck
