### ISSUE TITLE
nvim-treesitter.lua error on last nvim version

### ISSUE THREAD

**Issue by ynhhoJ** [siduck76/NvChad#2179]
**Describe the bug**
After updating to the latest version of NVim (`NVIM v0.10.0-dev+624-ge8b3ed74b`), on open any file i get error:

```
Failed to source `/home/ynhhoj/.local/share/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua`

vim/_editor.lua:0: BufReadPost Autocommands for "*"..script nvim_exec2() called at BufReadPost Autocommands for "*":0../home/ynhhoj/.local/share/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua: Vim(source):E5113: Error while calling lua chunk: /usr/share/nvim/runtime/lua/vim/tre
esitter/query.lua:609: Overriding trim!
stack traceback:
^I[C]: in function 'error'
^I/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:609: in function 'add_directive'
^I...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:252: in main chunk
^I[C]: in function 'require'
^I.../share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter.lua:8: in main chunk
^I[C]: in function 'require'
^I...are/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua:9: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:473: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:472>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:472: in function 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:431: in function 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:399: in function 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:335: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:184: in function 'load'
^I...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:54: in function 'load'
^I/home/ynhhoj/.config/nvim/lua/core/utils.lua:111: in function </home/ynhhoj/.config/nvim/lua/core/utils.lua:93>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/core/utils.lua:111
```

**To Reproduce**
1. Install last version of nvim
2. Install nvchad
3. Open any file 

P.S: Without `.config`, `Nevoim` does not show any error. I tried to remove the `custom` folder from `nvim` config, but it does not resolve the problem.
Also i tried to remove all files in `~/.local/share/nvim` and reinstall all dependencies again and problem still remain...

**Expected behavior**
Error should not appar

**Screenshots**

**Desktop (please complete the following information):**
 - Fedora 38
 - Kitty
 - `NVIM v0.10.0-dev+624-ge8b3ed74b`
 
**Additional context**
This error start appear after ` 0.10.0~dev.616.g203181234-500 ` update and i really don't know this is a `NvChad` or a `Neovim` problem :(
On `606` dev version everything is working good.

- 616: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6133667/ 
- 606: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6131945/ 

Versions list: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/package/neovim/

Thank you!

**Comment by siduck** [comment]
do you get the error on v0.9? nvchad suggest to use only the LTS which is 0.9

**Comment by ynhhoJ** [comment]
> do you get the error on v0.9? nvchad suggest to use only the LTS which is 0.9

No, i do not.
Error appear only on `0.10.0~dev.616.g203181234-500` and after versions.

Should I close this issues and create new one in `Treesitter` / `Nevoim` repository?

**Comment by siduck** [comment]
> > do you get the error on v0.9? nvchad suggest to use only the LTS which is 0.9
> 
> No, i do not. Error appear only on `0.10.0~dev.616.g203181234-500` and after versions.
> 
> Should I close this issues and create new one in `Treesitter` / `Nevoim` repository?

yes
