### ISSUE TITLE
no featureful branch

### ISSUE THREAD

**Issue by shelper** [siduck76/NvChad#2181]
on the nvchad.com site at https://nvchad.com/news/v2.0#example_config it says: 

> Example_config
> To have a custom config quickstart, you can check the [example_config](https://github.com/NvChad/example_config/). If you want something featureful, check its v2.0_featureful branch.

but there is no such `v2.0_featureful` branch ....

**Comment by georgejean** [comment]
[https://github.com/NvChad/example_config/tree/v2.0_featureful](https://github.com/NvChad/example_config/tree/v2.0_featureful)

![image](https://github.com/NvChad/NvChad/assets/11246966/1c6cb988-e387-4c99-b340-8c50f75728bb)
