### ISSUE TITLE
Git version too old to clone lazy.nvim, causing silent breaking error

### ISSUE THREAD

**Issue by jrwrigh** [siduck76/NvChad#2182]
**Describe the bug**
On a brand new install of nvchad, neovim will report that it can't fine the `lazy` module. In this particular case, it's because the version of git is too old (circa 1.8) to run the [`--filter=blob:none` option](https://github.com/NvChad/NvChad/blob/83aac1ecc0c84726d3aace3ed97d7001add4694b/lua/core/bootstrap.lua#L23C35-L23C55), causing `git` to error out and not clone the lazy.nvim repo. This error is not caught and so neovim steams full speed into `require "plugins"` where it then complains that `lazy` can't be found.

**To Reproduce**
1. Have machine with very old version of git (common on HPC machines using RHEL)
2. Install nvchad
3. `nvim`

**Expected behavior**
At the absolute bare-minimum, verify that the repository was cloned. Better yet, catch the error message from `git` and report it to the user.

Might also be worth considering whether `--filter=blob:none` is necessary, but that's much more a secondary point.

**Desktop (please complete the following information):**
 - RHEL
 - N/A
 - v0.9.1
 
 Bug originally found by @kamo6346

**Comment by jrwrigh** [comment]
Looks like `system` leaves the error code in `v:shell_error`, so that could be checked to at least verify that `git` exited cleanly. Otherwise it looks like `system()` should return the "output" as a string according to the docs, but it doesn't specify whether it's stdout, stderr, or both.

**Comment by siduck** [comment]
just install new git version then

**Comment by jrwrigh** [comment]
I think you missed the point of the issue. It wasn't "NVChad doesn't support old git versions"; it's quite reasonable to require a non-ancient version of `git` and compiling a newer git version is exactly what we did to get NVChad correctly installed.

The point of the issue was that there was an uncaught error and no checks to verify that external commands completely correctly. The same behavior could've happened if a proxy wasn't setup correctly inside a controlled environment. I don't think it's too much to change:
```lua
  vim.fn.system { "git", "clone", "--filter=blob:none", "--branch=stable", repo, install_path }
```
to 
```lua
  output = vim.fn.system { "git", "clone", "--filter=blob:none", "--branch=stable", repo, install_path }
  assert(vim.v.shell_error == 0, "git failed with error code: " .. vim.v.shell_error .. "\n" .. output)
  ```
  
  I'd be happy to make a PR for it if you'll take it.

**Comment by siduck** [comment]
this is a minor edgecase so i wont be adding new code for this!

**Comment by jrwrigh** [comment]
Have fun creating a worse user experience!

**Comment by siduck** [comment]
> Have fun creating a worse user experience!



> Have fun creating a worse user experience!

if folke consider's changing it in lazy's readme  then i'd go for it too!!

**Comment by jrwrigh** [comment]
Are you not understanding what I'm saying? The suggestion has nothing to do with this specific problem. It has to do with uncaught errors when making an external call. That can come from anywhere at anytime, not just the specific `git clone` command that caused this specific issue. Catching errors is software engineering 101.

**Comment by siduck** [comment]
> Are you not understanding what I'm saying? The suggestion has nothing to do with this specific problem. It has to do with uncaught errors when making an external call. That can come from anywhere at anytime, not just the specific `git clone` command that caused this specific issue. Catching errors is software engineering 101.

then you'd probably have to catch those git errors in lazy's codebase too , they probably clone plugins in a way which is probably too new for your git version

**Comment by jrwrigh** [comment]
That doesn't even make sense. Let's say you do implement the error catching. I try to install `NVChad`, then find out my `git` version is too old. So I update `git`. Now it's compatible with lazy. Tada!

Again, I am ***NOT*** suggesting that you try and change `NVChad` to be compatible with ancient versions of git.

I'm saying that `NVChad` could help prevent problems by simply checking for errors in external system calls.

**Comment by siduck** [comment]
> That doesn't even make sense. Let's say you do implement the error catching. I try to install `NVChad`, then find out my `git` version is too old. So I update `git`. Now it's compatible with lazy. Tada!
> 
> Again, I am _**NOT**_ suggesting that you try and change `NVChad` to be compatible with ancient versions of git.
> 
> I'm saying that `NVChad` could help prevent problems by simply checking for errors in external system calls.

you're right, but what does it error without the error handling? can you make a video or show a pic

**Comment by jrwrigh** [comment]
Symptoms match up with [this SO question]( https://stackoverflow.com/q/76326298/7564988), including the error message:
![image](https://github.com/NvChad/NvChad/assets/20801821/1fc0d385-5c9c-4c85-9b49-ef29c77ff12a)

**Comment by siduck** [comment]
> Symptoms match up with [this SO question](https://stackoverflow.com/q/76326298/7564988), including the error message: ![image](https://user-images.githubusercontent.com/20801821/251511639-1fc0d385-5c9c-4c85-9b49-ef29c77ff12a.png)

![image](https://github.com/NvChad/NvChad/assets/59060246/89140989-b434-4bab-9b07-852dde4e0479)

alright, make a PR
