### ISSUE TITLE
Everforest theme request

### ISSUE THREAD

**Issue by JustSage** [siduck76/NvChad#219]
[Everforest](https://github.com/sainnhe/everforest)
Please integrate this theme, it's a really chill one :)

**Comment by siduck76** [comment]
which one out of 3 in it? :sunglasses:

**Comment by siduck76** [comment]
what about this? 

https://github.com/b4skyx/serenade

**Comment by JustSage** [comment]
Looks very similar to it, would like the medium dark version of Everforest though :).
btw are the light themes limited by your base16 fork ?

**Comment by siduck76** [comment]
> Looks very similar to it, would like the medium dark version of Everforest though :).
> btw are the light themes limited by your base16 fork ?

yea for now kinda , I will make some nice light themes next month so hold on!

**Comment by JustSage** [comment]
Sweet! The dark themes look sick, can't wait :D!

**Comment by siduck76** [comment]
> Sweet! The dark themes look sick, can't wait for the light ones :D!

I'll make the light ones in the next month tho! I havent made any projects lately xD so no code to show off NvChad with light themes :'(

**Comment by tfs** [comment]
> > Sweet! The dark themes look sick, can't wait for the light ones :D!
> 
> I'll make the light ones in the next month tho! I havent made any projects lately xD so no code to show off NvChad with light themes :'(

I would love to have some light ones - maybe even Ayu? There's a Lua Port, but I'm still moving from vimscript to lua and basically don't know what I'm doing. Or how would you integrate something like this? https://github.com/Shatur/neovim-ayu
