### ISSUE TITLE
When I use nvchad to open the .vue file, this error occurs

### ISSUE THREAD

**Issue by oldqin97** [siduck76/NvChad#2191]
<img width="751" alt="image" src="https://github.com/NvChad/NvChad/assets/48620148/d286e2a0-738e-4bb6-95be-f59d38fbfa26">

When I open a .vue file, nvchad will have such an error, I have not modified anything on nvchad, just modified the key bindings and downloaded the LSP of vue using Mason.
I also downloaded all dependencies of this vue project

nvim:0.9.0
macos: Monterey,12.4
terminal: alarcitty

**Comment by siduck** [comment]
do you have tsserver downloaded via mason?

**Comment by siduck** [comment]
also doesnt look like a nvchad issue, so closing this. Just install typscript lsp via mason and  it should work
