### ISSUE TITLE
Several neovim and nvim plugins don't work in lazy mode

### ISSUE THREAD

**Issue by alexeygrant** [siduck76/NvChad#2197]
**Describe the bug**
Several popular plugins that I use only work when I use `lazy = false` in the plugins configuration. The list of plugins that don't work for me:
1. tpope/vim-fugitive
2. tpope/surround
3. ggandor/leap.nvim

**To Reproduce**
1. Add plugins to `%LOCALAPPDATA%/nvim/lua/custom/plugins.lua` folder.
2. Do not provide `lazy` property in the configuration or provide `lazy=true`
3. Attempt to use the functionality and observe that it's not working.
6. Set `lazy` property to false and observe that plugin begins working correctly.

**Expected behavior**
I expect the plugin to work correctly when it's lazy loaded - be loaded on the first use.

**Desktop (please complete the following information):**
 - Windows 11
 - PowerShell or Neovide
 - Version of Neovim: 0.9.1

**Additional context**

**Comment by siduck** [comment]
@alexeygrant all plugins in nvchad are set to lazy=true, please lazyload those plugins or just lazy=false them
