### ISSUE TITLE
Yank from Visual mode often results in yank+paste of entire buffer, not just the selected portion

### ISSUE THREAD

**Issue by plotfi** [siduck76/NvChad#2198]
Hi NVChad folks, I am very sorry if this issue is a bother due to a strange config I might be using. 

One thing to note is that I use ctrl-c as my escape even in visual mode:

```
vim.cmd([[
  noremap <C-c> <Esc>
  imap <C-c> <Esc>
]])
```

I suspect this might be interfering with something nvchad is doing, but I dont see this happening in default nvim or vim setups where I have this ctrl-c setup (which I can't unlearn from my muscle memory).

## Description
yanking in visual mode often results in a yank and subsequent paste of the content of the entire buffer not just the highlighted part from visual mode.

**To Reproduce**
1. Paste the following into a nvim nvchad buffer:

```
import Foundation

struct ContentView {
  init() {
      let url = URL(string: "https://foo.bar")!
      print(url)

      try? url.bookmarkData()
  }
}
```

2. Navigate the cursor down to line 5 (the `      let url = URL(string: "https://foo.bar")!` line).
3. Navigate to 3rd column just under the i in `init`
4. ctrl-v to enter visual mode
5. Block select some 2-4 columns, press X to cut-yank
6. paste

**Expected behavior**
Expected behavior is to paste the block, but it pastes the whole content of the buffer from `import Foundation` down

**Screenshots**
[Uploaded Screen Recording](https://github.com/NvChad/NvChad/assets/34139736/e6fe1f3e-fa58-4e66-805f-7336aa70f65e)

**Desktop (please complete the following information):**
 - Operating System: macOS Ventura
 - Terminal: iTerm2
 - Version of Neovim: NVIM v0.9.1 via Homebrew

**Comment by plotfi** [comment]
I think it may just be the case that noremap/imap don't load through `vim.cmd([[`

**Comment by siduck** [comment]
@plotfi we use C-c in our default mappings for copying whole file

**Comment by siduck** [comment]
just add this  in your custom mappings

```lua

M.general = {
  n = {
    ["<C-c>"] = {"<Esc>", "escape!!"}
  },
  i = {
    ["<C-c>"] = {"<Esc>", "escape!!"}
  },
}
```

**Comment by plotfi** [comment]
> @plotfi we use C-c in our default mappings for copying whole file

Whoa, How do I disable this? Thank's to Apple's touchbar I began using ctrl-c everywhere in place of esc. This has had lasting repercussions. :-/

**Comment by plotfi** [comment]
> just add this in your custom mappings
> 
> ```lua
> M.general = {
>   n = {
>     ["<C-c>"] = {"<Esc>", "escape!!"}
>   },
>   i = {
>     ["<C-c>"] = {"<Esc>", "escape!!"}
>   },
> }
> ```

THANKS!

**Comment by siduck** [comment]
> > @plotfi we use C-c in our default mappings for copying whole file
> 
> Whoa Holy Moly. How do I disable this? Thank's to Apple's touchbar I began using ctrl-c everywhere in place of esc. This has had lasting repercussions. :-/

https://nvchad.com/docs/config/mappings docs are  your friend :D
