### ISSUE TITLE
Move all lsp setup into a function and call it

### ISSUE THREAD

**Issue by lucario387** [siduck76/NvChad#2199]
**Is your feature request related to a problem? Please describe.**
Currently, to override LSPs, it requires not using nor calling `plugins.config.lspconfig`, as calling it will always lead to `nvchad_ui.lsp` and `lua-ls` to be called

**Describe the solution you'd like**
We can move those into a `M.setup = function() ... end` and then call it from `config = function() ... end` inside lazy.nvim plugin table

**Comment by georgejean** [comment]
Personally, I would also like to have all this lsp stuff (`lua_ls` config included) in the `opts` table (to possibly merge custom config with the defaults).
So, taking your proposal into account (if I undestand it), what would you think about that ? (note that this would break the current documented custom LSP configuration)
```lua
-- lua/plugins/configs/lspconfig.lua

-- dofile(vim.g.base46_cache .. "lsp")
-- require "nvchad_ui.lsp"

local M = {}
local utils = require "core.utils"

M.setup = function()
  dofile(vim.g.base46_cache .. "lsp")
  require "nvchad_ui.lsp"
end

-- (stuff about on_attach and capabilities ...)

-- require("lspconfig").lua_ls.setup {
--   on_attach = M.on_attach,
--   capabilities = M.capabilities,
--
--   settings = {
--     Lua = {
--       diagnostics = {
--         globals = { "vim" },
--       },
--       workspace = {
--         library = {
--           [vim.fn.expand "$VIMRUNTIME/lua"] = true,
--           [vim.fn.expand "$VIMRUNTIME/lua/vim/lsp"] = true,
--           [vim.fn.stdpath "data" .. "/lazy/extensions/nvchad_types"] = true,
--           [vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy"] = true,
--         },
--         maxPreload = 100000,
--         preloadFileSize = 10000,
--       },
--     },
--   },
-- }
M.servers = {
  lua_ls = {
    on_attach = M.on_attach,
    capabilities = M.capabilities,
    settings = {
      Lua = {
        diagnostics = {
          globals = { "vim" },
        },
        workspace = {
          library = {
            [vim.fn.expand "$VIMRUNTIME/lua"] = true,
            [vim.fn.expand "$VIMRUNTIME/lua/vim/lsp"] = true,
            [vim.fn.stdpath "data" .. "/lazy/extensions/nvchad_types"] = true,
            [vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy"] = true,
          },
          maxPreload = 100000,
          preloadFileSize = 10000,
        },
      },
    },
  },
}

return M
```
```lua
-- lua/plugins/init.lua
{
    "neovim/nvim-lspconfig",
    init = function()
      require("core.utils").lazy_load "nvim-lspconfig"
    end,
    opts = require "plugins.configs.lspconfig",
    config = function(_, opts)
      opts.setup()
      require("lspconfig").lua_ls.setup(opts.servers.lua_ls)
    end,
  },
```

**Comment by lucario387** [comment]
anything that makes `require`-ing `lspconfig.lua` to not also load `nvchad_ui`'s LSP-related functionality is okay for me

**Comment by georgejean** [comment]
I think it's interesting. If a PR is made with these ideas, documentation should be accordingly updated.

**Comment by siduck** [comment]
> I think it's interesting. If a PR is made with these ideas, documentation should be accordingly updated.

your code looks good but obscure's lspconfig's syntax!

**Comment by siduck** [comment]
> anything that makes `require`-ing `lspconfig.lua` to not also load `nvchad_ui`'s LSP-related functionality is okay for me

whats wrong with that? :thinking:

**Comment by georgejean** [comment]
> whats wrong with that? 🤔

perhaps the goal is to add one level in customization of NvChad or not to load `nvchad_ui.lsp` or `lua_ls` if already done. But I let @lucario387 answer to your question.


Regarding my proposal, I'd tought it could:
1. make customization of `lua_ls` server  easier (and not requiring it more than needed)
2. give an idea of how to setup other servers with a good experience for the user (see example below).

### Example of usage (using [these settings](https://github.com/NvChad/NvChad/issues/2199#issuecomment-1632124664))
```lua
-- /custom/plugins.lua
{
    "neovim/nvim-lspconfig",
    opts = require "custom.configs.lspconfig",
    config = function(_, opts)
      opts.setup() --enable nvchad_ui.lsp
      for server, config in pairs(opts.servers) do
          config.on_attach = opts.on_attach
          config.capabilities = opts.capabilities
          require("lspconfig")[server].setup(config)
      end
    end,
  },
```
```lua
-- /custom/configs/lspconfig
local util = require "lspconfig.util"
local M = {
  servers = {
    emmet_ls = {},
    html = {},
    cssls = {},
    tsserver = {},
    pyright = {},
    marksman = {},
    texlab = { --server with some stuff
      settings = {
        texlab = {
          chktex = {
            onEdit = true,
          },
        },
      },
    },
    ltex = { --another one
      filetypes = { "bib", "tex"},
      root_dir = function(filename)
        return util.path.dirname(filename)
      end,
      settings = {
        ltex = {
          enabled = {
            "bib",
            "tex",
            "latex"
          },
          language = "fr",
          checkFrequency = "save", 
        },
      },
    },
  },
}

return M
```
It's just an idea of a ​​possible evolution of lsp settings (which could lead to a little breaking change in lsp custom config).

**Comment by siduck** [comment]
@georgejean breaking changes are always hated by users :laughing: ,  maybe we could make default lspconfig just have the on_attach and capabilities stuff

soo a custom lspconfig could look like this

```lua
dofile(vim.g.base46_cache .. "lsp")
require "nvchad_ui.lsp"

local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = { "html", "clangd", "cssls", "jsonls", "unocss" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end

-- setup lua lsp
require("lspconfig").lua_ls.setup {
  on_attach = on_attach,
  capabilities = capabilities,

  settings = {
    Lua = {
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        library = {
          [vim.fn.expand "$VIMRUNTIME/lua"] = true,
          [vim.fn.expand "$VIMRUNTIME/lua/vim/lsp"] = true,
          [vim.fn.stdpath "data" .. "/lazy/extensions/nvchad_types"] = true,
          [vim.fn.stdpath "data" .. "/lazy/lazy.nvim/lua/lazy"] = true,
        },
        maxPreload = 100000,
        preloadFileSize = 10000,
      },
    },
  },
}
```
what do you think @lucario387

**Comment by lucario387** [comment]
better than currently, probably

**Comment by siduck** [comment]
> better than currently, probably

theoretically  it should be faster right? :thinking:

**Comment by lucario387** [comment]
probably not faster, just easier to handle (you load the same amount of code anyways)

**Comment by siduck** [comment]
> probably not faster, just easier to handle (you load the same amount of code anyways)

ik , although i/o reading of 1 file vs 2 files ( before we were loading default+custom lspconfig, now its just the custom lspconfig )

also 0.001 ms saved in lazy.nvim's process of merging lspconfig's spec table cuz we wont need the config function anymore

![image](https://github.com/NvChad/NvChad/assets/59060246/6469596a-aebd-49ea-b948-6ea8ea4d24ab)

**Comment by lucario387** [comment]
> ik , although i/o reading of 1 file vs 2 files ( before we were loading default+custom lspconfig, 

No, it's still reading 2 files (since custom is loading default as a module)

**Comment by siduck** [comment]
> > ik , although i/o reading of 1 file vs 2 files ( before we were loading default+custom lspconfig,
> 
> No, it's still reading 2 files (since custom is loading default as a module)

ohh true, custom lspconfig is still calling modules from default lspconfig

**Comment by siduck** [comment]
so whats the point of moving all the lsp setup in one function?

**Comment by lucario387** [comment]
> so whats the point of moving all the lsp setup in one function?

So that when one only wants to use the `on_attach` and `capabilities` (and not the UI related to nvchad), I wont have to manually disable/override all of those UI again

**Comment by lucario387** [comment]
and no, disabling the UI/config through chadrc doesn't suffice, one example being vim.diagnostic.config

**Comment by siduck** [comment]
> > so whats the point of moving all the lsp setup in one function?
> 
> So that when one only wants to use the `on_attach` and `capabilities` (and not the UI related to nvchad), I wont have to manually disable/override all of those UI again

no one wants that! then you'll say to do this for all plugin configs cuz they have the dofile cache line too. If the user really doesnt want those highlight groups then he can just copy paste the capabilities/on_attach to his custom config

**Comment by lucario387** [comment]
which kindof defeats the purpose of providing a default on_attach/capabilities settings for nvchad that one cannot use and must copy and paste

**Comment by lucario387** [comment]
> then you'll say to do this for all plugin configs cuz they have the dofile cache line too

I won't. I just want to have the easiest way out for setting up mason-lsp-config with nvchad. The current forces me to skip lua_ls because it's already set up, and I cannot easily manipulate the loading order of lua_ls with that
