### ISSUE TITLE
Forgetting # when typing in hex code for changed themes problems

### ISSUE THREAD

**Issue by LlunN3ll** [siduck76/NvChad#2205]
I was able to fix it by deleting my nvim-data folder and redownloading again to fix the base46 files, I think it may have something do with the one of the files in there

**Describe the bug**
Typing in a hex code without # to change a themes color in changed_themes causes an error
**To Reproduce**
1. Go to chadrc.lua in custom folder
2. Edit changed_themes and set a color to a hex code without #
3. Write file
4. Error

**Expected behavior**
Error is expected but the problem is that even after fixing the typo error persists. Trying to write after also gives mention of some plenary module being unable to reload

**Screenshots**
Typo Error:
![Invalid Highlight Color](https://github.com/NvChad/NvChad/assets/106228938/1da1e6af-79b2-40a1-8491-5e3e69c59a90)

Plenary Error:
![Plenary Module not found](https://github.com/NvChad/NvChad/assets/106228938/4498bb4c-d0ac-4407-9aa2-d558b756d1dc)
**Desktop (please complete the following information):**
 - Operating System: Windows
 - Terminal: None, using nvim-qt
 - Version of Neovim: 0.9.1

**Additional context**
None

**Comment by siduck** [comment]
please add the "#" , its necessary for a valid color that neovim supports
