### ISSUE TITLE
New Telescope live_grep_raw to search into gitignore directories

### ISSUE THREAD

**Issue by caneta** [siduck76/NvChad#2206]
**Is your feature request related to a problem? Please describe.**
I would like to add a Telescope live_grep_raw command in order to search also inside gitignore directories

**Describe the solution you'd like**
I would like to add
`["<leader>f."] = { "<cmd> Telescope live_grep_raw <CR>", "Live grep on .gitignore too" },` to ./lua/custom/mappings.lua, but I need the Telescope live_grep_raw command first: basically the same as Telescope live_grep but with the additional `-u` flag.

**Describe alternatives you've considered**
I've tried doing it myself in the custom dir [like suggested here](https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/9), without success

Thank you

**Comment by antoineco** [comment]
Inside your [`custom/plugins.lua`](https://github.com/NvChad/example_config/blob/f0786f5ea1ea4f7160e4c989f18b3d3ee081b13a/plugins.lua) add:

```lua
---@type NvPluginSpec[]
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-telescope/telescope-live-grep-args.nvim",
    },
    opts = {
      extensions = {
        live_grep_args = {
          auto_quoting = true,  -- random example from the README
        },
      },
      extensions_list = {
        "live_grep_args",
        -- NvChad defaults
        "themes",
        "terms",
      },
    },
  },
}

return plugins
```

**edited** (thanks @siduck)

Then, add this keymap inside  [`custom/mappings.lua`](https://github.com/NvChad/example_config/blob/f0786f5ea1ea4f7160e4c989f18b3d3ee081b13a/mappings.lua):

```lua
---@type MappingsTable
local M = {}

M.telescope = {
  n = {
    ["<leader>f."] = {
      function()
        require("telescope").extensions.live_grep_args.live_grep_args {
          vimgrep_arguments = {
            "rg",
            "--hidden",
            -- NvChad defaults
            "-L",
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
            "--smart-case",
          },
        }
      end,
      "Live grep, including hidden files",
    },
  },
}

return M
```

![image](https://github.com/NvChad/NvChad/assets/3299086/68979356-9f63-4435-8688-4a4b5f1b1982)

**Comment by siduck** [comment]
@antoineco looks a cleaner syntax

```lua
opts = {
  extensions = {
     live_grep_args = {  
        -- that extension's config here
     }
  },
  
  extensions_list = { "themes", "terms", "live_grep_args" }
  }
```

**Comment by caneta** [comment]
` -- that extension's config here` stands for? The whole content of lua/plugins/config/telescope.lua with the addition of "-u" to `vimgrep_artuments`?
Could you please give me a complete working example? Thanks

**Comment by antoineco** [comment]
@caneta see my updated example above (https://github.com/NvChad/NvChad/issues/2206#issuecomment-1633208010)

**Comment by caneta** [comment]
@antoineco, your snippets worked like a piece of cake, really appreciated!
Merci beaucoup!
