### ISSUE TITLE
Having issues with window pane navigation,

### ISSUE THREAD

**Issue by n0yal** [siduck76/NvChad#2207]
**Describe the bug**
When i press Control + h in escape mode there is no movement of cursor from right split vertical into left . All other direction but Control+h not working.

**To Reproduce**
1. Go to escape mode 
2. use :vsp to open up a new vertical window
3. use Control + h 
4. It is not moving towards the left file 

**Expected behavior**
When there two files opened in vertical it should move towards the left using Control+h in escape mode.

**Screenshots**
![Screenshot_2023-07-12_13_03_51](https://github.com/NvChad/NvChad/assets/69240615/1fdc2669-5565-4159-b039-20a774872f98)

**Desktop
 (please complete the following information):**
 - Kali linux in vmware workstation pro
 - Qterminal 
 - NVIM v0.9.1

**Additional context**

**Comment by antoineco** [comment]
The behavior you're seeing is caused by QTerminal:
- https://github.com/lxqt/qtermwidget/issues/235
