### ISSUE TITLE
user_config

### ISSUE THREAD

**Issue by se7en-x230** [siduck76/NvChad#221]
I understand that user_config is the file to add custom theme, keybindings and additional settings.

Can somebody explain how to add an additional keybinding to this file?
1. additional keybinding to telescope hidden files:
`map("n", "<Leader>fa", ":Telescope find_files hidden=true <CR>", opt)
`
2. option to start edit where you left off. 
`vim.cmd [[ au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif ]]
` 
The second is at the moment in option.lua which has to be enabled by hand.

**Comment by JustSage** [comment]
Currently `user_config.lua` contains the ui theme, and is interacted with nvchad's theme switcher. 
In the future it will contain additional mappings and settings but right now `mappings.lua` is for mappings (1) and `options.lua` is for settings & commands (2).

Both mappings.lua & options.lua are called from init.lua at runtime so you don't need to enable anything "by hand".

**Comment by se7en-x230** [comment]
Thanks.
So as I understand the plan for the future is to be able to add more custom settings in user_config. But for now only the theme settings is kept there.

For now I have to edit mapping.lua and options.lua
