### ISSUE TITLE
Telescope live_grep not working.

### ISSUE THREAD

**Issue by weckoe** [siduck76/NvChad#2218]
Hi folks. I'm eager to get help from you. currently i'm using latest version of NvChad and my Telescope plugin doesn't work correctly in a big project. I'm writing a few words in a live_grep UI and then it completely breaks my whole pc (i need to restart it). 
Wanna to get any help from you to fix this error cuz i cannot work at all using NvChad ( i like it pretty much, ty for it). assuming that you can help me somehow with that.
BTW: it works good in small projects.

**Comment by siduck** [comment]
not a  nvchad issue, its a telescope issue! can  you make a video and ask on r/neovim

**Comment by Andreius-14** [comment]
extra: Si usas linux instala ripgrep , en Arch sudo pacman -S ripgrep
