### ISSUE TITLE
Error executing vim.schedule lua callback in core/utils.lua

### ISSUE THREAD

**Issue by minocrafft** [siduck76/NvChad#2220]
**Describe the bug**
This error occurs every time when open a new file.

**To Reproduce**

**Expected behavior**

**Screenshots**
![스크린샷 2023-07-18 오후 3 53 06](https://github.com/NvChad/NvChad/assets/84756721/f97286f5-7374-4d59-8d76-41afff3cf70d)

**Desktop (please complete the following information):**
 - macbook air - M1 / Ventura 13.4.1
 - iterm2
 - Neovim 0.9.0

**Additional context**
The same error occurs when performing rm -rf .local/share/nvim referring to #2025 and reinstalling nvchad.

**Comment by siduck** [comment]
show your custom mappings file

**Comment by minocrafft** [comment]
[custom/mappings.lua](https://github.com/minocrafft/dotfiles/blob/main/nvim.chad/lua/custom/mappings.lua)

here is my custom mappings file

I've disabled and added some existing key mappings, is that a problem?

**Comment by antoineco** [comment]
The `M.lspconfig` table is malformed.

```diff
 M.lspconfig = {
+  n = {
     ["<leader>d"] = {
+  },
```

**Comment by minocrafft** [comment]
oops, I think I missed it while fixing the mapping. Modifying the table resolved it.

Thank you for letting me know!
