### ISSUE TITLE
How to enable spell checking? After I use :set spell; the detection of variable names does not take effect.

### ISSUE THREAD

**Issue by whxcode** [siduck76/NvChad#2221]
After using the set spell command, the word "directian" on the right is underlined; but the word on the left is not.

<img width="535" alt="image" src="https://github.com/NvChad/NvChad/assets/44012914/5b5f300b-2284-4941-afff-7586e27b5b36">

**Comment by antoineco** [comment]
Variable names aren't spell-checked by default, only text inside strings and comments is.

Doing so would be a poor decision. Variable names are either short and abbreviated, or long and camelCased or snake_cased, which would trigger the spell checker on pretty much... everything.

**Comment by whxcode** [comment]
> Variable names aren't spell-checked by default, only text inside strings and comments is.
> 
> Doing so would be a poor decision. Variable names are either short and abbreviated, or long and camelCased or snake_cased, which would trigger the spell checker on pretty much... everything.

So what if I need to check the variable name; how do I do it?

**Comment by antoineco** [comment]
The feature which restricts spell checking to comments and strings is part of Neovim's Tree-sitter integration. It was merged some time ago but the original project contains a useful README: https://github.com/lewis6991/spellsitter.nvim

There is currently no way to enable spell checking for _all_ capture groups when Tree-sitter is enabled. You can either:

- Disable Tree-sitter highlights in the current buffer.

- **(Better)** inject your own [Tree-sitter query](https://github.com/nvim-treesitter/nvim-treesitter#adding-queries) to capture `(variable)` as `@spell`.

    Example Lua command:
    ```vim
    :lua require("vim.treesitter.query").set_query("lua", "injections", "(variable) @spell")
    ```

**Comment by siduck** [comment]
> 

it works for me when i turn off the syntax ( vanilla neovim )

![image](https://github.com/NvChad/NvChad/assets/59060246/eaa39748-884c-47c7-bccd-a76d7b08053e)


this isnt a nvchad issue so closed it, you should ask this at r/neovim subreddit
