### ISSUE TITLE
Unable to get C/C++ LSP working on arm64 Linux

### ISSUE THREAD

**Issue by arifmetic** [siduck76/NvChad#2224]
**Describe the bug**
I am trying to install **clangd** as LSP for C/C++ using Mason. However I believe mason is just pulling binaries from clangd github releases, which only offers the x86_64 binaries. 

Here's what `file clangd` outputs after extracting the zip :

```
clangd: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux)
```

As a result Mason just reports the platform is unsupported.

**Screenshots**
<img width="683" alt="Screenshot 2023-07-21 at 7 49 44 PM" src="https://github.com/NvChad/NvChad/assets/97852663/4515e87d-2c99-4891-9551-bd989f149524">

**Additional context**
```
❯ uname -a
Linux Linux 6.3.12-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Jul  6 04:24:20 UTC 2023 aarch64 GNU/Linux
```

How do I configure NvChad to use my system clangd instead of the one installed by Mason?

**Comment by siduck** [comment]
just uninstall clangd from mason

**Comment by arifmetic** [comment]
@siduck it's not even installed actually. Well I still did an uninstall anyway. But it doesn't solve the problem, `:LspInfo` shows `0 client(s) attached to this buffer:`. So I still don't have an LSP server running.

**Comment by siduck** [comment]
> @siduck it's not even installed actually. Well I still did an uninstall anyway. But it doesn't solve the problem, `:LspInfo` shows `0 client(s) attached to this buffer:`. So I still don't have an LSP server running.

make sure you have clangd install globally then. show lspinfo pic, also ask these stuffs in our discord server

**Comment by arifmetic** [comment]
@siduck clangd installed with system package manager (dnf) in /usr/bin. So any program should expect that in PATH.

<img width="1305" alt="Screenshot 2023-07-21 at 10 21 07 PM" src="https://github.com/NvChad/NvChad/assets/97852663/815b788d-e62a-413d-8d67-b829de77a87f">

I am not on discord but did ask this question on the Matrix room. That was a day ago. Didn't get any replies.

**Comment by antoineco** [comment]
@parasaito could you please share the content of your `~/.config/nvim/lua/custom/configs/lspconfig.lua` file so that I can try to reproduce?

The Matrix "support" room is inactive by the way. The "general" one is a bridge to Discord so ask your questions there preferably.

**Comment by arifmetic** [comment]
@antoineco that seems to be an empty file. Nothing in there.

**Comment by antoineco** [comment]
That's why it doesn't work then.

Please use https://github.com/NvChad/example_config/tree/v2.0 and read the docs at https://nvchad.com if your are just getting started. It will help you a lot.

**Comment by arifmetic** [comment]
@antoineco I did try to lookup docs on the nvchad webpage, could not find anything related. Maybe wasn't searching the correct term. Thanks for this link though. Much appreciated.

**Comment by antoineco** [comment]
It's quite prominent, hard to miss 🙂

![image](https://github.com/NvChad/NvChad/assets/3299086/ed934634-a652-4816-aa0a-68e8ea87453b)
