### ISSUE TITLE
Feature request: Add a shortcut to reload nvim configs

### ISSUE THREAD

**Issue by joeynguyen** [siduck76/NvChad#2227]
**Is your feature request related to a problem? Please describe.**
This issue was closed a couple years ago because it got implemented - https://github.com/NvChad/NvChad/issues/369
However, looks like the change was reverted and was expected to be [revived](https://github.com/NvChad/NvChad/commit/3c7de7a890b47f9b4704f0a13577add8e73f38c9#commitcomment-55872768) later on, but the last trace of it was removed in this [commit](https://github.com/NvChad/NvChad/commit/3330d1cc06f79625c01f6eb4b3d01ec9a42985d6).

**Describe the solution you'd like**
Would like to see if this could be implemented again.

**Describe alternatives you've considered**
None I can think of.  Only solution seems to be: close the editor and reopen.  With stock Neovim, you could just do `:so`.

**Comment by siduck** [comment]
@joeynguyen core nvim devs themselves not suggest to reload config. its complicated and that code before was buggy so i removed it. 

however you can partially reload your custom config

saving any file in the custom dir will  automatically reload  the UI stuff and custom.plugins is reloadable too, just save it and lazy will recognize the changes.

**Comment by joeynguyen** [comment]
understood. Thanks for the context!
