### ISSUE TITLE
Individual colors for themes are incorrect

### ISSUE THREAD

**Issue by oldqin97** [siduck76/NvChad#2229]
My expected theme is something like this
<img width="1279" alt="image" src="https://github.com/NvChad/NvChad/assets/48620148/fbbb1858-db86-4aeb-ba6b-eb51e6d04278">

But actually the theme shows like this
<img width="492" alt="image" src="https://github.com/NvChad/NvChad/assets/48620148/b91aafeb-5ffb-4cf4-b324-7dd8ac0bb49b">

 - Operating System：Mac os
 - Terminal: alacritty
 - nvim: 9.0

**Comment by antoineco** [comment]
If you have `lsp_semantic_tokens = true` inside your chadrc.lua, that's the reason.

**Comment by oldqin97** [comment]
> If you have `lsp_semantic_tokens = true` inside your chadrc.lua, that's the reason.

Thank you very much, I have solved the problem
