### ISSUE TITLE
[Theme request] Dracula

### ISSUE THREAD

**Issue by lordlabuckdas** [siduck76/NvChad#223]
**Is your feature request related to a problem? Please describe.**
NvChad currently lacks proper support for the Dracula theme. The colors in [nvim-base16.lua](https://github.com/siduck76/nvim-base16.lua) for Dracula are inaccurate.

**Describe the solution you'd like**
It would be awesome if the Dracula theme is added to NvChad along with its correct colors in `nvim-base16.lua`.

**Describe alternatives you've considered**
Nothing comes close to Dracula imo. :stuck_out_tongue: 

**Additional context**
The color pallete for Dracula can be found [here](https://github.com/dracula/dracula-theme).

**Screenshot**
The current Dracula colorscheme from `nvim-base16.lua`

![NvChad dracula snip](https://user-images.githubusercontent.com/55460753/128665213-b3fd9469-e13f-44a6-8b4c-2655995a873f.png)

Thank you for your awesome work!

**Comment by siduck76** [comment]
I have tried original dracula before and the syntax colors were kinda ugly!  I will soon make a custom Dracula better than the original one for nvchad :D

**Comment by lordlabuckdas** [comment]
Personally, I like the original Dracula theme. So if it isn't too much to ask, could you please separate them into 2 files, say `dracula.lua` (the OG Dracula theme) and `chadracula.lua` (your custom Dracula theme)?

**Comment by siduck76** [comment]
> Personally, I like the original Dracula theme. So if it isn't too much to ask, could you please separate them into 2 files, say `dracula.lua` (the OG Dracula theme) and `chadracula.lua` (your custom Dracula theme)?

ofc , let's see if you would like chadracula more :D . I'll make the theme this Sunday tho! Gonna finish forestchad aka ever forest this Saturday

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/commit/d5c64d335ea4eafa1f7b39ca073a24254c405c4c
