### ISSUE TITLE
lsp.buf.hover

### ISSUE THREAD

**Issue by oldqin97** [siduck76/NvChad#2232]
When I use the "vim.lsp.buf.hover" function in a js or ts file, the cursor can be used normally on variables, but an error will be reported when the cursor is on a blank position, string or comment. I want to know how to solve this problem

<img width="284" alt="image" src="https://github.com/NvChad/NvChad/assets/48620148/1f285d51-bdf2-4e08-a303-a61833c18fb1">

<img width="758" alt="image" src="https://github.com/NvChad/NvChad/assets/48620148/aa896952-52d8-4a51-8d43-0cb6dd3ee04d">

Error: Error executing vim.schedule lua callback: ...lar/neovim/0.9.0/share/nvim/runtime/lua/vim/lsp/util.lua:1682: 'width' key must be a positive Integer
stack traceback:
	[C]: in function 'nvim_open_win'
	...lar/neovim/0.9.0/share/nvim/runtime/lua/vim/lsp/util.lua:1682: in function 'handler'
	...w/Cellar/neovim/0.9.0/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

 - Operating System：macos
 - Terminal: alacritty
 - Version of Neovim: 0.9.0

**Comment by siduck** [comment]
can you provide a video? i cant reproduce this

**Comment by oldqin97** [comment]
> can you provide a video? i cant reproduce this


https://github.com/NvChad/NvChad/assets/48620148/b071ba27-f190-4ed5-9668-890db6c87f84

Demo video here

**Comment by oldqin97** [comment]
> can you provide a video? i cant reproduce this


https://github.com/NvChad/NvChad/assets/48620148/ea9aaf76-2848-48d0-bb64-d86936ec8673

My shortcut key is bound to "vim.lsp.buf.hover", as you can see in the video, the errors are reported on blank lines, strings and comments.
When I use hover on variables, functions, etc., no error will be reported。😢

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/2cf507a8-d975-4d94-a73b-b8523062c61c

unable to reproduce, also this issue isnt related to nvchad, you should ask it on r/neovim or our discord server!
