### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CAESIUS-TIM** [siduck76/NvChad#2235]
https://github.com/NvChad/NvChad/blob/682b023fb36834fda744c9b488d9227c66be7c29/lua/core/default_config.lua#L38

https://whichiscorrect.com/riden-or-ridden/

overriden → overridden ?

**Comment by siduck** [comment]
changing it would be another breaking change! 

also this word exists 

![image](https://github.com/NvChad/NvChad/assets/59060246/0cee8b5e-6005-4639-b436-208dde227efd)
