### ISSUE TITLE
reload is executed even if tabufline and statusline are disabled

### ISSUE THREAD

**Issue by mjmjm0101** [siduck76/NvChad#2236]
https://github.com/NvChad/NvChad/blob/682b023fb36834fda744c9b488d9227c66be7c29/lua/core/init.lua#L94-L102

I disable tabufline and statusline in chadrc.lua like this and use other plugins, but the above part is executed and an error occurs.

```
M.ui = {
    tabufline = {
        enabled = false,
    },
    statusline = {
        enabled = false,
    },
}
```

**Comment by siduck** [comment]
what error? also statusline doesnt even have the enabled option

**Comment by mjmjm0101** [comment]
sorry. I didn't notice it because I was trying it at the same time, but it seems that the error occurs only in tabfuline, and statusline is executed without any problems.
Thank you for your response.
