### ISSUE TITLE
jsdoc can't be highlighted

### ISSUE THREAD

**Issue by ericzzh** [siduck76/NvChad#2241]
**Describe the bug**
When using jsdoc, which installed from nvim-treesitter, the jsdoc in comment can't be highlighted. 
Please help if this is the issue of setting of NvChad, or others( such as nvim or nvim-treesitter )
thanks.

**To Reproduce**
1. install jsdoc from nvim-treesitter( :TSInstall jsdoc)
2. edit a javascript file, and input some jsdoc in comment

**Expected behavior**
jsdoc should be highlighted in comment.

**Screenshots**
<img width="657" alt="image" src="https://github.com/NvChad/NvChad/assets/9389005/d0bb339a-a97d-494b-a988-198a8c6915b1">

**Desktop (please complete the following information):**
 - Operating System: macos 13.4.1 
 - Terminal: iTerm2 build 3.4.18
 - Version of Neovim: 0.9.0

**Additional context**
check my config if necessary
https://github.com/ericzzh/NvChad/tree/zzh/lua/custom

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/7e0202a6-68c1-4534-96f6-2a88adf1f07b)

with jsdoc

![image](https://github.com/NvChad/NvChad/assets/59060246/b4b64535-7f17-4b3b-b6a8-52d0e0aae2a1)

**Comment by siduck** [comment]
reopen neovim please, also make sure you have javascript parser installed too.

**Comment by ericzzh** [comment]
Thanks, it works after installing javascript parser( :TSInstall javascript) 
Sorry, I had a mistake of thinking javascript parser is default installed.
