### ISSUE TITLE
Theme plugin opts not being applied

### ISSUE THREAD

**Issue by danwetherald** [siduck76/NvChad#2244]
I are trying to customize the tokyonight plugin to use a different style:

```
       {
		"folke/tokyonight.nvim",
		lazy = false,
		priority = 1000,
		opts = {
			style = "moon",
		},
	},
```

When the style overrides are passed to `opts` they are not applied.

Not sure if this is a bug or if there is a better way to pass these overrides.

**Comment by siduck** [comment]
@dan003400 external themes on nvchad wouldnt work properly, just use nvchad themes. external themes dont have highlight groups provided by nvchad UI modules, it'd mess up whole look
