### ISSUE TITLE
lsp not attaching to buffer

### ISSUE THREAD

**Issue by MK-Mike** [siduck76/NvChad#2245]
Installed the example version of NVChad
When opening a file I get the following error message in the command line 
"Client {x} quit with code 1 signal 0" 
The same happens when running ":LspStart"

Running ":LspInfo" shows that null-ls is attached and list tsserver as another client that matches the file type

therefore there are no code completions (from lsp) or formatting except for lua 

:LspInfo gives the following
![image](https://github.com/NvChad/NvChad/assets/91474645/9e683018-fe32-4001-96d6-8739a4dec905)

:LspStart gives the following
![image](https://github.com/NvChad/NvChad/assets/91474645/0ea303a7-ee97-47b8-8e03-6586f8c80f1c)

custom/configs/lspconfig.lua
```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"

-- if you just want default config for the servers then put them in a table
local servers = { "html", "cssls",  "tsserver" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
  vim.cmd('LspStart')
end
```

custom/configs/null-ls.lua
```
local present, null_ls = pcall(require, "null-ls")

if not present then
  return
end

local b = null_ls.builtins

local sources = {

  -- webdev stuff
  b.formatting.deno_fmt, -- choosed deno for ts/js files cuz its very fast!
  b.formatting.prettier.with { filetypes = { "html", "markdown", "css" } }, -- so prettier works only on these filetypes

  -- Lua
  b.formatting.stylua,

  -- cpp
  b.formatting.clang_format,
}

null_ls.setup {
  debug = true,
  sources = sources,
}
```
plugins/configs/lspconfig.lua

```
M.on_attach = function(client, bufnr)
  client.server_capabilities.documentFormattingProvider = true
  client.server_capabilities.documentRangeFormattingProvider = true

  utils.load_mappings("lspconfig", { buffer = bufnr })

  if client.server_capabilities.signatureHelpProvider then
    require("nvchad_ui.signature").setup(client)
  end

  if not utils.load_config().ui.lsp_semantic_tokens and client.supports_method "textDocument/semanticTokens" then
    client.server_capabilities.semanticTokensProvider = nil
  end
end
```

**To Reproduce**
1. Fresh install of NVChad using example config
2. Open a file in a project

**Expected behaviour**
null-ls and tsserver should attach to the buffer and give code completions

**Desktop (please complete the following information):**
 - Pop OS
 - Alacrity 
 - Version of Neovim: 
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
(installed as `appimage)`

**Comment by siduck** [comment]
unable to reproduce https://0x0.st/H2sl.mp4

this isnt a nvchad issue, seems like something related to your OS

**Comment by siduck** [comment]
set the lsp log level to debug and check lsp logs

https://www.reddit.com/r/neovim/comments/q4lzki/client_1_quit_with_exit_code_1_and_signal_0_when/

better ask such questions in our discord server etc! you could get instant help there
