### ISSUE TITLE
Unable to integrate neoconf plugin

### ISSUE THREAD

**Issue by moisesmorillo** [siduck76/NvChad#2247]
**Describe the bug**
I'm trying to integrate [neoconf](https://github.com/folke/neoconf.nvim) plugin, this plugin need to be configured before any lsp client is set, but by default nvchad configures lua lsp as part of it startup behavior https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/lspconfig.lua#L44-L65 and there is no an easy way to disable automatically lua lsp setting in nvchad. Also tried to add priority to neoconf plugin to make it load before core  nvchad plugins
but it didn't work.

**To Reproduce**
1. Add neoconf to the list of lazy.nvim plugins
```
      {
        "folke/neoconf.nvim",
        cmd = "Neoconf",
        opts = {},
        priority = 10000,
      },
```
2. Restart neovim,
3. See the error:
```
vim/_meta.lua:0: Vim:Setup `require("neoconf").setup()` should be run **BEFORE** setting up any lsp server with lspconfig
```

**Expected behavior**
It should be a way to disable lua lsp setup on startup in nvchad, make it exportable to reuse when needed.

**Screenshots**
<img width="1329" alt="image" src="https://github.com/NvChad/NvChad/assets/8282983/88cae07f-0931-4157-a78f-7d274c294da8">

**Desktop (please complete the following information):**
 - Operating System: Mac OS 13.5
 - Terminal: alacritty 0.12.2 (9d9982d)
 - Version of Neovim: NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Additional context**

**Comment by siduck** [comment]
```lua
{
    "neovim/nvim-lspconfig",

    config = function()
      require("neoconf").setup()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end,
  },

{
    "folke/neoconf.nvim",
    cmd = "Neoconf",
  }
  ```

**Comment by moisesmorillo** [comment]
> ```lua
> {
>     "neovim/nvim-lspconfig",
> 
>     config = function()
>       require("neoconf").setup()
>       require "plugins.configs.lspconfig"
>       require "custom.configs.lspconfig"
>     end,
>   },
> 
> {
>     "folke/neoconf.nvim",
>     cmd = "Neoconf",
>   }
> ```

That solution didn't work, did you test it? the main reason is because there is an LSP Config already initialized in `lua/plugins/configs/lspconfig.lua` as told in the main message

<img width="1348" alt="image" src="https://github.com/NvChad/NvChad/assets/8282983/85d0a5ac-6aee-4675-b0fd-6116a4657566">
