### ISSUE TITLE
What is this line and how can I remove it

### ISSUE THREAD

**Issue by f4T1H21** [siduck76/NvChad#2248]
Hi,

What is this line and how can I remove it?
I see that line in any file I open with neovim. Even when opening a blank page by just executing nvim in cmdline without any arguments, I see it.

**Screenshot**
![image](https://github.com/NvChad/NvChad/assets/83399767/27f61815-2852-48ab-a4f1-c4ebe29146d4)

 - Terminal: Kitty
 - Version of Neovim: NVIM v0.9.1
 - Font: Nerd Fonts

Thanks for the project, and thanks for your reply in advance.
Kind regards, Şefik Efe.

**Comment by Teagar** [comment]
`colorcolumn` is an option available in Neovim that allows you to define highlighted columns with a specific color. This feature helps visualize column boundaries in a file, making it easier to write and format code.

To remove the `colorcolumn`, you need to remove the corresponding configuration from your Neovim configuration file (usually named `init.vim` or `init.lua`). Locate the line that sets the `colorcolumn` option and either remove it or comment out the associated code. For example, in Lua, if you have something like:

```lua
vim.cmd('set colorcolumn=80')
```

You can simply comment the line by adding "--" at the beginning:

```lua
-- vim.cmd('set colorcolumn=80')
```

After making this change, save the configuration file and restart Neovim for the changes to take effect.

The `colorcolumn` can be useful for maintaining consistent code formatting, but you may choose to remove it if you prefer not to highlight columns. Its usage may vary depending on personal preferences and coding guidelines of the project you are working on.

**Comment by siduck** [comment]
vim.opt.colorcolumn=""

put that in custom init.lua
