### ISSUE TITLE
null-ls alternatives?

### ISSUE THREAD

**Issue by saimon-moore** [siduck76/NvChad#2249]
Current documentation recommends null-ls for formatting/linting.

According to this: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621 it's going to be unmaintained soon.

Has anyone looked into an alternative?

**Comment by abdlmutii** [comment]
Itll probably still work for good amount of time

And if it stopped. Theres a big chace people will fork it and fix the problems.
No need to worry

**Comment by siduck** [comment]
formatter.nvim & nvim-lint

**Comment by GreenSleeper** [comment]
Any thoughts on [none-ls](https://github.com/nvimtools/none-ls.nvim)?

**Comment by siduck** [comment]
@GreenSleeper you can use it. But i will advice nvim-lint & conform.nvim. And conform.nvim's pretty good for lazyloading too

**Comment by gitaarik** [comment]
null/none-ls seems to be easier to setup. With nvim-lint / formatter.nvim / conform.nvim you have to configure each linter / formatter for the filetypes you want to use.  With none-ls you just have to add the sources, and they are automatically configured for the supported filetypes.

**Comment by siduck** [comment]
conform feels faster than null-ls tho ( formatting ) and null-ls cant be lazy loaded properly, we have to disable lsp formatting for null-ls cuz it hijacks the lsp!

**Comment by gitaarik** [comment]
What do you mean with "_we have to disable lsp formatting for null-ls cuz it hijacks the lsp!_" ?

**Comment by siduck** [comment]
> What do you mean with "_we have to disable lsp formatting for null-ls cuz it hijacks the lsp!_" ?

we disable the lsp's inbuilt formatter 
![image](https://github.com/NvChad/NvChad/assets/59060246/e1409d3c-f4bf-413f-a292-36da80a413b0)

or else null's wouldnt work, for example if you wanted to use stylua then ( without the  above formatting settings ) , the sumneko lua's formatter will be used 

cuz leader fm mapping runs this function

![image](https://github.com/NvChad/NvChad/assets/59060246/5b353e9c-2f71-4464-b932-bc13468b9eec)


and that'd make neovim's inbuilt lsp stuff to run the attached lsp's ( sumneko in our case )  to do formatting.

if we disable the lsp's inbuilt capabilities to format, then as you know null-ls also acts as fake lsp server, So i'm assuming neovim will loop through active lsps and use the one for formatting which has formatting capabilities like null-ls one

**Comment by siduck** [comment]
soon null-ls will be replaced with conform in example_config

**Comment by TiLopes** [comment]
Is there any ETA when conform.nvim will be on the example_config?

**Comment by siduck** [comment]
@TiLopes  this saturday

**Comment by siduck** [comment]
@TiLopes  https://github.com/NvChad/example_config/commit/a321ba986da839dc82eec52d072f1c16737d63b8

**Comment by jinzaizhichi** [comment]
Conform.nvim
Very Good!
