### ISSUE TITLE
Nvdash not working when tabufline is disabled

### ISSUE THREAD

**Issue by PedroDSFerreira** [siduck76/NvChad#2250]
**Describe the bug**
When enabling nvdash to load on startup and disabling tabufline, the dashboard does not show in startup, instead I get a buffer error.

**To Reproduce**
1. In '/home/$USER/.config/nvim/lua/custom/chadrc.lua', write:
```lua
M.ui = {
  nvdash = {
    load_on_startup = true,
  },

  tabufline = {
    enabled = false,
 },
}
```
2. Open neovim
4. See error: 
`
Error executing vim.schedule lua callback: ...e/pedro/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:22: attempt to get len
gth of field 'bufs' (a nil value)
stack traceback:
        ...e/pedro/.local/share/nvim/lazy/ui/lua/nvchad_ui/init.lua:22: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
`

**Expected behavior**
Show the dashboard when running `nvim` in the terminal, without any errors

**Screenshots**
![2023-07-29_17-38-23](https://github.com/NvChad/NvChad/assets/97121697/9f261b63-1804-4d65-a0a9-6ae795da80cc)

**Desktop:**
 - Operating System: Arch Linux
 - Terminal: Alacritty
 - Version of Neovim: v0.9.1

**Additional context**
When enabling `tabufline`, the dashboard shows as expected.

**Comment by siduck** [comment]
update nvchad
