### ISSUE TITLE
which-key.nvim: Name prefixes

### ISSUE THREAD

**Issue by CAESIUS-TIM** [siduck76/NvChad#2257]
### Discussed in https://github.com/NvChad/NvChad/discussions/2256

<div type='discussions-op-text'>

<sup>Originally posted by **CAESIUS-TIM** August  2, 2023</sup>
## [which-key.nvim README](https://github.com/folke/which-key.nvim/blob/7ccf476ebe0445a741b64e36c78a682c1c6118b7/README.md?plain=1#L234-L266)

```lua
-- all of the mappings below are equivalent


-- method 2
wk.register({
  ["<leader>"] = {
    f = {
      name = "+file",
      f = { "<cmd>Telescope find_files<cr>", "Find File" },
      r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
      n = { "<cmd>enew<cr>", "New File" },
    },
  },
})


-- method 3
wk.register({
  ["<leader>f"] = {
    name = "+file",
    f = { "<cmd>Telescope find_files<cr>", "Find File" },
    r = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
    n = { "<cmd>enew<cr>", "New File" },
  },
})


-- method 4
wk.register({
  ["<leader>f"] = { name = "+file" },
  ["<leader>ff"] = { "<cmd>Telescope find_files<cr>", "Find File" },
  ["<leader>fr"] = { "<cmd>Telescope oldfiles<cr>", "Open Recent File" },
  ["<leader>fn"] = { "<cmd>enew<cr>", "New File" },
})
```
https://github.com/NvChad/NvChad/blob/0e27cb4b44fbba69f8646d1f88555737d2b6aedf/lua/core/utils.lua#L54-L88

It seems that no argument named `name` in nvchad's core mapping util.😢

**Comment by siduck** [comment]
@CAESIUS-TIM yes, nvchad's mapping util doesnt support all of whichkey's functionality, so just please either register within whickey config itself

**Comment by siduck** [comment]
or

```lua

M.abc = {
  n = {
    ["<leader>f"] = { "  ", "+file" },
  },
}
```

**Comment by CAESIUS-TIM** [comment]
> ```lua
> ["<leader>f"] = { "  ", "+file" },
> ```

![image](https://github.com/NvChad/NvChad/assets/60285058/68c57853-b7de-4d2c-bd55-bea3394ab30f)
![image](https://github.com/NvChad/NvChad/assets/60285058/f86012f2-23e9-4025-8969-41d16efe8cc3)

but color is for a command but not for a prefix. 😂

![image](https://github.com/NvChad/NvChad/assets/60285058/60d11f98-ec70-4634-af53-aac156b5d9be)

and not be grouped as a prefix

Eazy, but whickey config itself is better for a perfectionism.

**Comment by orhnk** [comment]
Overloading: 

> [!NOTE]
> This is not going to work after a which-key.nvim
> refactoring (change in config function)

```lua
  { -- WhichKey overrides
    "folke/which-key.nvim",
    config = function(_, opts)         -- <-- START lua/plugins/init.lua
      dofile(vim.g.base46_cache .. "whichkey")
      require("which-key").setup(opts) -- <-- END lua/plugins/init.lua

   ----------------- CUSTOM -------------.
      local wk = require "which-key"    --.
      wk.register {                     --'
        ["<leader>"] = {                --'
          g = { name = "group name" },  --'
        },                              --'
      }                                 --'
   -------------------------------------'

    end,
  },
```

**Comment by stove-jeebs** [comment]
How can I add registered which-keys to the cheatsheet?

**Comment by siduck** [comment]
> How can I add registered which-keys to the cheatsheet?

you have to do some lua hackery i.e define keymaps in our mappings syntax and then add plugin=true to it, then pull that table in wk.register

**Comment by mks1508** [comment]
My simple solution:
```lua
M.hop = {
  n = {
    ["<leader>`"] = { "<leader>`", "+Hop" },
    ["<leader>``"] = { "<cmd>HopWord<CR>", "Hop word" },
    ["<leader>`1"] = { "<cmd>HopChar1<CR>", "Hop 1-char" },
    ["<leader>`2"] = { "<cmd>HopChar2<CR>", "Hop 2-chars" },
    ["<leader>`~"] = { "<cmd>HopPattern<CR>", "Hop pattern" },
  },
}
```
