### ISSUE TITLE
Statusline weird stuff overloading each other

### ISSUE THREAD

**Issue by meeffe** [siduck76/NvChad#2258]
**Describe the bug**
Statusline weird stuff overloading each other (rounded and square I guess)

**To Reproduce**
1. I just installed a default config following:
2. # Linux / Macos (unix)
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
3. and then: git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
4. I use Jetbrains Mono Nerd font

**Expected behavior**

**Screenshots**
Screenshot: https://share.cleanshot.com/0KNP5f6d
![statusbar](https://github.com/NvChad/NvChad/assets/94453502/5d186c17-42c4-406e-af5b-0c26e1c4fa8a)

**Desktop (please complete the following information):**
 - Operating System - macos ventura 13.4.1
 - Terminal iterm2
 - Version of Neovim 0.9

**Additional context**
No additional conntext

**Comment by siduck** [comment]
its your terminal issue, please apply nerdfonts properly

**Comment by meeffe** [comment]
![terminal](https://github.com/NvChad/NvChad/assets/94453502/a76c2768-e939-4e1a-b560-ce1962abdae0)

Thanks for your reply, but I downloded, installed proper nerdfonts and tried with many of them, still the same issue.

**Comment by siduck** [comment]
@meeffe can you try another terminal or another font? jetbrains nerd font for example
