### ISSUE TITLE
nomicfoundation-solidity-language-server doesn't attach

### ISSUE THREAD

**Issue by f4T1H21** [siduck76/NvChad#2261]
**nomicfoundation-solidity-language-server Doesn't Attach**

Hello,
I am looking for help to attach `nomicfoundation-solidity-language-server` to solidity files, thanks in advance!

I installed `nomicfoundation-solidity-language-server` via `mason.nvim`, and configured it in the `custom/config/lspconfig.lua` file as you can see below.

```lua
local base = require("plugins.configs.lspconfig")

local on_attach = base.on_attach
local capabilities = base.capabilities

local lspconfig = require("lspconfig")
local util = require("lspconfig/util")

print(lspconfig)

-- if you just want default config for the servers then put them in a table
local servers = { "pyright", "solidity_ls_nomicfoundation" }

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

Above file is called by the `custom/plugins.lua`, whose contents can be seen below.
I can confirm that the configuration files' structure is correct, because `pyright` is running properly.

```lua
local overrides = require("custom.configs.overrides")

local plugins = {
    {
        "christoomey/vim-tmux-navigator",
        lazy = false,
    },
    {
        "williamboman/mason.nvim",
        opts = {
            ensure_installed = {
                "lua-language-server",
                "pyright",
                "rust-analyzer",
                "clangd",
                "typescript-language-server",
                "nomicfoundation-solidity-language-server",
            },
        },
    },
    {
        "neovim/nvim-lspconfig",
        config = function ()
            require("plugins.configs.lspconfig")
            require("custom.configs.lspconfig")
        end,
    },
    {
        "nvim-treesitter/nvim-treesitter",
        opts = overrides.treesitter,
    },
}

return plugins
```
And the above file is of course called by the `custom/chadrc.lua` file:
```lua
---@type ChadrcConfig 
local M = {}
M.plugins = "custom.plugins"
return M
```
**Screenshots**
Here, you can see there's a solidity file opened and it seems like the file is providing all the requirements (eg. `root_dir`) for the language server to attach. But unfortunately it doesn't attach.
![solidity_lsp_doesn't_attach](https://github.com/NvChad/NvChad/assets/83399767/2dc4b6ae-80b4-4bcc-ab02-40047859caa1)

**Additional Environmental Information**
 - Operating System: Kubuntu 22.04.2 LTS 
 - Terminal: Kitty
 - Version of Neovim: v0.9.1

**Comment by siduck** [comment]
not a nvchad issue, please check lsp logs and better ask this at r/neovim or its matrix server

**Comment by f4T1H21** [comment]
Updated nodejs version from the nodejs website and this issue resolved
