### ISSUE TITLE
Same colorscheme in terminal and NvChad

### ISSUE THREAD

**Issue by zoomido** [siduck76/NvChad#2263]
I'm using base16-shell for changing my terminal colorscheme. I used to have this synced to neovim so when I changed theme in the terminal, neovim uses the same colors.
But since nvchad are using it's own (and better thank you) theming system I was wondering what the best way would be to keep the terminal and nvchad themes in sync?
The most important for me is that the background color matches both nvchad and terminal since otherwise I get an ugly border (because of padding in kitty).
I tried manually changing themes in both places but many of the nvchad themes are not available in base16 and it would be a hassle to try to manually find a good match for each.
Any ideas are welcomed 🙏 

Thank you for keeping this project up to date! I have had my own configs for several years but NvChad looks nice enough that I'm giving it a try now :)

**Comment by siduck** [comment]
@zoomido 

```lua

M.ui = {
  hl_override = {
    Normal =  {
      bg = 'none'
    }
  }
}
```
or change none with your hex color , read the theming docs in nvchad.com for more info

**Comment by zoomido** [comment]
Thanks, this seems to work satisfactory 👍  Would be nice with some integration in the future so that themes are in sync but maybe it is out of scope.

**Comment by siduck** [comment]
@zoomido you could just enable the transparency option as well
