### ISSUE TITLE
<TAB> acts weird after autocompletion (?)

### ISSUE THREAD

**Issue by hepp3n** [siduck76/NvChad#2267]
**Describe the bug**
I think it happens mostly after autocompletion, cursor jumps to random spots when pressing TAB. Basically it should make an indentation but it acts weird for few next presses. I'm not sure what is going on so I recorded a video explaining what I mean.

**To Reproduce**
1. Choose one of autocompletion by pressing Return / Enter
2. Make sure you are indented, then press Return to make new line with some indentation
3. Ctrl+c to enter Normal mode.
4. Enter insert mode. Press TAB few times.
5. See bug (?) Cursor will jumps from one place to another ;p

**Expected behavior**
Just indent line, not go to different place...

**Screenshots**
https://streamable.com/lrea4o

**Desktop (please complete the following information):**
 - Operating System: Linux/ Ubuntu 22.04
 - Terminal: Gnome terminal but it happens on many of them...
 - Version of Neovim: 0.9.1 stable branch + latest nvChad.

**Additional context**
Like I said. I'm not sure what's going on and what is triggering this cursor to jump to another spot instead of just indent. It's happens in insert mode, maybe some weird keybind? I don't know. My setup is mostly stock NvChad with rust and python treesitter parser and rust-analyzer. That's all. I did not change anything in NvChad.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/97a19f13-f787-4ecb-ad89-45436f3a3aae)

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/a2cbcfba-fd6b-46bb-8191-0a593124f585

if you're talking about this then i think its normal

**Comment by siduck** [comment]
just use `S` to get into insert mode then

**Comment by rafaelsmgomes** [comment]
I'm facing the same issue. 

Sometimes, when I click tab on insert mode my cursor jumps wildly to completely different places in the file.

**Comment by siduck** [comment]
> I'm facing the same issue.
> 
> Sometimes, when I click tab on insert mode my cursor jumps wildly to completely different places in the file.

show video

**Comment by rafaelsmgomes** [comment]
Absolutely! 

This has happened to me many times, but for some reason, I cannot reproduce it right now. 

So, I'll keep on top of it and will post one as soon as it happens again. 

Thanks for the response.

**Comment by rafaelsmgomes** [comment]
Hi! I'm sorry for taking so long to get back to you. 

I was going to go back to this and other things kept coming up.

Anyway, I figured out why the cursor jumps when using autocomplete. 

If I use a snippet and don't jump through all the cursor locations the jump locations get saved in memory and later on, when using tab in a different context (but in the same file) they can still get triggered. 

Guess just knowing this is enough for me. I can live with that. I don't think this is something on NvChad (it seems more like a nvim behavior to me).

Anyway, sorry for the long time to reply. Great plugin! It's been indispensable to me! Thanks!

**Comment by siduck** [comment]
@rafaelsmgomes you can always discuss on our discord server etc ( links in nvchad.com footer )
