### ISSUE TITLE
Error executing vim.schedule

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2268]
Howdy,

I was runnning into this error while configuring nvchad. it doesnt effect anything just wanted to let you know.
 To reproduce: This is my exact custom configuration and it happens everytime I start up neovim
[custom.zip](https://github.com/NvChad/NvChad/files/12268820/custom.zip)
and i get this error
![Screenshot 2023-08-06 014455](https://github.com/NvChad/NvChad/assets/65212972/fb96e0d3-f14e-4d6e-95d5-26fb4eed07fc)
my destop version is (what I get after running :cat /etc/*release)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
am running version 0.10.0 -dev of neovim (I did this cause apt-get is horrendously out of date)

**Comment by siduck** [comment]
issue with your custom mappings.

check the comment here

![image](https://github.com/NvChad/NvChad/assets/59060246/551b5b52-9114-47a9-bc7e-5ec6a9c77bff)

**Comment by DrTeagle** [comment]
I got rid of those comments and am still getting the errors

**Comment by siduck** [comment]
> I got rid of those comments and am still getting the errors

just comment your mappings table one by one please. i literally tested your custom config here, only the commented code was the fault i think

**Comment by DrTeagle** [comment]
thank you for your time I appreciate it, will do that now will come back if still problems

**Comment by DrTeagle** [comment]
I think I found the problem its that nvim-dap-ui and mason-nvim-dap.nvim both cause this issue as this issue persisted after I removed the mappings.lua file. I have commented out package by package and it seems that these two packages are what is causing it any idea why?

**Comment by DrTeagle** [comment]
more specifically it seems its due to me setting them to VeryLazy in loading
