### ISSUE TITLE
Use Without Base46

### ISSUE THREAD

**Issue by brainlessbitch** [siduck76/NvChad#2269]
I really like most of the default plugins, aside from base46, I'd much rather be able to use normal neovim colorschemes. I'm wondering if you could provide a preset config that does not include any instance of base46, or some info on how to remove it on the wiki. This would be a really nice optional feature, I'd love to use this project but that's the one thing keeping me from wanting to use it. Also I'm sorry if this is kinda a stupid request, I also wasn't certain whether to post this as an issue or a feature request so I'm sorry if this is in the wrong place. Thank you

**Comment by siduck** [comment]
you can technically, but you would have to override all plugin config specs and remove the "dofile" line and also that autocmd that contains some base46 code. imo its too much work. i wouldnt do it if i were you. 

which themes do you miss? I will port it for you, as long as it isnt CATPUCCIN

**Comment by brainlessbitch** [comment]
zenburn, catppuccin(the variants not just the base), and a lot of themes I've made myself

**Comment by siduck** [comment]
ok i will port zenburn and others,   but not catpuccin variants

**Comment by brainlessbitch** [comment]
may I ask why not the catppuccin variants? those are some of my most used themes lol

**Comment by brainlessbitch** [comment]
I also still think I'd be a nice option to have, I like to make my own nvim themes, but that took me a really long time to learn already learning a whole new system for making colorschemes is a lot of work

**Comment by siduck** [comment]
> may I ask why not the catppuccin variants? those are some of my most used themes lol

I refuse to elaborate, I'm ready to add thousands of other themes but not cattpuccin ones. Even the current one we is based on Oldest cattpuccin theme + that too its my modification

**Comment by brainlessbitch** [comment]
fair enough, would you consider making a guide to making themes for base46? I'd port catppuccin myself if I understood how

**Comment by brainlessbitch** [comment]
@siduck, I added you on discord, I'd like to learn more about this project, and github is not the ideal communication platform

**Comment by siduck** [comment]
@exoess sorry I dont take DMS from strangers. Although you can ask stuff in my server https://discord.gg/2zDfdRkrFj

**Comment by brainlessbitch** [comment]
that's kinda weird but whatever, I can't really ask other people questions about how _you_ developed it

**Comment by siduck** [comment]
> that's kinda weird but whatever, I can't really ask other people questions about how _you_ developed it

Just ping me with the question in the general channel

**Comment by brainlessbitch** [comment]
sorry to randomly add this to the thread, but is there a chance you could port fairyfloss to base46?

**Comment by siduck** [comment]
@exoess make an issue on base46 repo

**Comment by 9mm** [comment]
Im curious about catpuccin now ... ive searched all the issues and it seems you vehemently hate catpuccin. is there some good beef here?

**Comment by siduck** [comment]
> Im curious about catpuccin now ... ive searched all the issues and it seems you vehemently hate catpuccin. is there some good beef here?

I do not hate the colors tho, I refuse to elaborate as revealing it might get me into huge trouble

**Comment by 9mm** [comment]
🤔 the plot thickens... the mystery novel of NVChad
