### ISSUE TITLE
There is a problem with cmp autocompletion.

### ISSUE THREAD

**Issue by whxcode** [siduck76/NvChad#2274]
I want that after the completion menu appears; I use the Tab key, the first menu item should be selected, not the second. The lua/plugins/configs/cmp.lua configuration already contains the "preselect=cmp.PreselectMode.None," option, but it doesn't seem to take effect.

<img width="524" alt="image" src="https://github.com/NvChad/NvChad/assets/44012914/f1768235-ae97-486a-bff4-32a3ffbe24f3">

<img width="778" alt="image" src="https://github.com/NvChad/NvChad/assets/44012914/04161214-67c7-4e7e-be0c-352546e0c16c">

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/44d3c070-a670-4973-a1ed-a5f215987833

By default the 1st item gets selected, press "tab" again, it'll cycle down i.e select 2nd item

**Comment by idr4n** [comment]
> By default the 1st item gets selected, press "tab" again, it'll cycle down i.e select 2nd item

is there a way to override this default behavior? I would prefer that nothing is selected and, as mentioned by @whxcode, `preselect = cmp.PreselectMode.None` does not take effect in cmp's config options.

**Comment by siduck** [comment]
@idr4n look for cmp issues of this year, there was one in which i fixed this :thinking:

**Comment by idr4n** [comment]
> @idr4n look for cmp issues of this year, there was one in which i fixed this 🤔

Thanks for suggesting that. Took a bit to find but finally did. This was the culprit https://github.com/NvChad/NvChad/issues/2632#issuecomment-1915963405
