### ISSUE TITLE
Unstable to use other bufferline plugins due to UI issues

### ISSUE THREAD

**Issue by MKrbm** [siduck76/NvChad#2280]
In order to use `bufferline.nvim` plugin, I disabled tabufline.

```
M.ui = {
  tabufline = {
      enabled = false,
  },
}
```

in chadrc.lua.

However, as below image, even if there are multtiple buffers, they doesn't showup on the top.

![image](https://github.com/NvChad/NvChad/assets/57752203/a21b8a8e-7dbc-47bb-a77f-784098494d9f)

Could you kindly help me to solve this?

Btw, I'm looking for the other plugins for bufferlines re-ordering.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/3ef3d1d2-52d9-4cb5-98a7-515562f90124)

now figure out

**Comment by MKrbm** [comment]
Thank you. perfect!

I hope tabufline will have re-ordering feature.

**Comment by siduck** [comment]
@MKrbm https://nvchad.com/docs/api

**Comment by MKrbm** [comment]
It's embarrassing.  Thank you again.
