### ISSUE TITLE
Changing shiftwidth can cause tab rendering bug in C++ files

### ISSUE THREAD

**Issue by sasq64** [siduck76/NvChad#2282]
**Describe the bug**
Setting `shiftwidth = 4` causes rending of physical tabs to be incorrect in C++ files.

NOTE: Also setting `tabstop = 4` fixes the problem. It may be that problem only arrises
when tabstop < shiftwidth.

**To Reproduce**

* Start with clean nvchad install.
* Add `vim.opt.shiftwidth = 4` to custom/init.lua
* Open C++ source file with physical tab characters

**Expected behavior**

Characters should not become invisible after a physical tab

**Screenshots**
<img width="588" alt="Screenshot 2023-08-10 at 14 23 40" src="https://github.com/NvChad/NvChad/assets/531713/a0ede411-9c48-425e-9ff3-9e3f7f4287bd">

**Desktop (please complete the following information):**
OSX 13.0.1, Neovim 0.9.1
Both in iTerm, wezterm & terminal tested.

**Comment by siduck** [comment]
does it occur with vanilla neovim or non nvchad configs?

**Comment by siduck** [comment]
ok wait, there's a reason why all of these are "2" 

![image](https://github.com/NvChad/NvChad/assets/59060246/c21cd809-1e33-4e8f-a929-cb9e22c82cd7)


so please make tabstop accordingly

**Comment by sasq64** [comment]
I don't understand; what is the file in the screenshot and what does "accordingly" mean here?
If tabstop _must_ be equal to _shiftwidth_, shouldn't we see a warning at least?

(It took me an hour to figure out why I got the rendering bug).

**Comment by siduck** [comment]
you see the common pattern that those options have a common value which is 2 so it must be pretty obvious that you'd fall into issues if you set different values for them

**Comment by sasq64** [comment]
I... What?

I don't even know what file that screenshot is from or what it relates to.
And even I had found it I don't know of a rule that nvchad requires them to be changed to the same value.

Anyway, this issue can affect other C++ users this way;

* They install nvchad & c++ support and start editing a file.
* A soon as they press enter in the code they notice that autoindent is all wrong since the default tab size of 2 is not default in C++ code, 4 is the common value.
* They change shiftwidth to 4 which fixes auto indent, and everything seem fine.
* At some later point they open a file with physical tabs in them, they get rendering bugs and have no idea why because they don't even remember changing the shiftwidth setting.

Of course this is not a major issue, but it is not obvious,

**Comment by siduck** [comment]
all nvchad options are defined in core/init.lua..

**Comment by siduck** [comment]
other c++ wont find this bug unless they change the indent etc settings. also its common vim knowledge to know that those options exist so c++ users would just use same values for those options
