### ISSUE TITLE
neovim crashes after the Update  

### ISSUE THREAD

**Issue by 0xwagmi** [siduck76/NvChad#2283]
**Describe the bug**

```
Failed to run `config` for ui
config/nvim/lua/plugins/init.lua:24: module 'nvchad_ui' not found:
^Ino field package.preload['nvchad_ui']
cache_loader: module nvchad_ui not found
cache_loader_lib: module nvchad_ui not found
^Ino file './nvchad_ui.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/nvchad_ui.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui/init.lua'
^Ino file '/usr/share/lua/5.1/nvchad_ui.lua'
^Ino file '/usr/share/lua/5.1/nvchad_ui/init.lua'
^Ino file './nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad_ui.so'
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - ~/.config/nvim/lua/plugins/init.lua:24 _in_ **config**
  - ~/.config/nvim/lua/plugins/init.lua:282
  - 
Press ENTER or type command to continue
```

**To Reproduce**
I just  did :NvchadUpdate 

**Expected behavior**
Crashes every time when opened 

**Desktop (please complete the following information):**
 - Operating System  Linux
 - Terminal  Zsh
 - Version of Neovim latest

**Comment by 0xwagmi** [comment]
fixed it by   making a backup of my old config ,them re-cloned the repo and adjusted the new configuration files

**Comment by predmijat** [comment]
Adjusted how? I'm getting this:
```
Error detected while processing /Users/predmijat/.config/nvim/init.lua:
Lua module not found for config of ui. Please use a `config()` function instead
```
Where can I read more about what I should do?

**Comment by siduck** [comment]
@predmijat please show the full error by mes command. also do lazy sync too :/.

**Comment by predmijat** [comment]
That's all info I get even with `:mes`.
`:Lazy sync` also done.

**Comment by siduck** [comment]
> That's all info I get even with `:mes`. `:Lazy sync` also done.

do nvchadupdate too please, if that fails then that means you've edited outside of the custom dir, try a git pull within nvim dir

**Comment by predmijat** [comment]
I've also done `:nvchadupdate`. No edits outside `custom` dir. Tried removing `~/.config/nvim` and `~/.local/share/nvim`, doing a fresh clone, and then just `ln -s $my_custom_dir ~/.config/nvim/lua/custom` and I see the error I mentioned.

**Comment by siduck** [comment]
do you get the error without custom dir?

**Comment by siduck** [comment]
please go to the local dir for our ui repo plugin and check the recent commit in it,  show image of it :/ 

if all fails, then just do a clean installation of nvchad

**Comment by predmijat** [comment]
I did clean installation, and error shows up after I link my `custom` dir. My initial question is how to figure out what from my `custom` dir is causing the issue, as error itself isn't telling me much.

**Comment by siduck** [comment]
@predmijat please share you custom dir...

**Comment by predmijat** [comment]
Not really sure if I have something in there that I wouldn't like to be public, so I guess I'll comb through it myself...just thought there's a trick I didn't know which would pinpoint the issue. Thanks for the fast responses!

**Comment by fabruun** [comment]
Is there a fix for this? I'm having the same issue, on both my Laptop and Desktop PC now.
