### ISSUE TITLE
error detected after update

### ISSUE THREAD

**Issue by Marskey** [siduck76/NvChad#2287]
![image](https://github.com/NvChad/NvChad/assets/13499986/281d1e33-dfdb-4bb6-a063-ff5e6b7d8ce9)

i am override the ui config in my custom like.
```lua
    {
        "NvChad/ui",
        opts = {
            statusline = {
                separator_style = "block",
            },
            tabufline = {
                enabled = false,
                overriden_modules = nil,
            },
        },
    },
```

before the update, everything is fine.

**Comment by siduck** [comment]
Nvchad's ui plugin options are meant to be in chadrc man. not the opts
