### ISSUE TITLE
Can't disable the `<c-n>` mapping used for nvim-tree toggling

### ISSUE THREAD

**Issue by swrh** [siduck76/NvChad#2288]
I can't disable the `<c-n>` mapping. I can disable other mappings like `j` or `<tab>`, but not `<c-n>`. Adding `["<c-n>"] = "",` to `M.disabled` on `lua/custom/mappings.lua` doesn't do anything.

The only way I can disable CTRL-N is by removing its setting from `lua/core/mappings.lua`, but that's a hack and I'd like to avoid it if possible.

Is there anything I can do on `lua/custom` to disable it?

**Comment by georgejean** [comment]
It doesn't work with `<c-n>`. Use `<C-n>` instead (see `:h keycodes`).

**Comment by swrh** [comment]
I guess you're right: using capital `C` does work.

Can I make a feature request so it does a case-insensitive search when comparing key modifiers (`C-`, `M-`, `A-`, etc)?

**Comment by siduck** [comment]
@swrh our lua function for overriding user mappings etc just uses the key value pair stuff, so  you have to write the exact key name i.e keystroke which is <C-n>

> Can I make a feature request so it does a case-insensitive search when comparing key modifiers (C-, M-, A-, etc)?

it made our codebase complex so no, i have tried it before too.
