### ISSUE TITLE
Remove the Dashboard

### ISSUE THREAD

**Issue by insidersbuilt** [siduck76/NvChad#229]
Hello i am new to vim community and i triend to configure the lsp but i couldn't then i discoverd the NvChad that was awesome but now i am trying to remove Dashboard plugin but i am getting errors how can i remove the dashboard plugin

**Comment by siduck76** [comment]
Remove dashboard.lua file and remove this block from pluginlist.lua

Use {
"glephnir/dashboard"
Blah 
Blah
}

Remove the whole use block of dashboard and do :Packersync

**Comment by Vanderscycle** [comment]
@insidersbuilt The dashboard plugin should run without errors tho :/ What error are you getting?

**Comment by siduck76** [comment]
> IMHO the dashboard is kind of useless as `space fo` does pretty much the same thing but faster.

yea agreed but it's disabled by default so won't bother , probably better for those using mouse more

**Comment by siduck76** [comment]
> > Remove dashboard.lua file and remove this block from pluginlist.lua
> > Use {
> > "glephnir/dashboard"
> > Blah
> > Blah
> > }
> > Remove the whole use block of dashboard and do :Packersync
> 
> can i do the same thing with thethemes loaded in teliscope because i don't want the themes loaded in the teliscope

what do you mean? could you be more specific ?

**Comment by insidersbuilt** [comment]
> set this to true https://github.com/siduck76/NvChad/blob/main/lua/chadrc.lua#L34

i am felling guilty for wasting your time but how can we make this command work in lua
this is a very useful setting for yanking text 


augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank({timeout = 40})
augroup END

**Comment by insidersbuilt** [comment]
> vim.cmd( [[ add here ]] )

It worked thanks man Love from Pakistan🇵🇰

**Comment by siduck76** [comment]
> > vim.cmd( [[ add here ]] )
> 
> It worked thanks man Love from Pakistan

khuda hafiz akhi!
