### ISSUE TITLE
Keymap "jk" cannot be disabled.

### ISSUE THREAD

**Issue by LollipopFt** [siduck76/NvChad#2290]
**Describe the bug**
For insert mode, keymap "jk" to "<esc>" cannot be disabled.

**To Reproduce**
1. Go to `custom/mappings.lua` and add:
```lua
M.disabled = {
  i = {
    ["jk"] = ""
  }
}
```
2. Restart neovim, `:NvChadUpdate`, restart neovim again.
3. Typing "jk" in insert mode still escapes insert mode into normal mode.

**Expected behavior**
Typing "jk" in insert mode should type "jk" out normally.

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Pro 22H2
 - Terminal: Alacritty
 - Version of Neovim: `NVIM v0.10.0-dev-800+g3d948a4dc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3`

**Comment by LollipopFt** [comment]
figured out that it's the better escape plugin that's causing this problem.

**Comment by kevinkleine** [comment]
I have this problem as well! Could you tell me how you solved it? I don't think my config has the better escape plugin. Grepping on "jk" gives me no results, other than the code below in the custom mapping

```
M.disabled = {
  i = {
    ["jk"] = ""
  }
}
```

**Comment by siduck** [comment]
@kevinkleine  use vim.keymap.set
