### ISSUE TITLE
New module path seem invalid

### ISSUE THREAD

**Issue by hraytilakhealthcare** [siduck76/NvChad#2291]
**Describe the bug**
When opening most functions of NvChad, it fails with an error message for modules not found.

**To Reproduce**
1. Go to 'the last commit on the v2.0 branch'
2. Open an lua file (since the LSP is enabled by default), or use telescope
3. See error

**Expected behavior**
No error displayed

**Screenshots**
```
Failed to run `config` for nvim-lspconfig
/home/ahub/.config/nvim/lua/plugins/configs/lspconfig.lua:2: module 'nvchad.lsp' not found:
^Ino field package.preload['nvchad.lsp']
cache_loader: module nvchad.lsp not found
cache_loader_lib: module nvchad.lsp not found
^Ino file './nvchad/lsp.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/nvchad/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad/lsp/init.lua'
^Ino file '/usr/share/lua/5.1/nvchad/lsp.lua'
^Ino file '/usr/share/lua/5.1/nvchad/lsp/init.lua'
^Ino file './nvchad/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad/lsp.so'
^Ino file '/usr/lib/lua/5.1/nvchad/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './nvchad.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad.so'
^Ino file '/usr/lib/lua/5.1/nvchad.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - lua/plugins/configs/lspconfig.lua:2
  - lua/custom/plugins.lua:20 _in_ **config**
  - lua/core/utils.lua:104

```

**Desktop (please complete the following information):**
 - Operating System: Arch
 - Terminal: Alacritty
 - Version of Neovim: 0.9.1

**Additional context**

The error message while opening a Lua file is the following:
```
Failed to run `config` for nvim-lspconfig
/home/ahub/.config/nvim/lua/plugins/configs/lspconfig.lua:2: module 'nvchad.lsp' not found:
^Ino field package.preload['nvchad.lsp']
cache_loader: module nvchad.lsp not found
cache_loader_lib: module nvchad.lsp not found
^Ino file './nvchad/lsp.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/nvchad/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad/lsp.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad/lsp/init.lua'
^Ino file '/usr/share/lua/5.1/nvchad/lsp.lua'
^Ino file '/usr/share/lua/5.1/nvchad/lsp/init.lua'
^Ino file './nvchad/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad/lsp.so'
^Ino file '/usr/lib/lua/5.1/nvchad/lsp.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './nvchad.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad.so'
^Ino file '/usr/lib/lua/5.1/nvchad.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - lua/plugins/configs/lspconfig.lua:2
  - lua/custom/plugins.lua:20 _in_ **config**
  - lua/core/utils.lua:104

```

A similar one appear when trying to use telescope and other functions. Since the `:NvChadUpdate` doesn't work either, I went into the repository and manually rolled back to commit 05f5819 and everything works again. It seem likely that the recent work on module paths (from commit 487ca44 and onwards) broke.

PSA: If you experience the same issue, the following command does the trick. You'll be able to run `:NvChadUpdate` and continue using the latest changes when it is fixed:
```
cd ~/.config/nvim
git checkout 05f5819
```

**Comment by mjolk** [comment]
mm i had this shit as well after updating plugins via Lazy. For some reason i couldn't get my fork synced with the new commits in v2.0. Git fetch upstream kept giving me an old commit, after syncing my fork through the github UI; pulling the latest v2.0 commits and nuking .cache/nvim and .local/share/nvim everything works again.

**Comment by ariel-frischer** [comment]
Same issue, had to nuke .local/share/nvim + .cache/nvim then do a `git merge (nvchad-remote-name)/v2.0`

**Comment by siduck** [comment]
update nvchad properly and do lazy sync.

If you make changes outside the custom dir then nvchad update wont be done properly
