### ISSUE TITLE
Unable to update nvchad

### ISSUE THREAD

**Issue by ckt114** [siduck76/NvChad#2293]
**Describe the bug**
Updating nvchad throwing error below.

```
fatal: could not read Username for 'https://github.com': terminal prompts diabled
```

After that restarting nvim the following error is thrown.

```
^I...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:202: in function <...cal/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:185>
E15: Invalid expression: v:lua.require('nvchad.statusline.default').run()
```

**To Reproduce**
1. Run nvim
2. Open Lazy
3. Press `U`

**Expected behavior**

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/573808/5bd713d2-0a30-473c-bfc0-55cd50113a18)

**Desktop (please complete the following information):**
 - MacOS Ventura 13.4.1
 - Terminal: Wezterm
 - Version of Neovim: v0.9.1

**Additional context**

**Comment by siduck** [comment]
@ckt114 clean install nvchad

**Comment by siduck** [comment]
```bash
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```

**Comment by ckt114** [comment]
That works. Very odd but thanks.

**Comment by siduck** [comment]
@ckt114 extensions repo had UI related modules mostly so i migrated its stuff to our UI repo and hence deleted that extensions too!

**Comment by ckt114** [comment]
Got it. Thanks.
