### ISSUE TITLE
after clean install nvim (due to ui change), pressing <ESC> in telescope interface will get errors

### ISSUE THREAD

**Issue by xarthurx** [siduck76/NvChad#2294]
**Describe the bug**
I clean installed the nvim after the change in the `ui` package.
https://github.com/NvChad/NvChad/issues/2293

Then when using telescope, pressing <ESC> in the TL interface will get:

![image](https://github.com/NvChad/NvChad/assets/1921878/81fba67a-74b4-4392-aba8-fcd2a05ff625)

**Expected behavior**
telescope interface will disappear and go back to editor UI.

**Desktop (please complete the following information):**
 - Operating System: Windows
 - Terminal: Neovide

**Comment by xarthurx** [comment]
OK, not only pressing <ESC>, but also selecting anything from Telescope.

Telescope is not usable due to this issue, and I need to close NVIM every if I accidentally open a TL interface.

**Comment by xarthurx** [comment]
It seems the path is messed up. Compared with the screenshot above, it concatenate the current path with t he `nvim-data` path somehow...

![image](https://github.com/NvChad/NvChad/assets/1921878/a9cc9cb7-ed6b-41a6-92a8-9d3a49d41d9a)

**Comment by siduck** [comment]
those errors arent even nvchad related. check your telescope config!

**Comment by xarthurx** [comment]
> those errors arent even nvchad related. check your telescope config!

I never changed my telescope config.
Yesterday everything was fine. This morning, ui have problems, so I searched the issues and found your update. So I clean installed nvchad, then the error comes out...

**Comment by xarthurx** [comment]
I don't have any modification on telescope outside nvchad's default settings.

**Comment by xarthurx** [comment]
https://www.reddit.com/r/neovim/comments/v6towp/telescope_tries_to_create_cc_folder/
I think this is the same issue, when enabling `telescope history` but without the folder created, the path get messed up.

**Comment by siduck** [comment]
did u try 

rm -rf .local/share/nvim && rm -rf .local/state/nvim

**Comment by xarthurx** [comment]
> did u try
> 
> rm -rf .local/share/nvim && rm -rf .local/state/nvim

I'm on Windows. by "clean install", both `nvim` and `nvim-data` was removed.
