### ISSUE TITLE
NvChad/Extension Repository

### ISSUE THREAD

**Issue by msMatix** [siduck76/NvChad#2295]
Hi :),
I just wanted to update my packages (PackerSync) and saw that the update for NvChad/Extensions failed. After searching further, I saw that the repository no longer exists. Was the module already no longer needed, because it is still listed as a plugin in the init.lua.

**Comment by siduck** [comment]
@msMatix modules in it were mostly UI related, so i moved it to the UI Repo :)

**Comment by msMatix** [comment]
Ah!
Thank you for the Reply! :)
