### ISSUE TITLE
failed ui updated

### ISSUE THREAD

**Issue by dattienle2573** [siduck76/NvChad#2297]
**Describe the bug**
I tried to update nvchad and got this error

**To Reproduce**
Update nvchad

**Expected behavior**
All plugins update successfully

**Screenshots**
<img width="548" alt="image" src="https://github.com/NvChad/NvChad/assets/140530253/e255feae-6f44-4c33-84fc-5f817cbc80ce">

**Desktop (please complete the following information):**
 - Operating System: macos
 - Terminal: kitty
 - Version of Neovim: 0.9.1

**Additional context**

**Comment by siduck** [comment]
rm -rf .local/share/nvim/ui && nvim

**Comment by zoomido** [comment]
Same problem for me.
Tried `rm -rf **~/**.local/share/nvim/ui && nvim` then I tried both NvChadUpdate and Lazy Install & Lazy Update but it all ends with the same error. Don't know if it should be back but the ui folder is not there after running nvchadupdate or lazy install.
`Failed (1)
     ui 1.17ms  start
        fatal: not a git repository: nvchad_types/../.git/modules/nvchad_types`
<img width="789" alt="image" src="https://github.com/NvChad/NvChad/assets/35059247/e36b9b82-3e25-43b3-8234-85db929dbe04">

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/8298f851-4ec9-46f0-a381-9d4fe138fe87

@zoomido please rm -rf properly `rm -rf  ~/.local/share/nvim/ui`

**Comment by zoomido** [comment]
After removing `~/.local/share/nvim` and `~/.local/state/nvim` and installing everything from scratch it seems to work again!
