### ISSUE TITLE
Nerd Fonts v3.0.0 changed codepoint for telescope search icon

### ISSUE THREAD

**Issue by pvbaudin** [siduck76/NvChad#2305]
From nerdfonts.com `With Release v3.0.0 the Material Design Icons were updated and moved to new codepoints (reasons for that are in the release notes).`

The magnifying glass icon used in telescope search had it's codepoint moved from 0xf848 to 0xf039

**To Reproduce**
1. Update Nerd Font to latest release
2. Open Telescope

**Expected behavior**
See telescope search bar with a magnifying glass glyph

**Desktop:**
 - macOS 13.1
 - iTerm2 3.4.4
 - nvim v0.9.1

**Additional context**
Fix is a simple change in telescope.lua, submitting PR

**Comment by siduck** [comment]
we're using fa-search

![image](https://github.com/NvChad/NvChad/assets/59060246/316b9f82-ca8a-4c3d-bcd6-2d58b70ad163)


so please use another terminal or override that icon in telescope config. ive seen that only iterm has this issue
