### ISSUE TITLE
getting semanticTokenPrivider (a nil value)

### ISSUE THREAD

**Issue by nithin-raj-9100** [siduck76/NvChad#2307]
### After not opening neovim for 2 days i got this error hence i did NvChadUpdate

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/75822901/f5f61346-802b-4d8e-bc6b-06eab905523b)

### Neither did i install any plugin nor make customization

 - Operating System wsl2 Ubuntu 22.04.2 LTS
 - Terminal zsh
 - Version of Neovim 0.9.1

**Comment by siduck** [comment]
not a nvchad issue, this issue's pretty random.
