### ISSUE TITLE
Cannot focus on the `nvchadUpdate` window

### ISSUE THREAD

**Issue by xarthurx** [siduck76/NvChad#2313]
**Describe the bug**
I'm not sure if this is a `nvchad` bug or a nvim bug in general.

On windows, if I do `nvchadUpdate` after start up, and click on another window, when trying to focus back on nvchad, the cursor can only focus on the edit window under the "update popup", but cannot focus on the update window.

Using telescope buffer selection is also not working, as the pop-up window is not a selectable buffer.

As a result, I need to close the whole nvim, and re-start it again.

**To Reproduce**
1. start nvim on Windows
2. run `nvchadUpdate`
3. mouse-click on some other window
4. click back on nvim and trying to close the update window

**Expected behavior**
the update window can be closed correctly

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/1921878/a7b1877f-36e1-412a-8d75-403d14d2dfe5)

**Desktop (please complete the following information):**
 - Operating System: Windows
 - Terminal: neovide

**Comment by siduck** [comment]
c-jkl wont work for focusing floating window, i do it by mouse, idk other mappings or commands that let you focus a floating window. not a nvchad issue

if you want to focus nvchad's update window,then try the combination of c-hjkl mapping, idk about the lazy.nvim window

**Comment by xarthurx** [comment]
> c-jkl wont work for focusing floating window, i do it by mouse, idk other mappings or commands that let you focus a floating window. not a nvchad issue
> 
> if you want to focus nvchad's update window,then try the combination of c-hjkl mapping, idk about the lazy.nvim window

Mouse click on windows don't work either...

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/cb227904-a9bf-4171-910c-447fe2745762

works fine here

**Comment by xarthurx** [comment]
sorry, I meant on “Windows OS”…

**Comment by siduck** [comment]
why does this have to do anything with windows? does your terminal support mouse properly

**Comment by xarthurx** [comment]
> why does this have to do anything with windows? does your terminal support mouse properly

Because I use neovide GUI, not terminal.

In terminal, it works fine.

**Comment by xarthurx** [comment]
> > why does this have to do anything with windows? does your terminal support mouse properly
> 
> Because I use neovide GUI, not terminal.
> 
> In terminal, it works fine.

OK, this is a neovide bug. I just tested `nvim-qt`, and it works fine.
