### ISSUE TITLE
set relative number in NvChad

### ISSUE THREAD

**Issue by solankybasant** [siduck76/NvChad#2314]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by 0xwagmi** [comment]
`SPACE` + `R` + ` N `

**Comment by siduck** [comment]
please add its option in custom init.lua

**Comment by solankybasant** [comment]
Thanks NvChad/NvChad
