### ISSUE TITLE
Udpate fails to communicate with yubikey agent

### ISSUE THREAD

**Issue by Skarlso** [siduck76/NvChad#2322]
**Describe the bug**

So, I have a yubikey that I'm using an SSH key and Git is configured to always re-write to ssh git.

With Packer and the likes, I didn't have any problem at all when updating.

But with nvchad, I can't seem to update.

No idea what's wrong, honestly.

<img width="1503" alt="Screenshot 2023-08-21 at 12 38 14" src="https://github.com/NvChad/NvChad/assets/182850/94b4a5c5-1c04-42b9-bfee-c8945e831fd8">

```
Total: 30 plugins

  Failed (8)
     cmp-buffer   nvim-cmp
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     cmp-nvim-lua   nvim-cmp
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     lazy.nvim 6.19ms   init.lua
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     mason.nvim 2.92ms   Lazy load
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     null-ls.nvim  go
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     nvim-autopairs   nvim-cmp
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     nvim-colorizer.lua 
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
     which-key.nvim   <leader> " ' ` c v g
        sign_and_send_pubkey: signing failed for RSA "cardno:9_074_138" from agent: communication with agent failed
        git@github.com: Permission denied (publickey).
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.

```

**To Reproduce**
1. Have yubikey setup
2. ssh-agent is changed to gpg-agent.
git config:

```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
[url "git@github.com:"]
	insteadOf = https://github.com/
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 OSX
 - Terminal
iTerm
 - Version of Neovim
0.9.1

**Additional context**

**Comment by Skarlso** [comment]
The interesting part is that it worked when I was first installing nvchad. What I did is, I removed the yubikey and put it back in. So it prompter for the PIN and after that it worked. This trick doesn't seem to be working while updating. :/

**Comment by Skarlso** [comment]
So it appears to be only for _some_ of the repos? 🤔 

![Screenshot 2023-08-21 at 13 08 00](https://github.com/NvChad/NvChad/assets/182850/9288c245-258c-4c54-bde3-cb0eeb0feeed)

**Comment by Skarlso** [comment]
Nope, those repos failed. Interesting that it says up to date if that happens.

**Comment by siduck** [comment]
its lazy.nvim related, not nvchad! seems like your OS or system has some weird stuff going on, idk much so cant help. please ask on lazy.nvim repo

**Comment by siduck** [comment]
and 
![image](https://github.com/NvChad/NvChad/assets/59060246/871c0eb8-4674-4057-9c9b-693d399b51e9)

wouldnt this need you permissions on those repos? 

please remove your ssh stuff and recheck

**Comment by Skarlso** [comment]
I can ask them, sure. My ssh stuff works fine with other updating software. But I can try nevertheless.

**Comment by Skarlso** [comment]
It, indeed, worked without the SSH redirect.

**Comment by Skarlso** [comment]
For the record, a friend of mine has the same rewrite in gitconfig and it works fine. I think it's just a problem with communicating with the card, not the SSH part. Anyways, it works for now so I'm good. Thanks.
