### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by krtffl** [siduck76/NvChad#2324]
**Describe the bug**

When running :NvChadUpdate, extensions fails with the following message
`fatal: could not read Username: terminal prompts disabled`

**To Reproduce**
1. Open nvim
2. Run `:NvChadUpdate`

**Expected behavior**
It should update without issues

**Desktop (please complete the following information):**
 - Operating System -> macOS Monterey 12.6.7
 - Terminal -> iTerm 3.4.20
 - Version of Neovim -> 0.9.1

**Additional context**
After that I'm getting further errors, not sure if related to this update or not. 

```
^Ino field package.preload['nvchad_ui']
cache_loader: module nvchad_ui not found
cache_loader_lib: module nvchad_ui not found
^Ino file './nvchad_ui.lua'
^Ino file '/usr/local/share/luajit-2.1.0-beta3/nvchad_ui.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui.lua'
^Ino file '/usr/local/share/lua/5.1/nvchad_ui/init.lua'
^Ino file './nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/nvchad_ui.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```
```

# stacktrace:
  - ~/.config/nvim/lua/plugins/init.lua:23 _in_ **config**
  - ~/.config/nvim/lua/plugins/init.lua:279
  - ~/.config/nvim/init.lua:21
```

**Comment by krtffl** [comment]
Seems it is not happening anymore after uninstalling and installing back again.

**Comment by siduck** [comment]
@krtffl please do a git pull in the nvim config path
