### ISSUE TITLE
Tabufline nvimtree spacing

### ISSUE THREAD

**Issue by itamarsch** [siduck76/NvChad#2327]
When nvimtree is set to be on the right, tabs are spaced on the left with nothing there

**To Reproduce**
```lua
M.nvimtree = {
  view = {
    side = "right"
  },
}

```

**Expected behavior**
No spacing should occur if the tree is on the right side

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/71348842/105d7ad1-0219-4d18-a465-691393e206e0)
![image](https://github.com/NvChad/NvChad/assets/71348842/21aaee1d-66f8-4bdc-9c81-19cf3c02c3b6)

**Desktop (please complete the following information):**
 - Fedora 38
 - Gnome terminal
 - lts

**Comment by siduck** [comment]
@itamarsch override tabufline modules

```lua
tabufline = {
   overriden_modules = function(modules)
           modules[#modules+1] = modules[1]
           table.remove(modules,1)
   end
}
```
