### ISSUE TITLE
Cannot add cmp mappings in custom config

### ISSUE THREAD

**Issue by K0max** [siduck76/NvChad#2332]
**Describe the bug**
I added following contents to /lua/custom/configs/overrides.lua but it didn't work. Instead, **all** A-x keybinds have strange effects except A-i, A-v, A-h (already defined in /lua/core/mappings.lua).
```
local cmp = require "cmp"
M.cmp_mappings = {
  mapping = {
    ["<A-w>"] = cmp.mapping.select_prev_item(),
    ["<A-s>"] = cmp.mapping.select_next_item(),
    ["<A-d>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif require("luasnip").expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
    ["<A-a>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif require("luasnip").jumpable(-1) then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
      else
        fallback()
      end
    end, {
      "i",
      "s",
    }),
  },
}
```

**To Reproduce**
Go to .config/nvim/lua/custom/configs/overrides, and add the codes above

**Expected behavior**
I want to get the same outcome like Ctrl-N and Ctrl-P when I press A-s and A-w. And use A-d and A-a to replace Tab and S-Tab.
However, A-s will backspace, A-w will return to normal mode. A-d and A-a will not jump and will return to normal mode.

**Screenshots**

https://github.com/NvChad/NvChad/assets/100927897/4f138fd6-046e-422e-b0bf-c1c21e60f3c2

https://github.com/NvChad/NvChad/assets/100927897/b61a7a2c-c6dc-41ea-9ee4-22b4ba8b0d08

**Desktop (please complete the following information):**
 - Operating System: Arch Linux and Windows
 - Terminal: Kitty and WIndows Terminal
 - Version of Neovim: 0.9.0 and 0.10.0

**Additional context**
I also want to know where A-x was defined? I searched all files in ~/.config/nvim/ but found none of them contain A-x. (x means w,a,s,d etc.)

**Comment by siduck** [comment]
dont add it in overrides please, you're doing it the wrong way. Just override the default cmp config table in the opts function and then return it

**Comment by siduck** [comment]
```lua
 {
    "hrsh7th/nvim-cmp",
    opts = function()
      local cmp_conf = require "plugins.configs.cmp"
      table.insert(cmp_conf.sources, { name = "blabla" })

      return cmp_conf
    end,
  },
 ```
 
  this is an example to edit the sources of cmp config with opts function itself
