### ISSUE TITLE
Error on startup after computer updates

### ISSUE THREAD

**Issue by CaldwellYSR** [siduck76/NvChad#2333]
**Describe the bug**
Yesterday my computer ran a bunch of updates, probably updated vim as a result. Ever since those updates I get the following error on nvchad startup. I have gone through and done an NvChadUpdate, Lazy Update, and pulled the latest changes from the git repo to no avail. There were some errors in my custom config related to `tabufline` being imported incorrectly in my keymappings but I fixed those. This startup error is the one I can't seem to get fixed and it is coming from the core files.

```
Error executing vim.schedule lua callback: vim/keymap.lua:0: Invalid 'desc': Expected Lua string                                                                              
stack traceback:                                                                                                                                                              
        [C]: in function 'nvim_set_keymap'                                                                                                                                    
        vim/keymap.lua: in function 'set'                                                                                                                                     
        /home/user/.config/nvim/lua/core/utils.lua:72: in function 'set_section_map'                                                                                   
        /home/user/.config/nvim/lua/core/utils.lua:85: in function </home/user/.config/nvim/lua/core/utils.lua:55>  
```

**Desktop (please complete the following information):**
 - Operating System - Ubuntu 20.04.6 LTS
 - Terminal
 - Version of Neovim - 
 ```
 NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

**Comment by siduck** [comment]
your custom mappings  ( one of them probably ) has incorrect description. fix that

**Comment by CaldwellYSR** [comment]
Oh wow you're right. I was missing a description on one of the mappings. I was searching my mappings for `desc` thinking it was saying "Descending" not "Description". Thanks for the help. Wish the stacktrace had one of my files in it. I assumed since the stacktrace was all core files that it wasn't an error on my end.
