### ISSUE TITLE
Empty Icon when I resize terminal

### ISSUE THREAD

**Issue by dhia-gharsallaoui** [siduck76/NvChad#2334]
**Describe the bug**
Icons become blank when I zoom in using the resize-font functionality in urxvt.

**To Reproduce**
1- Open urxvt terminal.
2- Open Neovim in the terminal.
3- Zoom in using the resize-font functionality (e.g., by pressing Ctrl + +).
4- Observe icons displayed in Neovim, such as those used by plugins or syntax highlighting.

**Expected behavior**
Icons within Neovim should remain visible and properly rendered even when zooming in using the resize-font functionality. 

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/74959435/11864413-40d6-46d9-9bee-fd8d480424e7)

Zoom:
![image](https://github.com/NvChad/NvChad/assets/74959435/e3b6c1ea-f32f-4fb4-89f8-fc24dc41d460)

**Desktop (please complete the following information):**
 - Operating System: Fedorea 38
 - Terminal: rxvt-unicode (urxvt) v9.31 
 - Version of Neovim: v0.9.1

**Comment by siduck** [comment]
your terminal issue, not nvchad. use a better terminal like alacritty kitty etc
