### ISSUE TITLE
nvchad failing to work when installed on macos

### ISSUE THREAD

**Issue by SystemAdmin12345** [siduck76/NvChad#2337]
**Describe the bug**
This bug prevents nvchad from working when installing nvchad onto neovim.

**To Reproduce**
1. Install Neovim and the neovim & nvchad dependencies with a package manager.
2. Run this command in terminal to install nvchad
`git clone [https://github.com/NvChad/NvChad](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbF9aYzJwY1Itc2lqMUZRSHVPd0hNOTNFT0NOUXxBQ3Jtc0trWmZlUUVLaHEzeVpIaUVNaUs5bk56dGY3ejZvdkdEa29yZUlCT0plYUMzVFFaSklsUGtUblFBM2U3Mko4ZzFGdHZqM0lSU0V3VmJQYW5DbDgydG9kWUtHdjB1bFhGS1ljNW9EaEV2cjFreUIzZzEzcw&q=https%3A%2F%2Fgithub.com%2FNvChad%2FNvChad&v=Mtgo-nP_r8Y) ~/.config/nvim --depth 1 && nvim`
3. Respond with either yes or no with example config
4. See the error with base46 theme
Extra: If you installed nvchad, got an error then exited and re-enter neovim, the error appears

**Expected behavior**
NVchad installed and running completely fine when putting in "nvim" to launch Neovim

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/102834957/f26b4fb6-9d2b-47b9-87f6-78b42851ab59)

**Desktop (please complete the following information):**
 - Operating System: MacOS ventura
 - Terminal: Default MacOS terminal (zsh)
 - Version of Neovim: NVIM v0.9.1

**Additional context**
I installed all the necessary dependencies and requirements for neovim, NvChad and dependences of neovim and nvchad with a package manager (used both homebrew and macports), have git installed and installed neovim + nvchad giving an error. 

*Error*
  Compiling base46 theme to bytecode ...
Error detected while processing /Users/nikolaygavrilyuk/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/nikolaygavrilyuk/.config/nvim/lua/c
ore/bootstrap.lua:10: External call failed with error code: 128
fatal: destination path '/Users/nikolaygavrilyuk/.local/share/nvim/lazy/base46' 
already exists and is not an empty directory.

stack traceback:
        [C]: in function 'assert'
        /Users/nikolaygavrilyuk/.config/nvim/lua/core/bootstrap.lua:10: in funct
ion 'shell_call'
        /Users/nikolaygavrilyuk/.config/nvim/lua/core/bootstrap.lua:20: in funct
ion 'lazy'
        /Users/nikolaygavrilyuk/.config/nvim/init.lua:16: in main chunk
Press ENTER or type command to continue

**Comment by siduck** [comment]
please delete old nvim dirs

**Comment by SystemAdmin12345** [comment]
I tried erasing config

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/a681fadc-4c26-48d6-8493-1b3a54f7ee62)

this error is clear

rm -rf .local/share/nvim
then install nvchad
