### ISSUE TITLE
NvimPacker theme issue with nvim-base16

### ISSUE THREAD

**Issue by CTZxVULKAN** [siduck76/NvChad#234]
I ran a `:PackerSync` followed by a restart after which my Neovim broke.

I am presented with the following issue 
```
packer.nvim: Error running config for nvim-base16.lua: /home/vulkan/.config/nvim/lua/theme.lua:6 attept to index field  'themes' (a function value)
```

This is my `theme.lua`

```lua
vim.g.nvchad_theme = "onedark"

local present, base16 = pcall(require, "base16")

if present then
    base16(base16.themes["onedark"], true)  <--line 6
    require "highlights"
    return true
else
    return false
end
```

Additional Notes : 
My config was based off the previous version of NvChad ( the one before the theme selector with telescope was added) and i never updated my installation base and just changed minor stuff in the config.

I know little to none lua and i would love any help in this matter.
Thankyou

**Comment by JustSage** [comment]
Change the brackets when calling themes to parentheses. `[` -> `(`.
Need to do the same in the theme switcher extension file if you use it.

**Comment by Akianonymus** [comment]
how about updating the config from main repo ? lol

**Comment by CTZxVULKAN** [comment]
@JustSage  i changed the parentheses. from `[` to ` (` .
Now everything is fine. 
Could you please explain why such an issue occured (it was fine earlier) ?

**Comment by CTZxVULKAN** [comment]
> how about updating the config from main repo ? lol

@Akianonymus  i have no reason to update with the main repo ( there was no new feature included which i would use that was included the last pull request  ). 
Nvchad is very suckless i just installed the base and kept adding my custom configs over it.

**Comment by CTZxVULKAN** [comment]
> > @JustSage i changed the parentheses. from `[` to ` (` .
> > Now everything is fine.
> > Could you please explain why such an issue occured (it was fine earlier) ?
> 
> Since NvChad relies on @siduck76 fork of base16, doing `:PackerSync` automatically updates base16.
> Recently it had syntax changes that were affecting a couple of NvChad files.

@JustSage  I see thank you for the quick help it was really cool man :) (even my mum doesnt reply that fast )

**Comment by JustSage** [comment]
> > > @JustSage i changed the parentheses. from `[` to ` (` .
> > > Now everything is fine.
> > > Could you please explain why such an issue occured (it was fine earlier) ?
> > 
> > 
> > Since NvChad relies on @siduck76 fork of base16, doing `:PackerSync` automatically updates base16.
> > Recently it had syntax changes that were affecting a couple of NvChad files.
> 
> @JustSage I see thank you for the quick help it was really cool man :) (even my mum doesnt reply that fast )

Just happened to be around :).
