### ISSUE TITLE
Having problem while cloning extensions.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2340]
Assalamu Alaikum, I while setting up neovim with NvChad I got this error:

``` bash
    extensions 
        Cloning into '/home/USER/.local/share/nvim/lazy/extensions'...
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
Is it a problem with github? 
How do I fix it?

Thanks!

**Comment by siduck** [comment]
@MubinMuhammad that repo doesnt exist anymore, update nvchad config
