### ISSUE TITLE
:Tutor missing in NVChad

### ISSUE THREAD

**Issue by d13g0** [siduck76/NvChad#2343]
**Describe the bug**
`:Tutor` not available in NVChad

**To Reproduce**
1. Open nvim
2. `:Tutor`
3. See error `E492: Not an editor command: Tutor`

**Expected behavior**
show the tutorial

**Desktop (please complete the following information):**
 - Operating System MacOS
 - Terminal zsh
 - Version of Neovim 0.9.1

**Additional context**
The tutorial works if I do `nvim --clean`

**Comment by siduck** [comment]
its disabled by default in nvchad, just try nvim --clean

**Comment by d13g0** [comment]
Hi @siduck any reason for disabling it?

**Comment by siduck** [comment]
@d13g0 once you use nvim for some weeks, you dont need Tutor anymore. and it's a startup plugin so disabling it might save some very little time :grin:

**Comment by d13g0** [comment]
hey @siduck thanks for your reply. May I suggest then an update to the NvChad docs?

https://nvchad.com/docs/quickstart/post-install

I was checking and I saw the `Vim Tutor` so perhaps updating there to would help more people not run into this issue.
