### ISSUE TITLE
NvChad v2.0 Statusline with nvim-navic

### ISSUE THREAD

**Issue by LSleutsky** [siduck76/NvChad#2344]
**Describe the bug**
I am trying to get the v2.0 flavor of NvChad to work with the [`nvim-navic`](https://github.com/SmiteshP/nvim-navic) plugin. I came across and tried to implement logic from [this commit comment](https://github.com/NvChad/NvChad/commit/cd5d85a11b5eecaf12d9a9f420e8924ed6a214d7#commitcomment-77606986), as well as [this gist](https://gist.github.com/siduck/8d6f892d282fb5cbdf4cf623dd50b481), but have had no luck.

The latter gist's logic is not fully correct, as there is a missing `end` statement, so a direct copy and paste does not work, and when typing out the logic manually, to make sure all code blocks are properly modularized and closed, I get an error message of `Annotations specify that at least 0 return value(s) are required, found 1 returned here instead`, pointing to the `return` statement, so I can't get anywhere past that.

The commit comment seems to be outdated for v2.0 as well, since extrapolating that logic specific to `nvim-navic` does not yield any positive results. Can anyone point me in the right direction please...?

**To Reproduce**
1. Go to either [this commit comment](https://github.com/NvChad/NvChad/commit/cd5d85a11b5eecaf12d9a9f420e8924ed6a214d7#commitcomment-77606986) or [this gist](https://gist.github.com/siduck/8d6f892d282fb5cbdf4cf623dd50b481), and try to implement statusline logic for `nvim-navic`.
2. Notice either errors provided by the LSP, or no resulting changes on the statusline.

**Expected behavior**
To see the `nvim-navic` plugin working properly, ideally tied into LSP like the above linked gist aims to provide.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: **`MacOS Ventura 13.4.1`**
 - Terminal: **`WezTerm (nightly)`**
 - Version of Neovim: **`NVIM v0.10.0-dev-962+g874b8172a`**

**Additional context**
Thanks for any assistance or guidance that anyone can provide...!

**Comment by siduck** [comment]
hi @LSleutsky  do a lazy sync cuz i added navic support for base46 and updated the gist, check it

**Comment by LSleutsky** [comment]
Thank you so much @siduck!! Works like a charm now...
