### ISSUE TITLE
Display issue on Mac

### ISSUE THREAD

**Issue by BrikeX** [siduck76/NvChad#2346]
Hi, I came across the same issue in:
https://stackoverflow.com/questions/76575345/nvchad-not-showing-colors-correctly-mac-os

The terminal cannot show the file totally.

Environment:
macOS Monterey
Version 12.6.6
Chip Apple M1

**Comment by siduck** [comment]
enable true color support in terminal please

**Comment by BrikeX** [comment]
> enable true color support in terminal please

Thanks. Everything is fine in iTerm2.
