### ISSUE TITLE
LSP Formatting Command Not Sending Request to Server in metals.nvim Integration

### ISSUE THREAD

**Issue by dhia-gharsallaoui** [siduck76/NvChad#2352]
**Describe the bug**
I'm adding the metals.nvim plugin to my nvchad configuration. I noticed that some LSP functions are not available, even though they are available on the server. After opening an issue on metals.nvim, we discovered that the request doesn't arrive at the server. You can find more details in this [issue](https://github.com/scalameta/nvim-metals/issues/601)

**Expected behavior**
When I run `lsp.format`, the command should be sent to the LSP server.

**Desktop:**
 - Operating System: Fedora38
 - Terminal: Alacritty
 - Version of Neovim: v0.9.1

Thank you!

**Comment by siduck** [comment]
in your custom lspconfig, make your own custom on_attach function instead of using the default one ( which doesnt has these 2 lines related to formatting )

https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/lspconfig.lua#L9

**Comment by ckipp01** [comment]
> in your custom lspconfig, make your own custom on_attach function instead of using the default one ( which doesnt has these 2 lines related to formatting )

Just to clarify here, nvim-metals does have some custom stuff related to the `on_attach`, but this has no effect on the passed in `capabilities`. Neovim itself is a formatting provider, so unless this is somehow being overwritten by NvChad, then this should still work as expected.

**Comment by siduck** [comment]
@ckipp01 nvchad disables every lsp's formatting capabilities in its on_attach function, so vim.lsp.buf.format() wont work normally. Because  i thought its better to define formatters in null-ls config or formatters.nvim etc

**Comment by ckipp01** [comment]
> @ckipp01 nvchad disables every lsp's formatting capabilities in its on_attach function, so vim.lsp.buf.format() wont work normally

The downside of this approach is that any server that provides formatting won't work out of the box and may cause confusion like you're seeing here. I think it might be better to not do this.

**Comment by siduck** [comment]
> > @ckipp01 nvchad disables every lsp's formatting capabilities in its on_attach function, so vim.lsp.buf.format() wont work normally
> 
> The downside of this approach is that any server that provides formatting won't work out of the box and may cause confusion like you're seeing here. I think it might be better to not do this.

yes I agree, but the majority of the nvchad users use null-ls. IF we remove that code and for example i had to use deno formatter for js files then i had to manually disable tsserver's formatting in my custom lspconfig, same with other lsps. that'd add some boilerplate code.

And it'd might be a breaking change for some  users, i  need to think thoroughly about this

**Comment by dhia-gharsallaoui** [comment]
> Because i thought its better to define formatters in null-ls config or formatters.nvim etc

null-ls is now [archived](https://github.com/jose-elias-alvarez/null-ls.nvim#archived)

**Comment by siduck** [comment]
> > Because i thought its better to define formatters in null-ls config or formatters.nvim etc
> 
> null-ls is now [archived](https://github.com/jose-elias-alvarez/null-ls.nvim#archived)

it still works tho, i'm pretty sure someone will fork it. Also there have been some neovim PRs lately that would let us do what null-ls does :thinking:

**Comment by yusufshalaby** [comment]
Ran into this with rust-tools + rust-analyzer. Just copied the the default on_attach and commented out those two lines because I wanted to keep all the key maps. It's working fine now but I was puzzled as to why it was set up like that. Thanks for the explanation.
