### ISSUE TITLE
clean install of nvim and nvchad throws error

### ISSUE THREAD

**Issue by AshutoshPatole** [siduck76/NvChad#2354]
**Describe the bug**
everytime I try to modify/add LSP, I get this error when I do MasonInstall. I have to remove ~/.local/share/nvim/lazy to make it work.

**To Reproduce**
```bash
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod +x nvim.appimage
rm -rf /usr/local/bin/vim

mv nvim.appimage /usr/local/bin/nvim
# Create symbolic link for easy access
ln -s /usr/local/bin/nvim /usr/local/bin/vim

git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1"
```

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/47964182/1878affc-3a01-4641-b8d5-859cf6fab0c1)

**Desktop (please complete the following information):**
 - Linux mint 22
 - Terminal
 - Neovim version 0.9.1 Release

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/1ba7f80f-2aa3-4f19-967c-549dd2b5136e

Unable to reproduce and the error itself is related to lazy.nvim

provide a video and delete all old nvim dirs  before installing
