### ISSUE TITLE
Statusline missing after terminal actions

### ISSUE THREAD

**Issue by ag-stanciu** [siduck76/NvChad#236]
**Describe the bug**
Opening a terminal split, or an action which involves a terminal (LspInstall), makes the statusline not show up after closing the terminal

**To Reproduce**
1. Fresh install
2. Open a terminal split
3. Close the terminal split
4. Statusline missing

**Expected behavior**
Statusline should show up after the terminal is closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1621729/129323455-cfc830d3-65f0-4c79-ad83-afaf241391ff.png)

**Desktop (please complete the following information):**
 - Operating System: MacOS 11.5.1
 - Terminal: Kitty 0.22.2
 - Version of Neovim : 0.5

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/issues/236

**Comment by siduck76** [comment]
@ag-stanciu  https://github.com/siduck76/NvChad/issues/236
