### ISSUE TITLE
Removing default mappings in the custom configuration

### ISSUE THREAD

**Issue by d13g0** [siduck76/NvChad#2364]
**Is your feature request related to a problem? Please describe.**
With NvChad it is easy to add new mappings or replace default mappings thanks to the table extension mechanism. However it's not clear to me how to remove mappings that won't have a replacement in the custom configuration. 

**Describe the solution you'd like**
An alternative to extending the table so it can be replaced in its totality instead of merging since this prevents the removal of default mappings.

**Describe alternatives you've considered**
Perhaps an alternative is to have an attribute for the mapping that we want to remove? Something like `mapping.remove = true` ?

**Additional context**
I am trying to remove the Telescope oldfiles mapping (I don't want `[leader]fo` for that).

**Comment by siduck** [comment]
https://nvchad.com/docs/config/mappings read whole of it

**Comment by d13g0** [comment]
Thanks @siduck I see you can disable them like this:

```
M.disabled = {
  n = {
      ["<leader>h"] = "",
      ["<C-a>"] = ""
  }
}
```
