### ISSUE TITLE
Suggestion: changing the default mapping for toggling the neovim tree

### ISSUE THREAD

**Issue by d13g0** [siduck76/NvChad#2365]
**Is your feature request related to a problem? Please describe.**

Not a problem but an opportunity to improve usability and increase user adoption.

In other neovim frameworks `<Leader>e` is used to toggle the neovim tree. In NvChad this is mapped to the focus action:

```
M.nvimtree = {
  plugin = true,

  n = {
    -- toggle
    ["<C-n>"] = { "<cmd> NvimTreeToggle <CR>", "Toggle nvimtree" },

    -- focus
    ["<leader>e"] = { "<cmd> NvimTreeFocus <CR>", "Focus nvimtree" },
  },
}

```

**Describe the solution you'd like**
I think a better default is to assign the toggle function to `<Leader>e`:
```
M.nvimtree = {
  plugin = true,

  n = {
    -- focus
    ["<C-n>"] = { "<cmd> NvimTreeFocus <CR>", "Go to File Tree" },
    -- toggle
    ["<leader>e"] = { "<cmd> NvimTreeToggle <CR>", "Toggle File Tree" },
  },
}
```

**Comment by siduck** [comment]
C-n is used by many neovim users iirc and changing this would be a breaking change which i dont want. You are free to do in your custom config
