### ISSUE TITLE
packer.nvim: Error running config for base46: [string "..."]:0: attempt to call field 'load_theme' (a nil value)

### ISSUE THREAD

**Issue by 8ullyMaguire** [siduck76/NvChad#2367]
**Describe the bug**
packer.nvim: Error running config for base46: [string "..."]:0: attempt to call field 'load_theme' (a nil value)

**To Reproduce**
I've just deleted my nvim config directory and cloned it again.
```
cd ~/.config/dotfiles/config && rm -rf nvim && git clone https://github.com/NvChad/NvChad --depth=1 nvim && chmod -R 755 nvim
```
I have a symlink `/home/user/.config/nvim` pointing to that folder so everything should be working the same, but I get the error above.

**Desktop (please complete the following information):**
 - Manjaro Linux
 - Alacritty
```
❯ nvim -v
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck** [comment]
rm -rf .local/share/nvim

then install nvchad
