### ISSUE TITLE
Pre-requisites

### ISSUE THREAD

**Issue by 9i5BCrUcNX5NmT** [siduck76/NvChad#2372]
**Describe the bug**
On my new void Linux I can't install NvChad.

**To Reproduce**
1. Setup void Linux
2. Go to https://nvchad.com/docs/quickstart/install
3. Install Pre-requisites
4. Run: "git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && neovim"
5. Press y to install example custom config
6. Mason can't work

**After a day of reflection**
Please add Requirements from https://github.com/williamboman/mason.neovim to NvChad requirements.

**Comment by siduck** [comment]
most distros have that package, void tries to be too minimal so its upto you. And mason isnt an optional plugin in nvchad, not something which will obstruct your workflow if it doesnt work
