### ISSUE TITLE
telescope-fzf-native.nvim incorrect build target

### ISSUE THREAD

**Issue by mvds314** [siduck76/NvChad#2374]
**Describe the bug**
telescope-fzf-native cannot be compiled under Windows.

**Cause**

init.lua has{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" } 

But should read something like this (according to the telescope nvim github) as Windows uses cmake instead of make.
 { "nvim-telescope/telescope-fzf-native.nvim", build = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build" } 

**To Reproduce**
Update NvChad under windows

**Desktop (please complete the following information):**
Windows 11

**Comment by siduck** [comment]
ugh :/ 

@kayuxx

**Comment by siduck** [comment]
this is why i didnt wanted to add that plugin, such a long build command. reverting now

**Comment by siduck** [comment]
but wait, your windows doesnt have mingw?

![image](https://github.com/NvChad/NvChad/assets/59060246/3dd890e9-f964-4875-bf7e-190455cbe5d8)

**Comment by mvds314** [comment]
Yes, I installed mingw64. But then you get cmake instead of make.

Not sure where you got the above screenshot from, but this is where I got the cmake instructions from:
[https://github.com/nvim-telescope/telescope-fzf-native.nvim)](https://github.com/nvim-telescope/telescope-fzf-native.nvim)

**Comment by siduck** [comment]
@mvds314 read the make section below the cmake section

**Comment by georgejean** [comment]
@mvds314
I've used this link (using cmake manually) :
[https://www.cnblogs.com/Searchor/p/17280268.html](https://www.cnblogs.com/Searchor/p/17280268.html)
with powershell :
```powershell
cd (join-path $env:LOCALAPPDATA nvim-data\lazy\telescope-fzf-native.nvim)
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
cmake --install build --prefix build
```
It has worked for me.

**Comment by kayuxx** [comment]
@mvds314 I already mentioned that the extension required `make` to get it to work, I see that ur using Windows so you should know that nvchad required `MinGW` and `gcc`, so now you just have to install `make` with ur package manager, same thing for `cmake` if you want to work with it go to the plugins file and override that dependency.
