### ISSUE TITLE
How to set folder and file icon in NerdTree

### ISSUE THREAD

**Issue by solankybasant** [siduck76/NvChad#2375]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem was.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
@solankybasant  override nvimtree opts

**Comment by siduck** [comment]
please check the default nvimtree config in nvchad
