### ISSUE TITLE
Highlight definition not working with treesitter.

### ISSUE THREAD

**Issue by LinuxIsCool** [siduck76/NvChad#2381]
I can't get highlight definition working. 

I even tried using https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/master/README.md and I can't get highlight definition working. 

I did get highlight definition working from installing this: https://github.com/tzachar/local-highlight.nvim 

^^ But that one is really slow the lag is frustrating.

I am not overriding the defaults from `plugins/configs/treestitter.lua`:
```lua
local options = {
  ensure_installed = { "lua" },

  highlight = {
    enable = true,
    use_languagetree = true,
  },

  indent = { enable = true },
}

return options
```

**Comment by siduck** [comment]
where did   you install treesitter refactor? nowhere.

please install it and override treesitter opts https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/master/README.md#highlight-definitions
