### ISSUE TITLE
Integration of telescope-fzf-native

### ISSUE THREAD

**Issue by xarthurx** [siduck76/NvChad#2383]
**Is your feature request related to a problem? Please describe.**
A recent update of `telescope` installed `telescope-fzf-native` by default.
https://github.com/nvim-telescope/telescope-fzf-native.nvim

However, the default settings using `make` for the build instead of `cmake` -- creating some issues / errors on Windows platform.
Since `telescope` is set up by default with `nvchad`, could `nvchad` provides auto detection/change with different settings (provided on the plugin README)?

**Describe the solution you'd like**
Auto switch settings of `telescope-fzf-native` based on platform.

**Describe alternatives you've considered**
User add the plugin to their plugin list manually.

**Comment by siduck** [comment]
@xarthurx please install mingw on  your system

**Comment by xarthurx** [comment]
> @xarthurx please install mingw on your system

I actually can install `make` with `scoop`. The suggestion is for general Windows users. And they DO provide a `cmake` option for Windows users.

Nowadays, the dev env on Windows is quite complete and `cygwin` or `mingw` is not needed 99% of the time.

**Comment by siduck** [comment]
@xarthurx 

```lua
 { 
    "telescoep fzf blabla" , build =" cmake stuff here " 
  }
  ```
  
  put that in custom plugins

**Comment by xarthurx** [comment]
> @xarthurx
> 
> ```lua
>  { 
>     "telescoep fzf blabla" , build =" cmake stuff here " 
>   }
> ```
> 
> put that in custom plugins

Yes, I did that.
I started this just to see if you'd like to added it by default, since `telescope` is a `inbuilt` feature. 
Closing this issue.

**Comment by siduck** [comment]
make is available on all unix sytems where as CMAKE isnt, thats why I used make to build that plugin, if you have mingw etc then make would be available for you too ( as per telesocpe fzf readme )
