### ISSUE TITLE
Error detected while processing

### ISSUE THREAD

**Issue by Yajanth** [siduck76/NvChad#2386]
Error detected while processing /home/shera/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/shera/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/shera/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/shera/.config/nvim/init.lua:1: in main chunk

**Comment by Joematpal** [comment]
I got that too. I found this... https://guidefari.com/autocmd-nil-value/

install neovim via curl as an appimage.

**Comment by siduck** [comment]
please install neovim v0.9
