### ISSUE TITLE
`indentexpr` not getting overriden despite being set in `custom/init.lua`

### ISSUE THREAD

**Issue by ElSamhaa** [siduck76/NvChad#2387]
**Describe the bug**
I'm annoyed by the behavior where whenever I comment a line, it gets auto-shifted to the right. Upon investigating this, I found that the vim option `indentexpr` controls this. Tried overriding it in `custom/init.lua` but that doesn't have any effect unfortunately.

**To Reproduce**
1. Add any of the following to `custom/initlua`
```vim.cmd('set indentexpr=')
vim.opt.indentexpr = ""
vim.o.indentexpr = ""
vim.go.indentexpr = ""
```
2. Open a yaml file for example
3. Add a hash character before the first character of one of the indented lines
4. The line gets shifted to the right
5. Run `set indentexpr` in my case it returns `indentexpr=GetYAMLIndent(v:lnum)`

**Expected behavior**
The `custom/init.lua` should take precedence over other plugin configrations

**Screenshots**
<img width="437" alt="image" src="https://github.com/NvChad/NvChad/assets/34912861/f7c879cb-8505-4ff7-9fc1-d33f0ec4e6ec">

<img width="565" alt="image" src="https://github.com/NvChad/NvChad/assets/34912861/5c077112-0898-4574-b85b-5688a8c681a9">

**Desktop (please complete the following information):**
 - MacOS
 - Alacritty
 - NVIM v0.9.2

**Additional context**
I've tried appending the location of a another lua script to the `rtp` to override whatever resets this options, but it just doesn't work either.

**Comment by siduck** [comment]
this is not a nvchad issue. that option is being set by treesitter, either reset it after treesitter probably or filetype autocmd etc

**Comment by siduck** [comment]
```lua
local autocmd = vim.api.nvim_create_autocmd

autocmd("FileType", {
  callback = function()
    vim.schedule(function()
      vim.opt.indentexpr = ""
    end)
  end,
})
```

**Comment by ElSamhaa** [comment]
Thanks @siduck . Can I suggest adding a config file that loads after all other scripts/configurations? Also, do you have any insights on why appending to the `rtp` doesn't work?

**Comment by siduck** [comment]
@ElSamhaa try a minimal neovim config like https://github.com/NvChad/basic-config and check if the rtp stuff works there. 

I'm assuming the  rtp stuff doesnt work cuz treesitter's overriding the indentexpr, thats why I added the vim.schedule stuff in the . One thing you could do is disable indent option in treesitter config

Also just tried nvim --clean and checked indentexpr of a lua file, it wasnt empty. So im pretty sure there's  a better way to override this, ask on r/neovim

**Comment by ElSamhaa** [comment]
Thank you very much. And nice work btw :)

**Comment by siduck** [comment]
> Thank you very much. And nice work btw :)

alhamdullillah :point_up:
