### ISSUE TITLE
Fresh NvChad config (plus clang lsp), catppuccin correct color palette but wrong semantic application of the colors.

### ISSUE THREAD

**Issue by LarssonMartin1998** [siduck76/NvChad#2389]
**Describe the bug**
catppuccin semantics highlighting in C++(might be more languages, only tested with C++) doesn’t look right despite what looks like correct semantics when inspecting everything. "type: (primitive_type)" is colored as pastel yellow when it's supposed to be colored as pastel purple (same as "return statement" or "using declaration"). Parenthesis and brackets are red and lots more. I've included a screenshot below which compares CLion (left and correct) with Neovim (right and incorrect).

**To Reproduce**
Set up clangd LSP for C++ in base NvChad, change to catppuccin and compare the highlighting to what it looks like in Rider/CLion and VSCode.

**Expected behavior**
Expected behaviour is that with working semantics it should look like CLion/Rider/VScode. The theme in Neovim has the correct color palette but applied to the wrong things.

**Screenshots**
![Screenshot 2023-09-14 at 18 26 50](https://github.com/NvChad/NvChad/assets/35811847/7bcd5797-a026-446b-ac01-a9ffce62ed88)

**Desktop (please complete the following information):**
 - MacOS
 - Warp / Kitty
 - 0.9.2

**Comment by siduck** [comment]
nvchad's catpucin is the modified version of old cattpuccin theme so new cattpuccin theme wont match for sure
