### ISSUE TITLE
status line disappers 

### ISSUE THREAD

**Issue by insidersbuilt** [siduck76/NvChad#239]
when i open up a terminal inside of the nvim the status line or the galaxy line disappers idk why this is happening. Does anyone else have the same prob

**Comment by siduck76** [comment]
> when i open up a terminal inside of the nvim the status line or the galaxy line disappers idk why this is happening. Does anyone else have the same prob

When was the last time you updated config?

**Comment by G-Rowell** [comment]
Hi @insidersbuilt,

I'm working on this now

NvChad is designed to not have (hide) the statusline when your in a Terminal buffer,

However there is a bug where it doesn't return when entering back into a normal buffer.

I'm fixing this bug now.

And will work today on a NvChad config option to enable normal statusline behaviour in terminal buffers.

**Comment by G-Rowell** [comment]
Oh @insidersbuilt ,

I misread.

The `statusline` should be fine?
There is still a bug with the `numbers` column that I'm fixing right now.

Do you still have the `statusline` bug? If let's see if we can fix it!!

**Comment by siduck76** [comment]
@insidersbuilt 

![image](https://user-images.githubusercontent.com/59060246/129434478-b2edb66d-353d-4792-87fb-afa4e219e4b9.png)

**Comment by G-Rowell** [comment]
I'm so dumb, completely misread everything twice, 

do the above

**Comment by G-Rowell** [comment]
@insidersbuilt 

I think this is good to close?
Lemme know if you have any other questions, I'll have some more coffee before reading them this time :laughing:
