### ISSUE TITLE
Installation : mason show all available package count is 0

### ISSUE THREAD

**Issue by veelion** [siduck76/NvChad#2400]
**Describe the bug**
when installing is done, mason show all available package count is 0

**To Reproduce**
1.  git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim

the screenshot:

![image](https://github.com/NvChad/NvChad/assets/714675/ab3b2ab9-c88e-488f-9b79-162d04c4720a)

**Comment by siduck** [comment]
not a nvchad issue, mason issue.
