### ISSUE TITLE
For some reason the word 'Azure' is highlighted

### ISSUE THREAD

**Issue by ghost** [siduck76/NvChad#2401]
Is there any way how I can sort out what is causing the word Azure being highlighted?

![image](https://github.com/NvChad/NvChad/assets/143710742/dfb64e91-71a4-4291-96bd-5cd48d9a2c4a)

**Comment by siduck** [comment]
does with happen without nvchad?

**Comment by siduck** [comment]
ok i'm assuming you searched Azure with / . press ESC and it'll go away

**Comment by moisesmorillo** [comment]
@janvv-visma @siduck this behavior could be related to https://github.com/NvChad/nvim-colorizer.lua is part of the inbuilt features of NvChad https://nvchad.com/docs/features

I dit the test writing Azure in a buffer and it gets highlighted automatically

**Comment by siduck** [comment]
@moisesmorillo try disabling the names

```lua
{
    "NvChad/nvim-colorizer.lua",
    opts = {
      user_default_options = {
        names = false,
      },
    },
},
```

**Comment by moisesmorillo** [comment]
@siduck thanks, for me is ok that behavior. I just wanna be helpful in the reported issue 🤭

**Comment by ghost** [comment]
> @moisesmorillo try disabling the names
> 
> ```lua
> {
>     "NvChad/nvim-colorizer.lua",
>     opts = {
>       user_default_options = {
>         names = false,
>       },
>     },
> },
> ```

Disabling the names stopped this behavior. Interesting. I have to dig in the source to see how it works. Curious how it detects which words are names. Thanks !!

**Comment by siduck** [comment]
@janvv-visma azure is an actual color

**Comment by ghost** [comment]
Aha... obvious
