### ISSUE TITLE
Error when attempt to index field 'fs' (a nil value)

### ISSUE THREAD

**Issue by DravenJohnson** [siduck76/NvChad#2406]
**Describe the bug**
Error output when using `nvim` (replace correct home path with `$HOME`
```
Error detected while processing $HOME/.config/nvim/init.lua:
E5113: Error while calling lua chunk: $HOME/.config/nvim/lua/core/init.lua:77: attempt to index field 'fs' (a nil value)
stack traceback:
        $HOME/.config/nvim/lua/core/init.lua:77: in function 'func'
        vim/shared.lua:193: in function 'tbl_map'
        $HOME/.config/nvim/lua/core/init.lua:76: in main chunk
        [C]: in function 'require'
        $HOME/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

Not sure where the issue is, I checked the Line 77 in that `core/init.lua` file and I see its related to "reload some chadrc options on-save"

Something related to using autocmd - BufWritePost, and try to return `vim.fs.normalize()`
And the line above it, using `vim.tbl_map()`

It happy everytime when nvim start, with or without files

No Customization yet

Versions:
```
nvimNVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

`NvChad v2.0`

**To Reproduce**
1. Install NeoVIM
2. Install NvChad
3. run `nvim`

**Expected behavior**
No Error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System: Debian 12 Bookworm
 - Terminal: SSH to a Remote server, with or without tmux
 - Version of Neovim: v0.72

**Additional context**
It might related to some plugin it auto installed, but couldn't debug.
For now, it can't load NvChad

**Comment by georgejean** [comment]
I think you have to run NvChadUpdate (maybe you don't have this commit #2152 yet).

**Comment by siduck** [comment]
please use neovim v0.9.. at least, its mentioned in our docs :sob:
