### ISSUE TITLE
Adding `luasnip` table to vscode formatted snippet not working

### ISSUE THREAD

**Issue by DaitiDay** [siduck76/NvChad#2407]
**Describe the bug**
Adding personal snippets with a `luasnip` table in vscode format are not working

**To Reproduce**
1. Added `vim.g.vscode_snippets_path = "./lua/custom/my_snippets"` in `custom/init.lua`
2. Open a file
3. Type the trigger word

**Expected behavior**
If the snippet has the `autotrigger` field it should be auto-expanded, but it does not happen. As a matter of fact, the snippet does not even show up on the `cmp` list.
If the snippet does not have the `autotrigger` field, it appears on the `cmp` list and everything works as expected.

**Desktop:**
 - Operating System: Ubuntu 22.04 via WSL2
 - Terminal: Windows Terminal
 - Version of Neovim: v0.9.1

**Additional context**
Example snippet with `autotrigger` enabled:
```
{
    "Test": {
        "prefix": ",t",
        "body": [
            "test"
        ],
        "description": "Test",
        "luasnip": {
            "autotrigger": true
        }
    }
}
```
Removing the `luasnip` table from the snippet allows to select it via `cmp`.

**Comment by siduck** [comment]
please use full path.  look at the lua format here , use that stdpath function https://nvchad.com/docs/config/snippets

**Comment by siduck** [comment]
and your snippets dir must have package.json too, so please read luasnip docs as well

**Comment by DaitiDay** [comment]
The problem is that the snippets without the `luasnip` dictionary work no problem, meaning that the snippet files are imported as intended. I can take a snippet that works, add the dict and it stop working (not showing up in `cmp` and not autoexpanding).

**Comment by siduck** [comment]
@DaitiDay that isnt nvchad issue then , try a minimal config like https://github.com/NvChad/tinyvim and check if it works on it. if it does then i'll look into this issue
