### ISSUE TITLE
Not able to edit multiple lines.

### ISSUE THREAD

**Issue by 0xSegmented** [siduck76/NvChad#2408]
**Describe the bug**
I am not able to edit multiple lines.
In previous configurations and as noted on a lot of sources for vim cheatsheets. I've always been using:
Shift + V (to select multiple lines) and do Shift + i (to edit all the lines at the same time)
Noticed that this does not work in the 'NvChad' configuration. I'd really like a clear up.

**To Reproduce**
Press: Shift + v
(select multiple lines)
Press: Shift + i
(just type something, it should prefix on all lines)

**Expected behavior**
The expected behavior is to easily add prefix, suffix or even in the middle of multiple lines some text.

**Desktop (please complete the following information):**
 - Ubuntu, Windows, Kali, Debian
 - GNOME Terminal
 -  NVIM v0.10.0-dev-1038+gc3e176f6e

**Comment by siduck** [comment]
Its Ctrl + v , not shift v 

![image](https://github.com/NvChad/NvChad/assets/59060246/80356dfa-6529-4997-a97d-9da3b4c8237b)
