### ISSUE TITLE
LSP unable to include default win32 libraries. (windows.h)

### ISSUE THREAD

**Issue by ghost** [siduck76/NvChad#2409]
**Describe the bug**

Download nvim on windows
Run nvim on the terminal
Input :MasonInstall clangd
Open a .cpp file

I expect it to recognize default includes.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/45573459/b9fc7cd3-32af-453b-a0ee-d8091f5ae226)
^ Expected to suggest DWORD and such.

Using windows terminal
Guessing I need to add the default includes somewhere, anyone knows.

**Comment by siduck** [comment]
not a nvchad issue... please setup clangd lsp in your customlspconfig, read nvchad.com docs properly :sob
