### ISSUE TITLE
Error running NVChad

### ISSUE THREAD

**Issue by Tech0ne** [siduck76/NvChad#2412]
Hi

Tried to run NVChad on my computer, and got that error :

![SS from error](https://github.com/NvChad/NvChad/assets/114503799/d984203a-c449-4dd5-a81b-7829f81c7c79)

I am running Ubunutu 22.04.1.

**Comment by siduck** [comment]
please use neovim v0.9 at least, i beg u

**Comment by alex-pv01** [comment]
Hi, 
I was facing with the same issue and reinstalled a higher version of nvim (v.10.0). Now i get the following error:

![image](https://github.com/NvChad/NvChad/assets/131586706/e3c42198-6912-4262-8b93-9afb6f17a545)
![image](https://github.com/NvChad/NvChad/assets/131586706/c83e5b27-5cf5-40f6-9150-f124f33c2548)

I am on Ubuntu 22.04.3 and Lua 5.3.6

**Comment by siduck** [comment]
please use neovim 0.9! also before installing rm -rf .local/share/nvim and .config/nvim and .local/state/nvim

lua version shouldnt matter, neovim ships with it

**Comment by siduck** [comment]
use this https://github.com/MordechaiHadad/bob if 0.9 isnt on your repo, its better than compiling from src

**Comment by alex-pv01** [comment]
thx @siduck, it works on nvim v0.9.1
