### ISSUE TITLE
Let user choose the bootstrap config origin

### ISSUE THREAD

**Issue by aleixq** [siduck76/NvChad#2414]
I am using nvchad in a multiuser environment, loading in a similar way as archlinux is doing, so a main basecode in /etc/xdg/nvim is used everytime a new user starts neovim.

Recently I see that there were changes in how custom is loaded when no customizations exist, in this line is written: 

https://github.com/NvChad/NvChad/blob/v2.0/lua/core/bootstrap.lua#L43

So do you think that this could be changed or extended to let user choose a custom repository instead?  It will be useful in case a custom configuration needs to be replicated in other users/devices (in my case, it could make it easier to use https://gitlab.com/aleixq/nvchad_custom.git  instead of https://github.com/NvChad/example_config  )

**Comment by siduck** [comment]
@aleixq  bootstrap is only done when there's no custom config. if there is then it wont occur at all. So just use your repo as lua/custom dir, then nvchad on whatever new installs you do wont even use the example_config.

**Comment by aleixq** [comment]
Thank's @siduck for being blazing fast...
So I think that there's something not working when using nvchad with global /etc/xdg/nvim because despite I have custom config in `/etc/xdg/nvim/NvChad/lua/custom`, bootstrap asks for example_config so it's executed. 

I'll look

**Comment by siduck** [comment]
@aleixq its `~/.config/nvim/lua/custom` or `/etc/xdg/nvim/lua/custom`
