### ISSUE TITLE
How to change prefix in whick-key to another title

### ISSUE THREAD

**Issue by DMNghia** [siduck76/NvChad#2422]
i enabled whick-key in my config, but some keystrokes show prefix, it make me difficult to remember  all keymaps. How to fix it?
![image](https://github.com/NvChad/NvChad/assets/136049529/33e6c21d-0a33-459c-8f00-cea6a3c390d8)

**Comment by siduck** [comment]
this isnt a nvchad thing. Do that in whichkey config.

**Comment by siduck** [comment]
also search through whichkey inour issues tab, then you'll get some hints

**Comment by DMNghia** [comment]
ok, thanks!
