### ISSUE TITLE
Easily remove NOTES buffer on clean install/initial setup

### ISSUE THREAD

**Issue by Andrew15-5** [siduck76/NvChad#2423]
**Is your feature request related to a problem? Please describe.**
I've tried opening a file with `~/.local/share/nvim/` removed. When lazy.nvim popup was present, the opened file was seen in the background, but when the initial setup was done the "NOTES" buffer with "Now quit nvim!" still appeared. Which means that it "closed" my opened file. But I was able to jump back to it via `:bd<CR>`. I also had to write `:e<CR>` to enable syntax highlighting. Autocompletion and theme are working right away.

**Describe the solution you'd like**
The best solution would be to always or conditionally show the "NOTES" buffer in a **popup**, which means that the opened file would still be visible. After this, I can just press `<Esc>` and it will automatically execute either `:e<CR>` or `:e!<CR>`. A note about the opened file can also be added to the NOTES.

**Describe alternatives you've considered**
A similar solution would be to check a specific flag in settings `show_notes_during_init_setup = false`, which will skip the NOTES altogether and will just leave the opened file alone (again, with `:e<CR>`). If no files were opened during the initial setup, then just don't show anything (leave Neovim the way it looks during next `nvim` execution).

**Additional context**
_nil_

**Screenshot**
_nil_

**Comment by siduck** [comment]
just re open neovim? or leader x ?

**Comment by Andrew15-5** [comment]
As I said, syntax highlighting disappears after NOTES are appearing. Besides closing the NOTES, I have to re-enable syntax highlighting using `:e<CR>` (I don't know if there is a better way). So "leader x" is not enough. And re-opening feels redundant, since lazy.nvim loads everything right after the bootstrapping.
