### ISSUE TITLE
Missing custom/init.lua after clean install (on initial setup) which is present in the docs

### ISSUE THREAD

**Issue by Andrew15-5** [siduck76/NvChad#2424]
In https://nvchad.com/docs/config/walkthrough, I noticed that `custom/init.lua` is mentioned many times, but it is not mentioned that it is missing by default. I'm finding this confusing because the mentioned `custom/chadrc.lua` is present after the initial setup. I think it's best to either add a note about missing `custom/init.lua` or create it during the setup when `custom/chadrc.lua` is created.

P.S. I have also noticed that `custom/chadrc.lua` must be present to, for example, change the default theme (while `custom/init.lua` is obviously can be absent).

**Comment by siduck** [comment]
you selected "n" during installation so thatmeans you will have to setup custom dir :/

**Comment by Andrew15-5** [comment]
Yes, you are right (of course you are). I now tried the example and it helped a lot. I was (still) struggling with understanding how to override already used plugins. Now I know _how_ to override _most_ plugins. I need more time, but I'm guessing that the guide should be improved (about what I said).

**Comment by siduck** [comment]
@Andrew15-5  https://nvchad.com/docs/config/plugins
