### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by bryantchan** [siduck76/NvChad#2425]
**Describe the bug**
This bug happens after running lazy updates for the plugins. Didn't update my config for a month.

**To Reproduce**
1. Go to a JS/TS file
2. type any related keyword
3. Error will show up

**Expected behavior**
No errors will show up when using auto-complete

**Screenshots**
![CleanShot 2023-10-09 at 16 59 34@2x](https://github.com/NvChad/NvChad/assets/1303409/d1fec0a8-aadf-4403-8621-e097dac95a2e)

**Desktop (please complete the following information):**
 - Operating System: MacOS 14.0
 - Terminal: iTerm
 - Version of Neovim: v0.10.0-dev-925+g99265d099

**Comment by siduck** [comment]
that looks like cmp issue, not nvchad and please use neovim 0.9 + only
