### ISSUE TITLE
which-key doesn't show pop-up with keys when a file is open.

### ISSUE THREAD

**Issue by ftpd** [siduck76/NvChad#2427]
**Describe the bug**
When I hit `<leader>` on an empty buffer, I get the list of possible keybindings. Also:
1. When I do `nvim some-nonexisting-file` it works fine too.
1. When I do `nvim` and later `:e some-existing-file`, it works too.
1. When I do `nvim some-existing-file`, pressing space (the default leader) doesn't show the pop-up, just moves cursor one character right.

**To Reproduce**
<see 'Describe the bug'>

**Expected behavior**
Pop-up shows every time.

**Desktop (please complete the following information):**
 - Linux
 - foot
 - neovim 0.9.2

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/57c71ab3-bd6f-4dd1-960e-faa1f6446b78


Unable to reproduce

**Comment by ftpd** [comment]
Thanks for checking, @siduck. I've just tested on a different host and it works there - so there has to be something on my side. All standard stuff (like `checkhealth`) is ok, I didn't compile neovim with any special parameters. Any hints and ideas what more could I check?

**Comment by siduck** [comment]
@ftpd  try example_config repo, also did you add any stuff to your custom mappings? check  your custom dir

**Comment by ftpd** [comment]
I'm testing it on 'clean' installation, without `custom/` even existing.

**Comment by siduck** [comment]
@ftpd perhaps make a video + use a keystrokes app so i can believe u :p

**Comment by ftpd** [comment]
I don't know how to create a video of my screen and I prefer not to learn, also not to waste time on compiling (I'm on Gentoo) some OBS or other stuff like this.

Can't you simply trust me? I'm not a newbie, I didn't started using Linux/neovim 2 days ago because some bald youtuber told me to, I'm not an 'using arch btw' kid. We already know that the problem occurs only on my local machine, now I'm asking someone definitely more experienced on this field for any methods to check and identify the root cause. If you need 'a video so you can believe me', I think we can't move any further from here. Thanks for your time on answering me, though.

**Comment by siduck** [comment]
@ftpd okay i trust you, check Lazy output after pressing space or just share your custom config, i'd look into that in my free time

**Comment by ftpd** [comment]
I don't have ANY custom config. I'm testing on a totally vanilla version, so after cloning the repository and launching nvim, I anser 'no' for 'Do you want to install example custom config?' question.

How can I check Lazy output? When I simply run `:Lazy`, I have the standard window from lazy.vim with plugin details etc. There is no new content/output there, even in Debug section.

**Comment by siduck** [comment]
`nvim anyfile`
press leader, ( so whichkey doesnt open right)
now run Lazy 

check if whichkey is loaded

**Comment by ftpd** [comment]
Whichkey is loaded in this scenario.

Fun fact: when I simply run `nvim` (so without any file), whichkey is not loaded at first and pressing the leader loads is - everything as expected. But when I do `nvim some-existing-file` ('existing' is a very important part here!), whichkey is loaded on the start and stays loaded when I press the leader, despite there is no pop-up menu on the bottom.

**Comment by ftpd** [comment]
Just to be clear: all keybinds work fine. There is just no popup, only in case I run `nvim someEXISTINGfile`.

**Comment by ftpd** [comment]
One more finding: when I press leader-g, I have the 'submenu' for mappings on it. Later everything starts working again. But it doesn't work this way when I try to use this as a workaround with other submenus, like -p or -m or whatever.

What a crazy situation ;-)

**Comment by siduck** [comment]
very weird, icant reproduce this at all :( , does it happen with non nvchad distros? try tinyvim

**Comment by ftpd** [comment]
I'm using AstroNvim (want to switch to NvChad, that's why I'm here ;-)) and it works fine.

I'm started to think it's because Gentoo adds some 'non standard' options (but I can't see nothing 'special') in the ebuild. The other hosts I've tested on are Void and unfortunately I don't have another Gentoo host to check.

**Comment by siduck** [comment]
@ftpd same issue with void?

**Comment by ftpd** [comment]
No, it works on Void. That's why I'm thinking of blaming gentoo ;-)

**Comment by siduck** [comment]
hmm       looks like a distro issue, which is very weird!! This should work good regardless of OS, try https://github.com/MordechaiHadad/bob

**Comment by siduck** [comment]
uninstall old nvim too

**Comment by ftpd** [comment]
Nice tool. Yeah, it works with neovim installed from binary provided by bob.
So, this is definitely Gentoo's fault. I will try to investigate the ebuild more or talk to maintainers/create a ticket in Gentoo's bugzilla.

Thank you for helping me identifying the issue, I can confirm NvChad works fine. Case closed here! ;-)
