### ISSUE TITLE
Getting error about a non-existent repository when doing nvchad update

### ISSUE THREAD

**Issue by ayushxx7** [siduck76/NvChad#2432]
**Describe the bug**

**To Reproduce**
1. :NvChadUpdate
```
     extensions 0.33ms   core.init
        remote: Repository not found.
        fatal: repository 'https://github.com/NvChad/extensions.git/' not found
```

**Expected behavior**
no errors should be found on update

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/16764027/bd0ca15d-514e-42bd-af44-e0d9f46c88d2)

**Desktop (please complete the following information):**
 - Operating System - Windows
 - Terminal - Windows Powershell
 - Version of Neovim - latest probably

**Additional context**

**Comment by siduck** [comment]
@ayushxx7  cd into nvim dir and git pull

**Comment by siduck** [comment]
if nothing works then do a clean install of nvchad
