### ISSUE TITLE
Does NVchad support auto file saving

### ISSUE THREAD

**Issue by Frusadev** [siduck76/NvChad#2435]
I started using nvchad and i'm wondering if it has that feature

**Comment by siduck** [comment]
hi @Frusadev , it doesnt have it. u can use autosave.nvim plugin

**Comment by Frusadev** [comment]
Okay thanks, but i just ran into another problem i've wanted to install a plugin, so i edited the plugins.lua file inside of custom but when i run nvim, it says: `Error detected while processing /home/frusadev/.config/nvim/init.lua:
No specs found for module custom.plugins
Press ENTER or type command to continue`

here's the content chadrc.lua:
`local M = {}

M.ui = {theme = 'ayu_dark'}
M.plugins = 'custom.plugins'

return M`

And the content of plugins.lua:
`local plugins = {
  {
    'vim-crystal/vim-crystal',
    ft = 'crystal'
  }
}

return plugins`

**Comment by Frusadev** [comment]
Thanks
