### ISSUE TITLE
No specs found for module custom.plugins

### ISSUE THREAD

**Issue by Frusadev** [siduck76/NvChad#2436]
i just ran into anerror... I wanted to install a plugin, so i edited the plugins.lua file inside of custom/ but when i run nvim, it says:
Error detected while processing /home/frusadev/.config/nvim/init.lua: No specs found for module custom.plugins Press ENTER or type command to continue

https://github.com/NvChad/NvChad/assets/81917636/b7efd237-7c29-4140-ad55-a7207b393beb

the content of plugins.lua:

![Plugins](https://github.com/NvChad/NvChad/assets/81917636/ae3de352-637c-4da3-924e-04eebc39d07e)

chadrc:

![Chadrc](https://github.com/NvChad/NvChad/assets/81917636/677ce489-961c-46c6-afcf-e548c992e95b)

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/fce020d5-6fab-4dea-828d-1039d7d8a249)

whats this?

**Comment by siduck** [comment]
l ?

**Comment by Frusadev** [comment]
The path to ~/.config/nvim/lua/custom

**Comment by Frusadev** [comment]
By the way i'm using Ubuntu 23.04, and openbox.

Lua version: Lua 5.4.4
Neovim version: 0.9.4

I've installed it using brew

**Comment by siduck** [comment]
please try the example_config

**Comment by Frusadev** [comment]
Thanks it worked! But what was problem ?

**Comment by siduck** [comment]
@Frusadev  i dont know, if you're chadrc from scratch then make sure you read all of the docs. example_config is good to use initially btw
