### ISSUE TITLE
init file trying to call autocmd which is null

### ISSUE THREAD

**Issue by BGOPC** [siduck76/NvChad#2437]
**Describe the bug**
after installing NvChad and running nvim, I got an error meaning that the init file is trying to call local `autocmd` which is null, in line 67 

**To Reproduce**
remove existing nvim config
run `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim` 
and I get the error shown in the screenshot below 

**Expected behavior**
I expected it to ask me if I wanted to have an example custom config and proceed to install
**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/94793764/44d12771-af48-4000-9b47-daf5933985bb)

**Desktop**
 - Ubuntu 22.04.1 LTS
 - gnome-terminal
 - LuaJIT 2.1.0-beta3

**Comment by siduck** [comment]
pls use neovim 0.9 :sob:
