### ISSUE TITLE
icon not displaying

### ISSUE THREAD

**Issue by zhex900** [siduck76/NvChad#2439]
I have installed the Jetbrains Mono font. 

`fc-cache -v ./local/share/fonts`

However, the icons are still not showing. I am running Ubuntu Linux 6.2.0-1013-aws x86_64. I don't have a desktop. 

Anything else should I do to add the icon?

![Screenshot 2023-10-16 at 12 25 05 am](https://github.com/NvChad/NvChad/assets/5380757/398e8c9c-a9e4-4f61-8039-dd84854b114a)

**Comment by siduck** [comment]
set nerdfonts in terminal pls

**Comment by zhex900** [comment]
Sorry, this is a dumb question. How do I set the font in the terminal? Do you mean changing the console font on the server?
