### ISSUE TITLE
Conflict with GitHub Copilot

### ISSUE THREAD

**Issue by marek22k** [siduck76/NvChad#2440]
**Describe the bug**
When I install NvChad and then https://github.com/github/copilot.vim, the Copilot commands are not available and I get back `E492: Not an editor command: Copilot setup` as a message.

**To Reproduce**
1. Install neovim
2. Installl NvChad
3. Install Copilot for (Neo)vim
4. Open neovim and type `:Copilot setup`

**Expected behavior**
The normal copilot setup

**Desktop (please complete the following information):**
 - Operating System
 Debian-based

 - Terminal
mate-terminal

 - Version of Neovim
``` sh
$ nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

**Comment by marek22k** [comment]
After `:MasonInstall rubocop`, `:Rubocop` also results in E492.

**Comment by siduck** [comment]
please remove lazyloading for github copilot

**Comment by siduck** [comment]
https://nvchad.com/docs/config/plugins

**Comment by marek22k** [comment]
Copilot works when doing
```
local plugins = {

  { "github/copilot.vim" , lazy = false },
```
in `/home/bandura/.config/nvim/lua/custom/plugins.lua`.

@siduck And what about RuboCop?

**Comment by siduck** [comment]
@marek22k idk about rubocop,   but do its `rubocop` command. 

not Rubocop. and its not a vim command so please run that in terminal.

**Comment by marek22k** [comment]
With the vim [rubocop plugin](https://github.com/ngmy/vim-rubocop), the command should also be available in Vim.

**Comment by siduck** [comment]
@marek22k mason only installs the binaries, not enables any VIM Commands 

![image](https://github.com/NvChad/NvChad/assets/59060246/91474179-ba6b-4689-90a1-19ec1f6d605b)
 
 
so please learn how to use robocop, null-ls could be used but its un-maintained so please use nvim-lint  https://github.com/mfussenegger/nvim-lint

**Comment by marek22k** [comment]
But in the description of the plugin it says that after installation it gives the command :RuboCop.
As a command line tool I know rubocop quite well and have also worked with it several times.
How can I activate the plugin after downloading so that the corresponding commands are available?

**Comment by siduck** [comment]
@marek22k mason never does it. mason doesnt even install rubocop.vim...   :/
