### ISSUE TITLE
The phrase `recording @a` does not appear.

### ISSUE THREAD

**Issue by minocrafft** [siduck76/NvChad#2447]
**Describe the bug**
I remember the phrase like `recording @a` appearing in the past when using the Vim macro with nvchad,
but, It no longer sees this phrase after updating to the latest version.

**To Reproduce**
1. Run NvChadUpdate
2. Run vim macro such as `qa`

**Screenshots**
![recording](https://github.com/NvChad/NvChad/assets/84756721/500c9ebb-8ec5-4dcb-ac7d-c695a51f5582)
The "기록중" is the same word as "recording" in Korean.
Pure vim appears the phrase `recording @a`.
But, neovim is not.

Is the feature no longer used?

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - zsh 5.8
 - neovim 0.9.1

**Comment by siduck** [comment]
why is nvchadUpdate even involved here?  do you want to run macro before update?

**Comment by minocrafft** [comment]
`NvChadUpdate` is pulling the latest update to local. right?

So I thought some of the features were changed during the update.

If there is not any change, Isn't it supposed to appear?

**Comment by siduck** [comment]
@minocrafft yes nvchadUpdate pulls latest commit. but what does recording have to do with it?

**Comment by minocrafft** [comment]
Sorry, please excuse my poor expression

![no_recording](https://github.com/NvChad/NvChad/assets/84756721/dd5d8ea3-3eaf-4086-a060-2b1ab6faf195)

Previously, the word `recording @a` was displayed in the lower left corner, which means that you are recording a macro to register, but it does not appear now.

So there's no way to know if the macro key is working properly.

Of course, I can check it through the `:register` command, but I want to be able to know in real time.

**Comment by siduck** [comment]
@minocrafft  press qa   again

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/d6cc7fd7-afa6-4e40-af56-6d4d556efc30

**Comment by minocrafft** [comment]
Ooh.. I think there's a problem with my setting. Thank you.

**Comment by minocrafft** [comment]
I found the problem. The [folke/noice.nvim](https://github.com/folke/noice.nvim) was the cause.

Previously, the text was displayed at the bottom left, but the letter began to be invisible as it was displayed in the center floating window due to the `noice.nvim` plugin.

When the `noice.nvim` is disabled, the text appears properly.

![nonoice](https://github.com/NvChad/NvChad/assets/84756721/b3a59ffa-2519-4747-8c8f-837491665861)

**Comment by siduck** [comment]
yes, noice overrides some default functionality so messages wont show down ( cmd area ) but they'll be shown as notifications. i dont like that way so i dont use it.

Always verify issue before posting on nvchad github!
