### ISSUE TITLE
NvChad Update fails: repository 'https://github.com/NvChad/extensions.git/' not found

### ISSUE THREAD

**Issue by dierk42** [siduck76/NvChad#2449]
**Describe the bug**
Trying to update NvChad to latest version via lazy.nvim gives this error message:
  Failed (1)
     extensions 0.31ms 󰢱 nvchad.update  core.init
        remote: Repository not found.
        fatal: repository 'https://github.com/NvChad/extensions.git/' not found

**To Reproduce**

Start update in lazy.nvim

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal : MS Terminal App; pwsh
 - Version of Neovim : NVIM v0.9.2

**Comment by vic-gfuentes** [comment]
Same here: 
![image](https://github.com/NvChad/NvChad/assets/47761673/2e5d9a68-87c9-450c-a1f0-63efcda1adaa)

OS: MacOs 13.6
Terminal: Kitty 0.30.0
NVIM: v0.9.4

**Comment by vic-gfuentes** [comment]
> Same here: ![image](https://user-images.githubusercontent.com/47761673/275903423-2e5d9a68-87c9-450c-a1f0-63efcda1adaa.png)
> 
> OS: MacOs 13.6 Terminal: Kitty 0.30.0 NVIM: v0.9.4

Fixed by reinstalling NvChad

**Comment by DreamingRaven** [comment]
I am having the exact same issue, reinstalling from release did not help in my case:

![nvchad](https://github.com/NvChad/NvChad/assets/10534713/ce3ba6fd-7b9c-47da-9757-a7f3218dc3d3)

I know that the "fatal could not read Username" error usually means the repository is wrong, so I went looking for NvChad/extensions and I could not find it? Then I thought maybe this is a difference between the v2 release and the current master branch? So I presume when vic-gfuentes reinstalled he reinstalled using ``git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`` whereas I was installing from the release with chezmoi. https://gitlab.com/GeorgeRaven/chadfiles/-/blob/master/configs/.chezmoiexternal.toml?ref_type=heads#L10

Will try installing from master this time and see if that helps.

EDIT: yep rightly enough installing from the default branch works. Will change my chezmoi config to always use the default branch over the release.
EDIT2: changed my chezmoi to use the external:
```
[".config/nvim"]
  type = "archive"
  #url = "https://github.com/NvChad/NvChad/archive/refs/tags/v2.0.tar.gz"
  url = "https://github.com/NvChad/NvChad/archive/refs/heads/v3.0.tar.gz"
  extract = true
  stripComponents = 1
  refreshPeriod = "168h"
```
And now all is right with the world again. Thanks @siduck for the great work with nvchad, once a release of v3 is out I will switch to that!
https://gitlab.com/GeorgeRaven/chadfiles/-/commit/f22d03c9363a8dc054009fc1abdaf0b3333ecc36
