### ISSUE TITLE
Default VimTeX mappings don't work

### ISSUE THREAD

**Issue by v0id138** [siduck76/NvChad#2450]
Basically the title says it all. After loading VimTeX via the custom/plugins.lua file I am unable to use the default vimtex bindings, such as <leader>ll for compiling.
Is there any way to fix this or do I just have to manually map everything from scratch.

**Comment by siduck** [comment]
please read the plugin docs well, lazyload vimtex properly or lazy=false

**Comment by v0id138** [comment]
My bad for not including the fact that I have disabled lazy loading for vimtex. It is not due to that.

**Comment by siduck** [comment]
@vladdoster show your code for vimtex

**Comment by v0id138** [comment]
If you mean by showing how I load the plugin then, after fresh install, I put the following into custom/plugins.lua
`{"lervag/vimtex,
lazy = false,
}`

The plugin works ,just without the default bindings. No custom config for vimtex yet etc.

**Comment by siduck** [comment]
https://github.com/lervag/vimtex#configuration u didnt do any of this

**Comment by v0id138** [comment]
Unfortunately doesn't work anyways. But thanks for the effort. :)

**Comment by siduck** [comment]
@v0id138 i dont use vimtex so i cant help much but if it works with other distros and not nvchad then i'll open this issue back.
