### ISSUE TITLE
init.lua points to lua/custom/init.lua but NvChad does not include a lua/custom folder

### ISSUE THREAD

**Issue by sai-sy** [siduck76/NvChad#2451]
I am working on installing nvchad and neovim and found when I follow the instructions, I get no prompt that says "Do you want to install custom config. The tutorial said I should. I instead I just get normal nvim. I think this is because lua/custom/init.lua does not exist even though `./init.lua` points to `./lua/custom/init/lua`

I'm running WSL2. 

![image](https://github.com/NvChad/NvChad/assets/74868837/0fa6f7d7-abe6-4039-9134-ec927451a9ef)

Pointing init.lua to the core folder or the plugins folder also changes nothing

**Comment by siduck** [comment]
@sai-sy please select y/n during installation, it  creates custom dir :/

**Comment by sai-sy** [comment]
During the github pull? I wasn’t given the prompt. It just pulls the dir
and opens up nvim to the default page.

**Comment by siduck** [comment]
@sai-sy that could happen if you already had a custom dir :/  

Please do a clean installation , i.e delete all nvim dirs in existent, then install nvchad

**Comment by sai-sy** [comment]
@siduck I tried that too : (

```bash
sai@SAI-ASUS-LAPTOP:~$ find -name nvim
./.cache/nvim
sai@SAI-ASUS-LAPTOP:~$ cd /usr
sai@SAI-ASUS-LAPTOP:/usr$ find -name nvim
sai@SAI-ASUS-LAPTOP:/usr$ cd /home
sai@SAI-ASUS-LAPTOP:/home$ find -name nvim
./linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/nvim
./sai/.cache/nvim
sai@SAI-ASUS-LAPTOP:/home$ rm -rf ./sai/.cache/nvim
sai@SAI-ASUS-LAPTOP:/home$ find -name nvim
./linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/nvim
sai@SAI-ASUS-LAPTOP:/home$
```

Then I reinstall using
```bash
sudo apt-get install neovim
```
And once I apply do the git clone:
```bash
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```
I just get nvim open
![image](https://github.com/NvChad/NvChad/assets/74868837/a52c4f31-6e98-485a-9078-228b2659b113)

**Comment by sai-sy** [comment]
I'll also add this
```bash
sai@SAI-ASUS-LAPTOP:/usr$ find -name custom
./lib/byobu/custom
./local/go/pkg/mod/github.com/go-playground/validator/v10@v10.11.2/_examples/custom
./share/emacs/26.3/etc/images/custom
./share/nodejs/colors/lib/custom
sai@SAI-ASUS-LAPTOP:/usr$ cd /home
sai@SAI-ASUS-LAPTOP:/home$ find -name custom
./sai/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/@colors/colors/lib/custom
./sai/go/pkg/mod/github.com/go-playground/validator/v10@v10.11.2/_examples/custom
```

**Comment by sai-sy** [comment]
@siduck Could I get the issue reopened :)

**Comment by siduck** [comment]
@sai-sy  
![image](https://github.com/NvChad/NvChad/assets/59060246/8941a0c8-d92b-4d55-85e2-a30c9cb0fa8d)


you need neovim 0.9 + btw :skull:
