### ISSUE TITLE
Unable to disable `"` 

### ISSUE THREAD

**Issue by zdk** [siduck76/NvChad#2452]
**Describe the bug**

Adding `"` key in in disabled table for normal mode. 
It seems like `"` key only that is not disabled.
However, other keys in the table are disabled successfully.

**To Reproduce**
1. I'm using this mappings file: https://github.com/zdk/dotfiles/blob/master/config/nvim/lua/custom/mappings.lua
And, I have added the following table in order to disable `"` 
```
M.disabled = {
  n = {
      ["<leader>h"] = "",
      ["<C-a>"] = "",
      ['"'] = "" -- Added " here
  }
}
```
2. Check via `map "`

Got this result

![Screenshot 2023-10-18 073212](https://github.com/NvChad/NvChad/assets/5758/8eff0f82-1ab8-45da-b839-3faa25e56da8)

**Expected behavior**
Run command  `map "` 
And get the result `No mapping found`

**Desktop (please complete the following information):**
 - Operating System
 Ubuntu 22.04.3 LTS
 - Terminal
 Windows Terminal (WSL2)
 
 - Version of Neovim
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3

**Additional context**
I'm trying to enable this surround plugin: https://github.com/kylechui/nvim-surround
but, always getting triggered by `"` whenever I use `"`
So that I cannot do this operation
```help
     Old text                    Command         New text
--------------------------------------------------------------------------------
    "change quot*es"            cs"'            'change quotes'
```

**Comment by siduck** [comment]
@zdk m.disabled is only for disabling "NVCHAD" mappings. not default or plugin mappings.

**Comment by zdk** [comment]
@siduck Thanks! 
Made it work by configuring via `which-key` (The _default_ "plugin" of NVChad)

```diff
diff --git a/config/nvim/lua/custom/mappings.lua b/config/nvim/lua/custom/mappings.lua
index aea039c..a04313c 100644
--- a/config/nvim/lua/custom/mappings.lua
+++ b/config/nvim/lua/custom/mappings.lua
@@ -121,4 +121,14 @@ M.go = {
 	},
 }

+M.whichkey = {
+	plugin = true,
+	n = {
+		["\""] = {
+			"",
+			"no ops",
+		},
+	},
+}
+
 return M
diff --git a/config/nvim/lua/custom/plugins.lua b/config/nvim/lua/custom/plugins.lua
index c7495a6..15387fd 100644
--- a/config/nvim/lua/custom/plugins.lua
+++ b/config/nvim/lua/custom/plugins.lua
@@ -38,6 +38,7 @@ local plugins = {
 		opts = overrides.nvimtree,
 	},

+
 	-- Install a plugin
 	{
 		"max397574/better-escape.nvim",
@@ -96,6 +97,15 @@ local plugins = {
 			require("core.utils").load_mappings("dap")
 		end,
 	},
+
+  {
+    "folke/which-key.nvim",
+    config = function(_, opts)
+      require("which-key").setup(opts)
+      require("core.utils").load_mappings "whichkey"
+    end,
+  },
+
```
Just for other who might search for similar issue:
Even with this key disabled it still does not work very well with nvim-surround for some reason...
But, echasnovski/mini.surround works well with NVChad&which-key, so that I decided to moved to `mini.surround` instead.

**Comment by siduck** [comment]
@zdk  you can use vim.keymap.del . in custom/init.lua

```lua
vim.schedule(function()
  vim.keymap.del("n", '"')
end)
```

I wrapped this in schedule func cuz i'm assuming whichkey or some plugin initializes that mapping so we want to load the code after UI

**Comment by zdk** [comment]
> @zdk you can use vim.keymap.del . in custom/init.lua
> 
> ```lua
> vim.schedule(function()
>   vim.keymap.del("n", '"')
> end)
> ```
> 
> I wrapped this in schedule func cuz i'm assuming whichkey or some plugin initializes that mapping so we want to load the code after UI

Thanks! that `vim.keymap.del("n", '"')` works too for removing `"` from mapping.
But, still something of https://github.com/kylechui/nvim-surround does not compatible well with (assuming) which-key plugin.

I'm happy now that I can get NvChad working together with https://github.com/echasnovski/mini.surround. 
surround editing is must-have for me 🤣  so, any plugin that works I'm good to go!

And, thank you very much for your great NvChad config!
