### ISSUE TITLE
Telescope Error & nvim-treesitter Error

### ISSUE THREAD

**Issue by Abiel101** [siduck76/NvChad#2455]
**Describe the bug**
I continue getting this error on the screen shot below when trying to use telescope.

**To Reproduce**
1. open terminal
2. type in nvim 
3. type <leader> + f + o 

**Expected behavior**
<leader> + f + o

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/29215264/d1c2ad30-9252-49f6-8549-1a1b220c93f1)

**Desktop (please complete the following information):**
 - Windows
 - Powershell
 -  Neovim v0.9.0

**Additional context**
I also get a similar error when running another plugin called neorg. 

![image](https://github.com/NvChad/NvChad/assets/29215264/17c0c600-c910-4d9f-b374-6305d761a85d)

**Comment by siduck** [comment]
please install make on your system and do lazy sync

**Comment by Abiel101** [comment]
install make?

**Comment by siduck** [comment]
> install make?

yes, fzf native.nvim plugin needs that for compiling itself. check its readme

**Comment by Abiel101** [comment]
![image](https://github.com/NvChad/NvChad/assets/29215264/b3e11901-cfac-4f1c-84d9-2633e130d8b7)

**Comment by Abiel101** [comment]
Is this the make I need to install?

**Comment by siduck** [comment]
> Is this the make I need to install?

yes

**Comment by Abiel101** [comment]
After syncing I still got the following error

![image](https://github.com/NvChad/NvChad/assets/29215264/9e999100-66a0-4300-a46e-eb839389d222)

But this only happens once I close Neovim. After I open it and just click enter on the error everything work perfectly fine.

I also attempted to run the following command `Lazy build telescope-fzf-native.nvim` and got the the below error.

![image](https://github.com/NvChad/NvChad/assets/29215264/a417c454-ebaf-478b-a1aa-fe8cb65156ad)

**Comment by siduck** [comment]
@Abiel101  go to the local dir where fzf-native is installed and run make command there

**Comment by Abiel101** [comment]
Okay I tried this and this is the error that I got

![image](https://github.com/NvChad/NvChad/assets/29215264/77f93a8e-833c-40cd-bdca-5b530bcfd909)

**Comment by Abiel101** [comment]
Also this happens in NVIM.

![image](https://github.com/NvChad/NvChad/assets/29215264/eee80fe6-fb26-48b0-9180-90debae8eaa1)

**Comment by siduck** [comment]
> Okay I tried this and this is the error that I got
> 
> ![image](https://user-images.githubusercontent.com/29215264/277194322-77f93a8e-833c-40cd-bdca-5b530bcfd909.png)

run make, not cmake!
