### ISSUE TITLE
nvim-tree default folder icon doesn't show

### ISSUE THREAD

**Issue by Lepidopteran** [siduck76/NvChad#2457]
**Describe the bug**
When I Open Nvim-Tree the default folder icon shows a square .

**To Reproduce**
1. Open NvChad
2. Press <Space+E>

**Expected behavior**
The default folder icon to show up.

**Screenshots**
![project](https://github.com/NvChad/NvChad/assets/44733840/6ef08d5a-39d4-4575-aba6-8839fd3db0d1)

I did configure kitty with the correct font
![kitty config](https://github.com/NvChad/NvChad/assets/44733840/ba5dc60c-eae3-46e5-8aba-f6e6fadb1d67)

**Desktop (please complete the following information):**
 - Linux (Fedora 38)
 - Kitty
 - Neovim v0.9.2

**Additional context**
Some folder icons do show up.

I have tried update NvChad and I have the latest version of nerdfonts installed v3.0.2

**Comment by siduck** [comment]
pls set nerdfonts in terminal. also update nvchad to latest
