### ISSUE TITLE
Tabufline Sidebar Offset

### ISSUE THREAD

**Issue by rezafikkri** [siduck76/NvChad#2458]
**Describe the bug**
when I open multiple files, the tabufline offset sidebar is wrong (as picture below), but when I set nvimtree width to 20, then sidebar offset is correct

**To Reproduce**
1. Open nvim-tree
2. Try to open many files

**Expected behavior**
tabufline sidebar offset is correct, does not exceed the limit

**Screenshots**
![tabufline 1](https://github.com/NvChad/NvChad/assets/47538721/96150968-0005-4a3b-af9a-4e8bbe0dbd38)
![tabufline 2](https://github.com/NvChad/NvChad/assets/47538721/5a5766e4-82ad-48f8-b08c-7f8b473cf94a)
![tabufline 3](https://github.com/NvChad/NvChad/assets/47538721/51dca268-26be-4c88-a275-1363c70e2dff)

**Desktop (please complete the following information):**
 - Debian 11
 - Kitty 0.30.1
 - Nvim v0.9.4

**Comment by siduck** [comment]
@rezafikkri please override tabufline module,  read docs
