### ISSUE TITLE
Getting an error from LuaSnip telling that it cannot log for this session.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2461]
**Describe the bug**
When pressing `space+th`. This is error I get `LuaSnip: could not open log at "luasnip.log path". Not logging for this session`

**To Reproduce**
1. Install nvChad
2. press `space+th`

**Expected behavior**
The error shouldn't be there.

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - Linux 6.1.59-1-lts (Arch Linux)
 - alacritty
 - NVIM v0.9.4

Also getting this error while typing `vim/loader.lua:0: EACCES: permission denied: "path of lspkind.luac"`

**Comment by siduck** [comment]
unable to reproduce, show a video.

**Comment by mubin-thinks** [comment]
Here's the video:

https://github.com/NvChad/NvChad/assets/101094719/81fde88d-c8d3-4e7c-a403-ed7da7a01934

**Comment by siduck** [comment]
it clearly looks an OS issue, nvim doesnt have permissions on your system, especially write permissions. Please use xorg and check.

**Comment by mubin-thinks** [comment]
How do i check?

**Comment by siduck** [comment]
> How do i check?

try a xorg DE or wm like i3 instead of sway
