### ISSUE TITLE
Getting Errror " Failed to run `config` for telescope.nvim " after fresh install of nvchad

### ISSUE THREAD

**Issue by slippinjimmy1** [siduck76/NvChad#2465]
**Describe the bug**

After installing the lastest version of nvcahd on wsl2 arch linux i am getting the error i mentioned in the title

**To Reproduce**

I have no idea how I can reproduce this error on your machine

**Expected behavior**

I expected no error whatsoever

**Desktop (please complete the following information):**
 - Arch Linux (WSL2 Windows 11)
 - Windows Terminal
 - NVIM v0.9.4
 

![image](https://github.com/NvChad/NvChad/assets/121359583/3ce33c99-9532-455d-a649-92a025b0b87d)

**Comment by siduck** [comment]
pls install make on windows :/ 

and properly compile fzf native.nvim

@kayuxx !!!!!!!!!!!!!!!!!!!

**Comment by slippinjimmy1** [comment]
why do i need to install make on windows i am running it on wsl2 inside arch linux and what do u mean by compile fzf native.nvim

**Comment by slippinjimmy1** [comment]
Ok So I just got  the solution......

The Solution

First of all we need to make sure if you have a minimal install of linux, if thats the case most of linux os like arch donot ship  with cmake on board first of all u need to install gcc and cmake then install nvchad hopefully this error of yours just like mine will be fixed..

PS: The one who closed this issue is complete buffoon, he is unable to comprehend basic rudimentary information. (Hey, you I know u are reading this, stop giving solutions about things u have no idea of)

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/05828cec-20b0-4b23-9dc1-3b2e60a4eb1a)
![image](https://github.com/NvChad/NvChad/assets/59060246/2fc88889-db0f-4f01-b4cf-17b559e9c511)


![image](https://github.com/NvChad/NvChad/assets/59060246/ac8d5bf5-4ec5-4e77-ab64-945893fc1431)



Only if you were smart enough to read the pre-install docs

**Comment by siduck** [comment]
> PS: The one who closed this issue is complete buffoon
 
 I'm fed up of newbies not even reading the basic "install" docs and creating issues here. If you dont want to read it then dont use NvChad please. 
 
 Look at your language, was I even rude to you prior?  All I said was to install 'make' on windows,  Idc if you use wsl or something. You should literally understand that absence of make's causing the issue.  
 
 Indian newbies are the worst imo, they dont read docs and are rude

**Comment by slippinjimmy1** [comment]
Bruh the reason I called u a buffoon is because u told me to install make on windows and if u read what i wrote when i started the issue, i mentioned that i am using arch linux and u told me to install make on windows how will it affect my arch instance that it doesnt makes sense does it.

PS: I really didnt knew u were so much short tempered, u will get provoked this easily, a friend of mine asked me to write the issue this way and i wrote that as a joke, i really didnt mean to hurt someone on the "internet".

Peace brother

**Comment by siduck** [comment]
I dont know much about wsl but its pretty obvious that you should take it as "install make on whatever OS you're using"

**Comment by kayuxx** [comment]
@siduck pls refer that to the docs. there's no note for that neither the website or on GitHub

**Comment by siduck** [comment]
> @siduck pls refer that to the docs. there's no note for that neither the website or on GitHub

i did already,  yet some users get the issue. but after manual compiling it works for them
