### ISSUE TITLE
Pressing Ctrl+I doesn't jump back in history

### ISSUE THREAD

**Issue by tobias-haenel** [siduck76/NvChad#2467]
**Describe the bug**

**To Reproduce**
1. Open a single file
2. Search something
3. Press n a couple of times
4. Press Ctrl - O a couple of times
5. Pressing Ctrl - I does nothing

**Expected behavior**
Jump back in command history.

**Desktop (please complete the following information):**
 - Operating System: Archlinux
 - Terminal: kitty v0.30.1
 - Version of Neovim: v0.9.4

**Additional context**
Differentiating between Ctrl+I and Tab in neovim seems to be quiet hard, see https://sw.kovidgoyal.net/kitty/keyboard-protocol/#quickstart and https://superuser.com/questions/770068/in-vim-how-can-i-remap-tab-without-also-remapping-ctrli for details.

The problem also occured when I briefly tried out in Neovide v0.11.2.

Is there a proposed way to remap the forward action in the jump history?

**Comment by tobias-haenel** [comment]
https://github.com/neovim/neovim/issues/20126 gave me a solution

Add

```
M.general = {
  n = {
    ["<C-i>"] = { "<C-i>", opts = { noremap = true } },
  }
}
```
to `custom/mappings.lua`

**Comment by siduck** [comment]
seems like mapping Tab also maps C-i, idk how

https://www.reddit.com/r/neovim/comments/vguomm/how_can_i_map_tab_but_keep_the_default_action_for/

its a known issue btw. So your solution can be used

**Comment by LinuxIsCool** [comment]
BTW to get this working in tmux + alacritty I had to do the following: 
* Downgrade tmux to version 3.1c
* Add the following to alacritty.yml:
```
key_bindings:
    - { key: I, mods: Control, chars: "\x1b[105;6u" }
```

The mapping of <C-i> that @tobias-haenel shows above was not necessary for me.
