### ISSUE TITLE
Loading treesitter on VeryLazy can break neotest

### ISSUE THREAD

**Issue by bwafi** [siduck76/NvChad#2468]
**Describe the bug**
[this issue](https://github.com/nvim-neotest/neotest/issues/303#issuecomment-1782896751)

**To Reproduce**
run neotest : `no tests found `

**Desktop (please complete the following information):**
 - linux mint 
 - alacritty
 - nvim 0.9.4

**Comment by siduck** [comment]
just load treesitter after neotest

**Comment by siduck** [comment]
or dont use lazy=false for neotest
