### ISSUE TITLE
Show invisible characters for selected text

### ISSUE THREAD

**Issue by 8ullyMaguire** [siduck76/NvChad#2474]
By default, Visual Studio Code displays invisible characters, such as spaces, tabs, and line endings, when text is selected or highlighted. It would be helpful to have an option to show invisible characters for selected text, similar to the feature in Visual Studio Code. An alternative would be a toggle shortcut to switch invisible characters on and off, but I think it would be best to set the default the same as Visual Studio Code and let users add a shortcut to toggle on and off to their custom configuration if they want.

**Comment by siduck** [comment]
show an image

**Comment by 8ullyMaguire** [comment]
![Screenshot from 2023-11-02 01-22-22](https://github.com/NvChad/NvChad/assets/126260333/930f2d6b-8d2b-4c4a-8bcb-51c39d63ecd5)

**Comment by siduck** [comment]
@8ullyMaguire these are not related to nvchad. check blankline.nvim docs
