### ISSUE TITLE
[ISSUE] Disappearing characters

### ISSUE THREAD

**Issue by 4nt11** [siduck76/NvChad#2475]
**Describe the bug**

Characters seem to dissapear while using NvChad. It occurs when I open bash scripts, but I don't really know why. Using "vanilla" nvim, this doesn't happen:

**To Reproduce**
1. Open a bash script
2. Sadness occurs :( It hides characters, while "clean" Neovim does not.

**Expected behavior**
Characters not hiding would be the expected behavior.

**Screenshots**
![sc1](https://github.com/NvChad/NvChad/assets/64175868/81d20b13-8663-406f-be38-84b2957d1df9)

`nvim --clean ...`

![sc2](https://github.com/NvChad/NvChad/assets/64175868/5cff4547-d6e9-42cf-b307-678ac6a0fa66)

**Desktop (please complete the following information):**
 - Arch Linux
 - Kitty.
 - NVIM v0.9.4

**Additional context**
If anything else is needed, ask and I'll pass it back!

**Comment by siduck** [comment]
share that bash script here

**Comment by ssepi0l-pv** [comment]
Sure: https://paste.rs/wovXM

**Comment by 4nt11** [comment]
Btw: I've started to see this behavior occur too when I paste code from other places. For example, from my Logseq diary. Although in that case, it tends to be pretty random, and I might have an idea as to why this occurs. I manully set the shift width of my tabs to 8.

```lua
vim.cmd('set shiftwidth=8')
```

That's the only change I've made to the entire config (apart from colorscheme ofc). Deleted that line and all is good. Had to replace all spaces with tabs lol, but it was an issue in my end.

**Comment by siduck** [comment]
@ssepi0l-pv obviously! if you're setting that to 8, then you got to do it to all tab related options from core/init.lua

![image](https://github.com/NvChad/NvChad/assets/59060246/632ad5a5-8977-4f8f-8523-2bf36392fd9a)

**Comment by 4nt11** [comment]
@siduck lol you're right, I modified the core/init.lua file and now we're gooood :) thank you.

**Comment by siduck** [comment]
@ssepi0l-pv always make changes in custom dir only, not files outside it or else  nvchad updater wont work!
