### ISSUE TITLE
Unable to assemble

### ISSUE THREAD

**Issue by DameerGamlet** [siduck76/NvChad#2479]
**Describe the bug**
![image](https://github.com/NvChad/NvChad/assets/74682814/aebafb5a-aa8e-43a5-8ff1-b6cdbf8559c6)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
please rm -rf all old nvim dirs before cloning nvchad
