### ISSUE TITLE
toggle a specific terminal buffer

### ISSUE THREAD

**Issue by siduck76** [siduck76/NvChad#248]
![image](https://user-images.githubusercontent.com/59060246/129442133-62a777a9-68d9-41c5-aa65-82d3404789af.png)

toggle a terminal ( these terminal buffers arent opened by toggleterm) with a mapping.

**Comment by siduck76** [comment]
https://github.com/siduck76/NvChad/issues/247 should be fixed first , then this!

**Comment by G-Rowell** [comment]
Assign me!

**Comment by G-Rowell** [comment]
Hmmmm, 
so what do you mean by `toggle a terminal buffer`?

Do you mean similar behaviour to `toggleterm`?

**Comment by siduck76** [comment]
> Hmmmm,
> so what do you mean by `toggle a terminal buffer`?
> 
> Do you mean similar behaviour to `toggleterm`?

yes

**Comment by siduck76** [comment]
> Hmmmm,
> so what do you mean by `toggle a terminal buffer`?
> 
> Do you mean similar behaviour to `toggleterm`?

hide the active terminal buffer

**Comment by G-Rowell** [comment]
So `nvim-toggleterm.lua` is something that toggles terminals (hide and brings them back nicely),
so it doesn't really make sense to want `toggle term functionality without toggle term`,

`nvim-toggleterm.lua` is really great, and can do lots of stuff without being bloated at all

**Comment by siduck76** [comment]
> So `nvim-toggleterm.lua` is something that toggles terminals (hide and brings them back nicely),
> so it doesn't really make sense to want `toggle term functionality without toggle term`,
> 
> `nvim-toggleterm.lua` is really great, and can do lots of stuff without being bloated at all

we cant toggle terminals not created by toggleterm tho :/
