### ISSUE TITLE
Error installing NvChad on Ubuntu Server

### ISSUE THREAD

**Issue by DameerGamlet** [siduck76/NvChad#2481]
**Describe the bug**
Error installing NvChad on Ubuntu Server

1. Clonor nvchad with the latest version (as of Nov. 6)
2. Get the error and do nothing else.

**Expected behavior**
Expecting to get a nice shell for neovim

**Screenshots**
Displayed error:
![image](https://github.com/NvChad/NvChad/assets/74682814/a54d1a98-8561-4982-908a-672780546e5c)

Version vim:
![image](https://github.com/NvChad/NvChad/assets/74682814/4ca1f037-4e64-4f23-9f76-aa17d39ee7bb)

Version nvim:
![image](https://github.com/NvChad/NvChad/assets/74682814/5f7faa6f-c416-455a-b402-249054f0f551)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS x86_64
 - Terminal: Tilix
 - Version of Neovim: 0.9.4

**Additional context**
The command: rm -rf ~/.local/share/nvim and clearing the configuration directory does not help.

**Comment by siduck** [comment]
open neovim and run `lua vim.print(vim.version)` command, show output here

**Comment by DameerGamlet** [comment]
> open neovim and run `lua vim.print(vim.version)` command, show output here

![image](https://github.com/NvChad/NvChad/assets/74682814/57e5eaf3-8516-418c-95cd-a2474b0f2d19)

**Comment by DameerGamlet** [comment]
`
> neovim
zsh: command not found: neovim
`

**Comment by DameerGamlet** [comment]
Might help you understand the problem in some way

```bash
> where vim
/usr/bin/vim
/bin/vim

> where nvim
/usr/local/bin/nvim
```

**Comment by siduck** [comment]
show me output of `nvim -v`

**Comment by siduck** [comment]
i think the issue is with vim, you are not opening nvim during bootstrap, please uninstall vim too

**Comment by DameerGamlet** [comment]
The problem was solved by another way of installing neovim (vim had no problems). Before it was from the apt repository, I installed it from a tar.gz archive and everything worked

**Comment by siduck** [comment]
oh obviously, you should neovim 0.9.4 so i thought you had latest version of neovim
