### ISSUE TITLE
Issue with fzf in Void Linux.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2487]
**The bug**
Assalamu Alaikum, I hope the days of the contributors are going well. Unfortunately, My NvChad is not functioning correctly. I recently have switched from Arch Linux to Void Linux. And after installing NvChad, I am having problems with telescope.nvim.
Here is the error I get when I press `space+th` to change the colorscheme:
```
Failed to run `config` for telescope.nvim

...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ...hare/nvim/lazy/telescope-fzf-n
ative.nvim/lua/fzf_lib.lua:11: /home/USER/.local/share/nvim/lazy/telescope-fzf-native.nvim/lua/../build/libfzf.so: cannot open shared object file:
No such file or directory

# stacktrace:
  - /telescope.nvim/lua/telescope/_extensions/init.lua:10 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:62 _in_ **load_extension**
  - .config/nvim/lua/plugins/init.lua:247 _in_ **config**
```
I did try to install fzf with this command:
```bash
sudo xbps-install fzf
```
But sadly it didn't work. Hoping for a quick solution.
Thanks.

**To Reproduce**
I think, it should only happen when your trying install NvChad with Void Linux.

**Desktop Information**
 - Void Linux. Kernel: 6.5.10_1
 - Alacritty
 - NVIM v0.9.4

**Comment by siduck** [comment]
wa alaykum as salam wa rehmatullahi wa barakatuh, you dont need fzf to use the fzf plugin, just install "make" package. and make sure you have gcc

if nothing works, then navigate to the local dir where fzf-native.nvim is present, cd into it and run make
