### ISSUE TITLE
untoggle specific terminal buffers via telescope

### ISSUE THREAD

**Issue by siduck76** [siduck76/NvChad#249]
This should be fixed after https://github.com/siduck76/NvChad/issues/247.

What if the user has 5+ terminal buffers hidden and wants to untoggle one specific buffer? 

All the terminal buffers toggled ( hidden ) shall show in telescope , something similar to this 

![image](https://user-images.githubusercontent.com/59060246/129442423-a0a3f2e2-57be-445f-8a9c-9a14bf43f0c6.png)
 
 and selecting a buffer in the list here would untoggle it.

**Comment by G-Rowell** [comment]
Assign me!
