### ISSUE TITLE
Install Bug

### ISSUE THREAD

**Issue by niceEli** [siduck76/NvChad#2496]
**Describe the bug**
When installing i got this error

**To Reproduce**
1. install nvchad on debian
2. get error

**Expected behavior**
Install should succeed

**Output**
Error detected while processing /home/niceeli/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/niceeli/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocmd' (a nil value)
stack traceback:
        /home/niceeli/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/niceeli/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue

**Desktop (please complete the following information):**
 - Debian using Fish (WSL2)
 - Windows Terminal
 - 0.6.1-3

**Additional context**
after the error nothing works it just looks like default VI
![Screenshot 2023-11-15 092209](https://github.com/NvChad/NvChad/assets/78963198/8696bbf8-dd06-4270-a2e3-f4b11a43405e)

**Comment by moisesmorillo** [comment]
@niceEli make sure you are using Neovim 0.9.x as described in the install documentation https://nvchad.com/docs/quickstart/install
