### ISSUE TITLE
cursorline support

### ISSUE THREAD

**Issue by LinuxIsCool** [siduck76/NvChad#2497]
The following is not working to turn on vim cursorline:
```
:set cursorline!
```

How can I turn cursorline on?

There's no docs in nvchad on cursorline. I'm not sure how to debug this. 

![image](https://github.com/NvChad/NvChad/assets/31582215/d9141db4-1370-4f7c-8613-19015b9c18b8)

**Comment by siduck** [comment]
@LinuxIsCool go to chadrc and add bg color for Cursorline hl group.  in hl_override

**Comment by 10-SH** [comment]
![image](https://github.com/NvChad/NvChad/assets/22722321/203662f0-12a9-4263-a161-7fc282cfe044)
![image](https://github.com/NvChad/NvChad/assets/22722321/7ed622d0-43b5-48d5-b925-f9c4cfcc5176)

like this.

**Comment by LinuxIsCool** [comment]
I can't seem to get it working.

![image](https://github.com/NvChad/NvChad/assets/31582215/567700f8-cf56-41e4-8c07-0d2a9ea08d2e)

**Comment by siduck** [comment]
because it should be added in hl_override . pls read docs all of you https://nvchad.com/docs/config/theming
