### ISSUE TITLE
This error will be reported when using luasnip

### ISSUE THREAD

**Issue by amistyrain** [siduck76/NvChad#250]
![image](https://user-images.githubusercontent.com/16816655/129447609-328cc81f-4500-4620-86b0-2efc4d2ea714.png)

**Comment by JustSage** [comment]
We are currently investigating it. 
This occurs since [c7fdd68](https://github.com/siduck76/NvChad/commit/c7fdd680729ced2a3805f9aacd8c9910a902de1d)

**Comment by siduck76** [comment]
@amistyrain update your nvchad config and let me know if the problem is still there!
