### ISSUE TITLE
Statusline Displaying Incorrectly for 'default' and 'minimal'

### ISSUE THREAD

**Issue by grantsama** [siduck76/NvChad#2501]
I'd like to preface this by saying I've never created a bug report on github before or made any open source contributions. If I've done anything incorrectly, kindly let me know and I'll do my best to fix it.

**The Thing Being Weird**
Using the included statusline themes, the separator symbols are miscolored for the 'default' and 'minimal' presets. 

**Screenshots**
![default](https://github.com/NvChad/NvChad/assets/93460502/7d5b271e-5a42-4802-b847-5f741dd4b0ae)

![minimal](https://github.com/NvChad/NvChad/assets/93460502/2e7ab316-6959-4e38-a272-72d53c2fa5c1)

**Steps to reproduce the behavior**
1. Edit lua/core/default_config.lua and under statusline set theme to "default" or "minimal". 
2. Set separator_style to any of the valid options listed in the file's comments.
3. Write changes and restart neovim.
4. You should see incorrectly colored separator symbols

**Expected behavior**
The separator symbols should match the colors of the blocks.

**Desktop**
 - Operating System: Arch
 - Terminal: Kitty
 - Version of Neovim: 0.9.4

**Additional context**
'vscode' and 'vscode_colored' work perfectly fine.

overridden_modules is set to nil. Not sure if this matters.

I'm using the included gruvbox theme. Again, not sure if this matters. Who knows though, maybe the colors are referenced incorrectly for this one theme.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/62ac0850-8ee0-4de1-8f0d-e4c4a1178ca3


unable to reproduce both on v2.0 and v3.0 beta. Please make a video of it! also please save custom config with neovim only or else nothing of base46 stuff will re-compile & reload
