### ISSUE TITLE
when using vim-fugitive without a file open, highlight goes wrong

### ISSUE THREAD

**Issue by umlx5h** [siduck76/NvChad#2505]
**Describe the bug**

If I use [vim-fugitive](https://github.com/tpope/vim-fugitive) without ever opening a file, the highlight goes wrong.
Normally in git diff, red represents deletions and green represents additions, but right after startup, red is for additions. 

Since this problem does not occur in kickstart, I believe it is related to nvchad-specific lazy-load stuff of highlighting. (kickstart.nvim has fugitive by default)

I would like to fix this problem because sometimes I use neovim even when I just want to use fugitive.

**To Reproduce**

#### 1. freshly install nvchad and install fugitive

install nvchad to `.config/nvim_nvchad`
```
git clone https://github.com/NvChad/NvChad ~/.config/nvim_nvchad --depth 10
NVIM_APPNAME=nvim_nvchad nvim
```

install fugitive

```
$ cd ~/.config/nvim_nvchad
$ vi lua/custom/plugins.lua
  {
    "tpope/vim-fugitive",
    event = "VeryLazy",
  },
# install plugin
$ NVIM_APPNAME=nvim_nvchad nvim
```

#### 2. Make some changes to arbitrary git repo

make changes to nvchad repo

```diff
$ cd ~/.config/nvim_nvchad
$ grep -v '^--' init.lua | sponge init.lua
$ echo '-- text add!' >> init.lua
$ diff --git a/init.lua b/init.lua
index 21f0b6f..39c361b 100644
--- a/init.lua
+++ b/init.lua
@@ -10,7 +10,6 @@ require("core.utils").load_mappings()

 local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"

--- bootstrap lazy.nvim!
 if not vim.loop.fs_stat(lazypath) then
   require("core.bootstrap").gen_chadrc_template()
   require("core.bootstrap").lazy(lazypath)
@@ -19,3 +18,4 @@ end
 dofile(vim.g.base46_cache .. "defaults")
 vim.opt.rtp:prepend(lazypath)
 require "plugins"
+-- text add!

```

#### 3. Open fugitive

**without opening any file, highlight goes wrong.**
```
$ NVIM_APPNAME=nvim_nvchad nvim

# laungh fugitive from vim command line
$ :Git
$ press '=' on init.lua to view inline diff
```

delete: blue, add: red
![fugitive-status-red](https://github.com/NvChad/NvChad/assets/20206121/422eb72d-0992-4ce3-8d38-a60809178c5f)

**with opening any file, highlight is OK.**
```
# open file
$ NVIM_APPNAME=nvim_nvchad nvim LICENSE

# laungh fugitive from vim command line
$ :Git
$ press '=' on init.lua to view inline diff
```

delete: red, add: green
![fugitive-status-green](https://github.com/NvChad/NvChad/assets/20206121/13f7371b-e644-418b-9def-47a93f5216d9)

I have confirmed that the same highlighting goes wrong with the `Git log` command.

**Expected behavior**
It should be the same highlight even if you never opened the file.

**Desktop (please complete the following information):**
 - Operating System
 WSL2
 - Terminal
 wezterm
 - Version of Neovim
 NVIM v0.10.0-dev

**Comment by siduck** [comment]
nvchad's diff highlights are loaded on gitsigns plugin,  ig just load `dofile(vim.g.base46_cache .. "git")` , so put that in your config function of vim fugitive

**Comment by umlx5h** [comment]
thanks, I confirmed it work like this.
```
{
    "tpope/vim-fugitive",
    event = "VeryLazy",
    cmd = { "G", "Git" },
    config = function(_, _)
      dofile(vim.g.base46_cache .. "git")
    end,
    dependencies = {
      "tpope/vim-rhubarb",
    },
},
```

**Comment by siduck** [comment]
@umlx5h from your code it seems like its lazyloaded on certain CMDS, so remove the event line

**Comment by umlx5h** [comment]
I have defined the following alias and have set up CMD to start fugitive from the shell :)
```
alias G="nvim -c 'vert Git' ."
```
