### ISSUE TITLE
command recommendation not working

### ISSUE THREAD

**Issue by muhssamy** [siduck76/NvChad#2506]
I'm new to the world of configurations and I'm encountering a simple issue, which might be due to my inexperience. 
Previously, when I typed any command such as :MasonInstallAll, I would see suggestions. However, this has now stopped.

![image](https://github.com/NvChad/NvChad/assets/49695385/2bb49703-4ba5-4ea6-ae22-82a6f138adc2)

**Comment by siduck** [comment]
make sure mason is installed, and press tab

**Comment by muhssamy** [comment]
it is not related to Mason it was only an example
if i tried :CheckHealth also while typing there is no suggestions
![image](https://github.com/NvChad/NvChad/assets/49695385/0c7cb9ec-b41c-4ded-b237-4bc275daa769)

**Comment by siduck** [comment]
@muhssamy why is you tabline broken? try doing a clean install of nvchad and show a video that the completions dont work, just screenrecord it

**Comment by muhssamy** [comment]
Thanks :)
 i removed nvchad and re-cloned it again and everything is fine.
