### ISSUE TITLE
nvchad hanging on opening certain files.

### ISSUE THREAD

**Issue by amardhruva** [siduck76/NvChad#2509]
**Describe the bug**
Opening files with certain symbols will cause nvim to hang and use up several GB of RAM causing the system to go unresponsive
**To Reproduce**
1. Open the file attached in neovim (its from gnome-software source code. I had to zip it because github does not accept .po extension)

**Expected behavior**
You should be able to edit the file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System Ubuntu 23.10
 - Terminal gnome-terminal
 - Version of Neovim
 NVIM v0.9.1 snap
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

[hi.zip](https://github.com/NvChad/NvChad/files/13430429/hi.zip)

**Additional context**
you can edit the file in non nvchad neovim
The file is from https://gitlab.gnome.org/GNOME/gnome-software 
I tried a few more files and it seems to hang on hu.po too.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/837c332c-9556-40f0-8312-da92d8921fb9

unable to produce, make sure you have proper noto fonts

**Comment by amardhruva** [comment]
For the people having similar issue. The bug is caused by the snap being outdated :(. You can manually build the snap and install 0.9.4 to fix it.

**Comment by siduck** [comment]
@amardhruva use bob to manage nvim versions on ubuntu,never use snap!

**Comment by amardhruva** [comment]
@siduck Thanks for the recommendation. Bob is great but needs clearer docs. I just switched to arch now to keep nvim up to date lol.
Great job maintaining nvChad btw
