### ISSUE TITLE
v3.0 branch - ready for use?  Gotchas?

### ISSUE THREAD

**Issue by HaleTom** [siduck76/NvChad#2510]
I'm just starting out with NvChad.  Is the v3.0 branch ready for common usage?

What are the main differences to v2.0?

For those upgrading from 2.0 to 3.0, is there anything they should be aware of?

[Related: I opened issue [Example config for v3.0](https://github.com/NvChad/example_config/issues/41)  in NvChad/example_config.

**Comment by siduck** [comment]
its ready to use but not documented. So be patient and wait when it releases :v
