### ISSUE TITLE
Make mason PATH behavior configurable

### ISSUE THREAD

**Issue by gbbirkisson** [siduck76/NvChad#2511]
**Is your feature request related to a problem? Please describe.**

When working in a python virtual environment, I want the tools installed in that environment to take precedence over the tools installed with mason. I stumbled across this because I have a python project that uses `mypy` extensions, but those extensions are not available with the mason `mypy`. I still want the mason `mypy` to serve as a fallback when a project does not have `mypy` installed.

I can see that mason is configured by default to [skip](https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/mason.lua#L4) messing with the path and NvChad is [hard coded](https://github.com/NvChad/NvChad/blob/9d37797e6f9856ef25cfa266cff43f764e828827/lua/core/init.lua#L61) to append it. Is there any reason in particular for setting the path manually instead of mason doing it for us?

**Describe the solution you'd like**

Remove this [hard coded](https://github.com/NvChad/NvChad/blob/9d37797e6f9856ef25cfa266cff43f764e828827/lua/core/init.lua#L61) thing, and set `PATH="append"` in the [default mason config](https://github.com/NvChad/NvChad/blob/v2.0/lua/plugins/configs/mason.lua#L4). That way the user can configure this behaviour.

Alternatively provide a way to disable this [hard coded](https://github.com/NvChad/NvChad/blob/9d37797e6f9856ef25cfa266cff43f764e828827/lua/core/init.lua#L61) intervention.

**Describe alternatives you've considered**

My nasty workaround currently is to change the path in my custom config `init.lua`:

```lua
-- Move mason path to the back
local mason_path = vim.fn.stdpath "data" .. "/mason/bin"
vim.env.PATH = vim.env.PATH:gsub(mason_path .. ":", "")
vim.env.PATH = vim.env.PATH .. ":" .. mason_path
```

**Additional context**

N/A

**Screenshot**

N/A

**Comment by siduck** [comment]
mason is lazyloaded in nvchad, as its just used to download things. So as a result if mason isnt loaded on startup then all lsp binaries etc wont be on path too, resulting in some errors by lspconfig etc

**Comment by siduck** [comment]
so just add vim.env.PATH stuff in custom/init.lua, replace the default path with your string

**Comment by gbbirkisson** [comment]
Allrighty. Thank you :pray:
