### ISSUE TITLE
Add support for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ayushxx7** [siduck76/NvChad#2514]
**Is your feature request related to a problem? Please describe.**
I clone the repo in WSL, and I get this error and on launch I get this error
```
Error detected while processing /home/ayush/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/ayush/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocmd' (a
nil value)
stack traceback:
        /home/ayush/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/ayush/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue
```

**Describe the solution you'd like**
Should be able to run directly after clone

**Describe alternatives you've considered**
Fixing the error manually by understanding code flow

**Additional context**
![image](https://github.com/NvChad/NvChad/assets/16764027/de95b920-127d-4b25-88bb-98f161ebd823)
![image](https://github.com/NvChad/NvChad/assets/16764027/f9a3de65-839d-4a52-978a-b1a11f456db0)

**Comment by siduck** [comment]
nvchad supports nvim v0.9 and above only, make sure you install that. 

![image](https://github.com/NvChad/NvChad/assets/59060246/a88056c5-1955-46bc-8cb9-1bac1885c102)

**Comment by DrTeagle** [comment]
heres how you do that (by using nightly)
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
