### ISSUE TITLE
Could NvChad add language outline?

### ISSUE THREAD

**Issue by d3vw** [siduck76/NvChad#2515]
Hi 👋 A small question.

I used vscode before, and its outline is very helpful for me to understand the code.

I am a new bie, how can I see the outline?
look like this:
![image](https://github.com/NvChad/NvChad/assets/70519059/6e3a0f2c-2488-4f1e-8c0f-8c72ef5f7e31)

**Comment by siduck** [comment]
just add symbols outline plugin in custom plugins
