### ISSUE TITLE
Crashing because of some 'nil' value

### ISSUE THREAD

**Issue by developer-kush** [siduck76/NvChad#2516]
**Describe the bug**
After i cloned the repository and opened nvim, i got an error and no request to install example config files.

**To Reproduce**
1. Use the following installation command : `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1`
2. Start neovim using `nvim`
3. See error

**Expected behavior**
A message asking (y/n) for if we want to start with the example lua files.

**Screenshots**

![Screenshot from 2023-11-24 10-01-03](https://github.com/NvChad/NvChad/assets/94402194/ca611d6e-973f-4e2b-b786-96a3d29ce545)

**Desktop (please complete the following information):**
 - Operating System : Ubuntu 22.04
 - Terminal : GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEM
 - Version of Neovim : 
 ```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/46016728-f71f-4a32-b0e1-1f4998cc4e5c)
![image](https://github.com/NvChad/NvChad/assets/59060246/2b3ec814-f0c3-4448-8fa6-9b75f1f70fb2)

pls read docs :(
