### ISSUE TITLE
Wrong representation of long Unicode file names near `..` in `tabufline` tab

### ISSUE THREAD

**Issue by Andrew15-5** [siduck76/NvChad#2518]
**Describe the bug**
A Unicode multibyte character seems to be divided into bytes, and separate byte(s) of a single character is/are shown in the tab of the `tabufline` NvChad plugin. So the `файлов_ый_файл1` file is shows as `файлов_<d1>..` instead of `файлов_..` or `файлов_ы..`.

**To Reproduce**
1. `\nvim файлов_ый_файл1 файл2`
2. See error

**Expected behavior**
a `<d1>` byte should not be present, only Unicode characters.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/37143421/538d81e3-5a22-4f77-82b6-fa2900369a25)

**Desktop (please complete the following information):**
 - Operating System: Pop!_OS 22.04
 - Terminal: kitty
 - Version of Neovim: 0.9.4

**Additional context**
Without the `_` in the file name, it doesn't look like I can reproduce the issue.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/91af2bd5-504e-4030-aa11-8fce872ee6e5)


bring forth another function to trim chars

**Comment by siduck** [comment]
so not a nvchad issue

**Comment by Andrew15-5** [comment]
> bring forth another function to trim chars

You mean "suggest another function to trim chars"?

Here is a working example of extracting a substring with 7 or 8 Unicode characters:

```lua
local str = "файлов_ый_файл1"
local codepoint_start_index_list = vim.str_utf_pos(str)
-- local length = 7
local length = 8
local start_index = codepoint_start_index_list[length]
print("start_index:", start_index)
local end_index_offset = vim.str_utf_end(str, start_index)
print("end_index_offset:", end_index_offset)
local end_index = start_index + end_index_offset
print("end_index:", end_index)
print(string.sub(str, 1, end_index))
````

**Comment by siduck** [comment]
but this doesnt work  with en words if they are shorter than the length, we probably need to add some if checks

**Comment by Andrew15-5** [comment]
Of course. This is just a quick prototype.

**Comment by siduck** [comment]
i hope there isnt any performance drop by any ms :laughing:

**Comment by Andrew15-5** [comment]
Each tab name is only calculated once, right? And it all pure Lua code. I think it will be fine.

**Comment by siduck** [comment]
> Each tab name is only calculated once, right? And it all pure Lua code. I think it will be fine.

yep, i did some benchmark and ran it more than 5 times

![image](https://github.com/NvChad/NvChad/assets/59060246/38208d08-d5de-4029-9c8f-a0fbcb0b7b2f)

**Comment by siduck** [comment]
```lua
local function abc()
	local str1 = "siduck_ng.lua"
	local o = string.sub(str1, 1, 14)
end

local function xyz()
	local str2 = "siduck_ng.lua"
	local codepoint_start_index_list = vim.str_utf_pos(str2)
	local start_index = codepoint_start_index_list[11]
	local end_index = codepoint_start_index_list[11] + vim.str_utf_end(str2, start_index)
	local n = string.sub(str2, 1, end_index)
  print(n)
end

local function benchmark(func)
	local before = os.clock()

	func()

	local after = os.clock()

	return string.format("Loop took %0.6f seconds to run", after - before)
end

print(" substr: " .. benchmark(abc))
print(" utf: " .. benchmark(xyz))
```

open nvim and run `luaeval %` command, show me output

**Comment by Andrew15-5** [comment]
`luaeval` isn't a `:luaeval` command, but rather `echo luaeval()`. And I used `source %` instead.

<details><summary>output</summary>
<p>

```
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000012 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000013 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000018 seconds to run
 substr: Loop took 0.000003 seconds to run
siduck_ng.l
 utf: Loop took 0.000011 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000009 seconds to run
 substr: Loop took 0.000002 seconds to run
siduck_ng.l
 utf: Loop took 0.000010 seconds to run
```

</p>
</details>

**Comment by siduck** [comment]
> `luaeval` isn't a `:luaeval` command, but rather `echo luaeval()`. And I used `source %` instead.
> 
> output

oh my bad, its luafile
