### ISSUE TITLE
Angular LSP Not Working

### ISSUE THREAD

**Issue by deenath** [siduck76/NvChad#2519]
**Describe the bug**

I was successfully able to install and use NvChad with the typescript language server and everything. But I was facing issues while using the angular-language-server. I've used other distro's and the angular lsp works fine with it. But only on NvChad it throws me an error with minimum typescript version or the lsp is not installed in the project. And later I did try to install the lsp both globally and on the project level as well.

After installing it on the project level and the lsp did load but it wasn't giving any autocompletions on the html files.

<img width="1687" alt="Screenshot 2023-11-25 at 6 46 05 PM" src="https://github.com/NvChad/NvChad/assets/8143269/1640cc6a-0528-40d1-83a0-3eb77568ffbb">

**To Reproduce**

1. Install `angular-language-server` and do not install `@angular/language-service` as project dependency
2. Open any html file in an angular project

**Expected behavior**

After installing the angular lsp it was supposed to work fine and it does works fine with all the projects of mine on the other distro's but only with NvChad I was getting this error if the `@angular/language-service` wasn't installed in the project's dependency. And after installing it as a dependency, it doesn't work as well.

**Screenshots**

<img width="1689" alt="Screenshot 2023-11-25 at 6 50 31 PM" src="https://github.com/NvChad/NvChad/assets/8143269/a93ef21a-72f0-46a8-a701-a051a680d7c9">

**Desktop (please complete the following information):**

 - Operating System: macOS 14.0
 - Terminal: iTerm2
 - Version of Neovim: v0.9.1

**Additional context**

I tested the same scenario with another mac, I got the same problem.

The same angular lsp working fine on a different distro.

<img width="975" alt="Screenshot 2023-11-25 at 6 59 43 PM" src="https://github.com/NvChad/NvChad/assets/8143269/4e1229f6-b033-4b40-98a9-10c4255e029d">

I'm not sure if I'm missing any steps on configuring the lsp in NvChad, attaching a screenshot of the lua config.

<img width="1690" alt="Screenshot 2023-11-25 at 7 05 09 PM" src="https://github.com/NvChad/NvChad/assets/8143269/d29b3b4a-7ee7-48b4-ac4c-17f86fb38c61">

**Comment by siduck** [comment]
show lspInfo output

**Comment by deenath** [comment]
![Uploading Screenshot 2023-11-25 at 7.34.59 PM.png…]()

**Comment by deenath** [comment]
Here

<img width="1338" alt="Screenshot 2023-11-25 at 7 34 59 PM" src="https://github.com/NvChad/NvChad/assets/8143269/f6d1be62-8fcf-4ff5-a55c-ca8f7355227d">

**Comment by siduck** [comment]
hmm looks fine to me :/

do other completions work?

**Comment by deenath** [comment]
Yea, it does. Here's an screenshot of the typescript file.

<img width="660" alt="Screenshot 2023-11-25 at 8 05 53 PM" src="https://github.com/NvChad/NvChad/assets/8143269/0374eaf4-ceab-4d3a-8fe0-1464bbf61d22">

**Comment by siduck** [comment]
so what is even *?  if you want to get list of available completions then press ctrl space

**Comment by deenath** [comment]
It's not just the auto completions, the entire lsp is not working. And pressing ctrl + space as well doesn't show the completions of the angular lsp.

**Comment by siduck** [comment]
idk then , i dont use angular so cant help..  can u try it on https://github.com/NvChad/tinyvim ? its a minimal nvim config ( not nvchad )

**Comment by siduck** [comment]
ok i get it now, you didnt setup tsserver.  Please ask such small issues on discord server etc! as these are not nvchad's fault!

**Comment by deenath** [comment]
tsserver is installed and configured as well. On the lspinfo screenshot above you can see it. I feel the problem is happening only on the NvChad distro.

**Comment by siduck** [comment]
> tsserver is installed and configured as well. On the lspinfo screenshot above you can see it. I feel the problem is happening only on the NvChad distro.

nvchad only sets up the lua lsp, doe sit work with tinyvim? please try. Also ask in our discord server.

Does angular lsp work the same on all other distros or just that one distro you tried?

**Comment by deenath** [comment]
I got the same error using tinyvim from the screenshot I attached above under the screenshot section. Attaching the lspinfo.

I always get this when I open html or typescript file at the bottom in both NvChad & tinyvim.

<img width="1019" alt="Screenshot 2023-11-26 at 5 42 30 PM" src="https://github.com/NvChad/NvChad/assets/8143269/68a562e2-48f9-4ad7-a034-f6619e4c32ee">

LspInfo

<img width="1336" alt="Screenshot 2023-11-26 at 5 30 58 PM" src="https://github.com/NvChad/NvChad/assets/8143269/b6a84355-111e-49c7-b413-247bf8378750">

Mason & lspconfig lua

<img width="1688" alt="Screenshot 2023-11-26 at 5 38 00 PM" src="https://github.com/NvChad/NvChad/assets/8143269/dbbdbf24-b058-4342-9d0a-6b7575c6da0d">


I've tried with LazyVim. it's working fine. And I cloned kickstart nvim as well and installed angular lsp and it works fine.

Can you try to load the angular lsp on a new angular project and check for yourself once? Because in the other 2 places I installed, I used the default config and it was loaded the lsp without any error.

Screenshot from kickstart.

<img width="1019" alt="Screenshot 2023-11-26 at 5 40 31 PM" src="https://github.com/NvChad/NvChad/assets/8143269/c98c140e-5485-424b-9f71-f3ad4a5909f7">

**Comment by siduck** [comment]
ugh its using mason lspconfig trickery :exploding_head: 

can you try lazyvim...

**Comment by siduck** [comment]
LspLog shows this 

![image](https://github.com/NvChad/NvChad/assets/59060246/91ad358d-1b4e-4025-8125-bbc0594131b3)

**Comment by deenath** [comment]
Yea, I saw the mason lspconfig additionally in that. And yes, it works fine on LazyVim as well.

LazyVim config, I'm not sure how it's working. But apart from the `ensure_installed` I haven't referenced angularls in the config anywhere else. And it's still working fine. 

LazyVim lsp config

<img width="762" alt="Screenshot 2023-11-26 at 6 05 45 PM" src="https://github.com/NvChad/NvChad/assets/8143269/20b8ec6c-9edf-4c85-944a-cd1490caf46a">

Yea, I get the same error as what you've posted now. And I did even try to install different versions of `angular-language-server` and still keep getting this error. But under kickstart and lazyvim I don't get this minimum version which is mentioned at the end of the 1st line in the screenshot you've posted. And the same version of the angularls is installed under kickstart and lazyvim as well and works fine.

If this is issue is like unsolvable, is there a way I can use only the NvChad UI repo in a different standalone nvim? I really do like the NvChad UI. I appreciate the work a lot for this distro.

**Comment by siduck** [comment]
wait, i'm investigating this. it looks like a common issue faced by non nvim users too

**Comment by deenath** [comment]
Okay, cool.

**Comment by siduck** [comment]
```lua

local install_path = vim.fn.stdpath "data" .. "/mason/packages/angular-language-server/node_modules"
-- local cwdpath = vim.fn.getcwd() .. "/node_modules"
local ang = install_path .. "/@angular/language-server/node_modules"

local cmd = {
  "ngserver",
  "--stdio",
  "--tsProbeLocations",
  install_path,
  "--ngProbeLocations",
  ang,
}

lspconfig.angularls.setup {
  on_attach = on_attach,
  cmd = cmd,
  on_new_config = function(new_config, new_root_dir)
    new_config.cmd = cmd
  end,
}
```

**Comment by siduck** [comment]
fyi default cmd in lspconfig for angular ls has empty strings 

![image](https://github.com/NvChad/NvChad/assets/59060246/46380ac4-c725-4378-b45d-8848c7628619)

**Comment by siduck** [comment]
the reason it worked with kickstart, lazyvim is that they use mason-lspconfig and that plugin itself manages the lspconfig stuff too

look it changes the cmd path

![image](https://github.com/NvChad/NvChad/assets/59060246/89500f46-3d19-4243-9ceb-f05dfb5147f2)


i noticed this when the cmd value in LspInfo of kickstart.nvim was different... 

So after all this wasnt nvchad issue!!!!

**Comment by deenath** [comment]
Wow, thanks a lot for this. It works now. Thanks a lot for the help. I'm new to vim and I tried to solve it by myself but unfortunately I couldn't :sweat_smile:

<img width="762" alt="Screenshot 2023-11-26 at 6 56 26 PM" src="https://github.com/NvChad/NvChad/assets/8143269/0c1991ac-4374-4581-bb05-6a78c78bf6f4">

I hope your answer might help others if they face issue on installing angularls.

Thanks again for the help.
