### ISSUE TITLE
[FEAT] TagBar UI Plugin for NvChad

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [siduck76/NvChad#2520]
## Problem

Currently NvChad does not have a way to quickly get a list of all the method signatures (tags) or classes which can allow us to quickly navigate through a file which has many methods and classes.

## Potential Solution
For consistency with the UI, will it be a good idea to develop a UI plugin for NvChad along the lines of aerial.nvim which can offer something similar to a TagBar

**Comment by siduck** [comment]
just setup it in custom plugins or setup symbols outline.nvim
