### ISSUE TITLE
i need to hide this displayed line on right

### ISSUE THREAD

**Issue by muhssamy** [siduck76/NvChad#2521]
Dear All,
I would appreciate your assistance in removing the line that appears on the right side of the following image. 
Despite extensive internet searches using various keywords, I've been unable to identify the feature that needs to be disabled.
![image](https://github.com/NvChad/NvChad/assets/49695385/0cba6cc4-2f37-42d5-ac9b-aca39d2570d4)

**Comment by siduck** [comment]
its called colorcolumn i think, but we dont enable it anywhere .Probably  you set in custom config or some plugin that you installed sets it, nvchad doesnt set it by default

**Comment by muhssamy** [comment]
thanks, i found it and fixed this Now :)
