### ISSUE TITLE
diagnostics message can't automatically show up in my code when editing C++ files

### ISSUE THREAD

**Issue by ForgotDream** [siduck76/NvChad#2522]
The `clangd` LSP works well, but when I met errors or warnings the diagnostics message can't automatically show up in my code.

For example, the normal diagnostics message should be like this:

![2023-11-26_19-48](https://github.com/NvChad/NvChad/assets/60381827/4ba9ce74-e757-468b-b6bd-ccabe8000c72)

However, the diagnostics message doesn't show up in the code, even in the Normal Mode. But when I reopen the file or delete something with a command like `dd`, it reappears. When I go into Insert Mode, it disappears again.
 
The error is similar to this:

![2023-11-26_19-56](https://github.com/NvChad/NvChad/assets/60381827/b1cc21a2-b19f-4cfc-bbd8-9b8e3581d171)

Nothing was shown. Other features, such as auto-completion, work well.

 - Operating System: Arch Linux
 - Terminal: Konsole
 - Version of Neovim: NVIM v0.9.4

**Comment by siduck** [comment]
show your code, i'll test here.

nvchad doesnt even manage lsps other than lua, so this shouldnt be an issue :/

**Comment by ForgotDream** [comment]
```cpp
#include <bits/stdc++.h>

using i64 = int64_t;

int main() {
  i
  return 0;
}
```

Maybe it's easy to reproduce.

**Comment by ForgotDream** [comment]
> nvchad doesnt even manage lsps other than lua, so this shouldnt be an issue :/

I'm sorry, but I really don't know under which repository it's best to ask this question.

**Comment by siduck** [comment]
> > nvchad doesnt even manage lsps other than lua, so this shouldnt be an issue :/
> 
> I'm sorry, but I really don't know under which repository it's best to ask this question.

ask in discord server

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/01bdf807-0d4e-4eb2-9367-610e15bce3ca


tested here, works fine

**Comment by ForgotDream** [comment]
I found a strange solution to this problem, When I press C-c to exit insertion mode, the diagnostic message doesn't show up, but when I press ESC, it is able to function properly.

**Comment by siduck** [comment]
> I found a strange solution to this problem, When I press C-c to exit insertion mode, the diagnostic message doesn't show up, but when I press ESC, it is able to function properly.

![image](https://github.com/NvChad/NvChad/assets/59060246/0dd00c62-9dcf-49d7-8503-23c1e2fc3337)

diagnostics are updated only at InsertLeave event btw, ESC triggers it C-c doesnt. i suggest you to just map jk to leave insert mode

**Comment by ForgotDream** [comment]
> > I found a strange solution to this problem, When I press C-c to exit insertion mode, the diagnostic message doesn't show up, but when I press ESC, it is able to function properly.
> 
> ![image](https://private-user-images.githubusercontent.com/59060246/285653527-0dd00c62-9dcf-49d7-8503-23c1e2fc3337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDYxMDQsIm5iZiI6MTcwMTAwNTgwNCwicGF0aCI6Ii81OTA2MDI0Ni8yODU2NTM1MjctMGRkMDBjNjItOWRjZi00OWQ3LTg1MDMtMjNjMWUyZmMzMzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEzMzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDhlZmFlMDI1OTBjMmNkNzJiN2I3ZmQ1ZTFiMjYwYzgxZTI0NjBjY2ZmNzU2YWJkYTdmNzllMzBjOTBiNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YDKJO1oBUgrZ030Ds-arwcBVke6DK0E_FZdASaBY-Rs)
> 
> diagnostics are updated only at InsertLeave event btw, ESC triggers it C-c doesnt. i suggest you to just map jk to leave insert mode

thanks a lot, I didn't know about this before.

**Comment by siduck** [comment]
put this in custom lspconfig
 
```lua
vim.diagnostic.config {
  update_in_insert = true,
}
```

this will show diagnostics in insert mode too
