### ISSUE TITLE
'nvim arg' error, where to fix it 

### ISSUE THREAD

**Issue by d3vw** [siduck76/NvChad#2523]
Hi ~ 

I installed the plugin [kawre/leetcode.nvim](https://github.com/kawre/leetcode.nvim.git).

this is my relative plugins.lua

```
  {
    "kawre/leetcode.nvim",
    dependencies = {
        "nvim-telescope/telescope.nvim",
        "nvim-lua/plenary.nvim", -- required by telescope
        "MunifTanjim/nui.nvim",
    },
  },
 ```
 and as the repo, we could open leetcode dashboard by `nvim leetcode.nvim`

But I met
![image](https://github.com/NvChad/NvChad/assets/70519059/742cf12f-f6dc-464a-ba31-40e8e02e7629)

It just open a new file.

How I fix it?

Look forward to your reply, sincerely.

**Comment by d3vw** [comment]
And I can't use `Leet` cmd after I `Lazy load leetcode.nvim`

**Comment by siduck** [comment]
local leet_arg = "leetcode.nvim"

```lua
 {
    "kawre/leetcode.nvim", 
    dependencies = {
        "MunifTanjim/nui.nvim",
     },
    lazy = leet_arg ~= vim.fn.argv()[1],
    opts = {
        arg = leet_arg,
    },
}
```

![image](https://github.com/NvChad/NvChad/assets/59060246/7caa54e3-c93f-439b-bc09-adbd20104829)

**Comment by d3vw** [comment]
Thanks for your kindnesss
