### ISSUE TITLE
There was an error starting nvim after installation in windows

### ISSUE THREAD

**Issue by pCandKa** [siduck76/NvChad#2525]
**Describe the bug**
There was an error starting nvim after installation

**To Reproduce**
```bash
git clone https://github.com/NvChad/NvChad $HOME\AppData\Local\nvim --depth 1 && nvim
```

**Expected behavior**
Error detected while processing C:\Users\pCandKa\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: cannot open C:\Users\pCandKa\AppData\Local\nvim-data/nvchad/base46/defaults: No such file or directory
stack traceback:
        [C]: in function 'dofile'
        C:\Users\pCandKa\AppData\Local\nvim\init.lua:19: in main chunk
Press ENTER or type command to continue

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/69684715/df78caa8-9bb4-4111-8007-471307a259b9)

**Desktop (please complete the following information):**
 - windows11
 - windows Terminal
 - nvim 0.9.2

**Comment by siduck** [comment]
please remove all nvim dirs before installing nvchad

![image](https://github.com/NvChad/NvChad/assets/59060246/53645e4f-0fdb-46eb-b577-192ad9b22a42)
