### ISSUE TITLE
Editor UI fails to render italic fonts

### ISSUE THREAD

**Issue by RomaLzhih** [siduck76/NvChad#2531]
**Describe the bug**
I added some custom highlights in `custom/highlights.lua` as below to enable the italic font for words in the editor. But only the `Comment` option works; all others fail to render. I tried `:hi Function gui=italic` but it still didn't work. 

I use the provided `nord` theme in base32 and required `Hasklug Nerd Font`. 

Any suggestions?

**To Reproduce**
Copy the following code to `custom/highlights.lua` and `custom/chadrc.lua`, respectively and you may reproduce the behavior.

```{lua}
-- To find any highlight groups: "<cmd> Telescope highlights"
-- Each highlight group can take a table with variables fg, bg, bold, italic, etc
-- base30 variable names can also be used as colors

local M = {}

---@type Base46HLGroupsList
M.override = {
  CursorLine = {
    bg = "lightbg",
  },
  TSKeyword = { italic = true },
  TSString = { italic = true },
  TSFunc = { italic = true },
  TSParameter = { italic = true },
  Comment = {
    italic = true,
  },
  Macro = {
    italic = true,
  },
  String = {
    italic = true,
  },
  Keyword = {
    italic = true,
  },
  Function = {
    italic = true,
  },
}

---@type HLTable
M.add = {
  NvimTreeOpenedFolderName = { fg = "green", bold = true },
  String = { italic = true },
}

return M
```
```{lua}
---@type ChadrcConfig
local M = {}

-- Path to overriding theme and highlights files
local highlights = require "custom.highlights"

M.ui = {
  theme = "nord",
  theme_toggle = { "nord" },
  hl_override = highlights.override,
  hl_add = highlights.add,
}

M.plugins = "custom.plugins"

-- check core.mappings for table structure
M.mappings = require "custom.mappings"

return M
```

**Expected behavior**
The stuffs mentioned in `M.override` can be shown in italic.

**Screenshots**
![Weixin Screenshot_20231128202038](https://github.com/NvChad/NvChad/assets/45626759/a5dde143-8ddf-4e0a-bd53-8673ffcbf5e5)

**Desktop (please complete the following information):**
 - Local: Windows, remote: Centos 8
 - Windows Terminal
 - Version of Neovim: 0.8.0

**Comment by siduck** [comment]
try correct highlight group names, for example `['@function']` as per treesitter

**Comment by RomaLzhih** [comment]
Thanks for @siduck's answer, I finally figured out how it works :)
We can use the info. provided by `nvim-treesitter` to highlight the words, i.e.,:
```{lua}
M.override = {
  CursorLine = {
    bg = "lightbg",
  },
  ["@function"] = { italic = true },
  ["@function.call"] = { italic = true },
  ["@keyword"] = { italic = true },
  ["@keyword.return"] = { italic = true },
  ["@string"] = { italic = true },
  ["@storageclass"] = { italic = true },
  ["@type"] = { italic = true },
  ["@type.qualifier"] = { italic = true },
  ["@type.builtin"] = { italic = true },
  ["@type.identifier"] = { italic = true },
  ["@repeat"] = { italic = true },
  ["@parameter"] = { italic = true },
  ["@property"] = { italic = true },
  ["@variable.builtin"] = { italic = true },
  Comment = {
    italic = true,
  },
}
``` 
To check the tree sitter info of a word, we can use a [plug](https://github.com/nvim-treesitter/playground). If u have neovim version greater than 0.9, you can directly type `:Inspect`.

Cheers!
