### ISSUE TITLE
Remapping plugin keys is not deterministic

### ISSUE THREAD

**Issue by NiklasKappel** [siduck76/NvChad#2533]
**Describe the bug**
I set the following in `~/config/nvim/lua/custom/mappings.lua`:
```
M.nvimtree = {
  plugin = true,
  n = {
    ["<Leader>e"] = { "<cmd> NvimTreeToggle <CR>", "Toggle nvimtree" },
  },
}

require("core.utils").load_mappings "nvimtree"
```
Sometimes when I start nvim (about 30% of the time) the mapping works. `<Space>e` toggles nvim-tree and `map <Leader>e?` outputs `n  <Space>e    * <Cmd> NvimTreeToggle <CR>`. But most of the time the mapping does not work. `<Space>e` focuses nvim-tree and `map <Leader>e?` outputs `n  <Space>e    * <Cmd> NvimTreeFocus <CR>`.

**To Reproduce**
1. Install NvChad as described in the [docs](https://nvchad.com/docs/quickstart/install).
2. Let NvChad generate the example custom config.
3. Use the following `~/config/nvim/lua/custom/mappings.lua`:
```
---@type MappingsTable
local M = {}

M.nvimtree = {
  plugin = true,
  n = {
    ["<Leader>e"] = { "<cmd> NvimTreeToggle <CR>", "Toggle nvimtree" },
  },
}

require("core.utils").load_mappings "nvimtree"

return M
```
4. Start nvim, press `<Space>e` a few times, quit nvim, repeat. Only sometimes nvim-tree will toggle.

**Expected behavior**
nvim-tree should toggle always as set in `custom/mappings.lua`.

**Desktop (please complete the following information):**
 - Operating System: Fedora Silverblue 39
 - Terminal: Gnome terminal
 - Version of Neovim: NVIM v0.9.4

**Comment by NiklasKappel** [comment]
**Additional observations**
1. Removing `require("core.utils").load_mappings "nvimtree"` does not make a difference.
2. Disabling the original keymap does not make a difference. I added:
```
M.disabled = {
  n = {
    ["<Leader>e"] = "",
  },
}
```

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/e23857d5-8bf2-4970-962c-39c353839830)

this is very bad, u shouldnt do it

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/fc134e6c-edb5-4978-8299-01f273028a2f)

its leader not Leader :v
