### ISSUE TITLE
CPU usage on load with latest pyright

### ISSUE THREAD

**Issue by rafaponieman** [siduck76/NvChad#2535]
**Describe the bug**
*This issue may be completely unrelated to NvChad, however, I don't know how to debug it myself, or where to report it so I'd be grateful for any help or insights.*

I've updated NvChad to the latest version, updated all dependencies and used Mason to update my LSPs to their latest version. Right after this, I noticed when I open the first Python file for a project (which triggers pyright to load), I get 100% CPU usage on Neovim for about two minutes, while the editor freezes completely. After that, it becomes unlocked and everything seems to work normally. This issue is only occurring with pyright, every other LSP seem to work fine.

**To Reproduce**
1. Update NvChad and all dependecies to latest version.
2. Update pyright LSP through Mason.
3. Load a python file on a project containing multiple files.

**Expected behavior**
The editor should freeze for a second or two, then unfreeze and operate normally, offering LSP suggestions through pyright.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 23.10
 - Terminal: Konsole 23.08.1
 - Version of Neovim:
```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16=/usr/src/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16-23b2ca899~ubuntu23.10.1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16/.deps/usr/include -I/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16/build/src/nvim/auto -I/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16/build/include -I/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16/build/cmake.config -I/build/neovim-KSdDs9/neovim-0.10.0~ubuntu1+git202311302105-5e1ff4302-c60402a16/src
```

Thanks!!

**Comment by siduck** [comment]
@rafaponieman this looks like an issue with pyright itself so not related to nvchad

**Comment by rafaponieman** [comment]
Thank you @siduck, will go ahead and report on pyright.

**Comment by siduck** [comment]
> Thank you @siduck, will go ahead and report on pyright.

not yet! 

first try LTS version of neovim which is 0.9.4 ( try bob if LTS isnt on your OS ) 

if the error still persists then try a minimal nvim config like `tinyvim` and other nvim distros like lazyvim etc

if those dont face this error then this could be nvchad related

**Comment by rafaponieman** [comment]
> > Thank you @siduck, will go ahead and report on pyright.
> 
> not yet!
> 
> first try LTS version of neovim which is 0.9.4 ( try bob if LTS isnt on your OS )
> 
> if the error still persists then try a minimal nvim config like `tinyvim` and other nvim distros like lazyvim etc
> 
> if those dont face this error then this could be nvchad related

I installed 0.9.4 with bob and it works perfectly, it looks like it's a problem with the nightly neovim version. Do you think I should report it on the neovim bug tracker?

Thank you!

**Comment by siduck** [comment]
@rafaponieman to report it you should first try to replicate this on a minimal config

for example make a minimal nvim config which just has lspconfig and then test there! once     its confirmed, then make issue on lspconfig repo
