### ISSUE TITLE
Lsp does not restarts after i solved the bug

### ISSUE THREAD

**Issue by insidersbuilt** [siduck76/NvChad#254]
one the bug is solved i have to manuly stop and start the lsp idk why did i messed up some settings or this is the same with yo all guys

**Comment by JustSage** [comment]
Please explain your issue with some sense.
You **can** manually stop Lsp from running, the default start operation is to attach when reading a buffer. 
So if understood correctly, the issue is in your configurations.

Are you using NvChad's latest version ?

**Comment by insidersbuilt** [comment]
> Please explain your issue with some sense.
> You **can** manually stop Lsp from running, the default start operation is to attach when reading a buffer.
> So if understood correctly, the issue is in your configurations.
> 
> Are you using NvChad's latest version ?

i just downloaded the letest verion of it and it worked i upgraded it yesterday i think they patched it tody thanks it solved
