### ISSUE TITLE
Telescope fzf-native not found

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2540]
**Describe the bug**
whenvever running Telescope I get the error

**To Reproduce**
open neovim with a fresh install of nvchad on neovim nightly and do the command Telescope

**Expected behavior**
An error to not pop up

**Screenshots**
![Screenshot 2023-12-04 002247](https://github.com/NvChad/NvChad/assets/65212972/99543d4c-9f24-4706-80fb-132f0ff6325c)

**Desktop (please complete the following information):**

wsl 2 ubuntu
whatever terminal comes with wsl 2 (i believe GNOME)
Neovim nightly
**Additional context**

**Comment by siduck** [comment]
cd into the plugin dir and run make command

**Comment by DrTeagle** [comment]
ok thanks I thought that this would be done automaticaly silly me, thanks for the quick response

**Comment by siduck** [comment]
> ok thanks I thought that this would be done automaticaly silly me, thanks for the quick response

it should be, check default plugins file's telescope section, lazy would run make for the telescope extension , idk why it didnt work there, probably windows issues :/

**Comment by miloslavnosek** [comment]
Same issue on Linux. openSUSE Tumbleweed.

**Comment by siduck** [comment]
@miloslavnosek show the ouput of make command in the required dir!

ig i should remove this plugin @kayuxx  :((

**Comment by DrTeagle** [comment]
really unfortunate as it is very helpful ( I believe but I am weird and dont do much telecsope or fuzzy finding)

**Comment by DrTeagle** [comment]
maybe wait until binaries are shipped? but I know little and will defer to your expertise

**Comment by kayuxx** [comment]
@DockterTeagle pls read the docs before you open an issue!!. @siduck the docs ain't referring that
