### ISSUE TITLE
Version 3.0 Error with indent-blankline.nvim

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2541]
**Describe the bug**
indent blankline fails to load

**To Reproduce**
open a  lua file with a fresh neovim config under the version 3.0 branch(if this already exists I am sorry)

**Expected behavior**
Neovim to run without errors

**Screenshots**
![Screenshot 2023-12-04 080034](https://github.com/NvChad/NvChad/assets/65212972/a4c7a99d-9350-4c29-8f3a-ac0fd0aa1f85)

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim
 WSL 2 ubuntu
Neovim nightly
GNOME(or whatever comes with wsl 2)
uname -a returns this
Linux CHRISTHINK 5.15.133.1-microsoft-standard-WSL2 # 1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by siduck** [comment]
do lazy sync again

**Comment by DrTeagle** [comment]
yep that fixed it was it because of nvterm? idk I gotta go rq
