### ISSUE TITLE
Unable to load LuaSnip directory

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2543]
**Describe the bug**
Whenever I try to use any of my custom made autosnippets in version 2.0 they wont work, I have removed all of the files but the init.lua and the LuaSnip directory

**To Reproduce**
Use my neovim config with only the init.lua and LuaSnip directory(I wouldnt expect other wise) try to use ;a for \alpha expansion in tex files
 https://github.com/DockterTeagle/mynvimconfig

**Expected behavior**
for ;a and other such custom snippets to work

**Screenshots**

**Desktop (please complete the following information):**
Neovim Nightly
WSL 2 ubuntu 
uname -a returns this:
Linux CHRISTHINK 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by siduck** [comment]
does manually loading the path work? i.e go to plugins/others.lua and try

**Comment by DrTeagle** [comment]
I think I also tried putting it in the main init.lua file (though it was a slightly differnet syntax) I got it from https://www.ejmastnak.com/tutorials/vim-latex/luasnip and it still didnt work though I will try this

**Comment by DrTeagle** [comment]
am on version 3.0 so plugins/others.lua does not exist, but hardcoding the init.lua in the nvim directory does not work

**Comment by DrTeagle** [comment]
I added the following line to the init.lua
 require("luasnip.loaders.from_lua").lazy_load { paths = "~/.config/nvim/lua/custom/LuaSnip" }

**Comment by DrTeagle** [comment]
oh wait is it because autosnippets are not enabled by default?

**Comment by DrTeagle** [comment]
that is why, how do  I enable auto snippets?

**Comment by siduck** [comment]
> am on version 3.0 so plugins/others.lua does not exist, but hardcoding the init.lua in the nvim directory does not work

dont use v3.0, its still beta. use v2.0

**Comment by siduck** [comment]
> oh wait is it because autosnippets are not enabled by default?

![image](https://github.com/NvChad/NvChad/assets/59060246/6e9329af-6bd7-49d5-8ac0-23a68eba8684)

**Comment by siduck** [comment]
> I added the following line to the init.lua require("luasnip.loaders.from_lua").lazy_load { paths = "~/.config/nvim/lua/custom/LuaSnip" }

if it doesnt work even after this, then its not a nvchad issue

**Comment by siduck** [comment]
@DockterTeagle for plugin related issues ask for help in our discord server

**Comment by DrTeagle** [comment]
It worked after I added the line to enable auto snippets. will switch back to v 2.0

**Comment by siduck** [comment]
> It worked after I added the line to enable auto snippets. will switch back to v 2.0

anyways v3.0 shouldnt affect this,  i'm assuming some stuff in your custom config  probably broke v3.0
