### ISSUE TITLE
The keymap of LSP Implementation is not working

### ISSUE THREAD

**Issue by oakmegaeddie** [siduck76/NvChad#2546]
**Describe the bug**
I'm new to NvChad, I can't use keymap of LSP Implementation `gi`.
It just go to the latest insert position, even I installed `python-lsp-server` in Mason.
I'd like to know:
1. How should I do to use the keymap of LSP Imlementation.
2. Can I disable the behaviour of **go to the latest insert position**?

**To Reproduce**
1. git clone NvChad.
3. Agree to use example config.
4. Read cheatsheet, it says the keymap of LSP Implementation is `gi`.
5. Use `gi` in a Python project, it just go to the latest insert position, even I installed `python-lsp-server` in Mason.

**Expected behavior**
It should go to the implementation.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - Operating System: macOS
 - Terminal: iTerm2
 - Version of Neovim: v0.9.0

**Additional context**
No

**Comment by siduck** [comment]
setup the lsp server in custom lspconfig file
