### ISSUE TITLE
Lua Execution Error in Ubuntu 23.10

### ISSUE THREAD

**Issue by TahsinAyman** [siduck76/NvChad#2547]
**Describe the bug**
After installing `NvChad` i seem to be having a error when i try to change the theme. firstly the theme does change but when i save anything or any file it resets back to the old default `theme `. i seem to be having this error log:

```lua
E5108: Error executing lua: /home/tahsin/.local/share/nvim/lazy/ui/lua/nvchad/utils.lua:27: attempt to index local 'fil
e' (a nil value)
stack traceback:
        /home/tahsin/.local/share/nvim/lazy/ui/lua/nvchad/utils.lua:27: in function 'replace_word'
        .../share/nvim/lazy/ui/lua/telescope/_extensions/themes.lua:80: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:257: in function <...hare/nvim/lazy/telescope.nvim/
lua/telescope/mappings.lua:256>
Press ENTER or type command to continue
```

**To Reproduce**
1. Go to `Command Mode`
2. Type `Space` + `t` + `h`
3. Scroll down to a `theme`
4. See Error

**Expected behavior**
I exprected to be having a clear working theme without any bugs

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/87863787/d7dc62ad-7ebf-4ac8-a179-832ae755bc9c)

**Desktop (please complete the following information):**
 - `Ubuntu 23.10`
 - Terminlogy
 - Version of `Neovim v0.9.4`

**Additional context**

**Comment by siduck** [comment]
i'm assuming you dont have a chadrc or theme key is missing from chadrc, please write it there

**Comment by TahsinAyman** [comment]
what do you mean ?

**Comment by TahsinAyman** [comment]
i dont understand ?

**Comment by siduck** [comment]
> what do you mean ?

if you dont know what's chadrc  or key then please read nvchad.com

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/1765ce7f-a8aa-4237-bda2-e1d01d1dd5b9

cant reproduce your issue too. Make a video of clean installation and then leader th

**Comment by TahsinAyman** [comment]
https://github.com/NvChad/NvChad/assets/87863787/22c097f5-2a26-4037-9576-f1a9748e9f17

this is the video reporesetntation

**Comment by TahsinAyman** [comment]
please help me with this @siduck

**Comment by siduck** [comment]
> please help me with this @siduck

~/.config/nvim/lua/custom/chadrc, show me that file

**Comment by TahsinAyman** [comment]
there is no folder called custom under ~/.config/nvim/lua

**Comment by siduck** [comment]
> there is no folder called custom under ~/.config/nvim/lua

thats the issue!  either use this as custom dir https://github.com/NvChad/example_config 

or make a minimal chadrc

**Comment by TahsinAyman** [comment]
can you give me the steps how to do that here

**Comment by TahsinAyman** [comment]
thank you so much now it works
but is it possible to make the theme transparetn because my terminal is transparetnt

**Comment by siduck** [comment]
> thank you so much now it works but is it possible to make the theme transparetn because my terminal is transparetnt

there's an option for it, please read core/default_config.lua for all features and please read nvchad.com start to end, in order cuz without docs you'll keep asking for basic stuff here!

**Comment by TahsinAyman** [comment]
please one last favor i dont have much time

**Comment by siduck** [comment]
> please one last favor i dont have much time

check core/default_config.lua, it has an option for it.....

**Comment by TahsinAyman** [comment]
i have set
```lua
transparency = true
```
it dosent work 
what to do next ?

**Comment by TahsinAyman** [comment]
??

**Comment by siduck** [comment]
> i have set
> 
> ```lua
> transparency = true
> ```
> 
> it dosent work what to do next ?

set it in chadrc, that file autoreloads as its under custom dir

**Comment by TahsinAyman** [comment]
im in core/default_config.lua

**Comment by siduck** [comment]
> im in core/default_config.lua

Please set it in chadrc :/

**Comment by TahsinAyman** [comment]
thank you so much for the help i really appreciate your cusotmer support
