### ISSUE TITLE
Warngin on every time i write

### ISSUE THREAD

**Issue by TahsinAyman** [siduck76/NvChad#2548]
**Describe the bug**
Im having this error on everytime i write like 4 to 5 characters 

**To Reproduce**
I donknow

**Expected behavior**
A simple life

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/87863787/61d28d56-7f75-42c0-9ed1-3f1eccd38fd7)

**Desktop (please complete the following information):**
 - Ubuntu 23.10
 - Terminology

**Comment by siduck** [comment]
clang issue, not nvchad, pls google it

**Comment by TahsinAyman** [comment]
thanks man that helped
