### ISSUE TITLE
"warning: multiple different client offset_encodings detected for buffer, this is not supported  yet" Everytime i type a character in C and C++

### ISSUE THREAD

**Issue by sandbands** [siduck76/NvChad#2550]
**Describe the bug**

**To Reproduce**
1. Go to Konsole (KDE Terminal, using bash) and type nvim main.c (to test newly installed NvChad)
2. Type something like #include 
3. Accept an autocomplete
AND
5. just typing normally without accepting any autocompletes
6. See error

**Expected behavior**
Not glitch

**Screenshots**
![CopyQ DYyAct](https://github.com/NvChad/NvChad/assets/81774732/18907076-0425-479e-b9ac-2a8417335d63)

**Desktop (please complete the following information):**
 - OS and DE: Endeavour OS (Arch based Linux Distro) with KDE Plasma Desktop Environment (Version 5.27.10)
 - Terminal: Konsole by KDE
 - Version of Neovim: 0.9.4

**Additional context**

**Comment by siduck** [comment]
clangd issue... pls google this up, has nothing to do with nvchad

**Comment by sandbands** [comment]
thanks I fixed it also unrelated but I want to set my tabs to the Tab character and i also want to enable relative numbers as well as block cursor. The documentation is unclear to me and since its not a .vim file i dont know what to do

**Comment by siduck** [comment]
> Referen

read nvchad.com docs in order

**Comment by siduck** [comment]
for tabs character, blankline.nvim is useful

**Comment by sandbands** [comment]
ive read it in order but i havent really understood it

is there a specific file I can edit to make those settings permanent? and what code would i have to insert and where?

**Comment by siduck** [comment]
the file where your clang lsp is defined
