### ISSUE TITLE
all icon broken 

### ISSUE THREAD

**Issue by billysutomo** [siduck76/NvChad#2554]
**Describe the bug**
all icon is broken or change into "?" mark

**To Reproduce**
1. open nvim

**Expected behavior**
Show icon 

**Screenshots**
<img width="309" alt="Screenshot 2023-12-12 at 6 22 43 PM" src="https://github.com/NvChad/NvChad/assets/17403088/86c23068-1a24-48c6-a926-0ae0df12fc87">

**Desktop (please complete the following information):**
 - Mac OS Ventura 13.6.1
 - ITerm2 build 3.4.22
 - NVIM v0.9.4

**Comment by siduck** [comment]
nerdfont..................
