### ISSUE TITLE
Install ruby LSP within NvChad

### ISSUE THREAD

**Issue by gmhawash** [siduck76/NvChad#2556]
I am a bit lost with these configurations and not sure how to add plugins.  I am familiar with the Plug.vim before using neovim and installing NvChad.

How do I add plugins for ruby syntax and for git blame.

Thanks.

**Comment by siduck** [comment]
please read nvchad.com doc, from start to end. It  teaches you basic lua too

**Comment by gmhawash** [comment]
@siduck why would I want to learn Lua, I just want to use NvChad not program for it.  I am just hoping for an example of how to add additional plugins similar to what the Plug.vim did.

**Comment by siduck** [comment]
> @siduck why would I want to learn Lua, I just want to use NvChad not program for it. I am just hoping for an example of how to add additional plugins similar to what the Plug.vim did.

you need to know basic lua to configure any lua based nvim config :/  , nvchad.com covers everything and needs to be read in order

**Comment by siduck** [comment]
basic lua barely takes 15-20 mins if you already know programming
