### ISSUE TITLE
<C-R> behavior problems

### ISSUE THREAD

**Issue by ev2** [siduck76/NvChad#2560]
**Describe the bug**
<C-R> command does not work as in plain neovim

**To Reproduce**
1. start with a new file and insert a string:
    iabcdefgh<ESC>
   result: abcdefgh
2. Go to the start of the string:
    ^
3. Change the first 2 char with the value of register ".
   2cl\<C-R\>.
   result obtained with nvchad:  2abcdefghcdefgh

**Expected behavior**
   expected result as in plain neovim(vim): abcdefghcdefgh

 - Operating System Ubuntu 22.04
 - Terminal  kitty terminal
 - Version of Neovim NVIM v0.9.1                                                                                   
                    Build type: Release                                                                           
                    LuaJIT 2.1.0-beta3 

**Additional context**
The error is always present when using operator c (change) with a motion and a count as in 3cw 4cj etc...
The count appears as the first character of the change
It must be one of the plugins distributed with nvchad for sure.
I have tried also with the docker image and it is the same

**Comment by siduck** [comment]
unable to reproduce, please make a video and show

**Comment by ev2** [comment]
Sorry, markdown editor cut \<C-R\> from the indicted command.
I have sorted it out. Here it is the video starting from your docker image
Fonts are not the right ones but you can see the bug anyway

[![asciicast](https://asciinema.org/a/k6r9YjvSFQG5TxSBcxfUoWMij.svg)](https://asciinema.org/a/k6r9YjvSFQG5TxSBcxfUoWMij)

And the nvim --clean behaviour
[![asciicast](https://asciinema.org/a/mAlG8miZnQSNH3MSWHLQ1S6O6.svg)](https://asciinema.org/a/mAlG8miZnQSNH3MSWHLQ1S6O6)

**Comment by siduck** [comment]
this step is confusing

> Change the first 2 char with the value of register ".
2cl<C-R>.

do i press those keys?

**Comment by ev2** [comment]
Yes 
Change the first 2 char with the value of register ".
typing **2cl\<C-R\>.** means exactly that. 2cl is the command to change 2 char from the cursor entering in insert mode. Then \<C-R\>. insert the **.** register there

**Comment by siduck** [comment]
i tried, it just goes in insert mode, maybe join our discord server and ask there
