### ISSUE TITLE
NvChad throws error when opening vim documentation

### ISSUE THREAD

**Issue by alphaprads** [siduck76/NvChad#2564]
**Describe the bug**
whenever i try to open any page from vim documentation i get this error 
i just have to press any key to continue working and the error goes away and documentation opens

**To Reproduce**
just do :h lsp
or any other relevent doc page

**Expected behavior**
documentation to open without this error being thrown

**Screenshots**
![god](https://github.com/NvChad/NvChad/assets/111706331/cabbbe6f-a54f-4409-8ebc-4f8b00ea0c5b)

**Desktop:**
 - Operating System = Ubuntu 23.04
 - Terminal = alacritty
 - Version of Neovim = 0.10.0

 - NVIM v0.10.0-dev
 - Build type: RelWithDebInfo
 - LuaJIT 2.1.0-beta3

**Solution**
I solved it by just installing vimdoc please do tell me if I need to provide any other info related to problem I will provide any relevent info to this 
I could not find any similar issue to this if this issue is ongoing please close this issue

**Comment by siduck** [comment]
not a nvchad issue :/  , I hope TSInstall vimdoc was done. 

Last solution :
please use LTS version of neovim and rm -rf .local/share/nvim
