### ISSUE TITLE
Mismatch colors on bottom icons with transparent background

### ISSUE THREAD

**Issue by mdloucks** [siduck76/NvChad#2565]
**Describe the bug**
When running trying to make the background transparent on iTerm2 on MacOS, part of the icons on the bottom are treated as part of the background. 

**To Reproduce**
See screenshots above, options modifiable in Preferences -> Profiles -> Window.

**Expected behavior**
To have these icons at the bottom be the same color.

**Screenshots**

**Normal NvChad**
<img width="1066" alt="Screenshot 2023-12-19 at 3 35 47 PM" src="https://github.com/NvChad/NvChad/assets/19471665/54c954af-afea-428e-ad76-80a601e40caa">

**With transparency**
<img width="1061" alt="Screenshot 2023-12-19 at 3 36 42 PM" src="https://github.com/NvChad/NvChad/assets/19471665/a2eb234a-dd06-45e3-a61e-be810d6ab7bd">

**With transparency & nvchad (require('base46').toggle_transparency())**
<img width="1064" alt="Screenshot 2023-12-19 at 3 37 00 PM" src="https://github.com/NvChad/NvChad/assets/19471665/2ce84fc4-3ccc-470c-a167-73c9242343c8">

**Desktop (please complete the following information):**
 - Operating System MacOS Sonoma 14.1.2
 - Terminal iTerm2 3.4.22
 - Version of Neovim 0.9.4

**Additional context**
This seems to be caused by the icon texts being treated as background elements. Would this issue be fixable by having them become foreground elements upon calling toggle_transparency()? 

Changing the NvChad theme does not fix this issue, neither does setting the terminal theme. Additionally, I have the hack nerd font set.

**Comment by siduck** [comment]
please  set transparency option in chadrc

**Comment by mdloucks** [comment]
Transparency is already set to true. See 3rd screenshot.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/8b15a1d9-c532-4318-b8f5-f5517b233206


unable to reproduce, can you try with other terminal
