### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by MatBerg10** [siduck76/NvChad#2568]
Whenever I try to open neovim (v0.6.1) i get the following error:

`Error detected while processing /home/codeany/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/codeany/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocm
d' (a nil value)
stack traceback:
        /home/codeany/.config/nvim/lua/core/init.lua:67: in main chunk
        [C]: in function 'require'
        /home/codeany/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue`

I've tried reinstalling neovim and nvchad and it always gives me this error.
I use v0.6.1 of Neovim.
I don't know if it matters, but I'm installing it in an online Ubuntu environment with zsh using `sudo apt install neovim` and the standard `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1`

**Comment by jtuz** [comment]
read the docs, you need the latest stable version: https://nvchad.com/docs/quickstart/install

**Comment by MatBerg10** [comment]
> read the docs, you need the latest stable version: https://nvchad.com/docs/quickstart/install
Thank you very much for your availability.
