### ISSUE TITLE
Can't save the colorscheme

### ISSUE THREAD

**Issue by ignacek1** [siduck76/NvChad#2569]
Everytime I'm launching neovim the default theme loads, and when I'm trying to change it, this appears, and the new colorscheme won't change:
![image](https://github.com/NvChad/NvChad/assets/132497046/02c6f4bc-4d68-4b22-b879-c727abfb1949)

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck** [comment]
make sure chadrc.lua exists
