### ISSUE TITLE
NVChad LSP Config produces unwanted hints

### ISSUE THREAD

**Issue by Artur-Galstyan** [siduck76/NvChad#2570]
**Describe the bug**
With this Pyright config:

```lua
lspconfig.pyright.setup ({
  on_attach = on_attach,
  capabilities = capabilities,
  settings = {
    pyright = { autoImportCompletion = true },
    python = {
      analysis = {
        autoSearchPaths = true,
        diagnosticMode = "openFilesOnly",
        useLibraryCodeForTypes = true,
        typeCheckingMode = "basic",
        diagnosticSeverityOverrides = {
          reportUnusedImport = "none",
        },
      },
    },
  },
})
```

it still gives these hints:

![image](https://github.com/NvChad/NvChad/assets/63471891/e0143377-675e-4647-91de-59894eb6ac0a)

To double check, I changed the level from "none" to "error":

![image](https://github.com/NvChad/NvChad/assets/63471891/94627fed-f5b2-411f-9151-bbd4b5fe79bc)

which then actually shows those as errors. 

But I don't want it to show anything! I'm using Ruff and because of this purple text, I get duplicated warnings, which is super annoying. 

I updated NvChad using NvChadUpdate and the problem still persists. Nor ChatGPT or the internet had this problem :( 

AFAIK it's because of this light bulb
![image](https://github.com/NvChad/NvChad/assets/63471891/50dbd657-f2b5-4285-b57f-fc32aafe8888)

**Comment by siduck** [comment]
nothing to do nvchad imo ,   nvchad doesnt even configure specific lsp stuff! thats issue at your end or pyright,  please ask    in our discord group as this isnt a real nvchad issue
