### ISSUE TITLE
Headless NvChadUpdate

### ISSUE THREAD

**Issue by JonZeolla** [siduck76/NvChad#2573]
**Describe the bug**
I am attempting to update NvChad non-interactively, and it gives some errors. 

**To Reproduce**
Run `nvim --headless '+NvChadUpdate' +qa`
See:
```
Error detected while processing command line:
Error executing vim.schedule lua callback: ...nzeolla/.local/share/nvim/lazy/ui/lua/nvchad/updater.lua:61: Vim:E322: line number out of range: 1 past the end
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...nzeolla/.local/share/nvim/lazy/ui/lua/nvchad/updater.lua:61: in function <...nzeolla/.local/share/nvim/lazy/ui/lua/nvchad/updater.lua:58>
 error 143
Updating registries…
Successfully updated 1 registry.%
```

This happens even after I ran `NvChadUpdate` interactively.

**Expected behavior**
Headless updates should be allowed without errors, assuming updates function interactively.

**Screenshots**
Interactive:
<img width="1269" alt="Screenshot 2023-12-24 at 9 59 20 AM" src="https://github.com/NvChad/NvChad/assets/1385510/6b0960dd-e99b-4c24-aacd-29b3c306adab">
Headless:
<img width="1292" alt="Screenshot 2023-12-24 at 9 59 49 AM" src="https://github.com/NvChad/NvChad/assets/1385510/4c1e8ef8-5589-45e3-8235-1545f6784200">

**Desktop (please complete the following information):**
 - Operating System: macOS 14.2.1 (23C71)
 - Terminal: Warp v0.2023.12.19.08.02.stable_00
 - Version of Neovim:
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

**Comment by JonZeolla** [comment]
I'm also open to an alternative for auto maintenance; I recall seeing something in the docs about this before but now I'm not able to find it.

**Comment by siduck** [comment]
just git pull + lazy sync , if lazy doesnt support headless then we cant do anything about it
