### ISSUE TITLE
Include dressing to improve UI

### ISSUE THREAD

**Issue by amardhruva** [siduck76/NvChad#2576]
**Is your feature request related to a problem? Please describe.**
Things like mason use vim.ui.select to filter programming languages. But on nvchad its ugly.
![Screenshot from 2023-12-25 14-16-14](https://github.com/NvChad/NvChad/assets/7582063/5e598b4a-bc26-4fb1-aa55-01246fdb79a5)

**Describe the solution you'd like**
Install (dressing)[https://github.com/stevearc/dressing.nvim] by default in order to have pretty ui

**Describe alternatives you've considered**
N/A

**Screenshot**
![image](https://github.com/NvChad/NvChad/assets/7582063/01ee2fb4-148b-4f8a-963c-1f1c3034036e)

**Comment by siduck** [comment]
add it in your custom plugins
