### ISSUE TITLE
This is what happens when installation instructions are followed

### ISSUE THREAD

**Issue by Vinni-Cedraz** [siduck76/NvChad#2577]
steps to reproduce are simply the git clone installation you can see in the screenshot below:

![Screenshot_2023-12-26_11-25-20](https://github.com/NvChad/NvChad/assets/92558763/7cdb4b83-2a28-41f8-aab6-7a9ac64ab588)

the docker option has at least 10 plugins failing to be installed by Lazy

**Comment by siduck** [comment]
rm -rf all old nvim dirs and install again

**Comment by siduck** [comment]
> the docker option has at least 10 plugins failing to be installed by Lazy 

make a video and show me, i'm assuming they're most likely due to lazy's issues or your internet connection
