### ISSUE TITLE
<C-s> in insert mode doesn't save file

### ISSUE THREAD

**Issue by ghost** [siduck76/NvChad#2578]
**Describe the bug**
I have
```
  i = {
    ["<C-s>"] = { "<ESC>:w!<cr>" },
    ["<C-c>"] = { "<ESC>:wq!<cr>" },
  },
```

in my `custom/mappings.lua`. But neither shortcut does what is expected from it. When I press \<C-s\> it outputs "^S" and doesn't leave insert mode. And when I press \<C-c\> it just goes into normal mode but does not exit the editor. I have the same hotkeys in normal mode and they work as expected.

**Desktop (please complete the following information):**
 - Operating System
arch
 - Terminal
kitty
 - Version of Neovim
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/3467e710-69f1-43a8-9cac-bbdf1f90301d

your code works here! ig its your terminal issue, please ask such small issues in our discord server etc

**Comment by ghost** [comment]
Okay, I've figgured it out. Apparently it didn't work because of `vim.opt.paste = true`
