### ISSUE TITLE
Unable to add new functionality to telescope to open files from config directory.

### ISSUE THREAD

**Issue by wxguy** [siduck76/NvChad#2583]
I am trying to add a new key map `<leader>fc` to telescope so that it will only show me config files of my nvim directory. 

Here is the procedure I followed to include this functionality. Created a new lua file at `$HOME/.config/nvim/lua/custom/config/user/telescope.lua` with the following content:-

```
local telescope = require "telescope"
local telescope_builtin = require "telescope.builtin"
local telescope_actions = require "telescope.actions"
local M = {}

telescope.setup {
  defaults = {
    prompt_position = "top",
    layout_strategy = "horizontal",
    sorting_strategy = "ascending",
    use_less = false,
  },
}

M.find_config_files = function()
  local config_dir = vim.env.HOME .. "/.config/nvim"
  telescope_builtin.find_files {
    find_command = { "rg", "--files", "--iglob", "!.git", "--hidden", config_dir },
    previewer = false,
  }
end


return M
```

Then added the key following keymap in my custom `mapping.lua` file:-

```
M.telescope = {
  plugin = true,
  n = {
    ["<leader>fo"] = { "<cmd> Telescope find_config_files <CR>", "Find Config Files" },
  },
}
```

However, I get the following error when I open a new nvim window:-

![Screenshot from 2024-01-02 01-44-38](https://github.com/NvChad/NvChad/assets/9054645/c9c10ecf-6618-4709-86e9-1d4a35e3cb9a)

How do I get the desired action?

I use Arch Linux with GNOME. The terminal is a GNOME console and nvim version is `v0.9.5`
 - Operating System
 - Terminal
 - Version of Neovim

I feel that this option should be defaulted to NvChad as many times it is difficult to navigate config files again and again.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/0bebd016-08b7-45df-b14a-fabd02fe31ac)

where are you even calling that telescope file? nowhere! please ask    on discord/github discussions for your config related issues
