### ISSUE TITLE
utils.lua error

### ISSUE THREAD

**Issue by iddixx** [siduck76/NvChad#2584]
E5113: Error while calling lua chunk: C:\Users\ondar\AppData\Local\nvim/lua/core/utils.lua:26: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
        [C]: in function 'pairs'
        C:\Users\ondar\AppData\Local\nvim/lua/core/utils.lua:26: in function 'remove_disabled_keys'
        C:\Users\ondar\AppData\Local\nvim/lua/core/utils.lua:11: in function 'load_config'
        C:\Users\ondar\AppData\Local\nvim/lua/core/init.lua:3: in main chunk
        [C]: in function 'require'
        C:\Users\ondar\AppData\Local\nvim\init.lua:1: in main chunk
        
I just opened nvim and saw this error, everything was working fine before

**Comment by siduck** [comment]
please fix syntax err in your custom mappings.
