### ISSUE TITLE
Show modified status when only one file is open

### ISSUE THREAD

**Issue by dagraham** [siduck76/NvChad#2591]
**Is your feature request related to a problem? Please describe.**
When more than one file (buffer) is open, Tabufline is displayed and shows for each buffer an icon if the file is dirty.  When only one file is open, Tabufline is not displayed and there is no indication in the status line whether or not the file is dirty.

**Describe the solution you'd like**
With only one file open and thus when Tabufline is not displayed, show the modified status of the file in the status line next to the file name (as is normally done in vim).

**Describe alternatives you've considered**
Alternatively, provide an option to show Tabufline with only one file open.

**Comment by siduck** [comment]
its not dirty, its useful to know if there are multiple modified + unsaved files,  at some point i might make tabufline modules easy to override.

**Comment by dagraham** [comment]
Maybe I wasn’t clear. The problem is not being able to tell if a file is modified when only one file is open in NvChad and thus when Tabufline is not being displayed.

Dan

**Comment by dagraham** [comment]
By “dirty” I meant “has unsaved changes”.

Dan

**Comment by siduck** [comment]
> Maybe I wasn’t clear. The problem is not being able to tell if a file is modified when only one file is open in NvChad and thus when Tabufline is not being displayed. Dan
> […](#)
> On Jan 3, 2024 at 11:41 AM -0500, Sidhanth Rathod ***@***.***>, wrote: Closed #2591 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

just disable lazyload of tabufline so tabufline gets loaded at startup, read core/default_config.lua and make change in chadrc

**Comment by dagraham** [comment]
Brilliant! Thanks!!
