### ISSUE TITLE
Co pilot installation guide

### ISSUE THREAD

**Issue by heapbytes** [siduck76/NvChad#2592]
heyy, i wanted to install co pilot on nvchad, i followed this article : 
https://azamuddin.com/en/blog/050623-setting-up-copilot-on-nvchad

but, it says after you install the co pilot plugin, i am not sure how should i install that plugin, what file should i edit? since :PackerInstall isn't there, i am confused, 

also share your discord group link.

**Comment by heapbytes** [comment]
![image](https://github.com/NvChad/NvChad/assets/56447720/2ffff40e-60e0-4bea-928f-c0bb2dc1ccd2)

**Comment by siduck** [comment]
please read nvchad's plugin docs and also all of nvchad.com or else you'd never know how nvchad   custom config works
