### ISSUE TITLE
The icon of the selected theme is illegal

### ISSUE THREAD

**Issue by felixwluo** [siduck76/NvChad#2597]
**Describe the bug**
<img width="721" alt="image" src="https://github.com/NvChad/NvChad/assets/131352377/3e84a7e9-8c0c-4ffc-b105-97adf742b35c">
The icon of the selected theme is illegal

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
i'm assuming you are using iterm2, use a terminal that supports all nerdfont glyphs

**Comment by felixwluo** [comment]
Yes I use iterm2, how do I set it?

**Comment by siduck** [comment]
@felixwluo either change terminal or change icon in telescope config
