### ISSUE TITLE
Handling Non-Existent Files in Directory for New NvChad Installations

### ISSUE THREAD

**Issue by ayoubelmhamdi** [siduck76/NvChad#2600]
This line attempts to fetch some files from a directory, by calling dofile, but it should be wrapped to handle non-existent files in this directory:
```lua
-- /.local/share/nvim/nvchad/base46/...
dofile(vim.g.base46_cache .. "defaults")
```

**Comment by siduck** [comment]
@ayoubelmhamdi base46 is installed and its highlights are compiled before even nvchad plugins are installed during the boostrap, so not needed.

**Comment by ayoubelmhamdi** [comment]
That's weird.

**Comment by dattmavis** [comment]
I know this is closed, but this generally pops up when you're migrating from another customized neovim configuration. 

Don't skip steps in the Install docs. Make sure to run the following prior to install:

# Linux / Macos (unix)
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim

# Windows
rd -r ~\AppData\Local\nvim
rd -r ~\AppData\Local\nvim-data
