### ISSUE TITLE
Can't get pluggins working.

### ISSUE THREAD

**Issue by brighamdent** [siduck76/NvChad#2602]
Whenever I try to install the plugins I set lazy=false, I then lazy sync and restart. None of the pluggins I've tried installing have been working. They all have a start play button to the side as shown in the pic below. Ive spent hours trying to figure it out. Sorry for my ignorance.
![image](https://github.com/NvChad/NvChad/assets/155594466/ea266367-e02e-4d7d-afcf-740f797a5a2c)

**Comment by siduck** [comment]
please put plugins in custom plugins.lua file. Do lazy false to only those  plugins who cant be lazyloaded, also just use nvim-ts-autotag instead of vim-closetag. Ask such issues on our discord/matrix server.

reproduce your issue with example_config repo
