### ISSUE TITLE
Missing Icons (NerdFont Installed)

### ISSUE THREAD

**Issue by binmalyi** [siduck76/NvChad#2603]
**Describe the bug**
The dev icons are missing even though I literaly have the nerd font installed.

**To Reproduce**
Just install it on Windows and you'll see

**Expected behavior**
Icons to appear on both the tree as well as the statusbar

**Screenshots**
![Screenshot (60)](https://github.com/NvChad/NvChad/assets/70099365/1027bc03-65d4-404e-bbd7-dea458fe1ae1)
![Screenshot (61)](https://github.com/NvChad/NvChad/assets/70099365/c527b3e1-4a87-479f-afaa-aed74c6814c2)

**Comment by siduck** [comment]
terminal issue, nothing to do with nvchad. please install the latest version only

**Comment by danongba** [comment]
@siduck hi, I am having the same issue(on windows 10, command prompt and power shell). I am sure I downloaded the latest version of nerdfont. from the [release page](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.1) . How do I even make sure that the problem lies with the font and not with nvim

**Comment by danongba** [comment]
Mine is bit more severe 
![image](https://github.com/NvChad/NvChad/assets/156789503/a9dbda7f-b4a7-4dea-a52b-54e1c468f0b8)
![image](https://github.com/NvChad/NvChad/assets/156789503/e03d4a5d-d3dc-4d9a-9c04-773ae6d4ad34)

**Comment by danongba** [comment]
It might be font issue indeed. Works fine in [WindowsTerminal](https://github.com/microsoft/terminal) with NF font (didnot test for NFM font):
![image](https://github.com/NvChad/NvChad/assets/156789503/fe93e218-1f52-4445-b6ac-7b481e6f1eb6)

**Comment by siduck** [comment]
yea its the terminal issue!
