### ISSUE TITLE
Which-key custom config bug

### ISSUE THREAD

**Issue by KorigamiK** [siduck76/NvChad#2606]
**Describe the bug**
When defining the keys for the `which-key` plugin in the custom `lazy.nvim` plugins table, the options `keys` field is not overridden

Even though the config explicitly mentions to not activate which-key on pressing the `"` we still see which-key activate.

**Expected behavior**
Custom config should be followed.

**Screenshots** 
![image](https://github.com/NvChad/NvChad/assets/72932688/0b70e3a4-7e65-404c-8b05-a96489ae68c6)

**Comment by siduck** [comment]
thats because whichkey is activated on these keys by default

![image](https://github.com/NvChad/NvChad/assets/59060246/3ea8451d-88de-44fa-b0f7-b747cc2b2de6)

and lazy.nvim combines both the specs i.e parent table ones with custom ones so none of them get priority, lazy.nvim issue. not ours

**Comment by KorigamiK** [comment]
Man I have to disable which-key entirely if I want to omit it for a single key

**Comment by siduck** [comment]
> Man I have to disable which-key entirely if I want to omit it for a single key

you dont get how lazy.nvim list tables merge

if the custom plugin table exists then it'll get merged with the parent table one, instead of it having more priority

**Comment by KorigamiK** [comment]
> > Man I have to disable which-key entirely if I want to omit it for a single key
> 
> 
> 
> you dont get how lazy.nvim list tables merge
> 
> 
> 
> if the custom plugin table exists then it'll get merged with the parent table one, instead of it having more priority 

Yeah I understand that. This feels like NvChad forces me to use a which-key config that I can't change. 

This is an nvchad issue and it can be easily fixed if you remove the default table and allow the uses to set it in their custom config.

**Comment by siduck** [comment]
its not an nvchad issue, we use lazy.nvim as package manager and that handles merging tables. we had just the leader key in keys table before but added few in prs, removing it now would be a breaking change. better ask at lazy.nvim repo for an  actual solution/workaround

**Comment by siduck** [comment]
ok do something like this  
![image](https://github.com/NvChad/NvChad/assets/59060246/f8fbbad8-32e4-4600-8a58-1c2c5c87cc85)

**Comment by KorigamiK** [comment]
> ok do something like this ![image](https://private-user-images.githubusercontent.com/59060246/296540403-f8fbbad8-32e4-4600-8a58-1c2c5c87cc85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzA3MTQsIm5iZiI6MTcwNTIzMDQxNCwicGF0aCI6Ii81OTA2MDI0Ni8yOTY1NDA0MDMtZjhmYmJhZDgtMzJlNC00NjAwLThhNTgtMWMyYzVjODdjYzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDExMDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDFlYTljNGYyOGIxNGFmNjgyYzkyNmI4MDdlZWU1NmVmZDM1NjZjYjM2NGFmYjBiODNiOWQ4MzY2OGY2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fSnBaL-ILaO2HOQy7mHLP3Oi3hfaV_nIT7CDDQWddvI)

Hi, this doesn't work! I only uses the default keys that are already present.
 unfortunately the type checking raises a diagnostic error for me:

```sh
Cannot assign `(string|function|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?` to `(string|LazyKeymaps[]|fun(_: LazyPlugin, keys: string[]):string|LazyKeymaps[]|string[])?`.
```

I'm not sure what I'm doing wrong here. Maybe I can create an issue about this in the lazy.nvim repo?

**Comment by siduck** [comment]
@KorigamiK i tested my issue, it works here. pinged u on discord

**Comment by siduck** [comment]
https://github.com/folke/lazy.nvim/issues/1269
