### ISSUE TITLE
E5113 after installing on Ubuntu

### ISSUE THREAD

**Issue by tathyagarg** [siduck76/NvChad#2609]
**Describe the bug**
After cloning NvChad into `~/.config/nvim`, running nvim returns an error E5113

**To Reproduce**
1. Run `git clone https://github.com/NvChad/NvChad.git ~/.config/nvim --depth 1`
2. Run `nvim`
3. See error

**Expected behavior**
Non-erronous installation of NvChad

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/94824143/d06fdadd-8f0c-42e7-bf4c-2842251882c8)
![image](https://github.com/NvChad/NvChad/assets/94824143/39ea7841-aa57-4c92-a890-cfb67073d999)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Terminal: GNOME Shell (default)
 - Version of Neovim: NVIM V0.6.1

**Additional context**
Running `nvim` before installing NvChad doesn't give the same error. After uninstalling NvChad, the error is no more. Only once NvChad is installed does the error get raised.

**Comment by siduck** [comment]
pls install 0.9 nvim at least, read our docs :sob:
