### ISSUE TITLE
Add lazy.nvim configuration method

### ISSUE THREAD

**Issue by O1024** [siduck76/NvChad#2611]
Hi, I want to set the url_format of lazy.nvim. May I ask how to configure lazy.nvim under the nvchad framework? My current approach is to modify the file lua/plugins/configs/lazy_nvim.lua, but that's not what I want.
![image](https://github.com/NvChad/NvChad/assets/132685272/48d37d7c-78ee-4d3e-bfda-97ac3e94c0c4)

**Comment by siduck** [comment]
chadrc's lazynvim opt mergs with the one in core/default_config, read
