### ISSUE TITLE
Add Support for nvim v0.9.5

### ISSUE THREAD

**Issue by unikzforce** [siduck76/NvChad#2613]
**Is your feature request related to a problem? Please describe.**
Hi NvChad Team,
currently i have installed `nvim` through `brew` which only installs latest stable version which is v0.9.5, and doesn't provide installation of previous versions.

when i try to install nvchad after cleaning up `~/.config/nvim` and `~/.local/share/nvim`, i see this error during the first phase of installation, I had retried many times, the error pops up anyway:

```
nvim-treesitter[lua]: Error during tarball extraction.
tar: Error opening archive: Failed to open 'tree-sitter-lua.tar.gz'

Press ENTER or type command to continue
```

**Describe the solution you'd like**
I would like it to use nvchad with v0.9.5 which is the latest stable version.

**Describe alternatives you've considered**
the only thing i was able to think of currently is to fallback to manual installation of v0.9.4 without using brew package manager

**Additional context**
macos sonoma 14.2.1
M1 macbook pro.
![image](https://github.com/NvChad/NvChad/assets/7010566/caebecc8-3f0f-479e-a3a0-00c3da6c7d48)

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/bb4eb6c0-4704-4bb1-8df1-dcfd75ce952d)

i'm already using 0.9.5, facing no issues. looks like its related to your OS, ask on r/neovim or treesitter repo or our discord server but first test with a minimal nvim config like tinyvim ( check our org for repo )

**Comment by vendethiel** [comment]
this is broken on your end
