### ISSUE TITLE
nvtreesitter install fails

### ISSUE THREAD

**Issue by alkyde** [siduck76/NvChad#2614]
Same as https://github.com/NvChad/NvChad/issues/2613#issue-2086377607 but on Linux

Fresh install of NvChad and the following error appears.
[nvim-treesitter] [0/10] Extracting tree-sitter-lua...   
nvim-treesitter[lua]: Could not create tree-sitter-lua-tmp
mkdir: cannot create directory ‘tree-sitter-lua-tmp’: File exists

Then the tar errros as per issue 2086377607

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.9.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Gentoo 13.2.1_p20240113-r1 p12) 13.2.1 20240113
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.7.0",
  sysname = "Linux",
  version = "#1 SMP Mon Jan  8 04:20:38 EST 2024"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

**Comment by siduck** [comment]
that is not nvchad issue.
