### ISSUE TITLE
zsh error in the installtion

### ISSUE THREAD

**Issue by sudo-py-dev** [siduck76/NvChad#2617]
**Describe the bug**

**To Reproduce**
1. OPpen up 'terminal'
2. past the command 'git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim'
4. See error 'zsh: command not found: nvim'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System Linux mint 
 - Terminal 
 - Version of Neovim

**Additional context**
i run the command and it download the git repo but not install the nvim

**Comment by siduck** [comment]
install neovim
