### ISSUE TITLE
module nvchad.lsp not found

### ISSUE THREAD

**Issue by nsklaus** [siduck76/NvChad#2619]
**Describe the bug**
installed with:
`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
the background color became green i thought maybe i needed to restart nvim, there were no error output or anything so i waited a bit then restarted nvim and then i got this error message:
```
Failed to run `config` for nvim-lspconfig

/Users/klaus/.config/nvim/lua/plugins/configs/lspconfig.lua:2: module 'nvchad.lsp' not found
...
```

**To Reproduce**
1. install nvchad
2. start nvim with some C file i wanted to work on
3. plugin referenced in nvchad config files could not be found

**Expected behavior**
i expected the plugin referenced by nvchad config could be found and nvim/nvchad worked as it should have.

**Screenshots**
<img width="512" alt="Screenshot 2024-01-19 at 13 49 48" src="https://github.com/NvChad/NvChad/assets/6810861/40083083-e67b-403a-8709-3d2987678646">

**Desktop (please complete the following information):**
 - Operating System: macos sonoma 14.beta2
 - Terminal: macos term
 - Version of Neovim: NVIM v0.9.5

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/62e41fcb-55fe-4233-a99b-d590c5746545

unable to reproduce at all

nvchad.lsp module comes with ui repo, if you dont have that then rm -rf old nvim files please

**Comment by nsklaus** [comment]
ok, install wasn't able to complete i see.
after i deleted
- `~/.config/nvim`
- `~/.local/share/nvim`
- `~/.cache/nvim`
and then try again installing: `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim` this time install was able to complete. there is still two problems, the green color and the install script should make a check for `~/.local/nvim` and `~/.cache/nvim` and prompt user to delete or rename those dirs just like install script does if `~/.config/nvim` dir is found (pre-exists at install time).

**Comment by nsklaus** [comment]
you're too eager to dismiss and close this case i think. i report two valid problems. see my 2nd post, just above this one. (colors and lack of proper condition checks prior to start installing, if those dirs exists install will fail).  if installation fail nvchad.lsp and many other elements are never downloaded and installed. you should make sure user remove all previous nvim related directories and their contents.
for what it's worth, before attempting to install nvchad, my own nvim config used nvcoc (lsp based code completion) so maybe those conflicted with what nvchad setup tried to do ?

additionaly:
i see themes are completely broken on macos term, but do work well if i use iterm2

**Comment by siduck** [comment]
> there is still two problems, the green color

that isnt nvchad issue btw, all modern nvim colorschemes expect the user to have true colors set in his/her terminal

**Comment by siduck** [comment]
Also for the local dir check part, nvchad docs are clear about it in install section itself 
![image](https://github.com/NvChad/NvChad/assets/59060246/a2a9d60a-cdab-4b63-aa53-bf9151d0cc93)


We dont use any installer script and its better for the user to backup old files if he wants before installing nvchad rather than us prompting to delete or not / managing backup

**Comment by nsklaus** [comment]
themes work well in iterm2 but not is macos term. and in any cases for the other problem (the install one) your install script should make sure there are no leftovers from a previous nvim usage, otherwise install will fail. your "docs" only mention rm ~/.local/nvim for uninstalling, not for installing. this is misleading.

**Comment by siduck** [comment]
whats the last line here? 
![image](https://github.com/NvChad/NvChad/assets/59060246/0a291b6d-a6e2-4364-aa46-43fc63bdf72b)

**Comment by nsklaus** [comment]
first it should read "folderS" (plural) and it should list them.
that would be a minimum info given.

**Comment by siduck** [comment]
> first it should read "folderS" (plural) and it should list them. that would be a minimum info given.

ok fixed the typo.Just check the commands below for the folders list.

**Comment by nsklaus** [comment]
i don't see the updated instructions yet, but i bet you're still listing the concerned directories under uninstall steps, while it is mandatory to remove them prior to attempt installing. so potentialy other user will fail at installing nvchad straight from their first attempt. and you should investigate if macos term is currently really incompatible with nvchad themes or not. for your information, i was using nvim with coc (lsp) just fine within macos term. i had no color/theme problems. these came only after i installed nvchad. so the point in all this is that one too should be told to users in your install instruction page.

**Comment by siduck** [comment]
users can literally check the commands below 
![image](https://github.com/NvChad/NvChad/assets/59060246/103fcc67-9310-4c6d-abac-e8938b92b7c9)

**Comment by siduck** [comment]
I dont want to make pre-requisites more overwhelming 

> coc ( lsp )  , thats because nvchad theme only supports terminals which have true color support enabled.  I have not set any cterm colors in the theme plugin

**Comment by nsklaus** [comment]
you list steps for "uninstalling" and the user is supposed to understand you meant "you also need to delete the dir listed below (in uninstall steps)  before attempting to install".  this is not correct usage of language. this is misleading directions. you should reformulate.

**Comment by siduck** [comment]
are dirs not listed and visible here? 
![image](https://github.com/NvChad/NvChad/assets/59060246/77f2c759-6f0e-41a5-8525-84c6f80f46bc)

**Comment by nsklaus** [comment]
those are step for "uninstalling" why would users trying to "install" should follow steps for uninstalling ? because your directions are misleading.

**Comment by siduck** [comment]
misleading only for you, no one has problem with that. 

the install section clearly says 

`Delete old neovim folders (check commands below)`

any sane person would know that those commands are for deleting those old folders.

**Comment by nsklaus** [comment]
let me telling you what an insane person such as myself, as you put it, will do:
forget everything about nvchad, and its maintainer which have trouble expressing simple directions for installing the project (which could only indicate further similar problems down the road while using nvchad) and simply install the plugins i need myself directly without having to cope with you or your project. you should be thankful of constructive valid reports and not paint people as insane for trying to report issues.

**Comment by sim-raa** [comment]
its very clear, you just have to read and stop being ignorant
