### ISSUE TITLE
Pressing z after nvim startup doesn't bring up keybindings

### ISSUE THREAD

**Issue by lomaharshana** [siduck76/NvChad#2620]
**Describe the bug**
Pressing z after nvim startup doesn't bring up keybindings starting with the z key (e.g. zc - close code fold), the keybinding works though

**To Reproduce**
1. Start nvim with or without any file
2. Press z
3. This doesn't bring up keybinding list starting with z
4. The list starts appearing only after some other keybinding is shown. For example press c and wait for the list of keybindings starting with c. Close the window. Now if you press z, you see all the keybindings starting with z.

**Expected behavior**
Should show the keybinding list starting with z key in a new session when z is pressed.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
```lua

  {
    "folke/which-key.nvim",
    keys = { "z" },
  },
  ```
  
  add it in custom plugins , that keys "list" table gets merged in the default  plugin list's whichkey's section's keys table.
