### ISSUE TITLE
vim-latex-live-preview plugin "LLPStartPreview" Editor Command not found

### ISSUE THREAD

**Issue by ParadoxPacer** [siduck76/NvChad#2624]
**To Reproduce**
1. Download "xuhdev/vim-latex-live-preview" through custom/plugins.lua
2. Run the command "LLPStartPreview" in NVChad in a .tex file

**Expected behavior**
A window is supposed to open with the default pdf viewer of your system showing the pdf output of the current .tex fule

**Screenshots**
<img width="1014" alt="image" src="https://github.com/NvChad/NvChad/assets/149180602/def4fe89-c563-412c-a683-dd394e3a972d">

**Desktop (please complete the following information):**
 - MacOS 14.0
 - Alacritty Terminal emulator
 - NVIM v.0.9.5

  {
    "xuhdev/vim-latex-live-preview",
    lazy = false,
    config = function ()
vim.g.loaded_vim_live_preview = 1
vim.g.livepreview_previewer = 'zathura'
    end
  },

**Comment by siduck** [comment]
https://github.com/xuhdev/vim-latex-live-preview/issues/12
https://github.com/NvChad/NvChad/issues/1417
