### ISSUE TITLE
conform formatting not working even tried none-ls as well not working

### ISSUE THREAD

**Issue by debuging-life** [siduck76/NvChad#2625]
**Describe the bug**
while using conform formatting its not working for react typescript. Tried many methods, tried none-ls configration, conform configration as described. but still not working

**Comment by siduck** [comment]
please show your config, conform isnt even by default in nvchad. I bet you didnt even install prettier or whatever formatter from mason at all. did you even define the formatters in your conform  config? i     hope you made a mapping for triggering conform's format function

**Comment by siduck** [comment]
and please dont make issue for plugin issues, ask for help on our discord/matrix

**Comment by debuging-life** [comment]
<img width="914" alt="Screenshot 2024-01-24 at 8 26 55 AM" src="https://github.com/NvChad/NvChad/assets/14145891/654358c2-25c1-4af9-8ae8-b2700bcf2b7e">
<img width="914" alt="Screenshot 2024-01-24 at 8 26 37 AM" src="https://github.com/NvChad/NvChad/assets/14145891/a4ea0964-062a-40e2-ad2e-fb66a0d0cc3d">
<img width="914" alt="Screenshot 2024-01-24 at 8 26 20 AM" src="https://github.com/NvChad/NvChad/assets/14145891/c539fd4b-6b1d-4301-9ae1-edc33e93f9d6">

I will not open direct issues again sorry. But here are my config files

**Comment by debuging-life** [comment]
inside mapping file conform code is commented because it was not working,         
vim.lsp.buf.format { timeout_ms = 2000 } (this line of code working but not the way prettier works)
require("conform").format() (this guys is not working)

**Comment by siduck** [comment]
dont use vim.lsp.buf format, if you enable lsp fallback in conform then conform already handles that. And show your conform config

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/262e7503-b214-444f-b2bd-8ff6159c7ff7)

thats mine

**Comment by debuging-life** [comment]
<img width="1828" alt="Screenshot 2024-01-24 at 9 42 08 AM" src="https://github.com/NvChad/NvChad/assets/14145891/f98fce92-b527-452b-8e80-a91650caa234">

**Comment by debuging-life** [comment]
I used your's config and its working. thanks alot for the help

**Comment by siduck** [comment]
@pardipbhatti8791 https://github.com/NvChad/example_config/commit/4e0ccfe72c82a6ed9dd9bd56962b70aed8be9120
