### ISSUE TITLE
Unable to disable tabufline

### ISSUE THREAD

**Issue by alexluix** [siduck76/NvChad#2626]
**Describe the bug**
When I set enabled to `false` tabufline is still displayed and functional.

```
  M.ui = {
    tabufline = {
    │ show_numbers = false,
    │ enabled = false,
    │ lazyload = true,
    │ overriden_modules = nil,
    },
  }
```

**Expected behavior**
tabufline is disabled, no tabs displayed.

**Desktop (please complete the following information):**
 - Mac OSX
 - Iterm2
 - neovim: stable 0.9.5

**Additional context**
Tried restarting neovim.

**Comment by kars0n777** [comment]
Are you editing the right file `~/.config/nvim/custom/chadrc.lua`?

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/83f8de99-906a-4ed9-b8c5-d940924b1dae
