### ISSUE TITLE
Linting does not appear on C-c (as it does with Esc)

### ISSUE THREAD

**Issue by jonathandw743** [siduck76/NvChad#2627]
If there is a syntax error, and insert mode is entered a change is made (not fixing the error), making the error disappear. Then to exit insert mode:
- if Esc is pressed, the errors reappear
- if C-c is pressed, the errors do not reappear

1. install nvchad and use the default config (y on the prompt)
2. create a new lua file and type `local x =`
3. press Esc to exit insert mode
4. an error appears
5. enter insert mode and replace `x` with `y`
6. press C-c to exit insert mode
7. the error does not reappear

**Expected behavior**
C-c and Esc have the same behaviour

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/85790952/64fea754-ae1b-459f-a9e4-da2d41afbddc)
![image](https://github.com/NvChad/NvChad/assets/85790952/57ffd763-dfae-4574-b7f0-ef1217d8bc5e)

 - Operating System - Ubuntu 22.04
 - Terminal - Zsh, tmux
 - Version of Neovim - 0.9.5

**Comment by siduck** [comment]
because linting will appear only   if you are in normal mode. Idk for some reason C-c doesnt trigger it, so either enable linting in insert mode too or just  map C-c to Esc

**Comment by jonathandw743** [comment]
Yeah, not a big issue, but it doesn't seem like intended behaviour.
