### ISSUE TITLE
Disable clickable x buttons and theme toggle in `tabufline`

### ISSUE THREAD

**Issue by kars0n777** [siduck76/NvChad#2628]
I can't seem to find a way to disable the clickable buttons in `tabufline`
I've looked in the `plugins` directory and can't find a way to configure this outside of the 

3 options that are listed in the `default_config`. I've even looked into the modules page in the source and can't seem to figure any solution out.

I just personally never use the mouse for closing buffers or toggling a theme, so to me, it just looks ugly having something I'll never use take up space on the top line. 

I've added a picture of what I'm trying to remove from the UI below, please let me know how this can be done. Thanks!

![remove](https://github.com/NvChad/NvChad/assets/79391709/f11ffdce-5d14-44f0-9f92-4be0d9c9effc)

**Comment by siduck** [comment]
please read nvchad.com docs, the ui section and override tabufline's last module to delete the last x. For the close btn for buffers, i dont think you can. its too much work
