### ISSUE TITLE
Editorconfig doesn't work

### ISSUE THREAD

**Issue by wgxh-cli** [siduck76/NvChad#2633]
**Describe the bug**
I set `indent_size = 2` in `.editorconfig` file, but in any file except lua this doesn't work, the tab size remains 2 spaces. 

**To Reproduce**
1. Add `vim.g.editorconfig = true` in your config file.
2. Add a `.editorconfig` to your filesystem and add the following to it.
```toml
[*]
indent_size = 2
```
3. Open file of any type, and insert a tab

**Expected behavior**
Inserted a tab with 2 spaces

**Desktop:**
 - Archlinux, with `bspwm`
 - wezterm
 - occurred in v0.9.4, v0.9.1 and nightly version

**Additional context**
[Neovim's editorconfig supporting](https://neovim.io/doc/user/editorconfig.html)

**Comment by siduck** [comment]
we dont disable editorconfig plugin so no idea why this doesnt work

**Comment by siduck** [comment]
does this work in non nvchad configs?

**Comment by siduck** [comment]
try with tinyvim

**Comment by wgxh-cli** [comment]
I tried, it worked in both tinyvim and vanilla neovim, and I also tried more neovim configurations such as LazyVim and AstroVim. It's strange that this also work with them.

And I tested all the plugins that NvChad used, editorconfig worked normally when they installed individually.

**Comment by siduck** [comment]
is your nvchad uptodate?

**Comment by wgxh-cli** [comment]
Yeah

**Comment by siduck** [comment]
how do i test if the indent is working

**Comment by wgxh-cli** [comment]
Check if it worked like what you set in `.editorconfig`,

**Comment by wgxh-cli** [comment]
In my case, this setting `indent_size` is 2, and `indent_style` is `space`

**Comment by siduck** [comment]
yes but how do i verify in vim, like it should change any option right? like shiftwidth or something

**Comment by wgxh-cli** [comment]
Check `tabstop`, `shiftwidth, `expandtab` and so on.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/c18590a1-d3cf-4f51-afa4-29659ad3232f

doesnt work in tiny/kickstart

**Comment by wgxh-cli** [comment]
Try to open some specified file, like python file, rust file

**Comment by wgxh-cli** [comment]
In tinyvim and vanilla neovim editorconfig worked normally.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/dba7a7b3-ca6e-402e-81d8-436cf1ccc9bc

works in nvchad too

**Comment by wgxh-cli** [comment]
https://github.com/NvChad/NvChad/assets/94696950/ecbc62bf-5ec0-4eca-b60a-4b2986137d8a

**Comment by siduck** [comment]
i'm sure line 107 in core/utils.lua is causing it `do FileType`

for a temporary fix just add 

              `require("editorconfig").config(args.buf)`

 and args parameter to the callback = function(args)

**Comment by wgxh-cli** [comment]
OK, thanks!
