### ISSUE TITLE
Custom mappings aren't loaded automatically

### ISSUE THREAD

**Issue by TheAnachronism** [siduck76/NvChad#2641]
**Describe the bug**
I'm currently trying to setup my own environment, and I've been running into the issue of my custom mappings not getting loaded.

**To Reproduce**
1. I've added `M.mappings = require 'custom.mappings'` to my `chadrc.lua` file
2. Then trying to add the following mapping for lazygit in my `mappings.lua` file:
```lua
local M = {}

M.lazygit = {
  plugin = true,
  n = {
    ["<leader>gg"] = {"<cmd> LazyGit<CR>", "LazyGit"},
  },
}

return M
```

**Expected behavior**
As mentioned here: https://nvchad.com/docs/config/mappings#manually_load_mappings the mapping should get automatically loaded, yet it's only available if I manually load it with `require("core.utils").load_mappings("lazygit")`

**Desktop (please complete the following information):**
 - Debian inside WSL
 - zsh
```bash
$ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

Did I miss anything in my config setup?

**Comment by siduck** [comment]
https://nvchad.com/docs/config/mappings#manually_load_mappings

**Comment by siduck** [comment]
at least read docs before making an issue

**Comment by TheAnachronism** [comment]
That's exactly what I did, and the docs say:

>Mappings will be automatically loaded. You don't need to load them manually!

Then why **aren't** they automatically loaded?

**Comment by siduck** [comment]
plugin=true is only needed if you want to manually load them, then how do u expect it to load by default? so remove plugin=true please
