### ISSUE TITLE
Center text option

### ISSUE THREAD

**Issue by rp1231** [siduck76/NvChad#2644]
**Is your feature request related to a problem? Please describe.**
Right now the file is located on the far left of the screen, where as it would be more comfortable if the
document was centered, like how it is in microsoft word.

**Describe the solution you'd like**
It would be great if the document could be centered

**Describe alternatives you've considered**
Using fancyzones to maximize the window to the middle zone.

**Comment by siduck** [comment]
use something like zenmode.nvim
