### ISSUE TITLE
How to get hover working?

### ISSUE THREAD

**Issue by LinuxIsCool** [siduck76/NvChad#2648]
When my cursor is over a word, I would like all instances of that word to be highlighted. 

I'm trying to do this using the nvim-treesitter-refactor plugin, but it's not working. I have in my plugins.lua:

```lua
  {
    "nvim-treesitter/nvim-treesitter-refactor",
    config = function()
      require("nvim-treesitter.configs").setup {
        refactor = {
          highlight_definitions = {
            enable = true,
            clear_on_cursor_move = true,
          },
        },
      }
    end,
  },
```

I notice that scope highlight is on, but hover is not working.
![image](https://github.com/NvChad/NvChad/assets/31582215/44421099-6a1f-4506-b126-dea9fdfdf5c3)

**Comment by siduck** [comment]
event='VeryLazy', i suggest to load this plugin after treesitter plugin i.e in its dependencies array
