### ISSUE TITLE
CursorColumn not working.

### ISSUE THREAD

**Issue by LinuxIsCool** [siduck76/NvChad#2654]
I got CursorLine working by adding to hl_override, but CursorColumn is not working in the same way. 

```
local M = {}

---@type Base46HLGroupsList
M.override = {
  Comment = {
    italic = true,
    fg = "#7f7f7f",
  },
  NvimTreeGitDirty = { fg = "red", bold = true },
  CursorLine = { bg = "line" },
  CursorColumn = { bg = "line" },
}

---@type HLTable
M.add = {
  NvimTreeOpenedFile = { fg = "purple", bold = true },
}

return M
```

![image](https://github.com/NvChad/NvChad/assets/31582215/6a9b1791-08c0-4ae6-9204-f0097c71c9f7)

I'm also wondering how I can add a colorcolumn=80

**Comment by siduck** [comment]
add that option in custom.initllua
