### ISSUE TITLE
many errors upon opening nvim just after cloning

### ISSUE THREAD

**Issue by 00spydude00** [siduck76/NvChad#2655]
**Describe the bug**
Displays many errors upon opening nvim and answering "n" to the prompt.

**To Reproduce**
1. Paste command to clone
2. answer "n" to prompt
3. See error

**Expected behavior**
Install nvchad

**Screenshots**
![Screenshot 2024-02-06 9 20 53 PM](https://github.com/NvChad/NvChad/assets/158379087/7ce2aadd-e16f-4b38-a331-23a5cc30333e)
![Screenshot 2024-02-06 9 45 55 PM](https://github.com/NvChad/NvChad/assets/158379087/29f9f81c-6d27-4717-9ce4-7e0824ab287e)

**Desktop (please complete the following information):**
 - ChromeOs with Linux (beta), AArch64
 - Xfce terminal
 - Neovim = 0.10.0 dev

**Additional context**
I downloaded neovim from source. I also ended up using Xfce4 terminal because the built in chromeOs terminal didn't allow nerdfonts. I am quite the beginner when it comes to these things, so any help in simple terms would be lovely.

**Comment by siduck** [comment]
rm -rf .local/share/nvim and other nvim dirs, then clone nvchad repo
