### ISSUE TITLE
getting luasnip error while opening any file

### ISSUE THREAD

**Issue by vadirajks** [siduck76/NvChad#2659]
getting below error when i am trying to open any file with the installation: 
![image](https://github.com/NvChad/NvChad/assets/2026134/52f886e7-68c9-4860-9d2b-62ad834cb2d7)
Please let me know how i can fix it.
Thanks

**Comment by siduck** [comment]
this isnt a nvchad issue. rm -rf all nvim dirs before installing nvchad and make sure you use neovim lts version which is 0.9.5, or at least 0.9+
