### ISSUE TITLE
conflict with noice.nvim

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2661]
**Describe the bug**
At seemingly random I get an issue where part of the screen will turn black

**To Reproduce**
1.) Install Nvchad version 2.0
2.) install noice.nvim with this configuration:
```
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "rcarriga/nvim-notify",
    },
    config = function()
    require("noice").setup {
  lsp = {
    hover = {
      enabled = false,
    },
    override = {
      ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
      ["vim.lsp.util.stylize_markdown"] = true,
      ["cmp.entry.get_documentation"] = true,
    },
    signature = {
      enabled = false,
    },
  },

  presets = {
    bottom_search = true, -- use a classic bottom cmdline for search
    command_palette = true, -- position the cmdline and popupmenu together
    long_message_to_split = true, -- long messages will be sent to a split
    -- inc_rename = false,           -- enables an input dialog for inc-rename.nvim
    -- lsp_doc_border = false,       -- add a border to hover docs and signature help
  },
}

    end,
  },
```

**Expected behavior**
for there to be no issue in editing and no loss of screen space.

**Screenshots**
![Screenshot 2024-02-09 134751](https://github.com/NvChad/NvChad/assets/65212972/087f6f91-75dc-44c9-b5b4-add2ded99bba)

**Desktop (please complete the following information):**
 - WSL2 ubuntu:
 Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

 - Terminal: windows terminal/ tmux
 - Version of Neovim: nightly

**Additional context**
my chadrc file is as follows:
```
---@class ChadrcConfig
local M = {}
M.ui = {
  theme = "catppuccin",
  nvdash = {
    load_on_startup = true,
  },
}
M.mappings = require "custom.mappings" --loads the mappings?
M.plugins = "custom.plugins" --tells it where to look?
return M
```
The reason I am posting here instead of noice is because I cant reproduce it without the NvChad plugins, I have narrowed it down to just this plugin with the addition of the base NvChad plugins.

**Comment by siduck** [comment]
please make a video, i dont see black screen   anywhere.

**Comment by DrTeagle** [comment]
I am having trouble with uploading a video, how would you have me do it? the black box is in the top right corner blocking out some of the text.

**Comment by siduck** [comment]
> I am having trouble with uploading a video, how would you have me do it? the black box is in the top right corner blocking out some of the text.

  post it on our discord channel, doing convo there seems easier than here as i dont have github notifs enabled!
