### ISSUE TITLE
Some Characters not showing (shows with --clean flag)

### ISSUE THREAD

**Issue by skyler-0** [siduck76/NvChad#2663]
**Describe the bug**
Some Characters at the start of the line are missing (not showing for some reason) 
**To Reproduce**
1. Start Neovim (that's it)

**Expected behavior**
The Characters should be visible

**Screenshots**
![Screenshot from 2024-02-11 08-20-01](https://github.com/NvChad/NvChad/assets/81177923/659bbeea-8793-4f1b-b9fc-22738a8dd39a)

**Desktop (please complete the following information):**
 - Operating System -- Fedora 38 Workstation, Kernel Version: 6.7.3-100.fc38.x86_64
 - Terminal -- Gnome Terminal
 - Version of Neovim -- NVIM v0.9.5

**Additional context**
the issue is not there with other files, I only find bugs in `config.h` files for suckless utilites

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/ddbd508e-a2f1-4a7d-9b3b-83bb8dc5219c)

unable to reproduce, can you try other terminals

**Comment by skyler-0** [comment]
st screenshot:
![image](https://github.com/NvChad/NvChad/assets/81177923/531330fb-1b8c-4b3f-8ea2-58daafd848b3)

other theme in gnome terminal:
![image](https://github.com/NvChad/NvChad/assets/81177923/4b76c4ab-d31a-4b43-a6c6-c33df81f82a2)

kitty screenshot:
![image](https://github.com/NvChad/NvChad/assets/81177923/c0039f57-d11b-49a1-8b3d-3cbb98e008b8)

**Comment by siduck** [comment]
show me your plugin list, also talk in our discord server if you can, would be faster to fix than here as i dont have github notifs enabled.

**Comment by skyler-0** [comment]
Apparently it gets fixed when I enter `:set shiftwidth=2` my current shiftwidth is 4



> show me your plugin list, also talk in our discord server if you can, would be faster to fix than here as i dont have github notifs enabled.

no extra plugins installed
yes I will join the discord

Edit: 

tabstop=4 fixed it.

For  those who change 1 indent related option, make sure you do it for others too

![image](https://github.com/NvChad/NvChad/assets/59060246/0d470e21-f791-4beb-baa1-65c28e030a7d)
