### ISSUE TITLE
Unable to load vs code snippets

### ISSUE THREAD

**Issue by carried-away** [siduck76/NvChad#2667]
**Describe the bug**
Snippets do not show when prefix is typed

**To Reproduce**

As per the documentation, in my init.lua i put

vim.g.vscode_snippets_path = "C:\\Users\\user1\\AppData\\Local\\nvim\\snippets"

(ive also tried "~/nvim/snippets and "C:/Users/user1/AppData/Local/nvim/snippets")

Inside nvim/snippets i created a package.json file

``` json
{
	"name": "cookbook-snippets",
	"contributes": {
		"snippets": [
			{
				"language": [
					"all"
				],
				"path": ./cookbook.json"
			},
		]
	}
}
```

I created a cookbook.json file in the same snippets folder as package.json

``` json
{
	"Icon": {
		"prefix": "cook-docs-frontmatter",
		"body": [
		  "---",
		  "icon:",
		  "---",
		],
		"description": "Inserts an icon"
	  },
}
```

(I've also tried the absolute path C:/Users/user1/AppData/Local/nvim/snippets/cookbook.json)

**Expected behavior**
The snippet to show when the prefix is typed

**Desktop (please complete the following information):**
 -  windows
 - neovim
 - NVIM v0.10.0-dev-1731+g0bbe8e7fc
 - 
**Additional context**
I've spent two weeks on this. I'm ashamed to say that its brought me to tears and i've read the docs so much that I felt like i wrote the documentation. I really need help here. When i try to do ls.log.open(debug) I'm getting no output.

**Comment by siduck** [comment]
@carried-away this is mostly a luasnip issue, you should ask in our discord server as its more active and other snippet users could help you.

**Comment by carried-away** [comment]
Thanks for all your help

**Comment by siduck** [comment]
if you put your path here , plugins/configs/others.lua and  it works then i'll reopen this issue
![image](https://github.com/NvChad/NvChad/assets/59060246/4989d65d-8bb1-430b-aa05-12199a22a5b5)

**Comment by carried-away** [comment]
After doing that, luasnip fails to even load. I really do appreciate your time. But I've spent so much time on this that I have neglected everything else. I'm going to have to switch to vs code like the intellectually inferior piece of garbage that I am.

**Comment by siduck** [comment]
> After doing that, luasnip fails to even load. I really do appreciate your time. But I've spent so much time on this that I have neglected everything else. I'm going to have to switch to vs code like the intellectually inferior piece of garbage that I am.

show me what you did :/
