### ISSUE TITLE
Disable UI Buttons for Closing Tabs and Switching Themes in NvChad

### ISSUE THREAD

**Issue by riceset** [siduck76/NvChad#2671]
I have been enjoying the use of NvChad for my development work. However, I find that I do not need the GUI buttons for closing tabs and switching themes, and I would prefer to disable them to streamline my workflow.

I have attached a screenshot for reference. In the top right corner, there are buttons for closing tabs and switching themes. I am looking for a way to either remove or disable these buttons.

Is there a setting or configuration file where I can adjust the visibility of these UI elements? If so, could you please guide me on how to do this?

<img width="495" alt="Screenshot 2024-02-15 at 15 24 19" src="https://github.com/NvChad/NvChad/assets/48802655/25aafd9d-4876-4ea8-9238-be5d5a9d7efb">

**Comment by siduck** [comment]
read and override tabufline modules https://nvchad.com/docs/config/nvchad_ui

hint: table.remove(modules, 4)

**Comment by riceset** [comment]
Solved by doing the following:

```lua
---@type ChadrcConfig
local M = {}

M.ui = {
  tabufline = {
    order = {"buffers"}
  }
}

return M
```

**Comment by siduck** [comment]
@riceset you can add the treeoffset tho, or else when nvimtree is opened then tabufline will take its space too
