### ISSUE TITLE
Commit f17e830 ignores `vim.g.editorconfig`.

### ISSUE THREAD

**Issue by nega0** [siduck76/NvChad#2672]
**Describe the bug**
When `vim.g.editorconfig = false`. Commit f17e830 still forces editorconfig on, locally to the buffer.

**To Reproduce**
1. add `vim.g.editorconfig = false` to `custom/init.lua`
2. `:NvChadUpdate` and restart neovim
3. load file from a project with a `.editorconfig`
4. `:lua =vim.g.editorconfig` reports `false` as expected
5. `:lua =vim.b.editorconfig` reports `{}`, expected `nil`

**Expected behavior**
I'd expect editorconfig to be disabled when it's explicitly disabled.

**Screenshots**
n/a

**Desktop (please complete the following information):**
macos, nvim v0.9.5

**Additional context**
Works as expected in vanilla nvim and prior to f17e830 (`git checkout f17e830^`)

**Comment by siduck** [comment]
@nega0  try disabling editorconfig in lazy options itself

**Comment by nega0** [comment]
didn't work. even tried it in NvChad's `lazy_nvim.lua` directly.
