### ISSUE TITLE
Adding frappe variant for catppuccin theme

### ISSUE THREAD

**Issue by M-Sviridov** [siduck76/NvChad#2674]
Hi,

How would one approach this issue? I'd like to contribute by adding the frappe variant for the catppuccin theme.

I have the colors for base16 and a few for base30 using the official catppuccin palette, but how could I find the remaining colors? Especially when working with colors that are lighter/darker by a certain percentage. I do not know what that means and how I can find a color that is said - lighter or darker by a percentage.

I am more than happy to do the work and contribute if someone can bring a bit of guidance.

Thank you.

**Comment by siduck** [comment]
by lighter etc its meant to have lighter shades, there are many tools online that let you make a color darker or lighter, just use them
