### ISSUE TITLE
Deleting into the blackhole register does not work as expected

### ISSUE THREAD

**Issue by elkaramella** [siduck76/NvChad#2681]
**Describe the bug**
I added a a key mapping to `lua/custom/mappings.lua` in order to map the backspace key in visual mode to delete into the blackhole register, however, if I yank a line with `yy` then after that I delete another line using the backspace in the visual mode then I paste the line I yanked earlier then I am seeing the line that I deleted with the backspace
**To Reproduce**
1. Open `~/.config/nvim/lua/custom/mappings.lua`
2. Add 
```
v = {
  ["<BS>"] = {"_d", "delete"},
}
```
For example my mappings.lua looks like this
```
-- ~/.config/nvim/lua/custom/mappings.lua
---@type MappingsTable
local M = {}

M.general = {
  n = {
    [";"] = { ":", "enter command mode", opts = { nowait = true } },

    --  format with conform
    ["<leader>fm"] = {
      function()
        require("conform").format()
      end,
      "formatting",
    }

  },
  v = {
    [">"] = { ">gv", "indent"},
    ["<BS>"] = {"_d", "delete"},
  },
}

-- more keybinds!

return M
```
then save and close neovim.
4. Open any file with neovim the yank line 1 using `yy` then go to line 2 and highlight it with shift+v and click backspace.
Then click `p`

**Expected behavior**
I expect to see the line I yanked earlier, line 1 in step 4.

**Desktop (please complete the following information):**
 - macOS Monterey
 - iterm2
 - NVIM v0.9.5

**Comment by siduck** [comment]
does it work with vim.keymap.set?

**Comment by elkaramella** [comment]
I am a bit of a noob, so I just want to share what I tried, but I still see the same behavior with this change

```
-- ~/.config/nvim/lua/custom/mappings.lua
local M = {}

vim.keymap.set('v', '<BS>', '_d', { silent = true })
.
.
```

**Comment by siduck** [comment]
if it doesnt work with that then we cant do anything about it as we use that func under the hood

**Comment by Hucy** [comment]
> I am a bit of a noob, so I just want to share what I tried, but I still see the same behavior with this change

> Use the "black hole register", `"_` to really delete something: `"_d`.


```lua
vim.keymap.set('v', '<BS>', '"_d', { silent = true })
```
Hope it helps you
