### ISSUE TITLE
Telescope current_buffer_fuzzy_find does not work out of the box

### ISSUE THREAD

**Issue by szevzol** [siduck76/NvChad#2685]
**Describe the bug**
Telescope current_buffer_fuzzy_find does not work out of the box after installing NvChad.
When trying to jump to the searched word, it throws error message. Interestingly, if I enter words only in UPPERCASE letters then it works.

**To Reproduce**
1. Open a text file to have a buffer
2. `:Telescope current_buffer_fuzzy_find`
3. Try to find a word and press enter
4. Following error message can be seen:
```lua
E5108: Error executing lua: ...ta/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:552: attempt to compare two table values
stack traceback:
        ...ta/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:552: in function 'run_replace_or_original'
        ...im-data/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:269: in function <...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:268>
```

**Expected behavior**
Jump to the word I typed in the search box.

**Screenshots**
Not necessary, I pasted the error message above.

**Desktop (please complete the following information):**
 - Microsoft Windows 10 Enterprise 10.0.19045 Build 19045
 - Powershell inside Microsoft Terminal
 - Version of Neovim:
```
:version
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

**Additional context**

It seems I should use fzf extension to fix the issue. In my `custom/plugins.lua` I have to add fzf as a dependency and add the extension to the default list of extensions.

```lua
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      {
        "nvim-telescope/telescope-fzf-native.nvim",
        build = "make"
      }
    },
    opts  {
      extensions_list = { "themes", "terms", "fzf" }
    },
  },

```

In case fzf cannot be loaded because of missing dll file, you have to build it. Make sure you have make and gcc available and then in `:Lazy` step on fzf and do `:gb`.

**Comment by siduck** [comment]
Uploading simplescreenrecorder-2024-02-23_15.49.26.mp4…

it works without fzf btw, nvchad doesnt come with that plugin too.

**Comment by szevzol** [comment]
> Uploading simplescreenrecorder-2024-02-23_15.49.26.mp4…
> 
> it works without fzf btw, nvchad doesnt come with that plugin too.

Sorry, does it mean that this issue does not exist and I have to investigate it on my side?

**Comment by siduck** [comment]
> > Uploading simplescreenrecorder-2024-02-23_15.49.26.mp4…
> > it works without fzf btw, nvchad doesnt come with that plugin too.
> 
> Sorry, does it mean that this issue does not exist and I have to investigate it on my side?

most likely. i'm on v3.0 nvchad rn ( BETA ) , just tested v2.0 for you in case there's an issue at our end

https://github.com/NvChad/NvChad/assets/59060246/1c9cb973-6709-4941-bb59-31b2c280215f

**Comment by szevzol** [comment]
@siduck , thank you for quickly trying reproducing this! I found a reddit post dealing with the same issue:

https://www.reddit.com/r/neovim/comments/1at051s/telescope_current_buffer_fuzzy_find_error_when/

It can be a Telescope issue, so I started to gather info to file an issue on Telescope. However, their minimal.lua config for the issue submission contains installing and using fzf extension so that's why I cannot reproduce and send an issue to Telescope...

**Comment by siduck** [comment]
@szevzol  try their minimal config without that fzf plugin, or probably its required for that feature? but its weird that i cant reproduce it, try seeking help on our discord, many might help u

**Comment by szevzol** [comment]
> @szevzol try their minimal config without that fzf plugin, or probably its required for that feature? but its weird that i cant reproduce it, try seeking help on our discord, many might help u

Submitted issue on Telescope https://github.com/nvim-telescope/telescope.nvim/issues/2941
