### ISSUE TITLE
Mason errors on initial post install if "unzip" not installed on system

### ISSUE THREAD

**Issue by b4shful** [siduck76/NvChad#2691]
**Describe the bug**
First run/initial setup on environments without `unzip` installed will cause Mason package install failures (on 5 packages like clangd which require unzip). Also the post-first-time-install "NOTES" page will not be shown after this failure, it just leaves Mason up on screen. I solved this issue myself by installing `unzip` then restarting my terminal, and then uninstalling and reinstalling NvChad, but it might be worth looking into. 

Perhaps there should be a check somewhere to see if `unzip` is a valid command on the system? Or simpler yet, reminding users in the prerequisites section of the docs that they should have the `unzip` package or something aliased to `unzip`.

**To Reproduce**
(0. Ensure you don't have `unzip` or any program which can handle `unzip` commands installed)
1. Install with `git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
2. Select "y" when prompted to install example config

**Expected behavior**
Install happens without errors

**Desktop (please complete the following information):**
 - Operating System: Arch Linux 
 - Terminal: foot
 - Version of Neovim: 0.9.5

**Comment by siduck** [comment]
mason at least expects unzip to be installed on system for linux
