### ISSUE TITLE
Error code shows in help page

### ISSUE THREAD

**Issue by moooooo16** [siduck76/NvChad#2692]
**Describe the bug**
Error code displayed on help page.

**To Reproduce**
1.`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
2. `y` when ask to use custom config
3. Reenter after lazy setup completed.
4. `:Lazy` -> `U` to update all
5. `<leader>fh` to enter help page
6. Select any entry
7. Use `j` to nevigate
8. Red color erro code mixed with document

**Expected behavior**
Use `j` to navigate without error display

**Screenshots**
![截屏2024-02-25 上午11 41 35](https://github.com/NvChad/NvChad/assets/78249781/a7fe6155-18e4-49bb-9f80-08c50c567e8a)

**Desktop (please complete the following information):**
 - Operating System
   - MacOs 14.3.1
 - Terminal
   - iterm2: 3.4.23 (Also tested on Mac's Terminal.app)
 - Version of Neovim
   - NVIM v0.9.5

**Additional context**
N/A

**Comment by siduck** [comment]
:TSInstall vimdoc vim
