### ISSUE TITLE
Treesitter missing languages syntax

### ISSUE THREAD

**Issue by r3k2** [siduck76/NvChad#2697]
**Is your feature request related to a problem? Please describe.**
I check the list of supported syntax in the main treesitter git repo and lists a couple that
I do not see listed under nvchad, such with this it will fail to install...

**Describe the solution you'd like**
I will like for the list to be updated on nvchad with the supported syntax in the main treesitter repo supported list

**Describe alternatives you've considered**
changing to lazyvim

**Additional context**
This is kind of a game stopper for me since I work in Offensive security/hacking and I do software but also debug and break, find vulnerabilities
so I need some of that syntax on my day-to-day work.

**Comment by siduck** [comment]
TSInstall install language?

**Comment by siduck** [comment]
nvchad only installs vim, vimdoc, and lua ones by default.

**Comment by r3k2** [comment]
@siduck do you really think I will waste my time to create a ticket, if it was something as easy as to just read the documentation and run TSInstall ???? I feel very disrespected as if You called me stupid, because is what you just did. I have been 30 years doing Hacking Coding in ASM and C do you think I am going to waste my time if I could just run TSInstall  anything listed here? https://github.com/nvim-treesitter/nvim-treesitter 
![swappy-20240229-024155](https://github.com/NvChad/NvChad/assets/5316229/5a5f40c5-bd0d-4053-850a-dda329876a55)
do I also need to run a TSInfo and paste it here so you see I not all listed on the git repo are listed in nvchad as in my original msg?

**Comment by siduck** [comment]
@r3k2 first of all chill, in your initial message you didnt even mention disassembly so how would i know if you're not talking about it?

Also update nvchad as i fixed the issue for you now. NvChad was using v0.9.2 tag of nvim-treesitter plugin so which didnt had disassembly.

I locked to that version because treesitter had some huge breaking changes in highlight group names so i had to change a lot of files in base46

https://github.com/NvChad/base46/commit/36a44bf1c712a42b46479540ee89e296c6c63cdc

**Comment by r3k2** [comment]
Hello, well it was obvious, I *did* mention that not all the syntax languages in the main repo git were in nvchad, instead you assumed I was a lamer user and insulted me with obvious run this commands… instead of looking into the issue.  And as of now after running an Update on Lazy I saw that there was and update but still lacking this language and some others, does not matter which ones, it should be 100% in sync right ? And if not in sync, it should be noted somewhere. So now I do ask, after running Lazy update and TSUpdateSync etc. am I missing something?
![2024-02-29-191649](https://github.com/NvChad/NvChad/assets/5316229/ebce30f5-75fb-4cec-9d70-43ebd1527ae7)

**Comment by pazbryant7** [comment]
> Hello, well it was obvious, I _did_ mention that not all the syntax languages in the main repo git were in nvchad, instead you assumed I was a lamer user and insulted me with obvious run this commands… instead of looking into the issue. And as of now after running an Update on Lazy I saw that there was and update but still lacking this language and some others, does not matter which ones, it should be 100% in sync right ? And if not in sync, it should be noted somewhere. So now I do ask, after running Lazy update and TSUpdateSync etc. am I missing something? ![2024-02-29-191649](https://private-user-images.githubusercontent.com/5316229/309034714-ebce30f5-75fb-4cec-9d70-43ebd1527ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzU3NTYsIm5iZiI6MTcwOTIzNTQ1NiwicGF0aCI6Ii81MzE2MjI5LzMwOTAzNDcxNC1lYmNlMzBmNS03NWZiLTRjZWMtOWQ3MC00M2ViZDE1MjdhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTkzNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNjMzFlZDNiYTc0NDcyZjQ4Mjc1MDA1NjVlZTUxNTJlYWE0MmI3NzZmNWIxOWRkY2M3NzhlYTMzZTE5YzU4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4sjT8-Lec03T6TdvtBdrWowu00V-2tq-07HsvJM0FGs)

Probably friends

**Comment by siduck** [comment]
@r3k2 
run NvChadUpdate command or git pull in the ~/.config/nvim dir
