### ISSUE TITLE
Black formatting does not work

### ISSUE THREAD

**Issue by A-tA-v** [siduck76/NvChad#2700]
**Describe the bug**
"leader + fm" command produces the message:
_[null-ls] failed to run generator: ....local/share/nvim/lazy/null-ls.nvim/lua/null-ls/loop.lua:165: command black is not executable (make sure it's installed and on your $PATH)_

After the second command "leader + fm", the message is different:
_[LSP] Format request failed, no matching language servers._

Btw, exactly the same (first) message appears regarding mypy.

Both "black" and "mypy" are installed, and $PATH points correctly to the Python virtual environment.  

**To Reproduce**
Default installation on OSX Sonoma + Homebrew

**Expected behavior**
Expects fomatting of a Python file

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OSX Sonoma, Homebrew
 - iTerm2
 - The latest Neovim (0.9.5) and the latest update of NvChad

**Additional context**
N/A

**Comment by siduck** [comment]
install black on your OS, use either mason or something. Error is clear btw

**Comment by A-tA-v** [comment]
Hi Sidhanth, I do not quite understand the answer. Black is already installed in virtual environment and I run NvChad from that environment inside a terminal. Do you mean a system-wide installation?

**Comment by siduck** [comment]
hi, null-ls error is clear tho, it cant find the executable. open nvim and terminal inside it by :term command, and run black command. 

Also i suggest using conform https://github.com/stevearc/conform.nvim

**Comment by siduck** [comment]
using it is pretty ez too https://github.com/NvChad/example_config/blob/v2.0/configs/conform.lua

**Comment by A-tA-v** [comment]
I would prefer to stay with the default plugins because my Neovim experience is very limited. 

I tried:
```
export PATH=$(dirname $(which python3)):${PATH} && nvim
```
No effect, although "black" is installed in every Python environment including the system one.

I commented out "black" and added the absolute path in "black.lua", and it works!
The same approach works for "mypy" as well (file "mypy.lua").
There is a path resolution issue somewhere.

```
local h = require("null-ls.helpers")
local u = require("null-ls.utils")
local methods = require("null-ls.methods")

local FORMATTING = methods.internal.FORMATTING

return h.make_builtin({
    name = "black",
    meta = {
        url = "https://github.com/psf/black",
        description = "The uncompromising Python code formatter",
    },
    method = FORMATTING,
    filetypes = { "python" },
    generator_opts = {
        -- command = "black",
        command = "/Users/my-user-name/venv/qu/bin/black",   -- <<<<<<<<< HERE
        args = {
            "--stdin-filename",
            "$FILENAME",
            "--quiet",
            "-",
        },
        to_stdin = true,
        cwd = h.cache.by_bufnr(function(params)
            return u.root_pattern(
                -- https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
                "pyproject.toml"
            )(params.bufname)
        end),
    },
    factory = h.formatter_factory,
})
```

**Comment by siduck** [comment]
try conform, nullls is dead man
