### ISSUE TITLE
FAQ <ctrl-i> and <tab> documentation

### ISSUE THREAD

**Issue by iaquobe** [siduck76/NvChad#2701]
First off, thanks so much for this project. It's really a great distro and configuring mostly very quick and easy.

I have a suggestion for the documentation in the [faq about tab](https://nvchad.com/docs/faq#mapping_ctrl_+_o_/_i_keys).
I just spend a good amount of time disabling this mapping, because I was trying `<Tab>`, which is how it is referred in all the docs and `:nmap` also reported it to be `<Tab>`. 
Only after learning that it's case sensitive and digging through the code, did I find that its: `<tab>`.

I think it would be useful to have a little note about it in the faq, like: 
**NOTE:** key mappings are case sensitive, to disable the keymap use `<tab>`

**Comment by siduck** [comment]
send a pr! https://github.com/NvChad/nvchad.github.io/blob/main/src/routes/docs/faq.mdx

**Comment by iaquobe** [comment]
It's the first time I did a pull request. I think it should be online.
