### ISSUE TITLE
Cant change cursor style

### ISSUE THREAD

**Issue by quadans** [siduck76/NvChad#2703]
I tried to google and chatgpt and I cant seem to change the cursor style.
I want the cursor to be underline in insert mode and the block to be a block-outline in all other modes. Like this:
![block](https://github.com/NvChad/NvChad/assets/47493031/49c65e70-5c36-4005-a637-6b2158b9ed4d)
Also, disable blinking.
All solutions I found are only for vim which is not suitable for nvchad config in chadrc.lua or init.lua. On the fly settings like `:set guicursor+=a:blinkon0` doesnt work.

OS : Arch
Terminal : Kitty
NVIM v0.9.5

**Comment by siduck** [comment]
i tried with nvim --clean. Didnt work too, Ig its dependent on your terminal. so not a nvchad issue

>  which is not suitable for nvchad config in chadrc.lua or init.lua.

You should know chadrc is just meant to be an override of `core/default_config`  and you can add such options in init.lua.

it looks like a vimscript code so wrap in `vim.cmd` or convert to lua using vim.opt
