### ISSUE TITLE
How to close nvterm 

### ISSUE THREAD

**Issue by calvin0327** [siduck76/NvChad#2704]
**Describe the bug**
I open a new terminal type `space + h`, but I not found a mapping to close the terminal.

<img width="1001" alt="image" src="https://github.com/NvChad/NvChad/assets/45745657/7a6fcd4e-0a91-4a62-8ce6-84d8ab5df716">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
press ctrl x to get out of terminal mode. and the leader x

**Comment by calvin0327** [comment]
> press ctrl x to get out of terminal mode. and the leader x

thanks for this, it's work.
