### ISSUE TITLE
Can't `require` a module for nvim tree

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [siduck76/NvChad#2705]
**Describe the bug**
So I just have this piece of code this will `require` this module that is called `custom.configs.nvimtree.lua` but I am getting an error says that no module found. Here is the tree structure of my directoreis

```
├── LICENSE
├── init.lua
├── lazy-lock.json
└── lua
    ├── core
    │   ├── bootstrap.lua
    │   ├── default_config.lua
    │   ├── init.lua
    │   ├── mappings.lua
    │   └── utils.lua
    ├── custom
    │   ├── chadrc.lua
    │   ├── configs
    │   │   ├── lspconfig.lua
    │   │   └── nvimtree.lua
    │   └── plugins.lua
    └── plugins
        ├── configs
        │   ├── cmp.lua
        │   ├── lazy_nvim.lua
        │   ├── lspconfig.lua
        │   ├── mason.lua
        │   ├── nvimtree.lua
        │   ├── others.lua
        │   ├── telescope.lua
        │   └── treesitter.lua
        └── init.lua
```

and here is the piece of code that contains the nvimtree config in `custom/plugins.lua`
```lua
...
{
    "nvim-tree/nvim-tree.lua",
    opts = function()
        return require "custom.configs.nvimtree"
        end
},
...
```

and here is what in `custom/configs/nvimtree.lua`

```lua
local options = {
  filters = {
    custom = {
      ".venv",
      "^.git$"
    }
  }
}

return options

```
**To Reproduce**
1. Delete the `nvimtree.lua` and create it again
2. Make sure that it have been saved
3. Rename it

**Expected behavior**
To see it working
**Screenshots*

**Desktop (please complete the following information):**
 - OS: Ubuntu 22 lts on WSL
 - terminal :windows terminal with zsh shell
 - version of neovim 
 ```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
 ```

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/47df4b2d-48ca-40c4-9f33-d9da427ffbe8

Cant reproduce.

**Comment by ZeyadMoustafaKamal** [comment]
@siduck Well there are two things here 

first. I solved it by adding `require "lua.cuatom.configs.nvimtree"`

and second ... what is this theme? or how to make Arch like this ??🙂

**Comment by siduck** [comment]
@ZeyadMoustafaKamal  lua is alreday on path!  u should do cuatom.configs.nvimtree.

Also that theme is everforest, but its  my custom rice!  i will share dotfiles this year.

**Comment by ZeyadMoustafaKamal** [comment]
@siduck Thanks for replying. yeah, you are right. The problem was that I managed my dotfiles using rcm and when I created nvimtree.lua it was created in `~/.dotfiles/config/nvim/lua/custom/configs/nvimtree.lua` not in `~/.config/nvim/lua/custom/nvimtree.lua` so when I opened neovim from `~/.dotfiles/config/nvim` and required it using `lua.custom.configs.nvimtree` it worked but when opened another directory it didn't work so the simple solution is to create nvimtree.lua in `~/.config/nvim/lua/custom/nvimtree.lua`. Sorry for the long explanation but this is just if anyone had the same issue.
