### ISSUE TITLE
Add mason-lspconfig.nvim

### ISSUE THREAD

**Issue by gitaarik** [siduck76/NvChad#2707]
**Is your feature request related to a problem? Please describe.**
I haven't run into any problems, but it is recommended by mason.nvim if you use it together with lspconfig.

**Describe the solution you'd like**
Add mason-lspconfig.nvim as a default dependency in NvChad, having it loaded in the right order as described here:
https://github.com/williamboman/mason-lspconfig.nvim?tab=readme-ov-file#setup

**Comment by siduck** [comment]
@gitaarik its a problematic plugin imo, breaks all the lazyloading. 

Instead of that i suggest using a command that'll capture all the lsps configured in your config and then install them with mason. I'll see if i can make this in the future, need to support conform etc too! 

Also mason lspconfig adds some abstraction which i dont want for newbies

**Comment by gitaarik** [comment]
Aha ok, sounds fair.

It would indeed also be nice not to have to define your dependencies in two spots, although I don't mind it too much, it makes sense, one is for the install, the other is to configure.

But if Mason would automatically detect which dependencies you need by looking at your lspconfig / conform, then you would maybe also make it look at nvim-lint, if it is used..

There is apparently something like this for null-ls btw, maybe it can help for inspiration:
https://github.com/jay-babu/mason-null-ls.nvim

**Comment by siduck** [comment]
by my module, mason wont detect anything , we'll just give it a list of packages to install.

For example we'll have a list of lsp server names + their mason pkgs name. And there's a nvim function which gets us the configured lsp servers. 

Ig it'd be the same with nvim-lint, conform

**Comment by gitaarik** [comment]
Aha ok, but isn't that "detecting"? A function which gets the configured LSP servers, and then installs the appropriate Mason packages?

And so then you'll also have to get a list of configured formatting / linting tools.

**Comment by siduck** [comment]
it is detecting but mason doesnt do it, we just compute all the values and give mason the pkgs need to install :)

**Comment by gitaarik** [comment]
Aha ok, sounds good :+1:
