### ISSUE TITLE
Latest installation doesn't match the description

### ISSUE THREAD

**Issue by shu-bc** [siduck76/NvChad#2717]
**Describe the bug**
I try to install latest release v2.5. Migration script doesn't work for me. So I remove all related files and run latest installation script.
```sh
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim

 git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
```
According to the description of the section `Main Config Structure` of [walkthrough page](https://nvchad.com/docs/config/walkthrough), there is `nvchad` diretory in  `~/.config/nvim/lua`. But there are only `config`, `plugins`, which matches https://github.com/NvChad/starter . 

In `~/.config/nvim/init.lua`, I find refereces to `nvchad` diretory, like 
```lua
require "nvchad.autocmds"
```
so I suspect that nvchad diretory should be included in starter repo.

**To Reproduce**
See the section above

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: macOS 14.3.1
 - Terminal: iTerm2 
 - Version of Neovim: 0.9.5

**Additional context**

**Comment by siduck** [comment]
main nvchad repo 
![image](https://github.com/NvChad/NvChad/assets/59060246/4261c589-63a6-4aa9-a4ae-e1c90d5d11a9)


not starter repo. 

That structure is provided to give users an IDEA about what they're importing i.e nvchad/nvchad repo

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad
