### ISSUE TITLE
NvChad not installing as expected

### ISSUE THREAD

**Issue by TimmyMcPickles** [siduck76/NvChad#2718]
**Describe the bug**
When I clone the repo and open neovim, nvchad doesn't initially load. The only change to nvim is text saying "use this along starter!!!"

**To Reproduce**
clone the github repository into ~/.config/nvim --depth 1

**Expected behavior**
Expected it to give a prompt asking if I want to install an example config(which I planned to press no on, so I could config myself.)

**Desktop (please complete the following information):**
 - Operating System: Arch Linux
 - Terminal: Kitty
 - Version of Neovim: 0.9.5

**Additional context**
I tried installing NvChad on a different distro last night and this worked fine so I'm not sure if this is from a recent change, or an issue with my recent install of arch. I also installed the starter config earlier which worked fine, although it gave me a separate lua error on startup that I didn't think to copy and paste at the time.

**Comment by GurmanDhami05** [comment]
I have the same problem

**Comment by siduck** [comment]
https://nvchad.com/news/v2.5_release

so clone the starter repo. not mainr epo
