### ISSUE TITLE
Error on :MasonInstall

### ISSUE THREAD

**Issue by susnick** [siduck76/NvChad#2720]
**Describe the bug**
Following directions for windows powershell results in the following error.

Error executing Lua callback: ...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Wrong number of arguments             stack traceback:
        [C]: in function 'cmd'
        ...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>

**To Reproduce**
1. git clone https://github.com/NvChad/starter $ENV:USERPROFILE\AppData\Local\nvim && nvim
2. :MasonInstall

**Expected behavior**
I have no clue what is supposed to happen after this

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - MS Terminal
 - NVIM v0.9.5

**Comment by drewvanstone** [comment]
I've just run into this as well. Same version of NVIM.

**Comment by siduck** [comment]
MasonInstallAll, fixed the doc
