### ISSUE TITLE
CursorLine high light override not working after migrate to v2.5

### ISSUE THREAD

**Issue by DefectingCat** [siduck76/NvChad#2723]
**Describe the bug**
CursorLine high light override not working after migrate to v2.5. 

Im using migrate script to migrated configs. The CursorLine config is in `lua/chadrc.lua`. 

![image](https://github.com/NvChad/NvChad/assets/25033493/29315054-4333-46f0-aebd-c8159a09a448)

Other override seem works fine.

![image](https://github.com/NvChad/NvChad/assets/25033493/a5b3d828-69ab-4ba5-b704-516354a9fd70)

**To Reproduce**
1. Override CursorLine color in `chadrc.lua`

**Expected behavior**
The color has been override.

**Screenshots**
on above

**Desktop (please complete the following information):**
 - Operating System: macos
 - Terminal: kitty with tmux
 - Version of Neovim: 0.9.5

**Comment by DefectingCat** [comment]
Current whole configs https://github.com/DefectingCat/nvim , if this can help

**Comment by siduck** [comment]
`vim.o.cursorlineopt ='number,line'`

we set it to just number in default nvchad
