### ISSUE TITLE
UltiSnipsJumpForwardTrigger isn't working

### ISSUE THREAD

**Issue by salastro** [siduck76/NvChad#2724]
**Describe the bug**
Added the following config for Ultisnip:
```lua
  {
    "L3MON4D3/LuaSnip",
    enabled = false,
  },
  {
    "SirVer/ultisnips",
    commit = "f6d1501b630cb783b0af8507c5588328f826d40f",
    dependencies = {
      "honza/vim-snippets",
      "quangnguyen30192/cmp-nvim-ultisnips",
    },
    event = "InsertEnter",
    config = function()
      vim.g.loaded_python3_provider = nil
      vim.g.UltiSnipsExpandTrigger="<Tab>"
      vim.g.UltiSnipsJumpForwardTrigger="<Tab>"
      vim.g.UltiSnipsJumpBackwardTrigger="<S-Tab>"
      vim.g.UltiSnipsEditSplit = "vertical"
    end,
  },
```
The following for cmp:
```lua
.
.
.
  snippet = {
    expand = function(args)
      vim.fn["UltiSnips#Anon"](args.body)
    end,
.
.
.
    ["<C-Tab>"] = cmp.mapping(function()
      if cmp.visible() then
        cmp.confirm {
          behavior = cmp.ConfirmBehavior.Insert,
          select = true,
        }
      else
        cmp.complete()
      end
    end, {
      "i",
      "c",
    }),
.
.
.
  sources = {
    { name = "nvim_lsp" },
    { name = "ultisnips" },
    { name = "buffer" },
    { name = "nvim_lua" },
    { name = "path" },
  },
.
.
.
```
However, when I <Tab> after snippet expansion, the cursor does not go to the next field. Instead, the operation is existed and I am left with incomplete snippet that I have to modify manually. I am submitting this here since this issue is only in NvChad and only with <Tab> which probably means that there is another configuration/plugin that conflicts with Ultisnip.

**To Reproduce**
1. Change the configuration to as mentioned
2. Install Ultisnip (using Mason)
3. Expand a snippet in a file using <Tab>
4. Jump Forward using <Tab>

**Expected behavior**
For Ultisnip's `UltiSnipsJumpForwardTrigger="<Tab>"` functionality to work flawlessly as in normally configured neovim

**Desktop**
 - Operating System: Void Linux
 - Terminal: ST
 - Version of Neovim: v0.9.5

**Additional context**
I just dislike using Luasnip and feel more comfy with Ultisnips

**Comment by siduck** [comment]
clone main repo of nvchad into home dir

```lua
 {  
   "NvChad/NvChad", 
    dir = "~/NvChad"
}
```

And put that into your plugins file. Debug locally i.e add your changes in cmp's file itself or comment cmp mappings and check. I have no idea about how snippets work... Does this happen with non nvchad config? Can you try tinyvim?

**Comment by siduck** [comment]
>  I am submitting this here since this issue is only in NvChad

please  provide a minimal nvim config where ultisnips works, then i'd admit this is a nvchad issue.
