### ISSUE TITLE
ftplugin overriding custom/init.lua

### ISSUE THREAD

**Issue by ProgrammingRainbow** [siduck76/NvChad#2725]
I am not sure if this is a bug or a missing feature or possibly skill issue on how to configure.

This is my custom/init.lua file.
```
local opt = vim.opt

-- Indenting
opt.expandtab = true
opt.shiftwidth = 4
opt.smartindent = true
opt.tabstop = 4
opt.softtabstop = 4
```
This seems to work pretty well except when i open any ruby file. then shiftwidth gets reset to 2. this is coming from the default ftplugin that is overriding my settings. Shouldn't my custom setting have the last say? I don't see any mention of using after folder. Or am i supposed to configure custom settings for ftplugin? I couldn't find any answer in the past issues. And i googled a bit and asked some ai and didn't get anywhere after chasing my tail in circles. So what do i need to do to make sure those settings are the final value?

to reproduce simply open a .rb file and then
```
:verbose set shifwidth?
```

Again i don't know if this is a bug or if this is simply me not knowing how to correctly configure. So any help would be appreciated.

**Comment by siduck** [comment]
there is no custom init.lua since v2.5

**Comment by siduck** [comment]
> Shouldn't my custom setting have the last say? 

ftplugin or editorconfig settings prevail more, so not a nvchad issue. Either create an autocmd  or ftplugin dir

**Comment by ProgrammingRainbow** [comment]
Thanks for letting me know about the undocumented breaking changes from 2.5

but i am now even more confused it seems someone closed the issue without some kind real answer. Is this a bug? There is no documentation so i don't know what ftplugin directory i would need to create or what would go into it. The speed at which issues are closed is interesting considering the other issues i read before opening this one also seemed to point to them not being answer either. As the couple sentences in the documentation seem to raise more questions then answer and all other documentation points to the way i am doing it, this leads me to posting this issue.

**Comment by siduck** [comment]
>  Is this a bug?

Its not a bug ,its either ftplugin/lsp server or editor config that adds changes to options too. For some languages tho

**Comment by siduck** [comment]
check verbose of each of those options. 
![image](https://github.com/NvChad/NvChad/assets/59060246/95aa5033-4dfe-4087-913c-af69f93d4891)

So not a nvchad issue :/

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/aa1ab10a-8b1f-4937-bb58-ea42dc60a21d)


So just make these changes in after/ftplugin/ruby.lua

![image](https://github.com/NvChad/NvChad/assets/59060246/a0d7bc7c-39d7-4070-aab9-3064a88963a4)

**Comment by siduck** [comment]
so nothing nvchad can do in this regard!

**Comment by siduck** [comment]
>  undocumented breaking changes from 2.5

It is documented, did  you not read that custom config stuff has been removed? Also you are free to use v2.0 branch. Its still working.
