### ISSUE TITLE
The bg for cursor line doesn't work for v2.5

### ISSUE THREAD

**Issue by RomaLzhih** [siduck76/NvChad#2726]
**Describe the bug**
Like the title suggests, after I migrate from v2.0 to v2.5, there is no background color for cursor line, even if I have set `vim.opt.cursorline=true` in `myinit.lua` and `CursorLine = {bg = "one_bg" }` in `highlights.lua`. 

**To Reproduce**
My personal config is available at [here](https://github.com/RomaLzhih/neovim_config) .

**Expected behavior**
There should have cursor line and can be set by colors in base30.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/45626759/703ed138-8a04-445a-ab10-89cee3fbdf29)

**Desktop (please complete the following information):**
 - Ubuntu
 - Wezterm
 - NVIM v0.10.0-dev-2577+g119390e7c

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/2723
