### ISSUE TITLE
Cannot unmap some default keymaps in v2.5

### ISSUE THREAD

**Issue by eilefsen** [siduck76/NvChad#2728]
**Describe the bug**
I am unable to unmap `<leader>ra` (rename dialog) from `lua/mappings.lua`.
I want to unmap it so i can make my own mapping for this feature.

**To Reproduce**
1. Clone the v2.5 starter repo.
2. Add the line `vim.keymap.del("n", "<leader>ra")` to `lua/mappings.lua`.
3. Relaunch neovim
4. `Error executing vim.schedule lua callback: vim/keymap.lua:0: E31: No such mapping `

**Expected behavior**
I expect being able to unmap the default mapping from `lua/mappings.lua`

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1
 - Terminal: Kitty
 - Neovim 0.9.5

**Additional context**
I believe the root of the issue is that the default mapping is set inside the default on_attach function, and that the on_attach is called after `lua/mappings.lua` is sourced.
I could likely override this function with my own, but doing so means copy-pasting the entire function to override a single default mapping.

**Comment by siduck** [comment]
thats a lsp mapping and lsp/gitsigns mappings are added in their on_attach functions.

To override them, create a custom on_attach function that does this :
calls default on_attach + your mapping code

**Comment by eilefsen** [comment]
> thats a lsp mapping and lsp/gitsigns mappings are added in their on_attach functions.
> 
> To override them, create a custom on_attach function that does this : calls default on_attach + your mapping code

I see, I tried this also and i could not get it to work. I no longer get the error, but the mapping is still there. Maybe I'm just missing something obvious.

I think I'll just stick with v2.0 for now, i never had this sort of problem until i migrated.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/02ea6559-9be7-41ab-9841-c433b105ce4f)


An example

**Comment by RichterMaximilian** [comment]
I also cannot get this to work. I tried this:
```lua
local on_attach = function(client, bufnr)
  require("nvchad.configs.lspconfig").on_attach(client, bufnr)
  vim.keymap.set("n", "<leader>sh", require("gitsigns").stage_hunk, { desc = "Stage hunk" })
end
```
But I still get the LSP keymap for `<leader>sh`.

I replaced the keymap with something that isn't assigned yet and that worked.
Any idea what's the issue?

**Comment by siduck** [comment]
@RichterMaximilian   weird, can you  just try on lspAttach event?

**Comment by RichterMaximilian** [comment]
That doesn't work either.

For reference, I did this
```lua
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(_)
    vim.keymap.set("n", "<leader>sh", require("gitsigns").stage_hunk, { desc = "Stage hunk" })
  end,
})
```

**Comment by siduck** [comment]
```lua

vim.keymap.set("n", "<leader>sh", require("gitsigns").stage_hunk, { desc = "Stage hunk" })

-- disable lsp mappings as they're buffer local!
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    vim.schedule(function()
      vim.keymap.del("n", "<leader>sh", { buffer = args.buf })
    end)
  end,
})
```

 or
 
 ```lua
 local on_attach = function(client, bufnr)
    require("nvchad.configs.lspconfig").on_attach(client, bufnr)
    vim.keymap.del("n", "<leader>sh", { buffer = args.buf })
end
```

And then you can define the gitsigns mappings normally, like in your mappings file

**Comment by luftaquila** [comment]
None of these did work for me to remap the `<leader>ca`.

*lua/configs/lspconfig.lua*

```lua
 -- local on_attach = require("nvchad.configs.lspconfig").on_attach
local on_attach = function(client, bufnr)
  require("nvchad.configs.lspconfig").on_attach(client, bufnr)
  vim.keymap.del("n", "<leader>ca")
  vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { desc = "Telescope LSP code action preview" })
end
```

```lua
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    vim.schedule(function()
    vim.keymap.del("n", "<leader>ca")
    vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { desc = "Telescope 
    LSP code action preview" })
    end)
  end,
})
```

Telescope keymaps list still shows the defaulit code action mappings

![image](https://github.com/NvChad/NvChad/assets/17094868/7c6c2766-87cc-4458-ad79-d1c344828a54)

<hr>

edit: creating LspAttach Autocmd worked for me. there was a simple mistake applying it.

Thank you!

**Comment by elsesiy** [comment]
> None of these did work for me to remap the `<leader>ca`.
> 
> _lua/configs/lspconfig.lua_
> 
> ```lua
>  -- local on_attach = require("nvchad.configs.lspconfig").on_attach
> local on_attach = function(client, bufnr)
>   require("nvchad.configs.lspconfig").on_attach(client, bufnr)
>   vim.keymap.del("n", "<leader>ca")
>   vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { desc = "Telescope LSP code action preview" })
> end
> ```
> 
> ```lua
> vim.api.nvim_create_autocmd("LspAttach", {
>   callback = function(args)
>     vim.schedule(function()
>     vim.keymap.del("n", "<leader>ca")
>     vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { desc = "Telescope 
>     LSP code action preview" })
>     end)
>   end,
> })
> ```
> 
> Telescope keymaps list still shows the defaulit code action mappings
> 
> ![image](https://private-user-images.githubusercontent.com/17094868/325341633-7c6c2766-87cc-4458-ad79-d1c344828a54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzAwODEsIm5iZiI6MTczMDA2OTc4MSwicGF0aCI6Ii8xNzA5NDg2OC8zMjUzNDE2MzMtN2M2YzI3NjYtODdjYy00NDU4LWFkNzktZDFjMzQ0ODI4YTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIyNTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzY2Y4NDNkZjFkMWNiNjIzODZjMzU4ZTkzNDZkZjQ1NDY1ZWQ1OTkxNWYzYTFjMDliNTQ2MGU3NmVlNjI2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sAYHM3IvczsqeHbM5f0Z2KzRDZSUllhfovxHAMKmeJA)
> 
> edit: creating LspAttach Autocmd worked for me. there was a simple mistake applying it.
> 
> Thank you!

@luftaquila Would you mind sharing how you solved it? I am facing the exact same issue with `<leader>ca`. Using `LspAttach` as an event trigger is problematic as it triggers for each LSP (and setting `once` does not prevent that [ref](https://github.com/neovim/neovim/issues/25526)). Since I have multiple LSPs, the second event causes it to fail:

```
Error executing vim.schedule lua callback: vim/keymap.lua:0: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        vim/keymap.lua: in function 'nomap'
        /Users/abc/.config/nvim/lua/mappings.lua:106: in function </Users/abc/.config/nvim/lua/mappings.lua:105>
```

Thanks!

**Comment by siduck** [comment]
@elsesiy the above examples mappings need the buffer option too

**Comment by elsesiy** [comment]
> @elsesiy the above examples mappings need the buffer option too

yes I did set them but it doesn't solve the problem
```
vim.api.nvim_create_autocmd("LspAttach", {
	callback = function(args)
		vim.schedule(function()
			nomap({ "n", "v" }, "<leader>ca", { buffer = args.buf })
		end)
	end,
})
```

**Comment by siduck** [comment]
@elsesiy  your code works perfect here man


https://github.com/user-attachments/assets/70875a2c-2c08-458c-98d0-264aeecfe0ff

**Comment by elsesiy** [comment]
> @elsesiy your code works perfect here man
> simplescreenrecorder-2024-10-28_06.39.12.mp4

Thanks for taking a look. Yes it does when there's only a single LSP attached to the buffer, but I have multiple.

**Comment by siduck** [comment]
> > @elsesiy your code works perfect here man
> > simplescreenrecorder-2024-10-28_06.39.12.mp4
> 
> Thanks for taking a look. Yes it does when there's only a single LSP attached to the buffer, but I have multiple.

```lua
local nvlsp = require "nvchad.configs.lspconfig"

local on_attach = function(client, bufnr)
  nvlsp.on_attach(client, bufnr)
  vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { buffer = bufnr })
end
```

use this onattach for all your lsps

**Comment by elsesiy** [comment]
> > > @elsesiy your code works perfect here man
> > > simplescreenrecorder-2024-10-28_06.39.12.mp4
> > 
> > 
> > Thanks for taking a look. Yes it does when there's only a single LSP attached to the buffer, but I have multiple.
> 
> ```lua
> local nvlsp = require "nvchad.configs.lspconfig"
> 
> local on_attach = function(client, bufnr)
>   nvlsp.on_attach(client, bufnr)
>   vim.keymap.set('n', '<leader>ca', require("actions-preview").code_actions, { buffer = bufnr })
> end
> ```
> 
> use this onattach for all your lsps

That was my initial approach but e.g. `lua_ls` is configured [here](https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/configs/lspconfig.lua#L59) so this override does not apply everywhere

**Comment by siduck** [comment]
@elsesiy the autocmd works fine here, i dont see why it'd not work :/

**Comment by elsesiy** [comment]
>  @elsesiy the autocmd works fine here, i dont see why it'd not work :/

Do you have a setup with multiple LSPs attached? I can confirm it works fine with only one but I have eg copilot always attach in addition to the language local server and that triggers deletion twice where one fails. Lmk if there's any additional debug info I can provide, thanks!

**Comment by siduck** [comment]
> > @elsesiy the autocmd works fine here, i dont see why it'd not work :/
> 
> Do you have a setup with multiple LSPs attached? I can confirm it works fine with only one but I have eg copilot always attach in addition to the language local server and that triggers deletion twice where one fails. Lmk if there's any additional debug info I can provide, thanks!

hmmm, instead of deleting, cant you just set the mapping? deletion is required only if u want to disable the mapping itself and not map it to something else!

**Comment by elsesiy** [comment]
> > > @elsesiy the autocmd works fine here, i dont see why it'd not work :/
> > 
> > 
> > Do you have a setup with multiple LSPs attached? I can confirm it works fine with only one but I have eg copilot always attach in addition to the language local server and that triggers deletion twice where one fails. Lmk if there's any additional debug info I can provide, thanks!
> 
> hmmm, instead of deleting, cant you just set the mapping? deletion is required only if u want to disable the mapping itself and not map it to something else!

Just got back to this, it works with the following autocommand (no deletion as you suggested):
```
vim.api.nvim_create_autocmd("LspAttach", {
	callback = function(args)
		vim.schedule(function()
			map({ "n", "v" }, "<leader>ca", function()
				require("tiny-code-action").code_action()
			end, { noremap = true, silent = true, buffer = args.buf })
		end)
	end,
})
```

Thanks!

**Comment by luftaquila** [comment]
Sorry for the late check. I don't remember well about the problem and seems like you've solved it.

However, it seems like my solution was this: https://github.com/luftaquila/dotfiles/blob/main/nvim/lua/configs/lspconfig.lua#L52
