### ISSUE TITLE
Unable to use my custom folder

### ISSUE THREAD

**Issue by tushargoyalofficial** [siduck76/NvChad#2731]
Before, I used to copy paste my `custom` folder containing all settings, plugins etc and nvim install all using mason and I can continue with my work. Today after fresh install of `NvChad`, it's not working like before. I pasted my `custom` folder inside `lua` folder and nothing happening. No settings, TS installs, all Mason packages. nothing. Please help me to use my `custom`folder with my own settings in NvChad like before

**Comment by siduck** [comment]
https://nvchad.com/news/v2.5_release

if you want to use old version i.e v2.0, just clone that branch.
