### ISSUE TITLE
Toggle last nvchad.term

### ISSUE THREAD

**Issue by t1gu1** [siduck76/NvChad#2738]
## Is your feature request related to a problem? Please describe.

It's really usefull to navigate between terminal and toggle the last one open.
It's currently not possible to open the last open terminal if we don't know his ID.

## Describe the solution you'd like

A method to open the last opened terminal
`:lua require("nvchad.term").toggleLast({ pos = "float" })`

OR/AND

A method that simply give the last terminal id opened
`:lua require("nvchad.term").lastOpenedId`

## Describe alternatives you've considered
I generate random `id` for the terms with `:lua require("nvchad.term").toggle({ pos = "float" }, id = math.random(1, 100000))`

And I currently use the `:Telescope terms`. (Not as fast as a toggle)

<img width="1277" alt="image" src="https://github.com/NvChad/NvChad/assets/12479055/8f9d7567-cdf7-4231-b9af-daf74add8a0d">

**Comment by t1gu1** [comment]
I made something a bit more usefull than my first solution.
But not as nice as the feature request.

<img width="730" alt="image" src="https://github.com/NvChad/NvChad/assets/12479055/7dcdc415-bee2-4ca8-b283-7c0176e0c3d3">

**Comment by t1gu1** [comment]
Oh, i finally create a custom solution.

```lua
local lastTermIdUsed = 1

map({ "n" }, "<leader>t", function()
	require("nvchad.term").toggle({ pos = "float", id = lastTermIdUsed })
end, { desc = "Terminal Toggle Floating" })

for id = 1, 9 do
	map({ "n" }, id .. "<leader>t", function()
		require("nvchad.term").toggle({ pos = "float", id = id })
		lastTermIdUsed = id
	end, { desc = "Terminal Toggle to " .. id })
end
```

Finally the feature request could simply be a method that could return the last used terminal id number. (Maybe usefull for other case external to keymaps)

**Comment by siduck** [comment]
> It's currently not possible to open the last open terminal if we don't know his ID.

nvchad.term needs an id at least... or else how would you toggle?  or just loop through `vim.g.nvchad_terms` table, it has info of all terminals with their opts & buf etc. and then get info of each buf upto your matching & toggle it by sending its opts as arg

**Comment by t1gu1** [comment]
@siduck  Would it be a nice and simple idea to keep track of the last active term id?

With something like `vim.g.nvchad_active_term_id`

I would contribute that simple change, but I don't find the NvChad's terminal module O.o

OR

Maybe simply paste my example in the Doc to help others that would want to do that. (At least I added something in the help channel in discord with the resolve tag and my solution)

**Comment by siduck** [comment]
@TirtharajPramanik you can do this yourself, just make an autocmd

```lua

vim.api.nvim_create_autocmd({ "TermOpen" }, {
  callback = function(args)
    local buf = args.buf
    -- now do your stuff here
  end
})
```
