### ISSUE TITLE
Nvim-tree not left-aligned

### ISSUE THREAD

**Issue by insufficientFunding** [siduck76/NvChad#2741]
**Describe the bug**
Nvimtree always seems to be padded from the left

**To Reproduce**
Genuinely not sure how to reproduce this

**Expected behavior**
In every screenshot i've seen, nvimtree has been left-aligned, so obviously i expect that

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/49592058/a86ba08b-d3c8-49c5-8ef3-8db883411b4c)

**Desktop (please complete the following information):**
 - Arch Linux 6.7.9
 - Kitty
 - 0.10 preview

**Comment by siduck** [comment]
not a nvchad issue, looks like padding from your terminal buddy. i have made an autocmd for dynamic padding i.e 0 padding when nvim is opened and normal padding without nvim

**Comment by insufficientFunding** [comment]
> not a nvchad issue, looks like padding from your terminal buddy. i have made an autocmd for dynamic padding i.e 0 padding when nvim is opened and normal padding without nvim

unless kitty is being a rabid little kitty, it shouldnt be, as i set the padding to 0 in kitty.conf

**Comment by siduck** [comment]
idk then! does it happen with vanilla nvchad? can u try other terminals?

**Comment by insufficientFunding** [comment]
> idk then! does it happen with vanilla nvchad? can u try other terminals?

turns out my statuscolumn was the culprit, it seems to have allocated space for itself without actually showing anything, i added it to the ignore table and now it works like a charm ;)
