### ISSUE TITLE
Unknown function: TbTbKillBuf when trying to close buffer tab

### ISSUE THREAD

**Issue by annaxiomm** [siduck76/NvChad#2742]
**Describe the bug**
When I try to close a buffer from the tabs at the top, it doesn't close and I get an error at the bottom `E117: Unknown function: TbTbKillBuf`.

**To Reproduce**
1. Open 2 or more buffers
2. Click on "x" to close one of them
4. See error at bottom

**Expected behavior**
When I click the close button the buffer should close with no issue

**Screenshots**
<img width="666" alt="Screenshot 2024-03-18 at 8 40 17 AM" src="https://github.com/NvChad/NvChad/assets/93843215/39b9c449-8dcd-4bf3-b062-0162d83a175e">
<img width="374" alt="Screenshot 2024-03-18 at 8 40 51 AM" src="https://github.com/NvChad/NvChad/assets/93843215/6544f975-6d1a-4a6e-b5e3-9f5bbd4eac27">

**Desktop (please complete the following information):**
 - MacOS Sonoma 14.3
 - Kitty 0.32.2 with zsh
 - Neovim 0.9.5 + NvChad 2.5

**Comment by siduck** [comment]
do lazy sync
