### ISSUE TITLE
Installation is broken for branch 2.5

### ISSUE THREAD

**Issue by mdasrafkhan** [siduck76/NvChad#2747]
Install is not working with this command 
`git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim`
because it's cloning the `2.5` branch which is missing init.lua and possibly other configuration.

**Comment by David-Aguilo** [comment]
The installation for version 2.5 is done with a starter, available at: https://github.com/NvChad/starter.

You have to use the command available on the website:
`git clone https://github.com/NvChad/starter ~/.config/nvim && nvim`
