### ISSUE TITLE
Which-key does not show mappings for <leader> in visual mode

### ISSUE THREAD

**Issue by Hororohoruru** [siduck76/NvChad#2748]
**Describe the bug**
When opening neovim, going into visual mode and pressing <leader>, the which-key table does not show. After pressing any other of the which-key keybinds (including <leader> in normal mode), the window shows normally and it then starts showing in visual mode as well.

**To Reproduce**
1. Open nvim
2. Press `Ctrl + V` to go into Visual mode
3. Tap <leader>, no which-key window appears
4. Exit Visual mode and press <leader>, which-key window shows normally
5. Go back into visual mode, now which-key shows normally as well

**Expected behavior**
I would expect for which-key to show on <leader> press regardless of the mode.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Gnome-terminal
 - Nvim 0.9.4 (appimage)

**Comment by siduck** [comment]
whichkey in nvchad is lazy loaded on these keys

![image](https://github.com/NvChad/NvChad/assets/59060246/66de7bb7-7450-4f06-9870-1cec4f5a39af)

**Comment by Hororohoruru** [comment]
Thanks for the answer! I am new to lazy (and .lua config for that matter). Would you explain to me what difference does it make from pressing <leader> in visual mode and in normal mode? In my example I am indeed using one of the keys which-key is set to load from...

**Comment by siduck** [comment]
i think some mappings dont work to trigger in visual mode for whichkey

for example press Ctrl + v and then press `"` + go back to normal mode and repeat the step. 

Nvchad uses the default config for whichkey, idk much about it!

**Comment by Hororohoruru** [comment]
I see, thanks for the information! I will maybe ask in the which-key repo.

**Comment by siduck** [comment]
@Hororohoruru just a wild guess, try `event="VeryLazy"` for whichkey and see if it fixes for u
