### ISSUE TITLE
Bug Report: Exiting Terminal on ESC in LazyGit within NvChad

### ISSUE THREAD

**Issue by SouchonTheo** [siduck76/NvChad#2749]
# Bug Report: Exiting Terminal on ESC in LazyGit within NvChad

## Overview
Hello everyone 👋,

I've encountered an issue with the `LazyGit` plugin in NvChad where pressing `Esc` to navigate back within a pane unexpectedly exits the terminal session altogether. Despite searching online, I haven't found any solutions or mentions of similar problems.

## Steps to Reproduce
1. Install the `LazyGit` plugin using the Lua configuration provided below.
2. Open Neovim and launch `LazyGit` with the `:LazyGit` command.
3. Enter any pane within the `LazyGit` interface.
4. Press `Esc` in an attempt to go back or close the current pane.

## Expected Behavior
Pressing `Esc` should navigate back or close the current pane within the `LazyGit` interface without affecting the terminal session.

## Actual Behavior
Pressing `Esc` exits the entire terminal session instead of simply navigating back within the `LazyGit` interface.

## Configuration Details
Here is my Lua configuration for installing `LazyGit`:
```lua
return {
    "kdheepak/lazygit.nvim",
    cmd = {
        "LazyGit",
        "LazyGitConfig",
        "LazyGitCurrentFile",
        "LazyGitFilter",
        "LazyGitFilterCurrentFile",
    },
    -- Optional for floating window border decoration
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
}

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/a68512d7-6bd0-429a-84a9-7a36dae01126

Unable to reproduce , cant you just use lazygit with our term module?

**Comment by SouchonTheo** [comment]
@siduck I download NvChad from scratch and it doesn't seems to integrate lazyvim 

To give more info I started using NvChad this week and I used the repo starter as suggested

**Comment by siduck** [comment]
>   it doesn't seems to integrate lazyvim

why will it integrate with another distro?

**Comment by SouchonTheo** [comment]
I'm sorry I'm not sure to understand

If I dl NvChad from scratch and Start it I don't have lazygit preinstalled. The other fact is when I start nvim without a distro or with some other I can press escape to go back in lazygit not in NvChad

**Comment by siduck** [comment]
esc key in terminal mode is mapped
![image](https://github.com/NvChad/NvChad/assets/59060246/34723769-77a5-4131-b2c7-b1f903a252c0)

use vim.keymap.del to unmap it
