### ISSUE TITLE
v2.5 failed to pass cmd to LSP

### ISSUE THREAD

**Issue by RomaLzhih** [siduck76/NvChad#2751]
**Describe the bug**
The customized command cannot be passed to LSP according to the [tutorial](https://nvchad.com/docs/config/lsp) given.
For example, I am trying to pass the command `"--offset-encoding=utf-16"` to `clangd`, as shown in Screenshots below, but it fails.

**To Reproduce**
My config is available [here](https://github.com/RomaLzhih/neovim_config).

**Expected behavior**
The cmd can be passed to LSP as in v2.0

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/45626759/3128e55a-45a5-4691-9bbf-64a8c91d6054)
![image](https://github.com/NvChad/NvChad/assets/45626759/c20a913a-013c-4b29-ad0c-6108a4c6939b)
![image](https://github.com/NvChad/NvChad/assets/45626759/31734aa5-99b6-432e-ae0c-83f469d54495)

**Desktop (please complete the following information):**
 - Operating System: CentOS
 - Terminal: Wezterm
 - Version of Neovim: 0.9.5

**Additional context**
Any suggestion would be helpful. Thanks.

**Comment by siduck** [comment]
nvchad has nothing to do with clangd lsp -_-

**Comment by siduck** [comment]
nvchad only configures lua-ls by default, test it without nvchad and if it works then lemme know

**Comment by RomaLzhih** [comment]
Yes, I know the NvChad has nothing to do with the clangd LSP, but there might be issues when configuring the LSP using the method provided in its tutorial. 

Yes, I tried the configuration [here](https://github.com/RomaLzhih/NvChad_x), which is based on the NvChad 2.0, and everything works. 
![image](https://github.com/NvChad/NvChad/assets/45626759/62a2260a-a648-4cc6-81df-4f0d049b27d2)

**Comment by RomaLzhih** [comment]
The problem is that the another plugin `nvim-ufo` can modify the lsp setting to some extent when using the fold by LSP, which may over-write the one in lsp-config. One can move it into the together with [lspconfig](https://github.com/RomaLzhih/neovim_config/blob/main/lua/configs/lspconfig.lua#L9).

**Comment by siduck** [comment]
v2.0 and v2.5 have almost no difference when configuring with the lsp tho :l

**Comment by 89iuv** [comment]
This is indeed strange, but i can confirm that i have it working with nvchad so the problem may lie with your lsp config.

<img width="707" alt="image" src="https://github.com/NvChad/NvChad/assets/3298487/4a3f65b9-8e95-4925-8333-202331eb849a">

<img width="858" alt="image" src="https://github.com/NvChad/NvChad/assets/3298487/7a037545-53f5-4eea-b7a9-7ef1b22b3bc8">

**Comment by RomaLzhih** [comment]
Yes, other plugin modifies/reloads the configurations as well later, see [here](https://github.com/NvChad/NvChad/issues/2751#issuecomment-2010762309) and the plugin [here](https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#minimal-configuration).

**Comment by siduck** [comment]
> Yes, other plugin modifies/reloads the configurations as well later, see [here](https://github.com/NvChad/NvChad/issues/2751#issuecomment-2010762309) and the plugin [here](https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#minimal-configuration).

we your clang.setup after ufo then?

**Comment by siduck** [comment]
> Yes, other plugin modifies/reloads the configurations as well later, see [here](https://github.com/NvChad/NvChad/issues/2751#issuecomment-2010762309) and the plugin [here](https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#minimal-configuration).

load your clangd.setup after ufo then
