### ISSUE TITLE
Unable to install, install stuck

### ISSUE THREAD

**Issue by Dudoleitor** [siduck76/NvChad#2756]
I tried to install nvchad following the official instructions ([https://nvchad.com/docs/quickstart/install/](nvchad.com/docs/quickstart/install/)) but after opening nvim for the first time the installation is simply stuck.

I'm using Ubuntu 23.04 (also tried with an old wsl debian installation, same problem), I downloaded nvim version 0.9.5 and I'm executing the .appimage file.
Make and gcc are installed on the system (with apt), I deleted old folders before installing.
![Screenshot from 2024-03-22 19-29-58](https://github.com/NvChad/NvChad/assets/17532692/7f1870c5-98b4-462c-a7a6-bbf9d5282392)

**Comment by siduck** [comment]
not a nvchad issue. 

I can only advice rm -rf ~/.local/share/nvim 

probably more related to ubuntu, i'm sure it wont be the same on other distros

**Comment by Dudoleitor** [comment]
I already followed your advice, by deleting the nvim folder in .local/share, .cache, .config.
Also, as said, I was also unable to install nvchad on debian in wsl. In addition to this, it is impossible to install version 2.0 because some required files were deleted from github and the install procedure fails.

To me, this is a major nvchad issue. If you think it is not, can you at least point me to a potential direction to make it work?

**Comment by siduck** [comment]
I tried v2.0 for you, all you have to do is clone its branch :/ 


https://github.com/NvChad/NvChad/assets/59060246/ad7ca67d-1fd8-41fd-8dad-8cf15da3e253

> Also, as said, I was also unable to install nvchad on debian in wsl. 

Do know that nvchad supports 0.9.4 + , debian has an older version of neovim. Please seek help in our discord server. Nvchad's codebase is relatively simple, i cant think of anything that'd freeze after lazy. Can you try bob neovim manager?

**Comment by Dudoleitor** [comment]
Thanks a lot!
I think I cloned v2.0 in the wrong way, with v2.0 everything works.

Do you still need me to try bob neovim manager? If so, will you explain me what I have to do?

**Comment by siduck** [comment]
@Dudoleitor  v2.0 is depreceated tho, no docs for it too. its suggested to use v2.5.  No need of  bob now if your nvim appimage  works
