### ISSUE TITLE
Lazy.nvim floating window backdrop option added

### ISSUE THREAD

**Issue by zerochae** [siduck76/NvChad#2761]
**Is your feature request related to a problem? Please describe.**

- https://github.com/folke/lazy.nvim/commit/a6b74f30d5aab79a40d932f449c0aa5d4a0c6934

lazy.nvim added a backdrop option, so I want set same option in nvchad

**Describe the solution you'd like**

chadrc file has option backdrop

**Screenshot**

for example. i set backdrop option in `/lua/plugins/configs/lazy_nvim.lua`

its default value is 60 and 100 is fully transparent.

| backdrop = 60 | backdrop = 100 |
 | --- | --- |
|![스크린샷 2024-03-27 15 03 29](https://github.com/NvChad/NvChad/assets/84373490/36c2c877-1eb5-4abd-9db5-4032ff1e3053)| ![스크린샷 2024-03-27 15 03 47](https://github.com/NvChad/NvChad/assets/84373490/c5d973af-2667-4a83-ae59-b1f0212e9918) |

**Comment by GrayKwon** [comment]
i realized that add this code in chadrc, then problem has solved

```lua
M.lazy_nvim = {
  ui = {
    backdrop = 100
  },
}
```

plz close this issue, thx

**Comment by zerochae** [comment]
i realized that add this code in chadrc, then problem has solved

```lua
M.lazy_nvim = {
  ui = {
    backdrop = 100
  },
}
```

close this issue, thx

**Comment by siduck** [comment]
@zerochae that was for old nvchad ! check nvchad 2.5 :grimacing: . So you can add it directly here https://github.com/NvChad/starter/blob/main/lua/configs/lazy.lua

and do know that in v2.5 there's no custom stuff, you can delete the .git of ~/.config/nvim after installing v2.5

check our news page

**Comment by zerochae** [comment]
@siduck oops, I'll update it this weekend

thx 😀
