### ISSUE TITLE
Auto indentation not working while pressing up arrow.

### ISSUE THREAD

**Issue by reactVishnu** [siduck76/NvChad#2763]
Hi Team,

I observed while working in a python code, it doesn't intending while pressing up arrow. Attaching video for better understanding.

https://github.com/NvChad/NvChad/assets/134265914/2e6d57c4-0577-4882-b011-95d66757a044

Thanks,

**Comment by siduck** [comment]
does it happen without nvchad?  we only set indent options and dont even set mappings for it, so i dont think this is nvchad issue
