### ISSUE TITLE
Hide tabufline if no buffer?

### ISSUE THREAD

**Issue by ckt114** [siduck76/NvChad#2764]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I’ve configured nvim to open alpha when the last buffer is closed but the tabufline still show which is a diff color than alpha which is quite tacky. Is there a way to hide tabufline and only show it if there’s a buffer?

**Describe alternatives you've considered**
I’ve read the code in ui repo but couldn’t figure out a way to do it. 

**Additional context**

**Screenshot**
Maybe a screenshot of the feature

**Comment by siduck** [comment]
make an autocmd which checks number of buffers ( if its 0 + unamed ) , you can check the length of `vim.t.bufs` and then use showtabline option to toggle tabline
