### ISSUE TITLE
Feat: Explain how to disable friendly-snippets

### ISSUE THREAD

**Issue by kohloth** [siduck76/NvChad#2766]
**Is your feature request related to a problem? Please describe.**
I wish to use about 10 custom-define snippets and nothing else in my editor. When there are many hundreds of snippets that I do not want, its inconvenient to find my custom snippets.

**Describe the solution you'd like**
I can see several posts where people are asking how to disable friendly-snippets, some with short replies, some links to PRs, some links to 404s.

Example: A pull request, which does not really tell how to do this
https://github.com/LunarVim/LunarVim/pull/2546

There's also this reddit post (https://www.reddit.com/r/neovim/comments/114engw/nvchad_disabling_the_friendlysnippets_plugin/), but as I am a newb, I cannot understand what the answer means at all.

Theres also this issue:
https://github.com/NvChad/NvChad/issues/2176
But if I follow along and put

```
  {
     --"hrsh7th/nvim-cmp",
     "rafamadriz/friendly-snippets",
     enabled = false 
  }
```
into custom/plugins.lua (a new file) it has no effect. Theres also a reference to a `sources` var, but as I can't see this mentioned anywhere else in the docs I have no idea where this should be placed or what it really does.

Could someone tell me in simple terms how to disable all these unwanted snippets?

**Describe alternatives you've considered**
Not using snippets

**Additional context**
None

**Screenshot**
None

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/7801ae83-c48c-49df-be1a-8ae4cff6058b


i tried your code and it did disable the snippets

as for the other snippets, probably those are from your lsp and we cant do anything about it i think

**Comment by kohloth** [comment]
Ah ok I see now.

The post at https://github.com/NvChad/NvChad/issues/2176 says to put the code in custom/plugins.lua. I can see in your vid that you're putting it not there but in ~/.config/nvim/lua/plugins/init.lua.

Might be a good idea to add this information to https://nvchad.com/docs/config/snippets for the other newcomers

**Comment by siduck** [comment]
In nvchad 2.5 the dir structure has changed, now your nvchad config is just like a general neovim config, you dont have to learn custom config syntax. 

read https://nvchad.com/news/v2.5_release
