### ISSUE TITLE
Feat: Explain how to configure autocompletion popups

### ISSUE THREAD

**Issue by kohloth** [siduck76/NvChad#2767]
**Is your feature request related to a problem? Please describe.**

When using luasnip and nvchad, snip suggestions popup automatically. For example, I simply type the letter r in an empty document, and I get two popups - one showing all snippets that contain the letter r, and one that shows information about the first snippet in the list. Having this information is quite nice, but I find the fact that a large part of the editor is automatically obscured just because I've typed a character is very bad.

I've asked the folks over at luasnip how to turn this off, and they have explained that it is does not fall under the domain of luasnip, but under the domain of the cmp module. However, I cannot find any configuration for this inside ~/.config/nvim/**. I believe that nvchad is configuring this behaviour behind the scenes - is that correct? Looking at the nvchad documentation, I cannot see any information about how I can configure this or turn it off.

**Describe the solution you'd like**
Please could it be explained how I can turn off snippet suggestion popups? I want the ability to expand snippets (i.e. type "myfunc", press CTRL+K, and have the snippet expanded into the document text), but I don't want popups coming up at all. (This is why I'm moving back to vim from VS code!)

**Describe alternatives you've considered**
Configure neovim manually

**Additional context**
None

**Screenshot**
None

**Comment by siduck** [comment]
Do  read all of nvchad.com then you'll learn how to override nvchad's cmp config or else if i provide the code here you wont learn anything. 

So all you have to do is import our cmp's default config and modify its table and then use it ( either opts / config function )

**Comment by kohloth** [comment]
@siduck 

Hmm. Ok. These are the pages of nvchad.com that I have read.

https://nvchad.com/docs/quickstart/install
https://nvchad.com/docs/quickstart/post-install
https://nvchad.com/docs/quickstart/learn-lua
https://nvchad.com/docs/config/walkthrough
https://nvchad.com/docs/config/snippets
https://nvchad.com/docs/config/plugins
https://nvchad.com/docs/config/syntax
https://nvchad.com/docs/config/lsp
https://nvchad.com/docs/config/mappings
https://nvchad.com/docs/config/nvchad_ui
https://nvchad.com/docs/config/theming
https://nvchad.com/docs/features
https://nvchad.com/docs/recipes
https://nvchad.com/docs/api
https://nvchad.com/docs/faq

I think the page that is closest to what I am looking for is https://nvchad.com/docs/config/plugins. However, the information given on this page can be summarized as this (and only this):

* States that almost 95% of plugins are lazy loaded.
* That plugins can be loaded lazily or unlazily by passing lazy = false.
* Goes on to shows a variable named `plugins` which seems to follow a form in which each entry has a plugin name of sorts, and in some cases, some options.

The problems I have as a beginner (and I think many people using nvchad are likely to be) are:

* Where is the precise definition of this config API that is being shown here with an example but not explained any further?
* What is the magic string that is used to supply config for `vim-cmp`? (For tree sitter it is "nvim-treesitter/nvim-treesitter"). Where does this come from?
* How does the config for vim-cmp, described at https://github.com/hrsh7th/nvim-cmp intersect with the vim-chad `plugins` corresponding config object? Is it an exact match? Is it a facade pattern with its own API, or is it referrentially transparent? Do I pass parts of the nvim-cmp config listed on the nvim-cmp page to the `plugins.*.config` key, or the `plugins.*.opts` key?

I hope you can appreciate that while the questions above are unanswered by the documentation, the only way to get it working would be through trial and error, and that in consideration of all the permutations of the above uncertainties, it would be comparable to the "monkey writing shakespeare by chance" analogy!

**Comment by siduck** [comment]
@kohloth  check the last telescope example in it, and look how we import default config table and modify it

so check the cmp config mentioned here https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/plugins/init.lua#L117

**Comment by kohloth** [comment]
@siduck Really don't understand this at all. Thanks anyways.

**Comment by kohloth** [comment]
@siduck This section...

```
{
    "hrsh7th/nvim-cmp",
    event = "InsertEnter",
    dependencies = {
      {
        -- snippet plugin
        "L3MON4D3/LuaSnip",
        dependencies = "rafamadriz/friendly-snippets",
        opts = { history = true, updateevents = "TextChanged,TextChangedI" },
        config = function(_, opts)
          require("luasnip").config.set_config(opts)
          require "nvchad.configs.luasnip"
        end,
      },

      -- autopairing of (){}[] etc
      {
        "windwp/nvim-autopairs",
        opts = {
          fast_wrap = {},
          disable_filetype = { "TelescopePrompt", "vim" },
        },
        config = function(_, opts)
          require("nvim-autopairs").setup(opts)

          -- setup cmp for autopairs
          local cmp_autopairs = require "nvim-autopairs.completion.cmp"
          require("cmp").event:on("confirm_done", cmp_autopairs.on_confirm_done())
        end,
      },

      -- cmp sources plugins
      {
        "saadparwaiz1/cmp_luasnip",
        "hrsh7th/cmp-nvim-lua",
        "hrsh7th/cmp-nvim-lsp",
        "hrsh7th/cmp-buffer",
        "hrsh7th/cmp-path",
      },
    },
    opts = function()
      return require "nvchad.configs.cmp"
    end,
    config = function(_, opts)
      require("cmp").setup(opts)
    end,
  },
```

I think I need to copy and paste it into ~/.config/nvim/lua/plugins/init.lua. And make some changes.

Maybe if I delete these bits...

```
      {
        -- snippet plugin
        "L3MON4D3/LuaSnip",
        dependencies = "rafamadriz/friendly-snippets",
        opts = { history = true, updateevents = "TextChanged,TextChangedI" },
        config = function(_, opts)
          require("luasnip").config.set_config(opts)
          require "nvchad.configs.luasnip"
        end,
      },
```

```
        "saadparwaiz1/cmp_luasnip",
```

**Comment by kohloth** [comment]
Hmm nope still getting cmp popups whenever I type a character

**Comment by siduck** [comment]
@kohloth there's an option for cmp to disable popup on every char i think, pls google it and pls ask on our discord server, others might help u

**Comment by kohloth** [comment]
Thanks @siduck but the problem isn't so much trying to understand how to configure cmp, its how to configure cmp when its being partially controlled by nvchad.

1. Should it go inside this file ~/.config/nvim/lua/plugins/init.lua?

2. Should it be inside an object entry like this?

```
return {
  {
    "hrsh7th/nvim-cmp",
  }
}
```

3. Should the option then go inside opts, like this?

```
return {
  {
    "hrsh7th/nvim-cmp",
    opts = function()
      -- Options...
    end,
  }
}
```

Or should it go inside config, like this?

```
return {
  {
    "hrsh7th/nvim-cmp",
    config = function(_, opts)
      -- Options...
    end,
  }
}
```

**Comment by siduck** [comment]
@kohloth both 2 and 3 are correct,  i'd go with 3rd as you dont have to write full name of the opts module i.e `require ("nvchad.configs.cmp")`  you just modify the  opts argument directly!

but then dont forget to add `require('cmp').setup(opts)`
