### ISSUE TITLE
Declaring custom separators doesn't work

### ISSUE THREAD

**Issue by Ethanol48** [siduck76/NvChad#2773]
Declaring the separators in `M.ui.separators` doesn't affect the ui

**Expected behavior**
I expect the separators to work

**Screenshots**
![screenshot-nvchad](https://github.com/NvChad/NvChad/assets/96821054/63054101-7287-4281-96aa-b349a4a82093)

**Desktop (please complete the following information):**
 - Nixos
 - Alacritty
 - 0.9.4

**Additional context**
Changing the types of the separator; [block, round, ...] works as expected, is just the custom separator, it seems that the `ui` module doesn't pick up this field

**Comment by Ethanol48** [comment]
trying other styles of default separators works fine, here I'm trying block:

![screenshot-nvchad-block](https://github.com/NvChad/NvChad/assets/96821054/39d21299-9a5e-4f0c-bb5d-21f95039fdd3)

**Comment by siduck** [comment]
its separator_style, not separators

**Comment by Ethanol48** [comment]
It isn't working

![Nvchad](https://github.com/NvChad/NvChad/assets/96821054/27862ab3-fb69-473d-a282-ddafa8045901)

**Comment by siduck** [comment]
separator_style
