### ISSUE TITLE
Useless cheatsheet entries

### ISSUE THREAD

**Issue by ngvt1n** [siduck76/NvChad#2774]
**Describe the bug**
Hi I just migrated to v2.5 and noticed that cheatsheet now scans for keymaps from every plugin. My issue with this behavior is that cheatsheet now returns keymaps that are pretty useless and cause clutter in my opinion. 
![image](https://github.com/NvChad/NvChad/assets/68778329/f5990534-9034-4ec9-b555-67014abd3071)
![image](https://github.com/NvChad/NvChad/assets/68778329/d601ca83-8ae4-4ade-9f41-878e4fd18b86)

The long auto-detected entries from LuaSnip (which comes with LuaSnip by default) now also forces Cheatsheet into simple layout too. Unless I zoom out really far cheatsheet remains in the one-column layout. 
![image](https://github.com/NvChad/NvChad/assets/68778329/1ec91974-e912-483e-b608-8863971e9896)

**To Reproduce**
1. Activates cheatsheet by `Cheatsheet` or `<leader>ch` on v2.5

**Expected behavior**
More concise Cheatsheet entries. 
If possible, maybe a dictionary that lets Cheatsheet know where to scan for keymaps and where to not? 

**Desktop (please complete the following information):**
 - Operating System - Windows 10
 - Terminal - Windows Terminal 
 - NVIM v0.95

**Comment by siduck** [comment]
These are not useless, the cheatsheet scans from mappings, you'll see them in   telescope keymaps too

**Comment by siduck** [comment]
the long ones will be formatted well  soon, i'll  try to work on them next week.

Closing this as its related to https://github.com/NvChad/ui/issues/252 which is open
