### ISSUE TITLE
New to nvchad. Turns green after install on mac

### ISSUE THREAD

**Issue by ColtonIdle** [siduck76/NvChad#2776]
**Describe the bug**
green after install
![CleanShot 2024-04-07 at 03 27 38@2x](https://github.com/NvChad/NvChad/assets/31751141/9152a326-d960-4fd5-a716-d629c4b16b48)

**To Reproduce**
on mac 14.4.1 (latest) with default terminal and default zsh. I installed neovim and then tried getting nvchad working. This is the first screen I hit.

Do I have to use a different terminal (like iterm?) seems like thats what some folks are doing in previous issues

**Comment by siduck** [comment]
enable true colors in that terminal or use a terminal that supports it :/

**Comment by ColtonIdle** [comment]
Gotcha. New to this. Didn't know that was a requirement. Let me see if I can enable it in regular terminal.
