### ISSUE TITLE
problem with TSInstall vimdoc

### ISSUE THREAD

**Issue by dudu1001** [siduck76/NvChad#2778]
**Describe the bug**
i was using nvim but for some reason i received some problem after trying to use : help, after some tinkering i found that the problem is that i did not had the parser vimdoc installed, the thing is vimdoc is supposed to be installed by default (i think). after using TSInstall, i discovered that for some reason tree_sitter was not able to compile the vimdoc parser, after some searching i found that the problem is that i did not had a library called libc6-dev, after installing it the problem was solved. the problem is that there is no libc6-dev listed on the pre-requisites in the nvchad page. maybe for some reason i was supposed to had this library installed on my computer but for some reason i did not.

**To Reproduce**
1. make sure you do not have libc6-dev installed and the parser vimdoc
2. execute on nvim the command TSInstall vimdoc

**Screenshots**
![Screenshot from 2024-04-08 21-38-22](https://github.com/NvChad/NvChad/assets/106493868/2f076e92-0230-43f5-841b-24abced15fc1)

**Desktop (please complete the following information):**
 - linux mint latest stable version
 - standard linux mint terminal
 - 0.10.0\~ubuntu1+git202404051504-2b9d8dc87-971e32c87-84f4108c4~ubuntu22.04.1
 - gcc version 4:11.2.0-1ubuntu1
- make version 4.3-4.1build1

**Comment by siduck** [comment]
not a nvchad issue, google that error

**Comment by siduck** [comment]
https://stackoverflow.com/questions/23973971/no-stdint-h-file-on-debian

**Comment by siduck** [comment]
https://github.com/castwide/solargraph/issues/195
