### ISSUE TITLE
Multiple Errors During Installation

### ISSUE THREAD

**Issue by markfaine** [siduck76/NvChad#2779]
**Describe the bug**
Multiple errors appear right as nvim is loading immediately after installing.
![image](https://github.com/NvChad/NvChad/assets/949949/d9f29693-1b33-4dd5-adaf-75eb84af6050)

**To Reproduce**
1. Follow instructions for Linux/MacOS installation here:  https://nvchad.com/docs/quickstart/install/
2. The error will show itself after a couple of seconds
3. Press enter and it will continue on as normal

**Expected behavior**
Nvim loading normally and completing installation of nvchad

**Screenshots**
Added

**Desktop (please complete the following information):**
 - Windows 10
 - Microsoft Windows Terminal
 - Latest (installed from github)

**Additional context**
It appears at first to be fine after this installation but I do continue to get errors related to multiple different issues:

![image](https://github.com/NvChad/NvChad/assets/949949/c23ce18c-7b12-4994-a8a0-889700b82d88)
![image](https://github.com/NvChad/NvChad/assets/949949/c9c27551-17fa-45bf-9884-3d347f627f7a)

I'm not sure if maybe something didn't get installed correctly?

**Comment by siduck** [comment]
rm -rf all  old nvim dirs and use  nvim v0.9.5 at least

**Comment by markfaine** [comment]
> rm -rf all old nvim dirs and use nvim v0.9.5 at least

This seems to have fixed it.  Ubuntu 23.10 only goes to 0.8.1 but I was able to install it via the nvim website instructions.   I got some errors after that but after some searching it seems that upgrading node may have resolved those.

Thanks!
