### ISSUE TITLE
Mason configs

### ISSUE THREAD

**Issue by Laurent45** [siduck76/NvChad#2785]
The latest version of mason plugins is v1.10.0.
This version has different names for some config. We can see it at  https://github.com/williamboman/mason.nvim.
We must update the mason config file, what do you think ?

**Comment by siduck** [comment]
we use the master so i dont think it should matter

**Comment by Esquanor** [comment]
What do you mean by "we use master". I am a little bit confused because when I installed nvchad and I would change default settings of Mason I did change other name of settings put in your mason config file.

**Comment by Laurent45** [comment]
@siduck What do you mean by "we use the master". I am a little bit confused because when I installed nvchad and I would change default settings of mason, I did change other name of settings which are put in your mason config file.

**Comment by siduck** [comment]
i mean we dont set any versions for any plugin in nvchad so the code is from the main branch. Idk what you mean by name of settings , elaborate

**Comment by siduck** [comment]
and seek help in our discord server for quick help
