### ISSUE TITLE
Disable native mappings 

### ISSUE THREAD

**Issue by batyrmuhadov** [siduck76/NvChad#2786]
Hi there! When I'm disabling native mappings
![image](https://github.com/NvChad/NvChad/assets/83823943/bf8a2ac7-6fcf-46c2-9dbb-2ed4454f3948)
keep getting this error 
![image](https://github.com/NvChad/NvChad/assets/83823943/b26d5f6b-9685-44bb-93fe-b0f5523c76ed)

**Comment by siduck** [comment]
`<C-n>` :expressionless:
