### ISSUE TITLE
Symbols under buffer like in astronvim/lunarvim

### ISSUE THREAD

**Issue by Yakui420** [siduck76/NvChad#2787]
![1713090029711626](https://github.com/NvChad/NvChad/assets/97893737/e78a56dd-04aa-42af-8441-3cf03171d7db)
Is it possible to add these icons to nvchad too? Is there an option for that?

**Comment by UnderGrounder96** [comment]
These are called breadcrumbs, I think.

You can try and check how other projects implemented it.
I bet they use some plugin, in the past I used LSPSaga but ended up removing.

Links:
https://nvimdev.github.io/lspsaga/breadcrumbs/
https://github.com/UnderGrounder96/nvim-configs/commit/c48b8a4fa68bb5018e4fa3d53bea3f3759e5137d

**Comment by siduck** [comment]
```lua
  {
    "SmiteshP/nvim-navic",
    event = "LspAttach",
    config = function()
      dofile(vim.g.base46_cache .. "navic")

      require("nvim-navic").setup {
        highlight = true,
        lsp = { auto_attach = true },
      }

      vim.o.winbar = "%{%v:lua.require'nvim-navic'.get_location()%}"
    end,
  },
  ```
  
  make sure you include "navic" in the integrations table of base46
