### ISSUE TITLE
luasnip checkhealt require jsregexp 

### ISSUE THREAD

**Issue by haidaroh9** [siduck76/NvChad#2789]
luasnip: require("luasnip.health").check()
   15
   16 luasnip
   17 - WARNING             For Variable/Placeholder-      transformations, luasnip requires
   18   the jsregexp library. See :help |luasnip-            lsp-snippets-transformations| for advice

why this warning appears ?
i have enable installing it from myinitplugin with "L3MON4D3/LuaSnip",
            version = "v2.*",
            build = "make install_jsregexp",

but the warning still exist.

**Comment by siduck** [comment]
not a nvchad issue, and do know that build* opt will run only if that plugin is updated or installed so uninstall luasnip and open nvim

Also check through https://github.com/search?q=repo%3AL3MON4D3%2FLuaSnip+jsregexp+library&type=issues

**Comment by haidaroh9** [comment]
thanks so munch
