### ISSUE TITLE
`<C-i>` raises an error when tabufline is disabled

### ISSUE THREAD

**Issue by gmartsenkov** [siduck76/NvChad#2793]
**Describe the bug**
Pressing `<C-i>` fails when tabufline is disabled

**To Reproduce**
```lu
-- This file  needs to have same structure as nvconfig.lua
-- https://github.com/NvChad/NvChad/blob/v2.5/lua/nvconfig.lua

---@type ChadrcConfig
local M = {}

M.ui = {
  theme = "onedark",
  tabufline = {
    enabled = false
  }
}

return M
```
- press `<C-i>`

**Expected behavior**
- Goes to newer tab

**Screenshots**
<img width="1313" alt="Screenshot 2024-04-17 at 09 43 08" src="https://github.com/NvChad/NvChad/assets/7080637/c385c9dd-9476-47bd-b968-fa020fa988da">

**Desktop (please complete the following information):**
 - MacOs
 - Kitty
 - NVIM v0.9.5

**Additional context**

**Comment by siduck** [comment]
idk why C-i is mapped to  <tab> in vim or terminal , delete tabufline mappings 

```lua
vim.keymap.del("n", "<Tab>")
vim.keymap.del("n", "<S-Tab>")
```
