### ISSUE TITLE
Not able to move between Buffers and Terminal and Tree using Keyboard

### ISSUE THREAD

**Issue by koptan** [siduck76/NvChad#2794]
**Describe the bug**
Not able to switch between Folder Tree and Terminal using keyboard.

**To Reproduce**
For example, if I am writing something in terminal and want to go back to the current open file, I can't use C-h, C-l.

**Expected behavior**
Should be able to move between open buffers and Tree and Terminal using C-h,C-l

**Desktop (please complete the following information):**
 - Operating System: Mac
 - Terminal: ITerm2
 - Version of Neovim: 0.9.5

**Comment by siduck** [comment]
thats normal, not a nvchad issue... when you're in terminal then you're in terminal mode so get out of it, press C-x

**Comment by koptan** [comment]
> thats normal, not a nvchad issue... when you're in terminal then you're in terminal mode so get out of it, press C-x

Thanks, but then how I can go back to the active terminals after pressing C-x?
Is there any way to make the movement easier, just by using C-l and C-h?

**Comment by siduck** [comment]
@koptan  <leader> pt  to get list of all terminals which are hidden

as for active ones i'd just do this 

<C-x>  and then C-h/jkl/ which is our default mapping and you dont need to press C-x to switch to terminal window, thats needed only when u are inside the terminal + in terminal mode

**Comment by koptan** [comment]
@siduck  My issue is the default mapping is not working for C-h/jkl, my mapping file : 

```
require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")


-- Copilot
map({"i","n"}, "<C-l>", function()
  vim.fn.feedkeys(vim.fn['copilot#Accept'](), '')
end, { desc = "Copilot Accept" })

-- neotest
map("n","<leader>tt",":lua require('neotest').run.run()<CR>", { desc = "Test Nearest" })
map("n","<leader>tf",":lua require('neotest').run.run(vim.fn.expand('%'))<CR>", { desc = "Test File" })
```

**Comment by siduck** [comment]
can you make a video and press those keys? it works here
