### ISSUE TITLE
Can't use integrated terminal after clicking anywhere in the screen

### ISSUE THREAD

**Issue by brajnacs** [siduck76/NvChad#2795]
**Describe the bug**
I have ubuntu with zsh (running in default terminal). When i open the integrated terminal in neovim it opens and works just fine. But as soon as I click anywhere on the screen with mouse, my terminal stops working. I then can't type in the commands or interact with the terminal in any way.
It looks like whatever I do, is being targeted to another buffer somewhere.

I also noticed that when I first open the terminal it shows "TERMINAL" written in status bar. But as soon as I click anywhere, it changes to "NTERMINAL"

**To Reproduce**
1. Open nvim in any directory
2. Open terminal like (M+h)
3. Run commands and see everything works fine
4. Then click anywhere with mouse
5. Then see status bar "TERMINAL" changes to "NTERMINAL" and now you cant type commands there.

**Expected behavior**
We should be able to type commands and run them

**Screenshots**

![neovim-terminal-issue](https://github.com/NvChad/NvChad/assets/8384668/0add2eab-6c59-4b23-9a7c-867295a16167)

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Terminal: Default with Zsh
 - Version of Neovim: 0.9.5

**Additional context**
None

**Comment by siduck** [comment]
that is normal, please focus on your terminal's window... and then press  i to start typing in it

**Comment by brajnacs** [comment]
@siduck Focusing doesn't work in any way, How to focus it exactly? I tried clicking in terminal window, that doesn't work.
You can even see in Gif I posted, when i click in terminal window, the cursor is placed there, but whatever I type do not goes in that window

**Comment by siduck** [comment]
press "i"
