### ISSUE TITLE
I can't assign the toggle comment function to the gc command.

### ISSUE THREAD

**Issue by kamijodev** [siduck76/NvChad#2796]
**Describe the bug**

Hello! I recently started using nvchad as a beginner.
I want to execute comment toggling with gc, but it behaves strangely. Sometimes which-key.nvim appears.
Is this a bug, or is there something wrong with my settings?

It might be similar to #1972 

**To Reproduce**

```lua
nomap("n", "gc")
nomap("n", "gcc")

vim.keymap.set('n', 'gc',
  function()
    require("Comment.api").toggle.linewise.current()
  end, { desc = "Comment Toggle" }
)
```

**Desktop (please complete the following information):**
 - Operating System: Endeavour OS
 - Terminal: Alacritty
 - Version of Neovim: v0.10.0

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/a6af181f-c41b-46ef-844d-8e8c3d922874)

i guess you have to disable here

**Comment by siduck** [comment]
so in your custom plugins add that comment table ( not all of its options ), only keys and the mappings you need
