### ISSUE TITLE
vim.filetype.add({}) does not work in autocmd.lua

### ISSUE THREAD

**Issue by ckt114** [siduck76/NvChad#2797]
**Describe the bug**
I have the following code in `lua/autocmd.lua` but it doesn't work. No syntax highlighting. I've tested with lazyvim and it works as expected. 

```lua
vim.filetype.add({
  extension = {
    alloy = "terraform",
  },
})
```

**To Reproduce**
1. Add code above to `autocmd.lua`
2. Restart nvim

**Expected behavior**
Syntax coloring should work.

**Screenshots**
No

**Desktop (please complete the following information):**
 - Operating System: OSX Ventura
 - Terminal: wezterm
 - Version of Neovim: v0.95

**Additional context**
No

**Comment by ckt114** [comment]
I tried adding that same code to `~/.local/share/nvim/lazy/NvChad/lua/nvchad/autocmd.lua` and it works fine. So something is causing it not to work in my `autocmd.lua` file.

**Comment by ckt114** [comment]
Did a little more troubleshooting and it turns out that if I start vim first with `nvim` and then open the file then syntax highlighting works. If I do `vim file.alloy` the highlighting doesn't work.

**Comment by siduck** [comment]
and where are you loading this autocmd file?

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/fda38875-4632-4077-a728-95d3f6f92455

the filetype does get added here, not a nvchad issue

![image](https://github.com/NvChad/NvChad/assets/59060246/2725a66a-e4e6-425f-9920-13e67fdb5593)

**Comment by siduck** [comment]
i hope you have done `:TSInstall terraform` :/

**Comment by ckt114** [comment]
Thanks for looking into it. I wrapped the `autocmd.lua` inside of `vim.schedule` that was why it didn't work.

**Comment by siduck** [comment]
@ckt114  i'd  just create a new file called `lua/fts.lua`

and then `require("fts")` in main init.lua file

**Comment by ckt114** [comment]
@siduck Will do.
