### ISSUE TITLE
Failed to source

### ISSUE THREAD

**Issue by Tytan-Codes** [siduck76/NvChad#2798]
**Describe the bug**
when i run it i get a failed to source error

**To Reproduce**
1. follow nvchad install instructions
2. run nvim

**Expected behavior**
no error

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/91703892/5fb2456e-bd9c-4812-a3eb-cb0fdd32d50c)

**Desktop (please complete the following information):**
 - zorin 17.1
 - Wezterm
 - 0.9.5

When i run nvim it says:

```
Failed to source `/usr/share/nvim/runtime/filetype.lua`

vim/_editor.lua:0: /home/tytan/.config/nvim/init.lua..nvim_exec2() called at /home/tytan/.config/nvim/init.lua:0: Vim(source):E484: Can't open file /usr/share/nvim/runtime/filetype.lua

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - .config/nvim/init.lua:17
Press ENTER or type command to continue
```

**Comment by siduck** [comment]
not a nvchad issue :/

**Comment by siduck** [comment]
idk how you installed nvim on ubuntu, try its appimage and before installing nvchad rm -rf all nvim dirs
