### ISSUE TITLE
Noice conflict with lsp-config

### ISSUE THREAD

**Issue by DrTeagle** [siduck76/NvChad#2803]
**Describe the bug**
when opening a lua file or a python file I get the following output, this only happens with nvchad.configs.lspconfig.defaults, as every other time it has no error
![Screenshot from 2024-04-23 02-23-54](https://github.com/NvChad/NvChad/assets/65212972/12f2d1f3-7313-4d82-8afc-94cb87d08f74)

**To Reproduce**
1. Enable nvim-lspconfig
2. enable defaults
3. Enable noice.nvim

**Expected behavior**
For there to be no errors

**Screenshots**

**Desktop (please complete the following information):**
 - NixOs(irrelevant I hope)
 - (Alacrity)
 - nightly, have checked with non-nightly and error still appears

**Additional context**

**Comment by DrTeagle** [comment]
here was my config around time of writing
https://github.com/DockterTeagle/mynvimconfig.git

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/3b65e891-ef31-4f26-abb8-a46f39ea226c)

set it as false in M.ui

**Comment by DrTeagle** [comment]
thank you
