### ISSUE TITLE
[tabufline] Show lsp diagnostic info beside the buffer title

### ISSUE THREAD

**Issue by guanghechen** [siduck76/NvChad#2806]
**Is your feature request related to a problem? Please describe.**

Can me display LSP diagnostic information on the edge of the buffer title, as shown in the image below? This would help quickly identify which buffer needs action.

![image](https://github.com/NvChad/NvChad/assets/42513619/ec5e57a1-db46-4074-ace8-d6bfbb2910c6)

**Describe the solution you'd like**

If the current file has LSP warnings, errors, or hints, I'd like the opportunity to display them on the buffer. Considering the width limitations, we could use a priority-based approach to selectively display them. For example, if there are errors in the file, then we only display the error icon and the number of errors. Otherwise, if there are warnings, then we only display the warning icon and the number of warnings, and so on.

**Describe alternatives you've considered**

If it's hard to show such icons or numbers, I think render the title with different colors if there are some errors, warnings also good to me.

**Additional context**

**Screenshot**

**Comment by siduck** [comment]
i'd want to keep tabufline minimal so no

**Comment by siduck** [comment]
the tabufline just has one job, to show active buffers & tabs
