### ISSUE TITLE
Specific Custom Highlight Groups

### ISSUE THREAD

**Issue by namack** [siduck76/NvChad#2809]
**Describe the bug**
I am trying to control the theming overrides for a treesitter capture group. For example, I'd like to override `@keyword.coroutine` color. I am able to update the `@keyword` highlight groups using the information provided in the [theming docs](https://nvchad.com/docs/config/theming), but more specific highlight groups are not applied.

**To Reproduce**
1. Find capture group info by running `:Inspect`
<img width="551" alt="image" src="https://github.com/NvChad/NvChad/assets/6923792/a48cbaea-5129-4f8b-a20d-50933512b5dd">

2. Update theme overrides using the capture group
```lua
M.ui = {
  theme = "radium",
  hl_override = {
    --  This capture group works
    ["@keyword"] = { italic = true, fg = "blue" },

    -- This capture group does not work
    ["@keyword.coroutine"] = { fg = "red" },
  }
}
```
3. Restart nvim
4. Syntax highlighting works for `@keyword` but does not work for `@keyword.coroutine`

**Expected behavior**
Theme overrides should also apply to more specific capture groups.
**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
   - macOS Sonoma 14.4.1
 - Terminal
   - iTerm 2 Build 3.4.23
 - Version of Neovim
   - v0.9.5

**Additional context**
There's a good chance I'm barking up the wrong tree. Is it possible to override more specific highlight groups? Or are we limited to the top level link (in this case `@keyword`)?

**Comment by siduck** [comment]
use hl_add cuz  your hlgroups are new and not defined in nvchad

**Comment by namack** [comment]
Ah perfect, thank you so much! Love NVChad btw, it's great.
