### ISSUE TITLE
Setup prettier/eslint installed inside every node project

### ISSUE THREAD

**Issue by caneta** [siduck76/NvChad#2812]
I'm used to work with prettier/eslint installed per project instead the ones installed in the editor itself, because:

1. every project could have a different prettier/eslint version
2. every project could have a different prettier/eslint configuration
3. the configuration is shared into the project repo to assure that every dev uses the same version/conf

Now, how to tell NVChad to do that?

I'm not sure on what to configure to achieve this: Mason? Conform? I need to install something else?

Is there any config snippet suggested?

Thanks

**Comment by siduck** [comment]
mason shouldnt be  used here, because it downloads stuff globally for neovim and puts in a folder

i think you will achieve it by npm  and for eslint, use lspconfig and for prettier, use conform. And make sure prettier/eslint isnt installed globally

**Comment by caneta** [comment]
No way to make project prettier work: I've got some hint [here](https://github.com/stevearc/conform.nvim/issues/225), but cannot find the executable:
![image](https://github.com/NvChad/NvChad/assets/4066659/f2ad8eb7-d317-481b-803f-ff3356991db5)

My current config inside lua/configs/conform.lua is the following:

```
local options = {
  formatters = {
    prettier = {
      command = "./node_modules/.bin/prettier",
    },
  },

  formatters_by_ft = {
    lua = { "stylua" },
    css = { "prettier" },
    scss = { "prettier" },
    html = { "prettier" },
    javascript = { "prettier" },
    javascriptreact = { "prettier" },
    typescript = { "prettier" },
    typescriptreact = { "prettier" },
  },

  format_on_save = {
    -- These options will be passed to conform.format()
    timeout_ms = 500,
    lsp_fallback = true,
  },
}

require("conform").setup(options)
```

Any suggestion?

**Comment by siduck** [comment]
@caneta i dont use prettier so cant help sorry! you could ask in conform repo

**Comment by siduck** [comment]
or r/neovim

**Comment by caneta** [comment]
I solved with some changes to [NvChad/starter](https://github.com/NvChad/starter); here's a minimal example with prettier for css files:
### lua/plugins/init.lua
```lua
{
  "stevearc/conform.nvim",
  event = "BufWritePre", -- uncommented
  cmd = "ConformInfo", -- otherwise ConformInfo don't show up until first <leader>fm
  config = function()
    require "configs.conform"
  end,
},
```
### lua/configs/conform.lua
```lua
local options = {
  ft_parsers = { -- added
    css = "css",
  },

  formatters_by_ft = {
    css = { "prettier" }, --uncommented
  },

  format_on_save = { -- uncommented and changed
    -- These options will be passed to conform.format()
    timeout_ms = 999999, -- non way to make it work otherwise!
    lsp_fallback = true,
  },
}
```
### lua/mappings.lua
```lua
-- overwriting the same lines in NvChad mapping file, in order to add timeout_ms
-- even here no way to make it work without it
map("n", "<leader>fm", function()
  require("conform").format({ timeout_ms = 999999, lsp_fallback = true })
end, { desc = "custom format files" })
```

I do not know why but the [Conform async options](https://github.com/stevearc/conform.nvim/tree/master?tab=readme-ov-file#formatopts-callback) (default to false) seems not to work properly here...

**Comment by siduck** [comment]
@caneta if it works the weird way then the plugin probably has a bug, you should make an issue there!

**Comment by caneta** [comment]
No bugs Conform side, the author just clarified me how to configure it better: https://github.com/stevearc/conform.nvim/issues/401

In the end I make it work with the following:

### lua/plugins/init.lua
```lua
{
  "stevearc/conform.nvim",
  event = "BufWritePre",
  cmd = "ConformInfo",
  config = function()
    require "configs.conform"
  end,
},
```
### lua/configs/conform.lua
```lua
local options = {
  formatters_by_ft = {
    css = { "prettier" },
  },

  format_after_save = {
    lsp_fallback = true,
  },
}
```
### lua/mappings.lua
```lua
-- overwriting the same lines in NvChad mapping file, in order to add `async = true`
map("n", "<leader>fm", function()
  require("conform").format({ async = true, lsp_fallback = true })
end, { desc = "custom format files" })
```
Maybe the last one could be added to [the core mappings](https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/mappings.lua) of NvChad!

**Comment by siduck** [comment]
are there any cons of async?

**Comment by caneta** [comment]
Nope, as far as I know...
