### ISSUE TITLE
fs_event watcher error while using nvimtree (ctrl+n)

### ISSUE THREAD

**Issue by dawaldow** [siduck76/NvChad#2814]
**Describe the bug**
Each time I use CTRL + N, the message in the attached picture occurs for each file (or each directory).  

**To Reproduce**
1. open NVIM
2. CTRL+N
3. error occurs consistently and for each file in the directory
4. see picture

**Expected behavior**
No error should occur when activating CTRL+N.

**Screenshots**
![Screenshot from 2024-04-30 14-11-35](https://github.com/NvChad/NvChad/assets/57457955/bd5b2f6b-6efd-4ad8-bd0d-dd28cdc8ff10)
![Screenshot from 2024-04-30 14-16-33](https://github.com/NvChad/NvChad/assets/57457955/6e3bb28e-58a0-4c63-ac87-d94b1c96267f)

**Desktop (please complete the following information):**
 - Operating System: UBUNTU 24.04
 - Terminal: Gnome Terminal
 - Version of Neovim: 0.9.5

**Comment by siduck** [comment]
not a nvchad  issue, go ask in nvimtree repo!

**Comment by dawaldow** [comment]
ok, makes sense ... thank you.
