### ISSUE TITLE
Disabling tabufline breaks <C-i> key binding

### ISSUE THREAD

**Issue by pablolagreca** [siduck76/NvChad#2818]
Using the following config in chadrc.lua 

local M = {}

M.ui = {
	theme = "chadracula-evondev",
  -- Disabling tabufline makes <C-i> stop working
  tabufline = {
    enabled= false
  }
}

return M

Causes <C-i> to break with some ipairs error.

**To Reproduce**
- Update chadrc.lua with the provided config.
- Restart neovim
- Type <C-i>

You should see an error

**Expected behavior**
Keybinding should work taking you to the previous visited location

**Desktop (please complete the following information):**
 - MacOS
 - Kitty
 - 0.9

**Comment by siduck** [comment]
please disable `<Tab>` and`<S-Tab>` keys
