### ISSUE TITLE
Installing NvChad on fresh Ubuntu throws error

### ISSUE THREAD

**Issue by vincentka52** [siduck76/NvChad#2824]
When trying to install NvChad by following the guide (running `git clone https://github.com/NvChad/starter ~/.config/nvim && nvim`) the following error appears in the left bottom corner for a moment, then it is stays on the Plugins installation page:

`Error detected while processing /home/username/.config/nvim/init.lua:`

Ubuntu 24.04
zsh 5.9
nvim v0.9.5

Can you please point me how can I further investigate what's the source of the given error?

**Comment by maxawake** [comment]
I have the same issue on Arch Linux

**Comment by siduck** [comment]
rm -rf ~/.local/share/nvim

and make sure you     have latest  git version or else lazy wont work well

**Comment by vincentka52** [comment]
I'm running git `2.43.2`. I've tried to reinstall it multiple times with running `rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim` between reinstalling, didn't help either.

**Comment by siduck** [comment]
show image of full error

**Comment by vincentka52** [comment]
Ok, I was able to see whole error by running `:mes`, it was `No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.`

The problem was that there was no C compiler, I resolved it by installing `gcc`. Maybe it could be mentioned in the installation page that having a C compiler installed is required.

**Comment by siduck** [comment]
> Ok, I was able to see whole error by running `:mes`, it was `No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.`
> 
> The problem was that there was no C compiler, I resolved it by installing `gcc`. Maybe it could be mentioned in the installation page that having a C compiler installed is required.
 
![image](https://github.com/NvChad/NvChad/assets/59060246/fbbcebce-2ffc-42d3-aea9-0cae4d6db702)

**Comment by vincentka52** [comment]
completely missed this, apologies, and thanks for assistance and the `NvChad` config!
