### ISSUE TITLE
Override highlight groups by multiple colors of base46

### ISSUE THREAD

**Issue by AstrickHarren** [siduck76/NvChad#2827]
**Is your feature request related to a problem? Please describe.**
I want to override the hl groups `DiffAdd` to furnish a greenish bg and no fg. The green bg should vary 
depending on if the theme is light or dark. My approach is to calculate the luminance of the `Normal` (or base30.black)
color group and decide the current theme type. 

**Describe the solution you'd like**
This require me to take in more than one color from base30 as an input calculate `DiffAdd` 

**Describe alternatives you've considered**
It could also be useful to have a user-defined event under theme switch by base46 (which I have not found yet)

**Comment by siduck** [comment]
https://nvchad.com/docs/config/theming/

**Comment by AstrickHarren** [comment]
For those who are interested in how to change diffview colors based on theme type, I was able to do this with an autocmd on BufEnter the diffview buffers that changes the highlight groups dynamically with base46's `type`. 

There may be a more natural way to do this, perhaps customizing a theme integration like one in the base46.integration dir is most satisfying, but I was unable to figure out how even after reading related documentations and source codes.

**Comment by AstrickHarren** [comment]
![02:56:10PM@May_08_2024 grim](https://github.com/NvChad/NvChad/assets/33888523/348c75a1-f95d-47d1-a873-04913b525b40)
![02:55:51PM@May_08_2024 grim](https://github.com/NvChad/NvChad/assets/33888523/2a9321e6-ec28-41a7-a474-a481f4d1aca2)

**Comment by siduck** [comment]
why dynamically tho?  most use red for diffremoved, green for added. So just use hl_override!
