### ISSUE TITLE
Tab size is 4 in a Zig file.

### ISSUE THREAD

**Issue by mubin-thinks** [siduck76/NvChad#2828]
**Describe the bug**
Assalamu alaikum, the tab size in a zig file is 4. Formally when I press tab in a zig file there are 4 spaces in total. That isn't usually the case for other programming languages (C, C++, Lua, Python, etc.). How do I change it back to 2? I have installed the zls for zig LSP.

**To Reproduce**
1. Open `nvim test.zig`
2. Press tab.
3. If it shows 2 spaces then install zls.

**Expected behavior**
The tab spaces should be 2.

**Desktop (please complete the following information):**
 - Arch on `kernel: 6.6.30-1-lts`
 - Alacritty
 - NVIM v0.9.5

Thanks.

**Comment by siduck** [comment]
not a nvchad issue, either the zig filetype is setting it or some plugin you use is doing it

`verbose set tabstop` , run that command and see
