### ISSUE TITLE
Error while opening files on Windows

### ISSUE THREAD

**Issue by koppa96** [siduck76/NvChad#2834]
**Describe the bug**
When I try to save a file after a clean install of NvChad that already existed before opening neovim with `:w`, I get the following error message: `E13: File exists (add ! to override)`.

If I open the file directly, instead of just running `nvim`, I get the following error message:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24: Error executing lua: ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: Failed to load parser for language 'lua': uv_dlopen: C:\Users\Peti\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.

stack traceback:
        [C]: in function '_ts_add_language'
        ...win64/share/nvim/runtime/lua/vim/treesitter/language.lua:98: in function 'add'
        ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:98: in function 'new'
        ...n64/nvim-win64/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        ...n64/nvim-win64/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...n64/nvim-win64/share/nvim/runtime/lua/vim/treesitter.lua:460: in function 'start'
        ...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:25: in function <...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24: in function <...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:25: in function <...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24: in function <...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:24: in function <...ti/nvim-win64/nvim-win64/share/nvim/runtime/filetype.lua:10>
```

**To Reproduce**
1. Install Neovim 0.9.5
2. Follow the instructions in the [installation tutorial](https://nvchad.com/docs/quickstart/install/). I used Powershell to install NvChad.
3. Open a pre-existing lua file, eg. the `init.lua` file in your Neovim config folder.

**Expected behavior**

**Screenshots**
The output of `:w`:

![image](https://github.com/NvChad/NvChad/assets/43555816/455ddc43-f1d7-48ed-a1b8-74556b2ca147)

The output of `:f`:
![image](https://github.com/NvChad/NvChad/assets/43555816/0bae61e2-d12c-473f-876b-1c4ee5623884)

The error when I open the file directly:

![image](https://github.com/NvChad/NvChad/assets/43555816/4808a9ff-957e-49c5-b5df-64e78d416e0b)

**Desktop (please complete the following information):**
 - Windows 11 23H2 (Build nr. 22631.3447)
 - Terminal: Powershell
 - 0.9.5

**Additional context**

I have `gcc` and `make` installed and in the path.

![image](https://github.com/NvChad/NvChad/assets/43555816/c6424276-b9e0-4ab5-91f6-95db13522d27)

**Comment by siduck** [comment]
that doesnt look like a nvchad error. I suggest you to rm -rf all nvim dirs and reinstall nvchad. Also delete `~/.local/state/nvim` , idk what that might be on windows tho! check by `:echo stdpath("state")`

**Comment by koppa96** [comment]
If anyone faces an issue like this, see this: https://github.com/nvim-treesitter/nvim-treesitter/issues/1985

I managed to make it work with zig, instead of gcc as compiler.

**Comment by siduck** [comment]
nice!
