### ISSUE TITLE
"Default" (neovim/vim) theme or "no theme" not an option

### ISSUE THREAD

**Issue by scmeek** [siduck76/NvChad#2839]
**Describe the bug**
I'd prefer to use the default theme of neovim if possible, especially in anticipation of v0.10 on the horizon.

**To Reproduce**
Steps to reproduce the behavior (configs):
1. Specify no theme in `chadrc.lua`
2. A theme is still applied

Steps to reproduce the behavior (runtime):
1. Type `<leader>th` to bring up theme options
2. Only third-party themes are shown

**Expected behavior**
An option to not apply a theme.

**Screenshots**

**Desktop:**
 - Operating System: macOS
 - Terminal: Alacritty
 - Version of Neovim: v0.9.5

**Additional context**
N/A

**Comment by siduck** [comment]
the default theme does not have highlight groups for our statusline/tabufline and more. So its not supported in nvchad. 

Although you can override all instances of `dofile` function in plugin config functions and your main init.lua

**Comment by scmeek** [comment]
Ok, I’ll take a look. Thanks for the prompt response. Meant to mention this in the original post - love the project and using it! Really appreciate the hard work that’s gone into it.
