### ISSUE TITLE
indent-blankline.nvim failed after updated

### ISSUE THREAD

**Issue by DefectingCat** [siduck76/NvChad#2840]
**Describe the bug**

indent-blankline.nvim failed after updated

**To Reproduce**
1. Lazy sync to update indent-blankline to latest
2. Startup and open a buffer

**Expected behavior**

**Screenshots**

![image](https://github.com/NvChad/NvChad/assets/25033493/6714881b-f11f-4c0e-963c-e706327fc550)

![image](https://github.com/NvChad/NvChad/assets/25033493/852f3d57-3cd4-4872-b05e-ef329e871832)

**Desktop (please complete the following information):**
 - Operating System: Arch linux
 - Terminal: kitty
 - Version of Neovim: 0.9.5

**Additional context**

**Comment by MaggieLostKeys** [comment]
Looks like indent-blankline.nvim was just updated to support NeoVim 0.10.
That seems to have introduced this issue. They seem aware of that.

Not sure if this is an option for you, but bumping NeoVim to 0.10 fixed this for me.

**Comment by nonepork** [comment]
Why is everyone in this issue a cat.
