### ISSUE TITLE
neovim 0.11 compatibility: vim.lsp.get_active_clients() deprecated

### ISSUE THREAD

**Issue by glyh** [siduck76/NvChad#2842]
```
vim.lsp.get_active_clients() is deprecated, use vim.lsp.get_clients() instead. :help deprecated                           
Feature will be removed in Nvim 0.12                                                                                      
stack traceback:                                                                                                          
        /usr/share/nvim/runtime/lua/vim/lsp.lua:785: in function 'get_active_clients'                                     
        ...e/lyh/.local/share/nvim/lazy/ui/lua/nvchad/stl/utils.lua:145: in function 'lsp'                                
        ...lyh/.local/share/nvim/lazy/ui/lua/nvchad/stl/default.lua:50: in function 'module'                              
        ...e/lyh/.local/share/nvim/lazy/ui/lua/nvchad/stl/utils.lua:29: in function <...e/lyh/.local/share/nvim/lazy/ui/lu
a/nvchad/stl/utils.lua:16>  
```

My neovim version:
```
NVIM v0.11.0-dev-6+g06135cc21
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by glyh** [comment]
Looks like we're at a narrow compatibility point: Any version other than 0.10 is not compatible with NvChad, not newer, not older.

**Comment by glyh** [comment]
For anyone wondering on Arch Linux, you have to use Extra-Testing package neovim to work with NvChad for now. 

https://archlinux.org/packages/extra-testing/x86_64/neovim/

Which is pretty unfortunate.

**Comment by glyh** [comment]
Feel free to close it if you feel this is out of scope of the project at the moment.

**Comment by glyh** [comment]
<del>For any one use 0.11, here's a quick patch:</del>

<del>https://github.com/glyh/NvChad</del>

**Comment by danielstopp** [comment]
> For any one use 0.11, here's a quick patch:
> 
> https://github.com/glyh/NvChad

That's a 404, unfortunately.

Any other resources or solutions?

**Comment by siduck** [comment]
@Odiumediae  @glyh both of you do lazy sync

**Comment by glyh** [comment]
I deleted that repo as this is already fixed in master.

**Comment by ngthminhdev** [comment]
> ~For any one use 0.11, here's a quick patch:~
> 
> ~https://github.com/glyh/NvChad~

so, can i use nvchad with 0.11 now?
