### ISSUE TITLE
Error executing lua: vim/_editor.lua:431: nvim_exec2(): Vim(bwipeout):E517: No buffers were wiped out:  bw3

### ISSUE THREAD

**Issue by KevinGamer3D2** [siduck76/NvChad#2843]
**Describe the bug**
No buffers were wiped out whenever closing Nvimtree with Space + X

**To Reproduce**
1. Press Space + E or Ctrl + N
2. Press Space + X

**Expected behavior**
Nvimtree should be completely closed it's window by pressing Space + X.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/63291726/5b58dea6-9f17-4c08-b340-a1a8e7653bca)

**Desktop:**
 - Windows 11
 - Windows Powershell
 - Neovim 0.10.0

**Comment by siduck** [comment]
do lazy sync, to update ui plugin
