### ISSUE TITLE
Config reloading at startup if data directory is a symbolic link

### ISSUE THREAD

**Issue by SDA-31** [siduck76/NvChad#2845]
**Describe the bug**
I've symlinked `~/.local/share/nvim` to another location. After this, the config is reloaded on each startup with the message:
```
# Config Change Detected. Reloading...

- **added**: `/opt/sda/.local/share/nvim/lazy/NvChad/lua/nvchad/plugins/init.lua`
- **added**: `/opt/sda/.local/share/nvim/lazy/NvChad/lua/nvchad/plugins/ui.lua`
- **deleted**: `.local/share/nvim/lazy/NvChad/lua/nvchad/plugins/ui.lua`
- **deleted**: `.local/share/nvim/lazy/NvChad/lua/nvchad/plugins/init.lua`
```

**To Reproduce**
1. Move `~/.local/share/nvim` to the another location
2. Create symlink to the data catalogue

**Expected behavior**
Starts with configuration reloading only when necessary.

**Desktop (please complete the following information):**
 - OS: Artix Linux x86_64
 - Terminal: Foot
 - Version of Neovim: 0.10.0

**Comment by siduck** [comment]
not a nvchad issue, its lazy which detects the change. Idk why would you want a symlink there :thinking:  . If you want to use nvchad in a different dir then use nvimappname feature

**Comment by SDA-31** [comment]
> Idk why would you want a symlink there 🤔 . If you want to use nvchad in a different dir then use nvimappname feature

Not really. I'm running out of space in the /home directory, sooo... i've moved it to another partition (with zstd -2 compression)

Also, I have another annoying bug with Lazy.nvim. If you open a file and immediately go to the end of it (by pressing `G`), you will get an error message that will not go away until you close Neovim.

**Comment by SDA-31** [comment]
> Also, I have another annoying bug with Lazy.nvim

Oh, nvm. It is a bug in the different plugin
