### ISSUE TITLE
Terminal window in insert mode can not be exited by `ESC` on nvim 0.10

### ISSUE THREAD

**Issue by lishanyu777** [siduck76/NvChad#2857]
**Describe the bug**
In nvim 0.10, terminal window will not exit when pressing `ESC`

**To Reproduce**
1. use `<leader>h` to show the terminal window
2. tap `ESC`, the terminal window do not close

**Expected behavior**
expect the terminal window to close after tapping `ESC`

**Desktop (please complete the following information):**
 - Operating System: mac 14.4.1 (23E224)
 - Terminal wezterm
 - Version of Neovim 0.10

**Additional context**
I have using Lazy sync to update, but the problem still exists. Thanks for your help.
<img width="1033" alt="image" src="https://github.com/NvChad/NvChad/assets/160578081/aa819dc7-aec7-4cb9-98ae-7f421ca5f355">

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/156eeef8ecae812acd79d5eb58070d734a6202c6

**Comment by siduck** [comment]
it was removed due to some issues, you are free to add it in your config
