### ISSUE TITLE
Add lsp diagnostic keybinds back

### ISSUE THREAD

**Issue by KorigamiK** [siduck76/NvChad#2858]
**Describe the bug**
As of Nvim v0.10.0 https://github.com/neovim/neovim/pull/16230 the keybind was added to jump to next diagnostic does not open the lsp diagnostic float by default and you have to use the bind `<C-w>d` to open it.

NvChad however used `vim.diagnostic.goto_next` in the past which opens the diagnostic window as well. So adding these mappings back should be better as more people (including me) are used to the old binding.

These should do the trick:
```lua
map("n", "[d", vim.diagnostic.goto_prev, { desc = "lsp prev diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "lsp next diagnostic" })
```

**Comment by siduck** [comment]
@KorigamiK i'd avoid overriding the defaults, the line's virtual text still shows so imo its not necessary to show floating window always
