### ISSUE TITLE
NvTerm nested EDITOR sessions

### ISSUE THREAD

**Issue by dee-kryvenko** [siduck76/NvChad#2859]
Let me start with huge thanks for the project. It has become my entrance to the world of vim. Such a great learning experience - truly appreciated.

A little context - I am trying to replace tmux with a vim session with a bunch of NvTerm tabs. I could not tolerate the difference in between tmux and vim, some features are just not there at all in tmux (like - relative line numbers in the terminal). I often find myself scrolling through terminal history trying to yank bits and pieces to be send somewhere externally like a chat or email, and having differences in behavior between raw tmux and NvTerm session drives me nuts. I know I can remap key bindings in tmux of course, but it does not have feature parity with NvTree Ctrl+X, and never will. I do not think it was ever a point of the project. I still use tmux as tabs with different vim sessions btw, I just do not want to use tmux for navigation in the visual mode.

The problem I am facing with my workflow is that if I am in vim in NvTerm session, and I run a command like `git commit` or `kubectl edit` with `EDITOR=nvim`, I get a nested vim opened inside NvTerm. It leads to some peculiar behavior, and obviously is completely unusable.

Is it maybe already a feature that exists, that I can set something special into my `EDITOR` to make it just open a new tab in the vim session that is already open? If not, would it be something you'd consider supporting? Any alternatives you could think of?

**Comment by siduck** [comment]
@dee-kryvenko  i hope you're using nvchad v2.5! if not then check the news page on nvchad.com.  Also i have removed nvterm as it was not maintained by me and its codebase felt complex, so made a minimal module : https://nvchad.com/docs/config/nvchad_ui/#term

As for your nested issue, it isnt nvchad's bug. i tried with `nvim --clean` -> `:sp && term` ->  `nvim --clean` and saw the nested nvims! ask at r/neovim or its matrix server

**Comment by dee-kryvenko** [comment]
@siduck thanks for getting back to me! Yes, I'm using the latest - didn't realize what I'm using is no longer NvTerm. Good to know.

I wasn't sure if nvim itself would have anything to do with this, I thought this might be expected behavior actually. If you think this might be a bug, I could try to ask around in the upstream community.

My train of thought was that since terminal plugin runs in the vim session, it can communicate with it. So if I set something special into the EDITOR variable that is being listened by the terminal plugin, that would open a new buffer etc... as it also needs to wait for the buffer to save and close to continue executing command that spawned EDITOR. Do you think this is something nvim itself should/does support?

**Comment by siduck** [comment]
@dee-kryvenko i doubt if neovim would prevent this but there are some plugins i think which can do

look https://www.reddit.com/r/neovim/comments/11o53jg/flattennvim_open_files_from_a_neovim_terminal_in/

**Comment by siduck** [comment]
```lua

  {
    "samjwill/nvim-unception",
    event = "VeryLazy",
  },

```

**Comment by siduck** [comment]
https://github.com/samjwill/nvim-unception

**Comment by dee-kryvenko** [comment]
I can confirm it works great with

```
    {
        "willothy/flatten.nvim",
        config = true,
        lazy = false,
        priority = 1001,
    },
```

For blocking input, I had to do

```
export EDITOR="nvim --cmd 'let g:flatten_wait=1'"
```

Thanks a lot!

**Comment by siduck** [comment]
@dee-kryvenko  although i'd avoid lazy=false if event=VeryLazy or VimEnter works!!

**Comment by dee-kryvenko** [comment]
> @dee-kryvenko  although i'd avoid lazy=false if event=VeryLazy or VimEnter works!!

Agreed, should work for most cases I think. In my case, I generally watch out for what is getting loaded at which time, and I know that doing this one with `lazy = false` is not going to substantially harm my setup, while I can imagine some cases where lazy loading could potentially cause issues if I were to run it from some sort of a script or alias that does some action immediately after opening vim. It's not like I do it for every plugin, don't worry 😆 

Thanks for a tip though!
