### ISSUE TITLE
Most Lsp commands not working.

### ISSUE THREAD

**Issue by Frusadev** [siduck76/NvChad#2865]
**Bug description**
Here's the output of :LspInfo

Error executing Lua callback: ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:155: bad argument #1 to 'concat'
 (table expected, got string)
stack traceback:
        [C]: in function 'concat'
        ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:155: in function 'make_client_info'
        ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:236: in function <...re/nvim/lazy/nvim-lspconfig/lua/l
spconfig/ui/lspinfo.lua:187>
        ...ocal/share/nvim/lazy/nvim-lspconfig/plugin/lspconfig.lua:64: in function <...ocal/share/nvim/lazy/nvim-lspconfi
g/plugin/lspconfig.lua:63>
Press ENTER or type command to continue

![Screenshot from 2024-05-31 10-25-06](https://github.com/NvChad/NvChad/assets/81917636/9fcd8546-2f3e-493f-adc6-b06ca79ddec3)

And the output of :LspRestart

![Screenshot from 2024-05-31 10-28-10](https://github.com/NvChad/NvChad/assets/81917636/724641e4-30ee-4fef-bd58-b987c97a423e)

:LspStart

![Screenshot from 2024-05-31 10-29-24](https://github.com/NvChad/NvChad/assets/81917636/14b1dda2-22e4-4f03-830b-8523a9550295)

**To Reproduce**
Try any of these commands: 
 - LspInfo
 - LspRestart
 - LspStart
 
**Expected behavior**

 - LspInfo should give information about the current language server (Or the ones attached to the buffer)
 - LspRestart should restart the current language server for the current buffer
 - LspStart should start the language server for the current buffer

**Desktop information:**
 - Operating System: Fedora Linux 40 Workstation Edition, But i still had this issue when i was on ArchLinux
 - Terminal: Wezterm
 - Version of Neovim: 0.9.5-4

**Comment by siduck** [comment]
those clearly are not nvchad errors, look at the file paths. I advice you to use v0.10.

**Comment by Frusadev** [comment]
It seems to be working with LazyVim though 🤷. I'll try to reinstall the Lsp

**Comment by Frusadev** [comment]
It worked after downloading the latest nvchad version.
