### ISSUE TITLE
Telescope image preview is not working

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [siduck76/NvChad#2866]

**Comment by siduck** [comment]
obviously it wouldnt, neovim is a cli tool.  use something like telescope media plugin

This is  my config for using some telescope extensions! the nerdy is for nerdfont icons

```lua
{
    "nvim-telescope/telescope.nvim",
    opts = {
      extensions_list = { "fzf", "terms", "nerdy", "media" },

      extensions = {
        media = {
          backend = "ueberzug",
        },
      },
    },

    dependencies = {
      { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
      "2kabhishek/nerdy.nvim",
      "dharmx/telescope-media.nvim",
    },
  },
  ```
  
  and then run Telescope media command

**Comment by ahmedsayedabdelsalam** [comment]
Thank you 👌

I think we need to change the readme then

![image](https://github.com/NvChad/NvChad/assets/29691074/c2d8b0b8-0547-4d9c-ad18-b691ec16ef31)

**Comment by siduck** [comment]
done
