### ISSUE TITLE
Throws error when opening file without having a C compiler installed

### ISSUE THREAD

**Issue by J-Kappes** [siduck76/NvChad#2868]
**Describe the bug**
When calling `nvim anyfile` with no C compiler installed, NvChad throws an error. Luckily, it can be dismissed by pressing any key.

**To Reproduce**
1. Don't have a C compiler installed, e.g. fresh install of OpenSuse microOS
2. call `nvim anyfile`

**Expected behavior**
NvChad should not throw an error.

**Screenshots**
```
Error detected while processing BufNewFile Autocommands for "*":                                                               
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.                                                     
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.                                                     
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.                                                     
Press ENTER or type command to continue    
```

**Desktop (please complete the following information):**
 - Operating System: OpenSuse microOS
 - Terminal: Kitty
 - Version of Neovim: 0.9.5

**Comment by Alexis12119** [comment]
Please install `gcc` or any compiler there because `nvim-treesitter` needs it to install the `language parser` to improve the syntax highlighting.
