### ISSUE TITLE
Annoying issue with the terminal window

### ISSUE THREAD

**Issue by AregGhazaryan** [siduck76/NvChad#2872]
I know i might ask something noobish or annoying, but sometimes when i press ctrl + x to enter visual mode in terminal sometimes i would accidentally hit tab and it would replace the terminal with one of the open tabs, and i cant get it back using leader + j key, when i use leader + h it opens a new one while still retaining the processes run by the previous terminal, so i have to open something like activity monitor and delete those processes everytime.
How can i prevent the terminal window from acidentally swapping with the tabs?
Sorry for annoying to you all, thank you.

**Comment by siduck** [comment]
only thing you can do is change our tab mapping's function and manipulate with it i.e if current buffer's a terminal then dont run the tabufline function
