### ISSUE TITLE
Opening any lua or vim file crashes neovim.

### ISSUE THREAD

**Issue by vaqxai** [siduck76/NvChad#2874]
**Describe the bug**
When any file with the extension `.vim` or `.lua` is opened, neovim crashes.

**To Reproduce**
1. run `nvim test.lua` or `nvim test.vim` in your shell
2. or open `nvim` and open a `vim` or `lua` file through `<Leader>e` `nvim-tree`
3. or open `nvim` and run `:e test.lua` or `:e test.vim`

**Expected behavior**
The file is opened in a buffer for editing.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Terminal: Windows Terminal
 - Version of Neovim: Neovim 0.9.5

**Additional context**

**Comment by siduck** [comment]
unable to reproduce and also use v0.10
