### ISSUE TITLE
vim.lsp.get_active_clients() is deprecated

### ISSUE THREAD

**Issue by xarthurx** [siduck76/NvChad#2875]
**Describe the bug**
The `vim.lsp.get_active_clients()` is deprecated, and will be removed in `Nvim v0.12`.

**To Reproduce**
`:checkhealth vim.deprecated`

**Expected behavior**
replace the function as described in the report.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/1921878/1d456217-c393-4a2d-abfe-c799c3e51770)

**Comment by Alexis12119** [comment]
I think it'll better if you filed that on the `NvChad/ui` repo.

https://github.com/NvChad/ui

**Comment by siduck** [comment]
![image](https://github.com/NvChad/NvChad/assets/59060246/40f25248-ba61-4278-b2e7-0815de6d382b)

i have update to new functions days ago, please do lazy sync
