### ISSUE TITLE
Modularize NvChad

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [siduck76/NvChad#2876]
**Is your feature request related to a problem? Please describe.**
I would love to use standalone NvChad plugins without any hackery

**Describe the solution you'd like**
Make plugins easily configurable, without hardcoding specific files to search for. The usual `require(xyz).setup` would be great

**Describe alternatives you've considered**
Right now I am using some hackery to make my configuration compatible, but it was bothersome to implement and sometimes things break (for instance right now I am trying to figure out why top bar is not showing when multiple files are open)

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/blob/v2.5/lua/nvconfig.lua

and please make the change in your chadrc

**Comment by gytis-ivaskevicius** [comment]
yes, I am aware how to hack it together, I am asking to make it more modular. as in you open `base64`  or `nvchat-ui` repo and you see simple example and available options how to configure it, they should not be searching for config files themselves

**Comment by siduck** [comment]
@gytis-ivaskevicius its not possible,  we cant autoreload ui/base46 stuffs , we'd have to use lazy reload feature which doesnt work well sometimes.

https://nvchad.com/docs/config/nvchad_ui/
https://nvchad.com/docs/config/theming

those are ui/base46 docs
