### ISSUE TITLE
Terminal Send CTRL + X to exit nano

### ISSUE THREAD

**Issue by eminfedar** [siduck76/NvChad#2879]
**Describe the bug**
Can't exit from nano in a terminal window because CTRL + X unfocusing the terminal window.

**To Reproduce**
1. Open terminal with `<leader> + h`
2. Open nano
3. can't exit with `CTRL + X`

**Expected behavior**
I need to exit from nano with sending `CTRL + X` to terminal

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal: Gnome Terminal
 - Version of Neovim: 0.10

**Comment by siduck** [comment]
just disable <C-x> mapping in `t` mode

**Comment by linhx** [comment]
I tried to disable in init.lua
```
-- Disable mappings
local nomap = vim.keymap.del

nomap("t", "<C-x>")
```

But I got error "No such mapping"

**Comment by siduck** [comment]
just tried here,it works @linhx  i hope you're using nvchad  v2.5

**Comment by linhx** [comment]
@siduck thanks for crazy fast reply.
I'm in the latest commit of https://github.com/NvChad/starter/commits/main/

**Comment by siduck** [comment]
@linhx   load it  after nvchad.mappings or else it wont work


 so put  it here https://github.com/NvChad/starter/blob/main/lua/mappings.lua#L10

**Comment by linhx** [comment]
Thank you, it's working now.
