### ISSUE TITLE
leader + / for comment toggle doesnt work

### ISSUE THREAD

**Issue by insanXYZ** [siduck76/NvChad#2882]
I can't use leader + / for "comment toggle", why is this? is this a bug?

**Comment by siduck** [comment]
update neovim to 0.10

**Comment by bryanmaina** [comment]
Same here, it does not work for me.

![image](https://github.com/NvChad/NvChad/assets/8012851/6461caaa-acfd-4178-83c4-286fee280a76)

**Comment by siduck** [comment]
@bryanmaina i hope you are using latest nvchad 

and please use 0.10 stable one, idk if your dev version has the comment feature
