### ISSUE TITLE
gopls doesn't work with NvChad

### ISSUE THREAD

**Issue by Slorrr** [siduck76/NvChad#2885]
#### Problem Description
I installed a clean version of NvChad and downloaded `gopls` using Mason. However, when running the `:LspInfo` command, `gopls` does not appear as an active LSP server.

#### Steps to Reproduce

1. Installed a clean version of NvChad.
2. Installed `gopls` using Mason:
    ```vim
    :MasonInstall gopls
    ```
3. Added the following configuration to `configs/lspconfig.lua`:

    ```lua
    local on_attach = require("nvchad.configs.lspconfig").on_attach
    local on_init = require("nvchad.configs.lspconfig").on_init
    local capabilities = require("nvchad.configs.lspconfig").capabilities

    local lspconfig = require "lspconfig"
    local servers = { "html", "cssls", "gopls" }  -- Added gopls

    -- lsps with default config
    for _, lsp in ipairs(servers) do
      lspconfig[lsp].setup {
        on_attach = on_attach,
        on_init = on_init,
        capabilities = capabilities,
      }
    end
    ```

#### Expected Behavior
`gopls` should appear in the list of active LSP servers when running `:LspInfo`.

#### Actual Behavior
`gopls` does not appear in the list of active LSP servers when running `:LspInfo`.
<img width="604" alt="image" src="https://github.com/NvChad/NvChad/assets/86879002/f90399e9-8079-40d6-873d-521bcd740b58">

#### Additional Information
- Neovim version: 0.10.0
- NvChad version: 2.5
- OS: MacOS

Please let me know if there are any additional configurations or steps needed to properly set up `gopls` with NvChad.

**Comment by siduck** [comment]
please uncomment the lsp  code from your plugins file :/
