### ISSUE TITLE
vscode_colored statusline theme not working properly

### ISSUE THREAD

**Issue by HayKor** [siduck76/NvChad#2888]
So, I set my statusline theme to vscode_colored, as it says in the docs:

`M.ui = {
    theme = "catppuccin",
    statusline = {
        theme = "vscode_colored",
        separator_style = "default",
        -- order = nil,
        -- modules = nil
    },
`
I expected this:
 
![06⁄11⁄24_13-07](https://github.com/NvChad/NvChad/assets/63199429/291f53f6-b139-40ab-af26-958b0fad5784)

But I got this:

![06⁄11⁄24_13-03](https://github.com/NvChad/NvChad/assets/63199429/c47fa667-4ce1-4446-9365-e285b31bdeee)

OS: Ubuntu 22.04, Terminal: Kitty

**Comment by siduck** [comment]
that screenshot is old, that UTF stuff and the {} ft has been removed. but diagnostics and diffs will show

![image](https://github.com/NvChad/NvChad/assets/59060246/ebc1f713-81b5-4426-9544-96b8349a34c1)


but if there are no diagnostics/u are not on git repo then it wont
