### ISSUE TITLE
Github Copilot , Lazy.lua  NvChad

### ISSUE THREAD

**Issue by ghost** [siduck76/NvChad#2900]
I'm trying to install github copilot with nvim. 

When i add these lines into lazy.lua in order to be able to install it with LazyExtras

require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.coding.copilot" },
    { import = "plugins" },
  },
})

My whole NvChad configuration breaks with the following errors 

Error detected while processing /home/tasmaniandaemon/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/tasmaniandaemon/.config/nvim/init.lua:35
: module 'nvchad.autocmds' not found:
no field package.preload['nvchad.autocmds']
cache_loader: module nvchad.autocmds not found
cache_loader_lib: module nvchad.autocmds not found
no file './nvchad/autocmds.lua'
no file '/usr/share/luajit-2.1/nvchad/autocmds.lua'
no file '/usr/local/share/lua/5.1/nvchad/autocmds.lua'
no file '/usr/local/share/lua/5.1/nvchad/autocmds/init.lua'
no file '/usr/share/lua/5.1/nvchad/autocmds.lua'
no file '/usr/share/lua/5.1/nvchad/autocmds/init.lua'
no file './nvchad/autocmds.so'
no file '/usr/local/lib/lua/5.1/nvchad/autocmds.so'
no file '/usr/lib/lua/5.1/nvchad/autocmds.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './nvchad.so'
no file '/usr/local/lib/lua/5.1/nvchad.so'
no file '/usr/lib/lua/5.1/nvchad.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
-- More --

**Comment by siduck** [comment]
not  nvchad issue :/ 

You removed nvchad's main repo as plugin then why do you except all `nvchad.*` modules to work?
