### ISSUE TITLE
Vertical term width

### ISSUE THREAD

**Issue by Frusadev** [siduck76/NvChad#2901]
**Bug description**
The vertical terminal is very small (in width) when i launch it.
I've noticed it takes the same height as the horizontal one.

**To Reproduce**
Have the latest version of nvchad starter.
Alt-v.
I've only encountered this bug on the latest version of nvchad starter.

**Expected behavior**
The terminal should be wider.

**Screenshots**
![Screenshot from 2024-06-20 07-47-22](https://github.com/NvChad/NvChad/assets/81917636/14d216b5-b8d7-47e5-93e6-f2d868640248)

**Desktop**
 - Operating System: Fedora workstation 40
 - Terminal: Wezterm
 - Version of Neovim: NVIM v0.10.0

**Additional context**
Maybe is there anything i need to change in mapping Alt-v ?

**Comment by Frusadev** [comment]
I just needed to edit chadrc.lua

**Comment by saikete** [comment]
Hello! I also encountered the same problem, but I don't know how to solve it. I have referred to the ui.term settings on the official website but it still doesn't work. I want to know how you solved it. thanks

**Comment by siduck** [comment]
@saikete show your code

**Comment by saikete** [comment]
<img width="1073" alt="image" src="https://github.com/NvChad/NvChad/assets/45237450/d3ff274f-c1e1-4e6b-8816-35b87f2484ff">
I referred to the default configuration of nvconfig.lua and the configuration reference in the previous custom directory, but neither worked. I think I have configured something wrong, but I can't find any code I can refer to.

**Comment by siduck** [comment]
term isnt a part of ui table anymore, so your code should be M.term

**Comment by saikete** [comment]
Thank you for taking the time to reply! The problem has been solved.
