### ISSUE TITLE
Some Icons not displaying properly in filetree | Powershell

### ISSUE THREAD

**Issue by nat3Github** [siduck76/NvChad#2903]
- using latest nvchad config, latest neovim 0.10
- using latest JetbrainsMono NerdFont vers. 2.304 from https://www.nerdfonts.com/font-downloads

![image](https://github.com/NvChad/NvChad/assets/121395237/d19ec142-13d6-492c-af32-e2e6c9f60e7f)

**Comment by siduck** [comment]
not a nvchad issue, try another terminal.

**Comment by nat3Github** [comment]
the issue is not related to the terminal but rather the nerdfont used and more specific the icons beeing used by nvchads plugins. in this case a problem with the filetree plugin. fine if you dont consider this to be nvchads responsibility. 
there was a similar issue on lunarvim https://github.com/LunarVim/LunarVim/issues/4107

**Comment by siduck** [comment]
@nat3Github  that isnt nvchad issue cuz you're still using old nerdfonts version. Try the latest i.e  [v3.2.1](https://github.com/ryanoasis/nerd-fonts/releases/latest)

**Comment by nat3Github** [comment]
thank you for your help. i deinstalled all nerd fonts from the computer installed the latest v.3.2.1
this is using JetBrainMono NFM: there are still symbols missing.
![image](https://github.com/NvChad/NvChad/assets/121395237/76ff3a98-9325-41c3-a68e-2095a41cae94)

**Comment by nat3Github** [comment]
this is using Zed Mono NFM. same symbols:
![image](https://github.com/NvChad/NvChad/assets/121395237/0d5ea4b6-6cc8-4c65-a750-4c9936a5d609)

**Comment by siduck** [comment]
can you try it on sane terminals like alacritty/kitty/wezterm?

**Comment by nat3Github** [comment]
in alacritty it works, so you were right after all! :)

thanks! ill just use that for nvim for now. but a pita that it doesnt work natively, do you know the reason why?
maybe you could leave a note on the requirements of the nvchad site. to spare some confusion for new users

**Comment by nat3Github** [comment]
nevermind. scroling in floating windows is not possible. it just scrolls the whole window :(
this is not usable. ill maybe try the other ones or just live with it because this trial and erroralready does take a lot of time.

**Comment by siduck** [comment]
@nat3Github  how are u scrolling? i use  mouse and it works

**Comment by nat3Github** [comment]
im scrolling with a trackpad using a laptop. are you using alacritty with powershell? i imagine it could differ with other shells or os.

**Comment by siduck** [comment]
> im scrolling with a trackpad using a laptop. are you using alacritty with powershell? i imagine it could differ with other shells or os.

no i use st terminal + mksh, you should seek help in our discord server as there are many windows users there, i use linux so cant be of help :face_with_head_bandage:

**Comment by nat3Github** [comment]
will do. thank you!
