### ISSUE TITLE
nvcheatsheet attempt to index failed 'cheatsheet'

### ISSUE THREAD

**Issue by 4ry1337** [siduck76/NvChad#2908]
After updating nvchad plugins too latest version, base46b plugin started to throw this error:

...vim/lazy/base46/lua/base46/integrations/nvcheatsheet.lua:20: attempt to index field 'cheatsheet' (a nil value)
 

![image](https://github.com/NvChad/NvChad/assets/52571621/6c279fae-401c-4d97-816b-8adb16d92d05)
![image](https://github.com/NvChad/NvChad/assets/52571621/cfa18909-0aa9-4a78-9a79-7cc54dce37bf)

 Operating System: Arch Linux
 Terminal: Kitty
 Version of Neovim: v.0.10.0

**Comment by siduck** [comment]
https://github.com/NvChad/base46/commit/d4ffecc3e1a34f3ed9af6362529552eee79e57c2

**Comment by siduck** [comment]
run lazy sync again

**Comment by 4ry1337** [comment]
problem resolved, thx
