### ISSUE TITLE
 nvim-tree fit all elements to the view

### ISSUE THREAD

**Issue by mairm1340** [siduck76/NvChad#2912]
Hi
I am new to nvim and learnign nvim .

some of the file names are big for the project i am working on.

When I see them in Nvm tree it does not fit

based on the google search it seems that i need to configure view = { adaptive_size = true } but I dont find the way to do that while using nvchad...

can someone assist me...

**Comment by siduck** [comment]
all you have to do is override nvimtree opts 

I wont tell you the answer directly as it'll spoil you and you wont learn anything!

check the examples here https://nvchad.com/docs/config/plugins/

**Comment by mairm1340** [comment]
I did this and i get errors

-- ~/.config/nvim/lua/chadrc.lua

---@type ChadrcConfig
local M = {}

M.ui = {
  theme = "onedark",
}

M.plugins = {
  override = {
    ["kyazdani42/nvim-tree.lua"] = {
      view = {
        adaptive_size = true,
      },
    },
  },
}

return M


-- ~/.config/nvim/lua/plugins/init.lua

local chadrc = require("chadrc")

local overrides = chadrc.plugins.override

return {
  {
    "stevearc/conform.nvim",
    -- event = 'BufWritePre', -- uncomment for format on save
    config = function()
      require "configs.conform"
    end,
  },
  
  {
    "kyazdani42/nvim-tree.lua",
    config = function()
      print("Setting up nvim-tree with overrides")
      require("nvim-tree").setup(overrides["kyazdani42/nvim-tree.lua"])
    end,
  },

  -- other plugins
}


-- ~/.config/nvim/init.lua

vim.g.base46_cache = vim.fn.stdpath "data" .. "/nvchad/base46/"
vim.g.mapleader = " "

-- bootstrap lazy and all plugins
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
  local repo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system { "git", "clone", "--filter=blob:none", repo, "--branch=stable", lazypath }
end

vim.opt.rtp:prepend(lazypath)

local lazy_config = require "configs.lazy"

-- load plugins
require("lazy").setup({
  {
    "NvChad/NvChad",
    lazy = false,
    branch = "v2.5",
    import = "nvchad.plugins",
    config = function()
      require "options"
    end,
  },

  { import = "plugins" },
}, lazy_config)

-- load theme
dofile(vim.g.base46_cache .. "defaults")
dofile(vim.g.base46_cache .. "statusline")

require "nvchad.autocmds"

vim.schedule(function()
  require "mappings"
end)

**Comment by siduck** [comment]
M.plugins is useless. please use nvchad v2.5 :(

**Comment by siduck** [comment]
```lua
{  
  "kyazdani42/nvim-tree.lua",
   opts = {
         view = { adaptive_size = true }, 
    }
}
```

please read all of nvchad.com, nvchad isnt for newbies who arent willing to learn and are ignorant.
