### ISSUE TITLE
Use terminal color scheme

### ISSUE THREAD

**Issue by plasmoduck** [siduck76/NvChad#2917]
Is there an easy way to use my terminals 16 colors scheme? I am using 'Gruvbox Material Dark Soft' from Kitty's themes. If not, do you think you could add this theme to nvchad?

**Comment by siduck** [comment]
@plasmoduck  gruvchad is close to it,   base46 wont support terminal themes.

**Comment by siduck** [comment]
you can however edit colors of any theme

**Comment by plasmoduck** [comment]
What is the location on the theme so I can edit it?

**Comment by siduck** [comment]
https://nvchad.com/docs/config/theming/#customize_themes

**Comment by plasmoduck** [comment]
Please can you add this theme https://github.com/MayushKumar/base16-gruvbox-material-scheme/blob/master/gruvbox-material-dark-soft.yaml

https://github.com/sainnhe/gruvbox-material/blob/master/doc/gruvbox-material.txt

Also where is the location of existing theme files on the computer? The page you linked doesnt stay where they are.

**Comment by siduck** [comment]
@plasmoduck  we have gruvchad already

https://github.com/NvChad/base46/tree/v2.5/lua/base46/themes
