### ISSUE TITLE
LSP not workingNot able to go to definition using gD or gd and gr basically tries to replace

### ISSUE THREAD

**Issue by abhilashkr31** [siduck76/NvChad#2926]
**Describe the bug**
I use NVIM and have the compile_commands.json file as well. Still not able to jump to definition or see the references.

**To Reproduce**
1. Go to 'any_function' in your repo
2. Press gR which was LSP shortcut to find the references
3. The key map starts to replace rather than trying to find references.

**Expected behavior**
We should find references of the function in whole project.

**Desktop (please complete the following information):**
 - Operating System: Linux
 - Terminal: CMD for ssh to linux machine
 - Version of Latest 0.10

**Additional context**

**Comment by siduck** [comment]
you have not shown any video. i hope you are using our on_attach for your lsps cuz it defines lsp mappings too.
