### ISSUE TITLE
Plugins not loaded in NvChad

### ISSUE THREAD

**Issue by kmr-ankitt** [siduck76/NvChad#2927]
**Describe the bug**
I cant figure out why my installed plugins are not loaded.

**To Reproduce**
1. Install any plugin
2. Run `:Lazy`
3.  I see that particular plugin as not loaded

**Expected behavior**
I should have loaded the plugin perfectly.

**Screenshots**
![image](https://github.com/user-attachments/assets/386b64a4-3fb6-4a37-a3dd-a21fff4489fc)
<details><summary> current lua/plugins/init.lua </summary>
<p>

return {
```
  {
    "stevearc/conform.nvim",
    -- event = 'BufWritePre', -- uncomment for format on save
    config = function()
      require "configs.conform"
    end,
  },

  {
   "supermaven-inc/supermaven-nvim",
    config = function()
    require("supermaven-nvim").setup({
      keymaps = {
        accept_suggestion = "<Tab>",
        clear_suggestion = "<C-]>",
        accept_word = "<C-j>",
      },
      ignore_filetypes = { cpp = true },
      color = {
        suggestion_color = "#ffffff",
        cterm = 244,
      },
      log_level = "info", -- set to "off" to disable logging completely
      disable_inline_completion = false, -- disables inline completion for use with cmp
      disable_keymaps = false  -- disables built in keymaps for more manual control
    })
    end,
  },
```
</p>
</details> 

**Desktop (please complete the following information):**
 - Operating System - Arch linux
 - Terminal - Alacritty
 - Version of Neovim - v0.10.0

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/ddd438c7-f1ce-435e-8ea3-b0303e017cc5)


so either lazy load or use lazy=false
