### ISSUE TITLE
Change the default branch back to 2.0 for now, because ...

### ISSUE THREAD

**Issue by martin-braun** [siduck76/NvChad#2931]
- The branch is not ready, i.e. missing `.gitignore` and probably more issues
- There is no migration guide from 2.0 to 2.5, my configuration doesn't work out of the box, so I was looking for a migration guide without luck.

**Comment by siduck** [comment]
https://nvchad.com/news/v2.5_release

**Comment by siduck** [comment]
if your config is not more then 10k LOC then share it, i could migrate it for you

**Comment by martin-braun** [comment]
@siduck Thanks, I visited the website, maybe link the migration guide in the docs section to make it easier to find? Somewhere here? https://nvchad.com/docs/quickstart/install

Thanks for your offer. https://github.com/martin-braun/CocChad has only 3k LOC, but you absolutely don't have to do that. I will look into migrating my configuration in the near future. There are definitely more things to consider, since my configuration branches a lot off NvChad.

Maybe it is time for me to build my own, since I undo a lot of decisions that NvChad does, which isn't meant to be judgmental. I had an outstanding ride with NvChad and it really helped me to enjoy Neovim without having to go to a massive learning curve.

Thank you for that! ❤️

**Comment by siduck** [comment]
Coc has spoiled & deviated you from Neovim's native lua stuff :smile: 

migration guide is in this https://nvchad.com/news/v2.5_release

**Comment by martin-braun** [comment]
@siduck Ikr, I can't help it, it works too well for me and gets the job done. If I ever free myself from node, I will join the native-movement. 😇

About the link, of course I didn't read the news, as always. I'm guilty, thanks brother.
