### ISSUE TITLE
Unable to install base46 and ui plugins.

### ISSUE THREAD

**Issue by DarkiCraft** [siduck76/NvChad#2937]
**Describe the bug**
When running NVChad for the first time, or subsequent times, it fails to clone `NVChad/base46/` and `NVChad/ui/` and the following error pops up: `Remote branch v2.5 not found in upstream origin`

**To Reproduce**
1. Backup/remove current Neovim configurations.
2. Clone the `NVChad/starter/` repo.
3. Run `nvim`.
4. `base46` and `ui` plugins fail to install.

**Expected behavior**
All plugins install without problems.

**Screenshots**

![Screenshot 2024-07-20 130221](https://github.com/user-attachments/assets/063185fc-2d1b-4552-9c8c-7a16f241c732)
**Desktop:**
 - Operating System: Windows 10 22H2 (OS Build 19045.4651)
 - Terminal: Windows Terminal (1.20.11781.0) running pwsh
 - Version of Neovim: v0.10.0 Release
 - Version of Lua: LuaJIT 2.1.1713484068

**Additional context**

I have reinstalled Git multiple times. Cloning the respective repos on their own in some arbitrary folder works fine:

![Screenshot 2024-07-20 131155](https://github.com/user-attachments/assets/4e60a8f1-9fe0-4f6c-877b-2bf4b0cd3409)
Also I would mention that I am just starting out with Neovim. I have little experience with Git and similar applications.

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/da37bbe3-b29e-44e9-a326-191dee32ab63

unable to reproduce....

**Comment by siduck** [comment]
this is the weirdest issue i've ever seen, those branches exist and are default branches!

**Comment by DarkiCraft** [comment]
So I tried to do some more things here. Git just doesn't want to find the v2.5 branches of the repos.

![Screenshot 2024-07-21 125330](https://github.com/user-attachments/assets/5e877793-dbf6-485d-87dc-93a93c7eced0)

![Screenshot 2024-07-21 125506](https://github.com/user-attachments/assets/f3328708-2fa6-4ef6-b41a-3fbfa9e3ce1a)

![Screenshot 2024-07-21 125611](https://github.com/user-attachments/assets/a008c1e3-f6d2-492b-92e6-6c525f25e71b)

But anyway, thanks for your help still!

**Comment by siduck** [comment]
just use nvchad normally ! @DarkiCraft  are you in china or something?  

please try on another OS like linux :/ or wsl

**Comment by DarkiCraft** [comment]
Uh, no I am in Pakistan right now. Thank you for your help.

**Comment by siduck** [comment]
> Uh, no I am in Pakistan right now. Thank you for your help.

no need to thank me as my help didnt fix your issue, please seek help in our discord server, someone might be able to help! or DM on any of my socials ( link on my github profile )
