### ISSUE TITLE
Attention! Do you want all chadrc theming options in base46 table? Urgent Feedback needed.

### ISSUE THREAD

**Issue by siduck** [siduck76/NvChad#2938]
Hi everyone! I was thinking that it should be better to keep all theme related options in the base46 table of chadrc.

Current table structure of chadrc is like : 

```lua
{
   ui = {
       theme = "",
        --  more theme related...
       ...
       statusline =  {},
       tabufilne  = {}
       ...
   },
   
   term = {},
   base46 ={}
}
```
 
So after moving the theme* related options to base46 , it'll look like this : 
![image](https://github.com/user-attachments/assets/61046757-ac18-472d-beea-2771be4e4c15)

it makes more sense to me. Btw if we make this change then  I'll still keep the old ui way for few months. Obviously this change is a breaking one, but it wont stop your neovim from functioning, people those who use those options, just need to move those options in base46 table. I think this is the last piece to make chadrc configuration perfect

What do you think? if yes then react with :+1:  or :-1:

**Comment by BrunoKrugel** [comment]
>  Btw if we make this change then I'll still keep the old ui way for few months.

If we keep this, then I have no issues, It will be more organized.
Also, nice screen for feedback.

**Comment by ProgmRuanSilva** [comment]
For me it's ok.

**Comment by danielrs** [comment]
**Disclaimer:** I'm not super familiar with all configuration fields and conventions, so here are just my two cents:

As an user, it's not clear to me what the `base46` field describes. From looking at the configuration I would assume is like `base16` or `base30` but has more colors / options? Maybe a more semantically correct option like `styling`, `style`, `appearance`, `theming`, `colors`, etc; would make more sense and be more "future" proof.

Just for reference, what's the reasoning behind the `base46` name?

**Comment by siduck** [comment]
@danielrs base46 is the name of the plugin, so the options in its table will obviously be related to base46 and they will the word "theme" because base46 is responsible for theming in nvchad. 

check the default chadrc file here https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua

just the theme related options from M.ui will be moved to M.base46

**Comment by hriva** [comment]
It's fine :+1:

**Comment by danielrs** [comment]
@siduck Gotcha, that makes sense then!

**Comment by RomaLzhih** [comment]
As long as I can keep all personal configs unchanged, that is okay.

**Comment by hkhrithik007** [comment]
kinda no its good how it is

**Comment by dee-kryvenko** [comment]
There needs to be a way to alert users in some way of these changes. It is good to keep it backward compatible for a month, but what does it matter if a user had no idea? It will just delay the inevitable. I think there needs to be some kind of alert visible to the user and highly annoying.

**Comment by siduck** [comment]
> There needs to be a way to alert users in some way of these changes. It is good to keep it backward compatible for a month, but what does it matter if a user had no idea? It will just delay the inevitable. I think there needs to be some kind of alert visible to the user and highly annoying.

after i remove the support for the fallback, i'd just alert the user with this change whenever he tries to change his theme etc

**Comment by siduck** [comment]
> kinda no its good how it is

I think you dont understand the change, those options are not related to the ui field at all :/ 

ui field must only be for ui related customization . ui != theme!

base46 is responsible for theming, more options are gonna get added , like italic support etc. so I think its better to move it now to base46 than later 

in a nutshell ( left is before, right is after ): 
![image](https://github.com/user-attachments/assets/21cff9c9-3cf5-4253-9829-37d3b159684e)

**Comment by dee-kryvenko** [comment]
> > There needs to be a way to alert users in some way of these changes. It is good to keep it backward compatible for a month, but what does it matter if a user had no idea? It will just delay the inevitable. I think there needs to be some kind of alert visible to the user and highly annoying.
> 
> after i remove the support for the fallback, i'd just alert the user with this change whenever he tries to change his theme etc

Sounds like a solid plan and thanks for all your work BTW!

**Comment by PedAltuve** [comment]
Good for me :+1:

**Comment by IstiCusi** [comment]
Thx -- absolutely fine. May I add a question: I realized, that the visual mode highlighting is for most themes quite difficult to see. Is there a way to change the "transparency". Thanks a lot for all the work.

**Comment by LeonardoMor** [comment]
Looks good to me

**Comment by siduck** [comment]
> Thx -- absolutely fine. May I add a question: I realized, that the visual mode highlighting is for most themes quite difficult to see. Is there a way to change the "transparency". Thanks a lot for all the work.

https://nvchad.com/docs/config/theming/

**Comment by RPKuk** [comment]
it's ok 👍

**Comment by SodaSiz** [comment]
It's OK

**Comment by lucasws1** [comment]
sure, it's ok. thanks for your good work :)

**Comment by jaeheonji** [comment]
The highly customizations with good documentation is welcome 👍

**Comment by trongthanh** [comment]
IMO, it makes sense to move all theming-related fields to one table, just the key name `base46` is confusing and not intuitive...

**Comment by siduck** [comment]
@trongthanh i dont see why's base46 theme name confusing,  its the name of our theme plugin....

**Comment by jacobdcastro** [comment]
So long as it has good documentation, I'm all for it

**Comment by siduck** [comment]
> So long as it has good documentation, I'm all for it

its just that the theme related fields in M.ui are being moved to M.base46, idk how hard it can get to grasp it!!

anyways soon docs for ui/base46 will release so users dont have to go to nvchad.com

**Comment by xarthurx** [comment]
For `ui modules` such as `nv_dash` will remains in the `ui` ?

**Comment by siduck** [comment]
> For `ui modules` such as `nv_dash` will remains in the `ui` ?

obviously

**Comment by OBLIXi-ON** [comment]
It's fine! BTW what's the difference between `base46` and `ui`?

**Comment by siduck** [comment]
> It's fine! BTW what's the difference between `base46` and `ui`?

ui for all the ui stuff u see on nvchad like statusline, tabline etc
base46 for theming

https://github.com/NvChad/base46
https://github.com/NvChad/ui

**Comment by Turbid** [comment]
it's ok

**Comment by jono3030** [comment]
Only saw the notification screen now. Seems like a good idea to me!

**Comment by SophaHum** [comment]
For laravel file blade.php theme not support

**Comment by siduck** [comment]
> For laravel file blade.php theme not support

wym? just install the required treesitter parsers
