### ISSUE TITLE
clean install on rocky linux doesnt work.

### ISSUE THREAD

**Issue by NicTanghe** [siduck76/NvChad#2941]
Failed to run `config` for indent-blankline.nvim
...e/nvim/lazy/indent-blankline.nvim/lua/ibl/highlights.lua:20: attempt to call field 'nvim_get_hl' (a nil value)
# stacktrace:
  - /indent-blankline.nvim/lua/ibl/highlights.lua:20 _in_ **get**
  - /indent-blankline.nvim/lua/ibl/highlights.lua:29 _in_ **setup_builtin_hl_groups**
  - /indent-blankline.nvim/lua/ibl/highlights.lua:55 _in_ **setup**
  - /indent-blankline.nvim/lua/ibl/init.lua:41 _in_ **setup**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - /NvChad/lua/nvchad/plugins/init.lua:46 _in_ **config**

**Expected behavior**
evryhting works

**Screenshots**

**Desktop (please complete the following information):**
-rocky 9.4
-gnome classic x

**Additional context**

**Comment by siduck** [comment]
unable to reproduce

rm -rf .local/share/nvim and then install

I hope you're using neovim  v0.10

**Comment by NicTanghe** [comment]
I`m pretty sure the problem was indeed that sorry to bother.
