### ISSUE TITLE
Please provide support to toggle in tablinebuff with buffer numbers given by NvChad

### ISSUE THREAD

**Issue by xander412** [siduck76/NvChad#2942]
Previously I used to toggle between tabs with <Leader> + tabnumber. But as I moved to neovim , there is no shortcut for toggling between buffers in tablinebuff. Only forward and backward functionalities are there. If try to use :buffer <buffer number>, even the file explorer buffer is being counted and giving unpredictable behaviour. So this is a requisition for key mappings for toggling between tabufline buffers. Thank you.

**Comment by siduck** [comment]
https://nvchad.com/docs/api#gototab
