### ISSUE TITLE
NVChad 2.0 Theme Switcher Not Saving Theme

### ISSUE THREAD

**Issue by n-morgan** [siduck76/NvChad#2947]
**Describe the bug**
After using theme switcher and saving the file the theme applied is reverted. 

**To Reproduce**
1. do <space> <t> <h> 
2. enter
3. do :w to save file 

**Expected behavior**
theme remains after :w ; however it reverts back to default

**Screenshots**
<img width="1728" alt="After" src="https://github.com/user-attachments/assets/8d7a8e7a-9fa4-4ada-82a4-8062c29445a5">
<img width="1728" alt="Before" src="https://github.com/user-attachments/assets/e1269a0d-efd3-4f5b-bc5b-f767c85df987">

**Desktop (please complete the following information):**
 - MacOS Sonoma 14.5
 - Iterm2
 - Neovim 2.0

**Additional context**
Error Message: 

E5108: Error executing lua: .../velocity/.local/share/nvim/lazy/ui/lua/nvchad/utils.lua:27: attempt to index local 'file' (a nil value)
stack traceback:
        .../velocity/.local/share/nvim/lazy/ui/lua/nvchad/utils.lua:27: in function 'replace_word'
        .../share/nvim/lazy/ui/lua/telescope/_extensions/themes.lua:68: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:293: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:292>
Press ENTER or type command to continue

**Comment by siduck** [comment]
use v2.5
