### ISSUE TITLE
When deleting currently opened file, nvim-tree takes the whole width

### ISSUE THREAD

**Issue by mrpmohiburrahman** [siduck76/NvChad#2950]
**Describe the bug**
If I delete an opened file, the nvim-tree takes up full width, and the whole tree goes to the left.

But I was trying to make it behave like vs-code with nvim-tree ( file explorer ) on the right side.

**To Reproduce**
1. Refactor nvim-tree config, so that it will show on the right side.
2. Create a file and open it.
3. Now delete file from nvim-tree
4. Now nvim-tree will take the whole width as there are no buffer left, and the whole tree goes to the left side.

**Expected behavior**
The nvim-tree should be on the right side, no matter what.
May be we can add a "no name" file when the current opened file is being deleted or check if there is any other buffer ( file ) opened then switch to that buffer ( file ).

**Screenshots**

https://github.com/user-attachments/assets/18df0ed6-3b87-4e81-83fe-e0e87d54ceae

**Desktop (please complete the following information):**
 - Operating: Mac OS
 - Terminal: warp
 - Version of Neovim: 0.10.1

**Additional context**
After 2 days of configuring, I am stuck on this roadblock from using NvChad as a replacement for vscode.
Please, help.

**Comment by siduck** [comment]
nothing i can do about as this isnt nvchad issue

**Comment by mrpmohiburrahman** [comment]
> nothing i can do about as this isnt nvchad issue

@siduck, Got it. But can we have a work around? 

Like, Is it possible to place a "no name" file in place of currently deleted file, if there is no other file is opened?
or go to another opened file?

I am new to neovim, but I am trying to do that, any kind of hint or direction will help me a lot.

**Comment by siduck** [comment]
i tried it for you, but the file deletes after pressing "y"which we got no control of!

![image](https://github.com/user-attachments/assets/379ad232-6d3f-44cf-87eb-cef43c06b388)

**Comment by siduck** [comment]
@alex-courtis whats the best solution to this, without adding any plugins?

**Comment by alex-courtis** [comment]
Window removal is working as intended: nvim will delete the window when there are no remaining buffers.

Adding a no name new buffer to the window before deleting does sound like a solution. That's a bit tricky (edge cases), so I use [qpkorr/vim-bufkill](https://github.com/qpkorr/vim-bufkill) to do this.

You could do something like
```vim
:BD!
:lua require("nvim-tree.api").fs.remove()
```

**Comment by siduck** [comment]
> Window removal is working as intended: nvim will delete the window when there are no remaining buffers.
> 
> Adding a no name new buffer to the window before deleting does sound like a solution. That's a bit tricky (edge cases), so I use [qpkorr/vim-bufkill](https://github.com/qpkorr/vim-bufkill) to do this.
> 
> You could do something like
> 
> ```viml
> :BD!
> :lua require("nvim-tree.api").fs.remove()
> ```

hmm but if BD is ran with nvimtree in focus  then it'll close nvimtree.  

@mrpmohiburrahman 
```lua
:lua require("nvchad.tabufline").close_buffer()   require("nvim-tree.api").fs.remove()
```

**Comment by alex-courtis** [comment]
> hmm but if BD is ran with nvimtree in focus then it'll close nvimtree.

Yup, it's a tricky one. I ran the above two commands from the buffer's window. You could do something like finding the buffer number(s) for that file and focusing that window, but that's getting very convoluted and utterly impractical.

It's quite possible to add the desired functionality to nvim-tree, however edge cases etc.

Please raise a [Feature Request](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.md&title=) with the various use/edge cases and how you expect them to behave.

**Comment by siduck** [comment]
> Please raise a feature Request with the various use/edge cases and how you expect them to behave.

done https://github.com/nvim-tree/nvim-tree.lua/issues/2861

btw i dont think there are other edgecases, this happens only when there's 1 listed buffer
