### ISSUE TITLE
Trouble installing on WSL Ubuntu

### ISSUE THREAD

**Issue by codr1** [siduck76/NvChad#2952]
**Problem**

On an absolutely fresh Ubuntu running under Windows WSL, with a fresh NeoVim install from tarball, I get the following error every time I run :MasonInstall for the very first time.

Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Wrong number of arguments
stack traceback:
[C]: in function 'cmd'
.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/l
azy/core/handler/cmd.lua:16>

**Steps to reproduce**
Fresh install on a fresh Ubuntu under WSL.  Download and install NeoVim tarball.  Run the NvChad installation git command.  (This is a fresh install, so nothing to clean up) Start NeoVim.  Type :MasonInstall

**Expected behavior**
Don't get an error

**Desktop (please complete the following information):**
 - Windows 11
 - Windows Terminal / Ubuntu
 - Version of Neovim - 10.01

**Comment by siduck** [comment]
that looks like a lazy.nvim error

please rm -rf .local/share/nvim and then install. I hope your git version is the latest..

**Comment by codr1** [comment]
For posterity - this was a skills issue on my part.
