### ISSUE TITLE
<leader>/ doesn't work in normal and visual mode

### ISSUE THREAD

**Issue by adilJamshad** [siduck76/NvChad#2955]
**Describe the bug**
Whenever I want to comment a line or any piece of code `<leader>/` doesn't work on mac pro m1.

**To Reproduce**
Just try to comment any line on mac.

**Expected behavior**
It should comment the line

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Terminal: Warp
 - Version of Neovim: v0.9.5

**Comment by siduck** [comment]
hi,update to v0.10 of neovim! cuz we now use the inbuilt feature of commenting, rather than a plugin

**Comment by oobleck** [comment]
For anyone else looking into this, I was on v0.10.0 (pre-release) and `gcc` (`<leader>/`) still didn't work. I upgraded to v0.10.1 (Linuxbrew) and then commenting worked.

Before:
```
❯ nvim --version
NVIM v0.10.0-dev-2382+g478273a42-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
```

After:
```
❯ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```
