### ISSUE TITLE
Disable all proprietary keybindings

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [siduck76/NvChad#2956]
**Is your feature request related to a problem? Please describe.**
I often find myself hunting down the keymaps to delete / I don't feel comfortable with that NvChad set for me.

**Describe the solution you'd like**
Use M.mappings = { disabled = true } in chadrc to prevent nvchad from setting any mapping. 

Or actually what I would enjoy even more is for you to throw all proprietary mappings into the user config file, lua/mappings.lua, so I could manually walk through it, remove the ones I don't like and have everything under version control. However, the most idiomatic way would probably be to have something like (I see most other plugins have something like this):

```
 M.defaults = {
    mappings = {
      n = {
        ["<C-n>"] = ...
      }
    }
  },
```

**Describe alternatives you've considered**
vim.keymap.del('n', <A-v>), ... is just tedious if you have a lot and want to start from scratch.

**Comment by siduck** [comment]
hi @MartyMcFlyInTheSky , i suggest you to use nvchad v2.5 

https://github.com/NvChad/starter/blob/main/init.lua#L36

and you can just delete that line

**Comment by siduck** [comment]
https://nvchad.com/news/v2.5_release/

**Comment by MartyMcFlyInTheSky** [comment]
Very cool, my eyes didn't catch that line.

Btw. does version 2.5 also allow to disable the ui-internal term module? Something like `M.ui.term.disable = true`?

**Comment by siduck** [comment]
ui.term?  its not enabled by default i.e its code wont run unless its functions get called. 

And you said that you're disabling all mappings so the term mappings will also get erased

**Comment by MartyMcFlyInTheSky** [comment]
Ok thanks :+1:
