### ISSUE TITLE
plugins.lua does not install plugins despite following instructions

### ISSUE THREAD

**Issue by Veltair-D** [siduck76/NvChad#2957]
I have installed NvChad multiple times by now. I keep having the same issue. I have been trying to install a plugin to no avail. At this point I even tried to use one of the samples from the docs but it is still not working.

**To Reproduce**
1. Fresh NvChad install
2. Create plugins.lua file in the lua/plugins directory.
3. Create the plugins function
```
local plugins = {
{
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {"html", "css", "bash"},
    },
  },
}
return plugins
```
4. run :MasonInstallAll
5. Plugins do not work

Extra:
Did not work with rust-analyzer with the following code 
```
local plugins = {
{
"williamboman/mason.nvim",
opts = {
  ensure_installed = {
    "rust-analyzer",
    },
  },
}
```
**Desktop:**
 - Operating System: OSX
 - Terminal: Alacritty
 - Version of Neovim v0.10.1

**Comment by siduck** [comment]
please enable rust analyzer in your lspconfig. then masoninstall command will pull it up 
for explicitily setting it https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L85
