### ISSUE TITLE
Grammar autocompletion in NvChad

### ISSUE THREAD

**Issue by Anonymous-ABC-XYZ** [siduck76/NvChad#2958]
**Is your feature request related to a problem? Please describe.**
How do I add this:  [https://github.com/octaltree/cmp-look](url) in order to enable options for english autocompletion in NvChad, for md and txt file?
**Describe the solution you'd like**
I would like to know how to configure the NvChad pre-built config to add this and enable functionalities.

**Screenshot**
Currently this:
![image](https://github.com/user-attachments/assets/9c81e59a-4fb9-474d-9c5a-2c90eae5e310)

I want an option to display all possible options like hello as shown in cmp-look, but with the same styling and lua snips as in the default NvChad setup:
![image](https://github.com/user-attachments/assets/a8a1fe07-8039-4ac1-b26a-6c32ef5a4cc6)

I'm incredibly new to using nvim as an IDE (day 2!), so I would appreciate any help you can give me!

**Comment by siduck** [comment]
```lua
{
    "hrsh7th/nvim-cmp",
    dependencies = {
      "octaltree/cmp-look",
    },

    config = function(_, opts)
      table.insert(opts.sources, {
        name = "look",
        keyword_length = 2,
        option = {
          convert_case = true,
          loud = true,
        },
      })

      require("cmp").setup(opts)
    end,
  },
```
