### ISSUE TITLE
vscode normal theme in nvchad

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [siduck76/NvChad#2959]
I got so accustomed to the vscode default theme that I would like to see it also in nvchad. Also I need to switch around often between my colleagues and myself so it would be a great benefit to not always have to adapt to a different syntax highlighting.

![image](https://github.com/user-attachments/assets/98b9b69e-43a6-43c4-a569-7f27ff6eddda)

**Comment by siduck** [comment]
its available in  our themes, use it.

**Comment by MartyMcFlyInTheSky** [comment]
Are you sure? I'm not talking about vscode_dark. This one doesn't look like vscode at all:

nvchad (vscode_dark):
![image](https://github.com/user-attachments/assets/66b7e5dc-fbb4-44e4-96be-0f81386852aa)
vscode (the theme is called "Dark modern", but this is also not available)
![image](https://github.com/user-attachments/assets/7a8788b9-f306-4782-8d9c-6a4ae6b6531c)

**Comment by siduck** [comment]
@MartyMcFlyInTheSky  you are free to improve our vscode theme! and send PR

**Comment by MartyMcFlyInTheSky** [comment]
I had a quick look but I can't make heads and tails on what those color names originally refered to:

```
M.base_30 = {
  white = "#dee1e6",
  darker_black = "#1a1a1a",
  black = "#1E1E1E", --  nvim bg
  black2 = "#252525"
  ...
```

Also:

```
M.base_16 = {
  base00 = "#1E1E1E",
  base01 = "#262626",
  base02 = "#303030",
  ...
```

I mean the names are completely meaningless to me. This probably needs a refactor somewhen, it must be a nightmare integrating new themes.

**Comment by siduck** [comment]
read https://github.com/chriskempson/base16/blob/main/styling.md
