### ISSUE TITLE
Better ways for the user to "unmap" key mappings for plugins shipped with `nvchad`

### ISSUE THREAD

**Issue by xarthurx** [siduck76/NvChad#2967]
**Is your feature request related to a problem? Please describe.**
There're many key mappings shipped with `nvchad`.
They are located in two places:
1. main mapping file: https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/mappings.lua
2. config files for each plugin: e.g. `gitsigns.lua` and `lspconfig.lua`

For `1.`, users can easily de-map it with the method provided in the doc, using `nomap`.
But for `2`, the above approach doesn't work and will create errors -- User needs to separately "unmap" it in the config of each plugin. 
And this creates some inconvenience...

**Describe the solution you'd like**
Move all the mapping to the main `mapping.lua`.

**Describe alternatives you've considered**
Just remove the mappings in the `plugin-config.lua` and tell users about it.

**Additional context**
In either way, default mapping should be easily reconfigured by the user.

**Comment by siduck** [comment]
```lua

{ 
          "gitsigns blaba",
           opts = {  
           
              on_attach = function ()
              
                                do here 
                 end
              }

**Comment by siduck** [comment]
for lspconfig u can do on lspattach event

**Comment by siduck** [comment]
those  2 are the only exceptions

**Comment by xarthurx** [comment]
Could you please be specific on the `lspconfig`? 
I'm using `mason-lspconfig` which needs to be loaded before `lspconfig`, so:

```
		{
			"williamboman/mason-lspconfig.nvim",
			lazy = false,
			config = function()
				require("configs.mason-lspconfig")
			end,
		},

		{
			"neovim/nvim-lspconfig",
			-- IMPORTANT: configs are set in the mason-lspconfig
			--
			-- config = function()
			-- require("nvchad.configs.lspconfig")
			-- 	require("configs.lspconfig")
			-- end,
		},

```

And I'm also using `noice`, but due  to the default mapping of the `signatureHelp`, I got this error:
![image](https://github.com/user-attachments/assets/12a0bf62-b001-48a0-b0e3-8ba7bc37c958)


I'd like to del the default map related to that part.

**Comment by siduck** [comment]
either disable noice's signature,  or our signature  https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L78

as for lsp mapping override, just make custom on attach

```lua
local function my_attach(client, bufnr)
  local function opts(desc)
    return { buffer = bufnr, desc = desc }
  end
  configs.on_attach(client, bufnr)
  -- map('n', 'gk', vim.lsp.buf.hover, opts 'Lsp hover information')
 -- do here
end
```

**Comment by siduck** [comment]
also fyi you can use our MasonInstallAll command too,  it will capture the lsp    names, formatter names, linter names from lspconfig,conform, nvim-lint and automatically map em to mason pkg names & install em, so u dont have to use our mason's ensure_installed field anymore :D

**Comment by xarthurx** [comment]
> also fyi you can use our MasonInstallAll command too, it will capture the lsp names, formatter names, linter names from lspconfig,conform, nvim-lint and automatically map em to mason pkg names & install em, so u dont have to use our mason's ensure_installed field anymore :D

Is this a new thing? Cos when I started the `mason-lspconfig`, the `MasonInstallAll` cannot do this.

**Comment by siduck** [comment]
yes its a new thing

**Comment by siduck** [comment]
masoninstallall  just runs the install_all function here https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/mason/init.lua

**Comment by xarthurx** [comment]
> either disable noice's signature, or our signature https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L78
> 
> as for lsp mapping override, just make custom on attach
> 
> ```lua
> local function my_attach(client, bufnr)
>   local function opts(desc)
>     return { buffer = bufnr, desc = desc }
>   end
>   configs.on_attach(client, bufnr)
>   -- map('n', 'gk', vim.lsp.buf.hover, opts 'Lsp hover information')
>  -- do here
> end
> ```

When I do as you show above:

```lua
local function x_on_attach(client, bufnr)
	-- Call the original NvChad on_attach function
	on_attach(client, bufnr)

	-- Add your custom keybindings here
	local function opts(desc)
		return { buffer = bufnr, desc = "LSP " .. desc }
	end

	nomap("n", "wl")
	nomap("n", "ra")
	nomap("n", "ca")

end

for _, lsp in ipairs(servers) do
	lspconfig[lsp].setup({
		on_attach = x_on_attach,
		on_init = on_init,
		capabilities = capabilities,
	})
end

```

It seems for some filetype, the keymap was not added, so that the `nomap` function will report errors:

![image](https://github.com/user-attachments/assets/a5407c02-e5bc-477b-a2c8-89db76020fb6)

**Comment by siduck** [comment]
@xarthurx  add buffer  opt in nomap too

**Comment by xarthurx** [comment]
> @xarthurx add buffer opt in nomap too

```
  local keys_to_unmap = {
    "wl", "ra", "ca"
  }

  for _, key in ipairs(keys_to_unmap) do
    -- vim.keymap.del("n", key, unmap_opts())
    vim.keymap.del("n", key, {buffer = bufnr})
  end

```

same issue.
