### ISSUE TITLE
Fields cannot be injected into the reference of `ChadrcConfig` for `plugins`. To do so, use `---class` for `M`. warning in chadrc.lua 

### ISSUE THREAD

**Issue by kartavkun** [siduck76/NvChad#2969]
**Describe the bug**
I wanted to add the line `M.plugins = "custom.plugins"` in the chadrc.lua file, but I got warning and I guess is not good

**To Reproduce**
1. Install NvChad with `git clone https://github.com/NvChad/starter ~/.config/nvim && nvim` command
2. Ran `:MasonInstallAll` command after lazy.nvim finishes downloading plugins
3. Opened chadrc.lua file
4. Add line with `M.plugins = "custom.plugins"`
5. Saw warning `Fields cannot be injected into the reference of `ChadrcConfig` for `plugins`. To do so, use `---class` for `M`.`

**Expected behavior**
Work without warnings

**Screenshots**
![image](https://github.com/user-attachments/assets/8b957b01-2dee-45ba-a579-23abb35108cc)

**Desktop (please complete the following information):**
 - Arch Linux x86-64 with linux-zen kernel 6.10.4.zen2-1 and Hyprland 0.41.2-3
 - kitty
 - neovim 0.10.1-3

**Additional context**
idk what to say about that xd

**Comment by siduck** [comment]
hi, update your config to v2.5...  https://nvchad.com/news/v2.5_release/
