### ISSUE TITLE
reopen same file，buffer will changed，how to dissabled this action

### ISSUE THREAD

**Issue by xu910121** [siduck76/NvChad#2973]
open a file with Cscope_maps.nvim ( https://github.com/dhananjaylatkar/cscope_maps.nvim ),  refind a symbol in already opend file，after this operation，pass u, nvim will warning buff has changed. when close the opend file, there will error: E37: No write since last change.
how to disable buff chang action?

**Comment by siduck** [comment]
show a video

**Comment by xu910121** [comment]
https://github.com/user-attachments/assets/501d4d2a-9f1c-42b7-8bf2-11c079bfee65
@siduck

**Comment by xu910121** [comment]
https://github.com/user-attachments/assets/2e85f8fa-8b85-41f9-9db8-d46f99f09893

@siduck thanks

**Comment by siduck** [comment]
seems like that plugin's issue? its modifying the buffer i think, press C-s to save the file!

**Comment by xu910121** [comment]
@siduck I have test Cscope_maps.nvim on vim-plug (https://github.com/junegunn/vim-plug), there no buffer changed warnning.

**Comment by siduck** [comment]
@xu910121  we use lazy.nvim plugin manager, if this doesnt happen outside of nvchad, like in lazyvim etc then i can look into it or show  me a minimal nvim config with this plugin

**Comment by xu910121** [comment]
@siduck I test on lazy.nvim, same as nvchad .... thanks a lot.

**Comment by siduck** [comment]
@xu910121  you should ask in that plugin repo , that its modifying the buffer
