### ISSUE TITLE
Show dotfiles in nvim-tree by default

### ISSUE THREAD

**Issue by Insprill** [siduck76/NvChad#2975]
**Is your feature request related to a problem? Please describe.**
In c892cfedb247cf829720dda80d3b32d7535a96ac, nvim-tree's `filters.dotfiles` option was changed to `true`, which causes it to hide all dotfiles by default. There are lots of dotfiles that people may have to access frequently (`.env`, `.gitignore`, `.github/`, and many more for various other tools).

In my opinion, this should be reverted, as I never want to hide dotfiles, and I'd assume many others feel the same. At the end of the day, it's easy to enable in my own config, but I believe showing them is a more sensible default than hiding them.

**Describe the solution you'd like**
Set nvim-tree's `filters.dotfiles` option back to `false`.

**Describe alternatives you've considered**
Setting it to false in my personal config.

**Comment by siduck** [comment]
yes add it in your own config

**Comment by heit0r** [comment]
I've just disable it in the /home/<me>/.local/share/nvim/lazy/NvChad/lua/nvchad/configs/nvimtree.lua

```
local options = {
  filters = { dotfiles = true }, -- here
  disable_netrw = true,
```

But there should be an default option to toggle if definitely as easier as the default Shift+H. Maybe Ctrl+Shift+H or somewhere in the <leader> menu or even in the cheatsheet. I had to dig up around to find which file should I alter. As a newcomer this was a bit of a hassle to find out. Just my 2¢. Amazing project btw. Cheers.

**Comment by heit0r** [comment]
I've just disable it in the /home/<me>/.local/share/nvim/lazy/NvChad/lua/nvchad/configs/nvimtree.lua

```
local options = {
  filters = { dotfiles = true }, -- here
  disable_netrw = true,
```

But there should be an default option to toggle if definitely as easier as the default Shift+H. Maybe Ctrl+Shift+H or somewhere in the menu or even in the cheatsheet. I had to dig up around to find which file should I alter. As a newcomer this was a bit of a hassle to find out. Just my 2¢.

Amazing project btw. Cheers.

**Comment by heit0r** [comment]
I've just disable it in the /home/me/.local/share/nvim/lazy/NvChad/lua/nvchad/configs/nvimtree.lua

local options = {
  filters = { dotfiles = true }, -- here
  disable_netrw = true,

But there should be a default option to toggle if definitely as easier as the default Shift+H. Maybe Ctrl+Shift+H or somewhere in the menu or even in the cheatsheet. I had to dig up around to find which file should I alter. As a newcomer this was a bit of a hassle to find out. Just my 2¢.

Amazing project btw. Cheers.

**Comment by heit0r** [comment]
I've just disable it in the /home/me/.local/share/nvim/lazy/NvChad/lua/nvchad/configs/nvimtree.lua

```
local options = {
filters = { dotfiles = true }, -- here
disable_netrw = true,
```

But there should be a default option to toggle if definitely as easier as the default Shift+H. Maybe Ctrl+Shift+H or somewhere in the leader menu or even in the cheatsheet. I had to dig up around to find which file should I alter. As a newcomer this was a bit of a hassle to find out. Just my 2¢.

Amazing project btw. Cheers.

**Comment by siduck** [comment]
> I had to dig up around to find which file should I alter. As a newcomer this was a bit of a hassle to find out.

it shouldnt be unless you know how plugins work with lazy, you can override them by opts

press g? in nvimtree window and its mappings will show up

**Comment by heit0r** [comment]
The mappings work. H, in this case (Shift + h). The problem is that this is not persistent. Next time I open nvim, .dotfiles crowd my NvimTree again. So I had to add

```
require'nvim-tree'.setup {
  filters = {
    dotfiles = true,  -- Hide hidden files permanently
  },
}
```

to my init.lua.

**Comment by heit0r** [comment]
The mappings work. H, in this case (Shift + h). The problem is that this is not persistent. Next time I open nvim, .dotfiles crowd my NvimTree again. I altered /home/me/.local/share/nvim/lazy/NvChad/lua/nvchad/configs/nvimtree.lua and end up breaking the nvchad update in Lazy, which I didn't think could happen. Lazy seems to check all files integrity before allow an update. So, to not mess things up, I had to add

```
require'nvim-tree'.setup {
  filters = {
    dotfiles = true,  -- Hide hidden files permanently
  },
}
```

to my init.lua, which seems to be the place users are allowed to make changes.

**Comment by siduck** [comment]
@heit0r please see how to override plugin opts...
 
 ```lua
 
 {  
     "blabla nvimtree",
      opts = {
                 filters = {
                  dotfiles = true,  -- Hide hidden files permanently
                   },
       }
  }
  ```

**Comment by heit0r** [comment]
> @heit0r please see how to override plugin opts...
> 
> ```lua
> {  
>     "blabla nvimtree",
>      opts = {
>                 filters = {
>                  dotfiles = true,  -- Hide hidden files permanently
>                   },
>       }
>  }
> ```

Sorry to bother, but I couldn't figure it out ;~
Are you referring to [this](https://nvchad.com/news/v2.0_release)?
But where? chadrc.lua?

**Comment by siduck** [comment]
please read nvchad.com plugin docs, you should know where to put which code.... The first thing a nvchad user must do after installing nvchad is read nvchad.com. Docs are short :/

**Comment by heit0r** [comment]
Indeed, they are short. I must have missed something. Thanks!
