### ISSUE TITLE
Mason ignoring ensure_installed when running MasonInstallAll

### ISSUE THREAD

**Issue by Hororohoruru** [siduck76/NvChad#2980]
**Describe the bug**
After migrating to v2.5, I ran the `:MasonInstallAll` command to check if my lsp configuration is working correctly. However, it only installs pyright and stylua. However, my mason config is the following in `nvim/lua/plugins/myplugins.lua`:

```
local plugins = {
  {
    "christoomey/vim-tmux-navigator",
    lazy = false,
  },
  {
    "ThePrimeagen/vim-be-good",
    lazy = false,
  },
  {
    "rcarriga/nvim-dap-ui",
    dependencies = {
      "mfussenegger/nvim-dap",
      "nvim-neotest/nvim-nio"
    },
    config = function()
      local dap = require("dap")
      local dapui = require("dapui")
      dapui.setup()
      dap.listeners.after.event_initialized["dapui_config"] = function()
        dapui.open()
      end
      dap.listeners.before.event_terminated["dapui_config"] = function()
        dapui.close()
      end
      dap.listeners.before.event_exited["dapui_config"] = function()
        dapui.close()
      end
    end
  },
  {
    "mfussenegger/nvim-dap",
    config = function(_, opts)
      require("core.utils").load_mappings("dap")
    end
  },
  {
    "mfussenegger/nvim-dap-python",
    ft = "python",
    dependencies = {
      "mfussenegger/nvim-dap",
      "rcarriga/nvim-dap-ui"
    },
    config = function(_, opts)
      local path = "~/.local/share/nvim/mason/packages/debugpy/venv/bin/python"
      require("dap-python").setup(path)
      require("core.utils").load_mappings("dap_python")
    end,
  },
  {
    "nvimtools/none-ls.nvim",
    dependencies = {
      "nvimtools/none-ls-extras.nvim",
    },
    ft = {"python"},
    opts = function()
      return require "configs.null-ls"
    end,
  },
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "black",
        "debugpy",
        "mypy",
        "ruff",
        "pyright",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    config = function()
      require "nvchad.configs.lspconfig"
      require "configs.lspconfig"
    end,
  },
}
``` 

It seems that the ensure_installed option is being ignored (I don't even know where the stylua is coming from). I'm not proficient in lua so I don't know how should I set up the configuration for the plugins.

**Comment by siduck** [comment]
move your mason pkgs here https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L85

I hope you're using nvchad v2.5 , i see some old functions being used.

MasonInstallAll  will pull lsps/formatters/linters from their specific configs like lspconfig, conform, nvim-lint , so the ensure_installed stuff is no longer needed ( M.mason.pkgs field )

you can add support for nvim-dap to, send a PR! https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/mason/init.lua#L4

**Comment by Hororohoruru** [comment]
Thanks for the quick response!

I am trying to migrate my old config to 2.5 and I am a bit lost, so that is why you see some old functions! Could you tell me which ones should I remove?

Lastly, I'd be happy to send a PR to add support for nvim-dap, but I have no idea how to do such a thing!

**Comment by Hororohoruru** [comment]
Where should I find the equivalent of this file in my config? https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L85

EDIT: I found it `~/.local/share/nvim/lazy/ui/lua/nvconfig.lua`. I added the packages to the list and now it works. Thank you! However, I find it a bit cumbersome that part of my config is outside my .config folder. I usually work on multiple machines and share my dotfiles between them. Is there a way of including this configuration inside `~/.config/nvim/`?

Thank you very much for helping with all these newbie questions. It is much appreciated!

**Comment by siduck** [comment]
> which ones should I remove

the load_mappings one

**Comment by siduck** [comment]
@Hororohoruru  nvconfig is the main options file for ui and base46 plugin, make the change in your chadrc :grin:

**Comment by siduck** [comment]
soon :h nvchad ( docs for ui/base46 ) will release clearing all these doubts

**Comment by bryanmaina** [comment]
> move your mason pkgs here https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L85
> 
> I hope you're using nvchad v2.5 , i see some old functions being used.
> 
> MasonInstallAll will pull lsps/formatters/linters from their specific configs like lspconfig, conform, nvim-lint , so the ensure_installed stuff is no longer needed ( M.mason.pkgs field )
> 
> you can add support for nvim-dap to, send a PR! https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/mason/init.lua#L4

Is this still the way it works? It looks like `MasonInstallAll` command doesn't exist anymore.

**Comment by siduck** [comment]
@bryanmaina  open nvim and see

**Comment by bryanmaina** [comment]
I did a fresh install of NvChad tried to run `MasonInstallAll` but the command does not exist. I followed the guide 
![image](https://github.com/user-attachments/assets/27b256e8-b5a0-495f-8237-90e497b39a24)

I have looked in neovim at Mason repo there is no traces of `MasonInstallAll`.
it should have be here it it exists on Mason side using the main branch because that is what is installed by the starter.

https://github.com/williamboman/mason.nvim/blob/main/lua/mason/api/command.lua

![image](https://github.com/user-attachments/assets/54e584df-42b9-4be9-9182-7034d8ec5765)

Mason Repo main branch does not have contain `MasonInstallAll`.
v2.x branch does have it

This what we have on `NvChad
/ui` repo
![image](https://github.com/user-attachments/assets/70a6108e-3dde-4d30-9f8f-9d928126326d)
![image](https://github.com/user-attachments/assets/ac8d37a2-6822-471f-969f-5d9936525247)


I tried to use `M.mason.pkgs` maybe this is not the right way to use it:
![image](https://github.com/user-attachments/assets/e298ab12-ddc5-45d8-95e5-757c5786b447)

and Run `Lazy sync` and that also did not change anything.

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/78be7ca6-ea31-4125-a4be-4ce5b5785037

did a clean install, it works..

**Comment by bryanmaina** [comment]
Then the cause might be a particular case on my install only.
Does your lazy-lock.json look somewhat like mine? 
```
{
  "LuaSnip": { "branch": "master", "commit": "e808bee352d1a6fcf902ca1a71cee76e60e24071" },
  "NvChad": { "branch": "v2.5", "commit": "8d2bb359e47d816e67ff86b5ce2d8f5abfe2b631" },
  "base46": { "branch": "v2.5", "commit": "82d71bc6def6a752cbf5fbd0e496aea5f088d940" },
  "cmp-buffer": { "branch": "main", "commit": "3022dbc9166796b644a841a02de8dd1cc1d311fa" },
  "cmp-nvim-lsp": { "branch": "main", "commit": "39e2eda76828d88b773cc27a3f61d2ad782c922d" },
  "cmp-nvim-lua": { "branch": "main", "commit": "f12408bdb54c39c23e67cab726264c10db33ada8" },
  "cmp-path": { "branch": "main", "commit": "91ff86cd9c29299a64f968ebb45846c485725f23" },
  "cmp_luasnip": { "branch": "master", "commit": "05a9ab28b53f71d1aece421ef32fee2cb857a843" },
  "conform.nvim": { "branch": "master", "commit": "1a99fdc1d3aa9ccdf3021e67982a679a8c5c740c" },
  "friendly-snippets": { "branch": "main", "commit": "00ba9dd3df89509f95437b8d595553707c46d5ea" },
  "gitsigns.nvim": { "branch": "main", "commit": "1ef74b546732f185d0f806860fa5404df7614f28" },
  "indent-blankline.nvim": { "branch": "master", "commit": "18603eb949eba08300799f64027af11ef922283f" },
  "lazy.nvim": { "branch": "main", "commit": "077102c5bfc578693f12377846d427f49bc50076" },
  "mason.nvim": { "branch": "main", "commit": "e2f7f9044ec30067bc11800a9e266664b88cda22" },
  "nvim-autopairs": { "branch": "master", "commit": "f158dcb865c36f72c92358f87787dab2c272eaf3" },
  "nvim-cmp": { "branch": "main", "commit": "ae644feb7b67bf1ce4260c231d1d4300b19c6f30" },
  "nvim-colorizer.lua": { "branch": "master", "commit": "0671e0eabc6842676d3310370e8fae4e1c51d7f9" },
  "nvim-lspconfig": { "branch": "master", "commit": "dd329912c8d446240584a2dbcd3802af3a19105a" },
  "nvim-tree.lua": { "branch": "master", "commit": "8405ecfbd6bb08a94ffc9c68fef211eea56e8a3b" },
  "nvim-treesitter": { "branch": "master", "commit": "6511cd984ab4b21e28f83af488f38dc89c3b0586" },
  "nvim-web-devicons": { "branch": "master", "commit": "26220156aafb198b2de6a4cf80c1b120a3768da0" },
  "plenary.nvim": { "branch": "master", "commit": "2d9b06177a975543726ce5c73fca176cedbffe9d" },
  "telescope.nvim": { "branch": "master", "commit": "b324469959908c1c7434eb65d80e87895e6828f7" },
  "ui": { "branch": "v2.5", "commit": "62f6ede07573a04e7c1a76ec48e7ce19b43d39f3" },
  "which-key.nvim": { "branch": "main", "commit": "fb070344402cfc662299d9914f5546d840a22126" }
}
```
I also did do the following before attempting the install to make sure that I get no residues of previous installs.
```
rm -rf ~/.config/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.local/share/nvim
```

![image](https://github.com/user-attachments/assets/bfee0121-37ee-4275-b529-e318ee0db2f0)

**Comment by siduck** [comment]
@bryanmaina  i have noticed that masonInstallAll doesnt show up after mason is opened

for now make some command that calls this
```lua
 require("nvchad.mason").install_all()
```

**Comment by bryanmaina** [comment]
@siduck  `require("nvchad.mason").install_all()` will will run an installAll but will only install what is required by lsp in these 2 locations: https://github.com/NvChad/starter/blob/59f23d053a047a0c6c555fea2fc4b7b26201e64f/lua/configs/lspconfig.lua#L7

![image](https://github.com/user-attachments/assets/3e3a0199-c5a4-4bd0-85e8-a21aab910a08)

For some reason it does not use what we mention in `M.mason.pkgs`.

That does a lot of the work that I would normally have do manually and helps for now. Anything in `M.mason.pkgs` mainly things that conform needs must be installed manually for now.

**Comment by siduck** [comment]
@bryanmaina  conform/nvim-lint stuff must be autodetected by mason install... ig you're doing something wrong ._.

**Comment by bryanmaina** [comment]
@siduck You are right it did catch the dependency after some tries. I also added a package the was prone to failure that might be part of the problem. My bad.

![image](https://github.com/user-attachments/assets/2dd13942-dd21-4b27-bbd5-d72fbb367e1e)

I will roll with  `require("nvchad.mason").install_all()` for.

Adding things to M.mason.pkgs it did not work but after playing with Conform for about 15 mins, I got it to to catch that yamlfix from Conform configs (no idea what happened there on the first run).
I noticed after some testing that `MasonInstallAll` is back and available once `require("nvchad.mason").install_all()` finishes and running right after it `MasonInstallAll` does gets thing from `M.mason.pkgs` and retries what ever failed from Conform in this case `prettier` and `prettierd`

![image](https://github.com/user-attachments/assets/934d457c-782c-4d11-82ce-cad2615e20d8)

![image](https://github.com/user-attachments/assets/7f0939ad-b3b8-4f60-9829-327950f64875)

**Comment by siduck** [comment]
@bryanmaina for now

```lua
    require("nvchad.mason").install_all(require("nvconfig").mason.pkgs)
```

and that pkgs fields must be only used if mason doesnt detect the configured tool in your config

**Comment by MoffunW** [comment]
So is there any way to setup M.mason.pkgs so packages install automatically?

**Comment by siduck** [comment]
there is, plz read h nvui.mason
