### ISSUE TITLE
Dim inactive windows

### ISSUE THREAD

**Issue by dmyyy** [siduck76/NvChad#2985]
**Is your feature request related to a problem? Please describe.**
It can be hard to tell what window is currently selected

**Describe the solution you'd like**
Dim inactive windows

**Describe alternatives you've considered**
There is https://github.com/levouh/tint.nvim

Would be nice to have something like this out of the box

**Additional context**

**Screenshot**
https://user-images.githubusercontent.com/31262046/188533069-966c663b-5be7-49ce-b389-60bb3b10c572.gif

**Comment by siduck** [comment]
i dont think is useful to re-invent the wheel unless i'm adding something new to ours! you can just use that plugin
