### ISSUE TITLE
Cannot override commentstring

### ISSUE THREAD

**Issue by Shiny380** [siduck76/NvChad#2987]
**Describe the bug**
as discussed originally [here](https://github.com/neovim/neovim/issues/29079#issuecomment-2333027287)
`:set commentstring=//\ %s` doesn't have any affect

running neovim with `nvim --clean` works

**To Reproduce**
1. open any c or c++ file
2. `:set commentstring=//\ %s`
3. `gcc` to comment line

**Expected behavior**
Line should be commented like `// ...` instead of the old default `/*...*/`

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim
    ```
    NVIM v0.10.1
    Build type: Release
    LuaJIT 2.1.1713484068
    ```

**Additional context**

**Comment by siduck** [comment]
just tested on nvim --clean, its the same

so not a nvchad issue

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/346ee0ae-057e-4ab6-b8d9-3d3e22bb2a32

u sure it works for vanilla nvim? nvchad doesnt at all handle commentstring stuff

**Comment by Shiny380** [comment]
clarification, you are right however it does work with .cpp files

**Comment by Shiny380** [comment]
https://github.com/user-attachments/assets/c75f6d2a-abc3-43b4-a48c-8d76007676ee

**Comment by siduck** [comment]
run TSUninstall cpp

and try

**Comment by Shiny380** [comment]
Thanks,
It works after running `TSUninstall cpp` then restarting nvim. Is there somewhere else I should move this issue to?

**Comment by siduck** [comment]
i think its better to ask on r/neovim before making issue  there

**Comment by ghost** [comment]
for anyone who may stumble upon the issue where treesitter with cpp parser enabled overrides `:set commentstring=//\ %s`
 from neovim/neovim#28176:

> The best approach for users to customize 'commentstring' is to create a filetype plugin (see :h ftplugin) or FileType autocommand inside which set the option locally (with :setlocal or lua vim.bo). Changing it interactively will not always work (for example, in presence of active tree-sitter parser).

so the solution for me was: 
```lua
        vim.api.nvim_create_autocmd("FileType", {
            pattern = "cpp",
            callback = function()
                vim.bo.commentstring = "// %s"
            end,
        })
```

**Comment by siduck** [comment]
@MoonlyVibes  or u can use the ftplugin dir too
