### ISSUE TITLE
Floating terminal is positioned out of screen

### ISSUE THREAD

**Issue by dee-kryvenko** [siduck76/NvChad#2991]
**Describe the bug**
It seems like the terminal is misaligned. See the screenshots attached. This is a basic sample form https://github.com/rivo/tview/wiki/Flex but can also reproduce with something like lazygit. It works fine in the same terminal emulator in tmux with same session. It could be easily overlooked if the terminal app does not have borders.

**To Reproduce**
1. Run anything that renders borders in a floating terminal

**Expected behavior**
Should be displayed with proper size and positioning.

**Screenshots**

<img width="1860" alt="Screenshot 2024-09-12 at 7 39 18 PM" src="https://github.com/user-attachments/assets/3150ba2e-f566-4aee-923d-4682f43a0f0a">
<img width="1869" alt="Screenshot 2024-09-12 at 7 44 16 PM" src="https://github.com/user-attachments/assets/955ca287-1c99-4d84-8a50-0d62e8b25fa2">

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Alacritty
 - Version of Neovim:

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
```

**Additional context**
N/a

**Comment by siduck** [comment]
increase width and height of the terminal in float_opts

**Comment by siduck** [comment]
```lua
M.term =  {
   winopts = { scl = 'no' } 
}
```

try this in ur chadrc

**Comment by dee-kryvenko** [comment]
That doesn't seem to have any effect, I already had size of the float customized... Also I said float in the subject, but actually this is also broken for me in the same way in both vertical and horizontal split terms too. Strangely this problem went away when I set `winopts = { number = true, relativenumber = true }` - but I was not trying to fix the issue, I just needed line numbers in my terminal because I often need to go back and copy stuff from the history.

**Comment by siduck** [comment]
try `scl = 'auto'`
