### ISSUE TITLE
eiidrovo@espol.edu.ec

### ISSUE THREAD

**Issue by eiidrovo** [siduck76/NvChad#2992]
Hi, I tried to make the background of nvchad transparent so I changed the value of transparency in the default_config.lua file from false to true and it doesn't change anything. 
Im using picom, with kitty terminal.

**Comment by siduck** [comment]
default_config.lua? that doesnt exist at all. i hope you're using nvchad v2.5.........

please change in your chadrc

**Comment by eiidrovo** [comment]
I fixed it
