### ISSUE TITLE
Using 'j' Key in Instert Mode Causes Input Bug

### ISSUE THREAD

**Issue by xyzpw** [siduck76/NvChad#2994]
While I am in edit mode, if I type the letter 'j' it takes the input like I was in normal mode.<br>
The cursor stays behind the letter and even appears on the bottom of the screen like I am using a command.

**Reproduce**
Open nvim and go into insert mode with the key 'i', typing the letter 'j' will cause the issue.

**Expected behavior**
Cursor should move ahead of letter as it is typed, not before it for a short duration of time.

![nvchad-2024-09-16](https://github.com/user-attachments/assets/0f766267-0b5f-40f0-88ce-4d94fe606734)

 - OS: Linux
 - Can reproduce on terminals  Konsole, Alacritty, and Kitty.
 - Neovim version: v0.10.1

**Comment by siduck** [comment]
disable this mapping https://github.com/NvChad/starter/blob/main/lua/mappings.lua#L8

its an example
