### ISSUE TITLE
Error E212 When Opening/Saving Files with Both Square Brackets and Parentheses in Path

### ISSUE THREAD

**Issue by moha-abdi** [siduck76/NvChad#2997]
Description:

I am experiencing an issue with Neovim configured with NvChad where I cannot open or save files if the path includes special characters. Specifically, the issue arises when working with file paths that contain both brackets and paranthesis., like [locale]/(dashboard).

Steps to Reproduce:

Create a directory with brackets or special characters in the path, for example, ~\GitProjects\sarifle\app\[locale]\(dashboard)\notifications\page.tsx.
Open the base of the directory, and then with nvim-tree try to open file that is inside it, for example page.tsx in my case.

Expected Behavior:

The file should open and save without any issues.

Actual Behavior:

I receive the following error message:

```
E212: Can't open file for writing: no such file or directory
```

Environment:

Neovim Version: 0.9.4
Operating System: Windows
Additional Information:

I thought the issue was with nvim-tree, so I tried a minimal version of nvim with minimal nvim-tree configuration and it worked fine without any issues. 

Screenshot:
![image](https://github.com/user-attachments/assets/70ad0b3f-e25f-427e-af37-02cafe49f7d1)

**Comment by siduck** [comment]
show a video with an without it :/

**Comment by moha-abdi** [comment]
> show a video with an without it :/

## Here is a video showcasing the issue
https://github.com/user-attachments/assets/ea3869c8-45e8-4511-957b-534493409846

## And this is another one I tried clean neovim with only minimal nvim-tree

https://github.com/user-attachments/assets/79f4ebb4-1f25-4bd8-b804-39bce8858464

**Comment by siduck** [comment]
now try with this https://github.com/NvChad/tinyvim

and lazyvim

i hope you know using nvimappname feature!

**Comment by moha-abdi** [comment]
lol. its working now. Some plugins needed updates because there was escaping issues. Now that I have tried this it worked. Thanks
