### ISSUE TITLE
Help me format JSON files

### ISSUE THREAD

**Issue by knnmran** [siduck76/NvChad#2998]
**Describe the bug**
I am not able to format JSON files

**To Reproduce**
1. Open any JSON file

**Expected behavior**
Leader + fm should format/order the json file

**Desktop (please complete the following information):**
 - Operating System - MacOS
 - Terminal - Alacritty
 - Version of Neovim - v0.10.0

**Comment by siduck** [comment]
why would it even format      by default?

**Comment by siduck** [comment]
setup prettier for json filetype in your conform config

**Comment by siduck** [comment]
```lua
{
     "blabla conform",
      opts = {
             formatters_by_ft =   {
                   json = { "prettier" }
              }
      }
  }
  ```

**Comment by knnmran** [comment]
i installed "prettier" using Mason and then updated the "conform.lua" as in attachments which did not help. anything else i am missing here?

![Screenshot 2024-09-19 at 12 23 56 PM](https://github.com/user-attachments/assets/98e4334d-f4cf-4b23-9ba6-31b7869f3077)
![Screenshot 2024-09-19 at 12 24 26 PM](https://github.com/user-attachments/assets/ce09b79a-1306-42ce-b280-7212ff012032)

**Comment by siduck** [comment]
nwo run leader + fm to format

**Comment by knnmran** [comment]
i am guessing "nwo" stands for "new word order"?!

i ran "leader + fm"(previously mentioned) but did not see anything change as pictured below. 

i am using the latest version of NvChad and able to format other file types except jsons.

<img width="415" alt="Screenshot 2024-09-19 at 11 48 44 PM" src="https://github.com/user-attachments/assets/acd2609b-56f7-454d-b369-36082e5503a9">

**Comment by siduck** [comment]
my bad , i meant now*

**Comment by siduck** [comment]
https://github.com/user-attachments/assets/b3069fc0-d63c-4a2c-9263-2b92aab7d05b

tried a fresh install, works fine :/

**Comment by siduck** [comment]
> i am guessing "nwo" stands for "new word order"?!

You're funny :grimacing:

**Comment by knnmran** [comment]
well, something must be wrong with my setup then. i will try to find out.

thanks for the video walk-through!!!
