### ISSUE TITLE
E5113: Error while calling lua chunk

### ISSUE THREAD

**Issue by Staz0r** [siduck76/NvChad#2999]
**Describe the bug**
After completing all the prerequsites and installation process, nvim shows some error codes when being ran. Nvim works fine without the environment of functionality of Nvchad.

**To Reproduce**
1. Download Neovim 0.10.0
2. Run uninstallation commands
3. Run installation commands
4. Run `nvim`

**Desktop (please complete the following information):**
 - Operating System ParrotOS 6.1 on Virtual Machine
 - Terminal Bash
 - Version of Neovim 0.10.0

**Additional context**
```lua
Error detected while processing /home/someone/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/loader.lua:0: attempt to call upvalue '' (a nil valu
e)
stack traceback:
        vim/loader.lua: in function 'cache_file'
        vim/loader.lua: in function 'read'
        vim/loader.lua: in function 'loadfile'
        vim/loader.lua: in function <vim/loader.lua:0>
        [C]: in function 'require'
        ...meone/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:77: in function 'setup'
        /home/someone/.config/nvim/init.lua:17: in main chunk
Error detected while processing /usr/share/nvim/runtime/filetype.lua:
E5111: Error calling lua: vim/loader.lua:0: attempt to call upvalue '' (a nil value)
stack traceback:
        vim/loader.lua: in function 'cache_file'
        vim/loader.lua: in function 'read'
        vim/loader.lua: in function <vim/loader.lua:0>
```

It's my first time using Linux, I've never had any problem with installation on Windows so I am confused about what happened.

**Comment by siduck** [comment]
this isnt a nvchad issue, please update to latest nvim i.e 0.10.1

**Comment by Staz0r** [comment]
If thats the case, shouldn't you guys have updated the installation guide on the documentation?
The link clearly pointed to 0.10.0, and since It was not written on the NvChad page either I didn't know that I should update it.
This will also help others as well. Thank you

**Comment by siduck** [comment]
my bad,  0.10 should work too, just tested its appimage ..

**Comment by siduck** [comment]
can you record a video of clean install?

**Comment by bhunter234** [comment]
Facing same issue on 0.10.3 and 0.10.4
