### ISSUE TITLE
nvim-cmp crashes after today's update

### ISSUE THREAD

**Issue by RomaLzhih** [siduck76/NvChad#3007]
After updating the nvchad to the latest config, without any change of the user configuration, the nvim-cmp crashes as follows,
my configs can be found[ here](https://github.com/RomaLzhih/neovim_config/blob/main/lua/plugins/myplugins.lua#L773). 

Is there anything we should change in our configuration? 
![image](https://github.com/user-attachments/assets/ceab17cb-f1ed-4141-87df-6b083d007d55)

**Comment by RomaLzhih** [comment]
Ok by reinstalling the neovim it solves ...

**Comment by siduck** [comment]
@RomaLzhih  you had to do lazy sync twice to fix the issue! cuz a ui plugin moved to new branch as default so lazy wont pull commits in first sync itself
