### ISSUE TITLE
Nvstart vs nvchad v2.5 natively

### ISSUE THREAD

**Issue by str0g** [siduck76/NvChad#3008]
**Describe the bug**
Working differently. I was trying to setup definition jumping (gd) with compile commands.
On v2.5 done natively it works while on  with starter(nvchad v2.5) it does not work.

**reproduction**
starter
git remote show origin 
* remote origin
  Fetch URL: https://github.com/NvChad/starter (v2.5)
branch master

v2.5
git remote show origin 
* remote origin
  Fetch URL: https://github.com/NvChad/NvChad.git
branch v2.5

**Expected behavior**
Should work the same.

**Desktop (please complete the following information):**
 - ArchLinux
 - Kitty
 - 0.10.1

**Additional context**
In my opinion settings up nvchad is still too complex
Loading plugins like python with custom init.lua does not work with starter, while works perfectly fine with v2.5 natively
I have no idea how to enabled vim.lsp.
I have no idea how to make work clang-format it does not work in both cases with starter it just don't work while with v2.5
 module 'configs.conform' not found and I have no idea how to fix it. It's just too complicated with this lack of documentation.

**Comment by siduck** [comment]
@str0g  gd is a  lsp mapping, load it at lspattach or in your custom onattach in lspconfig
