### ISSUE TITLE
nvdash not showing after recent update

### ISSUE THREAD

**Issue by aditiapratama** [siduck76/NvChad#3009]
**Describe the bug**
After recent update, nvdash not showing.

**To Reproduce**
1. update nvchad using lazy sync twice
2. close nvim and reopen
3. it's return blank

**Expected behavior**
Nvdash should show because it setup in chadrc to show 

**Desktop (please complete the following information):**
 - Operating System : Pop!OS 20.04
 - Terminal : alacritty
 - Version of Neovim : 0.10.0

**Additional context**
here's my chadrc config
```lua
local M = {}
M.ui {
  nvdash = {
     load_on_startup = true,
     }
}
```

**Comment by siduck** [comment]
hi, nvdash has been moved outside of ui table,
so 

M.nvdash
