### ISSUE TITLE
.env files are being ignored in telescope! how to remove this behaviour. I am new to NvChad

### ISSUE THREAD

**Issue by piyushyadav0191** [siduck76/NvChad#3014]
Problem is pretty simple

I have .env file and it is not showing in telescope. How to enable this ? Is their any filter toggling this behavior?

**Comment by siduck** [comment]
.env is gitignored hence not shown in telescope

run <leader>fa to see hidden files

or there must be a way to include files in find_files() of telescope, read its docs

**Comment by bupd** [comment]
@siduck I want to see gitignored files in my nvtree how to do that

**Comment by siduck** [comment]
@bupd  check nvimtree options, there's an option for that
