### ISSUE TITLE
[Site Bug]: NvChad website API page is down

### ISSUE THREAD

**Issue by ianTevesAcc** [siduck76/NvChad#3017]
**Describe the bug**
The page for NvChad API page is down.

**To Reproduce**
1. Go to https://nvchad.com/docs/api/

**Expected behavior**
For it load the NvChad API page.

**Screenshots**
![image](https://github.com/user-attachments/assets/22ba2c5e-83a7-418d-8846-a5b9ba14d9a5)

**Additional context**
I wanted to get the toggle theme api to toggle my theme with a keymap. But I found out that the site page for API is down. I waited for the whole day, but it's still down. When is it coming back up?

**Comment by siduck** [comment]
that page is no longer needed. read :h nvui

**Comment by ianTevesAcc** [comment]
@siduck Awesome! Thanks 😎
