### ISSUE TITLE
Adding loaders in init file doesn't add my custom snippets

### ISSUE THREAD

**Issue by IbrahimQatato** [siduck76/NvChad#3018]
**Describe the bug**
Adding loaders in init file doesn't add my custom snippets

**To Reproduce**
1. Go to the main init file `./init.lua` 
2. Add the following lines to the end of the file:
```lua
vim.g.lua_snippets_path = vim.fn.stdpath("config") .. "/lua/custom/snippets/"
print(vim.g.lua_snippets_path)
require("luasnip.loaders.from_lua").load({ paths = { vim.g.lua_snippets_path } })
```
3. Save and exit vim
4. Open a tex file, you will not see the new snippets

**Expected behavior**
To be able to trigger the new snippets

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal: Bash
 - Version of Neovim: 2.5

**Additional context**
This is my file structure:
```
.
├── init.lua
├── lazy-lock.json
├── LICENSE
├── lua
│   ├── chadrc.lua
│   ├── configs
│   │   ├── conform.lua
│   │   ├── lazy.lua
│   │   └── lspconfig.lua
│   ├── custom
│   │   └── snippets
│   │       └── tex.lua
│   ├── mappings.lua
│   ├── options.lua
│   └── plugins
│       └── init.lua
└── README.md
```
tex.lua contents:
````lua
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("tex", {
  s("lim", {
      t("lim_{"), i(1), t("\\to") , i(2) , t("}"), i(0)
    }
  )
})


ls.add_snippets("tex", {
  s("_", {
      t("_{"), i(1), t("}") , i(0)
    }
  )
})
```

**Comment by siduck** [comment]
that breaks whole lazyloading, please add only the global

**Comment by IbrahimQatato** [comment]
by global do you mean only the 
`vim.g.lua_snippets_path = vim.fn.stdpath("config") .. "/lua/custom/snippets/"`
line?
it still doesn't work

I am not sure I get how to add snippets from the docs, perhaps you can tell me? I'd love to add to the docs also if you think it's a good idea so that new nvim users can enjoy your plugin

**Comment by siduck** [comment]
first try to load your snippets without our abstraction i.e  without our global

```lua
{
      "Blabla luasnip",
       config = function(_, opts)
          -- load our default config 
          require("luasnip").config.set_config(opts)
          require "nvchad.configs.luasnip"
          
          -- then load your code here
        end,
}
```

if this works then there's an issue with the global

**Comment by IbrahimQatato** [comment]
so I did this:
```lua
{
    "L3MON4D3/LuaSnip",
    config = function(_, opts)
    -- load our default config 
    require("luasnip").config.set_config(opts)
    require "nvchad.configs.luasnip"
    -- then load your code here
    require("luasnip.loaders.from_lua").lazy_load({ paths = "/custom/snippets" })
    end,
},
```

and still my latex snippets aren't loaded, I tried just using `load` rather than `lazy_load` also.
I also tried
```lua
require("luasnip.loaders.from_lua").lazy_load({ paths = "/lua/custom/snippets" })
```
and outright
```lua
require("luasnip.loaders.from_lua").lazy_load({ paths = "~/.config/nvim/lua/custom/snippets" })
```

It doesn't seem to be an issue with the global, but I still do not know what the problem is

**Comment by siduck** [comment]
try with a non nvchad config now, use nvimappname feature to test multiple configs without messing up ~/.config/nvim

**Comment by IbrahimQatato** [comment]
I tried this with NvChad and it worked:
```lua
  {
    "L3MON4D3/LuaSnip",
    config = function(_, opts)
    -- load our default config 
    require("luasnip").config.set_config(opts)
    require "nvchad.configs.luasnip"
    -- then load your code here
    require("luasnip.loaders.from_lua").load({ paths = {"~/.config/nvim/lua/custom/snippets"} })

    end,
  },
```
and now it works, but it doesn't work with lazy_load though

**Comment by siduck** [comment]
ok try removing our config

```lua
  {
    "L3MON4D3/LuaSnip",
    config = function(_, opts)
    require("luasnip").config.set_config(opts)
    require("luasnip.loaders.from_lua").lazy_load({ paths = {"~/.config/nvim/lua/custom/snippets"} })
    end,
  },
  ```

**Comment by IbrahimQatato** [comment]
if I do it with lazy load I get neither `friendly-snippets` nor my snippets, but if I do so with load I only get my snippets

**Comment by siduck** [comment]
> if I do it with lazy load I get neither `friendly-snippets` nor my snippets, but if I do so with load I only get my snippets

so it just works with load?

**Comment by IbrahimQatato** [comment]
yeah

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/04576afe-9d74-4757-9ee9-eaa58cbe5f97)

as per luasnip docs, its using load for luasnippets

**Comment by siduck** [comment]
you should join our discord server and ask help there, i no nothing about snippets as i just use the defaults. if luasnipets dont work with lazyload then i'll make the change on main repo. But need confirmation first!

**Comment by IbrahimQatato** [comment]
Yeah I'd love to join, where can I join?

**Comment by siduck** [comment]
> Yeah I'd love to join, where can I join?

https://discord.com/invite/gADmkJb9Fb

**Comment by IbrahimQatato** [comment]
Thank you! I joined will message you guys over there after the cooldown :+1:

**Comment by 5ayam5** [comment]
Hi, were you able to get the custom snippet to work? I am facing the same issue where the custom loader file isn't being detected.
Here is `myplugins.lua` (my snippets are in `config/lua/snippets`).
```lua
  {
    "L3MON4D3/LuaSnip",
    dependencies = {
      "rafamadriz/friendly-snippets"
    },
    config = function(_, opts)
      require("luasnip").config.set_config(opts)
      require "nvchad.configs.luasnip"
      require("luasnip.loaders.from_lua").load({paths = {vim.fn.stdpath("config") .. "/lua/snippets/"}})
    end,
  }
```
