### ISSUE TITLE
Error in themeing

### ISSUE THREAD

**Issue by Codesmith28** [siduck76/NvChad#3020]
**Describe the bug**
- Whenever i press enter after selecting a theme in nvchad i get the following error, however pressing escape closes the theme changer and the theme is applied:
![Screenshot_05-10-2024_123815](https://github.com/user-attachments/assets/622d06b4-43eb-4ade-a2e7-e89a79a32eff)
![Screenshot_05-10-2024_123842](https://github.com/user-attachments/assets/b0f6f5e9-679e-4410-97be-2f42f6c8d0ef)
- furthermore, when i modify and save my config files in nvchad like `chadrc.lua`, the theme automatically reverts back to `onedark`
![Screenshot_05-10-2024_123908](https://github.com/user-attachments/assets/9a01bd3a-ab20-42b8-8aff-77036ff3b76c)

**To Reproduce**
1. Open the theme changer using `<leader> th` and then select a theme and press `enter` for the first bug
2. Open the config files in nvchad and make some modifications within `plugins` or `chadrc.lua` file, on saving the changes the theme reverts back to `onedark`

**Expected behavior**
- No errors should be shown on changing the theme
- The theme should not revert to onedark on saving config after modifying them

**Desktop:**
 - Operating System : Arch Linux with kernel: Linux 6.11.1-zen1-1-zen
 - Terminal: Kitty
 - Version of Neovim: v0.10.2

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/issues/2938

please put all the theme related options in base46,not ui table..

**Comment by Codesmith28** [comment]
Thank you so much!

**Comment by ngthminhdev** [comment]
Can you show me how to get that toast Error? it look nice

**Comment by siduck** [comment]
@ngthminhdev  thats from noice.nvim plugin!
