### ISSUE TITLE
prisma model name doesn't stick to the top, earlier it used to work

### ISSUE THREAD

**Issue by shyamayadav154** [siduck76/NvChad#3023]
**Describe the bug**
prisma model name doesn't stick at the top

**To Reproduce**
1. Install tesitter-context from nvchad-community plugin
2. install treesitter and lsp for prisma, setup lsp by adding `prismals` in `lspconfig.lua` file servers variable
3. open any prisma file

**Expected behavior**
model name should stick at the top 

**Screenshots**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c279a26c-b4d6-41b0-a1f1-2ce4d0bf54eb">

**Desktop (please complete the following information):**
 - Operating System: MacOS: 14.3.1
 - Terminal: WezTerm
 - Version of Neovim: 0.10.2

**Additional context**

**Comment by siduck** [comment]
i tried with lazyvim, it doesnt work, issue's with the plugin, not nvchad. If you're able to make it work on non nvchad config then i'll reopen the issue and debug
