### ISSUE TITLE
The Mutable Ai badge doesn't match the style of other badges

### ISSUE THREAD

**Issue by kamack38** [siduck76/NvChad#3025]
Currently the Mutable Ai badge is:

![](https://img.shields.io/badge/Auto_Wiki-Mutable.ai-blue)

It should have the same style as the others (flat-square):

![](https://img.shields.io/badge/Auto_Wiki-Mutable.ai-blue?style=flat-square)

(https://img.shields.io/badge/Auto_Wiki-Mutable.ai-blue?style=flat-square)

**Comment by siduck** [comment]
fixed
