### ISSUE TITLE
Command `MasonInstallAll` not found after loading `mason.nvim`

### ISSUE THREAD

**Issue by firashacker** [siduck76/NvChad#3026]
after i installed Mason and sat my ensureinstalled servers when i run MasonInstallAll i get

Command `MasonInstallAll` not found after loading `mason.nvim`

**Comment by siduck** [comment]
https://github.com/williamboman/mason.nvim/discussions/1795

related to that.  For now you can make new mapping that runs this : `require("nvchad.mason").install_all()`

**Comment by siduck** [comment]
do lazy sync @firashacker

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/commit/6f25b2739684389ca69ea8229386c098c566c408
