### ISSUE TITLE
Extra padding present inside terminals

### ISSUE THREAD

**Issue by aryanjassal** [siduck76/NvChad#3028]
**Describe the bug**
All terminals have a two-character horizontal padding, where two characters are hidden from the terminal view, requiring scrolling to view the hidden characters. This happens across the vertical, horizontal, and floating terminal.

**To Reproduce**
1. Open terminal either using `<A-i>`, or `<A-v>` or `<A-h>`
2. Type a command which exceeds the window width (easy to do in vertical-split terminal using `<A-v>`)
3. See the hidden characters

**Expected behavior**
The terminal shouldn't have extra horizontal padding leading to hidden characters and needing to scroll.

**Screenshots**

![image](https://github.com/user-attachments/assets/33b97379-5373-44b1-be3b-a3b2424bf9ca)

![image](https://github.com/user-attachments/assets/bbc1c296-61a7-4591-b28e-d4e7efabb0f9)

**Desktop (please complete the following information):**
 - Operating System: NixOS 24.11 (using home-manager-installed neovim, nixpkgs commit `a58bc8ad779655e790115244571758e8de055e3d`)
 - Terminal: Kitty
 - Version of Neovim: v0.10.1 (release)

**Additional context**

**Comment by siduck** [comment]
thats signcolumn, disable it for terminal

**Comment by siduck** [comment]
read `:h nvui.term` and disable signcolumn in winopts
