### ISSUE TITLE
Can't select theme

### ISSUE THREAD

**Issue by ZouDongj** [siduck76/NvChad#3030]
Every time I press enter to select a theme the following warning appears,
`E5108: Error executing lua: ....local/share/nvim/lazy/ui/lua/nvchad/themes/mappings.lua:23: attempt to index field 'base46' (a nil value)`

at this point I exit the theme selector and the theme is applied successfully for the time being, subsequently once I edit the file and save it, the theme reverts to the default theme

**Comment by siduck** [comment]
please move your theme variables to M.base46.  check the pinned issue
