### ISSUE TITLE
[ feature request ] Search ~/.config/nvchad for custom config files

### ISSUE THREAD

**Issue by yonas** [siduck76/NvChad#3037]
## Proposal

This way, I can add all my customizations in another place that I control and not have to reinstall them when I do `git clone https://github.com/NvChad/starter ~/.config/nvim && nvim`.

Let's use `chadrc.lua` as an example. This ought to apply the same way to `options.lua`, `mappings.lua`, etc.

`chadrc.lua` is currently searched for in `~/.config/nvim/lua/chadrc.lua`, but if `~/.config/nvchad/lua/chadrc.lua` exists, it would be added and would overwrite existing settings.

## Benefits
- easy deployment of customizations
- works well with dotfile managers (eg. chezmoi)
- allows overwriting default settings and adding new settings without touching NvChad directly

## Location of files under `~/.config/nvchad`

- [ ] Direct mapping: 
`~/.config/nvim/lua/chadrc.lua` => `~/.config/nvchad/lua/chadrc.lua`
- [ ] Convenience mapping:
`~/.config/nvim/lua/chadrc.lua` => `~/.config/nvchad/chadrc.lua`

Direct mapping is more self-explanatory and allows the use of duplicate filenames by using directories.

Convenience mapping is more future-proof by withstanding a directory structure reorganization from NvChad if it were to happen in the future.

**Comment by siduck** [comment]
starter repo is only an example on how to use nvchad main repo as a plugin. Dont worry about the updates, just do lazy sync.
