### ISSUE TITLE
[Question] Is there a way to overwrite some LSP keybindings (specifically "K")

### ISSUE THREAD

**Issue by ryanbas21** [siduck76/NvChad#3041]
Hi,

I was hoping to try out the `hover.nvim` package. This keybinding is kind of what the lsp.buf.hover does, and nvchad has "K" bound for it, which is what I want to "override". I am having a hard time understanding where and if this is possible to override.

I've seen a few older issues with similar-esque questions, that have changes to the chadrc file, but I haven't really narrowed down a working solution.

I've tried writing these keybindings in my `on_attach` method of my lsp and I couldn't get it working.

The main thing I want to do is, can I override and if so - how, the "K" keybinding to use `hover.nvim`

**Comment by siduck** [comment]
make a custom onattach, load ours in it first then your code. 

or do it in callback of lspattach event ( wrap with vim.schedule to avoid race conditions )
