### ISSUE TITLE
Tabline doesn't disappear when there is nothing to show

### ISSUE THREAD

**Issue by GCBallesteros** [siduck76/NvChad#3043]
I have configured my tabline to only show "tabs". Most of the time I only have one tab open but will occasionally open another, for example to open neogit.

Once the tabline appears for example after opening neogit it will not disappear when there is just one tab left. In that case the tabline just looks like a gray bar sitting at the top of the screen. Shown below:

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/ec0249e4-7dc0-4fea-8106-fc023f403640">

It would be nice that if the tabline has nothing to show then it collapses.

**Comment by siduck** [comment]
you need to write an autocmd for this.  at these events. and then use showtabline option to toggle tabline
![image](https://github.com/user-attachments/assets/8d1a4988-ba2c-4fe0-8ef4-a6d37685e58f)
