### ISSUE TITLE
Luasnip globals set after LuaSnip is loaded

### ISSUE THREAD

**Issue by egaban** [siduck76/NvChad#3045]
If I set in my `options.lua`
```lua
local nvim_config = vim.fn.stdpath "config"
vim.g.vscode_snippets_path = nvim_config .. "/snippets"
```

The global `vim.g.vscode_snippets_path` is being set after the plugin is loaded. I've tried changing locally the NVChad's luasnip snippets loading file to print the global `vim.g.vscode_snippets_path` and it is prints as `nil` initially. If I set `vim.g.vscode_snippets_path` at the root `init.lua` it does work as expected.

Basically, the `options.lua` (tried `charc.lua` too) is being called after the luasnip is setup.

**Comment by egaban** [comment]
What I've end up doing was creating a `luasnip.lua` file and adding

```lua
return {
  "L3MON4D3/LuaSnip",
  event = "InsertEnter",
  config = function()
    local nvim_config = vim.fn.stdpath "config"
    vim.g.vscode_snippets_path = nvim_config .. "/snippets"

    require "nvchad.configs.luasnip"
  end,
}
```

Maybe we should document that?

**Comment by siduck** [comment]
your options are loaded on startup where as luasnip is lazyloaded.

just checked, and its not nil. I hope you're not loading luasnip on startup.

https://github.com/user-attachments/assets/6d84cf55-286a-4a9c-9274-882fa98ea059

**Comment by siduck** [comment]
where are you loading your options file?

**Comment by egaban** [comment]
@siduck  I'm using the `lua/options.lua` file. I think I know the issue: to disable the Tab mapping on cmp, I've added it at `lua/plugins/cmp.lua` as 

```lua
return {
  "hrsh7th/nvim-cmp",
  opts = function()
    local config = require "nvchad.configs.cmp"
    config.mapping["<Tab>"] = nil
    return config
  end,
}
```

Maybe this is making luasnip be loaded before it should? I've tried setting cmp event to VeryLazy and InsertEnter, but still no luck :(

Also, thanks for the quick reply, and for maintaining such a great project :)

**Comment by siduck** [comment]
```lua
  opts = function(_, opts)
    opts.mapping["<Tab>"] = nil
  end,
  ```
  this should work too.
  
  Never put cmp at verylazy.. that will break the lazyloading :/ 
  
  You can join nvchad's discord and get help quicker there
