### ISSUE TITLE
Wrong which-key.nvim lazy key

### ISSUE THREAD

**Issue by maksz42** [siduck76/NvChad#3047]
While trying to write a simple plugin I found that which-key.nvim has `<c-r>` mapped in normal mode, but it should be mapped in insert mode
https://github.com/NvChad/NvChad/blob/f6025f0788880989484733c90deff07dff01ef02/lua/nvchad/plugins/init.lua#L60
https://github.com/folke/which-key.nvim?tab=readme-ov-file#registers

**Comment by maksz42** [comment]
Shouldn't `<c-r>` be still mapped but in insert mode?
```lua
keys = { "<leader>", { "<c-r>", mode = "i" }, "<c-w>", '"', "'", "`", "c", "v", "g" }
```

**Comment by siduck** [comment]
the user can add that, i wont add each and every key that opens up whichkey!
