### ISSUE TITLE
LSP parameter hint

### ISSUE THREAD

**Issue by moooooo16** [siduck76/NvChad#3053]
Hi,

Is there any way to change the parameter hint format?
![Screenshot 2024-10-17 at 20 23 50](https://github.com/user-attachments/assets/5164d575-731c-4f44-b276-009b07147860)
Above is a screen shot from pyright LSP's parameter hint effect.

Thanks!

**Comment by siduck** [comment]
i dont think so. I just use the default signature_help() from vim.lsp . You can look at advanced plugins like signature.nvim
