### ISSUE TITLE
Issue with lua-language-server

### ISSUE THREAD

**Issue by tmoutinho** [siduck76/NvChad#3055]
Hey, 

Thanks for the work with NvChad, its pretty awesome.
I am new to neovim and tried to install nvchad but getting an error after saving a file.

I am following this youtube video https://www.youtube.com/watch?v=8um8OYwvz3c

<img width="1103" alt="Captura de ecrã 2024-10-18, às 13 48 39" src="https://github.com/user-attachments/assets/3c439f6b-7a43-4259-84a7-2459466adcd4">

Thanks for any help and amazing job.

**Comment by siduck** [comment]
open nvim, run MasonInstallAll command

**Comment by tmoutinho** [comment]
Thanks @siduck that fixed it. Why does the file appears with a red icon?

<img width="222" alt="Captura de ecrã 2024-10-18, às 15 45 24" src="https://github.com/user-attachments/assets/551a615d-b043-4bc8-9397-7974158ff348">

**Comment by siduck** [comment]
nvimtree has git integrations so files which have changed will have different color etc
