### ISSUE TITLE
Error on nvchad installation: attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by gidigal** [siduck76/NvChad#3056]
I am trying to install nvchad. When I run this command:
git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
The output is:
Error detected while processing /home/gidi/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/gidi/.config/nvim/init.lua:7: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/gidi/.config/nvim/init.lua:7: in main chunk
My nvim version is 0.7.2 (tried to follow the recommendation to install the most recent release of neovim, but it did not solve this issue).

I will be grateful for any ideas how to solve this. Thanks :-)

**Comment by siduck** [comment]
use neovim v0.10!

**Comment by gidigal** [comment]
I don't have much experience with apt. When I run "sudo apt-get install neovim"  it installs v0.6.1.
I tried running "sudo apt-get install neovim=v0.10" and got 
E: Version 'v0.10' for 'neovim' was not found
Same error for v0.10.0

**Comment by siduck** [comment]
you should either  compile nvim from source or use appimage or nvim binary from nvim releases or a neovim version manager

**Comment by lumattr** [comment]
If your no longer publishing updates to the debian package, please remove it from your documented installation steps. Just installed and encountered this error.
