### ISSUE TITLE
Auto complete is not working

### ISSUE THREAD

**Issue by gidigal** [siduck76/NvChad#3059]
Hello,
I am following [this video ](https://youtu.be/lsFoZIg-oDs?t=379) in order to work with nvchad.
When I type "st" autocomplete does not propose "std" in its list of options.
When I type "std::cout" and hit enter it does not add the required "include" statement.
I am working with nvchad 2.0, as this video does not  support nvchad 2.5.
How do I solve this ? Thanks :-)

**Comment by siduck** [comment]
enable clangd lsp . And switch to nvchad v2.5 ,v2.0 is dead.

**Comment by siduck** [comment]
please read all of nvchad.com, then you can add support for any language
