### ISSUE TITLE
Error while installing NVChad on Debian 12.

### ISSUE THREAD

**Issue by MaayerAli** [siduck76/NvChad#3060]
I was installing NVChad on Debian 12, but then it returned this error:
Error detected while processing /home/maayerali/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/maayerali/.config/nvim/init.lua:7: attempt to index field 'uv'
 (a nil value)

I am using Debian Trixie Repos btw since Sid repos don't work for me :/
![Screenshot_2024-10-20_12-27-43](https://github.com/user-attachments/assets/633b2daf-ecdb-4636-a581-3babb29bb65f)

**Comment by siduck** [comment]
use v0.10 at least.

**Comment by MaayerAli** [comment]
How? Neovim 0.10 is not on Debian Trixie Repos in my experience

**Comment by MaayerAli** [comment]
Could you tell me a better solution?

**Comment by siduck** [comment]
use a neovim version manager or use the nvim binary/appimage from nvim releases

**Comment by MaayerAli** [comment]
What's a neovim version manager?

**Comment by MaayerAli** [comment]
Thank you so much! i thought I would have to use another Neovim Distrobution.

**Comment by siduck** [comment]
> Thank you so much! i thought I would have to use another Neovim Distrobution.

when i was in debian, i used to use mpr , it has latest nvim too! https://mpr.makedeb.org/packages?O=0&K=neovim

its like aur but for debian
