### ISSUE TITLE
WinResized Autocommand Error When Opening Terminal Split Before 

### ISSUE THREAD

**Issue by micahkepe** [siduck76/NvChad#3065]
<img width="1237" alt="Screenshot 2024-10-23 at 1 26 06 PM" src="https://github.com/user-attachments/assets/15b56b85-49d5-45f5-8b77-bc502c7f260a">

**To replicate**:
- Have NVDash configured to open on startup 
- Open Neovim but do not open any files 
- Create a terminal buffer with `<leader>h`

**Comment by siduck** [comment]
do lazy sync
