### ISSUE TITLE
Bug: looks like NvChad cannot support to run the native vim command. like :Explore :tabnew

### ISSUE THREAD

**Issue by jpixy** [siduck76/NvChad#3066]
I try to run `:Explore` to open default file explore, (I know there is <c - n>)
and try to run `:tabnew` 

I found both command got fail.

I have no ideas why it happened. I think it is better to allow users to use the native vim commands. 

Thanks.

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/636ae8dc-6c8d-4426-a162-0b3a8d9eedea)

go uncomment netrw in your lazy config. or just use nvimtree
