### ISSUE TITLE
vim.lsp.buf_get_clients() is deprecated

### ISSUE THREAD

**Issue by HugoPhi** [siduck76/NvChad#3069]
The original project is currently archived, but the latest Lua API is incompatible with its API. This causes a minor issue, leading to the following error:

```bash
vim.lsp.buf_get_clients() is deprecated. Feature will be removed in Nvim 0.12
```

![image](https://github.com/user-attachments/assets/0c4bed44-0b49-412e-85b9-ac96c31a3619)

To investigate, I used the command `:checkhealth vim.deprecated`, which provided the following details:

```bash
==============================================================================
vim.deprecated:                       require("vim.deprecated.health").check()

 ~
- WARNING vim.lsp.buf_get_clients() is deprecated. Feature will be removed in Nvim 0.12
  - ADVICE:
    - use vim.lsp.get_clients() instead.
    - stack traceback:
        /home/tibless/.local/share/nvim/lazy/symbols-outline.nvim/lua/symbols-outline/providers/nvim-lsp.lua:41
        /home/tibless/.local/share/nvim/lazy/symbols-outline.nvim/lua/symbols-outline/providers/init.lua:15
        /home/tibless/.local/share/nvim/lazy/symbols-outline.nvim/lua/symbols-outline.lua:161
        /home/tibless/.local/share/nvim/lazy/symbols-outline.nvim/lua/symbols-outline.lua:19
```

![image](https://github.com/user-attachments/assets/27f9eeaa-5697-4b1b-bf12-2b358bc932cb)

Based on the information provided, I resolved this by editing the source file located at `~/.local/share/nvim/lazy/symbols-outline.nvim/lua/symbols-outline/providers/nvim-lsp.lua`. The necessary modification involves a simple replacement:

```lua
  -- local clients = vim.lsp.buf_get_clients(bufnr)  -- deprecated
  local clients = vim.lsp.get_clients()  -- new
```

This change resolved the issue. However, I’m concerned about making this modification manually, as it may affect future updates with Lazy. Is there a recommended approach for handling such deprecations in archived projects without compromising update compatibility?

**Comment by siduck** [comment]
you should make a PR to that plugin and change it.
