### ISSUE TITLE
Current line and column in status line in default theme

### ISSUE THREAD

**Issue by Bazulenkov** [siduck76/NvChad#3075]
This is my chadrc.lua

```lua
---@type ChadrcConfig
local M = {}

M.base46 = {
  theme = "onenord",
}

M.ui = {
  statusline = {
    -- modules arg here is the default table of modules
    overriden_modules = function(modules)
      table.insert(modules, " Ln %l, Col %c")
    end,
  },
}
return M
```

But I do not see the cursor position in status line.

I take this code from #1562 
Also I have read [#121](https://github.com/NvChad/ui/issues/121)

I can not find any references for "overriden_modules".

How can I add cursor position in default theme in the newest NvChad?

**Comment by Bazulenkov** [comment]
I have found https://github.com/NvChad/ui/issues/254

overriden_modules - was deprecated.

I'm newbie in lua and resently have installed NvChad.
I will be graful if somebody help me to edit "cursor" module.

**Comment by siduck** [comment]
read :h nvui.statusline and add your custom module to order

**Comment by aryanjassal** [comment]
This is what I have done to achieve something similar in my setup. @Bazulenkov 

```lua
--- chadrc.lua
M.ui = {
  statusline = {
    theme = "vscode_colored",
    order = { "mode", "git", "diagnostics", "%=", "cursor", "lsp" },
    modules = {
      cursor = function()
        return "%#StText# %l:%c "
      end,
    },
  },
}
```

**Comment by siduck** [comment]
@aryanjassal  if you have 0 logic in your module then just you can use a string instead of function, like

`cursor = "blabla"`
