### ISSUE TITLE
Error when trying to select a theme

### ISSUE THREAD

**Issue by aryanjassal** [siduck76/NvChad#3078]
### Description

When I press enter to select a theme using the new `volt` theme selector, it gives me the following error:

```
E5108: Error executing lua: ....local/share/nvim/lazy/ui/lua/nvchad/themes/mappings.lua:23: attempt to index field 'base46' (a nil value)
stack traceback:
        ....local/share/nvim/lazy/ui/lua/nvchad/themes/mappings.lua:23: in function <....local/share/nvim/lazy/ui/lua/nvchad/themes/mappings.lua:19>
```

I have ensured that `base46` exists. I have updated all the plugins, too. A similar error happens when I press escape inside the selector.

```
E5108: Error executing lua: ...user/.local/share/nvim/lazy/ui/lua/nvchad/themes/init.lua:128: attempt to index field 'base46' (a nil value)
stack traceback:
        ...user/.local/share/nvim/lazy/ui/lua/nvchad/themes/init.lua:128: in function 'after_close'
        /home/user/.local/share/nvim/lazy/volt/lua/volt/utils.lua:64: in function 'close'
        /home/user/.local/share/nvim/lazy/volt/lua/volt/init.lua:85: in function </home/user/.local/share/nvim/lazy/volt/lua/volt/init.lua:84>
```

### Steps to reproduce
1. Open `nvim`
2. Open theme selector using `<leader>th`
3. Select a theme
4. Press `<cr>` or `<esc>`

### Evidence

https://github.com/user-attachments/assets/2410d59d-7fd9-476c-8ac4-47c0f419edd8

### System info
**OS**: NixOS 24.05
**Neovim version**: v0.10.1

**Comment by siduck** [comment]
Move all your theme related options to M.base46 . Its even pinned issue on this repo. And mentioned in the nvui news page :/

https://nvchad.com/news/nvui

**Comment by aryanjassal** [comment]
> Move all your theme related options to M.base46 . Its even pinned issue on this repo. And mentioned in the nvui news page :/
> 
> https://nvchad.com/news/nvui

Ah, I had missed migrating one of the `hl_` tables. However, this raised another interesting issue. I had not set the theme name in my config file anywhere, but it still somehow worked with my themes. However, after the migration, I still got an error saying that it could not find `name` somewhere.

I went source code digging and realised that I need the theme name to be set when running the theme switcher. After setting it, everything works. But, shouldn't adding the field if it doesn't exist be the default behaviour, instead of throwing a (possibly) cryptic error?

I'm not sure if this should be implemented or not, so I left this as a comment. I can make this into an issue if you want to track this as one, or keep it closed if the current behaviour is intentional.

**Comment by siduck** [comment]
> , shouldn't adding the field if it doesn't exist be the default behaviour, i

No, i dont want to add that lvl of complexity to the codebase, that'd require reading the table and checking if it has theme opt or not, then writing to the file, and probably would break formatting too. theme variable is a required field if you want the theme switcher else dont use the theme switcher
