### ISSUE TITLE
Uncommenting multiple CPP lines just comments them again

### ISSUE THREAD

**Issue by ReKylee** [siduck76/NvChad#3081]
I am fairly new to nvim, and I don't why it might even behave this way.
Screenshots:

![{6FB2DAA6-D78A-465B-ABA2-C887626DB911}](https://github.com/user-attachments/assets/ba339678-549a-4640-b798-aabd5be7ddcd)

After using ```<leader>-/```
![{4E57D42E-5F73-4E44-B674-D2B29164AFAF}](https://github.com/user-attachments/assets/63fd2dec-42a6-49bb-bf29-ad7863643d26)

It doesn't recognize it as a commented block for some reason?

**Comment by siduck** [comment]
nvchad just uses nvim's inbuilt comment mappings
![image](https://github.com/user-attachments/assets/b4cff5ef-f036-4772-b472-710ae2ad62ae)

i think it does linewise commenting instead of block.
