### ISSUE TITLE
Mason ignores config

### ISSUE THREAD

**Issue by mishka173** [siduck76/NvChad#3084]
Just started with NvChad. For some reason Mason ignores ensure_installed option in plugins/init.lua. I am not sure that just adding Mason config is enough, but other plugins work normal 

 ```
{
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "gopls",
        "clangd",
      },
    },
  },
```
when I exec :MasonInstallAll it does nothing.

And also i dont understand why it installed stylua and lua LSP, css-lsp, html-lsp. How i can find this default options that NvChad use

I'v also seen in tutorails that in older versions there was commented mason config in plugins/init.lua and treesitter. Now there is just treesitter. So... maybe I`m doing something wrong...

**Comment by siduck** [comment]
please read :h nvui.mason
