### ISSUE TITLE
Keymaps for cmp not working

### ISSUE THREAD

**Issue by theTechGoose** [siduck76/NvChad#3085]
This is my config. In the plugins.lua im calling M.plugin its just set up this way so each plugin can have its own file.
none of the print statements in the mappings fire so somehow the mapping is just not getting registered.

local M = {}

function on_start(_, opts) 
local cmp = require "cmp"
local luasnip = require "luasnip"
local utils = require "utils"
local options = {
  mapping = {
    ["<Tab>"] = cmp.mapping(function(fallback)
      print('dookster')
      print('**********************************************************************************')
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end, { "i", "s" }),
  },
}

local function load_mappings() 
vim.keymap.set('i', '<C- >', '<CMD>lua require("cmp").complete()<CR>', {noremap = true})
end

options = vim.tbl_deep_extend("force", opts, options)
require("cmp").setup(opts)
load_mappings()
end

M.plugin = {
'hrsh7th/nvim-cmp',
 config = on_start,
 event = "InsertEnter",
}

return M

**Comment by siduck** [comment]
please format your code, its unreadable...

**Comment by siduck** [comment]
looks like your config issue, cmp mappings must be in its mapping table, not vim.keymap.set
