### ISSUE TITLE
Indent Blankine highlight changes style when switching themes

### ISSUE THREAD

**Issue by n6v26r** [siduck76/NvChad#3086]
When switching the theme (or just playing with the switcher menu), the `@ibl.scope.underline.1` highlight becomes underlined.

How it looks before switching themes:
![2024-11-09-182011_1920x1080_scrot](https://github.com/user-attachments/assets/fe9d175e-cdc4-4c6a-baec-3b31268ca00d)
How it looks after:
![2024-11-09-181949_1920x1080_scrot](https://github.com/user-attachments/assets/15f32e11-3b29-4d20-b6b6-ec6ade5f471f)

There also seems to be something weird going on with spaces after a theme switch, but I'm not sure (indent lines appear where there aren't supposed to be any)

**Comment by siduck** [comment]
that is normal, since the release of v3.0 of blankline, it became difficult to reload its theme.  Nothing i can do about. just reopen nvim

**Comment by n6v26r** [comment]
@siduck Couldn't the plugin be reloaded automatically when rebuilding theme cache? (With an event for example)

**Comment by siduck** [comment]
> @siduck Couldn't the plugin be reloaded automatically when rebuilding theme cache? (With an event for example)

i dont want to add such edgecases in base46. just reopen nvim, not of a big deal
