### ISSUE TITLE
how to load mappings ?

### ISSUE THREAD

**Issue by SH-ke** [siduck76/NvChad#3093]
i'm sorry, i am a beginner for neovim, i learned nvchad from this video, [ The perfect Neovim setup for Python ](https://www.youtube.com/watch?v=4BnVeOUeZxc)

and, i learned the nvchad configs in this video, but i found something in trouble. it seems that nvchad has changed its dir structure. i want to set the dap mappings (or other plugin mappings as well ) into nvchad. there is a loadmappint() method in the past , for example
      -- require("core.utils").load_mappings("dap_python")

but, it seems deprecated, so i wonder is there any recommended way to replace this operation, or other ways to add the mapping easily and elegantly

**Comment by siduck** [comment]
no need to use load_mappings(), just use the native way https://nvchad.com/docs/config/mappings
