### ISSUE TITLE
[help request] A space(padding) in beginning of each line, how to cancel it

### ISSUE THREAD

**Issue by EssenSea** [siduck76/NvChad#3099]
here is what i said "space": 
![screenshot_2024-11-13-151731](https://github.com/user-attachments/assets/cbebbec7-a339-4710-8ff1-933e98ab3225)

and here is what I want: 
![screenshot_2024-11-13-152015](https://github.com/user-attachments/assets/09b53c4f-1956-4594-b713-b24a5e59fb16)

And I've tried 'Dynamic terminal padding'(kitty),  seems not it. kitty's padding was conf to 0.

Newbie in any of computer science, but love nvchad, hope could get some advices. THX!

**Comment by siduck** [comment]
disable signcolumn option :thinking:

**Comment by EssenSea** [comment]
> disable signcolumn option 🤔

THX for help!
