### ISSUE TITLE
LSP colors don't properly apply?

### ISSUE THREAD

**Issue by SaverinOnRails** [siduck76/NvChad#3100]
Hi, i'm new to this config, and no matter what base46 theme i chose, colors on variable declartions, function parameters e.t.c stay the same across all languages. It sometimes makes it difficult to even notice the highlighting.
![Screenshot_14-Nov_08-11-43_2](https://github.com/user-attachments/assets/ea54c4e9-cca7-44c0-8afc-d32bf911bf03)
![Screenshot_14-Nov_08-11-25_10001](https://github.com/user-attachments/assets/a972e149-4e92-44b4-bc84-089ea5a34e81)

This is my chadrc.lua config:
```
M.base46 = {
	theme = "wombat",
  transparency = true
	-- hl_override = {
	-- 	Comment = { italic = true },
	-- 	["@comment"] = { italic = true },
	-- },
}

```
Am i doing something wrong perhaps? Many thanks.

**Comment by siduck** [comment]
install treesitter parsers for every language, use TSInstall command

**Comment by kumkee** [comment]
> install treesitter parsers for every language, use TSInstall command

Is there a place in the config where I can set auto-installation of my treesitter parsers?

**Comment by siduck** [comment]
> > install treesitter parsers for every language, use TSInstall command
> 
> Is there a place in the config where I can set auto-installation of my treesitter parsers?

https://nvchad.com/docs/config/plugins
