### ISSUE TITLE
 When I type nvim, the menu is not displayed.

### ISSUE THREAD

**Issue by Tzlzl12** [siduck76/NvChad#3102]
![Snipaste_2024-11-15_16-24-35](https://github.com/user-attachments/assets/18c3963c-0ee6-4d79-908c-2a348f7fda64)
![Snipaste_2024-11-15_16-24-22](https://github.com/user-attachments/assets/3fdd76e0-e6b3-42b2-9861-7da9a420b9e2)
The second picture is the result of typing nvim
I did not make any changes to the contents of the nvim folder.

**Comment by siduck** [comment]
enable nvdash on startup, please read :h nvui
