### ISSUE TITLE
how to enable nvdash O.O

### ISSUE THREAD

**Issue by D3B-0x0** [siduck76/NvChad#3107]
Hewwo again NvChad devs! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

### ૮ ˶ᵔ ᵕ ᵔ˶ ა Issue: Nvdash Documentation is Making Me Go (╥﹏╥)

(˃ᆺ˂) Hewwo wonderful developers-sama! *notices your amazing work on NvChad* 

### ᗦ↞◃ What's twoubling me (｡•́︿•̀｡):
- We can use `:Nvdash` command (✧ω✧) so sugoi!
- Documentation says "check nvconfig.lua" (◕︿◕) but whewe is it?
- Can ovewwide fwom chadwc... but how? (●´⌓`●)

**_(╯°□°）╯︵ ┻━┻ The pwoblems making me go nya~:
1. nvconfig.lua is playing hide and seek! ⊙﹏⊙
2. *searches everywhere like lost neko* whewe do we put the config? (◕︿◕✿)
3. nyo examples in documentation (┛◉Д◉)┛彡┻━┻
4. *sad keyboard noises* ｡:ﾟ(;´∩`;)ﾟ:｡_**

### (づ｡◕‿‿◕｡)づ What we nyeed:
- Whewe is the mystewious nvconfig.lua hiding? (=^･ｪ･^=)
- Ow maybe update docs with correct way? (◕ᴗ◕✿)
- Show us how to make Nvdash go brrr on startup! ٩(◕‿◕｡)۶
- Give us the sacred override syntax! (ﾉ≧∀≦)ﾉ

### Awigato for your time, senpai! (◍•ᴗ•◍)❤

P.S.: Your code is more kawaii than a basket of kittens! (｡♥‿♥｡)
P.P.S.: NvChad is sugoi desu ne! (◕‿◕✿)

_*Nuzzles the submit button* UwU_

~ Youw fwiendly NvChad usew who just wants their dashboard to work (ノ∀`♥)

**Comment by siduck** [comment]
```lua
M.nvdash = {
      load_on_startup = true 
  }
  
 ```
 
 i added the nvconfig file url in the doc now

**Comment by siduck** [comment]
btw that option is documented in :h nvui.chadrc.options too

**Comment by D3B-0x0** [comment]
thankewww 👉👈

**Comment by siduck** [comment]
whatever language you're speaking, its not fun :neutral_face:

**Comment by D3B-0x0** [comment]
> whatever language you're speaking, its not fun 😐

alright...lmao where do i put the config lines you said? chadrc?? ughh i did use it there but no fix

**Comment by D3B-0x0** [comment]
> > whatever language you're speaking, its not fun 😐
> 
> alright...lmao where do i put the config lines you said? chadrc?? ughh i did use it there but no fix

umm do i have to use any startup prompt with nvim or so?? i use hyprland so its set to ```bind = Super, Z, exec, wezterm -e nvim # Launch Neovim (editor)```

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/8ad29593-7150-452a-a104-034174837217)

**Comment by siduck** [comment]
> > whatever language you're speaking, its not fun 😐
> 
> alright...lmao where do i put the config lines you said? chadrc?? ughh i did use it there but no fix

yes chadrc

**Comment by D3B-0x0** [comment]
> ![image](https://github.com/user-attachments/assets/8ad29593-7150-452a-a104-034174837217)
> 
> 

Very much thanks🙏🏼
