### ISSUE TITLE
Add vimplug by default ?

### ISSUE THREAD

**Issue by NicTanghe** [siduck76/NvChad#3109]
Hello I`ve forgone installing several plugins becouse the gh pages list install via vimplug.

It is highly unclear to me if both can work at the same and after looking at how mason whould handle installing plugins i found nothing.

**Comment by siduck** [comment]
read nvchad.com

nvchad/starter must be installed, which uses this repo as a plugin

**Comment by siduck** [comment]
and i use lazy.nvim in nvchad not vimplug
