### ISSUE TITLE
Treesitter is not working in the main text.

### ISSUE THREAD

**Issue by Tzlzl12** [siduck76/NvChad#3110]
It works in the preview, 
![Snipaste_2024-11-23_21-11-14](https://github.com/user-attachments/assets/74da8e34-3fc6-4e7e-bf99-a063aad93234)

but once I enter, it stops working.
![Snipaste_2024-11-23_21-11-22](https://github.com/user-attachments/assets/b9962f43-456c-49d4-9ad0-4cb43e191bc8)

**Comment by Tzlzl12** [comment]
There is no issue with Lua rendering. 
The highlighting in the preview is exactly the same as in the main text.

**Comment by Tzlzl12** [comment]
ok ,finished
miss 
```lua
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
```

**Comment by siduck** [comment]
this is not required, what have you done to treesitter lazy spec?
