### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by ADiamondChanger** [siduck76/NvChad#3113]
I was minding my OWN BUSINESS when the fuzz walked by...

The error:
`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter.lua:421: Parser could not be created for bugger 29 and language "markdown"
stack traceback:
                [C]: in function 'assert'
                /usr/share/nvim/runtime/lua/vim/treesitter.lua:421: in function 'start'
                /usr/share/nvim/runtime/lua/vim/lsp/uti;.lua:1570: in function 'open_floating_preview'
                /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:465: in function 'signature_help'
                /username/.local/share/nvim/lazy/ui/lua/nvchad/signature.lua:7: in function 'handler'
                /usr/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function ''
                vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue`

**Comment by siduck** [comment]
hmmmthis isnt a nvchad issue,  treesitter related
