### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by palandovalex** [siduck76/NvChad#3114]
- WARNING vim.lsp.get_active_clients() is deprecated. Feature will be removed in Nvim 0.12
  - ADVICE:
    - use vim.lsp.get_clients() instead.
    - stack traceback:
        /home/lexsilentium/.local/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:171
        /home/lexsilentium/.local/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:210
    - stack traceback:
        /home/lexsilentium/.local/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:171
        /home/lexsilentium/.local/share/nvim/lazy/ui/lua/nvchad/statusline/default.lua:210
        [C]:-1
        /usr/share/nvim/runtime/lua/vim/health.lua:353
        nvim>:1

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/e21fbfd7-dc89-4f2a-8559-4983fcaed2c4)

update your plugins. i use the new function
