### ISSUE TITLE
Improvment: Batch "Config Change Detected" messages

### ISSUE THREAD

**Issue by Kennedy242** [siduck76/NvChad#3115]
When the `init.lua` file is edited and saved multiple times, then you switch back to an already open nvim session, config reloaded is displayed as many times as the `init.lua` file was saved. 

Would it be a possible improvement to batch these messages and show only once?

Steps to recreate:

1. Open `~/.config/nvim/init.lua` in nvim
2. Open another file in nvim
3. Make a change in the `init.lua` file, save the file. Repeat 6 times
4. Go to the other nvim session and see the config reloaded message 3 times after pressing enter 3 times.

![image](https://github.com/user-attachments/assets/0053bbff-a4e5-4502-ac64-5c14d1910d4e)

> I know this is a super NIT. One shouldn't be editing their config this much... but here we are. Just wanted to mention

**Comment by siduck** [comment]
thats related to lazy.nvim , i dont handle that part. i think lazy has an option to disable this
