### ISSUE TITLE
Support for rainbow pairs

### ISSUE THREAD

**Issue by oz123** [siduck76/NvChad#3117]
I am very fond of nvchad, and I spend quite a while using it. But I am really missing something like :

https://github.com/junegunn/rainbow_parentheses.vim/

I tried also :

https://gitlab.com/HiPhish/rainbow-delimiters.nvim

But both seem to not work with nvchad.

**Comment by siduck** [comment]
please know that nvchad does lazy=true by default. to load a plugin on startup either do lazy=false or verylazy event. or lazyload appropriately...  https://nvchad.com/docs/config/plugins
