### ISSUE TITLE
How do I make NVChad transparent???

### ISSUE THREAD

**Issue by MaayerAli** [siduck76/NvChad#3120]
I am an endeavourOS user and I am wondering how to make nvchad transparent.

**Comment by siduck** [comment]
read :h nvui. there's a transparency option in base46 table

**Comment by siduck** [comment]
M.base46 ={
 transparency = true
 }

**Comment by MaayerAli** [comment]
Which file do I put this in???

**Comment by siduck** [comment]
chadrc.  i  advise you to read of nvchad.com and :h nvui :/
