### ISSUE TITLE
Bluescreen when installing NvChad on Windows

### ISSUE THREAD

**Issue by anamoyee** [siduck76/NvChad#3121]
While i'd like to provide as much helpful information as possible, there is just none that i can think of other than the system info? Windows 10 Pro 22H2 (Build 19045).

Steps to reproduce:
- install neovim for windows
- install nvchad for windows
- run neovim

After 15-20 seconds when it installs, it just bluescreens? I really hope i can get this working because i want to try something else than vscode... this has been an issue for at least 3 months, where i got the same issue but i think i just posted on reddit on r/neovim which everybody promptly ignored. today i tried again

Below is the weird looking bluescreen as it somehow appears as transparent and the only thing that's visible behind it is the terminal which ran neovim that caused the crash:
![IMG_20241204_213015650](https://github.com/user-attachments/assets/61f6ebac-f282-4c88-a116-d34642019524)

3 months ago the issue and error code were the same but the bluescreen was regular, like: not transparent

**Comment by siduck** [comment]
enable true color support in terminal

**Comment by anamoyee** [comment]
I am using "Windows Terminal" which already has true color enabled, also why would lack of true color cause a bluescreen?

**Comment by anamoyee** [comment]
Update: I successfully installed nvchad by setting the variable "COLORTERM" to "truecolor", but surely, it's not right to bluescreen the computer if a color variable is set too conservatively for the terminal?

**Comment by siduck** [comment]
your terminal's responsible for weird colors

**Comment by siduck** [comment]
nvim needs truecolor support for all the modern themes etc u see. without it, you'll just have the actual   colors like blue etc
