### ISSUE TITLE
Hey, how do I make custom mappings?

### ISSUE THREAD

**Issue by MaayerAli** [siduck76/NvChad#3123]
Look I am sorry this isn't a bug, but I checked every where and there wasn't any help. Just tell me how to make custom mappings. That would be heavily appreciated. This is probably a very simple thing to do but I don't know how to make custom bindings.

**Comment by siduck** [comment]
https://nvchad.com/docs/config/mappings

**Comment by MaayerAli** [comment]
Turns out I didn't have lua-language-server installed. After Installing it, it works. I read the documentation and used the correct mappings. I just didn't have lua-language-server installed.
