### ISSUE TITLE
Option to disable all icons in NvChad

### ISSUE THREAD

**Issue by jitvrdon-cen64924** [siduck76/NvChad#3124]
# Option to disable all icons in NvChad

Hello,

I would like to inquire if it's possible to disable all icons in NvChad. The reason is incompatibility with my terminal client, even though I have Nerd Fonts installed.

## Current situation

- I have NvChad and Nerd Fonts installed
- Icons are not displaying correctly in my terminal client
- This is causing issues with the user interface

## Requested feature

An option to globally disable all icons in NvChad, so that only text is displayed instead.

## Additional information

- NvChad version: v2.5_release
- Operating system: Linux - TalosOS
- Terminal client: coder.com - basically some sort of alternative to *gotty* (I mean in regards to terminal functionality, otherwise coder.com is a complex platform)

Thank you in advance for considering this request and any potential assistance.

**Comment by siduck** [comment]
use latest version of nerdfonts, you cant disable icons in nvchad
