### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by Cr7pt0nic** [siduck76/NvChad#3127]
Every time I execute NvChad during startup I have a consistent error that occurs when starting NvChad
![image](https://github.com/user-attachments/assets/0cb39232-5d08-479e-a5d6-6c4fddf5037a)
Here is the section from line 80 in utils.lua
![image](https://github.com/user-attachments/assets/db547360-04cd-4bea-9425-e2a180e6debe)

**Comment by siduck** [comment]
please use nvchad v2.5!! v2.0 is dead and depreceated

**Comment by Cr7pt0nic** [comment]
Never mind I seem to have fixed the issue by including "M.mappings = require "custom.configs.mappings"" into my chadrc.lua configuration
