### ISSUE TITLE
v2.0 to v2.5 migration error

### ISSUE THREAD

**Issue by Cr7pt0nic** [siduck76/NvChad#3128]
Using the NvChad v2.5 migration (Unix only) script has broken my plugins.lua configuration for nvim-dap.
![image](https://github.com/user-attachments/assets/d9e58ab0-d6b3-4fde-be1d-18b6768430f4)
Any way to resolve this issue?

**Comment by siduck** [comment]
remove that code. just load mappings via vim.keymap.set

**Comment by Cr7pt0nic** [comment]
> remove that code. just load mappings via vim.keymap.set

I am not worried about the mappings I'm specifically talking about the custom plugins

**Comment by Cr7pt0nic** [comment]
Also you closed the thread without properly helping to resolve the issue

**Comment by siduck** [comment]
> Also you closed the thread without properly helping to resolve the issue

v2.5  was released ages ago. Everyone knows that core.utils stuff is no longer being used You havent read even the news section at nvchad.com

**Comment by siduck** [comment]
> > remove that code. just load mappings via vim.keymap.set
> 
> I am not worried about the mappings I'm specifically talking about the custom plugins

doesnt matter. dont you know how to define mappings in nvim? vim.keymap.set function

just put them in your config func instead of using core.utils function or load all your mappings in your mappings file

**Comment by siduck** [comment]
https://nvchad.com/docs/config/mappings

**Comment by Cr7pt0nic** [comment]
> https://nvchad.com/docs/config/mappings

Like I said I am not talking about the mappings. I am specifically talking about the plugins. I already understand how the mappings work and I'm already currently modifying my mappings as we speak. I am only talking about the plugins and the plugins/custom/ configurations including the naming conventions specifically for the file paths as those have been entirely messed up. I already saw the news already which states that I need to specify "nvchad" instead of "plugin.configs".

**Comment by siduck** [comment]
those filepaths should be renamed as per the script. just remove the custom. strings ?
