### ISSUE TITLE
Failed to clone a lot of plugins on first launch

### ISSUE THREAD

**Issue by andr3i1010** [siduck76/NvChad#3131]
When i open neovim with the NvChad config, the plugins download but most of them fail with the error `fatal: unable to access 'https://github.com/plugin/name.git/': Could not resolve host: github.com`.
When i try to open the link to the repositories, they open normally without an error.

![image](https://github.com/user-attachments/assets/f288ef7b-6226-4b85-be72-e025d8f9269a)

**Comment by andr3i1010** [comment]
edit: after restarting neovim a lot of times it works. i have no idea why

**Comment by siduck** [comment]
your OS issue!
