### ISSUE TITLE
Poor color themes

### ISSUE THREAD

**Issue by emirmorris** [siduck76/NvChad#3132]
I have a problem with color schemes in Nvchad. 
None of themes can't provide full colors for different entities, such as variables and other elements. As if there are very few colors. Let's see and compare with VS code:

![CleanShot 2024-12-20 at 11 28 47@2x](https://github.com/user-attachments/assets/6bf1d867-f6ea-4310-b542-bebb72015f4e)
![CleanShot 2024-12-20 at 11 38 33@2x](https://github.com/user-attachments/assets/28bab4fb-518f-416c-8cea-24bb1f6a5852)

- console (from `console.log()`) and variables have the same color
- let, cost, swithc are the same
- !, &&, ||, >,<,== the same color with variables (just white)
- boolean and numbers are the same
- etc... just a simple example file with 16 lines

I tried to fix that problem few days ago. But cannot. 
Today I've installed ray.so and look at this:
![CleanShot 2024-12-20 at 11 24 04@2x](https://github.com/user-attachments/assets/65b03ac2-1ea0-4f90-9733-d9bda023ae5e)
I upset. Coz all examples looks much better that mine nvim. I love neovim and nvchad, but with complex syntax highlighting, my job would be more pleasant. 

I tried to disable Treesitter. It didn't help.  

I ask for help, give me a direction where I can solve this problem. Is it possible to solve it at all, or the themes do not have such functionality and are limited color scheme .

**Comment by emirmorris** [comment]
I tried others themes. Almost the same. The material-darker a liitle bit better and have another color for compare elements (>, &&, ||)

I also tried assigning different colors to different entities in cradrc.lua. This helped partially. But it feels like the theme has too few elements. For example, I colored a variables to red, and at the same time "console" got colored as well.

![CleanShot 2024-12-20 at 11 54 06@2x](https://github.com/user-attachments/assets/56b82ccb-a321-4f39-aa8d-dad4c978f442)

chadrc.lua:

```chadrc.lua
vim.cmd [[
  highlight clear Console
]]

M.base46 = {
  theme = "material-darker",

  hl_override = {
    ["@variable"] = { fg = "#FF0000" },
    ["@function"] = { fg = "#00FF00" },
    ["@keyword"] = { fg = "#FFFF00" },
    ["@method"] = { fg = "#FF00FF" },
    ["@string"] = { fg = "#FFA500" },
    ["@number"] = { fg = "#0000FF" },
    ["@comment"] = { fg = "#888888", italic = true },
    Console = { fg = "#FFA500" },
  }
}
```

**Comment by emirmorris** [comment]
I also noticed that when I restart Neovim, for a second "console" has a different color (orange), but then something overwrites it and it has the same color as the variable (red). What could be the problem?

https://github.com/user-attachments/assets/73ec7ce3-4982-4d1b-a884-65b24d9ed60f

**Comment by siduck** [comment]
the thing that overriwrites is lsp semantic highlighting. if you did not use our on_init() in your lspconfig then it will color by lsp.

**Comment by siduck** [comment]
Install treesitter parsers for the langauges

**Comment by emirmorris** [comment]
Thanks. I've used `on_init()` and it helps. I'm happy. 
![CleanShot 2024-12-20 at 16 00 56@2x](https://github.com/user-attachments/assets/0d8507e8-ea1a-4252-aeb9-713961de8cee)
