### ISSUE TITLE
Autocomplete doesn't work in command-mode

### ISSUE THREAD

**Issue by emirmorris** [siduck76/NvChad#3135]
Autocomplete in command mode doesn't work properly. 
Only if I press "TAB". But I wanna see suggestions while I typing.

https://github.com/user-attachments/assets/d35c5446-e181-4bb4-88f2-143683457ed5

I already tried to configure CMP.lua. Before it even didn't work if I pressed TAB. But now I have no idea how to see real-time suggestions while I typing. 

My config – https://github.com/emirmorris/NVChad

**Comment by siduck** [comment]
copy the cmdline code from here https://github.com/NvChad/NvChad/discussions/3033#discussioncomment-11625235 . 

you need that plugin for this

**Comment by emirmorris** [comment]
Thanks! It helped :)

**Comment by emirmorris** [comment]
> copy the cmdline code from here [#3033 (reply in thread)](https://github.com/NvChad/NvChad/discussions/3033#discussioncomment-11625235) .
> 
> you need that plugin for this

@siduck It helped. But now I can't accept the first element in command mode.
The "Enter" does not accept the first suggestion. Ctrl-Y does, but it is very inconvenient.

https://github.com/user-attachments/assets/6ba49259-2546-47a4-992e-ed072240c18d

https://github.com/supermaven-inc/supermaven-nvim/issues/123

**Comment by siduck** [comment]
press enter to accept
