### ISSUE TITLE
NvimTree Tab Opens on Left While Tree Opens on Right

### ISSUE THREAD

**Issue by phukon** [siduck76/NvChad#3137]
I'm experiencing an issue with NvimTree where the tree view opens on the right side of the Neovim window, but the tab heading appears on the left. This behavior is inconsistent and affects the workflow.

Steps to Reproduce:
- Configure NvimTree to open on the right side by setting view.side = "right".
- Observe that the tree view opens on the right, but the tab heading is on the left.

Here's my Neovim NvChad config -> [https://github.com/phukon/nvim-config](https://github.com/phukon/nvim-config)

![wedww](https://github.com/user-attachments/assets/5bb32847-47ff-4812-8049-2d1fa42d5cec)

**Comment by siduck** [comment]
nota nvchad issue. Please change the order in your tabufline.order field. go read h nvui!

**Comment by phukon** [comment]
Will do. Thanks! ✨
