### ISSUE TITLE
image preview for nvchad

### ISSUE THREAD

**Issue by kervanaslan** [siduck76/NvChad#3148]
Hi there,

I'm looking for a image viewer for nvim. I found this one : https://github.com/adelarsq/image_preview.nvim
But this plugin doesn't have a custom key binding feature and leader+p is reserved on NVChad.

Is there any plugin which works with NVChad?

I know this is not a NVchad issue but I wanted to ask because all NVChad experts are here.

**Comment by siduck** [comment]
<leader>p isnt reserved. its <leader>pt. Just map it.

and try image.nvim
