### ISSUE TITLE
When opening a `lua` file for the first time, `ftplugin/lua.lua` will be loaded twice.

### ISSUE THREAD

**Issue by JavaHello** [siduck76/NvChad#3154]
- `ftplugin/lua.lua`
```lua
-- ftplugin/lua.lua
print("hello")
```

```txt
# ~/.config/nvim
nvim
:e init.lua
:message
hello
hello
```

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/bfd91b24-aa1d-4e0a-893e-f219b127da21)

thats needed in userfilepost autocmd or else lspconfig wont attach lsp to buffer, cuz we're lazyloading lspconfig after uienter

If u want to stop this then remove nvchad.autocmds module loading in ur config and whichever plugins set by nvchad users user filepost autocmd, replace that with verylazy
