### ISSUE TITLE
Mason ensure isn't working

### ISSUE THREAD

**Issue by nixway** [siduck76/NvChad#3156]
Hi! I would like to upgrade to 2.5. But there is a problem with Mason `ensure_installed` option. I added configs following the example of the previous configuration:

![2024-12-31_12-48](https://github.com/user-attachments/assets/4b5b069d-8711-4946-8068-a694d4cc2620)

![2024-12-31_12-49](https://github.com/user-attachments/assets/26dd75bf-a1f9-43d6-9ae0-8a12272f47c6)

But in treesitter the `ensure_installed` option worked correctly. Can you tell me what is wrong with the Mason configuration?

**Comment by siduck** [comment]
read :h nvui.mason

put it in M.mason.pkgs table. Mason  never added that ensure_installed , i added it for the users but then moved it to chadrc opt

**Comment by nixway** [comment]
The packages listed in the table are installed only if they are used in any configuration. Debugpy is listed, but it is not installed because it is not mentioned in any configuration. The path to debugpy is used in nvim-dap:

```lua
function()
  local path = "~/.local/share/nvim/mason/packages/debugpy/venv/bin/python"
  require("dap-python").setup(path)
end,
```

Is it possible to fix this? Thanks!

**Comment by siduck** [comment]
@nixway currently only lspconfig, nvimlint andd conform are supported. Prs are welcome for nvimdap, check    src code of ui repos mason module and contribute!!!!!!!!!

**Comment by kumkee** [comment]
> put it in M.mason.pkgs table

Which file should this be in?
I tried `lua/configs/overrides.lua` and it didn't work.

**Comment by siduck** [comment]
> > put it in M.mason.pkgs table
> 
> Which file should this be in? I tried `lua/configs/overrides.lua` and it didn't work.

chadrc ofc

do read :h nvui and mason.pkgs isnt needed most of the time, masonInstallAll can detect the tools u use in ur config
