### ISSUE TITLE
Missing Special Characters on Clean Install

### ISSUE THREAD

**Issue by reeslabree** [siduck76/NvChad#400]
**Describe the bug**
Special Characters/Symbols missing from file explorer, headers, etc.

**To Reproduce**
1. Clean install of neovim 0.5.0
2. Clean install of NvChad
3. Start nvim
4. ctrl+n to open file explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/25036432/131182706-f9361547-93ad-4368-ab05-b6df69574bad.png)

**Desktop (please complete the following information):**
 - Ubuntu
 - OhMyZsh
 - Neovim 0.5.0

**Comment by siduck76** [comment]
@reeslabree you need to use a nerd font in your terminal , i.e set a nerdfont . I use JetBrainsMono Nerd Font
