### ISSUE TITLE
work directory changed after jump and jump back

### ISSUE THREAD

**Issue by tydra-wang** [siduck76/NvChad#546]
example project layout:

```
project_root
└── main
    └── main.py
```

Steps to reproduce the problem:

1.  enter vim on project_root and open main.py.
2. `gd`(or some other lsp keymaps) jump to a file out of  the work directory, like going to definition of `os.getenv('')` in main.py.
3. `:pwd` shows the work directory changed to the directory of python libs. 
4. `C-t` jump back to main.py
5. `:pwd` shows the work directory changed to `project_root/main/`

How can I keep the final work directory being `project_root/`?

**Comment by siduck76** [comment]
I think this is cause the  update_cwd is enabled
