### ISSUE TITLE
No Galaxy line for non focused windows

### ISSUE THREAD

**Issue by Mangeshrex** [siduck76/NvChad#55]
Why is there no statusline for the non focused window ? are there any special settings?

**Comment by siduck76** [comment]
> Why is there no statusline for the non focused window ? are there any special settings?

That's the feature , the inactive windows will just have thin lines as statuslines. This way it looks much cleaner, minimal and saves space.

**Comment by Mangeshrex** [comment]
Ahh ok so I can't get this in any other status line plugins? Also can you please drop the old galaxy line file?

**Comment by siduck76** [comment]
> Ahh ok so I can't get this in any other status line plugins? Also can you please drop the old galaxy line file?

wym old? you can ofc use other statuslines but it just make my neovim look much bloated 

with statuslines on inactive nvimtree

![image](https://user-images.githubusercontent.com/59060246/121778357-2fb6e800-cbb4-11eb-8f43-1a974fafecdb.png)

with statusliines as thin lines

![image](https://user-images.githubusercontent.com/59060246/121778377-46f5d580-cbb4-11eb-8df5-544d965a2053.png)

**Comment by Mangeshrex** [comment]
yes that makes my nvim slow too so i wanted to get that thing in mine i use staline. so you didnt do any  additional configurations for that ryt?

**Comment by siduck76** [comment]
> yes that makes my nvim slow too so i wanted to get that thing in mine i use staline. so you didnt do any additional configurations for that ryt?

Ig you need galaxyline for this , also nvim 0.5

**Comment by Mangeshrex** [comment]
hmm i have that version of galaxy line

**Comment by Mangeshrex** [comment]
Ill try this

**Comment by siduck76** [comment]
> Ill try this that command doesnt hides my status line but doesnt even throw any errors

Ig it works only for galaxyline , idk about others

**Comment by Mangeshrex** [comment]
Hmm ok

**Comment by Mangeshrex** [comment]
And by old statusline file I meant the old one which was round the status line conf which is there in the repo pictures

**Comment by siduck76** [comment]
> And by old statusline file I meant the old one which was round the status line conf which is there in the repo pictures

you can change that , just check statusline.lua file . I have changed lots of things now and I'll push it soon if this resolves https://github.com/akinsho/nvim-bufferline.lua/pull/119

**Comment by Mangeshrex** [comment]
Ahh ok

**Comment by siduck76** [comment]
I'll close this issue lol

**Comment by Mangeshrex** [comment]
yes
