### ISSUE TITLE
Problem with auto complete and diagosis

### ISSUE THREAD

**Issue by nataneb32** [siduck76/NvChad#551]
**Describe the bug**
Problem with diagnostics and auto complete. When writing and deleting characters cursor moves and line dont update. 

**To Reproduce**

1. Install nvim and NvChad.
2. Use purescriptls (did not test on other lsp)

**Expected behavior**
I  wanna be able to type.

**Screenshots**
![Peek 2021-10-13 18-01](https://user-images.githubusercontent.com/26772526/137212515-e2238a0a-ecb0-46e9-8834-2495b3d29a45.gif)

**Desktop (please complete the following information):**
 - Arch
 - Kitty
 - 0.6.0-dev+460-g6b9cb665f

**Comment by siduck76** [comment]
@nataneb32 when writing and deleting chars means that you're in the insert mode and diagnostics dont update in the insert mode by default .can you set this to true and recheck?

![image](https://user-images.githubusercontent.com/59060246/137234218-00d2cf6f-1964-45a0-8b3a-cebd7891af05.png)

**Comment by nataneb32** [comment]
> @nataneb32 when writing and deleting chars means that you're in the insert mode and diagnostics dont update in the insert mode by default .can you set this to true and recheck?
> 
> ![image](https://user-images.githubusercontent.com/59060246/137234218-00d2cf6f-1964-45a0-8b3a-cebd7891af05.png)

I see. I didn`t need to do that. The screenshoot is bad, but since it started working again i can reproduce.
