### ISSUE TITLE
Redundant options in configuration for nvim-tree

### ISSUE THREAD

**Issue by SystematicError** [siduck76/NvChad#564]
On [this line](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/nvimtree.lua#L56-L62) in the config for nvim-tree, diagnostics is disabled but the icons are declared for it anyways, whats the point of this?

**Comment by siduck76** [comment]
> On [this line](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/nvimtree.lua#L56-L62) in the config for nvim-tree, diagnostics is disabled but the icons are declared for it anyways, whats the point of this?

in case someone wants to have nvimtree diagnostics , he/she would have to use his custom config and could easily enable the diagnostics and edit the diagnostics icons . If we remove the diagnostic icons then the user would have to search up for nvimtree docs to get it work. If it doesnt seem ok then I'll remove it if you want :smiley:

**Comment by SystematicError** [comment]
Ah ok, makes sense, I'd recommend you put some sort of a comment on that line to indicate that :)
