### ISSUE TITLE
Conflicting <Leader>fb both find buffers and JumpMarks.

### ISSUE THREAD

**Issue by lkhphuc** [siduck76/NvChad#57]
In `telescope-nvim.lua`, L72
`vim.api.nvim_set_keymap("n", "<Leader>fb", [[<Cmd>lua require('telescope.builtin').buffers()<CR>]], opt)`

L80
`vim.api.nvim_set_keymap("n", "<Leader>fb", [[<Cmd> DashboardJumpMarks<CR>]], opt)`

**Comment by siduck76** [comment]
@lkhphuc thanks for reporting this mistake , its fixed now 7611d1390b7d58aaec485586705564b385385e4d
