### ISSUE TITLE
E5113: ErroraE5113: Error while calling lua chunk: /Users/${USER}/.config/nvim/init.lua:4: Error loading core

### ISSUE THREAD

**Issue by flexboni** [siduck76/NvChad#570]
**Describe the bug**
When i open some files in core directory, An error occurs.
I didn't edit anything, just opened it to check the contents.

**To Reproduce**
1. cd .config/nvim/lua/core
2. vi init.lua
3. Show error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/29271126/138387319-dd043594-5c36-4a78-9f6a-3dd5ab03ccd7.png)

**Desktop (please complete the following information):**
 - Operating System : MacOS Big Sur 11.4
 - Terminal : iTerm2 3.4.10
 - Version of Neovim : 0.5.1

**Additional context**

**Comment by flexboni** [comment]
First installed a month ago.
The first install also gave an error, so I deleted all the '.config/nvim/' directories and reinstalled it 2 hours ago today.

**Comment by peppapig450** [comment]
Mine also threw this error think this should help 
Error detected while processing VimEnter Autocommands for "*":
Feline needs 'termguicolors' to be enabled to work properly
