### ISSUE TITLE
weird lines in indentation lines

### ISSUE THREAD

**Issue by marbinuwusito** [siduck76/NvChad#58]
![Screenshot_20210614_122437](https://user-images.githubusercontent.com/72583007/121940631-8e42aa00-cd0b-11eb-8395-16f35568445e.png)
only happen in html files

**Comment by siduck76** [comment]
That's weird,  which terminal is it?

**Comment by marbinuwusito** [comment]
it's alacritty

**Comment by mTvare6** [comment]
What font is it and can you send the html file you are editing?

**Comment by marbinuwusito** [comment]
it's shuretecmono nerd font
the .html file is arbitray, happen in all files (sorry for bad english)

**Comment by siduck76** [comment]
> it's shuretecmono nerd font
> the .html file is arbitray, happen in all files (sorry for bad english)

this looks like alacritty and font issue , try asking it here https://github.com/lukas-reineke/indent-blankline.nvim

**Comment by marbinuwusito** [comment]
yes, i've tried in urxvt and works fine :c thanks for your time c:

**Comment by marbinuwusito** [comment]
only one more question, why in php files i have the autoindent and smart indent broken?
when i want to do a new line with enter or pressing the key "o" nvim don't respect the actual indentation and the cursor go to the beginning of the line
![Screenshot_20210615_012527](https://user-images.githubusercontent.com/72583007/122010800-b0bedc80-cd78-11eb-8e04-53d53d173d4f.png)

**Comment by siduck76** [comment]
> only one more question, why in php files i have the autoindent and smart indent broken?
> when i want to do a new line with enter or pressing the key "o" nvim don't respect the actual indentation and the cursor go to the beginning of the line
> ![Screenshot_20210615_012527](https://user-images.githubusercontent.com/72583007/122010800-b0bedc80-cd78-11eb-8e04-53d53d173d4f.png)

I havent faced this yet ,sorry Ive never tried neovim on php files . I'll take a look

**Comment by marbinuwusito** [comment]
thanks c:

**Comment by marbinuwusito** [comment]
thanks c:

**Comment by siduck76** [comment]
@marbinuwusito sorry I forgot to tell , autoindent or smartindent isnt enabled in NvChad! could you tell me your settings for it? Im new to vim so Idk much indenting :p

**Comment by ashincoder** [comment]
hey @siduck76  here is for smart indent `vim.bo.smartindent = true` -- Makes indenting smart

**Comment by ashincoder** [comment]
close the issue please

**Comment by siduck76** [comment]
@marbinuwusito add this in the misc-utils.lua file opt("b", "smartindent", true)

here 

![image](https://user-images.githubusercontent.com/59060246/122086567-72c9c300-ce21-11eb-87e3-856a3f696eb9.png)

**Comment by mTvare6** [comment]
> it's shuretecmono nerd font
> the .html file is arbitray, happen in all files (sorry for bad english)

I use alacritty, seems the same how it looks on other terminal with cozettevector
