### ISSUE TITLE
Hydra ASCII is not correct

### ISSUE THREAD

**Issue by isquack** [siduck76/NvChad#62]
The Hydra ASCII logo isn't correctly displayed on the bottom,please fix.

**Comment by siduck76** [comment]
> The Hydra ASCII logo isn't correctly displayed on the bottom,please fix.

could you show how it looks?

**Comment by ashincoder** [comment]
[Nvim Hydra](https://github.com/ashincoder/dotfiles/blob/master/.screenshots/nvim.png)

**Comment by ashincoder** [comment]
here is the unrendered pic of hydra in neovim

**Comment by isquack** [comment]
If take a look at the screenshot on the repo,the bottom part is having one block missing.i am not sure if that's intentional

**Comment by siduck76** [comment]
> [Nvim Hydra](https://github.com/ashincoder/dotfiles/blob/master/.screenshots/nvim.png)

this looks like a terminal issue , My st build lets me enable boxdraw for  brailie characters , idk how you'll do it in another terminals tho 

https://github.com/siduck76/st

 https://github.com/siduck76/st/blob/main/config.h#L88

**Comment by siduck76** [comment]
> If take a look at the screenshot on the repo,the bottom part is having one block missing.i am not sure if that's intentional

yes I removed the hydra text , check it here https://github.com/glepnir/dashboard-nvim/wiki/Ascii-Header-Text
