### ISSUE TITLE
Nvchad destroys your old config

### ISSUE THREAD

**Issue by isquack** [siduck76/NvChad#63]
Ya probably should be backing up the old config.
It's not that hard.ya just have to remove the line which warns you that your old config is gone and add these lines.
mv $HOME/.config/nvim  $HOME/.config/nvim.bak
And also tell the location of the backup.

**Comment by siduck76** [comment]
you can add a PR for this

**Comment by ashincoder** [comment]
Hey Close this issue. It is fixed. In commit #64 .
