### ISSUE TITLE
Would you like me to add commentary

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#65]
In your config I could add commenting setting. Using  `<leader>/` we can comment lines.
Would you like me to add it @siduck76

**Comment by siduck76** [comment]
Do we need to add a plugin for it?

**Comment by ashincoder** [comment]
yes

**Comment by ashincoder** [comment]
It is written in lua the plugin

**Comment by ashincoder** [comment]
Shall I do a PR @siduck76

**Comment by siduck76** [comment]
> Shall I do a PR @siduck76

yes , I'll check out the plugin and test it . I hope its config's easy and not bloated!

**Comment by ashincoder** [comment]
no only add 5 lines of code

**Comment by siduck76** [comment]
sure then!

**Comment by ashincoder** [comment]
There is nothing to config
Just add install the plugin and add a keybinding.

**Comment by ashincoder** [comment]
ok then

**Comment by ashincoder** [comment]
Hey @siduck76 I did the PR. Just check it out and say if it works well.
Closing

**Comment by ashincoder** [comment]
## how is it did u check it out
