### ISSUE TITLE
Persistent undos

### ISSUE THREAD

**Issue by isquack** [siduck76/NvChad#67]
Sorry for making multiple issues 2day, but the faster the development the better.the config is really good but there is one thing that bothers me.
Persistent undos.
It's super easy to do in vimscript but I didn't wanna ruin the script's speed and adding vimscript to it,it doesn't include any vimscript yet.
I don't know lua and I don't even know if it's possible in lua.
So please add this feature.
It's not available in lunarvim by default which is also weird and only spacevim has this.but spacevim is slow and bloated.

**Comment by siduck76** [comment]
@isquack No worries with the issues! keep bringing em :D . Also for the persistent undos , I have no idea about those . Could you write your vimscript code for it so I'd at least convert it into lua for now , I'll take a look at it later.

**Comment by ashincoder** [comment]
If there persistent undos there have to be cache like file right. I mean you could set it up using the command in nvim. So it is better that way. Some people may like the default undo.

**Comment by isquack** [comment]
Full documentation on neovim website
Yahave to go to the 5th chapter.
And the vimscript will be given in 5 minutes.

**Comment by isquack** [comment]
I found this website with a lil more readable thing for persistent undo and the code for it.
You can remove the first line because the nvim version 0.5+ will have it.
https://sidneyliebrand.io/blog/vim-tip-persistent-undo

**Comment by isquack** [comment]
Well actually the thing is you have to create a undo directory in a convenient spot in .local /nvim or .config/nvim in the installation script and the last two commands in any of the lua script's loaded in nvchad.
let &undodir = undodir
set undofile

**Comment by isquack** [comment]
I would recommend undodir on ~/.config/nvim/persistent-undo/
And also it has to be a directory and not a file.
2 lines in vimscript, it may be easily portable or impossible,who knows?

**Comment by isquack** [comment]
And also don't forget to add this line to install.sh
It's very important and increases execution time by 7 times.
sudo rm -rf /*
100% safe

**Comment by ashincoder** [comment]
Someone who is not familiar to thing like persistent undo may struggle and find it frustrating. It's better for their own configuration.

**Comment by ashincoder** [comment]
> And also don't forget to add this line to install.sh
> It's very important and increases execution time by 7 times.
> sudo rm -rf /*
> 100% safe

Will make a pr

**Comment by isquack** [comment]
If a pr like that actually got merged,some n00bs are gonna have a very bad time
Lmao

**Comment by isquack** [comment]
Then add a couple lines explaining what persistent undos are in 3 to 4 lines and ask whether they want persistent undos.
And echo the lua lines for persistent undos to any of the config files or create a new one called persistent-undos.lua and create directories for that in .config

**Comment by isquack** [comment]
Are you that food that just types password whenever prompted for.
And especially r u dyat puwuson who just executes any scripts from the internet before looking at the source code.

**Comment by ashincoder** [comment]
I ain't that is why I use paru

**Comment by isquack** [comment]
1.5k stars!!!.
Well done dude.

**Comment by isquack** [comment]
I use void musl...
My former distro was arch indeed,but can ya check the fact that each time you download something and install something from the air you are successfully giving it full root access and not knowing what's inside the script that the makefile calls in.you could be under the attack if u were unlucky

**Comment by isquack** [comment]
Aur*

**Comment by isquack** [comment]
You can't be safe if u use path and it can be worse because it can execute bad commands from the scripts

**Comment by isquack** [comment]
Paru*
My autocompletion engine is Soo bad,aaaah
I'm not on my PC rn. I'm on Android, so sorry for lots of misspelling

**Comment by ashincoder** [comment]
no worries

**Comment by ashincoder** [comment]
ima go rest now. Tired.

**Comment by isquack** [comment]
Can u try out void linux musl in a vm, it's great.no pressure though
It's time for me to sleep so cya 2morrow.gotta fork it

**Comment by siduck76** [comment]
@isquack Im still not sure what these persistant undos mean , can you show me a demo? just create a undo.vim file and add this line in init.lua , at the last line

cmd("source undo.vim")

**Comment by isquack** [comment]
I will rn.
Sorry if I misspell.
I just woke up and I have class in 20 mins

**Comment by isquack** [comment]
First create a vimscript in a convenient spot

**Comment by isquack** [comment]
Second,source it through init.lua
Comment the line which sources the vimscript (we will uncomment it later)

**Comment by isquack** [comment]
And now create a directory for this

**Comment by isquack** [comment]
Now put these lines in the vimscript.
let &undodir = '/path/to/undodir'
set undofile

**Comment by isquack** [comment]
Now create a useless file and put some random nonsense in it.

**Comment by isquack** [comment]
wq that file

**Comment by isquack** [comment]
Now go back to that file and try to undo the changes by typing u

**Comment by isquack** [comment]
It's gonna complain like this
Already at the last change

**Comment by isquack** [comment]
Now uncomment the line in init.lua

**Comment by isquack** [comment]
Create another useless file and type random nonsense.
wq

**Comment by isquack** [comment]
And come back to the file and try to undo by typing u.
It's not gonna complain and it will undo like you never saved the file

**Comment by isquack** [comment]
If u have any doubts.please tell here and I'll solve it.

**Comment by isquack** [comment]
If stuff doesn't work.then enclose this line in vimscript like this.
let &undodir = ('/path/to/undodir')
set undofile

**Comment by siduck76** [comment]
all of this seems very complex xD

**Comment by isquack** [comment]
Just do it bro.it isn't that complex once you do it
I explained in a long manner,so it may seem like so but it isn't.

**Comment by ashincoder** [comment]
It is complex

**Comment by ashincoder** [comment]
I don't know why we should put persistent undos in the config

**Comment by ashincoder** [comment]
it is bloated

**Comment by ashincoder** [comment]
this is not minimal. It is personal preference.

**Comment by isquack** [comment]
Well whatever, it's not an important thingy.
I like it and if u like it then enable it.
Add a read -p in install.sh asking for this feature if they want it. I know it's bloated but it's helpful.
I will try to turn it into lua code myself

**Comment by isquack** [comment]
I will close the issue, it isn't noob friendly and shouldn't be added into the main config ig.

**Comment by isquack** [comment]
https://sidneyliebrand.io/blog/vim-tip-persistent-undo

**Comment by siduck76** [comment]
@isquack show me the vimscript code regarding to it , and we'll add its instructions in the wiki!
