### ISSUE TITLE
Verified

### ISSUE THREAD

**Issue by alsalalal1091** [siduck76/NvChad#72]
https://www.instagram.com/hu_yty/
[Screenshot_٢٠٢١٠٦١٦-٠٣١٤٥٤_Instagram.jpg](https://user-images.githubusercontent.com/85954631/122139357-783f0180-ce51-11eb-9c1f-25f5ae70227c.jpg)

**Comment by alsalalal1091** [comment]
llenguatge de programació

**Comment by alsalalal1091** [comment]
> https://www.instagram.com/hu_yty/
> [Screenshot_٢٠٢١٠٦١٦-٠٣١٤٥٤_Instagram.jpg](https://user-images.githubusercontent.com/85954631/122139357-783f0180-ce51-11eb-9c1f-25f5ae70227c.jpg)

- [Verified]

**Comment by ashincoder** [comment]
Is this relevant

**Comment by siduck76** [comment]
@alsalalal1091 whats this lol?

**Comment by siduck76** [comment]
Since this isnt even an issue Im closing this!
