### ISSUE TITLE
Create more suggestions

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#75]
Hello guys it would be better if you guys suggest any more features as we could grow this into more than a config and more like a framework.

**Comment by isquack** [comment]
1.6K stars!!!
That's Soo great

**Comment by isquack** [comment]
1.7K already??
That's insane

**Comment by Mangeshrex** [comment]
Really can't believe a config file got more than 1k and is going so on 🥳🥳

**Comment by isquack** [comment]
Lunarvim and spacevim are the only things having more stars

**Comment by siduck76** [comment]
> Lunarvim and spacevim are the only things having more stars

haha yes , But I find NvChad the most beautiful neovim setup and its gonna get more faster .NvChad is still in its infancy stage so dont compare it with lunarvim and spacevim :p

**Comment by ashincoder** [comment]
yes sir

**Comment by ashincoder** [comment]
Hey @siduck76 what all features are in your mind

**Comment by isquack** [comment]
I didn't compare it.i know that lunarvim and spacevim are distribution configs but nvchad is not a distribution config.
(Like doom emacs and spacemacs being distribution configs)
Nvchad is significantly faster and not really intended for being a full config framework.but it can be one.you have to build on top on nvchad to make it your own.
The best improvement that I can think of is amazing documentation

**Comment by isquack** [comment]
I only said that they are the only ones having more stars,not meaning they are better.
Nvchad is both eyecandy and blazing fast.

**Comment by ashincoder** [comment]
ok.

**Comment by isquack** [comment]
A good wiki and more colorscheme support will be one great improvement.

**Comment by ashincoder** [comment]
What do you say on making README.org instead of README.md

**Comment by ashincoder** [comment]
hey @siduck76 couldn't you fork a colorscheme repo and change it.

**Comment by siduck76** [comment]
> hey @siduck76 couldn't you fork a colorscheme repo and change it.

its not that easy , we would use a colorscheme repo (nvim-base16) mostly for syntax highlighting and the rest of the colors are manually added here 

![image](https://user-images.githubusercontent.com/59060246/122161845-12259f00-ce90-11eb-9091-639001c76e6c.png)

**Comment by ashincoder** [comment]
oh ok

**Comment by ashincoder** [comment]
> What do you say on making README.org instead of README.md

what about this

**Comment by siduck76** [comment]
> > What do you say on making README.org instead of README.md
> 
> what about this

idk about .org

**Comment by ashincoder** [comment]
checkout my xmonad config doc written in org.
https://github.com/ashincoder/dotfiles/tree/master/.config/xmonad

**Comment by siduck76** [comment]
> A good wiki and more colorscheme support will be one great improvement.
 
yeah you can send md files for the wiki so I'd change it . Alnd for the colorscheme , its gonna be a long process since I have to find perfect colors matching each other and creating a perfect harmony of shades etc!

**Comment by ashincoder** [comment]
> > A good wiki and more colorscheme support will be one great improvement.
> 
> yeah you can send md files for the wiki so I'd change it . Alnd for the colorscheme , its gonna be a long process since I have to find perfect colors matching each other and creating a perfect harmony of shades etc!

yeah it can be a difficult process

**Comment by siduck76** [comment]
> checkout my xmonad config doc written in org.
> https://github.com/ashincoder/dotfiles/tree/master/.config/xmonad

we'll try keeping things as simple as possible , markdown must be easier than org I suppose so we'll stick with Readme.md

**Comment by ashincoder** [comment]
> > A good wiki and more colorscheme support will be one great improvement.
> 
> yeah you can send md files for the wiki so I'd change it . Alnd for the colorscheme , its gonna be a long process since I have to find perfect colors matching each other and creating a perfect harmony of shades etc!

shall i send you a org file for this repo.

**Comment by ashincoder** [comment]
no actually org is more cleaner and easier to use.
It can be given headings and subheadings, tables, source code blocks.
just like md but easier actually

**Comment by ashincoder** [comment]
I mean which is easier for you. Ok we can continue md if you want

**Comment by ashincoder** [comment]
Org is a document maker it is built into emacs.

**Comment by siduck76** [comment]
Idk about org at all and most people tend to use markdown so I think we should stick to it and this 

![image](https://user-images.githubusercontent.com/59060246/122162238-d808cd00-ce90-11eb-88a4-a86e203c5fdb.png) :c

**Comment by ashincoder** [comment]
I don't know who wrote this article but it's not true

**Comment by ashincoder** [comment]
Yeah we can continue md if you want

**Comment by ashincoder** [comment]
Anyting else more like features for nvim

**Comment by isquack** [comment]
I have a suggestion
This maybe great or terrible

**Comment by isquack** [comment]
Why not create another repo called nvchad++ or something like that and make this repo the base for that project and make it like a full framework like lunarvim/spacevim while still maintaining this project?

**Comment by siduck76** [comment]
> Why not create another repo called nvchad++ or something like that and make this repo the base for that project and make it like a full framework like lunarvim/spacevim while still maintaining this project?

Since NvChad is still in its early stage , we wont be focusing on such complex stuff for now :)

**Comment by isquack** [comment]
Not yet.
After we make nvchad stable enough and all those good stuff,we can move to some other project with nvchad as a base
It's gonna take months of development to make nvchad mature and stable.

**Comment by isquack** [comment]
Chat is ported to gitter.so close this issue
