### ISSUE TITLE
https://p20.zdusercontent.com/attachment/66681/EFE0cSAYw9XPNDK3zaydpGB3v?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..Wd5BF_ZqpPqM5j078xpDPA.7xVVptUOaCadTUtjGABmBECynOT4qtulT0FhwMCitKhgqDx68MQs0eQesFruKJ3zMdG6SuPOMbeSHFZiMbhxZw7eOPNnKVuSYRIiuIoqxFvciW4KUf2RxpBynCg5tWUUcn_tWyTg1k34qf12Tm3gjkL9IcmlOWjGBDnwuxOS9FzSy5eOZrcL_H3hX5uMtzOeBRwtfGaTVOi4w275BBcU6LZLYF33gpRbxCrDihvEx5v8Qi16SHSirAs81asGBxuVVLEXM-huppBmaVUOZExe1LKG9J1J1VKt4glDKbmFcGY.8wHG_cjpjTzlulXpLNprPA

### ISSUE THREAD

**Issue by alsalalal1091** [siduck76/NvChad#76]
https://p20.zdusercontent.com/attachment/66681/EFE0cSAYw9XPNDK3zaydpGB3v?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..Wd5BF_ZqpPqM5j078xpDPA.7xVVptUOaCadTUtjGABmBECynOT4qtulT0FhwMCitKhgqDx68MQs0eQesFruKJ3zMdG6SuPOMbeSHFZiMbhxZw7eOPNnKVuSYRIiuIoqxFvciW4KUf2RxpBynCg5tWUUcn_tWyTg1k34qf12Tm3gjkL9IcmlOWjGBDnwuxOS9FzSy5eOZrcL_H3hX5uMtzOeBRwtfGaTVOi4w275BBcU6LZLYF33gpRbxCrDihvEx5v8Qi16SHSirAs81asGBxuVVLEXM-huppBmaVUOZExe1LKG9J1J1VKt4glDKbmFcGY.8wHG_cjpjTzlulXpLNprPA

**Comment by alsalalal1091** [comment]
https://p20.zdusercontent.com/attachment/66681/EFE0cSAYw9XPNDK3zaydpGB3v?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..Wd5BF_ZqpPqM5j078xpDPA.7xVVptUOaCadTUtjGABmBECynOT4qtulT0FhwMCitKhgqDx68MQs0eQesFruKJ3zMdG6SuPOMbeSHFZiMbhxZw7eOPNnKVuSYRIiuIoqxFvciW4KUf2RxpBynCg5tWUUcn_tWyTg1k34qf12Tm3gjkL9IcmlOWjGBDnwuxOS9FzSy5eOZrcL_H3hX5uMtzOeBRwtfGaTVOi4w275BBcU6LZLYF33gpRbxCrDihvEx5v8Qi16SHSirAs81asGBxuVVLEXM-huppBmaVUOZExe1LKG9J1J1VKt4glDKbmFcGY.8wHG_cjpjTzlulXpLNprPA

**Comment by siduck76** [comment]
dude
