### ISSUE TITLE
Globals config

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#77]
Hey what about we add like a file globals.lua. In lunarvim there is a example. How about we use it.

**Comment by ashincoder** [comment]
It can manipulate settings.

**Comment by ashincoder** [comment]
Think about it and let me know

**Comment by siduck76** [comment]
This feature wouldnt be implemented this soon , NvChad will first focus on existing features like  configuring existing plugins very well and making the config as small as possible. We'll include most stuff in the wiki so the config doesnt get very bloated. Adding tons of config by default isnt good either , like adding lsp configs for all the languages. We'll keep NvChad as minimal as possible and add many features and their configs in the wiki so the it'd depend on the user what features he wants and keeping NvChad as base config and spoonfeeding each and everything isnt good either :p

**Comment by ashincoder** [comment]
ok
