### ISSUE TITLE
How do I use coc.nvim with NvChad

### ISSUE THREAD

**Issue by samrath2007** [siduck76/NvChad#80]

**Comment by siduck76** [comment]
NvChad uses lua plugins mostly , nvim-lsp has been working very well as well . if you knew lua , you could add it . But why coc.nvim tho?

**Comment by samrath2007** [comment]
I am just very used to it now. I've been using for it 2-3 months.

**Comment by siduck76** [comment]
> I am just very used to it now. I've been using for it 2-3 months.

oh , nvim-lsp integrates well with file tree , statusline , bufferline etc so I use it . Btw which languages do you code in? its easy with nvim-lsp too ( easier with lspinstall)

**Comment by samrath2007** [comment]
I work with  typescript, react, node, express and python. For most things I can add plugins and it works. But emmet doesn't work with vim-lsp.

**Comment by siduck76** [comment]
> I work with typescript, react, node, express and python. For most things I can add plugins and it works. But emmet doesn't work with vim-lsp.

it works buddy!

**Comment by siduck76** [comment]
install emmet-lsp tho

**Comment by samrath2007** [comment]
This is what I got earlier
![image](https://user-images.githubusercontent.com/69572668/122313886-ad705000-cf34-11eb-9fca-439e268516bd.png)

**Comment by siduck76** [comment]
> This is what I got earlier, it still shows this(I did run `npm install -g emmet-ls`)
> ![image](https://user-images.githubusercontent.com/69572668/122313886-ad705000-cf34-11eb-9fca-439e268516bd.png)

is node prefix set ?

**Comment by siduck76** [comment]
nvim-lsp isnt hard , check 

https://github.com/siduck76/NvChad/wiki#--install--lsp-servers

**Comment by samrath2007** [comment]
> > This is what I got earlier, it still shows this(I did run `npm install -g emmet-ls`)
> > ![image](https://user-images.githubusercontent.com/69572668/122313886-ad705000-cf34-11eb-9fca-439e268516bd.png)
> 
> is node prefix set ? and whats the output of emmet-ls in the terminal?


![image](https://user-images.githubusercontent.com/69572668/122324304-317f0380-cf46-11eb-910e-b25513c0d092.png)

**Comment by ashincoder** [comment]
try root.
`sudo install npm -g emmet-ls`

**Comment by ashincoder** [comment]
when I install from npm emmet-ls it will be installed to a folder in .local/share/bin
there will be emmet-ls binary. We must add it to path.

**Comment by samrath2007** [comment]
```
sam@Samraths-MacBook-Air lib % tree -L 2
.
└── node_modules
    ├── emmet
    └── emmet-ls

3 directories, 0 files
sam@Samraths-MacBook-Air lib % pwd
/Users/sam/.node_modules/lib
```
On Mac it is installed at ~/.node_modules/lib

**Comment by siduck76** [comment]
weird , I usually put this on path 

PATH=$PATH:~/.node_modules/bin

**Comment by ashincoder** [comment]
inside .node_modules there should be a folder called bin

**Comment by samrath2007** [comment]
I debugged nvchad for the most of today. Removed all lip and added coc.nvim. Thank you for the help though!

**Comment by ashincoder** [comment]
sorry for the trouble you had

**Comment by samrath2007** [comment]
> sorry for the trouble you had

No problem, I learnt a lot of Lua because of it 😀
