### ISSUE TITLE
Problems executing macros

### ISSUE THREAD

**Issue by jtuz** [siduck76/NvChad#81]
## Behaivor

When which-key is active there are some troubles executing macros after a record

## How can reproduce It

Put this content on a file:
```
abc
adt
asdf
```
go to the first line

1. start a macro qa
2. go at the beginning of line _
3.  insert a colon i: and pres ESC
4. go to the next line j
5. stop macro recording q
6. execute macro @a

**Comment by ashincoder** [comment]
Does it. When I did it works fine.

**Comment by siduck76** [comment]
@Vanderscycle is it possible to make whichkey not running always and getting invoked directly like normal mappings?

**Comment by Vanderscycle** [comment]
@jtuz,

I tried recreating the problem and didn't find an issue with folke/which-key. Please find my recording bellow. 
 
[![asciicast](https://asciinema.org/a/BCfukqIlSO1vRiPLLcQ7IvdnJ.svg)](https://asciinema.org/a/BCfukqIlSO1vRiPLLcQ7IvdnJ)

An added step in helping us and potentially Folke debug the issue would be to record the event using [asciinema](https://asciinema.org/)

**Comment by folke** [comment]
This used to be an issue a couple of weeks ago but as far as I know it should be fixed. I also can't reproduce this.

@siduck76 you can define a list of triggers in the configuration instead of letting which-key automatically set them up. Do understand that you won't see any which key help for any trigger not defined in the config that way. You'll also need to setup the correct triggers for any presets you want to have loaded.

**Comment by siduck76** [comment]
@folke is it possible to just show default vim  mappings? I want to create a whichkey popup for all the NvChad related mappings and maybe put certain titles to them too , something like this 

![image](https://user-images.githubusercontent.com/59060246/122489941-69e21880-cffe-11eb-92ba-eec2ec31a220.png)

**Comment by folke** [comment]
That's not possible and out of scope for which key, but there's a [cheatsheet plugin](https://github.com/sudormrfbin/cheatsheet.nvim) that might be interesting to you

**Comment by jtuz** [comment]
Hi to all!, I think this was something with neovim, I was testing all nightly builds and after the last night I updated mi neovim and It seems macros is working right with `which-key`, certainly when I opened this issue I disabled `which-key` to get macros working right, So I'll close this Issue for now thank You for your help!
