### ISSUE TITLE
Clone of shyam

### ISSUE THREAD

**Issue by SANJUSHYAMSONROY** [siduck76/NvChad#84]

**Comment by ashincoder** [comment]
May I know the issue

**Comment by siduck76** [comment]
why are we getting these useless issues?

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/124415092-b5702280-dd71-11eb-8cd6-48555e5baedd.png)

**Comment by siduck76** [comment]
Coc vs nvim-lsp function completion
https://user-images.githubusercontent.com/59060246/124447747-4d383580-dd9f-11eb-9120-1edcdf122b58.mp4
