### ISSUE TITLE
Lag when not in the nvim directory.

### ISSUE THREAD

**Issue by asmallcarrot** [siduck76/NvChad#85]
I have been trying to figure out a issue with nvim-tree and decided to try out your config to see if it would work. For whatever reason there is no lag when I'm in the nvim folder but not when I'm in for example ~. 
https://github.com/kyazdani42/nvim-tree.lua/issues/453
(For reference)

**Comment by ashincoder** [comment]
Isnt this a plugin related issue

**Comment by siduck76** [comment]
@asmallcarrot can you show the lag? I havent faced any of this also unable to reproduce it either. I have seen the videos you provided on nvim-tree.lua's issue , But i dont see any change! can you try it with my config and test? you have used  your own config there . I think this shouldnt be the part of NvChad's issue since you didnt even use it!

**Comment by ashincoder** [comment]
Not only that we can't do anything if it is a plugin related issue.

**Comment by siduck76** [comment]
> Not only that we can't do anything if it is a plugin related issue.

yeah agreed , do you face the issue?

**Comment by ashincoder** [comment]
Sometimes there is a short delay.
Then no lag issues

**Comment by ashincoder** [comment]
only that much.

**Comment by ashincoder** [comment]
Atleast it was faster than when I used init.vim

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/122490245-2f2cb000-cfff-11eb-9c9a-03cc883d3f16.mp4

Im on my old pc and it has low specs , I dont see any lag or slowness tho 

![image](https://user-images.githubusercontent.com/59060246/122490281-48cdf780-cfff-11eb-8b74-32dff42c0afb.png)

**Comment by asmallcarrot** [comment]
can you show that when opening a document

**Comment by siduck76** [comment]
> can you show that when opening a document


https://user-images.githubusercontent.com/59060246/122490551-e4f7fe80-cfff-11eb-9e36-e3ffa6c396da.mp4

**Comment by ashincoder** [comment]
it is snappy.

**Comment by asmallcarrot** [comment]
I mean when opening a new document, not with the file tree.

**Comment by siduck76** [comment]
> I mean when opening a new document, not with the file tree.

that looks like a neovim problem , not nvimtree 

look 

https://user-images.githubusercontent.com/59060246/122502664-ad478180-d014-11eb-9b5a-2c597920d464.mp4
