### ISSUE TITLE
Would you consider creating a tmux theme?

### ISSUE THREAD

**Issue by genesis-algorithms** [siduck76/NvChad#91]
Hi, your defaults are amazing O_O congrats! I just wanted to ask if you think about creating a tmux theme also?

**Comment by siduck76** [comment]
Hi , I've never used tmux before and idk how it feels like , anyways PR's are always welcomed ^o^

**Comment by siduck76** [comment]
also tmux is cli right? so why a different theme for it? neovim should look the same on it.

**Comment by siduck76** [comment]
@genesis-algorithms there's already onedark theme for tmux , check https://github.com/odedlaz/tmux-onedark-theme

**Comment by genesis-algorithms** [comment]
Yeah, I checked them all but none is good enough IMO. I found that making themes for Tmux is not that hard I may be able to create one that's matching NVChad and send a pull request then.

Thanks, I'm closing the issue now.
