### ISSUE TITLE
(Improvement) Use Buffer Delete Plugin

### ISSUE THREAD

**Issue by kingavatar** [siduck76/NvChad#92]
Hello, thank you for this really cool configuration. Here is a suggestion for using [bufdelete.nvim](https://github.com/famiu/bufdelete.nvim) or [nvim-bufdel](https://github.com/ojroques/nvim-bufdel) (these were written in lua) etc and replace the bdelete command with Bdelete for Shift-x mapping which helps in maintaining the windows layout when nvim-tree is open and not mess up layout for other windows.

https://user-images.githubusercontent.com/31726036/122888829-d5f6b080-d35f-11eb-9588-55b9e727ac16.mp4

**Comment by siduck76** [comment]
could you show the behaviour without bufdelete.nvim?

**Comment by kingavatar** [comment]
### Without
When I try to close buffers by pressing shift-x i get unwanted behavior of focusing on nvim-tree when it is open and it resizes itself to half the window and not closing the last buffer as well.

https://user-images.githubusercontent.com/31726036/122907853-2a565c00-d371-11eb-8942-48305136b829.mp4

### Splits
It retains the layout which we created and deletes buffers.

https://user-images.githubusercontent.com/31726036/122908321-9e90ff80-d371-11eb-9234-79e63f1b1be7.mp4

**Comment by siduck76** [comment]
This looks nice! I'll soon add some configurations for lazy loading most plugins , once thats done I'll add this plugin.

**Comment by Vanderscycle** [comment]
If you don't want to go the plugin route you can also map the close buffer commands to a key. It closes the buffer you are currently on.

```lua
-- closing buffer
map("n","<leader>q",":bp<bar>sp<bar>bn<bar>bd<CR>", opt)```

**Comment by siduck76** [comment]
> you

does this maintain the windows layout?

**Comment by Vanderscycle** [comment]
> > you
> 
> does this maintain the windows layout?

yes (not sure if that was meant to me or regarding the plugin） I‘ve added a asciinema gif.

**Comment by m2kulkarni** [comment]
Thanks @Vanderscycle , the map works nice for me!

**Comment by siduck76** [comment]
@Vanderscycle I get this issue sometimes , the buffer duplicates itself when I delete it 


https://user-images.githubusercontent.com/59060246/123508568-d9ef3f00-d68d-11eb-82bd-c3b14be67f9a.mp4

**Comment by Vanderscycle** [comment]
@siduck76 never had this issue, but I haven't pushed the edge cases yet. I'll investigate. All the keybinding is tied to vim commands so they can be easily modified.

Nice gruvbox theme, Do you think you can write instructions on how to generate and submit your own theme?

**Comment by siduck76** [comment]
@Vanderscycle https://github.com/siduck76/NvChad/wiki#themes

**Comment by siduck76** [comment]
@Vanderscycle :bp<bar>sp<bar>bn<bar>bd looks nice but how do we force close the buffer without prompting?

**Comment by siduck76** [comment]
@Vanderscycle Btw using bd! instead of bd allows closing of terminal buffers too :)

**Comment by siduck76** [comment]
we wont be using a plugin for this! 

bp<bar>sp<bar>bn<bar>bd!

should be added now :D

**Comment by Vanderscycle** [comment]
> Btw using bd! instead of bd allows closing of terminal buffers too :)

Interresting, I use tmux as I found it was much easier to have multiple terminal running.

**Comment by siduck76** [comment]
> > Btw using bd! instead of bd allows closing of terminal buffers too :)
> 
> Interresting, I use tmux as I found it was much easier to have multiple terminal running.

I dont use tmux , we can have multiple terminal windows on neovim too , either as splits or open them in new tabs.

![image](https://user-images.githubusercontent.com/59060246/123553828-09d83880-d79b-11eb-95d7-6bb335cd6896.png)

**Comment by Vanderscycle** [comment]
I know, its pretty cool.

What sold me on tmux is that you can combine tmux and tmuxinator to create predefined environment (e.g. 1 windows is nvim, 2nd db, 3rd npm dev etc.)
here's an example if you ever [try](https://github.com/Vanderscycle/dot-config/blob/main/tmuxinator/TSGrapqlPostgres.yml)
