### ISSUE TITLE
Please Windows Support

### ISSUE THREAD

**Issue by yhnu** [siduck76/NvChad#93]

**Comment by siduck76** [comment]
I dont use windows and dont have it installed it any of my machines , also none uses windows in my home either. Idk much about windows but you just have to put the lua folder + init.lua file in your neovim folder on windows I think

**Comment by Vanderscycle** [comment]
I think its more an issue of getting nvim to work on Windows. You can use windows WSL or use gVim.

**Comment by ashincoder** [comment]
I think gvim or a vim gui client is better for windows.

**Comment by siduck76** [comment]
> I think gvim or a vim gui client is better for windows.

no just use NvChad in windows terminal. Only installation part by install.sh is not possible cuz Idk how windows scripts work , they just need to copy lua folder + init.lua to their neovim folder and install neovim 0.5 , done :)

**Comment by ashincoder** [comment]
Is this still an issue as @siduck76 made his statement

**Comment by siduck76** [comment]
@ashincoder yes I'll ask for help with some of my friends who use windows :'(

**Comment by siduck76** [comment]
@yhnu 

# install packer 

- git clone https://github.com/wbthomason/packer.nvim "$env:LOCALAPPDATA\nvim-data\site\pack\packer\start\packer.nvim"

- go to  ~/AppData/Local/nvim

- copy nvchad's init.lua and lua folder in the nvim folder 

- nvim +PackerSync

- press enter to skip errors and let it install plugins.

**Comment by exorcist365** [comment]
Windows plebs don't deserve to have this beauty.

**Comment by ashincoder** [comment]
offcourse

**Comment by dumblob** [comment]
@siduck76 did your friends also try to simply download [Git for Windows](https://gitforwindows.org/ ) and run the `install.sh` from it?

If it doesn't work, could `install.sh` be adjusted so that this IMHO simpliest method works?

Maybe a CI (GitHub supports also Windows CI) could check it every time a change of `install.sh` is pushed to this repo.

**Comment by siduck76** [comment]
> @siduck76 did your friends also try to simply download [Git for Windows](https://gitforwindows.org/) and run the `install.sh` from it?
> 
> If it doesn't work, could `install.sh` be adjusted so that this IMHO simpliest method works?
> 
> Maybe a CI (GitHub supports also Windows CI) could check it every time a change of `install.sh` is pushed to this repo.

I wish I could help , Idk much scripting also Im not familiar with windows :( . It would be nice if the install.sh could be adjusted for windows install too.

**Comment by barun108** [comment]
# Windows 10

also do 
```ps
ps>choco install mingw
```

before installing the plugins

`treesitter` requires c compiler to install  [read it here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support)

untill I did not install c compiler it kept producing this error #97 

after installing `mingw` it is working great  👍

**Comment by siduck76** [comment]
> # Windows 10
> also do
> 
> ```postscript
> ps>choco install mingw
> ```
> 
> before installing the plugins
> 
> `treesitter` requires c compiler to install [read it here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support)
> 
> untill I did not install c compiler it kept producing this error #97
> 
> after installing `mingw` it is working great

thanks for this , I will update the procedure!

**Comment by barun108** [comment]
@siduck76 

But I am still struggling to configure language server
`:LspInstall <some lnaguage>` produces a error , `/usr/bin/env` not found 😕
of course on my Windows 10 machine 

but, 

manually installing Language Servers like `npm install -g typescript-language-server` works just okay 😑

**Comment by siduck76** [comment]
> @siduck76
> 
> But I am still struggling to configure language servers
> `:LspInstall <some lnaguage>` produces a error , `/usr/bin/env` not found 
> of course on my Windows 10 machine
> 
> but,
> 
> manually installing Language Servers like `npm install -g typescript-language-server` works just okay

its a lspinstall issue I think , maybe they didnt add commands for installing lsp servers on windows 

https://github.com/kabouzeid/nvim-lspinstall
