### ISSUE TITLE
LSP not working in Terminal ( C++)

### ISSUE THREAD

**Issue by MR-TLL** [siduck76/NvChad#94]
I use clangd as a language server for editing c++ file. When the files are initially opened the LSP server displays the diagnostics , but it never updates. Also there are no auto completions, this always happens when nvim is opened in Terminal mode, but the problem disappears if i use a GUI client for neovim like Nvim-qt or Neovide.

I am attaching some images for references.
The LSP shows diagnostics the first time file is opened , after that it  stops updating, i've tried :LspRestart with no avail. 
![image](https://user-images.githubusercontent.com/76173714/123297087-4c460f00-d528-11eb-943d-f976b42e9ec9.png)

Following is :LspInfo on the same file
![image](https://user-images.githubusercontent.com/76173714/123297351-8e6f5080-d528-11eb-96a9-d53e06922c45.png)

Following is the image of nvim-qt, as you can see , auto complete as well as LSP update works fine here:
![image](https://user-images.githubusercontent.com/76173714/123298094-37b64680-d529-11eb-8554-bdbf2065a02a.png)

I'm using the nightly build of nvim from aur.
I've tried using st and kitty as terminals , to no avail.

Also i don't know if it's a related issue/feature or not , but the rainbow brackets (coloring of matching brackets) also don't work (Don't know the exact name , sorry i'm new to vim world :D), that i saw in some screenshots.

**Comment by siduck76** [comment]
how did you install clangd? did you set any lspconfig for it?

**Comment by siduck76** [comment]
the rainbow brackts is a treesitter thing , file an issue for it there.

**Comment by siduck76** [comment]
I suggest you to add ccls , gives nice completions :)

![image](https://user-images.githubusercontent.com/59060246/123305353-a43b4080-d53d-11eb-9d7f-01b32699b175.png)

**Comment by siduck76** [comment]
just add this at the bottom in your lua/nvim-lspconfig.lua file 
 
 ```
   local lspconfig = require "lspconfig"
    lspconfig.ccls.setup {
        init_options = {
            compilationDatabaseDirectory = "build",
            index = {
                threads = 0
            },
            clang = {
                excludeArgs = {"-frounding-math"}
            }
        }
    }
    ```
   
   Install ccls for your OS too :)

**Comment by MR-TLL** [comment]
> how did you install clangd? did you set any lspconfig for it?

I used :LspInstall inbuilt command to install clangd. and it works fine in GUI clients.


> I suggest you to add ccls , gives nice completions :)
> 
> ![image](https://user-images.githubusercontent.com/59060246/123305353-a43b4080-d53d-11eb-9d7f-01b32699b175.png)

hmm ccls can be a valid alternative, but i actually prefer clangd since i use it everywhere i.e on vscode , Emacs etc. would be great if it works on Nvchad too :smile:

**Comment by siduck76** [comment]
ccls uses clang underneath iirc

**Comment by MR-TLL** [comment]
> Install ccls for your OS and just add this at the bottom in your lua/nvim-lspconfig.lua file
> 
> ```
>   local lspconfig = require "lspconfig"
>    lspconfig.ccls.setup {
>        init_options = {
>            compilationDatabaseDirectory = "build",
>            index = {
>                threads = 0
>            },
>            clang = {
>                excludeArgs = {"-frounding-math"}
>            }
>        }
>    }
> ```

I tried this solution just now, and i have removed clangd using LspUninstall , Unfortunately the same issue happens , the autocomplete is working fine in terminal using ccls , but the diagnostics aren't updating in terminal mode.
Following is the diagnostic in terminal
![image](https://user-images.githubusercontent.com/76173714/123309247-bf09b700-d535-11eb-9382-a0f966661b27.png)
It is still referencin the initial ccls error even though i've replaced ccls with ccls_extraa

Following is the same experiment in nvim-qt
![image](https://user-images.githubusercontent.com/76173714/123309423-f2e4dc80-d535-11eb-8f4f-298d5c7c3d01.png)
As you can see it immediatly catches the ccls_extraaa , the moment i enter normal mode. :sweat:

**Comment by siduck76** [comment]
the issue might be your terminal :c , I use st terminal and it works fine.

**Comment by siduck76** [comment]
check my st build.

**Comment by MR-TLL** [comment]
> check my st build.

Ok will do , BTW i just tried on my st , still the same result. so far i've tried kitty and st, i'll also test it on your st build and konsole :smile:

**Comment by siduck76** [comment]
@MR-TLL clangd and ccls work fine for me :)


https://user-images.githubusercontent.com/59060246/123314030-b7530e00-d547-11eb-8a54-e1d014bb1ec3.mp4

**Comment by MR-TLL** [comment]
> @MR-TLL clangd and ccls work fine for me :)
> 
>  simplescreenrecorder-2021-06-24_23.36.32.mp4

Wow I'm jealous.  
Well i give up now, I've tried most terminals under the sun ( st , kitty , gnome-terminal , konsole , alacritty , xterm ) all have this issue. ( though i'll try your st build sometime later, too tired right now )
Interestingly i installed Nvchad on my another machine with KDE Plasma on Konsole and it works there without any problems :partying_face: 
For the meantime i'll use Neovide GUI client on my main machine to combat the issue, what a weird issue this is :expressionless: 

Btw, your colorscheme looks very different from the default Nvchad , is there some setting/way to change the colorschemes? Also could you tell the font you are using , looks absolutely gorgeous.

**Comment by siduck76** [comment]
@MR-TLL seems like your system has some issues! also thats gruvbox , I'll add the theme soon :). font is jetbrainsmono nerd font medium.

**Comment by MR-TLL** [comment]
> > @MR-TLL clangd and ccls work fine for me :)
> > simplescreenrecorder-2021-06-24_23.36.32.mp4
> 
> Wow I'm jealous.
> Well i give up now, I've tried most terminals under the sun ( st , kitty , gnome-terminal , konsole , alacritty , xterm ) all have this issue. ( though i'll try your st build sometime later, too tired right now )
> Interestingly i installed Nvchad on my another machine with KDE Plasma on Konsole and it works there without any problems 
> For the meantime i'll use Neovide GUI client on my main machine to combat the issue, what a weird issue this is 
> 
> Btw, your colorscheme looks very different from the default Nvchad , is there some setting/way to change the colorschemes? Also could you tell the font you are using , looks absolutely gorgeous.

@siduck76 , i was trying to locate the problem source on my other machine with konsole where the Diagnostics were working in terminal and it stopped working even there.

Fortunately i think i have pinned down the start of the problem. This issue happens whenever i open a file as : nvim file.cpp
If i open nvim directly , and use the Inbuilt FileTree or Recent files and the open file.cpp , this issue never happens.


> @MR-TLL clangd and ccls work fine for me :)
> 
>  simplescreenrecorder-2021-06-24_23.36.32.mp4

In the above recording i can see that you always open nvim as VI , and not as nvim file.cpp , i was using the latter method always and hence this issue comes up.
Only question is that is this a upstream issue or the configs.

**Comment by siduck76** [comment]
@MR-TLL then this isn't an NvChad issue I suppose , file it on nvimtree repo , they're very helpful :)

**Comment by siduck76** [comment]
nvim main.cpp works for me , the issue might be your system 
https://user-images.githubusercontent.com/59060246/123727298-1057d480-d8af-11eb-9351-e0cfd4df0556.mp4

**Comment by ashincoder** [comment]
Hello guys . May I know does this issue still continue

**Comment by MR-TLL** [comment]
> nvim main.cpp works for me , the issue might be your system
> simplescreenrecorder-2021-06-29_07.34.27.mp4

Hey Thanks for trying to help , but the issue persists , I'll try to install it on Ubuntu or clean arch install in the next week and will update about the same. 


> Hello guys . May I know does this issue still continue

Unfortunately for me Yes , this issue still exists.

**Comment by siduck76** [comment]
> > nvim main.cpp works for me , the issue might be your system
> > simplescreenrecorder-2021-06-29_07.34.27.mp4
> 
> Hey Thanks for trying to help , but the issue persists , I'll try to install it on Ubuntu or clean arch install in the next week and will update about the same.
> 
> > Hello guys . May I know does this issue still continue
> 
> Unfortunately for me Yes , this issue still exists.

remove clang completely , delete ~/.config/nvim , ~/.local/share/nvim , ~/.cache/nvim folders

run the install script from nvchad repo and once all the plugins are installed , do :LspInstall cpp

**Comment by Wolffoner** [comment]
Hello guys, i have the same issue when i try to use NvChad when install from :LspInstall cpp, and when i edit my code in C , have the same problem the flag errors doesn´t update. I use kitty and Pop OS.

**Comment by ashincoder** [comment]
I dont't know what is the real problem. I installed cpp lsp and it works fine. I use it to edit my suckless utility. We will try our best. Please bring any updates @Wolffoner

**Comment by siduck76** [comment]
> Hello guys, i have the same issue when i try to use NvChad when install from :LspInstall cpp, and when i edit my code in C , have the same problem the flag errors doesn´t update. I use kitty and Pop OS.

show a recording of it

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/124156818-b37a3b00-dab5-11eb-809e-3b89309c0184.mp4

tested cpp lsp just now and it werks.

**Comment by Wolffoner** [comment]
Sorry, when i tried NvChad 2 weeks ago, i have this issue, and change to coc, yesterday i update my version from Pop OS 20.10 to Pop OS 21.04, i tried today and  doesnt have any problem, thank u :partying_face:

**Comment by MR-TLL** [comment]
Hey guys , so i tried the latest config on Ubuntu 21.04 today , and the diagnostics work fine when i open a cpp file , however the LSP server isn't started when i create and open a new file like , nvim newfile.cpp , but if i open a existing file ( by issuing a touch command before , or opening a existing CPP file) the LSP server is started and works.

I also tested it in my other arch based system and it works there too :partying_face: 

BTW , i noticed the welcome page doesn't show up in the latest config , was it removed?  it looked awesome though.

**Comment by siduck76** [comment]
@MR-TLL check https://github.com/siduck76/NvChad/wiki#dashboard

**Comment by ashincoder** [comment]
please closet the issue if finished. Thank You

**Comment by Oscuro1111** [comment]
> Install ccls for your OS and just add this at the bottom in your lua/nvim-lspconfig.lua file
> 
> ```
>   local lspconfig = require "lspconfig"
>    lspconfig.ccls.setup {
>        init_options = {
>            compilationDatabaseDirectory = "build",
>            index = {
>                threads = 0
>            },
>            clang = {
>                excludeArgs = {"-frounding-math"}
>            }
>        }
>    }
> ```
Where lua/nvim-lspconfig.lua exist?
