### ISSUE TITLE
weird color line

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#95]
I have weird color line here 
check this:
![Nvim](https://github.com/ashincoder/dotfiles/blob/master/.screenshots/nvim.png)

**Comment by ashincoder** [comment]
The line on the left handside is the problem

**Comment by siduck76** [comment]
@ashincoder did you remove nvim-base16 plugin? show me your init.lua

**Comment by ashincoder** [comment]
yeah i found the issue sorry my bad. I had enabled two colorschemes. It got conflicted. My bad
