### ISSUE TITLE
shows check config for correctness

### ISSUE THREAD

**Issue by ashincoder** [siduck76/NvChad#97]
![error](https://user-images.githubusercontent.com/83629316/123498488-ccb26000-d64d-11eb-9f99-eb2a0fc80095.png)

Here it show in the statusline.

**Comment by ashincoder** [comment]
It is when I get into insert mode this error shows up.
When i start up it doesn't show. I think it is the compe-completion

**Comment by siduck76** [comment]
Do :PackerSync

**Comment by siduck76** [comment]
Sorry I forgot to mention it

**Comment by ashincoder** [comment]
But it still shows

**Comment by siduck76** [comment]
open neovim again and check.

**Comment by ashincoder** [comment]
I did actually. It still shows.

**Comment by ashincoder** [comment]
Does it show for you

**Comment by siduck76** [comment]
no , I even reinstalled Nvchad by its install script . it doesnt show

**Comment by siduck76** [comment]
try :PackerCompile

**Comment by ashincoder** [comment]
ok

**Comment by ashincoder** [comment]
yeah it doesn't show now. I cleaned the cache direcotory. Great!
