### ISSUE TITLE
Colorscheme not working

### ISSUE THREAD

**Issue by Zigrino** [siduck76/NvChad#98]
![Screen Shot 2021-06-26 at 1 25 38 PM](https://user-images.githubusercontent.com/56608462/123521035-17e66600-d682-11eb-8af3-1a6008e13e56.png)

**Comment by siduck76** [comment]
you sure you have treesitter parsers installed?

**Comment by Zigrino** [comment]
I ran brew install tree-sitter and It said it was installed, I'm not sure though I'm pretty new to neovim.

**Comment by siduck76** [comment]
what's your neovim version? also share the code so I could check the syntax highlighting on my system.

**Comment by Zigrino** [comment]
I don't think I've changed anything from the original config. the code is here: 
[main.py.zip](https://github.com/siduck76/NvChad/files/6720993/main.py.zip)

**Comment by Zigrino** [comment]
neovim version 0.5.0

**Comment by mTvare6** [comment]
@Zigrino run `tree-sitter -V` and are you running stuff in terminal or goneovim?

**Comment by Zigrino** [comment]
tree-sitter version 0.19.5 and I'm running it in iterm

**Comment by siduck76** [comment]
@Zigrino treesitter is working and the syntax highlight is correct too :

without treesitter 

![image](https://user-images.githubusercontent.com/59060246/123589466-e4811400-d806-11eb-88ea-780d923a10ca.png)

with treesitter 

![image](https://user-images.githubusercontent.com/59060246/123589505-f498f380-d806-11eb-868b-a6ae1bb23096.png)

**Comment by Zigrino** [comment]
I think tree-sitter is working fine for me, it's just the color scheme that won't work.

**Comment by siduck76** [comment]
> I think tree-sitter is working fine for me, it's just the color scheme that won't work.

I think its the syntax highlighting is normal , did you try it on vscode or such?

**Comment by Zigrino** [comment]
yes, the syntax highlighting in vscode works just fine for me, but I'm not using the Neovim plugin for vscode.

**Comment by siduck76** [comment]
> yes, the syntax highlighting in vscode works just fine for me, but I'm not using the Neovim plugin for vscode.

could you show it?

**Comment by Zigrino** [comment]
![Screen Shot 2021-06-28 at 1 51 03 PM](https://user-images.githubusercontent.com/56608462/123681527-f0c19d00-d817-11eb-93ec-7e7b555e8734.png)

**Comment by siduck76** [comment]
I meant main.py

**Comment by Zigrino** [comment]
![Screen Shot 2021-06-28 at 1 53 41 PM](https://user-images.githubusercontent.com/56608462/123681849-4bf38f80-d818-11eb-8c45-d8a0f666c530.png)

**Comment by siduck76** [comment]
hmm weird , could you share the whole dino_dude folder so I could test it?

**Comment by Zigrino** [comment]
[dino_dude.zip](https://github.com/siduck76/NvChad/files/6728317/dino_dude.zip)

**Comment by Zigrino** [comment]
I don't think it's the issue with the files though, whenever I open neovim there is no color scheme.

![Screen Shot 2021-06-28 at 1 56 27 PM](https://user-images.githubusercontent.com/56608462/123682183-abea3600-d818-11eb-825b-c7af99c84d67.png)

**Comment by siduck76** [comment]
@Zigrino read the wiki , nvchad makes neovim take bg color from the terminal so if your iterm is black then neovim is black.

**Comment by siduck76** [comment]
road.py syntax looks ok 

![image](https://user-images.githubusercontent.com/59060246/123682777-12974000-d869-11eb-827e-d3cf12c87c69.png)

**Comment by Zigrino** [comment]
Oh, sorry. Thanks for helping me out! I got it to work.
![Screen Shot 2021-06-28 at 3 09 03 PM](https://user-images.githubusercontent.com/56608462/123690878-eeb10b80-d822-11eb-85dc-e8ff21a64821.png)

**Comment by siduck76** [comment]
@Zigrino but the main.py doesnt have proper syntax highlighting :(
