### ISSUE TITLE
Error with python autocompletation

### ISSUE THREAD

**Issue by marbinuwusito** [siduck76/NvChad#99]
![Screenshot_20210626_143239](https://user-images.githubusercontent.com/72583007/123525044-6815f600-d68b-11eb-96d8-b17fe209eeeb.png)
This happen when I press TAB in a completed key word, then lsp server doesn't work anymore and the autocomplete puts a 0 in the code
![imagen](https://user-images.githubusercontent.com/72583007/123525070-93004a00-d68b-11eb-887a-0017c968938d.png)

**Comment by siduck76** [comment]
which lsp server are you using?

**Comment by marbinuwusito** [comment]
python, really idk xd, I just installed it with `LspInstall python`

**Comment by siduck76** [comment]
> python, really idk xd, I just installed it with `LspInstall python`

Idk python so give me the code , I'll test it.

**Comment by marbinuwusito** [comment]
sorry, what code?, this happens in every .py file :(

**Comment by siduck76** [comment]
@marbinuwusito I just tested it now and works fine asf buddy!!
 
 
![image](https://user-images.githubusercontent.com/59060246/123531419-fb016f80-d721-11eb-8a68-72a58f104985.png)

**Comment by marbinuwusito** [comment]
oh :(, maybe I messed up something, thanks for your time c:

**Comment by siduck76** [comment]
@marbinuwusito you sure you dide :PackerSync and :PackerCompile? recently a lot has changed on NvChad!!!

**Comment by marbinuwusito** [comment]
My man, thank you so much c:!
